apache/ignite-3

modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java, modules/metastorage-server/src/main/java/org/apache/ignite/internal/metastorage/server/Operation.java
Added `IgniteUtils.toHexString()` methods (actually copied from AI 2.x and renamed).
`Operation` constructor's assertion will print `key` and `val` as hex string.
=> IGNITE-14754 Improved assertion message in meta storage server operation.

modules/client-handler/src/test/java/org/apache/ignite/client/handler/ClientHandlerIntegrationTest.java, modules/client/src/test/java/org/apache/ignite/client/AbstractClientTest.java, modules/client/src/test/java/org/apache/ignite/client/ConnectionTest.java
Connect to the actual server port, do not assume 10800: server can bind to any port from the range.
=> IGNITE-15237 Thin 3.0: Fix ClientHandlerIntegrationTest flakiness

modules/metastorage-client/src/integrationTest/java/org/apache/ignite/internal/metastorage/client/ITMetaStorageServicePersistenceTest.java, modules/metastorage-client/src/integrationTest/java/org/apache/ignite/internal/metastorage/client/ITMetaStorageServiceTest.java, modules/metastorage-server/pom.xml, modules/metastorage-server/src/main/java/org/apache/ignite/internal/metastorage/server/KeyValueStorage.java, modules/metastorage-server/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDBKeyValueStorage.java, modules/metastorage-server/src/test/java/org/apache/ignite/internal/metastorage/server/AbstractKeyValueStorageTest.java, modules/metastorage-server/src/test/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/MetaStorageManager.java, modules/runner/pom.xml, modules/runner/src/integrationTest/java/org/apache/ignite/internal/storage/ITDistributedConfigurationStorageTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, parent/pom.xml
https://issues.apache.org/jira/browse/IGNITE-15456
1. `SimpleKeyValueStorage` is moved to the `test` folder.
2. `RocksDbKeyValuesStorage` is used when creating `IgniteImpl` instances.
=> IGNITE-15456 Integrate RocksDBKeyValueStorage into the production code

modules/api/src/main/java/org/apache/ignite/table/TupleImpl.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTableCommon.java, modules/client/src/test/java/org/apache/ignite/client/CustomTuple.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/registry/UpgradingRowAdapter.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/row/Row.java, modules/table/src/main/java/org/apache/ignite/internal/table/AbstractRowTupleAdapter.java, modules/table/src/main/java/org/apache/ignite/internal/table/MutableRowTupleAdapter.java, modules/table/src/test/java/org/apache/ignite/internal/table/MutableRowTupleAdapterTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/impl/TestTupleBuilder.java, modules/table/src/test/java/org/apache/ignite/table/TupleImplTest.java
https://issues.apache.org/jira/browse/IGNITE-15519
I'm not sure we must force Tuple interface being Serializable, but user may want/need to send tuple over network.
In this case we must preserve internal state from being serialized, which also reduces tuple footprint.
=> IGNITE-15519: Make tuples serializable

modules/api/src/main/java/org/apache/ignite/table/KeyValueView.java, modules/api/src/main/java/org/apache/ignite/table/TableView.java, modules/platforms/dotnet/Apache.Ignite.Benchmarks/Program.cs, modules/platforms/dotnet/Apache.Ignite.Benchmarks/Proto/WriteGuidBenchmarks.cs, modules/platforms/dotnet/Apache.Ignite.Benchmarks/Table/TupleGetBenchmarks.cs, modules/platforms/dotnet/Apache.Ignite.Tests/IgniteTestsBase.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/CustomTestIgniteTuple.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/IgniteTupleTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/TableTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/TablesTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Buffers/PooledArrayBufferWriter.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/MessagePackReaderExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Table.cs, modules/platforms/dotnet/Apache.Ignite/Table/ITableView.cs, modules/platforms/dotnet/Apache.Ignite/Table/IgniteTuple.cs, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/Storage.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/basic/ConcurrentHashMapStorage.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/AbstractStorageTest.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/PartitionCommandListenerTest.java
* Add and implement all known methods in `ITableView`.
* Fix NPE in `InternalTableImpl`: `getAll`, `insertAll`, `deleteAll`. Reuse multirow processing logic.
* Invert `Storage#removeAll` and `removeAllExact` logic: return skipped rows so that `deleteAll`/`deleteAllExact` public API works as specified in the Javadoc.
* Refactor `Storage` to accept `List` instead of `Collection` to simplify implementation and reduce allocations.
=> IGNITE-15430 .NET: Add Table API

modules/api/src/main/java/org/apache/ignite/table/Tuple.java, modules/api/src/main/java/org/apache/ignite/table/TupleImpl.java, modules/client/src/test/java/org/apache/ignite/client/ClientTupleTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/MutableRowTupleAdapter.java, modules/table/src/test/java/org/apache/ignite/internal/benchmarks/TupleMarshallerFixlenOnlyBenchmark.java, modules/table/src/test/java/org/apache/ignite/internal/benchmarks/TupleMarshallerVarlenOnlyBenchmark.java, modules/table/src/test/java/org/apache/ignite/internal/table/MutableRowTupleAdapterTest.java, modules/table/src/test/java/org/apache/ignite/table/TupleImplTest.java
https://issues.apache.org/jira/browse/IGNITE-15382
Finnaly, TupleImpl was made a package-private to restrict user access.
TupleImpl left in ignite-api module and can be reused in table and/or client module via using public factory methods.
=> IGNITE-15382 Decouple API and implementation for Tuple

modules/platforms/dotnet/Apache.Ignite.Tests/JavaServer.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/PlatformTestNodeRunner.java
`mvn exec` downloads artifacts on the first run, which may cause node start timeout when the network is slow. Perform a separate, dry run of the command with a bigger timeout to download artifacts and compile the code with a bigger timeout (5 minutes). Then start the node with a smaller timeout.
=> IGNITE-15670 .NET: Fix ClientSocketTests flakiness

modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientMessageCommon.java, modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientMessagePacker.java, modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientMessageUnpacker.java, modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientMsgPackType.java, modules/client-common/src/test/java/org/apache/ignite/internal/client/proto/ClientMessagePackerUnpackerTest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTableCommon.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTable.java, modules/client/src/test/java/org/apache/ignite/client/AbstractClientTableTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientTableTest.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeIgniteTables.java, modules/platforms/dotnet/Apache.Ignite.Tests/Proto/MessagePackExtensionsTest.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/ClientMessagePackType.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/MessagePackReaderExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/MessagePackWriterExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/ProtoCommon.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Table.cs
Ignite Table API handles "column set to null" (1) and "column not set" (2) differently.
* Non-nullable column does not allow (1), but allows (2) as long as there is a default value.
* Nullable column will be set to null in (1) and to default value in (2).
Add a new data type `NO_VALUE` to the protocol to reflect this distinction.
=> IGNITE-16093 Thin client: Handle absent and null values differently

modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTableCommon.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientKeyValueView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientRecordSerializer.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientRecordView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTable.java, modules/client/src/test/java/org/apache/ignite/client/AbstractClientTableTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientKeyValueBinaryViewTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientKeyValueViewTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientRecordViewTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientTableTest.java
* Extract record serialization logic into `ClientRecordSerializer`.
* Implement `KeyValueView` in thin client.
=> IGNITE-16121 Thin client: Implement KeyValueView

modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientMessagePacker.java, modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientMessageUnpacker.java, modules/client-common/src/test/java/org/apache/ignite/internal/client/proto/ClientMessagePackerTest.java, modules/client-common/src/test/java/org/apache/ignite/internal/client/proto/ClientMessageUnpackerTest.java, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/IgniteUuid.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/MessagePackReaderExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/MessagePackWriterExtensions.cs
* `BigDecimal#scale` is usually small and will use 1 byte instead of 4.
* `IgniteUuid.localId` can use 1-5 bytes instead of 8 for small values.
=> IGNITE-15352 Thin client: Use varint for decimal scale and IgniteUuid localId

modules/platforms/dotnet/Apache.Ignite.Tests/IgniteTestsBase.cs, modules/platforms/dotnet/Apache.Ignite.Tests/JavaServer.cs, modules/platforms/dotnet/Apache.Ignite.Tests/RawSocketConnectionTests.cs, modules/platforms/dotnet/DEVNOTES.md
Do not start/stop a new node for every test class, use one for everything, stop on test process exit.
=> IGNITE-16382 .NET: Speed up tests by reusing server node

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/jdbc/ItJdbcConnectionSelfTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItInternalTableScanTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTablePersistenceTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNode.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java, modules/table/src/test/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
1. TODO "IGNITE-15188" was just not deleted after the task was closed. So simply remove it.
2. TODO "IGNITE-15443" meant having to replace HashMap implementations with primitive IntMap in Table module. Since the task was not finished, this feed contains the corresponding edits to the module.
=> IGNITE-16311 Removed redundant mentions of closed tasks in code. 

modules/cli/src/main/java/org/apache/ignite/cli/builtins/config/ConfigurationClient.java, modules/cli/src/test/java/org/apache/ignite/cli/IgniteCliInterfaceTest.java, modules/rest/src/main/java/org/apache/ignite/internal/rest/RestModule.java, modules/rest/src/main/java/org/apache/ignite/internal/rest/routes/Router.java, modules/rest/src/test/java/org/apache/ignite/internal/rest/routes/RouteTest.java
https://issues.apache.org/jira/browse/IGNITE-16487
=> IGNITE-16487 Use PATCH HTTP verb instead of PUT for modifying cluster/node configuration

modules/client/src/test/java/org/apache/ignite/client/HeartbeatTest.java, modules/platforms/dotnet/Apache.Ignite.Tests.ruleset, modules/platforms/dotnet/Apache.Ignite.Tests/ClientSocketTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/HeartbeatTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/IgniteTestsBase.cs, modules/platforms/dotnet/Apache.Ignite.Tests/ListLogger.cs, modules/platforms/dotnet/Apache.Ignite.Tests/RawSocketConnectionTests.cs, modules/platforms/dotnet/Apache.Ignite/IgniteClientConfiguration.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientFailoverSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/ClientOp.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/ClientOpExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Log/LoggerExtensions.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/PlatformTestNodeRunner.java
Implement keepalive in .NET client: https://cwiki.apache.org/confluence/display/IGNITE/IEP-83+Thin+Client+Keepalive
* Add `IgniteClientConfiguration.HeartbeatInterval`, default 30 seconds. Heartbeats are always enabled (no need to disable like in 2.x).
* Set effective heartbeat interval to `Math.Min(HeartbeatInterval, IdleTimeout / 3)`. Log warning when user-defined value is overridden.
=> IGNITE-16531 .NET: Thin client: add heartbeats

modules/api/src/main/java/org/apache/ignite/Ignite.java, modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientMessagePacker.java, modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientMessageUnpacker.java, modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientOp.java, modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/ItClientHandlerTest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientHandlerModule.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/cluster/ClientClusterGetNodesRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/compute/ClientComputeExecuteRequest.java, modules/client/src/main/java/org/apache/ignite/internal/client/TcpIgniteClient.java, modules/client/src/main/java/org/apache/ignite/internal/client/compute/ClientCompute.java, modules/client/src/test/java/org/apache/ignite/client/TestServer.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeIgnite.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/IgniteComputeImpl.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientComputeTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
* Implement `IgniteCompute` interface.
* `execute` and `broadcast` use the same `ClientOp#COMPUTE_EXECUTE`.
* For now all operations go through the default node; cluster awareness to be implemented separately (IGNITE-16771).
* Add temporary `Ignite#clusterNodes` to enable Compute usage while Cluster API is not available.
=> IGNITE-16734 Java thin: Add Compute

modules/api/src/main/java/org/apache/ignite/Ignite.java, modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs, modules/platforms/dotnet/Apache.Ignite/ClientOperationType.cs, modules/platforms/dotnet/Apache.Ignite/Compute/ICompute.cs, modules/platforms/dotnet/Apache.Ignite/IIgnite.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Common/ThreadLocalRandom.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Compute/Compute.cs, modules/platforms/dotnet/Apache.Ignite/Internal/IgniteClientInternal.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Network/ClusterNode.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/ClientOp.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/ClientOpExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/MessagePackReaderExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/MessagePackWriterExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Network/IClusterNode.cs, modules/platforms/dotnet/Apache.Ignite/RetryReadPolicy.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/PlatformTestNodeRunner.java
* Add and implement `ICompute` interface. 
* For now all operations go through the default node; cluster awareness to be implemented separately (IGNITE-16823). 
* Add temporary `IIgnite.GetClusterNodes` to enable Compute usage while Cluster API is not available.
=> IGNITE-16735 .NET: Add Compute

modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientResourceRegistry.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTableCommon.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/tx/ClientTransactionBeginRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/tx/ClientTransactionCommitRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/tx/ClientTransactionRollbackRequest.java, modules/client-handler/src/test/java/ClientResourceRegistryTest.java
Guard `ClientResourceRegistry` with an `RwLock` so that new resources can't be added to a closed registry.
=> IGNITE-16776 Thin client: Fix potential resource leak on disconnect

modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/compute/ClientComputeExecuteRequest.java, modules/client/src/main/java/org/apache/ignite/internal/client/ProtocolContext.java, modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/compute/ClientCompute.java, modules/client/src/main/java/org/apache/ignite/internal/client/io/ClientConnection.java, modules/client/src/main/java/org/apache/ignite/internal/client/io/netty/NettyClientConnection.java, modules/client/src/test/java/org/apache/ignite/client/TestClientHandlerModule.java, modules/client/src/test/java/org/apache/ignite/client/TestServer.java, modules/platforms/dotnet/Apache.Ignite.Tests.ruleset, modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeClusterAwarenessTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/FakeServer.cs, modules/platforms/dotnet/Apache.Ignite.Tests/RawSocketConnectionTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/TestUtils.cs, modules/platforms/dotnet/Apache.Ignite/IIgnite.cs, modules/platforms/dotnet/Apache.Ignite/IIgniteClient.cs, modules/platforms/dotnet/Apache.Ignite/IgniteClient.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientFailoverSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Compute/Compute.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ConnectionContext.cs, modules/platforms/dotnet/Apache.Ignite/Internal/IgniteClientInternal.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Schema.cs
* Include node id and name into handshake response.
* Establish connections to all known endpoints in background.
* During Compute calls, match target node name against active connections and send request directly to the correct node when possible.
=> IGNITE-16823 .NET: Add cluster awareness to Compute

modules/api/src/main/java/org/apache/ignite/network/ClusterNode.java, modules/client/src/main/java/org/apache/ignite/client/IgniteClient.java, modules/client/src/main/java/org/apache/ignite/internal/client/ClientChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/ReliableChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/TcpIgniteClient.java, modules/client/src/main/java/org/apache/ignite/internal/client/compute/ClientCompute.java, modules/client/src/test/java/org/apache/ignite/client/ClientComputeTest.java, modules/client/src/test/java/org/apache/ignite/client/RetryPolicyTest.java, modules/client/src/test/java/org/apache/ignite/client/TestClientHandlerModule.java, modules/client/src/test/java/org/apache/ignite/client/TestServer.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientConnectionTest.java
* Establish connections to all known endpoints in background.
* During Compute calls, match target node name against active connections and send request directly to the correct node when possible.
=> IGNITE-16771 Thin client: Add cluster awareness to Compute

modules/network/src/main/java/org/apache/ignite/internal/network/serialization/ClassDescriptorFactory.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshaller.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/ExternalizableMarshaller.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/SchemaMismatchHandler.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/SchemaMismatchHandlers.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/UosObjectInputStream.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/UosObjectOutputStream.java, modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultSchemaMismatchHandlerTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerWithExternalizableTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerWithSchemaChangeTest.java
https://issues.apache.org/jira/browse/IGNITE-16573
=> IGNITE-16573 Support schema changes concerning externalizability status

modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/IgniteTestsBase.cs, modules/platforms/dotnet/Apache.Ignite.Tests/RawSocketConnectionTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/RecordViewBinaryTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/RecordViewPocoTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/TablesTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Transactions/TransactionsTests.cs, modules/platforms/dotnet/Apache.Ignite/ClientErrorCode.cs, modules/platforms/dotnet/Apache.Ignite/Compute/ICompute.cs, modules/platforms/dotnet/Apache.Ignite/IgniteClientException.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Compute/Compute.cs, modules/platforms/dotnet/Apache.Ignite/Internal/IgniteClientInternal.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/ClientOp.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/ClientOpExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/RecordView.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/RecordSerializer.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Table.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Tables.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/PlatformTestNodeRunner.java
* Implement `ExecuteColocated` in .NET client. Send requests to default node, partition awareness will be added later (IGNITE-16930).
* To avoid extra table request on every `ExecuteColocated` call (we need table id and schemas), cache tables by name. If a table gets dropped and created again with the same name and a different id, retry the operation.
=> IGNITE-16930 .NET: Thin 3.0: Add Compute.ExecuteColocated

modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/raft/ItCmgRaftServiceTest.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListener.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftService.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/RaftStorageManager.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/ValidationManager.java, modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListenerTest.java, modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/ConcurrentMapClusterStateStorage.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/runner/src/main/java/org/apache/ignite/internal/app/LifecycleManager.java
https://issues.apache.org/jira/browse/IGNITE-17100
=> IGNITE-17100 Make JoinReady command idempotent

modules/api/src/main/java/org/apache/ignite/configuration/schemas/table/TableConfigurationSchema.java, modules/api/src/main/java/org/apache/ignite/configuration/schemas/table/TablesConfigurationSchema.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStoreManager.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStoreManagerTest.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/configuration/SchemaConfigurationConverterTest.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/StorageUtils.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/PageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryPartitionStorageTest.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageEngine.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-16665
=> IGNITE-16665 Introduced integer table id.

modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorage.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorageTest.java
* "Destroy" method returns a future that completes after the data is flushed
* Storage is closed after "destroy" is called
* FlushOptions are cached in RocksDbTableStorage so that they do not get GC-ed
https://issues.apache.org/jira/browse/IGNITE-17500
=> IGNITE-17500 Fix minor issues in RocksDB-based partition storages

modules/cli/src/main/java/org/apache/ignite/cli/config/ConfigConstants.java
https://issues.apache.org/jira/browse/IGNITE-17529
Allow changing config file path, which is now determined by the XDG spec.
=> IGNITE-17529 Override CLI config file path via environment variable

modules/cli/src/integrationTest/java/org/apache/ignite/cli/deprecated/ItConfigCommandTest.java, modules/cli/src/main/java/org/apache/ignite/cli/commands/cluster/config/ClusterConfigShowReplSubCommand.java, modules/cli/src/main/java/org/apache/ignite/cli/commands/cluster/config/ClusterConfigShowSubCommand.java, modules/cli/src/main/java/org/apache/ignite/cli/commands/node/config/NodeConfigShowReplSubCommand.java, modules/cli/src/main/java/org/apache/ignite/cli/commands/node/config/NodeConfigShowSubCommand.java, modules/cli/src/main/java/org/apache/ignite/cli/core/repl/completer/DynamicCompleterActivationPoint.java, modules/cli/src/main/java/org/apache/ignite/cli/core/repl/completer/HoconDynamicCompleter.java, modules/cli/src/test/java/org/apache/ignite/cli/core/repl/completer/DynamicCompleterFilterTest.java, modules/cli/src/test/java/org/apache/ignite/cli/core/repl/completer/HoconDynamicCompleterTest.java, modules/cli/src/test/java/org/apache/ignite/cli/deprecated/IgniteCliInterfaceTest.java
https://issues.apache.org/jira/browse/IGNITE-17528
This drops the `--selector` option in `config show` commands and allow similar UX as `config update` commands so that the user can write `node config show network` rather than `node config show --selector network`.
=> IGNITE-17528 Use parameter instead of option in config show commands

modules/client/src/main/java/org/apache/ignite/internal/client/ReliableChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/compute/ClientCompute.java
Flakiness is caused by a race:
* `ClientChannelHolder.getOrCreateChannel` sets `ch` then updates `nodeChannels`.
* `IgniteClient.connections()` (used by the test to wait for connections to establish) uses `holder.ch`.
* `ReliableChannel.handleServiceAsync()` uses `nodeChannels` to send request to proper node.
As a result, it was possible that `connections()` return new connections, but `handleServiceAsync()` does not yet see them, sending the request to the default node.
Fixed by using `nodeChannels` in `IgniteClient.connections()`.
=> IGNITE-17402 Fix testClientSendsComputeJobToTargetNodeWhenDirectConnectionExists flakiness

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItAbstractThinClientTest.java
Wait for background client connections to be established.
=> IGNITE-17491 Fix testIgniteExceptionInJobPropagatesToClientWithMessageAndCodeAndTraceId flakiness

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/RocksDbClusterStateStorage.java, modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/AbstractClusterStateStorageTest.java, modules/core/src/main/java/org/apache/ignite/internal/util/ByteUtils.java, modules/core/src/main/java/org/apache/ignite/internal/util/Cursor.java, modules/core/src/main/java/org/apache/ignite/internal/util/HashUtils.java, modules/core/src/test/java/org/apache/ignite/internal/util/HashUtilsTest.java, modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/ColumnFamily.java, modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/RocksIteratorAdapter.java, modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/RocksUtils.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/BinaryTupleParser.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/MvTableStorage.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/HashIndexDescriptor.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/HashIndexStorage.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/SortedIndexDescriptor.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/chm/TestConcurrentHashMapMvTableStorage.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/index/AbstractHashIndexStorageTest.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/index/AbstractSortedIndexStorageTest.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/index/TestSortedIndexStorageTest.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/index/impl/TestHashIndexStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/AbstractPageMemoryTableStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/ColumnFamilyUtils.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbDataRegion.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMetaStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbHashIndexStorage.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbHashIndexStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-17338
=> IGNITE-17338 Implement RocksDB hash index storage

modules/core/src/test/java/org/apache/ignite/internal/testframework/IgniteTestUtils.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientComputeTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientConnectionTest.java
* Use the same `testNodeName` on Windows and Linux.
* Make it shorter to avoid hitting Windows MAX_PATH limit.
https://issues.apache.org/jira/browse/IGNITE-17596
=> IGNITE-17596 ItThinClientComputeTest fails on Windows

modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientKeyValueBinaryView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientKeyValueView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientRecordBinaryView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientRecordView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTable.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTupleSerializer.java, modules/client/src/test/java/org/apache/ignite/client/PartitionAwarenessTest.java, modules/client/src/test/java/org/apache/ignite/client/RetryPolicyTest.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeInternalTable.java
* Move common hash calculation logic to `ClientTupleSerializer`.
* Add partition awareness to all APIs in `ClientRecordView`, `ClientRecordBinaryView`, `ClientKeyValueView`, `ClientKeyValueBinaryView`.
https://issues.apache.org/jira/browse/IGNITE-17739
=> IGNITE-17739 Add Partition Awareness to all table APIs in Java client 

modules/client/src/main/java/org/apache/ignite/client/ClientOperationType.java, modules/client/src/main/java/org/apache/ignite/client/RetryReadPolicy.java, modules/client/src/main/java/org/apache/ignite/internal/client/ReliableChannel.java, modules/client/src/test/java/org/apache/ignite/client/AbstractClientTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientComputeTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientLoggingTest.java, modules/client/src/test/java/org/apache/ignite/client/PartitionAwarenessTest.java, modules/client/src/test/java/org/apache/ignite/client/ReconnectTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItAbstractThinClientTest.java
Introduce `ClientOperationType.CHANNEL_CONNECT` and pass it to `RetryPolicy` when performing connection attempts.
Fixes `testRetryReadPolicyRetriesReadOperations` flakiness caused by failed handshake.
=> IGNITE-17763 Use retry policy when connecting default channel

modules/platforms/dotnet/Apache.Ignite.Internal.Generators/Apache.Ignite.Internal.Generators.csproj, modules/platforms/dotnet/Apache.Ignite.Internal.Generators/ErrorGroupsGenerator.cs, modules/platforms/dotnet/Apache.Ignite.Internal.Generators/ExceptionsGenerator.cs, modules/platforms/dotnet/Apache.Ignite.Internal.Generators/JavaToCsharpGeneratorBase.cs
Generate code only on build. Do not generate when C# code changes, because the logic is based only on Java code. Fixes potentially degraded IDE performance due to unnecessary processing.
=> IGNITE-17794 .NET: Fix source generators performance

modules/client/src/main/java/org/apache/ignite/client/RetryReadPolicy.java, modules/client/src/main/java/org/apache/ignite/internal/client/ReliableChannel.java, modules/client/src/test/java/org/apache/ignite/client/RetryPolicyTest.java, modules/client/src/test/java/org/apache/ignite/client/TestRetryPolicy.java
Fix API call hang when there is an exception in `RetryPolicy` implementation. Catch exceptions and propagate to the caller.
=> IGNITE-17812 Fix RetryPolicy exception handling, propagate exceptions to API caller

modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/SqlReplCommand.java
https://issues.apache.org/jira/browse/IGNITE-17782
Picocli treats white space as a positional argument and creates a arg group object, so we need to add a check for this.
=> IGNITE-17782 `sql` with white space in repl fails

modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/platforms/dotnet/Apache.Ignite.Internal.Generators/ExceptionsGenerator.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientSocket.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/PlatformTestNodeRunner.java
* Read Java exception stack trace from server (when present) and include it in the `InnerException`.
* Fix logging in `ClientInboundMessageHandler`.
=> IGNITE-17826 .NET: Propagate Java exception stack traces

modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientMessagePacker.java, modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientMessageUnpacker.java, modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Proto/MessagePackExtensionsTest.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/UuidSerializer.cs
* Use the same little-endian UUID format in MessagePack and BinaryTuple.
* Fix .NET Guid to match Java UUID format so that string representation is the same (important for debugging and logging).
=> IGNITE-17830 .NET: Fix Guid serialization to match UUID

modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/OptionTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Sql/SqlTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/PocoStruct.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/RecordViewBinaryTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/RecordViewDefaultMappingTest.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/RecordViewPocoTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/Serialization/ObjectSerializerHandlerTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Transactions/TransactionsTests.cs, modules/platforms/dotnet/Apache.Ignite/Apache.Ignite.csproj, modules/platforms/dotnet/Apache.Ignite/Compute/ICompute.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Common/IgniteArgumentCheck.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Compute/Compute.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Sql/Sql.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/RecordView.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/IRecordSerializerHandler.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/ObjectSerializerHandler.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/RecordSerializer.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Table.cs, modules/platforms/dotnet/Apache.Ignite/Option.cs, modules/platforms/dotnet/Apache.Ignite/Sql/IResultSet.cs, modules/platforms/dotnet/Apache.Ignite/Sql/ISql.cs, modules/platforms/dotnet/Apache.Ignite/Table/IRecordView.cs, modules/platforms/dotnet/Apache.Ignite/Table/ITable.cs
* Remove `where T : class` constraint from all APIs.
* Use `Option<T>` as a return type for APIs which can return "no value" results, such as `Get`, `GetAndUpsert`, `GetAndDelete`.
* It is not possible to handle nullable value and reference types in a generic way, so we have to use a common wrapper. `Option<T>` also clearly indicates which APIs always return something and which don't.
* Fix `ObjectSerializerHandler` to support value types.
=> IGNITE-16355 .NET: Support value types in the Table API

modules/core/src/main/java/org/apache/ignite/internal/future/OrderingFuture.java, modules/core/src/test/java/org/apache/ignite/internal/future/OrderingFutureConcurrencyTest.java, modules/core/src/test/java/org/apache/ignite/internal/future/OrderingFutureTest.java
https://issues.apache.org/jira/browse/IGNITE-17881
=> IGNITE-17881 OrderingFuture should notify dependents asynchronously

packaging/build.gradle, packaging/docker/ignite.java.util.logging.properties, packaging/linux/start.sh
https://issues.apache.org/jira/browse/IGNITE-17879
Docker image doesn't need replace tokens task so split the CopySpec again and customize it for the docker.
Also the docker container should log the output to the console so the previous logging.properties is restored for it.
Start script for DEB/RPM was missing the --node-name argument.
=> IGNITE-17879 Packaging is broken

modules/platforms/dotnet/Apache.Ignite.Tests/JavaServer.cs
* Use `Process.Kill(entireProcessTree: true)` to ensure Java node termination after tests.
* Increase Java node startup timeout.
=> IGNITE-17901 .NET: Fix Java server termination, increase timeout

modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlExecuteRequest.java, modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/ListLogger.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Sql/SqlTests.cs, modules/platforms/dotnet/Apache.Ignite/Compute/ICompute.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Compute/Compute.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/MessagePackWriterExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Sql/Sql.cs, modules/platforms/dotnet/Apache.Ignite/Log/CategoryLogger.cs, modules/platforms/dotnet/Apache.Ignite/Log/ConsoleLogger.cs, modules/platforms/dotnet/Apache.Ignite/Log/IIgniteLogger.cs, modules/platforms/dotnet/Apache.Ignite/Log/LoggerExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Sql/ISql.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientComputeTest.java
Change `params object[] args` to `params object?[]? args` in all public APIs.
=> IGNITE-17840 .NET: Allow null args in SQL and Compute

modules/storage-api/src/main/java/org/apache/ignite/internal/storage/MvPartitionStorage.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/ReadResult.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java
https://issues.apache.org/jira/browse/IGNITE-17968
=> IGNITE-17968 Fix write-intents being filtered out in case if it's a tombstone

modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTupleSerializer.java, modules/core/src/main/java/org/apache/ignite/internal/util/HashCalculator.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/row/Row.java, modules/schema/src/main/java/org/apache/ignite/internal/util/ColocationUtils.java, modules/table/src/test/java/org/apache/ignite/internal/table/ColocationHashCalculationTest.java
Use toByteArray instead of conversion to double to make the logic portable to other languages.
=> IGNITE-17994 Use toByteArray for colocation hash of BigDecimal and BigInteger

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDataTypesTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlQueryProcessor.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/StopCalciteModuleTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/MockedStructuresTest.java
https://issues.apache.org/jira/browse/IGNITE-18004
=> IGNITE-18004 Compilation fixed, test disabled.

gradle.properties, settings.gradle
* Optimization and fix for race cache modification
https://issues.apache.org/jira/browse/IGNITE-17965
=> IGNITE-17965: Enable remote build cache for Gradle build on CI.

modules/platforms/dotnet/Apache.Ignite.Tests/Table/PocoCustomColumnMapping.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/RecordViewCustomMappingTest.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/ObjectSerializerHandler.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/ReflectionUtils.cs
Support custom column names with a standard `System.ComponentModel.DataAnnotations.Schema.ColumnAttribute` when mapping user-defined types to Ignite columns in `RecordView<T>` and `KeyValueView<T>`.
=> IGNITE-16356 .NET: Add mapped column name customization with ColumnAttribute

modules/platforms/dotnet/Apache.Ignite.Internal.Generators/ErrorGroupsGenerator.cs
Replace `static readonly int` with `const int` in generated error codes - constants work better in pattern matching scenarios.
=> IGNITE-18059 .NET: Convert error codes to constants

modules/platforms/dotnet/Apache.Ignite.Tests/FakeServer.cs, modules/platforms/dotnet/Apache.Ignite.Tests/ListLogger.cs, modules/platforms/dotnet/Apache.Ignite.Tests/SocketTimeoutTest.cs, modules/platforms/dotnet/Apache.Ignite/IgniteClientConfiguration.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientFailoverSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientSocket.cs
If the server does not respond to the initial handshake message or a periodic heartbeat in the specified time, close the connection with a `TimeoutException`.
=> IGNITE-18058 .NET: Add timeout for handshake and heartbeats

modules/network/src/main/java/org/apache/ignite/network/MessageSerializationRegistryImpl.java, modules/network/src/test/java/org/apache/ignite/network/serialization/MessageSerializationRegistryImplTest.java
https://issues.apache.org/jira/browse/IGNITE-17775
Here, we just make the behavior between passing a negative group/messageType and passing an unknown group/messageType consistent. For further developments, see IGNITE-18072.
=> IGNITE-17775 Invalid data in network buffers causes message deserialization errors and messages loss

modules/client/src/main/java/org/apache/ignite/internal/client/ReliableChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/compute/ClientCompute.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTable.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTupleSerializer.java, modules/client/src/test/java/org/apache/ignite/client/PartitionAwarenessTest.java
Send `executeColocated` request to the target node if a direct connection exists.
=> IGNITE-16925 Java thin: Add partition awareness to executeColocated

modules/configuration-api/src/main/java/org/apache/ignite/configuration/annotation/PolymorphicConfig.java, modules/configuration-api/src/main/java/org/apache/ignite/configuration/annotation/PolymorphicId.java, modules/configuration/README.md, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/asm/ConfigurationAsmGenerator.java
- This PR fixes the flaky test `org.apache.ignite.internal.configuration.asm.ConfigurationAsmGeneratorTest.testPolymorphicErrors`
- The mentioned test may fail or pass without changes made to the source code when it is run in different JVMs due to `Class#getDeclaredFields`'s non-deterministic output order.
- According to [Java documentation](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getDeclaredFields--) about `getDeclaredFields`, returned array are not sorted and are not in any particular order.
- `ConfigurationUtil#schemaFields()` uses `getDeclaredFields` to return the list of schema fields. This list is passed to `ConfigurationAsmGenerator#createNodeClass()` and then passed to `ConfigurationAsmGenerator#addNodeTraverseChildrenMethod()`.  In this method at line 1249, …
=> IGNITE-18080 Fix flaky test failure in ConfigurationAsmGeneratorTest#testPolymorphicErrors

packaging/build.gradle
https://issues.apache.org/jira/browse/IGNITE-17918
There wasn't dependency on configurations declared in allDistZip. That's why we needed a workaround copy task.
=> IGNITE-17918 Fix uber zip task dependencies

modules/platforms/dotnet/Apache.Ignite.Internal.Generators/ExceptionsGenerator.cs, modules/platforms/dotnet/Apache.Ignite.Tests/PartitionAwarenessTests.cs
Generated classes may be present multiple times in build artifacts, which breaks .NET build. Skip them - we don't need those classes.
=> IGNITE-18133 .NET: Ignore CLI module and build artifacts in ExceptionsGenerator

modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqSqlGenerationTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/Poco.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/PocoCustomNames.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/Serialization/ReflectionUtilsTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Linq/DEVNOTES.md, modules/platforms/dotnet/Apache.Ignite/Internal/Linq/IgniteQueryExpressionVisitor.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/ReflectionUtils.cs
* When generating `SELECT` clause, instead of `*`, emit only mapped column names. For example, if a table has 10 columns, but LINQ expression uses a type with 5 properties, only select those 5 columns.
* Handle `[NotMapped]` attribute to allow more control over column mapping.
* Add DEVNOTES to Linq directory with some technical details.
=> IGNITE-18138 .NET: LINQ: Avoid overfetching, select only mapped columns

modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqSqlGenerationTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.Aggregate.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Sql/SqlTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Common/StringBuilderExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Linq/IgniteQueryExecutor.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Linq/IgniteQueryModelVisitor.cs
* Add support and tests for Sum, Count, Min, Max, Average, Count, Any, All.
* Ported 2.x code supports most of that, but Any and All had to be reworked to use SQL `EXISTS`.
* Fix result set type conversion logic.
=> IGNITE-18196 .NET: LINQ: Add aggregates support

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItAggregatesTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlConformance.java
Enable `isGroupByAlias` and `isGroupByOrdinal` in SQL conformance.
=> IGNITE-18212 Fix parsing error on GROUP BY with alias

build.gradle, buildscripts/java-core.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
* Disable build cache for test tasks
* Move build cache enabling to CI
* Specify path to checkstyle report generation
https://issues.apache.org/jira/browse/IGNITE-18110
=> IGNITE-18110 Modernize Gradle cache usage

modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqSqlGenerationTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.Aggregate.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.Cast.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.GroupBy.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.Join.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Sql/SqlColumnTypeExtensionsTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Linq/IgniteQueryExpressionVisitor.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Linq/IgniteQueryModelVisitor.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Sql/SqlColumnTypeExtensions.cs
* Unlike Ignite 2.x, we can't rely on SQL engine to perform type conversion in many cases. Emit explicit SQL `cast` when required.
* Remove redundant whitespace in generated SQL.
* Improve `ToSqlTypeName`.
=> IGNITE-18257 .NET: LINQ: Implement type casts

modules/sql-engine/src/main/codegen/config.fmpp, modules/sql-engine/src/main/codegen/includes/parserImpls.ftl, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlCreateZone.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlCreateZoneOption.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlCreateZoneOptionEnum.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlDropZone.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/AbstractDdlParserTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/SqlDdlParserTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/SqlDdlZoneParserTest.java
Basic SQL grammar to CREATE/DROP distributed zones.
It was decided not to overload the parser with complex validation logic of command options (it should be implemented somewhere near the conversion level).
Thus, currently the parser is not responsible for invalid (unknown) options, invalid option invariants, and duplicates.
=> IGNITE-18156 Sql. Extend SQL grammar with CREATE/DROP ZONE statement.

modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqSqlGenerationTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Common/StringBuilderExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Linq/IgniteQueryModelVisitor.cs
* Fix subquery handling with `Skip` and `Take`.
* Remove H2-specific workaround.
* Allow combining `Skip` with `First` or `Single`.
=> IGNITE-18123 .NET: LINQ: Improve Skip and Take (offset / limit) support

modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqSqlGenerationTests.KvView.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqSqlGenerationTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.Aggregate.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.Cast.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.GroupBy.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.UnionIntersectExcept.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Linq/AliasDictionary.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Linq/IgniteQueryExpressionVisitor.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Linq/IgniteQueryModelVisitor.cs
* Use column alias when projecting a complex expression into a new type to support some `.Distinct` use cases.
* Add more tests.
=> IGNITE-18131 .NET: LINQ: Improve Distinct support

modules/rest/build.gradle
https://issues.apache.org/jira/browse/IGNITE-18340
Pass a compiler argument to the annotation processor.
=> IGNITE-18340 Gradle build doesn't produce OpenAPI spec

RELEASE.md, modules/platforms/build.gradle, packaging/build.gradle, packaging/cli/build.gradle, packaging/db/build.gradle
https://issues.apache.org/jira/browse/IGNITE-18092
This also combines most of the tasks needed to release into one `prepareRelease` task, which copies artifacts to one directory.
=> IGNITE-18092 Fix zip distribution name providing to sign and checksum tasks

DEVNOTES.md, packaging/build.gradle, packaging/docker/Dockerfile, packaging/docker/docker-compose.yml, packaging/docker/docker-entrypoint.sh
https://issues.apache.org/jira/browse/IGNITE-17920
Simple docker compose file to start an uninitialized 3 nodes cluster.
This also slims docker image by using custom JRE by about 100 MB and adds CLI to the image (which adds about 25 MB back) so it can be run using `docker run apacheignite/ignite3 cli`
=> IGNITE-17920 Develop docker-compose file for Ignite cluster

.idea/inspectionProfiles/Project_Default.xml, modules/client/src/main/java/org/apache/ignite/client/IgniteClient.java, modules/client/src/main/java/org/apache/ignite/client/IgniteClientConfiguration.java, modules/client/src/main/java/org/apache/ignite/internal/client/ClientUtils.java, modules/client/src/main/java/org/apache/ignite/internal/client/IgniteClientConfigurationImpl.java, modules/client/src/main/java/org/apache/ignite/internal/client/ReliableChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/TcpIgniteClient.java, modules/client/src/test/java/org/apache/ignite/client/AbstractClientTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientComputeTest.java, modules/client/src/test/java/org/apache/ignite/client/ConnectionTest.java, modules/client/src/test/java/org/apache/ignite/client/HeartbeatTest.java, modules/client/src/test/java/org/apache/ignite/client/MultiClusterTest.java, modules/client/src/test/java/org/apache/ignite/client/RetryPolicyTest.java, modules/client/src/test/java/org/apache/ignite/client/TestClientHandlerModule.java, modules/client/src/test/java/org/apache/ignite/client/TestServer.java
* Add `IgniteClientConfiguration.heartbeatTimeout`.
* Close connection when there is no response from server to heartbeat message within the specified timeout.
* Minor fixes - add nullable annotations, improve logger handling.
* Add test for `connectTimeout`.
* Fix Netty buffer leak in case of connect timeout.
=> IGNITE-18071 Add client-side heartbeat timeout

RELEASE.md, modules/platforms/build.gradle, packaging/build.gradle, packaging/cli/build.gradle, packaging/db/build.gradle
* Fix dependencies to get rid of Gradle warnings.
* Do not assembly release artifacts (such as .NET binaries) during regular build.
This fix properly declares dependencies between packaging tasks so that Gradle can optimize them correctly and don't complain.
Also this adds a property check for adding release artifacts. The reason is that adding an artifact to the configuration automatically adds a dependency to the `assemble` task so running `gradlew build` always produces artifacts intended only for the release.
https://issues.apache.org/jira/browse/IGNITE-18280
=> IGNITE-18280 Fix dependencies in Gradle packaging tasks

modules/schema/src/main/java/org/apache/ignite/internal/schema/BinaryConverter.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/BinaryConverterTest.java
https://issues.apache.org/jira/browse/IGNITE-18450
`BinaryConverter.toTuple` incorrectly assumed that a bitmask field has variable length.
=> IGNITE-18450 Incorrect conversion of bitmask to binary tuple

modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/PocoEnums.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/RecordViewPocoTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/BinaryTupleMethods.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/ILGeneratorExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/ObjectSerializerHandler.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/ReflectionUtils.cs
* Map integer columns (int8, int16, int32, int64) to .NET enums.
* Includes support in `RecordView`, `KeyValueView`, and LINQ.
=> IGNITE-18435 .NET: Add support for Enum mapping

modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/IgniteTestUtils.java, modules/sql-engine/build.gradle, modules/sql-engine/pom.xml, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlQueryProcessor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/ColumnDescriptorImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/IgniteSchema.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/benchmarks/SqlBenchmark.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImplTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/DataProvider.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/PredefinedSchemaManager.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestBuilders.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestCluster.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestClusterService.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestNode.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestTable.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/AbstractPlannerTest.java
The patch introduces the Test Object Builder framework and repas an example of use as very simple test to measure the performance of the query execution engine in isolation from the overhead introduced by tables and transactions
=> IGNITE-17275 Sql. Performance testing of pure SQL execution

modules/platforms/dotnet/Apache.Ignite.Tests/JavaServer.cs
* `--no-daemon` removed to speed up local test execution
* `IGNITE_DOTNET_GRADLE_OPTS` env var added to TC to keep the existing behavior: https://ci.ignite.apache.org/admin/editBuildParams.html?id=buildType:ApacheIgnite3xGradle_Test_RunNetTests
=> IGNITE-18555 .NET: Enable Gradle daemon in tests

modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqSqlGenerationTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.Aggregate.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.Cast.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.GroupBy.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.Join.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.KvView.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.UnionIntersectExcept.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Linq/AliasDictionary.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Linq/IgniteQueryExpressionVisitor.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Linq/IgniteQueryModelVisitor.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Sql/Sql.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/PlatformTestNodeRunner.java
* When a complex expression (as opposed to a simple column name) is used in `GroupBy`, emit an alias to fix `Expression '_T0.VAL' is not being grouped` SQL parser error.
Extra:
* Remove redundant parenthesis in emitted SQL `ORDER BY`
* Add `TestOrderByMultiple`
* Make `PlatformTestNodeRunner` run time configurable through env var
=> IGNITE-18215 .NET: LINQ: Fix GroupBy with complex expression

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerConfigurationChangesTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerWatchListenerTest.java
https://issues.apache.org/jira/browse/IGNITE-18540
=> IGNITE-18540 Fixed processing of the default distribution zone.

modules/platforms/dotnet/Apache.Ignite.Tests/Proto/BinaryTuple/BinaryTupleTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/BinaryTuple/BinaryTupleReader.cs
* Throw exception instead of returning incorrect value when field payload size has unexpected length.
* Add tests for type compatibility - long can be read as int (if it fits), etc.
=> IGNITE-18588 .NET: Fix BinaryTupleReader behavior on payload size mismatch

modules/platforms/dotnet/Apache.Ignite.Tests/Buffers/ByteArrayPoolTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Linq/ResultSelector.cs
Fix `System.AccessViolationException` when reading nullable value types in LINQ.
No new tests: existing tests cover the use case, but the bug could only be reproduced in Release mode on Linux, or in any mode without a debugger on Windows.
Release mode test run step added to TC: https://ci.ignite.apache.org/buildConfiguration/ApacheIgnite3xGradle_Test_RunNetTests?branch=pull%2F1477&buildTypeTab=overview&mode=builds
=> IGNITE-18626 .NET: Fix nullable result handling in LINQ

modules/platforms/dotnet/Apache.Ignite.Tests/Sql/IgniteDbDataReaderTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Sql/ResultSet.cs, modules/platforms/dotnet/Apache.Ignite/Sql/IgniteDbDataReader.cs
* Fix `IndexOutOfRangeException` when reading empty result set
* Fix `HasRows` to return false for empty result set
* Fix `NextResult` to return false instead of throwing exception
=> IGNITE-18627 .NET: Fix empty result set handling in IgniteDbDataReader

modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.cs
Clean up existing table data to ensure that the same test node can be reused for multiple test runs.
=> IGNITE-18614 .NET: Fix test data cleanup

modules/platforms/dotnet/Apache.Ignite/IgniteClientConfiguration.cs
5 seconds was way too small, no matter test or prod.
`SocketTimeout` applies to initial handshake and to heartbeat messages. Connection is closed if a handshake or heartbeat response was not received within the specified time.
=> IGNITE-18618 .NET: Increase default SocketTimeout to 30 seconds

modules/core/src/main/java/org/apache/ignite/lang/ErrorGroups.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaService.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItTableApiContractTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/LockException.java
https://issues.apache.org/jira/browse/IGNITE-18358
=> IGNITE-18358 IGN-TX-5 on concurrent transactional single key load

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientConnectionTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/IgniteTablesInternal.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
Fix NullPointerException when assignments are requested for a table that no longer exists.
=> IGNITE-18650 Fix NullPointerException in TableManager.assignments

modules/platforms/dotnet/Apache.Ignite.Tests/Table/RecordViewBinaryTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/RecordViewPocoTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Transactions/TransactionsTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/KeyValueView.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/RecordView.cs, modules/platforms/dotnet/Apache.Ignite/Table/IKeyValueView.cs, modules/platforms/dotnet/Apache.Ignite/Table/IRecordView.cs
* `IRecordView` does not have `Contains`, and `KeyValueView` has one. Add the missing method. 
* Use `ContainsKey` name to stress the fact that only key part of the record is checked (which is evident from the signature in `KeyValueView`, but not in `RecordView`).
=> IGNITE-18609 .NET: Add ContainsKey method to Record API

modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeClusterAwarenessTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/PartitionAwarenessTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/RequestBalancingTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientFailoverSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/RecordView.cs
When .NET client is connected to more than one server node, send requests to different connections in a round-robin fashion instead of using the same default connection every time.
=> IGNITE-18613 .NET: Balance requests across connections

modules/platforms/cpp/ignite/client/detail/transaction/transaction_impl.h, modules/platforms/cpp/ignite/client/transaction/transaction.h
Transactions now rolled back synchronously on destruction.
No new tests as existing tests cover this case.
=> IGNITE-18815 C++ Tx sync rollback on destruction

modules/schema/src/main/java/org/apache/ignite/internal/schema/SchemaManager.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/registry/SchemaRegistryImpl.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/registry/SchemaRegistryImplTest.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/registry/UpgradingRowAdapterTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/StopCalciteModuleTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/MockedStructuresTest.java, modules/table/src/test/java/org/apache/ignite/internal/benchmarks/TupleMarshallerFixlenOnlyBenchmark.java, modules/table/src/test/java/org/apache/ignite/internal/benchmarks/TupleMarshallerVarlenOnlyBenchmark.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-18732
When removing blocking calls in SchemaManager, it was discovered, that `fireEvent` was called from the async part of the configuration listener. This is a problem, because `fireEvent` listeners call `VersionedValue#update` which can already be notified of the new configuration revision, in which case `update` will throw an exception.
=> IGNITE-18732 Fix race in VersionedValues in SchemaManager

modules/platforms/dotnet/Apache.Ignite.Benchmarks/Program.cs, modules/platforms/dotnet/Apache.Ignite.Benchmarks/Table/TableGetBenchmarks.cs, modules/platforms/dotnet/Apache.Ignite.Benchmarks/Table/TableGetMultiThreadedBenchmarks.cs, modules/platforms/dotnet/Apache.Ignite.Tests/ClientFailoverSocketTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/FakeServer.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientFailoverSocket.cs
* Take `_socketLock` only when a reconnect is required to avoid blocking operations on healthy channels.
* Add benchmarks to measure networking performance and client scaling on multiple connections.
=> IGNITE-18818 .NET: Improve locking granularity in ClientFailoverSocket

modules/platforms/dotnet/Apache.Ignite.Tests/ClientFailoverSocketTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/FakeServer.cs, modules/platforms/dotnet/Apache.Ignite.Tests/FakeServerGroup.cs, modules/platforms/dotnet/Apache.Ignite.Tests/HeartbeatTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/PartitionAwarenessTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/ReconnectTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/SocketTimeoutTest.cs, modules/platforms/dotnet/Apache.Ignite/IgniteClientConfiguration.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientFailoverSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientSocket.cs
Before this change .NET client would repair a connection only on demand (when all connections are broken, or when partition awareness requests a specific connection). Therefore, some connections may be lost and never repaired, which negatively affects request balancing.
* Add `IgniteClientConfiguration.ReconnectInterval`.
* Run a background task that checks and repairs all endpoints periodically.
This works together with heartbeats (which detect broken connections).
=> IGNITE-18808 .NET: Reconnect all endpoints periodically in background

modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientMessagePacker.java, modules/client/src/main/java/org/apache/ignite/internal/client/ReliableChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/compute/ClientCompute.java, modules/client/src/main/java/org/apache/ignite/internal/client/sql/ClientSession.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientKeyValueBinaryView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientKeyValueView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientRecordBinaryView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientRecordView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTable.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTupleSerializer.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/PartitionAwarenessProvider.java, modules/client/src/main/java/org/apache/ignite/internal/client/tx/ClientTransaction.java, modules/client/src/test/java/org/apache/ignite/client/AbstractClientTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientComputeTest.java, modules/client/src/test/java/org/apache/ignite/client/PartitionAwarenessTest.java, modules/client/src/test/java/org/apache/ignite/client/RequestBalancingTest.java, modules/platforms/dotnet/Apache.Ignite/Internal/ClientFailoverSocket.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientSqlTest.java
When Java client is connected to more than one server node, send requests to different connections in a round-robin fashion instead of using the same default connection every time. This improves client performance and evens the load among servers.
=> IGNITE-18810 Java client: Balance requests across connections

modules/platforms/dotnet/Apache.Ignite.Tests/ClientSocketTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/FakeServer.cs, modules/platforms/dotnet/Apache.Ignite.Tests/HeartbeatTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/ReconnectTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientFailoverSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientSocket.cs, modules/platforms/dotnet/Apache.Ignite/Log/LoggerExtensions.cs
Root cause: `TaskCancelledException` and `ObjectDisposedException` are sometimes thrown on disconnect from `ClientSocket`, and those exceptions are not retried.
* Fix exceptions.
* Improve logging: include socket id to correlate messages.
* Enable logging in the test.
* Improve assertion message.
=> IGNITE-18851 .NET: Fix TestReconnectAfterFullClusterRestart flakiness

gradle/libs.versions.toml, modules/cli/build.gradle, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/SqlCompleter.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/SqlReplCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/call/AbstractCallExecutionPipeline.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/call/AsyncCall.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/call/AsyncCallExecutionPipeline.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/call/AsyncCallExecutionPipelineBuilder.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/call/CallExecutionPipeline.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/call/CallExecutionPipelineBuilder.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/call/ProgressBarTracker.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/call/ProgressTracker.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/call/SingleCallExecutionPipeline.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/sql/SqlSchemaProvider.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/core/call/PipelineTest.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/sql/SqlSchemaProviderTest.java
I've introduced the core functionality for background async calls with a progress bar. The SQL completion hanging is fixed with background async initialization. 
I don't see any reason to use a UI thread with a special API.
https://issues.apache.org/jira/browse/IGNITE-18674
=> IGNITE-18674 Introduce async logic to CLI

modules/platforms/dotnet/Apache.Ignite.Tests/Transactions/TransactionsTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Transactions/Transaction.cs
* Do not throw exception on `Commit` & `Rollback` when transaction is already completed (committed or rolled back).
* Add `TroString` override.
=> IGNITE-18513 .NET: Ignore commit/rollback on completed tx

modules/client/src/main/java/org/apache/ignite/client/IgniteClient.java, modules/client/src/main/java/org/apache/ignite/client/IgniteClientConfiguration.java, modules/client/src/main/java/org/apache/ignite/internal/client/IgniteClientConfigurationImpl.java, modules/client/src/main/java/org/apache/ignite/internal/client/ReliableChannel.java, modules/client/src/test/java/org/apache/ignite/client/HeartbeatTest.java, modules/client/src/test/java/org/apache/ignite/client/ReconnectTest.java, modules/client/src/test/java/org/apache/ignite/client/RetryPolicyTest.java
Add `reconnectInterval` property to client configuration, which controls periodic background connect/repair of all known endpoints.
=> IGNITE-18809 Java client: Reconnect secondary endpoints in background

modules/client/src/test/java/org/apache/ignite/client/ClientLoggingTest.java, modules/client/src/test/java/org/apache/ignite/client/TestLoggerFactory.java
* Fix flakiness: introduce `waitForLogContains`, do not rely on log message count. Speeds up the test as well (wait only for what we need).
* Synchronize access to entries in `TestLoggerFactory`.
* Improve assertion messages.
=> IGNITE-19058 Fix ClientLoggingTest.testBasicLogging flakiness

modules/platforms/dotnet/Apache.Ignite.Tests/SslTests.cs, modules/platforms/dotnet/Apache.Ignite/ISslStreamFactory.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientSocket.cs, modules/platforms/dotnet/Apache.Ignite/SslStreamFactory.cs
* Replace a custom and potentially incomplete (e.g. ciphers could not be set before) set of options in `SslStreamFactory` with `SslClientAuthenticationOptions`. This way our API is simpler, and full set of options is available to the users.
* Make `ISslStreamFactory` asynchronous.
[SslClientAuthenticationOptions](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions?view=net-7.0) is a property bag that can be passed to `SslStream.AuthenticateAsClientAsync`. This API is not available in "classic" .NET or .NET standard, so we could not use it in Ignite 2.x.
=> IGNITE-19045 .NET: Refactor SslStreamFactory to use SslClientAuthenticationOptions

modules/platforms/dotnet/Apache.Ignite/Apache.Ignite.csproj
* Enable package validation in main project.
* Add `dotnet pack` step on CI to validate on every build (https://ci.ignite.apache.org/admin/editBuild.html?id=buildType:ApacheIgnite3xGradle_Test_RunNetTests).
=> IGNITE-18949 .NET: Enable NuGet package validation

modules/platforms/dotnet/Apache.Ignite.Tests/ReconnectTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientFailoverSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/SocketEndpoint.cs
* Use double check locking in `ClientFailoverSocket.ConnectAsync` to avoid connecting the same endpoint twice (this was the root cause of flakiness: `FakeServer` does not support multiple connections. But this is also a bug - two connections to the same server should not happen).
* Handle `ObjectDisposedException` when sending requests (may happen connection is closed concurrently).
* Increase `SocketTimeout` - 200ms is too short.
=> IGNITE-19069 .NET: Fix TestReconnectAfterFullClusterRestart flakiness

modules/distribution-zones/build.gradle, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerConfigurationChangesTest.java, modules/metastorage/build.gradle, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java, modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/impl/StandaloneMetaStorageManager.java
https://issues.apache.org/jira/browse/IGNITE-19093
=> IGNITE-19093: Create standalone MetaStorage implementation for test purposes

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotCopier.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotCopierTest.java
https://issues.apache.org/jira/browse/IGNITE-19142
=> IGNITE-19142 IncomingSnapshotCopier.cancel() blocks forever if called from multiple threads

modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java
`this::onPartitionAssignmentChanged` allocates a new delegate object, so `removeAssignmentsChangeListener` did not work. Store the delegate in a field and use the same object to unsubscribe.
=> IGNITE-19143 Fix memory leak in ClientInboundMessageHandler

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItRaftCommandLeftInLogUntilRestartTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java
https://issues.apache.org/jira/browse/IGNITE-19043
After the investigation it's occurred that the reason of the failure is that raft log re-appliance is skipped within PartitionListener#handleUpdateCommand and PartitionListener#handleUpdateAllCommand because of following logic
```
TxMeta txMeta = txStateStorage.get(cmd.txId());
if (txMeta != null && (txMeta.txState() == COMMITED || txMeta.txState() == ABORTED)) {
storage.runConsistently(() -> {
storage.lastApplied(commandIndex, commandTerm);
return null;
});
} 
```
Full scenario is following:
1. tx1.put populates raft log and mvPartitionStorage with corresponding log record and data.
2. tx1.commit also populates raft log with raft record and finished the transaction within txnStateStorage along wiht cleanup in mvPartitionStorage.
3. …
=> IGNITE-19043 ItRaftCommandLeftInLogUntilRestartTest fixed

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterInitializer.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftService.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/cluster/management/ItClusterInitTest.java
* Also reduce the number of changePeersAsync calls in CMG manager.
https://issues.apache.org/jira/browse/IGNITE-19171
=> IGNITE-19171 Fix flaky ItClusterInitTest.testDoubleInit

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-19238
1. First of all I've renamed tablesToStopInCaseOfError to pending tables, because they aren't only ...InCaseOfError.
2. I've also reworked tablesToStopInCaseOfError cleanup by substituting tablesToStopInCaseOfError.clear on revision change with
```
tablesByIdVv.get(causalityToken).thenAccept(ignored -> inBusyLock(busyLock,  ()-> {      
pendingTables.remove(tblId);
})); 
```
meaning that we
2.1. remove specific table by id instead of ready.
2.2. do that removal on corresponding table publishing wihtin tablesByIdVv.
3. That means that at some point right after the publishing but before removal it's possible to have same table both within tablesByIdVv and pendingTables thus in order not to stop same table twice (which is safe by the way …
=> IGNITE-19238 ItDataTypesTest and ItCreateTableDdlTest are flaky

modules/runner/src/integrationTest/java/org/apache/ignite/internal/Cluster.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/compute/ItLogicalTopologyTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceTest.java
https://issues.apache.org/jira/browse/IGNITE-19126
=> IGNITE-19126 Make ItTableRaftSnapshotsTest less invasive

modules/runner/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java
https://issues.apache.org/jira/browse/IGNITE-18485
=> IGNITE-18485 ItTableRaftSnapshotsTest.entriesKeepAppendedAfterSnapshotInstallation() sometimes hangs

modules/cli/src/main/java/org/apache/ignite/internal/cli/call/sql/SqlQueryCall.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/SqlReplCommand.java
https://issues.apache.org/jira/browse/IGNITE-19038
defaultValue is required in order to reset `@Parameters`-annotated field to null.
=> IGNITE-19038 sql command does not enter repl

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/call/unit/ItDeployUndeployCallsTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/unit/ItDeploymentUnitTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/rest/ItGeneratedRestClientTest.java, modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/deployment/DeploymentCodeApi.java
https://issues.apache.org/jira/browse/IGNITE-19139
The underlying issue is a static converters registry in the Mirconaut framework: `io.micronaut.core.convert.ConversionService#SHARED`
1. First node is started, this registry is populated with `io.micronaut.security.config.InterceptUrlMapConverter`
2. Second node begins starting, clearing the registry in `io.micronaut.context.DefaultBeanContext#start`
3. First node receives any HTTP request, instantiating `io.micronaut.security.rules.ConfigurationInterceptUrlMapRule` which retrieves the `micronaut.security.intercept-url-map[1].pattern` configuration value, tries to convert it to the `InterceptUrlMapPattern` and fails since the registry is cleared. So the `ConfigurationInterceptUrlMapRule` in the first node is broken and every subsequent …
=> IGNITE-19139 Fix flaky ItDeployUndeployCallsTest

modules/platforms/dotnet/Apache.Ignite.Tests/MetricsTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientSocket.cs
* Fix potentially duplicate `RequestsActiveDecrement` call in `ClientSocket`.
* Disable retry policy to avoid extra requests.
* Wait for active requests and connections to go to zero.
=> IGNITE-19298 .NET: Fix MetricsTests.TestRequestsActive flakiness

modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/SqlReplTopLevelCliCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/version/VersionCommand.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/CliCommandTestBase.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/ReuseCommandTest.java
https://issues.apache.org/jira/browse/IGNITE-19296
This was not due to some bug in picocli but rather due to the caching of commands when using `@Singleton`
=> IGNITE-19296 Unmute PicocliBugTest

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/core/repl/executor/ItIgnitePicocliCommandsTest.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/registry/impl/ClusterConfigRegistryImpl.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/registry/impl/JdbcUrlRegistryImpl.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/registry/impl/LazyObjectRef.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/registry/impl/MetricRegistryImpl.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/registry/impl/NodeConfigRegistryImpl.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/registry/impl/NodeNameRegistryImpl.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/registry/impl/UnitsRegistryImpl.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/core/repl/registry/impl/LazyObjectRefTest.java
https://issues.apache.org/jira/browse/IGNITE-19316
I've added logging to the process of background fetching of configurations and other stuff that is needed for the  CLI completions. Also `LazyObjectRef` is introduced. This reference will try to fetch the value from the source till this is not null.
=> IGNITE-19316 Fix ItIgnitePicocliCommandsTest

modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTableCommon.java, modules/platforms/dotnet/Apache.Ignite.Tests/LoggingTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/VersionTests.cs, modules/platforms/dotnet/Apache.Ignite.sln, modules/platforms/dotnet/Apache.Ignite/Internal/ClientFailoverSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Compute/Compute.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/RecordView.cs, modules/platforms/dotnet/Apache.Ignite/Internal/VersionUtils.cs, modules/platforms/dotnet/DEVNOTES.md, modules/platforms/dotnet/Directory.Build.props, modules/platforms/dotnet/version.json
* Add [GitVersioning](https://github.com/dotnet/Nerdbank.GitVersioning) library to manage assembly and package versions in one place (`version.json`).
* Build-time only dependency, does not affect users.
* `AssemblyInformationalVersion` includes git revision hash.
* Log version with hash with `Info` level on client start.
* Add test to check that versions in .NET and Java projects are the same.
Extra:
* Remove TODO leftovers for closed tickets.
=> IGNITE-19391 .NET: Add commit hash to assembly version

modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/connect/ConnectCommand.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/UrlOptionsNegativeTest.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/connect/ConnectCommandTest.java
https://issues.apache.org/jira/browse/IGNITE-19446
=> IGNITE-19446 Non-REPL connect command should only allow URLs

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/core/repl/executor/ItIgnitePicocliCommandsTest.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/node/NodeUrlMixin.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/converters/NodeNameOrUrlConverter.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/PeriodicSessionTask.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/PeriodicSessionTaskExecutor.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/completer/cluster/ClusterUrlDynamicCompleterFactory.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/registry/impl/JdbcUrlRegistryImpl.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/registry/impl/NodeNameRegistryImpl.java
https://issues.apache.org/jira/browse/IGNITE-18551
This also simplifies `NodeNameRegistry` to use `String` instead of `URL`.
=> IGNITE-18551 Create general task executor for all registries

modules/platforms/dotnet/Apache.Ignite.Benchmarks/Table/TableGetBenchmarks.cs, modules/platforms/dotnet/Apache.Ignite.Benchmarks/Table/TableGetMultiThreadedBenchmarks.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeClusterAwarenessTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/FakeServer.cs, modules/platforms/dotnet/Apache.Ignite.Tests/FakeServerTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/MetricsTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/RetryPolicyTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/SchemaUpdateTest.cs, modules/platforms/dotnet/Apache.Ignite.Tests/TestUtils.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Table.cs
Cache schema tasks instead of schemas (task results). If a given schema is already requested, await existing task instead of sending another request.
=> IGNITE-19355 .NET: Do not request same schema more than once

modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationChanger.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/ConfigurationChangerTest.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/ConfigurationRegistryTest.java, modules/configuration/src/testFixtures/java/org/apache/ignite/internal/configuration/storage/TestConfigurationStorage.java, modules/core/src/main/java/org/apache/ignite/lang/ErrorGroups.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/ItNodeBootstrapConfigurationTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/ItNodeConfigurationFileTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/ItSslConfigurationValidationTest.java, modules/runner/src/main/java/org/apache/ignite/internal/configuration/NodeConfigParseException.java, modules/runner/src/main/java/org/apache/ignite/internal/configuration/storage/LocalFileConfigurationStorage.java
https://issues.apache.org/jira/browse/IGNITE-19315
=> IGNITE-19315 Validate node configuration on node start

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/CliCommandTestNotInitializedIntegrationBase.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/sql/CliSqlCommandTestBase.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/ssl/ItJdbcSslTest.java
https://issues.apache.org/jira/browse/IGNITE-19605
This test fail happens when previous test used `connect` command without paired `disconnect`, which leaves the periodic session task running.
When starting the nodes in the next test, it so happens that the request for the node configuration from the `JdbcUrlRegistryImpl` or any other periodic task is received while the Micronaut's context is starting in the `RestController` for the second node. In this case the `io.micronaut.core.convert.ConversionService#SHARED` is cleared and is not yet populated.
It's not entirely clear what happens next, but most probably the HTTP server caches the state where there's no corresponding type converter and this leaves the node in the broken state.
It doesn't seem possible to properly fix this outside of …
=> IGNITE-19605 ItDeploymentUnitTest is flaky

modules/client/src/test/java/org/apache/ignite/client/ClientMetricsTest.java, modules/client/src/test/java/org/apache/ignite/client/TestClientHandlerModule.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeAsyncResultSet.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeSession.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientComputeTest.java
TeamCity now triggers a failure condition on **NullReferenceException** in the log - it usually indicates a bug. Fix client tests to avoid NPEs.
=> IGNITE-19653 Fix NPEs in client test logs

modules/runner/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java
https://issues.apache.org/jira/browse/IGNITE-19656
=> IGNITE-19656 Retry more frequently in ItTableRaftSnapshotsTest

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/ssl/ItSslTest.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/registry/impl/ClusterConfigRegistryImpl.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/registry/impl/MetricRegistryImpl.java
https://issues.apache.org/jira/browse/IGNITE-19659
First NPE is shown in the logs when we connect to uninitialized cluster.
Second NPE is shown when we run non-REPL `connect` command without proper environment.
=> IGNITE-19659 NPE in ClusterConfigRegistryImpl.fetchConfig

modules/core/src/main/java/org/apache/ignite/lang/ErrorGroups.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/disruptor/StripedDisruptor.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaService.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/exception/ReplicaStoppingException.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ReplicaUnavailableTest.java
https://issues.apache.org/jira/browse/IGNITE-19494
=> IGNITE-19494 Correctly stop a replica

modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/ItClusterManagerTest.java
Increase timeout of electing a new leader
=> IGNITE-19689 fix ItClusterManagerTest.testClusterConfigurationIsRemovedFromClusterStateAfterUpdating

modules/platforms/dotnet/Apache.Ignite.Tests/Common/CollectionExtensions.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/FakeServer.cs, modules/platforms/dotnet/Apache.Ignite.Tests/IgniteProxy.cs, modules/platforms/dotnet/Apache.Ignite.Tests/IgniteProxyTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/IgniteServerBase.cs, modules/platforms/dotnet/Apache.Ignite.Tests/IgniteTestsBase.cs, modules/platforms/dotnet/Apache.Ignite.Tests/PartitionAwarenessRealClusterTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/PartitionAwarenessTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientFailoverSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/PreferredNode.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/RecordView.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Table.cs, modules/platforms/dotnet/Apache.Ignite/Network/IClusterNode.cs
There was a confusion between *Local Node ID* (`ConnectionContext.ClusterNode.Id`) and *Consistent Node ID* (which is the same as Node Name, comes from `ConnectionContext.ClusterNode.Name`). Partition assignment (returned by `ClientTablePartitionAssignmentGetRequest` on the server) must be based on *Consistent Node ID*.
All partition awareness tests use `FakeServer`, so we never tested that it actually works.
* Remove `ClientFailoverSocket._endpointsById` and related logic, identify nodes only by Name (consistent id)
* Add `IgniteProxy` to track request routing on real cluster, and compare results to the primary node calculated on the Java side
=> IGNITE-19826 .NET: Fix partition awareness node ids

modules/client/src/main/java/org/apache/ignite/internal/client/ReliableChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/compute/ClientCompute.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientKeyValueBinaryView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTable.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTupleSerializer.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/PartitionAwarenessProvider.java, modules/client/src/test/java/org/apache/ignite/client/PartitionAwarenessTest.java, modules/runner/build.gradle, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItAbstractThinClientTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientPartitionAwarenessTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/proxy/IgniteClientProxy.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/proxy/IgniteClientProxyBackendHandler.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/proxy/IgniteClientProxyFrontendHandler.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/proxy/IgniteClientProxyInitializer.java
There was a confusion between *Local Node ID* (`protocolContext().clusterNode().id()`) and *Consistent Node ID* (which is the same as Node Name, comes from `protocolContext().clusterNode().name()`). Partition assignment (returned by `ClientTablePartitionAssignmentGetRequest` on the server) must be based on *Consistent Node ID*.
All partition awareness tests use `FakeIgnite`, so we never tested it on real clusters.
* Remove `ReliableChannel.nodeChannelsById` and related logic, identify nodes only by Name (consistent id)
* Add `IgniteClientProxy` to track request routing on real cluster, and compare results to the primary node calculated on the server side (via Compute)
=> IGNITE-19827 Java client: fix partition awareness node ids

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientTransactionsTest.java
https://issues.apache.org/jira/browse/IGNITE-19393
=> IGNITE-19393 Java thin 3.0: testAccessLockedKeyTimesOut is flaky

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlQueryProcessor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PrepareServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/ParsedResult.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/ParserService.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/ParserServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/Cache.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/CacheFactory.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/CaffeineCacheFactory.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/benchmarks/TpchPrepareBenchmark.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImplTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestNode.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/ParserServiceImplTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/util/EmptyCacheFactory.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/util/StatementChecker.java
Before:
```
Benchmark                  (fsync)  Mode  Cnt   Score   Error  Units
InsertBenchmark.sqlInsert    false  avgt   20   1.937 ± 0.286  ms/op
```
After
```
Benchmark                  (fsync)  Mode  Cnt   Score   Error  Units
InsertBenchmark.sqlInsert    false  avgt   20   1.550 ± 0.204  ms/op
```
=> IGNITE-17765 Sql. Introduce cache for parsed statements

modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/compute/ClientComputeExecuteColocatedRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientSchemasGetRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTableCommon.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTablePartitionAssignmentGetRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTupleContainsKeyRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTupleDeleteAllExactRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTupleDeleteAllRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTupleDeleteExactRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTupleDeleteRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTupleGetAllRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTupleGetAndDeleteRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTupleGetAndReplaceRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTupleGetAndUpsertRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTupleGetRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTupleInsertAllRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTupleInsertRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTupleReplaceExactRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTupleReplaceRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTupleUpsertAllRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTupleUpsertRequest.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeIgniteTables.java, modules/table/src/main/java/org/apache/ignite/internal/table/IgniteTablesInternal.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
* Make `ClientTableCommon.readTable` async to avoid blocking Netty threads
* Change `IgniteTablesInternal#assignments` to async too
* Extend unpacker lifetime in `ClientInboundMessageHandler` to allow unpacking in future continuations
=> IGNITE-19667 Make ClientTableCommon.readTable async

modules/client/src/main/java/org/apache/ignite/internal/client/ClientMetricSource.java, modules/client/src/main/java/org/apache/ignite/internal/client/ReliableChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientDataStreamer.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientKeyValueBinaryView.java, modules/client/src/test/java/org/apache/ignite/client/ClientMetricsTest.java, modules/client/src/test/java/org/apache/ignite/client/TestServer.java, modules/core/src/main/java/org/apache/ignite/internal/streamer/StreamerMetricSink.java, modules/core/src/main/java/org/apache/ignite/internal/streamer/StreamerSubscriber.java, modules/table/src/main/java/org/apache/ignite/internal/table/DataStreamer.java
Add data streamer metrics to .NET client:
* `StreamerBatchesSent`
* `StreamerItemsSent`
* `StreamerBatchesActive`
* `StreamerItemsQueued`
`StreamerMetricSink` is added because most of the streamer code is in `ignite-core` module, which is shared across client and server.
=> IGNITE-19609 Java client: Add data streamer metrics

modules/runner/src/integrationTest/java/org/apache/ignite/internal/streamer/ItAbstractDataStreamerTest.java
Increase timeout, use read-only tx instead of try-catch for concurrent reads.
=> IGNITE-19859 Fix testAutoFlushByTimer flakiness

modules/client/src/test/java/org/apache/ignite/client/AbstractClientTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientAuthenticationTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientMetricsTest.java, modules/client/src/test/java/org/apache/ignite/client/DataStreamerTest.java, modules/client/src/test/java/org/apache/ignite/client/PartitionAwarenessTest.java, modules/core/src/main/java/org/apache/ignite/internal/streamer/StreamerSubscriber.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/streamer/ItAbstractDataStreamerTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/streamer/ItClientDataStreamerTest.java
* Use `IgniteUtils.closeAll` to close multiple resources reliably
* Use try-with-resources for `SubmissionPublisher` in all tests
* Use `scheduleAtFixedRate` instead of `Timer` in client streamer ([recommended approach for modern code](https://stackoverflow.com/questions/409932/java-timer-vs-executorservice))
https://issues.apache.org/jira/browse/IGNITE-20036
=> IGNITE-20036 Fix resource leaks in client tests and streamer

modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java
Remove the port limitation to support other dynamic port reverse proxys. Like testcontainers[1]
[1]
https://stackoverflow.com/questions/76746998/why-ignite-tcpclientchannel-port-can-not-larger-than-49151
=> IGNITE-20026 Java client: Remove port range limitation

modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvPartitionStorage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/StorageUpdateHandler.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
https://issues.apache.org/jira/browse/IGNITE-20148
=> IGNITE-20148 Explicit writeIntent cleanup on primary replica

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/BaseDistributionZoneManagerTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerAlterFilterTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerConfigurationChangesTest.java, modules/distribution-zones/src/testFixtures/java/org/apache/ignite/internal/distributionzones/DistributionZonesTestUtil.java
https://issues.apache.org/jira/browse/IGNITE-20058
=> IGNITE-20058 Flaky distribution zone tests were fixed by fixing order of the meta storage watches deploying and a distribution zone manager start

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/datatypes/uuid/ItUuidExpressionTest.java
Add two test cases that conversion from invalid UUID string to UUID is not possible - one for literals, one for dynamic parameters.
https://issues.apache.org/jira/browse/IGNITE-19361
---
- …
=> IGNITE-19361: Sql. UUID. Add removed test cases.

modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientBinaryTupleUtils.java, modules/client/src/test/java/org/apache/ignite/client/AbstractClientTableTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientRecordViewTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientTableTest.java, modules/marshaller-common/src/main/java/org/apache/ignite/internal/marshaller/FieldAccessor.java, modules/marshaller-common/src/main/java/org/apache/ignite/internal/marshaller/MarshallerUtil.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientMarshallingTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientSqlTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/streamer/ItAbstractDataStreamerTest.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/marshaller/reflection/KvMarshallerImpl.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/marshaller/reflection/ObjectStatistics.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/marshaller/reflection/RecordMarshallerImpl.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/row/RowAssembler.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/marshaller/KvMarshallerTest.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/marshaller/RecordMarshallerTest.java
* Add `ItThinClientMarshallingTest` tests to ensure consistent schema validation across embedded and client APIs
* Fix inconsistent column type mismatch error messages 
* Add missing column type validation to client marshaller
* Add column type validation to `ObjectStatistics` to fix weird/inconsistent exceptions (statistics are collected before marshalling, so exceptions were different)
=> IGNITE-19841 Add tests for schema validation consistency in client and embedded API

modules/client/build.gradle
Change dependency type for `ignite-api` and `ignite-core` projects from `implementation` to `api`.
Those two projects contain public API types.
* With `implementation` dependency type, users have to explicitly add dependencies to all three modules to use those types
* With `api` dependency type, single `ignite-client` dependency is enough to use the entire public API
=> IGNITE-19978 Java client: Change Gradle dependencies from implementation to api

modules/client/src/test/java/org/apache/ignite/client/PartitionAwarenessTest.java
Use dynamic port to fix intermittent "port is in use" issues.
=> IGNITE-20152 Fix PartitionAwarenessTest.startServer2 flakiness

modules/platforms/dotnet/Apache.Ignite.Tests/.editorconfig, modules/platforms/dotnet/Apache.Ignite.Tests/ClientSocketTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/FakeServer.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Transactions/TransactionsTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientFailoverSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/IClientSocketEventListener.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Sql/Sql.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Transactions/Transactions.cs
Track observable timestamp in .NET client:
* Maintain latest value in `ClientFailoverSocket`
* Send back to server in `TxBegin` and `SqlExec`
=> IGNITE-20056 .NET: Track observable timestamp

modules/platforms/dotnet/Apache.Ignite.Tests/Table/SchemaSynchronizationTest.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Common/ExceptionExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Compute/Compute.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/ErrorExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/RecordView.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Table.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientSchemaSynchronizationTest.java
* Read known error extensions data from server
* Retry `SchemaVersionMismatch` error code with specified schema
* Improve code reuse in `RecordView` (there are still multiple methods which do the same retry logic; we could fix it with delegates `DoOp(() -> blabla)`, but this will increase allocations)
=> IGNITE-19838 .NET: Retry outdated schema error 

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlAsynchronousApiTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlSynchronousApiTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/AsyncSqlCursorImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/AsyncSqlCursorImplTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/NoOpTransaction.java
- Commits implicit transaction on AsyncCursor::close.
- Adds unit tests for AsyncCursorImpl.
https://issues.apache.org/jira/browse/IGNITE-19919
---- …
=> IGNITE-19919: org.apache.ignite.sql.ResultSet#close should close implicit transaction if any.

buildscripts/java-core.gradle
Gradle returns non-zero exit code when at least 1 test fails, causing the build on TC go red, even if that test is muted. After this change test failures are still reported locally and on TC, but the exit code is `0`.
Before:
```
245 tests completed, 1 failed, 3 skipped
> Task :ignite-client:test FAILED
FAILURE: Build failed with an exception.
```
After:
```
245 tests completed, 1 failed, 3 skipped
There were failing tests. See the report at: file:///home/apolo/Work/ignite-3/modules/client/build/reports/tests/test/index.html
BUILD SUCCESSFUL in 36s
```
=> IGNITE-20200 Ignore unit test failures with Gradle

modules/platforms/dotnet/Apache.Ignite.Tests/ProjectFilesTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/SchemaSynchronizationTest.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/SchemaValidationTest.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Compute/Compute.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Column.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/RecordView.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/KvPair.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/ObjectSerializerHandler.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/SerializerExceptionExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/TuplePairSerializerHandler.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/TupleSerializerHandler.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Table.cs
When unmapped columns are detected in a Tuple or a POCO, we must ensure that the latest schema is used before throwing an exception.
For example, right after `ALTER TABLE ADD COLUMN`, the user expects to be able to insert a tuple with the new column. However, the client still has the old schema in the cache, and previously would throw unmapped column error. Now we retry the operation with forced schema refresh.
=> IGNITE-19840 .NET: Reload schema when unmapped columns are detected

modules/client/src/test/java/org/apache/ignite/client/PartitionAwarenessTest.java
Tx uses random connection, so don't use a hardcoded node name.
=> IGNITE-20183 Fix testNonNullTxDisablesPartitionAwareness flakiness

modules/platforms/dotnet/Apache.Ignite.Tests/Table/Serialization/ReflectionUtilsTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Linq/ResultSelector.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/ObjectSerializerHandler.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/ReflectionUtils.cs
`GetFieldByColumnName` was always called inside a loop, therefore inner call to `GetFieldsByColumnName` is repeated.
* Remove `GetFieldByColumnName` to avoid this mistake
* Call `GetFieldsByColumnName` outside of the loop instead
=> IGNITE-20197 .NET: Fix excessive dictionary lookups by GetFieldByColumnName usages

modules/platforms/cpp/ignite/client/detail/cluster_connection.cpp, modules/platforms/cpp/ignite/client/detail/cluster_connection.h, modules/platforms/cpp/ignite/client/detail/connection_event_handler.h, modules/platforms/cpp/ignite/client/detail/node_connection.cpp, modules/platforms/cpp/ignite/client/detail/node_connection.h, modules/platforms/cpp/ignite/client/detail/sql/sql_impl.cpp, modules/platforms/cpp/ignite/client/detail/transaction/transactions_impl.h, modules/platforms/cpp/ignite/odbc/query/data_query.cpp, modules/platforms/cpp/ignite/odbc/sql_connection.cpp, modules/platforms/cpp/ignite/odbc/sql_connection.h, modules/platforms/cpp/tests/odbc-test/connection_test.cpp
Added storing and sending of observable timestamp to both ODBC and C++ client.
=> IGNITE-20057  Track observable timestamp in C++ client and ODBC

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/connect/ItConnectWithBasicAuthenticationCommandTest.java
https://issues.apache.org/jira/browse/IGNITE-20219
Fix the typo of "user name" to username, and we are using username in many pieces. Keep it consistent.
=> IGNITE-20219 Fix the typo of user name to username

modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/storage/ItRebalanceDistributedTest.java
https://issues.apache.org/jira/browse/IGNITE-20230
The root cause of a flakiness was in instant destroyPartition check after receiving assignments.stable notification, which is basically incorrect because destroyPartition is called after receiving the aforementioned event in an async flow.
\- The pull request title is treated as the final commit …
=> IGNITE-20230 ItRebalanceDistributedTest#testDestroyPartitionStoragesOnEvictNode fixed.

modules/platforms/dotnet/Apache.Ignite.Benchmarks/Program.cs, modules/platforms/dotnet/Apache.Ignite.Benchmarks/Table/Serialization/SerializerHandlerReadBenchmarks.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/BinaryTupleIgniteTupleAdapterTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/IgniteTupleTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/ToStringTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/BinaryTuple/BinaryTupleIgniteTupleAdapter.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/IgniteTupleCommon.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Schema.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/TupleSerializerHandler.cs, modules/platforms/dotnet/Apache.Ignite/Table/IIgniteTuple.cs, modules/platforms/dotnet/Apache.Ignite/Table/IgniteTuple.cs
When reading data from server, currently we unpack all elements of the incoming `BinaryTuple` into `IgniteTuple`. This is extra work and extra allocations. Instead, create an adapter from `BinaryTuple` to `IIgniteTuple` like `MutableRowTupleAdapter` does in Java.
**Benchmarks**
```
BEFORE
|             Method |      Mean |    Error |   StdDev | Ratio | RatioSD |  Gen 0 | Allocated |
|------------------- |----------:|---------:|---------:|------:|--------:|-------:|----------:|
|   ReadObjectManual |  52.66 ns | 0.326 ns | 0.305 ns |  1.00 |    0.00 | 0.0003 |      80 B |
|         ReadObject |  88.41 ns | 0.425 ns | 0.398 ns |  1.68 |    0.01 | 0.0002 |      80 B |
|          ReadTuple | 263.26 ns | 2.822 ns | 2.502 ns |  5.00 |    0.06 | 0.0019 |     544 B |
| ReadTupleAndFields | 268.03 …
```
=> IGNITE-19542 .NET: Add BinaryTupleIgniteTupleAdapter

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDmlTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/ddl/DdlSqlToCommandConverter.java
Fixes handling of `NULL` literal in `DEFAULT NULL` constraint of `CREATE TABLE` command.
https://issues.apache.org/jira/browse/IGNITE-18965
---- …
=> IGNITE-18965: Sql. CREATE TABLE fails when a column with DEFAULT constraint NULL is present.

modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientHandlerModule.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/client/src/test/java/org/apache/ignite/client/TestClientHandlerModule.java
`clusterId` was initialized after we start the endpoint, so it was possible for client to connect quickly while we don't yet have an id.
Fix: pass `CompletableFuture<UUID>` to `ClientInboundMessageHandler`. This eliminates race condition, removes blocking wait in most cases (likely the future will complete before the first handshake), and simplifies the code.
Additionally:
* Fix other potential race conditions when accessing volatile fields
* Fix deprecated exception ctor calls
=> IGNITE-20275 Fix race condition in ClientInboundMessageHandler

modules/platforms/dotnet/Apache.Ignite.Tests/BasicAuthenticatorTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeClusterAwarenessTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/IgniteClientExtensions.cs, modules/platforms/dotnet/Apache.Ignite.Tests/LoggingTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/PartitionAwarenessTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/ReconnectTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/RequestBalancingTests.cs
* Increase timeout to fix flakiness
* Extract common method to wait for background client connections and reuse in all tests
=> IGNITE-20288 .NET: Fix TestDroppedConnectionsAreRestoredInBackground flakiness

modules/runner/src/integrationTest/java/org/apache/ignite/internal/streamer/ItAbstractDataStreamerTest.java
Wait for streamer completion in all tests to ensure that no updates happen after test exit, causing conflicts with SQL in `clearTable`.
=> IGNITE-20308 Fix ItAbstractDataStreamerTest flakiness

modules/platforms/dotnet/Apache.Ignite.Tests/Table/DataStreamerTests.cs
Move `Transactions.BeginAsync` inside `WaitForConditionAsync`, otherwise the same RO TX uses the same old read timestamp and we never see the update.
=> IGNITE-20306 .NET: Fix TestAutoFlushFrequency flakiness

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/BaseAggregateTest.java
The race was caused by rewinding node from incorrect thread.
The problematic sequence of event was as follow:
1. main thread calls `hasNext` and waits on condition inside `RootNode`
2. task executor thread starts scanning empty iterator, which renders in an immediate call to `Downstream#end` on the entire tree
3. inside `SortAggregateNode#end` task executor calls to `downstream().end()` that notifies condition and releases main thread
next points go concurrently
4. task executor proceeds execution inside `SortAggregateNode#end` and nullifies `grp` field
5. main thread rewinds the node and reinitialise `grp` with new group
If main thread outruns task executor (p5 goes before p4), then `grp` will be incorrectly nullified, and root node will return empty result.
Besides fix of the race, in …
=> IGNITE-20264 Sql. Races in BaseAggregateTest::countOfEmptyWithRewind

README.md, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/datatypes/BaseTypeCoercionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/datatypes/NumericBinaryOperationsTypeCoercionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/datatypes/NumericComparisonTypeCoercionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/datatypes/utils/Types.java
=> IGNITE-20000: Add planner test to verify numeric type coercion in binary arithmetic

modules/platforms/dotnet/Apache.Ignite.Tests/MetricsTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/SchemaSynchronizationTest.cs
To work around `IncompatibleSchemaException`, ensure that we don't perform schema updates while streamer upserts data in the background.
=> IGNITE-20399 .NET: Fix TestSchemaUpdateWhileStreaming flakiness

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/LogicalRelImplementor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/metadata/IgniteFragmentMapping.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/metadata/IgniteMdDistribution.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteRelShuttle.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteSqlToRelConvertor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteSqlValidator.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PlannerPhase.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rel/IgniteRelVisitor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rel/IgniteSystemViewScan.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rel/ProjectableFilterableTableScan.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rel/logical/IgniteLogicalIndexScan.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rel/logical/IgniteLogicalSystemViewScan.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rule/LogicalScanConverterRule.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rule/logical/FilterScanMergeRule.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rule/logical/ProjectScanMergeRule.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/AbstractIgniteDataSource.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/CatalogSqlSchemaManager.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/IgniteDataSource.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/IgniteSchema.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/IgniteSystemView.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/IgniteSystemViewImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/IgniteResource.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImplTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestTable.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/AbstractPlannerTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/SystemViewPlannerTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/prepare/TypeCoercionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/schema/CatalogSqlSchemaManagerTest.java
Makes system views accessible to planner via calcite's Table class.
* Introduces `IgniteDataSource` interface that represents both Tables and System Views.
* Extracts common fields from IgniteTable to IgniteDataSource.
https://issues.apache.org/jira/browse/IGNITE-20020
----
\- The pull request title is treated as the final commit message. The following …
=> IGNITE-20020: Sql. Support system views in planner.

modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/raft/ItCmgRaftServiceTest.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/NodeAttributes.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/NodeAttributesCollector.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/NodeAttributesProvider.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListener.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftService.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/commands/ClusterNodeMessage.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/topology/api/LogicalNode.java, modules/cluster-management/src/testFixtures/java/org/apache/ignite/internal/cluster/management/MockNode.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZonesUtil.java, modules/distribution-zones/src/testFixtures/java/org/apache/ignite/internal/distributionzones/DistributionZonesTestUtil.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesAbstractTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageWatchTest.java, modules/runner/build.gradle, modules/runner/src/integrationTest/java/org/apache/ignite/internal/compute/ItLogicalTopologyTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/ItDistributedConfigurationPropertiesTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/storage/ItDistributedConfigurationStorageTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/distribution/zones/ItIgniteDistributionZoneManagerNodeRestartTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/system-view/build.gradle, modules/system-view/src/main/java/org/apache/ignite/internal/systemview/ClusterSystemView.java, modules/system-view/src/main/java/org/apache/ignite/internal/systemview/NodeSystemView.java, modules/system-view/src/main/java/org/apache/ignite/internal/systemview/SystemView.java, modules/system-view/src/main/java/org/apache/ignite/internal/systemview/SystemViewManager.java, modules/system-view/src/main/java/org/apache/ignite/internal/systemview/SystemViewManagerImpl.java, modules/system-view/src/main/java/org/apache/ignite/internal/systemview/utils/SystemViewUtils.java, modules/system-view/src/test/java/org/apache/ignite/internal/systemview/SystemViewManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-20019
System views are registered when the views manager starts.
In order to understand at the planning phase on which node which system views are available, a list of system views is added to the attributes of the logical node.
To collect attributes from system components before a node joins the cluster, the `NodeAttributesCollector` class was introduced, which gets attributes from component and writes them to a `ClusterNodeMessage` when a node is joined.
Public node attributes (from configuration) may be used for filtering when creating distribution zones (see [zones-filter](https://github.com/apache/ignite-3/blob/main/modules/distribution-zones/tech-notes/filters.md#zones-filter) ), in order to minimize the possible risks of mixing user …
=> IGNITE-20019 Sql. Implement system views manager

modules/api/src/main/java/org/apache/ignite/lang/ErrorGroups.java, modules/placement-driver-api/src/main/java/org/apache/ignite/internal/placementdriver/PlacementDriver.java, modules/placement-driver-api/src/testFixtures/java/org/apache/ignite/internal/placementdriver/TestPlacementDriver.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/PrimaryReplicaAwaitException.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/PrimaryReplicaAwaitTimeoutException.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/LeaseTracker.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/PlacementDriverTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/placementdriver/ItPrimaryReplicaChoiceTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTableScanTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-20367
- Two new exceptions were introduced in order to ease the test failure analysis by distinguishing primary replica await timeout and common future timeout. PrimaryReplicaAwaitException, PrimaryReplicaAwaitTimeoutException.
- PlacementDriver#awaitPrimaryReplica updated a bit by adding timeout and unit parameters to the method API.
-  LeaseUpdate#nextLeaseHolder method was adjusted in order to skip nodes that were missing in logical topology.
=> IGNITE-20367 ItTableRaftSnapshotsTest times out with high flaky rate

modules/platforms/dotnet/Apache.Ignite/IgniteClient.cs, modules/platforms/dotnet/Apache.Ignite/IgniteClientConfiguration.cs, modules/platforms/dotnet/Apache.Ignite/IgniteException.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Common/IgniteArgumentCheck.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Common/IgniteToStringBuilder.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Compute/Compute.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Sql/ResultSet.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Sql/Sql.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/DataStreamer.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/KeyValueView.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/RecordView.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Tables.cs, modules/platforms/dotnet/Apache.Ignite/Log/CategoryLogger.cs, modules/platforms/dotnet/Apache.Ignite/Log/LoggerExtensions.cs, modules/platforms/dotnet/Apache.Ignite/RetryLimitPolicy.cs, modules/platforms/dotnet/Apache.Ignite/RetryReadPolicy.cs, modules/platforms/dotnet/Apache.Ignite/Sql/IgniteDbDataReader.cs, modules/platforms/dotnet/Apache.Ignite/Sql/IgniteQueryableExtensions.Average.cs, modules/platforms/dotnet/Apache.Ignite/Sql/IgniteQueryableExtensions.Dml.cs, modules/platforms/dotnet/Apache.Ignite/Sql/IgniteQueryableExtensions.Sum.cs, modules/platforms/dotnet/Apache.Ignite/Sql/IgniteQueryableExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Sql/SqlStatement.cs, modules/platforms/dotnet/Apache.Ignite/SslStreamFactory.cs, modules/platforms/dotnet/Apache.Ignite/Table/IIgniteTuple.cs
IGNITE-20479 (#2636) replaced custom null checks with standard `ArgumentNullException.ThrowIfNull`. However, `ThrowIfNull` takes *object*, which involves boxing for value types, resulting in heap allocations.
Bring back generic `NotNull` check which does not allocate.
=> IGNITE-20523 .NET: Restore generic IgniteArgumentCheck.NotNull

modules/platforms/cpp/ignite/client/detail/utils.cpp, modules/platforms/cpp/tests/client-test/key_value_binary_view_test.cpp, modules/platforms/cpp/tests/client-test/record_binary_view_test.cpp, modules/platforms/cpp/tests/client-test/record_view_test.cpp
- Checked that number of written columns is no less than total number of columns in tuple. Reject tuple if there are any extra columns;
- Added tests.
=> IGNITE-20240 C++ 3.0: Reject Tuples with unmapped fields

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngine.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/causalitydatanodes/DistributionZoneCausalityDataNodesTest.java
https://issues.apache.org/jira/browse/IGNITE-20317
=> IGNITE-20317 return metastorage invokes for zones changes in handlers, immediately recalculate data nodes when scale up/down is immediate.

modules/platforms/cpp/ignite/client/detail/utils.cpp, modules/platforms/cpp/ignite/odbc/CMakeLists.txt, modules/platforms/cpp/ignite/odbc/query/column_metadata_query.h, modules/platforms/cpp/ignite/odbc/query/foreign_keys_query.cpp, modules/platforms/cpp/ignite/odbc/query/foreign_keys_query.h, modules/platforms/cpp/ignite/odbc/query/query.h, modules/platforms/cpp/ignite/odbc/query/table_metadata_query.cpp, modules/platforms/cpp/ignite/odbc/query/table_metadata_query.h, modules/platforms/cpp/ignite/odbc/query/type_info_query.h, modules/platforms/cpp/ignite/odbc/sql_statement.cpp, modules/platforms/cpp/ignite/odbc/sql_statement.h, modules/platforms/cpp/ignite/odbc/type_traits.h, modules/platforms/cpp/tests/client-test/key_value_binary_view_test.cpp, modules/platforms/cpp/tests/client-test/record_binary_view_test.cpp, modules/platforms/cpp/tests/client-test/record_view_test.cpp, modules/platforms/cpp/tests/odbc-test/api_robustness_test.cpp
- Ported solution from Ignite 2. Currently, foreign keys request returns no rows in all cases, as we do not support foreign keys on SQL level right now;
- Un-commented related test.
=> IGNITE-19217 Implement foreign keys query for ODBC 

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/IgniteResource.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/DmlPlannerTest.java
Fixes incorrect error message produced by SQL validator when a DML statement attempts to update a primary key column.
https://issues.apache.org/jira/browse/IGNITE-20600
---
- [Apache Ignite …
=> IGNITE-20600: Sql. Updating primary key column produces an incorrect error message.

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSecondaryIndexTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/RowConverter.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ScannableTableImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/SqlRowHandler.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/ExpressionFactoryImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/RangeCondition.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/bounds/RangeBounds.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/exp/ExpressionFactoryImplTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/ScannableTableSelfTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/SingleRangeIterable.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/SortedIndexSpoolExecutionTest.java
=> IGNITE-20478 Sql. Get rid of UNSPECIFIED_VALUE_PLACEHOLDER

modules/marshaller-common/src/main/java/org/apache/ignite/internal/marshaller/Marshaller.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/rpc/AbstractRpcTest.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/rpc/IgniteRpcTest.java, modules/raft/src/testFixtures/java/org/apache/ignite/raft/jraft/test/TestUtils.java
https://issues.apache.org/jira/browse/IGNITE-20545
=> IGNITE-20545 Improve logging in AbstractRpcTest

modules/client/src/test/java/org/apache/ignite/client/ClientTableTest.java
https://issues.apache.org/jira/browse/IGNITE-20576
=> IGNITE-20576 Fix testGetReturningTupleWithUnknownSchemaRequestsNewSchema

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCreateTableDdlTest.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/SchemaUtils.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/registry/UpgradingRowAdapter.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/SchemaColumnMapperTest.java
https://issues.apache.org/jira/browse/IGNITE-20724
The patch fixes two problems:
1. When deleting a column, the column mapper for reading the row of the previous schema version may have been incorrect.
2. UpgradingRowAdapter lacked support for the BOOLEAN type (IGNITE-17298), which resulted in incorrect results when reading an old version of the row.
=> IGNITE-20724 Sql. Columns mapper fix.

modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientHandlerModule.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/IdleChannelHandler.java, modules/client-handler/src/test/java/org/apache/ignite/client/handler/ClientInboundMessageHandlerTest.java, modules/client/src/test/java/org/apache/ignite/client/TestClientHandlerModule.java
Generate an ID for every client connection for diagnostics (logging, monitoring) and management purposes.
=> IGNITE-20511 Track and log client connection ID on the server

modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationChanger.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/storage/ConfigurationStorage.java, modules/configuration/src/testFixtures/java/org/apache/ignite/internal/configuration/storage/TestConfigurationStorage.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/runner/src/main/java/org/apache/ignite/internal/configuration/storage/DistributedConfigurationStorage.java, modules/runner/src/main/java/org/apache/ignite/internal/configuration/storage/LocalConfigurationStorage.java, modules/runner/src/main/java/org/apache/ignite/internal/configuration/storage/LocalFileConfigurationStorage.java
https://issues.apache.org/jira/browse/IGNITE-20866
Previously, the configuration was applied locally when the meta-storage revision was 0, leading to potential race conditions and the configuration being ignored if the revision changed.
Changes made:
- Altered the initialization logic to first check for the local revision of the configuration key.
- If the local revision is absent, the system now falls back to the initial configuration.
This fix ensures more reliable and consistent application of the cluster configuration, particularly during initialization phases where the meta storage revision is susceptible to change.
we ask both an author and a reviewer to verify the …
=> IGNITE-20866 Resolved a race condition issue in the cluster configuration initialization process

modules/platforms/dotnet/Apache.Ignite.Tests/ReconnectTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientFailoverSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientSocket.cs
`TestDroppedConnectionIsRestoredOnDemand` was flaky because in some cases we failed to retry a broken connection error.
* Close client socket immediately on write error
* Improve `ShouldRetry` logic
=> IGNITE-20832 .NET: Improve retry mechanism

modules/platforms/dotnet/Apache.Ignite.Tests/IgniteProxy.cs
Remove timeout from `IgniteProxy` - it was causing connection abort when test took longer than 5 seconds.
=> IGNITE-20920 .NET: Fix TestPutRoutesRequestToPrimaryNode flakiness

modules/platforms/dotnet/Apache.Ignite.Tests/BasicAuthenticatorTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/IgniteTestsBase.cs
Ensure that all servers have applied the configuration change, not only one.
=> IGNITE-20962 .NET: Fix TestAuthnOnClientNoAuthnOnServer flakiness

modules/client-handler/src/test/java/org/apache/ignite/client/handler/ClientPrimaryReplicaTrackerTest.java, modules/client-handler/src/testFixtures/java/org/apache/ignite/client/handler/FakePlacementDriver.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTable.java, modules/client/src/test/java/org/apache/ignite/client/PartitionAwarenessTest.java
* Use `partitionAssignmentTimestamp` and `waitForCondition` to wait for heartbeat update reliably
* Fix `FakePlacementDriver` to preserve `leaseStartTime`
* Fix `PartitionAwarenessTest.initPrimaryReplicas` to use the same `leaseStartTime` for all nodes
=> IGNITE-20963 Fix testClientReceivesPartitionAssignmentUpdates flakiness

modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientMessagePacker.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlExecuteRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlExecuteScriptRequest.java, modules/client/src/main/java/org/apache/ignite/internal/client/sql/ClientSession.java, modules/client/src/test/java/org/apache/ignite/client/ClientSqlTest.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeAsyncResultSet.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeIgniteSql.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeSession.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeSessionBuilder.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlClientAsynchronousApiTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlClientSynchronousApiTest.java
* Fix protocol - propagate session details correctly, skip `pageSize` for scripts
* Fix `ItSqlClientAsynchronousApiTest` and `ItSqlClientSynchronousApiTest` - remove overloaded methods, they were missing `@Test` annotation, and we don't need an override anyway
* Add script and properties propagation tests to `ClientSqlTest`
=> IGNITE-21011 Fix SQL script API in Java client

modules/platforms/dotnet/Apache.Ignite.Internal.Generators/ExceptionsGenerator.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/MetricsTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Sql/SqlTests.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/PlatformTestNodeRunner.java
Currently there are no public exceptions derived from `IgniteCheckedException`, but we don't want to miss them in .NET when they are added.
=> IGNITE-20568 .NET: Add support for IgniteCheckedException in ExceptionsGenerator

modules/api/src/main/java/org/apache/ignite/table/mapper/MapperBuilder.java, modules/marshaller-common/src/main/java/org/apache/ignite/internal/marshaller/Marshaller.java, modules/marshaller-common/src/testFixtures/java/org/apache/ignite/internal/marshaller/testobjects/TestObjectWithAllTypes.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientMarshallingTest.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/marshaller/asm/AsmMarshallerGenerator.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/marshaller/asm/ObjectMarshallerCodeGenerator.java
* Skip static and transient fields in `MapperBuilder`
* Propagate mapper to `ObjectMarshallerCodeGenerator` to reuse the field list
=> IGNITE-20952 Ignore static and transient fields in MapperBuilder

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlQueryProcessor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/AsyncRootNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/RootNode.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImplTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestNode.java
https://issues.apache.org/jira/browse/IGNITE-21030
* added timeout for ExecutionService shutdown
* added diagnostic information output when a timeout occurs
Current timeout set as constant 60 seconds (debatable).
Configuration will be added separately.
Diagnostic info output example:
```
Debug info for query: 08034d4d-2586-474e-86dc-bd69a3a52bfd (canceled=false, stopped=false)
Coordinator node: node_1 (current node)
Root node state: opened
Fragments awaiting init completion:
id=0, node=node_1
id=1, node=node_1
id=1, node=node_2
id=1, node=node_3
Local fragments:
id=0, state=opened, canceled=false, class=Inbox  (root)
id=1, state=opened, canceled=false, class=Outbox
```
=> IGNITE-21030 Dump debug info if the ExecutionService could not be stopped within a timeout

modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java
The cause of the flakyness was TxManager starting read-only transactions with a truncated logical part of the actual timestamp. This caused some RO transactions to not see the latest changes to the catalog.
-------------------------
\- The pull request title is treated as the final commit message. The following pattern must be used: IGNITE-XXXX Change …
=> IGNITE-21016 Sql. Fix flaky ItMixedQueriesTest.testIgniteSchemaAwaresAlterTableCommand

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTransactionConflictTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/TransactionStateResolver.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java, modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/TransactionResult.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/HeapLockManager.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/OrphanDetector.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxMessageSender.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/AbstractLockManagerEventsTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-21147
Fixed the bug with a TimeoutException on transaction finish:
See `PartitionReplicaListener.appendTxCommand`.
The issue was that an RW operation adds a cleanup future to `txOps.futures` map and the future is completed based on the result of the transaction operation future. If a transaction fails to build the latter, for example because of a lock conflict, the future in  `txOps.futures` map will never be completed. Thus a subsequent finish will wait on that future until a timeout expires.
Another bug fixed in this commit:
`TransactionStateResolver.resolveTxStateFromTxCoordinator`: If a request to a coordinator fails with an exception (see `send`), the fallback to get the state from commit partition will not be triggered.
Also added Tx …
=> IGNITE-21147 Transaction finish fails with a timeout exception

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCreateTableDdlTest.java, modules/sql-engine/src/main/codegen/includes/parserImpls.ftl, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/ddl/DdlSqlToCommandConverter.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/SqlDdlParserTest.java
Fixes SQL grammar to support `<TYPE> [NULL]` in `ALTER TABLE .. ADD COLUMN .. ` .
https://issues.apache.org/jira/browse/IGNITE-20905
--- …
=> IGNITE-20905 Make it possible to add an explicitly NULL column via ADD COLUMN

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/api/AsyncResultSetImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/api/SessionImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/api/SessionImplTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImplTest.java
https://issues.apache.org/jira/browse/IGNITE-21203
This patch addresses the race between session closing and cursor cancellation. The solution is to trigger cursors cancellation and proceed with session closing after all the cursors have been cancelled.
Also this patch fixes a race between cancellation of a query and the query initialisation when exception is thrown during root fragment initialisation.
-----------
\- The …
=> IGNITE-21203 Sql. Fix flaky ItSqlAsynchronousApiTest.closeSession

modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientPrimaryReplicaTracker.java, modules/placement-driver-api/src/main/java/org/apache/ignite/internal/placementdriver/event/PrimaryReplicaEventParameters.java
Using `consistentId` for partition awareness is ok, we don't need to change it. See detailed explanation in the JIRA comments: https://issues.apache.org/jira/browse/IGNITE-21202
=> IGNITE-21202 Un-deprecate PrimaryReplicaEventParameters.leaseholder

modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/HeapLockManager.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/AbstractLockManagerTest.java
Make HeapLockManager methods symmetrical in terms of delegating a parent lock manager.
https://issues.apache.org/jira/browse/IGNITE-21231
=> IGNITE-21231 Delegate to parent lock manager in release and iterator

modules/platforms/dotnet/Apache.Ignite.Tests/ByteArrayPoolTest.cs, modules/platforms/dotnet/Apache.Ignite.Tests/IgniteServerBase.cs, modules/platforms/dotnet/Apache.Ignite.Tests/IgniteTestsBase.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqSqlGenerationTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/LoggingTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/MetricsTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/MultiClusterTest.cs, modules/platforms/dotnet/Apache.Ignite.Tests/PartitionAwarenessRealClusterTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/ProjectFilesTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Proto/MsgPack/MsgPackReaderTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Sql/SqlResultSetObjectMappingTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Sql/SqlTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/BinaryTupleIgniteTupleAdapterTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/DataStreamerTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/IgniteTupleTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/TestUtils.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Transactions/TransactionsTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Buffers/ByteArrayPool.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Buffers/PooledBuffer.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Sql/ResultSet.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Sql/Sql.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/RecordView.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Transactions/Transaction.cs
* Add `TestSharedArrayPoolIsNotUsedDirectly` to ensure that all pooling goes through our own `ByteArrayPool` class
* Add pooled array tracking to `ByteArrayPool` and check after tests
* Fix detected leaks in core module:
* `ClientSocket.HandleResponse` when there is an error from the server or an exception
* `ClientSockeet.SendHeartbeatAsync`
* `Sql.ExecuteAsyncInternal` when there is an exception during `ResultSet` initialization
* `Transaction.CommitAsync`
* Fix many leaks in test code
=> IGNITE-21028 .NET: Fix pooled buffer leaks

modules/client/src/test/java/org/apache/ignite/client/ClientComputeTest.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeCompute.java
`JobStatus` static field in the `FakeCompute` is accessed concurrently from several executions, we need to mimic what the implementation is doing by storing statuses in the map.
https://issues.apache.org/jira/browse/IGNITE-21360
=> IGNITE-21360 Fix ClientComputeTest

modules/client/src/main/java/org/apache/ignite/client/IgniteClient.java, modules/client/src/main/java/org/apache/ignite/client/IgniteClientConfiguration.java, modules/client/src/main/java/org/apache/ignite/internal/client/IgniteClientConfigurationImpl.java, modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java, modules/client/src/test/java/org/apache/ignite/client/ConnectionTest.java, modules/client/src/test/java/org/apache/ignite/client/RetryPolicyTest.java
Add `IgniteClientConfiguration.operationTimeout`:
* 0 by default (no timeout)
* Only affects user-initiated operations; there are separate timeouts for connect and heartbeat.
=> IGNITE-20573 Java client: Add configurable operation timeout

modules/platforms/dotnet/Apache.Ignite.Tests/MetricsTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Metrics.cs, modules/platforms/dotnet/Apache.Ignite/MetricNames.cs, modules/platforms/dotnet/Apache.Ignite/Metrics.cs
Add public `MetricNames` class with a name for every metric and usage examples in XMLdoc.
Previously, as a user, you had to look at internal class source code to get a list of available metrics; now it is a part of the public API.
=> IGNITE-21268 .NET: Expose metric names as public constants

modules/platforms/dotnet/Apache.Ignite.Tests/OperationTimeoutTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/SocketTimeoutTest.cs, modules/platforms/dotnet/Apache.Ignite/IgniteClientConfiguration.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientSocket.cs
Add `IgniteClientConfiguration.OperationTimeout`:
* `Timeout.InfiniteTimeSpan` by default (no timeout)
* Only affects user-initiated operations; there are separate timeouts for connect and heartbeat.
=> IGNITE-20491 .NET: Add configurable operation timeout

modules/platforms/dotnet/Apache.Ignite.Tests/MetricsTests.cs
Relax the condition: there is no guarantee that another batch will be sent before we cancel the streamer.
=> IGNITE-21393 .NET: Fix TestDataStreamerMetricsWithCancellation flakiness

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCreateTableDdlTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlQueryProcessor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutableTableRegistryImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/IgniteTable.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/IgniteTableImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/SqlSchemaManagerImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutableTableRegistrySelfTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestTable.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/prepare/TypeCoercionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/schema/SqlSchemaManagerImplTest.java
- Updates `IgniteTable` to store the number of partitions.
- Updates `SqlQueryProcessor` to use the number of partitions stored in `IgniteTable`.
https://issues.apache.org/jira/browse/IGNITE-21396
---
\- The pull request title is treated as the final commit message. The following pattern must be used: IGNITE-XXXX Change summary where XXXX - number of …
=> IGNITE-21396: NPE SqlQueryProcessor during concurrent SELECT and DROP  TABLE.

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/cache/CaffeineCacheFactory.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/metrics/PlanningCacheMetricsTest.java
Fixes tests by running eviction tasks in the current thread.
https://issues.apache.org/jira/browse/IGNITE-21504
--- …
=> IGNITE-21504: Sql. PlanningCacheMetricsTest.plannerCacheStatisticsTest is flaky.

modules/client/src/test/java/org/apache/ignite/client/fakes/FakeTxManager.java, modules/raft-api/src/main/java/org/apache/ignite/internal/raft/service/RaftGroupListener.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/storage/snapshot/local/LocalSnapshotCopierTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItAbstractInternalTableScanTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItInternalTableReadOnlyOperationsTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ReplicasSafeTimePropagationTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/TxManager.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java
https://issues.apache.org/jira/browse/IGNITE-20826
maxObservableSafeTime is now evaluated as clock.now() + CLOCK_SKEW on each leader re-election, thus it's no longer possible to have missvalidated safeTimePropagation command that was skipped because of uninitialized watermark.
Given PR also contain several unrelates mixins:
1. Storage scan on partition restart is removed. It's no longer needed because of fully implement write intent resolution logic, including the one on recovery.
2. LocalSnapshotCopierTest#testInterrupt() enabled.
3. Obsolete closed todo removed from the code. // TODO: need to properly handle primary replica changes https://issues.apache.org/jira/browse/IGNITE-17615
=> IGNITE-20826 Add maxObservableSafeTime initialization on leader election

modules/platforms/cpp/ignite/client/detail/cluster_connection.cpp, modules/platforms/cpp/ignite/client/detail/cluster_connection.h, modules/platforms/cpp/ignite/client/detail/compute/compute_impl.cpp, modules/platforms/cpp/ignite/client/detail/response_handler.h, modules/platforms/cpp/ignite/client/detail/sql/sql_impl.cpp, modules/platforms/cpp/ignite/client/detail/table/table_impl.cpp, modules/platforms/cpp/ignite/client/detail/table/table_impl.h, modules/platforms/cpp/ignite/common/ignite_error.h, modules/platforms/cpp/ignite/protocol/utils.cpp, modules/platforms/cpp/tests/client-test/schema_synchronization_test.cpp
- Added tests;
- Found an issue in the current implementation - there was a crash if server returns a tuple with the unknown schema version;
- Re-factored `table_impl` to allow performing multiple subsequent async calls;
- Read and store known error extensions data from server;
- Retry operation with specified schema on error.
=> IGNITE-20242 Retry outdated schema error

modules/client/src/test/java/org/apache/ignite/client/fakes/FakeInternalTable.java, modules/index/src/integrationTest/java/org/apache/ignite/internal/index/ItBuildIndexTest.java, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/ItPrimaryReplicaChoiceTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteInMemoryNodeRestartTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItRaftCommandLeftInLogUntilRestartTest.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/table/NodeUtils.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/TableScanNodeExecutionTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItInternalTableReadWriteScanTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItColocationTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/InternalTable.java, modules/table/src/main/java/org/apache/ignite/internal/table/TableImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/TableRaftService.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/TableRaftServiceImpl.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImplTest.java, modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/TxAbstractTest.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-21554
- Moved raft-related methods to a separate entity - TableRaftService
- InternalTableImpl now uses the consistent way of building a replication group id
=> IGNITE-21554 Encapsulate raft-related code of InternalTable

packaging/client/java/build.gradle
The issue comes from new packaging-java-client module And it seems it's only triggered on certain configurations i.e. not 100% reproducible
We use java plugin to solve it as it contributes to dependency resolution strategies of gradle
---------------
\- The pull request title is treated as the final commit message. The following pattern must be used: …
=> IGNITE-21592 fixed resolution strategy issue when running build task

modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTableCommon.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeIgniteTables.java, modules/index/src/main/java/org/apache/ignite/internal/index/IndexManager.java, modules/index/src/test/java/org/apache/ignite/internal/index/IndexManagerTest.java, modules/platforms/dotnet/Apache.Ignite.Benchmarks/Program.cs, modules/platforms/dotnet/Apache.Ignite.Benchmarks/Table/TupleGetBenchmarks.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/schemasync/ItSchemaSyncAndReplicationTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/IgniteTablesInternal.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
* `ClientTableCommon.readTableAsync` is called on every table operation (get, put, etc), so performance is critical
* It calls `TableManager.tableAsync(int tableId)`, which performs complex async logic
* To speed this up, check cached tables in `TableManager.startedTables`, which will return a table immediately in most cases
* The table can be stopped, but that is not a problem:
* New table with the same id can't be started
* Any operation will throw an exception
Benchmarked from .NET thin client (`TupleGetBenchmarks`), ~8% improvement:
```
| Method |     Mean |   Error |  StdDev |
|------- |---------:|--------:|--------:|
|    Get | 123.6 us | 2.46 us | 5.66 us | (before)
|    Get | 113.8 us | 1.74 us | 1.45 us | (after)
```
https://issues.apache.org/jira/browse/IGNITE-20745
=> IGNITE-20745 Improve performance of ClientTableCommon.readTableAsync

build.gradle, gradle/libs.versions.toml, modules/core/src/main/java/org/apache/ignite/internal/util/BrokenPointerWrapping.java, modules/core/src/main/java/org/apache/ignite/internal/util/FeatureChecker.java, modules/core/src/main/java/org/apache/ignite/internal/util/GridUnsafe.java, modules/core/src/main/java/org/apache/ignite/internal/util/JavaNioPointerWrapping.java, modules/core/src/main/java/org/apache/ignite/internal/util/PointerWrapping.java, modules/core/src/main/java/org/apache/ignite/internal/util/WrapWithIntDirectBufferConstructor.java, modules/core/src/main/java/org/apache/ignite/internal/util/WrapWithLongDirectBufferConstructor.java, packaging/common/bootstrap-functions.sh, packaging/db/build.gradle
* DirectByteBuffer constructor signature has changed, length is now long, not int
* MethodHandle-based mechanism used on Java 11 was broken as a wrong package was used (jdk.internal.misc instead of jdk.internal.access)
https://issues.apache.org/jira/browse/IGNITE-21602
=> IGNITE-21602 Fix direct buffers allocation on Java 21

modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/IgniteTestUtils.java
The tests change a final field value. In such a situation, the corresponding IgniteTestUtils method changes the corresponding Field's modifiers to remove the final flag from them. The modifiers are changed through a MethodHandle, and on highest Java versions, a MethodHandle of a final Field now throws an UnsupportedOperationException.
It turns out, this modification of the modifiers is actually not needed on any of the currently LTS Java versions (11, 17, 21), so we just remove this in this commit.
https://issues.apache.org/jira/browse/IGNITE-21645
=> IGNITE-21645 Fix tests extending AbstractPlannerTest on Java 21

modules/client/src/main/java/org/apache/ignite/internal/client/compute/ClientCompute.java, modules/client/src/main/java/org/apache/ignite/internal/client/compute/ClientJobExecution.java, modules/client/src/main/java/org/apache/ignite/internal/client/compute/SubmitResult.java
Fix `Unpacker is closed` error due to a race condition: do not postpone response deserialization.
https://issues.apache.org/jira/browse/IGNITE-21654
=> IGNITE-21654 Fix flaky client compute tests

modules/network/src/main/java/org/apache/ignite/internal/network/NetworkMessageTypes.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/HandshakeHandler.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/MessageHandler.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryClientHandshakeManager.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryServerHandshakeManager.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/message/ProbeMessage.java, modules/network/src/test/java/org/apache/ignite/internal/network/netty/RecoveryHandshakeTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotCopierTest.java
If a channel gets opened right at the moment the server closes its server socket (but the server process still lives), the channel might look as open and alive to the client, but the server will never see it, so the handshake will not start.
Sending a probe message from the client makes sure that the client detects such a broken channel and is able to react.
https://issues.apache.org/jira/browse/IGNITE-21523
=> IGNITE-21523 Send a probe message to server when channel opens at client side

gradle/libs.versions.toml, modules/client-handler/build.gradle, modules/network/build.gradle, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotCopierTest.java
Netty uses OpenJDK internal classes to implement TLS; doing so, it uses Reflection to invoke their methods. In Java 21, one of the needed methods (set()) does not exist anymore, so OpenJDK's classes cannot be used anymore.
This commit switches to BouncyCastle by adding it to the classpath.
https://issues.apache.org/jira/browse/IGNITE-21651
=> IGNITE-21651 Fix ItSslClientHandlerTest on Java 21

modules/platforms/dotnet/Apache.Ignite.Tests/BasicAuthenticatorTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeClusterAwarenessTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTestExtensions.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/PartitionAwarenessRealClusterTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/PartitionAwarenessTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Proto/ColocationHashTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/SchemaSynchronizationTest.cs, modules/platforms/dotnet/Apache.Ignite/ClientOperationType.cs, modules/platforms/dotnet/Apache.Ignite/Compute/ICompute.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Compute/Compute.cs
Async methods (returning `Task<>`) must have async suffix.
=> IGNITE-21655 .NET: Fix async method naming in Compute API

modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/compute/ClientComputeExecuteColocatedRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/compute/ClientComputeExecuteRequest.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeCompute.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/IgniteComputeImpl.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/IgniteComputeInternal.java, modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientComputeTest.java
**Problem**: `ClientComputeExecuteColocatedRequest` retrieves the table by id, then passes the (unquoted) name to `submitColocated`, which fails.
**Fix**: we already get the table by id, no need to use the name. Extract `IgniteComputeInternal.submitColocatedInternal` method and pass the table directly.
=> IGNITE-21685 Fix client executeColocated with quoted table names

modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/BinaryTupleBuilder.java, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.Cast.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.Functions.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Linq/IgniteQueryExpressionVisitor.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Linq/MethodVisitor.cs
`inlineConstArgs` workaround is no longer needed - SQL engine has been fixed. Remove the extra logic and TODOs, update tests, create and mention tickets for unrelated decimal issues.
https://issues.apache.org/jira/browse/IGNITE-18258
=> IGNITE-18258 .NET: LINQ: Clean up inlineConstArgs logic

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSecondaryIndexTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/RexUtils.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/IndexSearchBoundsPlannerTest.java
Fixes incorrect handling of numeric literals in `RexUtils`.
https://issues.apache.org/jira/browse/IGNITE-19976
--- …
=> IGNITE-19976: Sql. ClassCastException when trying to select from indexed smallint column

modules/api/src/main/java/org/apache/ignite/table/DataStreamerOptions.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientDataStreamer.java, modules/client/src/test/java/org/apache/ignite/client/DataStreamerTest.java, modules/client/src/test/java/org/apache/ignite/client/PartitionAwarenessTest.java, modules/core/src/main/java/org/apache/ignite/internal/streamer/StreamerOptions.java, modules/core/src/main/java/org/apache/ignite/internal/streamer/StreamerSubscriber.java, modules/core/src/test/java/org/apache/ignite/internal/streamer/StreamerSubscriberTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/DataStreamer.java
* Data streamer was changed to perform per-partition batching - rename the options accordingly.
* Change the default from 4 to 1: there are multiple partitions per node, we don't want too many active requests.
=> IGNITE-21748 Rename DataStreamerOptions.perNodeParallelOperations to perPartitionParallelOperations

modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/meta/IndexMetaKey.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryMvTableStorageTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/PageMemoryIndexesTest.java
Storage does not expect that an index with the same ID will be created concurrently with being dropped.
https://issues.apache.org/jira/browse/IGNITE-21764 …
=> IGNITE-21764 Fix PersistentPageMemoryMvTableStorageTest.testIndexDestructionOnRecovery

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/CorrelatedNestedLoopJoinNode.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/ExecutionTest.java
https://issues.apache.org/jira/browse/IGNITE-21722
The problem occurs because for the left join we have not protected the loop that pushes the rows to downstream.
The following sequence occurs (**in case of disabled assertions**):
1. `CorrelatedNestedLoopJoinNode` pushes last row to downstream (FilterNode). See `joinType == JoinRelType.LEFT` branch in `join()` method.
2. `FilterNode` receives last requested row and tries to request next batch from the upstream (CorrelatedNestedLoopJoinNode).
3. `CorrelatedNestedLoopJoinNode` is in IDLE state (which is incorrect), so it submits `join()` to the execution queue.
4. `CorrelatedNestedLoopJoinNode` resets `rightInBuf`, changes state to FILLING_LEFT and requests rows from `leftsource()`.
5. Previously submitted `join()` starts executing and …
=> IGNITE-21722 Fix NPE in correlated nested loop join

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItRecordViewKeyPositionsTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/RecordViewImpl.java
Fixes RecordView::deleteAll to send key only tuples.
https://issues.apache.org/jira/browse/IGNITE-21852
--- …
=> IGNITE-21852: RecordView. RecordView deleteAll should pass key-only rows.

modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientPrimaryReplicaTracker.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTablePartitionPrimaryReplicasGetRequest.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTable.java, modules/platforms/dotnet/Apache.Ignite.Tests/FakeServer.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/DataStreamer.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Table.cs, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItKvKeyColumnPositionTest.java
Always return partition count from `ClientTablePartitionPrimaryReplicasGetRequest`, even when assignment is not available, so that per-partition batches can be initialized.
Before that we could end up with 0 partitions in `DataStreamer`, resulting in broken awareness.
Also: Fix TODOs for closed IGNITE-21768
=> IGNITE-21765 Fix streamer partition awareness

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/core/repl/executor/ItIgnitePicocliCommandsTest.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/registry/impl/JdbcUrlRegistryImpl.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/registry/impl/NodeNameRegistryImpl.java
https://issues.apache.org/jira/browse/IGNITE-21989
Changes in the test are not really related, just the clarification that `allNodeNames` returns actual list of node names.
=> IGNITE-21989 Get topology in the JDBC URL completer directly

modules/platforms/dotnet/Apache.Ignite.Tests/ProjectFilesTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/DataStreamer.cs
* Remove `Console.WriteLine` leftovers from `DataStreamer`
* Add a test to prevent console output in the core project
=> IGNITE-22025 .NET: Remove Console.WriteLine leftovers

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlOperatorsTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/sqllogic/ItSqlLogicTest.java, modules/sql-engine/src/integrationTest/sql/function/json/test_json.test, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/externalize/RelJson.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteSqlValidator.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/fun/IgniteSqlOperatorTable.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/IgniteResource.java
Adds JSON_TYPE operator to operator table. This operator is used to wrap nested json objects.
Additionally, I've disabled `FORMAT JSON` expression because it doesn't work.
https://issues.apache.org/jira/browse/IGNITE-22022
---
\- The pull request title is treated as the final commit message. The following pattern must be used: IGNITE-XXXX Change …
=> IGNITE-22022: Sql. Json object with nested object creation fails

modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryStorageEngine.java
https://issues.apache.org/jira/browse/IGNITE-22055
=> IGNITE-22055 Shut destruction executor down before closing volatile regions

modules/schema/src/main/java/org/apache/ignite/internal/schema/marshaller/MarshallerUtil.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/marshaller/reflection/ObjectStatistics.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/marshaller/KvMarshallerTest.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/marshaller/MarshallerUtilTest.java
Fixes tuple size estimation for `BigDecimal` type used by KvMarshallers, https://github.com/apache/ignite-3/pull/3493 didn't update `MarshallerUtil::getValueSize` to include additional 2 bytes for `BigDecimal` type that PR introduced.
https://issues.apache.org/jira/browse/IGNITE-21963
---
\- The pull request title is treated as the final commit …
=> IGNITE-21963: flaky KvMarshallerTest#basicTypes

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PlannerHelper.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/hints/ForceIndexHintPlannerTest.java
Wrappinternal errors during optimization in SqlExceptions.
With in code an that throws an exception in LogicalTableScanConverterRule.
Prior to fix:
> java.lang.RuntimeException: Error while applying rule LogicalTableScanConverterRule(in:NONE,out:IGNITE), args [rel#22:LogicalTableScan.NONE.any.[](table=[PUBLIC, TEST_TBL],filters=>=($t1, 10),projects=[$t0],requiredColumns={0, 1})]
After this patch:
> org.apache.ignite.sql.SqlException: IGN-CMN-65535 TraceId:041f8c94-9e3a-4569-ba9a-60de7753ef32 Unable to optimize plan due to internal error
https://issues.apache.org/jira/browse/IGNITE-21404
---
\- There is a …
=> [IGNITE-21404] Do not wrap SqlException into RuntimeException for PlannerHelper.optimize.

modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/ItClientHandlerMetricsTest.java, modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/ItClientHandlerTest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/client/src/main/java/org/apache/ignite/internal/client/ClientChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/ClientChannelFactory.java, modules/client/src/main/java/org/apache/ignite/internal/client/ReliableChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java, modules/client/src/test/java/org/apache/ignite/client/ClientMetricsTest.java, modules/client/src/test/java/org/apache/ignite/client/ObservableTimestampPropagationTest.java, modules/client/src/test/java/org/apache/ignite/internal/client/RepeatedFinishClientTransactionTest.java, modules/platforms/cpp/ignite/client/detail/node_connection.cpp, modules/platforms/cpp/ignite/client/detail/node_connection.h, modules/platforms/cpp/ignite/protocol/messages.cpp, modules/platforms/cpp/ignite/protocol/messages.h, modules/platforms/dotnet/Apache.Ignite.Tests/FakeServer.cs, modules/platforms/dotnet/Apache.Ignite.Tests/MetricsTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Transactions/TransactionsTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ConnectionContext.cs
Before this fix we propagated `observableTimestamp` to the client with every response, but not on handshake. As a result, the very first operation from the client has `observableTimestamp = 0`, which can lead to causality issues.
=> IGNITE-22086 Thin client: initialize observableTimestamp in handshake

modules/schema/src/main/java/org/apache/ignite/internal/schema/registry/UpgradingRowAdapter.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ProjectedTableRowConverterImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/TableRowConverterFactoryImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/TableRowConverterImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ProjectedTableRowConverterSelfTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/TableRowConverterSelfTest.java
=> IGNITE-21732: Sql. Split TableRowConverterImpl on two different implementations

modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/ItClientHandlerMetricsTest.java, modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/ItClientHandlerTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientMetricsTest.java
Fix tests that rely on a specific value of `IgniteProductVersion.CURRENT_VERSION`:
* `ItClientHandlerMetricsTest`: Override version in props to ensure consistent results
* `ItClientHandlerTest`: Remove response size check
* `ClientMetricsTest`: Simplify check
=> IGNITE-21962 Fix client tests relying on specific product version

modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/StripeAwareLogManager.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/NodeImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/disruptor/StripedDisruptor.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/option/LogManagerOptions.java, modules/raft/src/test/java/org/apache/ignite/disruptor/StripedDisruptorTest.java
https://issues.apache.org/jira/browse/IGNITE-22128
=> IGNITE-22128 Balancing partitions across stripes

modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/ItClusterManagerTest.java, modules/cluster-management/src/testFixtures/java/org/apache/ignite/internal/cluster/management/MockNode.java
Previously the test could fail if the following order of events occurred:
1. A cluster is restarted.
2. A node hosting the CMG starts with an empty state.
3. The other node starts with the previous state and tries to connect to the leader.
4. Initialization request arrives, Raft group starts but the second node is able to send the join request faster, than the request with the cluster state is applied.
I fixed this by first starting the CMG node, initializing it and only then starting the other node.
https://issues.apache.org/jira/browse/IGNITE-22184
\- There is a single JIRA ticket related to the pull …
=> IGNITE-22184 Fix race in ItClusterManagerTest#testJoinInvalidTag

modules/client-handler/src/main/java/org/apache/ignite/client/handler/JdbcHandlerBase.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/JdbcQueryCursorHandlerImpl.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/JdbcQueryEventHandlerImpl.java, modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcMultiStatementSelfTest.java
https://issues.apache.org/jira/browse/IGNITE-21167
In jdbc handler exception message has changed from
`Transaction control statement cannot be executed within an external transaction`
to more understandable
`Transaction control statements are not supported when autocommit mode is disabled`
`JdbcHandlerBase` abstract class was introduced to handle such errors uniformly.
=> IGNITE-21167 Sql. Jdbc. Raise a clearer error message when the tx control statement is used in non-autocommit mode

modules/sql-engine/src/integrationTest/sql/cte/test_cte.test, modules/sql-engine/src/integrationTest/sql/cte/test_cte_in_cte.test
https://issues.apache.org/jira/browse/IGNITE-21947
=> IGNITE-21947: Cover SQL T121(WITH (excluding RECURSIVE) in query expression) feature by tests

modules/runner/src/integrationTest/java/org/apache/ignite/internal/schemasync/ItSchemaSyncConfigTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/schemasync/ItSchemaSyncSingleNodeTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java
https://issues.apache.org/jira/browse/IGNITE-21801
=> IGNITE-21801 Add missing Schema Sync integration tests

modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/instance/SharedRocksDbInstance.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/instance/SharedRocksDbInstanceCreator.java
https://issues.apache.org/jira/browse/IGNITE-22210
This fixes a leak of a RocksDB resource that holds IgniteImpl from being GCed
=> IGNITE-22210 Close DBOptions in SharedRocksDbInstance#stop()

modules/platforms/dotnet/Apache.Ignite.Benchmarks/Table/DataStreamerBenchmark.cs, modules/platforms/dotnet/Apache.Ignite.Tests/FakeServer.cs, modules/platforms/dotnet/Apache.Ignite.Tests/PartitionAwarenessTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/DataStreamer.cs
1. Remove timer-based partition assignment check - is not necessary. `Table.GetPartitionAssignmentAsync` is backed by a cache with a double-checked locking, and uses a `ValueTask`, so there is no overhead in case of unchanged assignment - we can call it as often as needed.
2. Add `TestDataStreamerReceivesPartitionAssignmentUpdatesWhileStreaming` to cover this use case explicitly.
3. Reorder operations in `DataStreamer`: check partition assignment before handling the next item, not after.
Benchmark results are not affected compared to `main` branch. Updated results are caused by previous changes (#3546, #3560).
=> IGNITE-22031 .NET: Remove DataStreamer.PartitionAssignmentUpdateFrequency

modules/affinity/src/main/java/org/apache/ignite/internal/affinity/Assignments.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/PartitionReplicatorNodeRecovery.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/message/DataPresence.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/message/HasDataResponse.java, modules/table/src/main/java/org/apache/ignite/internal/utils/RebalanceUtilEx.java
https://issues.apache.org/jira/browse/IGNITE-19234
The reentry logic (see IGNITE-16668) was erroneously disabled. This commit enables it back and contains fixes required to make it work (due to changes made to the common rebalancing code since it was disabled).
=> IGNITE-19234 Enable and fix group reentry logic for volatile storages

modules/sql-engine/src/integrationTest/sql/dml/test_self_referencing.test
Self-referencing in DML operations.
https://issues.apache.org/jira/browse/IGNITE-21979
---
- [Apache Ignite Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Java+Code+Sty …
=> IGNITE-21979: Extend test coverage for SQL F781(Self-referencing operations)

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDmlTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteSqlToRelConvertor.java
https://issues.apache.org/jira/browse/IGNITE-22164
Issue description.
Schema with 2 tables.
```
TABLE TEST1(C1 INT, C2 INT)
TABLE TEST2(C1 INT, C2 INT)
```
`SqlToRelConverter` for the following insert statement
```
INSERT INTO TEST1 (C1, C2) SELECT C1, C2 FROM TEST2
```
produces the following rel node.
```
LogicalTableModify(table=[[PUBLIC, TEST1]], operation=[INSERT], flattened=[false])
LogicalProject(C1=[$0], C2=[$1])
LogicalTableScan(table=[[PUBLIC, TEST2]])
```
But if we swap columns C1 and C2.
```
INSERT INTO TEST1 (C2, C1) SELECT C2, C1 FROM TEST2
```
the result will be
```
LogicalTableModify(table=[[PUBLIC, TEST1]], operation=[INSERT], flattened=[false])
LogicalTableScan(table=[[PUBLIC, TEST2]])
```
`convertMerge()` expects projection in the input of table modify node and fails …
=> IGNITE-22164 Sql. Fixed conversion from SqlMerge AST to relational expression when columns defined in different order.

modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/DefaultLogStorageFactory.java, modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/ColumnFamily.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/instance/SharedRocksDbInstance.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/instance/SharedRocksDbInstanceCreator.java
Ticket: https://issues.apache.org/jira/browse/IGNITE-22240
=> IGNITE-22240 Improve handling for RocksDb resources in DefaultLogStorage and SharedRocksDbInstance

modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
JIRA ticket: [IGNITE-22355 | `TableManagerTest`'s static mocks from `#mockManagersAndCreateTableWithDelay` don't work properly](https://issues.apache.org/jira/browse/IGNITE-22355)
**Description**
In tests table creation method there is code like below:
```java
try (MockedStatic<AffinityUtils> affinityServiceMock = mockStatic(AffinityUtils.class)) {
ArrayList<List<ClusterNode>> assignment = new ArrayList<>(PARTITIONS);
for (int part = 0; part < PARTITIONS; part++) {
assignment.add(new ArrayList<>(Collections.singleton(node)));
}
affinityServiceMock.when(() -> AffinityUtils.calculateAssignments(any(), anyInt(), anyInt()))
.thenReturn(assignment);
}
```
As the result `AffinityUtils#calculateAssignments` calls outside of try-with-resources returns list of empty sets, but desired behavior is …
=> IGNITE-22355 TableManagerTest's static mocks from #mockManagersAndCreateTableWithDelay don't work properly

modules/client-common/src/main/java/org/apache/ignite/internal/jdbc/proto/event/JdbcBatchExecuteResult.java, modules/client-common/src/main/java/org/apache/ignite/internal/jdbc/proto/event/JdbcColumnMeta.java, modules/client-common/src/main/java/org/apache/ignite/internal/jdbc/proto/event/JdbcConnectResult.java, modules/client-common/src/main/java/org/apache/ignite/internal/jdbc/proto/event/JdbcMetaColumnsResult.java, modules/client-common/src/main/java/org/apache/ignite/internal/jdbc/proto/event/JdbcMetaPrimaryKeysResult.java, modules/client-common/src/main/java/org/apache/ignite/internal/jdbc/proto/event/JdbcMetaSchemasResult.java, modules/client-common/src/main/java/org/apache/ignite/internal/jdbc/proto/event/JdbcMetaTablesResult.java, modules/client-common/src/main/java/org/apache/ignite/internal/jdbc/proto/event/JdbcQueryCloseResult.java, modules/client-common/src/main/java/org/apache/ignite/internal/jdbc/proto/event/JdbcQueryFetchResult.java, modules/client-common/src/main/java/org/apache/ignite/internal/jdbc/proto/event/JdbcQuerySingleResult.java, modules/client-common/src/main/java/org/apache/ignite/internal/jdbc/proto/event/JdbcTableMeta.java, modules/client-common/src/main/java/org/apache/ignite/internal/jdbc/proto/event/Response.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/JdbcHandlerBase.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/JdbcQueryCursorHandlerImpl.java, modules/client-handler/src/test/java/org/apache/ignite/client/handler/JdbcQueryCursorHandlerImplTest.java, modules/client-handler/src/test/java/org/apache/ignite/client/handler/JdbcQueryEventHandlerImplTest.java, modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc/JdbcConnection.java, modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc/JdbcDatabaseMetadata.java, modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc/JdbcPreparedStatement.java, modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc/JdbcQueryExecuteResponse.java, modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc/JdbcResultSet.java, modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc/JdbcStatement.java, modules/jdbc/src/test/java/org/apache/ignite/internal/jdbc/JdbcResultSetTest.java, modules/platforms/cpp/ignite/odbc/meta/table_meta.cpp, modules/platforms/cpp/ignite/odbc/query/column_metadata_query.cpp, modules/platforms/cpp/ignite/odbc/query/primary_keys_query.cpp, modules/platforms/cpp/ignite/odbc/query/table_metadata_query.cpp
https://issues.apache.org/jira/browse/IGNITE-22413
This patch addresses an issue when 2 additional *unnecessary* roundtrips were issued in JDBC driver on every consequent invocation of method `execute` on (Prepared-)Statement.
Below are results of benchmark runs on my laptop (MBP M3, 5 performance and 6 efficiency cores, 36GB):
```
Results before
Benchmark                   (clusterSize)  Mode  Cnt    Score   Error  Units
SelectBenchmark.jdbcGet                 1  avgt   20  145.237 ± 1.838  us/op
SelectBenchmark.sqlThinGet              1  avgt   20   60.506 ± 0.375  us/op
Results after 
Benchmark                   (clusterSize)  Mode  Cnt   Score   Error  Units
SelectBenchmark.jdbcGet                 1  avgt   20  84.314 ± 0.288  us/op
SelectBenchmark.sqlThinGet              1  avgt   20 …
```
=> IGNITE-22413 Jdbc. Reduce amount of roundtrips on statement execution

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDmlTest.java
Adds java tests for DROP default.
https://issues.apache.org/jira/browse/IGNITE-21974
--- 
- [Apache Ignite Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Java+Code+Styl …
=> IGNITE-21974: Extend test coverage for SQL F221(Explicit defaults)

modules/core/src/main/java/org/apache/ignite/internal/event/EventListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexMeta.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexMetaStorage.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/index/BaseIndexMetaStorageTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/index/IndexMetaStorageRecoveryTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/index/IndexMetaStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-22470
=> IGNITE-22470 Switch IndexMetaStorage from Vault to MetaStorage

modules/sql-engine/src/integrationTest/sql/types/char/test_implicit_cast.test, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/TypeUtils.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/util/TypeUtilsTest.java
Fixes a bug in `TypeUtils` that incorrectly skips `NULL` values.
https://issues.apache.org/jira/browse/IGNITE-22451
--- …
=> IGNITE-22451: Sql. An insert may cause specific later updates to fail. Affects only char/varchar

modules/platforms/cpp/tests/client-test/compute_test.cpp
https://issues.apache.org/jira/browse/IGNITE-22422
It looks like on newer JDK versions string representation of the floats varies a little. Check both variants.
=> IGNITE-22422 C++ Fix compute_test.all_arg_types flakiness

modules/platforms/dotnet/Apache.Ignite.Tests/PartitionAwarenessTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/DataStreamerTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/KeyValueView.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/RecordView.cs, modules/platforms/dotnet/Apache.Ignite/Table/IDataStreamerTarget.cs, modules/platforms/dotnet/Apache.Ignite/Table/ReceiverDescriptor.cs
Similar to #3971, add `ReceiverDescriptor` to .NET.
* Non-generic class for receiver without results
* Generic class for receiver with results
This also removes the need for the user to specify generic arguments. Before: `view.StreamDataAsync<SourceClass, PayloadClass, ResultClass>(...)`, after `view.StreamDataAsync(...)` - type arguments are inferred by the compiler from the receiver class.
=> IGNITE-22540 .NET: Add ReceiverDescriptor to Data Streamer

modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/impl/RocksDbSpillout.java
https://issues.apache.org/jira/browse/IGNITE-22761
=> IGNITE-22761 Disable WAL in RocksDB used to spill volatile Raft logs on disk

docs/_docs/developers-guide/clients/cpp.adoc, modules/table/src/test/java/org/apache/ignite/internal/benchmarks/UpdateCommandsMarshallingMicroBenchmark.java
`Marshaller` and `marshalling` should be spelled with 2 `l`s.
Most places were fixed in #4100.
https://issues.apache.org/jira/browse/IGNITE-22791
=> IGNITE-22791 Fix marshaller spelling

modules/client/src/main/java/org/apache/ignite/internal/client/ClientChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/ReliableChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/TcpIgniteClient.java, modules/client/src/test/java/org/apache/ignite/client/ObservableTimestampPropagationTest.java, modules/client/src/test/java/org/apache/ignite/client/PartitionAwarenessTest.java, modules/client/src/test/java/org/apache/ignite/client/RetryPolicyTest.java, modules/platforms/dotnet/Apache.Ignite.Tests/IgniteClientTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/MetricsTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/TestUtils.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Transactions/TransactionsTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientFailoverSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/ClientSocket.cs, modules/platforms/dotnet/Apache.Ignite/Internal/IgniteClientInternal.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientConnectionTest.java
Add internal heartbeat API with optional payload for benchmarking to Java and .NET clients.
=> IGNITE-22642 Add internal heartbeat API to Java and .NET clients

modules/platforms/dotnet/Directory.Build.props
Build will fail if a security vulnerability is detected in any package in the dependency graph (direct or transitive).
=> IGNITE-22751 .NET: Enable NuGet audit

modules/api/src/main/java/org/apache/ignite/compute/IgniteCompute.java, modules/api/src/main/java/org/apache/ignite/compute/TaskDescriptor.java, modules/api/src/main/java/org/apache/ignite/compute/task/MapReduceTask.java, modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientMessagePacker.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/compute/ClientComputeExecuteMapReduceRequest.java, modules/client/src/main/java/org/apache/ignite/client/ClientOperationType.java, modules/client/src/main/java/org/apache/ignite/internal/client/compute/ClientCompute.java, modules/client/src/test/java/org/apache/ignite/client/ClientComputeTest.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeCompute.java, modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItComputeBaseTest.java, modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItMapReduceTest.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/AntiHijackIgniteCompute.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/IgniteComputeImpl.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientComputeMarshallingTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientComputeTest.java
Similar to `JobDescriptor`, add `TaskDescriptor` for MapReduce method family, to keep the API consistent.
=> IGNITE-22847 Add TaskDescriptor to Сompute API

modules/platforms/dotnet/Apache.Ignite.Benchmarks/Apache.Ignite.Benchmarks.csproj, modules/platforms/dotnet/Apache.Ignite.Benchmarks/Table/Serialization/SerializerHandlerReadBenchmarks.cs, modules/platforms/dotnet/Apache.Ignite.Internal.Generators/Apache.Ignite.Internal.Generators.csproj, modules/platforms/dotnet/Apache.Ignite.Internal.Generators/ExceptionsGenerator.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Apache.Ignite.Tests.csproj, modules/platforms/dotnet/Apache.Ignite.Tests/ConsoleLogger.cs, modules/platforms/dotnet/Apache.Ignite.Tests/ListLogger.cs, modules/platforms/dotnet/Apache.Ignite/Apache.Ignite.csproj, modules/platforms/dotnet/Apache.Ignite/Compute/JobTarget.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Network/ConnectionInfo.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Network/SslInfo.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Sql/ColumnMetadata.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Sql/ColumnOrigin.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Sql/ResultSetMetadata.cs, modules/platforms/dotnet/Apache.Ignite/Table/ReceiverDescriptor.cs, modules/platforms/dotnet/Directory.Build.props
**Build-only** dependencies:
* StyleCop.Analyzers `1.2.0-beta.435` -> `1.2.0-beta.556`
* Microsoft.CodeAnalysis.Analyzers `3.3.3` -> `3.3.4`
* JetBrains.Annotations `2023.3.0` -> `2024.2.0`
**Test-only** dependencies:
* Microsoft.Extensions.Logging.Console `6.0.0` -> `8.0.0`
* MessagePack `2.1.90` -> `2.5.171`
* BenchmarkDotNet `0.13.1` -> `0.13.12`
Runtime dependencies are not affected.
=> IGNITE-21595 .NET: Update dependencies

modules/client-handler/src/testFixtures/java/org/apache/ignite/client/handler/FakePlacementDriver.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientPartitionManager.java, modules/client/src/test/java/org/apache/ignite/client/AbstractClientTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientPartitionManagerTest.java, modules/client/src/test/java/org/apache/ignite/client/PartitionAwarenessTest.java, modules/client/src/test/java/org/apache/ignite/client/ReconnectTest.java, modules/client/src/test/java/org/apache/ignite/client/TestServer.java, modules/client/src/test/java/org/apache/ignite/client/benchmarks/ClientPutGetBenchmark.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeIgnite.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeIgniteTables.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeInternalTable.java
* Remove hardcoded one-minute cache timeout 
* Use `ReliableChannel.partitionAssignmentTimestamp` to invalidate the cache (relies on `PARTITION_ASSIGNMENT_FLAG` response flag)
=> IGNITE-22678 Java thin: fix ClientPartitionManager cache invalidation

packaging/client/cpp/build.gradle
Add `-cpp` part to C++ client package name to make it clear what kind of client it is.
=> IGNITE-22752 Fix C++ package name

modules/platforms/dotnet/Apache.Ignite.Tests/Table/BinaryTupleIgniteTupleAdapterTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/IgniteTupleTests.cs, modules/platforms/dotnet/Apache.Ignite/Table/IIgniteTuple.cs
Fix .NET `IIgniteTuple` equality logic to match Java - ignore column order in `Equals` and `GetHashCode`.
=> IGNITE-22934 .NET: Fix tuple equality - ignore column order

modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/BinaryTupleBuilder.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/marshaller/MarshallerUtil.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/marshaller/asm/AsmMarshallerGenerator.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/row/RowAssembler.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/marshaller/MarshallerUtilTest.java, modules/table/src/main/java/org/apache/ignite/internal/schema/marshaller/TupleMarshallerImpl.java, modules/table/src/test/java/org/apache/ignite/internal/benchmarks/TupleMarshallerFixlenOnlyBenchmark.java, modules/table/src/test/java/org/apache/ignite/internal/benchmarks/TupleMarshallerVarlenOnlyBenchmark.java, modules/table/src/test/java/org/apache/ignite/internal/schema/marshaller/TupleMarshallerStatisticsTest.java
https://issues.apache.org/jira/browse/IGNITE-22941
```
Benchmark                                   (character)  (dataSize)  (fieldsCount)             (type)  Mode  Cnt          Before           After  Units
TupleMarshallerVarlenOnlyBenchmark.measure            a         250              2  PREDEFINED_STRING  avgt   20   0.706 ± 0.001   0.397 ± 0.001  us/op
TupleMarshallerVarlenOnlyBenchmark.measure            a         250             10  PREDEFINED_STRING  avgt   20   1.649 ± 0.005   1.207 ± 0.004  us/op
TupleMarshallerVarlenOnlyBenchmark.measure            a         250            100  PREDEFINED_STRING  avgt   20  13.485 ± 0.043  13.022 ± 0.018  us/op
TupleMarshallerVarlenOnlyBenchmark.measure            a       64000              2  PREDEFINED_STRING  avgt   20  72.666 ± 0.301   4.390 …
```
=> IGNITE-22941 Improve performance of TupleMarshaller

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogTableDescriptor.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogTableTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/IgniteIndex.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/SqlSchemaManagerImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/schema/SqlSchemaManagerImplTest.java
Introduces a cache for indexes (indexId, indexStatus) and a full table data cache (catalog version, tableId) that includes all table related information.
The number of IgniteTableImpl in java heap after 110 tables were created:
https://issues.apache.org/jira/browse/IGNITE-22757
---
\- The pull request title is treated as the final commit message. The …
=> IGNITE-22757: Excessive memory usage in schema-related code in SQL

modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNodeCollocated.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestThreeNodesThreeReplicasCollocated.java, modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java
JIRA Ticket: [IGNITE-22774 | Remove raftClient map from ItTxTestCluster](https://issues.apache.org/jira/browse/IGNITE-22774)
The goal is to remove `raftClient` from `ItTxTestCluster`.
All raft-clients are created inside replicas through `ReplicaManager#startReplica`, and most of usages of `raftClient` are effectively useless
1. The map `raftClients` is removed.
2. `getLeader` and related assertions are removed. 
3. `getLeaderId` method is rewritten as following:
```java
int partId = 0;
return replicaManagers.get(extractConsistentId(cluster.get(partId)))
.replica(new TablePartitionId(tables.get(tableName).tableId(), partId))
.thenApply(replica -> replica.raftClient().leader())
.join();
```
4. Replicas are stopped instead of raft-clients from the map as following:
```java
for (String …
```
=> IGNITE-22774 Remove `raftClient` map from `ItTxTestCluster`

.idea/inspectionProfiles/Project_Default.xml, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItMetadataTest.java, modules/sql-engine/src/integrationTest/sql/basic_queries/rename_columns_in_from.test, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteAliasNamespace.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteSqlValidator.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/TableDescriptor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/TableDescriptorImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/AbstractPlannerTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/CorrelatedSubqueryPlannerTest.java
https://issues.apache.org/jira/browse/IGNITE-22772
This patch introduces proper handling of system/hidden columns during column renaming in `FROM` clause (`SELECT * FROM my_table AS new_name(new_c1, new_c2, ...)`). Provided solution has one limitation: it's impossible to rename system columns directly. But this limitation has workaround: table may be replaced with sub-select explicitly mentioning system columns in SELECT clause (see last test case in `rename_columns_in_from.test`). 
-------------
\- The web-link to the pull request is attached to …
=> IGNITE-22772 Sql. Fix row type derivation for renaming in FROM clause

modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientBinaryTupleUtils.java, modules/client/src/test/java/org/apache/ignite/client/ClientTableTest.java, modules/core/src/main/java/org/apache/ignite/internal/type/DecimalNativeType.java, modules/core/src/main/java/org/apache/ignite/internal/type/NativeType.java, modules/core/src/main/java/org/apache/ignite/internal/type/NativeTypeSpec.java, modules/core/src/main/java/org/apache/ignite/internal/type/TemporalNativeType.java, modules/core/src/main/java/org/apache/ignite/internal/type/VarlenNativeType.java, modules/core/src/test/java/org/apache/ignite/internal/type/NativeTypeSpecTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientMarshallingTest.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/Column.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/row/RowAssembler.java, modules/table/src/test/java/org/apache/ignite/internal/table/MutableRowTupleAdapterTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/RecordBinaryViewOperationsTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/type/NumericTypesSerializerTest.java
Fixes error message for a column type mismatch error in KV/Record View APIs.
https://issues.apache.org/jira/browse/IGNITE-22873
--- …
=> IGNITE-22873: InvalidTypeException should not include a value in its error message

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/Replica.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaImpl.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ZonePartitionReplicaImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
JIRA Ticket: [IGNITE-22851 | Move raft client's update configuration process into replicas](https://issues.apache.org/jira/browse/IGNITE-22851)
The main goal is to remove all calls `RaftGroupService#updateConfiguration` from `TableManager`.
There should no any raft client usages inside `TableManager`.
1. Method Replica#updateConfiguration is introduced.
2. All calls like `raftClient -> raftClient.updateConfiguration(...)` are replaced with `replica -> replica.updateConfiguration(...)`
---
\- The web-link to the pull request is attached to the JIRA …
=> IGNITE-22851 Move raft client's update configuration process into replicas

modules/compute/src/main/java/org/apache/ignite/internal/compute/executor/ComputeExecutorImpl.java, modules/platforms/dotnet/Apache.Ignite.Benchmarks/Apache.Ignite.Benchmarks.csproj, modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Marshalling/JsonMarshallerTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Proto/BinaryTuple/BinaryTupleTests.cs, modules/platforms/dotnet/Apache.Ignite/Compute/JobDescriptor.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Buffers/PooledArrayBuffer.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Compute/Compute.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/BinaryTuple/BinaryTupleBuilder.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/HashUtils.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/MsgPack/MsgPackReader.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/MsgPack/MsgPackWriter.cs, modules/platforms/dotnet/Apache.Ignite/Marshalling/IMarshaller.cs, modules/platforms/dotnet/Apache.Ignite/Marshalling/JsonMarshaller.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/PlatformTestNodeRunner.java
Public API changes:
* Add `IMarshaller<T>` interface
* Unlike Java, we don't operate on `byte[]`, but use `IBufferWriter<byte>` and `ReadOnlySpan<byte>`, which allow reading/writing directly from/to underlying `BinaryTuple` without extra allocations and copying. 
* Those APIs work directly and efficiently with modern serializers, such as `System.Text.Json`
* Add `JsonMarshaller` 
* Unlike Java, we don't need a third-party library for JSON, so an out-of-the box implementation with good defaults and performance makes sense.
* Add `JobDescriptor.ArgMarshaller`, `JobDescriptor.ResultMarshaller`
=> IGNITE-22644 .NET: Add JobDescriptor.Marshaller

modules/core/src/main/java/org/apache/ignite/internal/util/IgniteSpinReadWriteLock.java, modules/core/src/main/java/org/apache/ignite/internal/util/VersatileReadWriteLock.java, modules/core/src/test/java/org/apache/ignite/internal/util/IgniteSpinReadWriteLockTest.java, modules/core/src/test/java/org/apache/ignite/internal/util/VersatileReadWriteLockTest.java
https://issues.apache.org/jira/browse/IGNITE-22989
=> IGNITE-22989 Add sync/async read-write lock

modules/compute/src/main/java/org/apache/ignite/internal/compute/ComputeJobFailover.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/IgniteComputeImpl.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/messaging/ComputeMessaging.java
https://issues.apache.org/jira/browse/IGNITE-22995 
The reason why this test can hang is that when we execute broadcast job in the embedded mode on the same node that has been used as an entry point to the job call (for example, call job from node 1 and on node 1,2) -- then we failed to detect local node because of the wrong usage of ClientNode.equals method.
=> IGNITE-22995 Fix compute broadcast hanging test

modules/platforms/dotnet/Apache.Ignite.Tests/LoggingTests.cs
Close synchronized writer to avoid race condition while accessing results.
=> IGNITE-22794 .NET: Fix TestMicrosoftConsoleLogger flakiness

modules/api/src/main/java/org/apache/ignite/table/IgniteTables.java, modules/api/src/main/java/org/apache/ignite/table/KeyValueView.java, modules/api/src/main/java/org/apache/ignite/table/RecordView.java, modules/api/src/main/java/org/apache/ignite/table/Table.java, modules/table/src/main/java/org/apache/ignite/internal/table/InternalTable.java
1. Remove "started table" term, "table" is enough
2. Remove "binary object" mentions
3. Explain how KV view projects row data into key-value pairs
4. Replace "Transaction or null to auto-commit" with "Transaction or null for implicit transaction"
5. Remove "@throws IgniteException If an unspecified platform exception has occurred internally", it is not useful
6. Describe the order of tables in tables() and tablesAsync()
https://issues.apache.org/jira/browse/IGNITE-22267
=> IGNITE-22267 Improve Table API javadocs

modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/server/raft/ItMetaStorageRaftGroupTest.java
https://issues.apache.org/jira/browse/IGNITE-22986
Storage was closed before RAFT server and a running thread was trying to access the already closed RocksDB storage, which resulted in a crash.
=> IGNITE-22986 Close storage after RAFT

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java
JIRA Ticket: [IGNITE-22622 | PartitionReplicaLifecycleManager must use weakStart/weaskStop approach](https://issues.apache.org/jira/browse/IGNITE-22622)
The main goal of the ticket is to wrap start and stop zone replicas inside of `PartitionReplicaLifecycleManager` processes with weak start/stop.
Weak start and stop are saving us from replicas deletion while a replica may was primary.
Inside `PartitionReplicaLifecycleManager` all entries of `startReplica` and `stopReplica` are wrapped with `weakStartReplica` and `weakStopReplica` respectively.
Also there was fixed an issue in related test: before the fix zeroth node is registered as cluster node with consistent and local identifiers that are node name. Local name is UUID and the described code is a mistake.
---
Thank you for submitting …
=> IGNITE-22622 PartitionReplicaLifecycleManager must use weakStart/weaskStop approach

modules/client/src/main/java/org/apache/ignite/client/IgniteClientConnectionException.java, modules/client/src/main/java/org/apache/ignite/internal/client/ClientChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/ReliableChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/io/netty/NettyClientConnectionMultiplexer.java, modules/client/src/test/java/org/apache/ignite/client/ConnectionTest.java, modules/client/src/test/java/org/apache/ignite/internal/client/RepeatedFinishClientTransactionTest.java
* Add `IgniteClientConnectionException#endpoint` so that there is a mandatory constructor parameter
* Add endpoint to the exception message
* Propagate endpoints from call sites
=> IGNITE-22984 Java thin: Add endpoint info to connection errors

modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java, modules/client/src/test/java/org/apache/ignite/client/ConnectionTest.java, modules/core/src/main/java/org/apache/ignite/internal/future/timeout/TimeoutObject.java, modules/core/src/main/java/org/apache/ignite/internal/future/timeout/TimeoutWorker.java, modules/network/src/main/java/org/apache/ignite/internal/network/DefaultMessagingService.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/IgniteRpcClient.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/FeatureTimeoutBenchmark.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/FutureTimeoutBenchmark.java
**FeatureTimeoutBenchmark**
```
*  Results on 11th Gen Intel® Core™ i7-1165G7 @ 2.80GHz, openjdk 11.0.24, Windows 10 Pro:
* Benchmark                     (useFutureEmbeddedTimeout)  Mode  Cnt   Score    Error  Units
* FeatureTimeoutBenchmark.test                       false  avgt   20   1,501 ±  0,058  us/op
* FeatureTimeoutBenchmark.test                        true  avgt   20  32,573 ± 47,598  us/op
```
https://issues.apache.org/jira/browse/IGNITE-20869
=> IGNITE-20869 Got rid of using CompletableFuture#orTimeout method on operations hot path

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/CliIntegrationTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/ItConnectToClusterTestBase.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/connect/ItConnectCommandTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/connect/ItConnectNonReplCommandTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/sql/ItSqlReplCommandNotInitializedClusterTest.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/Main.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/ReplManager.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/call/connect/ConnectCall.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/call/connect/ConnectionChecker.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/connect/ConnectCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/questions/ConnectToClusterQuestion.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/SqlCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/SqlReplCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/Repl.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/ReplBuilder.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/SessionInfo.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/executor/ReplExecutorImpl.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/cliconfig/ConfigManagerTest.java, modules/cli/src/testFixtures/java/org/apache/ignite/internal/cli/commands/cliconfig/TestConfigManagerHelper.java
https://issues.apache.org/jira/browse/IGNITE-22781
=> IGNITE-22781 Fix question during connect to a node

modules/sql-engine/src/integrationTest/sql/cast/test_cast_decimal.test, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/IgniteSqlFunctions.java
Updates numeric overflow error message to `Numeric field overflow. A field with precision 5, scale 0 must round to an absolute value less than 10^5.`
https://issues.apache.org/jira/browse/IGNITE-22160
---
\- The pull request title is treated as the final commit message. The following pattern must be used: IGNITE-XXXX Change summary where XXXX - number …
=> IGNITE-22160: Sql. Usability of error message in case of numeric overflow

modules/catalog-compaction/src/test/java/org/apache/ignite/internal/catalog/compaction/CatalogCompactionRunnerSelfTest.java
https://issues.apache.org/jira/browse/IGNITE-23078
The test runs compaction and expects that the earliest version of catalog will change from 0 to N at once.
But versions are stored in `ConcurrentSkipListMap`, when we trim the catalog we clear the head of this map.
And while trimming this map we can observe an earliest version between 0 and N, which looks valid and shouldn't be a problem.
Therefore, the test has been fixed to wait for the required version (ver == N), instead non zero version (ver != 0).
=> IGNITE-23078 Fix flaky test CatalogCompactionRunnerSelfTest.mustNotPerformWhenAssignmentNodeIsMissing.

modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/TestServer.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientHandlerModule.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClusterInfo.java, modules/client/src/test/java/org/apache/ignite/client/TestClientHandlerModule.java, modules/client/src/test/java/org/apache/ignite/client/TestServer.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterState.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/system-disaster-recovery/build.gradle, modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItCmgDisasterRecoveryTest.java, modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryStorage.java
https://issues.apache.org/jira/browse/IGNITE-22883
Whole history of cluster IDs is passed the client handler so it can pass it to clients when they connect to allow them do cluster ID validation, but support cluster ID change (due to CMG repair).
=> IGNITE-22883 Send all cluster IDs to thin client on connection

modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/help/SqlHelpCommand.java
https://issues.apache.org/jira/browse/IGNITE-23136
Color scheme for the help is also adjusted to match the picocli default style:
=> IGNITE-23136 Duplicate commands in sql help

modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerRecoveryTest.java
`TableManagerRecoveryTest.workDir` hides a field from superclass, which prevents junit version update:
```
org.apache.ignite.internal.table.distributed.TableManagerRecoveryTest.initializationError
java.lang.IllegalStateException: Test class must have a single field of type 'java.nio.file.Path' annotated with '@WorkDirectory', but 2 fields have been found
```
Remove the field, it is not needed.
=> IGNITE-23158 Remove redundant TableManagerRecoveryTest#workDir

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java, modules/raft-api/src/main/java/org/apache/ignite/internal/raft/IndexWithTerm.java, modules/raft-api/src/main/java/org/apache/ignite/internal/raft/RaftManager.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/Loza.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/server/RaftServer.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/Node.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/NodeImpl.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/system-disaster-recovery-api/src/main/java/org/apache/ignite/internal/disaster/system/message/MetastorageIndexTermRequestMessage.java, modules/system-disaster-recovery-api/src/main/java/org/apache/ignite/internal/disaster/system/message/MetastorageIndexTermResponseMessage.java, modules/system-disaster-recovery/build.gradle, modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItMetastorageIndexGettingTest.java, modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/ClusterIdService.java, modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImpl.java, modules/system-disaster-recovery/src/test/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImplTest.java
https://issues.apache.org/jira/browse/IGNITE-22900
=> IGNITE-22900 Implement ability to get MG index+term from node

modules/runner/src/main/java/org/apache/ignite/internal/configuration/storage/LocalFileConfigurationStorage.java, packaging/docker/docker-compose.yml, packaging/docker/node.Dockerfile
https://issues.apache.org/jira/browse/IGNITE-23142
Issue is fixed by providing a config with text content. Requires Docker Compose version 2.23.1.
Logging is also added to help debug these issues.
=> IGNITE-23142 Docker compose example doesn't save config

modules/platforms/build.gradle
* Add Gradle task to run .NET tests: `./gradlew dotnetTest`
* If any test fails, the task fails
* Starts test cluster automatically, unless already started (e.g. you can debug Java side of things by running `PlatformTestNodeRunner` under a debugger, then starting `dotnetTest`)
=> IGNITE-22048 .NET: Add Gradle task to run tests

modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/DefaultLogStorageFactory.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/RocksDbSharedLogStorage.java
https://issues.apache.org/jira/browse/IGNITE-23180
What was done: 
set fsync in writeOptions (if it's not set, then fsync=false is used regardless of DBOptions), moved writeOptions creation to factory
\- The pull request title is treated as the final commit message. The following pattern must be used: IGNITE-XXXX Change summary where XXXX - number of …
=> IGNITE-23180 Fix fsync setting for RocksDbSharedLogStorage

modules/metastorage/build.gradle, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMaintenanceTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesAbstractTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesRocksDbTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesSimpleStorageTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesVsStorageTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageLeaderElectionListener.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetastorageGroupMaintenance.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/system-disaster-recovery-api/src/main/java/org/apache/ignite/internal/disaster/system/message/BecomeMetastorageLeaderMessage.java, modules/system-disaster-recovery/build.gradle, modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImpl.java, modules/system-disaster-recovery/src/test/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImplTest.java
https://issues.apache.org/jira/browse/IGNITE-22903
When BecomeMetastorageLeaderMessage is received:
* make the current node the leader of the Metastorage group by forcing the voting members set to only consist of the current node
* stop managing learners and propagating safe-time if requested by the message (useful as an optimization to avoid 2-step configuration change when the target MG voting set consists of just 1 node)
=> IGNITE-22903 Handle BecomeMetastorageLeaderMessage

modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.Cast.cs
Increase timeout from default 15s to 90s.
Decimal handling is very slow due to [IGNITE-23170](https://issues.apache.org/jira/browse/IGNITE-23170), will be fixed by [IGNITE-18922](https://issues.apache.org/jira/browse/IGNITE-18922)
=> IGNITE-23177 .NET: Increase SQL decimal tests timeout

modules/platforms/dotnet/Apache.Ignite.Tests/Linq/LinqTests.Cast.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Sql/SqlTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Linq/IgniteQueryExpressionVisitor.cs
Limit decimal scale to 30 when performing a cast in generated SQL - .NET `decimal` has 28-29 digit precision and can't represent bigger scales.
Default scale is 32767, which causes performance issues ([IGNITE-23170](https://issues.apache.org/jira/browse/IGNITE-23170)).
With this fix, `TestCastToDecimalPrecision` and other decimal SQL tests now run in milliseconds instead of minutes.
=> IGNITE-23204 .NET: LINQ: Limit decimal scale to 30

modules/core/src/main/java/org/apache/ignite/internal/future/timeout/TimeoutWorker.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMaintenanceTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageLeaderElectionListener.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/raft/MetaStorageWriteHandler.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/RaftGroupServiceImpl.java
https://issues.apache.org/jira/browse/IGNITE-23206
* If an elected leader is same as before, still update term used for Metastorage Idle SafeTime propagation
* Fix a race condition in test which was giving false positives. That is, we now make sure that 'old' SafeTime advancements (made before pausing secondary duties) are waited out before checking that no new advancements happen
* Improve logging
=> IGNITE-23206 Update term used for Metastorage idle SafeTime propagation on leadership refresh

modules/placement-driver/build.gradle, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/ActiveActorTest.java, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/MultiActorPlacementDriverTest.java, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/PlacementDriverManagerTest.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/PlacementDriverManager.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/LeaseNegotiationTest.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/LeaseUpdaterTest.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/configuration/ReplicationConfigurationSchema.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
https://issues.apache.org/jira/browse/IGNITE-23081
=> IGNITE-23081 Add lease expiration time to configuration

modules/core/src/main/java/org/apache/ignite/internal/util/BrokenPointerWrapping.java, modules/core/src/main/java/org/apache/ignite/internal/util/FeatureChecker.java, modules/core/src/main/java/org/apache/ignite/internal/util/GridUnsafe.java, modules/core/src/main/java/org/apache/ignite/internal/util/JavaNioPointerWrapping.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/logit/LogitLogStorageFactory.java
JIRA Ticket: [IGNITE-23221](https://issues.apache.org/jira/browse/IGNITE-23221)
The main goal is to remove obsolete links on Apache Ignite documentation website.
We should use proper up-to-date documentation warning messages for our users.
The only place that contains a link with the noticed prefix https://apacheignite.readme.io/ is JAVA_VER_WARN variable that is used for user's notification about Java version specific startup parameters. But for now we're supporting only Java 11+, so at most the message is obsolete and we should to inform a user about proper JVM's startup parameters with a link on a proper documentation about Ignite startup but 3.0.0-beta version until release: https://ignite.apache.org/docs/3.0.0-beta/quick-start/getting-started-guide 
Also the constant itself was …
=> IGNITE-23221 Update a message about java version and jvm startup params 

modules/catalog/build.gradle, modules/catalog/src/integrationTest/java/org/apache/ignite/internal/catalog/it/ItConcurrentDdlsTest.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java
https://issues.apache.org/jira/browse/IGNITE-23220
Each DDL tries to make a write to the Metastorage. Each write is assigned a sequential number (version); if a few DDLs try to write to the Metastorage, they will all compete for the same version, and only one of them can succeed. This competition is wasteful. This commit avoids such concurrency on the same node by explicitly linearizing writes to the Metastorage from the Catalog before doing them.
=> IGNITE-23220 Avoid concurrent Catalog writes to Metastorage on the same node

build.gradle
To fix build failures caused by Gradle bug (https://github.com/gradle/gradle/issues/30601), remove `mavenLocal()` from Gradle repositories.
Build time is not affected - 31 minutes is same as main branch: https://ci.ignite.apache.org/buildConfiguration/ApacheIgnite3xGradle_Test_RunAllTests/8480930?hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true&expandBuildDeploymentsSection=false&expandCode+Inspection=true
https://issues.apache.org/jira/browse/IGNITE-23228
=> IGNITE-23228 Remove mavenLocal repository from Gradle

modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientBinaryTupleUtils.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientMarshallingTest.java, modules/table/src/main/java/org/apache/ignite/internal/schema/marshaller/TupleMarshallerImpl.java
* Fix NPE when assertions are disabled
* Throw `MarshallerException` with descriptive message
* Add test for client and embedded modes
=> IGNITE-23157 Improve column value type validation when serializing Tuples

modules/client/src/main/java/org/apache/ignite/internal/client/io/netty/NettyClientConnection.java, modules/client/src/main/java/org/apache/ignite/internal/client/io/netty/NettyClientConnectionMultiplexer.java
Pass the original address to `NettyClientConnection` to avoid using `channel.remoteAddress()`, which can return null on disconnect. We want have the address for logging and debugging purposes even after disconnect.
=> IGNITE-23133 Java thin: fix NPE in handshakeRes

modules/client/src/main/java/org/apache/ignite/internal/client/table/AbstractClientStreamerPartitionAwarenessProvider.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTable.java
Data streamer does not accept data while schema and partition count are loading.
Cache table partition count on client to speed up data streamer startup. Fresh assignment is not required to initialize streamer buffers.
=> IGNITE-23262 Java thin: cache table partition count

modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/NodeImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/impl/LogManagerImpl.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/storage/impl/LogManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-23132
In this PR we change a behaviour of `org.apache.ignite.raft.jraft.storage.impl.LogManagerImpl#getLastLogIndex(boolean)` and 
`org.apache.ignite.raft.jraft.storage.impl.LogManagerImpl#getLastLogId` so they do not fail with NPE if were invoked after `org.apache.ignite.raft.jraft.storage.impl.LogManagerImpl#shutdown`, but they throw `IllegalStateException` 
\- The description of …
=> IGNITE-23132 fix NullPointerException in LogManagerImpl

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java, modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItCmgDisasterRecoveryTest.java, modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItSystemGroupDisasterRecoveryTest.java
https://issues.apache.org/jira/browse/IGNITE-22783
Handling of CMG network messages may cause I/O and hence must be offloaded to its own thread pool to avoid blocking network threads
=> IGNITE-22783 Handle CMG-related network messages in CMG thread pool

modules/client/build.gradle, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeCompute.java, modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItComputeTestStandalone.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/ComputeUtils.java
https://issues.apache.org/jira/browse/IGNITE-23165
This fix expands the error message in case deployment units list was empty to help debug cases when user forgot to provide deployment units when submitting a job.
=> IGNITE-23165 Improve error message when deployment unit is not provided

modules/compute/src/main/java/org/apache/ignite/internal/compute/ComputeJobFailover.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/IgniteComputeImpl.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/messaging/ComputeMessaging.java, modules/compute/src/test/java/org/apache/ignite/internal/compute/ComputeComponentImplTest.java, modules/compute/src/test/java/org/apache/ignite/internal/compute/IgniteComputeImplTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/ItInProcessRestartApiReferencesTest.java
https://issues.apache.org/jira/browse/IGNITE-23233
Compare cluster nodes by consistent id rather than id when determining whether the execution should be local or remote.
Send the network messages by consistent id.
=> IGNITE-23233 Fix infinite recursion in RemoteJobExecution#stateAsync()

modules/client/src/main/java/org/apache/ignite/internal/client/ReliableChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTable.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/api/PublicApiClientKeyValueView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/api/PublicApiClientRecordView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/api/PublicApiClientViewBase.java
Avoid unnecessary jump to `asyncContinuationExecutor` for synchronous client API operations.
Local benchmark result shows ~8% improvement:
```
Benchmark                  (clusterSize)  (fsync)  (useSyncOptimization)  Mode  Cnt   Score   Error  Units
SelectBenchmark.kvThinGet              1    false                   true  avgt   20  86,590 ± 2,708  us/op
SelectBenchmark.kvThinGet              1    false                  false  avgt   20  94,047 ± 0,979  us/op
```
https://issues.apache.org/jira/browse/IGNITE-22842
=> IGNITE-22842 Improve synchronous client API performance

packaging/db/zip/ignite.java.util.logging.properties
https://issues.apache.org/jira/browse/IGNITE-23375
There's a separate log configuration for the deb/rpm/msi packages in the `packaging/db/ignite.java.util.logging.properties` which logs to the file only.
The configuration for docker in the `packaging/docker/ignite.java.util.logging.properties` logs to console only.
The zip distribution configuration in the `packaging/zip/ignite.java.util.logging.properties` logs to both file and console.
=> IGNITE-23375 Write logs to console and file in zip distribution

modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTable.java, modules/client/src/test/java/org/apache/ignite/client/ConnectionTest.java
* Restore `try (var unpacker = new ClientMessageUnpacker(buf)) {` in `onMessage` (entry point)
* Add `retain()` where needed
Adding `retain()` in places where the buffer escapes current thread is easier than hunting leaks (forgotten `release` calls).
https://issues.apache.org/jira/browse/IGNITE-23374
=> IGNITE-23374 Java thin: Fix Netty buffer leak

modules/core/src/main/java/org/apache/ignite/internal/util/VersatileReadWriteLock.java, modules/core/src/test/java/org/apache/ignite/internal/util/VersatileReadWriteLockTest.java
https://issues.apache.org/jira/browse/IGNITE-23381
* When async attempt to acquire a write lock is handled, lock acquisition could be registered twice
* Write unlocking logic could corrupt read lock count
* A test was flaky because it did not account for asynchrony
=> IGNITE-23381 Fix excessive locking in VersatileReadWriteLock

modules/platforms/cpp/ignite/tuple/binary_tuple_builder.cpp, modules/platforms/cpp/ignite/tuple/binary_tuple_builder.h
The old calculation in `fits` could result in a signed integer overflow. The new version uses two comparisons combined with a logical and, but the compiler is smart enough to generate even better code than for the old version.
If append_bytes is called with an empty view memcpy could be called with a nullptr which ubsan complained about, even though we are not copying anything.
\- The description of the JIRA ticket explains …
=> IGNITE-23405 Fix some issues reported by undefined behavior sanitizer

modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java, modules/client/src/test/java/org/apache/ignite/client/ClientComputeTest.java
* Add checks for `CompletableFuture#complete` results - when false, the future is already completed by another thread (e.g. channel is closing), so the buffer has to be released.
* Use `asyncContinuationExecutor` for notifications, add test.
=> IGNITE-23396 Fix Netty buffer leak on client

modules/client/src/test/java/org/apache/ignite/client/DataStreamerTest.java
Reduce `perPartitionParallelOperations` to avoid exhausting retry count.
=> IGNITE-23367 Fix testManyItemsWithDisconnectAndRetry flakiness

modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/ItClientHandlerMetricsTest.java, modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/ItClientHandlerTest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientComputeTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientConnectionTest.java
https://issues.apache.org/jira/browse/IGNITE-22865
- Added hint if the `clientConnector.sendServerExceptionStackTraceToClient` is set to `false`;
- Added test.
=> IGNITE-22865 Add a hint to enable the full stack trace

modules/core/src/main/java/org/apache/ignite/internal/hlc/HybridTimestamp.java, modules/low-watermark/src/main/java/org/apache/ignite/internal/lowwatermark/LowWatermarkImpl.java, modules/low-watermark/src/test/java/org/apache/ignite/internal/lowwatermark/LowWatermarkImplTest.java
https://issues.apache.org/jira/browse/IGNITE-23437
=> IGNITE-23437 Do not use ByteUtils#toBytes to persist timestamps in LowWatermark

modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/recovery/system/ResetClusterRequest.java, modules/rest/src/main/java/org/apache/ignite/internal/rest/recovery/system/SystemDisasterRecoveryController.java, modules/rest/src/test/java/org/apache/ignite/internal/rest/recovery/system/SystemDisasterRecoveryControllerTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManager.java, modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImpl.java, modules/system-disaster-recovery/src/test/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImplTest.java
https://issues.apache.org/jira/browse/IGNITE-22896
=> IGNITE-22896 REST API for initiating MG repair

modules/catalog-compaction/build.gradle, modules/catalog-compaction/src/integrationTest/java/org/apache/ignite/internal/catalog/compaction/ItCatalogCompactionTest.java, modules/catalog-compaction/src/main/java/org/apache/ignite/internal/catalog/compaction/CatalogCompactionRunner.java, modules/catalog-compaction/src/main/java/org/apache/ignite/internal/catalog/compaction/message/CatalogCompactionMinimumTimesResponse.java, modules/catalog-compaction/src/test/java/org/apache/ignite/internal/catalog/compaction/AbstractCatalogCompactionTest.java, modules/catalog-compaction/src/test/java/org/apache/ignite/internal/catalog/compaction/CatalogCompactionRunnerSelfTest.java, modules/index/src/main/java/org/apache/ignite/internal/index/IndexNodeFinishedRwTransactionsChecker.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/ActiveLocalTxMinimumRequiredCatalogTimeProvider.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/ActiveLocalTxMinimumRequiredTimeProvider.java
https://issues.apache.org/jira/browse/IGNITE-22975
`ActiveLocalTxMinimumBeginTimeProvider` (renamed `ActiveLocalTxMinimumRequiredTimeProvider`) now returns not the minimum start time among transactions, but the minimum time corresponding to the activation time of the earliest catalog version required by active transactions.
This change significantly reduces the time a write lock is held and makes it independent of the number of active transactions. For example, for 100 000 active transactions, the previous method could hold a lock for about 1_000_000 nanoseconds (on my PC), the current method for the same number of transactions holds a lock for about 50 nanoseconds.
=> IGNITE-22975 Improve detection of minimum catalog version required by active transactions

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/connect/ItConnectCommandTest.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/cluster/ClusterUrlMixin.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/connect/ConnectCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/connect/ConnectReplCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/node/NodeUrlMixin.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/node/NodeUrlProfileMixin.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/cluster/migrate/MigrateToClusterMixin.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/converters/RestEndpointUrlConverter.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/cluster/config/ClusterConfigReplTest.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/cluster/config/ClusterConfigTest.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/node/config/NodeConfigReplTest.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/node/config/NodeConfigTest.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/recovery/cluster/migrate/MigrateToClusterCommandReplTest.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/recovery/cluster/migrate/MigrateToClusterCommandTest.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/recovery/partitions/restart/RestartPartitionsTest.java
https://issues.apache.org/jira/browse/IGNITE-23267
=> IGNITE-23267 Trailing slash in the node URL results in an error

modules/client/src/test/java/org/apache/ignite/client/ClientMetricsTest.java
Get rid of heartbeats in `testRequestsMetrics` to ensure consistent request count.
=> IGNITE-23258 Fix testRequestsMetrics flakiness

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItTablesApiTest.java
https://issues.apache.org/jira/browse/IGNITE-23481
=> IGNITE-23481 Remove useless ItTablesApiTest#testGetTableFromLaggedNode.

modules/core/src/main/java/org/apache/ignite/internal/hlc/ClockService.java, modules/core/src/main/java/org/apache/ignite/internal/hlc/ClockServiceImpl.java, modules/core/src/main/java/org/apache/ignite/internal/hlc/HybridClock.java, modules/core/src/main/java/org/apache/ignite/internal/hlc/HybridClockImpl.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/TestHybridClock.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/hlc/TestClockService.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
https://issues.apache.org/jira/browse/IGNITE-23314
```
Benchmark                (clusterSize)  (fsync)  (useCurrentTime)   Mode  Cnt       Score       Error  Units
SelectBenchmark.kvGet                1    false              true  thrpt   20  111516.766 ±  4852.060  ops/s
SelectBenchmark.kvGet                1    false             false  thrpt   20  106539.353 ±  7714.372  ops/s
SelectBenchmark.kvGet8               1    false              true  thrpt   20  392582.275 ± 19418.875  ops/s
SelectBenchmark.kvGet8               1    false             false  thrpt   20  360583.874 ± 17743.514  ops/s
SelectBenchmark.kvGet16              1    false              true  thrpt   20  504817.362 ± 33241.876  ops/s
SelectBenchmark.kvGet16              1    false             false  thrpt   20  446573.687 …
```
=> IGNITE-23314 PartitionReplicaListener#ensureReplicaIsPrimary does not require to use hybrid timestamp

modules/index/src/test/java/org/apache/ignite/internal/index/IndexAvailabilityControllerTest.java
https://issues.apache.org/jira/browse/IGNITE-23520
=> IGNITE-23520 Fix flaky IndexAvailabilityControllerTest#testMetastoreKeysAfterDropIndexWithTwoRemainingPartitions

modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTuple.java, modules/client/src/test/java/org/apache/ignite/client/ClientKeyValueBinaryViewTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientTupleTest.java
When `ClientTuple` wraps a full row but represents only key or value part, don't allow accessing the columns from the other part by name.
P.S. There is no such problem in .NET, because we don't use BinaryTuple wrapper for KV API. Ticket created: IGNITE-23537
=> IGNITE-23164 Improve ClientTuple validation for KV view

modules/platforms/dotnet/Apache.Ignite.Tests/LoggingTests.cs
Remove flaky assertions. Those log messages can vary when secondary connections are established very quickly.
https://issues.apache.org/jira/browse/IGNITE-23140
=> IGNITE-23140 .NET: Fix TestBasicLogging flakiness

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterStatePersistentSerializer.java, modules/core/src/main/java/org/apache/ignite/internal/replicator/PartitionGroupId.java, modules/core/src/main/java/org/apache/ignite/internal/replicator/ReplicationGroupId.java, modules/core/src/main/java/org/apache/ignite/internal/replicator/TablePartitionId.java, modules/core/src/main/java/org/apache/ignite/internal/versioned/VersionedSerializer.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/Lease.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/LeaseBatch.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/LeaseBatchSerializer.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/NodesDictionary.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/leases/LeaseBatchSerializerTest.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/leases/LeaseSerializationTest.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/leases/NodesDictionaryTest.java, modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/ResetClusterMessagePersistentSerializer.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/ManualGroupRestartRequestSerializer.java
https://issues.apache.org/jira/browse/IGNITE-23496
Apart from removing Java Serialization (which might make it more difficult to maintain backwards compatibility), new serialization is more compact and faster.
For the case of 1000 tables (25 partitions each) and 3 nodes in cluster, the gain in the number of bytes is approximately 30 times:
>Old 4710568 bytes, new 240456 bytes
Performance has also improved (serializing and deserializing same batch of 25000 leases):
```
Benchmark                                         Mode  Cnt      Score      Error  Units
LeaseBatchSerializationBenchmark.deserializeNew   avgt   15   1443,554 ±   52,776  us/op
LeaseBatchSerializationBenchmark.deserializeOld   avgt   15  67598,438 ± 2111,874  us/op
LeaseBatchSerializationBenchmark.serializeNew     avgt   15 …
```
=> IGNITE-23496 Optimize lease batch serialization

modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/distributionzones/ItDistributionZonesFiltersTest.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/distributionzones/ItIgniteDistributionZoneManagerNodeRestartTest.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/AugmentationSerializer.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DataNodesMapSerializer.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZonesUtil.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/LogicalTopologySetSerializer.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/Node.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/NodeSerializer.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/NodeWithAttributes.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/NodeWithAttributesSerializer.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/NodesAttributesSerializer.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/TopologyAugmentationMapSerializer.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/causalitydatanodes/CausalityDataNodesEngine.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DataNodesMapSerializerTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/LogicalTopologySetSerializerTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/NodeWithAttributesSerializerTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/NodesAttributesSerializerTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/TopologyAugmentationMapSerializerTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/causalitydatanodes/DistributionZoneCausalityDataNodesTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngineTest.java, modules/distribution-zones/src/testFixtures/java/org/apache/ignite/internal/distributionzones/DistributionZonesTestUtil.java
https://issues.apache.org/jira/browse/IGNITE-23484
=> IGNITE-23484 Do not use ByteUtils#toBytes in zones management

modules/platforms/dotnet/version.json
Disable `setVersionVariables` in GitVersioning config to fix docfx build hang.
More details: https://github.com/dotnet/docfx/issues/10144
=> IGNITE-23575 Fix docfx build on CI

modules/client/src/main/java/org/apache/ignite/client/RetryLimitPolicy.java, modules/client/src/test/java/org/apache/ignite/client/ConnectionTest.java, modules/client/src/test/java/org/apache/ignite/client/DataStreamerTest.java, modules/client/src/test/java/org/apache/ignite/client/HeartbeatTest.java, modules/client/src/test/java/org/apache/ignite/client/SchemaUpdateTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/streamer/ItClientDataStreamerLoadTest.java
It was not possible to disable retries previously, 0 meant infinite retries and 1 meant 1 retry. Some tests were using incorrect values.
Change to:
* -1 for infinite retries
* 0 for disabled retries
* N for max N retries
=> IGNITE-23456 Fix RetryLimitPolicy behavior

modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/distributionzones/ItIgniteDistributionZoneManagerNodeRestartTest.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngine.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/WatchProcessor.java, modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/impl/StandaloneMetaStorageManager.java
https://issues.apache.org/jira/browse/IGNITE-23661
Long story short, the stack trace of a problem is following:
1. `assertTrue(waitForCondition(() -> newLogicalTopology.equals(finalDistributionZoneManager.logicalTopology())` fails because `finalDistributionZoneManager.logicalTopology()` is not updated because 
2. `notificationFuture` in `WatchProcessor#notifyWatches()` is not completed because `notifyUpdateRevisionFuture` is not completed because 
3. `assert causalityToken > lastCompleteToken` in `org.apache.ignite.internal.causality.IncrementalVersionedValue#completeInternal` isn't matched (but not logged though) because
4. watch events are reordered by revision despite the fact that they are properly ordered by timestamp, see `org.apache.ignite.internal.metastorage.server.NotifyWatchProc …
=> IGNITE-23661 Eliminate race in onBeforeApply within StandaloneMetaStorageManager

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/raft/PartitionSnapshotMeta.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/MvPartitionMeta.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/MvTableStorage.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/PrimitivePartitionMeta.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/ThreadAssertingMvTableStorage.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvPartitionStorage.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/AbstractPageMemoryTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/VolatilePageMemoryMvPartitionStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorage.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/AccessPartitionMeta.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/PartitionAccess.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/PartitionAccessImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/PartitionSnapshotStorageFactory.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/RaftSnapshotPartitionMeta.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotCopier.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/outgoing/OutgoingSnapshot.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/outgoing/SnapshotMetaUtils.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/NullMvTableStorage.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotCopierTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/outgoing/OutgoingSnapshotCommonTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/outgoing/SnapshotMetaUtilsTest.java
https://issues.apache.org/jira/browse/IGNITE-23379
=> IGNITE-23379 Pass lease information with Raft snapshot of partition

modules/client/src/main/java/org/apache/ignite/internal/client/ClientTimeoutWorker.java, modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java, modules/client/src/test/java/org/apache/ignite/client/ClientMetricsTest.java, modules/client/src/test/java/org/apache/ignite/client/ConnectionTest.java, modules/core/src/main/java/org/apache/ignite/internal/future/timeout/TimeoutWorker.java, modules/core/src/test/java/org/apache/ignite/internal/future/timeout/TimeoutWorkerTest.java, modules/network/src/main/java/org/apache/ignite/internal/network/DefaultMessagingService.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/FutureTimeoutBenchmark.java
Use shared timeout worker for all client channels within the JVM instead of one worker per channel.
The worker starts on demand, and shuts down if there are no active channels during some period of time.
https://issues.apache.org/jira/browse/IGNITE-23076
=> IGNITE-23076 Add shared timeout worker for all client channels

modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java, modules/client/src/test/java/org/apache/ignite/client/ClientMetricsTest.java, modules/client/src/test/java/org/apache/ignite/client/ConnectionTest.java, modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java
* Make sure all cleanup steps are performed
* Handle exception in `sock.close()` - we don't care about network issues when closing the channel
=> IGNITE-23569 Fix TcpClientChannel.close reliability

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointMetricsTracker.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/Checkpointer.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointMetricsTrackerTest.java
https://issues.apache.org/jira/browse/IGNITE-23701
=> IGNITE-23701 Add output of execution duration LogSyncer to message "Checkpoint finished"

modules/table/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java
https://issues.apache.org/jira/browse/IGNITE-23690
Occurred that it's a test issue: test will fail if node with index 2 that we knock out is primary.
=> IGNITE-23690 Fix ItTableRaftSnapshotsTest.txSemanticsIsMaintained.

modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItComputeBaseTest.java, modules/compute/src/jobs/java/org/apache/ignite/internal/compute/SilentSleepJob.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/FailSafeJobExecution.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/queue/QueueExecutionImpl.java, modules/compute/src/test/java/org/apache/ignite/internal/compute/queue/PriorityQueueExecutorTest.java
https://issues.apache.org/jira/browse/IGNITE-23696
Complete result future exceptionally when cancellation was requested before the job completion.
=> IGNITE-23696 Fix return result for remote execution

modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItComputeTestStandalone.java
https://issues.apache.org/jira/browse/IGNITE-19623
It's unclear why they were disabled, it doesn't seem like they were using custom user objects.
=> IGNITE-19623 Compute: enable tests

modules/platforms/cpp/tests/client-test/compute_test.cpp
Now the check does not assert, but throws an exception instead,  that we can handle accordingly in the test body.
=> IGNITE-23175 Fix all_arg_types test for Java 21

modules/platforms/dotnet/Apache.Ignite.Tests/IgniteClientGroupTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/IgniteServerBase.cs, modules/platforms/dotnet/Apache.Ignite.Tests/ReconnectTests.cs
Add `IgniteServerBase.AllowMultipleConnections` (default false) to speed up tests based on `FakeServer`.
=> IGNITE-23757 .NET: Fix TestDroppedConnectionsAreRestoredInBackground flakiness

modules/core/src/main/java/org/apache/ignite/internal/type/TemporalNativeType.java, modules/core/src/main/java/org/apache/ignite/internal/type/VarlenNativeType.java, modules/core/src/test/java/org/apache/ignite/internal/type/NativeTypeTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/util/TypeUtilsTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/InteropOperationsTest.java
Fixes `equals` method of `TemporalNativeType` and `VarlenNativeType `.
https://issues.apache.org/jira/browse/IGNITE-23704
--- …
=> IGNITE-23704: Incorrect equal implementation in TemporalNativeType and VarlenNativeType

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftService.java, modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManagerTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageServiceImpl.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/impl/MetaStorageDeployWatchesCorrectnessTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerRecoveryTest.java, modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/impl/StandaloneMetaStorageManager.java, modules/raft-api/src/main/java/org/apache/ignite/internal/raft/service/RaftCommandRunner.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/ExecutorInclinedRaftCommandRunner.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/RaftGroupServiceImpl.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/RetryContext.java, modules/raft/src/test/java/org/apache/ignite/internal/raft/ExecutorInclinedRaftCommandRunnerTest.java, modules/replicator/src/main/java/org/apache/ignite/internal/raft/client/TopologyAwareRaftGroupService.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/ItIgniteStartTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/storage/InternalTableEstimatedSizeTest.java
https://issues.apache.org/jira/browse/IGNITE-23754
Also, TimeoutException from Raft client is enriched with information about current and original commands
=> IGNITE-23754 Do not fail initialized node start because of CMG or MG unavailability

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/BaseSqlMultiStatementTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlQueriesSystemViewTest.java
https://issues.apache.org/jira/browse/IGNITE-23733
The problem is that the test code assumed that the cursor closing and the removal of this query from the registry (`QueryExecutor.runningQueries`) were synchronized but this is not true.
So the test must take into account that after closing the cursor we can observe the query among running for some time.
=> IGNITE-23733 Sql. Fix flaky test ItSqlQueriesSystemViewTest.multiStatement

modules/core/src/main/java/org/apache/ignite/internal/hlc/HybridClockImpl.java, modules/core/src/test/java/org/apache/ignite/internal/hlc/HybridClockTest.java, modules/core/src/test/java/org/apache/ignite/internal/hlc/benchmarks/HybridClockBenchmark.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/HeapLockManager.java
```
Before
Benchmark                                            Mode  Cnt       Score      Error  Units
HybridClockBenchmark.hybridClockNowFiveThreads      thrpt   10   37536.317 ± 2033.320  ops/s
HybridClockBenchmark.hybridClockNowSingleThread     thrpt   10  238352.974 ± 4753.761  ops/s
HybridClockBenchmark.hybridClockNowTenThreads       thrpt   10   34136.852 ±  283.247  ops/s
HybridClockBenchmark.hybridClockUpdateFiveThreads   thrpt   10   14143.705 ±  365.301  ops/s
HybridClockBenchmark.hybridClockUpdateSingleThread  thrpt   10  124273.226 ± 3827.199  ops/s
HybridClockBenchmark.hybridClockUpdateTenThreads    thrpt   10    9028.719 ±  249.099  ops/s
After
Benchmark                                            Mode  Cnt       Score      Error  Units …
```
=> IGNITE-23707 Optimize update() in hybrid clocks

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListener.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/raft/MetaStorageListener.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/raft/MetaStorageWriteHandler.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/ZonePartitionRaftListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java
https://issues.apache.org/jira/browse/IGNITE-23834
* Currently, these implementations only let the client know about some exceptions occurring when executing write commands, but JRaft is not notified, so application of subsequent commands is not prohibited. This might cause state machines diverge in the same group if some command fails on just one of the machines. This commit makes sure that the state machine is marked as broken if something is thrown when executing a command
* Busy locks usage is improved (they were not actually protecting the machines from applying commands even when the locks were blocked) …
=> IGNITE-23834 Avoid state machines divergence due to permissive error handling

modules/api/src/main/java/org/apache/ignite/table/TupleImpl.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/ClassDescriptorFactory.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/Classes.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/SpecialSerializationMethodsImpl.java, modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerWithSerializableTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/MutableRowTupleAdapterTest.java
https://issues.apache.org/jira/browse/IGNITE-23825
There were two problems:
* `TupleImpl` doesn't declare `writeObject` so the `StructuredObjectMarshaller.fillStructuredObjectLayerFrom` method doesn't call `readObject` to properly deserialize it.
* `ClassDescriptorFactory` doesn't search for the `writeReplace` method in superclasses.
\- The pull …
=> IGNITE-23825 Returning Tuple from table fails

modules/core/src/test/java/org/apache/ignite/internal/lang/IgniteExceptionTest.java, modules/platforms/dotnet/Apache.Ignite.Tests/ErrorGroupTests.cs, modules/platforms/dotnet/Apache.Ignite/ErrorGroups.cs, modules/platforms/dotnet/Apache.Ignite/IgniteException.cs
* Use unchecked context to calculate error codes
* Add missing `IgniteException.GroupCode`
* Add tests in .NET and Java to ensure consistent behavior
=> IGNITE-23786 .NET: Fix OverflowException on ErrorGroups.Common.Internal

modules/client/src/main/java/org/apache/ignite/internal/client/io/netty/NettyClientConnectionMultiplexer.java, modules/security/src/integrationTest/java/org/apache/ignite/internal/ssl/ItSslTest.java
Initialize `SslContext` earlier to capture error details.
=> IGNITE-23916 Java thin: fix SSL error details propagation

modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/TestCluster.java
https://issues.apache.org/jira/browse/IGNITE-23821
INSTALLING_SNAPSHOT is discarded only when
- a snapshot is installed correctly
- if a leader dies and a new one is elected, the new leader installs new snapshot
- when the node is restarted (INSTALLING_SNAPSHOT is stored in memory only)
In other cases INSTALLING_SNAPSHOT will remain forever.
=> IGNITE-23821 Check whether INSTALLING_SNAPSHOT will not be discarded on leader stop

modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/cluster/init/ClusterInitOptions.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/CliCommandTestBase.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/ProfileMixinTest.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/cluster/ClusterInitTest.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/cluster/config/ConfigUpdateCommandTest.java
https://issues.apache.org/jira/browse/IGNITE-23935
Options in the mixin classes should use `NULL_VALUE` default value.
The tests are refactored so that the command line object is not recreated on each execution so that the added tests are actually fail without the fix.
=> IGNITE-23935 Cluster init command use previous config

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/sql/ItSqlMultistatementTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/sql/ItSqlReplCommandTest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/JdbcHandlerBase.java, modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcComplexDmlDdlSelfTest.java, modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcKillCommandTest.java, modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcMultiStatementSelfTest.java, modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcStatementSelfTest.java, modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcUpdateStatementSelfTest.java
https://issues.apache.org/jira/browse/IGNITE-23965
=> IGNITE-23965 Sql.  JDBC update counter for DDL/KILL statements must always be zero.

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/CliIntegrationTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/ItVerbosityReplTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/ItVerbosityTest.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/BaseCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/Options.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/call/AbstractCallExecutionPipeline.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/call/AsyncCallExecutionPipeline.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/call/AsyncCallExecutionPipelineBuilder.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/call/CallExecutionPipelineBuilder.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/call/SingleCallExecutionPipeline.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/call/SingleCallExecutionPipelineBuilder.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/flow/builder/FlowBuilder.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/flow/builder/FlowBuilderImpl.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/rest/ApiClientFactory.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/logger/CliLoggers.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/logger/HttpLogging.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/flow/FlowTest.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/core/call/PipelineTest.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/logger/CliLoggersTest.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/logger/HttpLoggingTest.java
https://issues.apache.org/jira/browse/IGNITE-23938
Verbose option is extended so that a single option prints requests and responses, second one adds headers, third one adds bodies.
Also fixed an issue when verbose wasn't working in non-REPL mode.
=> IGNITE-23938 Add verbose levels in CLI

modules/platforms/dotnet/Directory.Build.props
Switch to SDK-based analyzers.
=> IGNITE-23978 .NET: Remove NetAnalyzers from public dependencies

modules/catalog-compaction/build.gradle, modules/catalog-compaction/src/test/java/org/apache/ignite/internal/catalog/compaction/CatalogCompactionRunnerSelfTest.java
https://issues.apache.org/jira/browse/IGNITE-24047
Need to conditionally wait until the versions map is truncated, similarly to other tests in `CatalogCompactionRunnerSelfTest`.
=> IGNITE-24047 Fixed flaky test CatalogCompactionRunnerSelfTest.rebalancePreventsCompaction

modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-23899
The errors were caused by the intricate process of mocking and setting up components. Any change to catalog before TableManager is started leads to missed notifications and diverged indexes.
=> IGNITE-23899 Get rid of AssertionErrors in test

modules/compute/src/main/java/org/apache/ignite/internal/compute/task/TaskExecutionInternal.java
https://issues.apache.org/jira/browse/IGNITE-24008
When cancelling map reduce task, we need to cancel dependent future manually, it might not be cancelled when we cancel the queue execution.
=> IGNITE-24008 Properly cancel map reduce task

modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcKillCommandTest.java, modules/sql-engine/build.gradle, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlApiBaseTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCancelQueryTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCancelScriptTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlQueriesSystemViewTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/kill/ItSqlKillCommandTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlQueryProcessor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/fsm/Query.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/fsm/QueryExecutor.java, modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/BaseSqlIntegrationTest.java, modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/engine/util/SqlTestUtils.java
https://issues.apache.org/jira/browse/IGNITE-23939
To achieve consistent behavior between query cancellation and script cancellation, query cancellation should only wait the termination phase and don't wait until the query is removed from the running queries registry.
Note: fixed tests to conditionally wait until the query is removed from the registry.
p.s. the main change have been made in `Query` and `QueryExecutor` classes.
=> IGNITE-23939 Query cancellation should wait for the query termination phase only

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java
https://issues.apache.org/jira/browse/IGNITE-24109
=> IGNITE-24109 Ignore NodeStoppingException in ReplicaManager#sendSafeTimeSyncIfReplicaReady()

modules/raft/src/main/java/org/apache/ignite/internal/raft/RaftGroupServiceImpl.java, modules/raft/src/test/java/org/apache/ignite/internal/raft/RaftGroupServiceTest.java
https://issues.apache.org/jira/browse/IGNITE-24112
=> IGNITE-24112 Retry in RaftGroupServiceImpl on a RecipientLeftException

build.gradle, buildscripts/java-junit5.gradle
https://issues.apache.org/jira/browse/IGNITE-24122
Also, decrease default heap sizes for unit and integration tests to 1g and 2g, respectively
=> IGNITE-24122 Add -Xmx1g to defaultJvmArgs

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlUsesKeyValueGetTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlUsesSelectCountOptimizedTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/datatypes/ItCastToIntWithoutFastQueryOptimizationTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/CacheKey.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/KeyValueGetPlan.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/KeyValueModifyPlan.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/Commons.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/DmlPlannerTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/DynamicParametersTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/ImplicitCastsTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/PartitionPruningMetadataTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/SelectCountPlannerTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/util/QueryCheckerTest.java
https://issues.apache.org/jira/browse/IGNITE-24134
Results as follow:
```
Before
Benchmark               (clusterSize)  (fsync)  Mode  Cnt  Score   Error  Units
SelectBenchmark.kvGet               1    false  avgt   20  3.238 ± 0.185  us/op
SelectBenchmark.sqlGet              1    false  avgt   20  5.889 ± 0.143  us/op
After
SelectBenchmark.sqlGet              1    false  avgt   20  4.805 ± 0.068  us/op
Before
Benchmark                          (clusterSize)  (fsync)  (partitionCount)  (replicaCount)  Mode  Cnt   Score   Error  Units
InsertBenchmark.kvInsert                       1    false                24               1  avgt   20  38.814 ± 9.475  us/op
InsertBenchmark.sqlPreparedInsert              1    false                24               1  avgt   20  45.951 ± 7.650  us/op
After …
```
=> IGNITE-24134 Sql. Improve performance of KV plan in SQL

modules/api/src/main/java/org/apache/ignite/lang/util/IgniteNameUtils.java, modules/api/src/main/java/org/apache/ignite/table/QualifiedName.java, modules/api/src/test/java/org/apache/ignite/table/QualifiedNameTest.java, modules/core/src/main/java/org/apache/ignite/internal/sql/SqlCommon.java
=> IGNITE-24036 Sql schema. Introduce QualifiedName class

modules/client/src/main/java/org/apache/ignite/client/IgniteClient.java, modules/client/src/test/java/org/apache/ignite/client/HeartbeatTest.java
All config properties reviewed:
* Negative values are not allowed
* In some cases, `0` means disabled timeout (when stated in the javadoc)
=> IGNITE-23888 Thin client: add config argument validation

modules/core/src/main/java/org/apache/ignite/internal/logger/IgniteThrottledLogger.java, modules/core/src/main/java/org/apache/ignite/internal/logger/IgniteThrottledLoggerImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/HeapLockManager.java
https://issues.apache.org/jira/browse/IGNITE-24062
=> IGNITE-24062 Use throttled logger for heap lock manager

modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTableGetRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTablesGetRequest.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTables.java, modules/platforms/cpp/ignite/client/detail/table/tables_impl.cpp, modules/platforms/dotnet/Apache.Ignite.Tests/ClientSocketTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/FakeServer.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Tables.cs
Reserve space for schema name in `TABLE_GET` and `TABLES_GET` payloads.
=> IGNITE-24254 Thin client: add schema name placeholder to protocol

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDataTypesTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/externalize/RelJson.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rex/IgniteRexBuilder.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/IgniteMath.java
=> IGNITE-23873 Sql. Fix processing Infinite and NaN values after calcite version was bumped

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/freelist/PagesList.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/replacement/DelayedPageReplacementTracker.java
https://issues.apache.org/jira/browse/IGNITE-24277
=> IGNITE-24277 Add necessary `log.isDebugEnabled()` checks in `ignite-page-memory` module

modules/platforms/cpp/ignite/client/CMakeLists.txt, modules/platforms/cpp/ignite/client/compute/broadcast_execution.h, modules/platforms/cpp/ignite/client/compute/broadcast_job_target.cpp, modules/platforms/cpp/ignite/client/compute/broadcast_job_target.h, modules/platforms/cpp/ignite/client/compute/compute.cpp, modules/platforms/cpp/ignite/client/compute/compute.h, modules/platforms/cpp/ignite/client/compute/job_execution.cpp, modules/platforms/cpp/ignite/client/compute/job_execution.h, modules/platforms/cpp/ignite/client/compute/job_target.cpp, modules/platforms/cpp/ignite/client/compute/job_target.h, modules/platforms/cpp/ignite/client/detail/argument_check_utils.h, modules/platforms/cpp/ignite/client/detail/compute/any_node_job_target.h, modules/platforms/cpp/ignite/client/detail/compute/colocated_job_target.h, modules/platforms/cpp/ignite/client/detail/compute/compute_impl.cpp, modules/platforms/cpp/ignite/client/detail/compute/compute_impl.h, modules/platforms/cpp/ignite/client/detail/compute/job_execution_impl.h, modules/platforms/cpp/ignite/client/detail/compute/job_target_type.h, modules/platforms/cpp/ignite/client/detail/compute/nodes_broadcast_job_target.h, modules/platforms/cpp/ignite/client/detail/ignite_client_impl.cpp, modules/platforms/cpp/ignite/client/detail/utils.cpp, modules/platforms/cpp/ignite/client/detail/utils.h, modules/platforms/cpp/ignite/client/network/cluster_node.h, modules/platforms/cpp/tests/client-test/compute_test.cpp, modules/platforms/cpp/tests/client-test/schema_synchronization_test.cpp, modules/platforms/cpp/tests/test-common/basic_auth_test_suite.h
https://issues.apache.org/jira/browse/IGNITE-24200
- Introduced classes `broadcast_execution`, `job_target`, `broadcast_job_target`;
- Re-factored `compute` facade to use them;
- Added `get_node()` method to `job_execution`;
- Fixed tests;
=> IGNITE-24200 C++ Unify Compute API

modules/api/src/main/java/org/apache/ignite/sql/ResultSet.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/AbstractMultiNodeBenchmark.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/CreatingDistributionZoneBenchmark.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/CreatingTableBenchmark.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/TxBalanceRetryOperationBenchmark.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/TxUpsertRetryOperationBenchmark.java
https://issues.apache.org/jira/browse/IGNITE-24221
Creating a new distribution zone:
|Benchmark|(clusterSize)|(fsync)|(partitionCount)|(replicaCount)|Mode|Cnt|Score ± Error|Units|
|---|---|---|---|---|---|---|---|---|
|createEmptyDistributionZone|3|false|1|1|avgt|5|218.719 ± 0.916|ms/op|
|createEmptyDistributionZone|3|false|1|3|avgt|5|218.821 ± 0.660|ms/op|
|createEmptyDistributionZone|3|false|8|1|avgt|5|218.955 ± 1.294|ms/op|
|createEmptyDistributionZone|3|false|8|3|avgt|5|218.657 ± 1.082|ms/op|
Creating a new table in the default distribution zone:
|Benchmark|(clusterSize)|(fsync)|(partitionCount)|(replicaCount)|Mode|Cnt|Score ± Error|Units|
|---|---|---|---|---|---|---|---|---|
|createTableInDefaultZone|3|false|1|1|avgt|5|1003.333 ±  15.817|ms/op| …
=> IGNITE-24221 Implement new benchmarks that cover creating a distribution zone and table

modules/table/src/integrationTest/java/org/apache/ignite/internal/table/distributed/disaster/AbstractHighAvailablePartitionsRecoveryTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/distributed/disaster/ItHighAvailablePartitionNodeFiltersTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/distributed/disaster/ItHighAvailablePartitionsRecoveryByFilterUpdateTest.java
https://issues.apache.org/jira/browse/IGNITE-24209
=> IGNITE-24209 Added tests for filters and storage profiles awareness on partition reset

modules/platforms/dotnet/version.json
Enable public release builds from branches with `ignite-3.` prefix
=> IGNITE-24302 .NET: Fix publicReleaseRefSpec

.idea/inspectionProfiles/Project_Default.xml, modules/api/src/main/java/org/apache/ignite/compute/BroadcastJobTarget.java, modules/api/src/main/java/org/apache/ignite/compute/ColocatedJobTarget.java, modules/api/src/main/java/org/apache/ignite/compute/JobTarget.java, modules/api/src/main/java/org/apache/ignite/compute/TableJobTarget.java, modules/client/src/main/java/org/apache/ignite/internal/client/compute/ClientCompute.java, modules/client/src/test/java/org/apache/ignite/client/ClientComputeTest.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/IgniteComputeImpl.java
=> IGNITE-24033 Sql schema. Extend Compute API with supporting qualified names

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageLeaderElectionListener.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/time/ClusterTimeImpl.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/impl/MetaStorageLeaderElectionListenerTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/time/ClusterTimeTest.java
https://issues.apache.org/jira/browse/IGNITE-24262
=> [IGNITE-24262] AssertionError in ClusterTimeImpl.startSafeTimeScheduler

modules/platforms/dotnet/Apache.Ignite.Tests/LoggingTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/MultiClusterTest.cs
Fix `TestClientDropsConnectionOnClusterIdMismatch`, `TestMicrosoftConsoleLogger`.
=> IGNITE-24228 .NET: Fix flaky tests on Windows

modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/IgniteTestsBase.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Sql/SqlTests.cs, modules/platforms/dotnet/Apache.Ignite/BigDecimal.cs
* Implement `IFormattable` on `BigDecimal`
* Fix tests to use invariant culture for string conversions
=> IGNITE-24198 .NET: Fix locale-dependent Compute tests failures

DEVNOTES.md, buildscripts/jmh.gradle
* `./gradlew jmh` now is running without profiling
* `./gradlew jmh` now is not cached and reruns everytime
* `-PjmhProfileAsync` and `-PjmhProfileJfr` are added
https://issues.apache.org/jira/browse/IGNITE-24435
=> IGNITE-24435 Disable profiling by default for jmh task

modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceTest.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtil.java, modules/index/src/integrationTest/java/org/apache/ignite/internal/index/ItIndexAndRebalanceTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/distributed/disaster/AbstractHighAvailablePartitionsRecoveryTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/distributed/disaster/ItHighAvailablePartitionsRecoveryTest.java, modules/transactions/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryReconfigurationTest.java
https://issues.apache.org/jira/browse/IGNITE-24413
=> [IGNITE-24413] More HA tests

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlApiBaseTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItPublicSchemaTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSchemaTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PlanningContext.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PrepareServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/IgniteSchemas.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/SqlSchemaManagerImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/mapping/FragmentMappingTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/PredefinedSchemaManager.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/AbstractPlannerTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/PlannerTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/PlannerTimeoutTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/prepare/PrepareServiceImplTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/prepare/ddl/AbstractDdlSqlToCommandConverterTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/schema/SqlSchemaManagerImplTest.java
Introduces a schema contaner to resolve this issue - `SqlSchemaManager` now returns a top level schema container instead of a default schema.
The example illustrates resolution behaviour prior to this fix the second part was not possible due to `SchemaNotFoundError`:
```
// Root schema: [Schema1, Schema2]
// Schema S1. Tables: T1
// Schema S2. Tables: T1, T2
// Default schema: S1
//
// T1 resolves to S1.T1
// T2 does not exist.
// S2.T2 resolves to S2.T2
//
// When Default schema is not specified or refers to not existing schema:
//
// T1 does not exist.
// T2 does not exist.
// S1.T1 resolves to S1.T1
// S2.T2 resolves to S2.T2
// S2.T2 resolves to S2.T2
```
https://issues.apache.org/jira/browse/IGNITE-24456
---
To streamline the review process …
=> IGNITE-24456: Sql. Unexpected SchemaNotFoundError when query does not access that schema

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/PartitionTxStateAccess.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/PartitionTxStateAccessImpl.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/RaftSnapshotPartitionMeta.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/lease/LeaseInfo.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/PartitionMvStorageAccessImpl.java, modules/transactions/build.gradle, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/ThreadAssertingTxStatePartitionStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/TxStatePartitionStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateMetaRocksDbPartitionStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbPartitionStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbSharedStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbStorage.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/rocksdb/RocksDbTxStatePartitionStorageTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateMetaRocksDbPartitionStorageTest.java, modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/AbstractTxStatePartitionStorageTest.java, modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/test/TestTxStatePartitionStorage.java
https://issues.apache.org/jira/browse/IGNITE-24571
=> IGNITE-24571 Add methods for saving configuration and leases in the TX storage

modules/api/src/main/java/org/apache/ignite/table/TupleImpl.java, modules/client-common/src/main/java/org/apache/ignite/internal/client/table/MutableTupleBinaryTupleAdapter.java, modules/client/src/main/java/org/apache/ignite/internal/client/sql/ClientSqlRow.java, modules/client/src/test/java/org/apache/ignite/client/ClientTupleTest.java, modules/core/src/main/java/org/apache/ignite/internal/tostring/IgniteToStringBuilder.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientSqlTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlApiBaseTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/api/AsyncResultSetImpl.java
Ensure consistent `toString` for `Tuple` and `SqlRow` (`extends Tuple`).
=> IGNITE-24318 Unify Tuple and SqlRow string representation

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/sql/ItSqlCommandTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/ParserServiceImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/ParserServiceImplTest.java
https://issues.apache.org/jira/browse/IGNITE-24560
----------
=> IGNITE-24560 Sql. Result of script parsing with single statement is cached incorrectly

modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/Replicator.java
https://issues.apache.org/jira/browse/IGNITE-24643
=> IGNITE-24643 Lower logging level for 'Peer id not found' in Replicator

modules/platforms/dotnet/Apache.Ignite.Tests/Table/DataStreamerTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/SchemaSynchronizationTest.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/DataStreamer.cs
Fix invalid batch situation causing `IndexOutOfBoundsException` on the server: batch header contains new schema version, while one of the tuples is written with old schema version.
* Update streamer schema under lock
* Add batch schema version check
=> IGNITE-24612 .NET: Fix streamer schema update

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/AbstractZoneReplicationTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItAbstractColocationTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java
https://issues.apache.org/jira/browse/IGNITE-24687
1. Use delayDuration of 100ms
2. metaStorage.idleSyncTimeInterval must be twice as small, that is, 50ms, to prevent waits on schema syncs
=> IGNITE-24687 Use integration test defaults for schema sync settings in colocation tests

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/GroupUpdateRequest.java
https://issues.apache.org/jira/browse/IGNITE-24701
result of getAliveNodesWithData is modified in enrichAssignments, so we can't return unmodifiable set there
=> IGNITE-24701 Unhandled exception java.lang.UnsupportedOperationException for Reset Partitions

modules/client/src/test/java/org/apache/ignite/client/fakes/FakeTxManager.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTableScanTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/ClusterServiceFactory.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/NoOpTransaction.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItInternalTableReadWriteScanTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java, modules/transactions/src/jmh/java/org/apache/ignite/internal/tx/impl/TransactionExpirationRegistryBenchmark.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/InternalTransaction.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/PublicApiThreadingTransaction.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadOnlyTransactionImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadWriteTransactionImpl.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/impl/ReadWriteTransactionImplTest.java
https://issues.apache.org/jira/browse/IGNITE-24658
The patch is split on 2 commits: first one adjust test framework (adds node eviction from physical topology) to highlight original issue (highlighted by `QueryRecoveryTest#queryWithImplicitTxRecoversWhenNodeLeftClusterBeforeFragmentHasBeenSent`); the second commit addresses the issue.
-----------
\- …
=> IGNITE-24658 Sql. Fix NPE in ReadWriteTransactionImpl#enlist

modules/catalog-dsl/src/integrationTest/java/org/apache/ignite/internal/catalog/ItCatalogDslTest.java, modules/catalog-dsl/src/main/java/org/apache/ignite/internal/catalog/sql/CreateTableImpl.java, modules/catalog-dsl/src/main/java/org/apache/ignite/internal/catalog/sql/IgniteCatalogSqlImpl.java, modules/catalog-dsl/src/main/java/org/apache/ignite/internal/catalog/sql/IndexColumnImpl.java, modules/catalog-dsl/src/main/java/org/apache/ignite/internal/catalog/sql/Option.java, modules/catalog-dsl/src/main/java/org/apache/ignite/internal/catalog/sql/SelectFromView.java, modules/catalog-dsl/src/main/java/org/apache/ignite/internal/catalog/sql/TableDefinitionCollector.java, modules/catalog-dsl/src/test/java/org/apache/ignite/internal/catalog/sql/CreateTableTest.java, modules/catalog-dsl/src/test/java/org/apache/ignite/internal/catalog/sql/QueryPartTest.java
Use `system.index_columns` view in catalog dsl. 
Drop methods that parse column name/column definition lists from strings.
https://issues.apache.org/jira/browse/IGNITE-24294
---
- [Apache …
=> IGNITE-24294 IgniteCatalog API. Table's IndexDefinition reports incorrect name/sorting of index column

modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItComputeBaseTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/TestCluster.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/JRaftUtils.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/NodeManager.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/RaftGroupService.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/RaftMessageGroup.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/NodeImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/option/NodeOptions.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/NetworkInvoker.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/RpcRequests.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/AbstractClientService.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/IgniteRpcServer.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/core/AppendEntriesRequestProcessor.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/core/DefaultRaftClientService.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/core/HeartbeatRequestProcessor.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/rpc/IgniteRpcTest.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/rpc/impl/cli/AbstractCliRequestProcessorTest.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/test/MockAsyncContext.java, modules/raft/src/testFixtures/java/org/apache/ignite/raft/jraft/rpc/TestIgniteRpcServer.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestThreeNodesThreeReplicas.java
https://issues.apache.org/jira/browse/IGNITE-24484
=> IGNITE-24484 RAFT heartbeat coalescing

modules/index/src/integrationTest/java/org/apache/ignite/internal/index/ItBuildIndexTest.java, modules/index/src/main/java/org/apache/ignite/internal/index/ChangeIndexStatusTaskController.java, modules/index/src/main/java/org/apache/ignite/internal/index/ChangeIndexStatusTaskScheduler.java, modules/index/src/main/java/org/apache/ignite/internal/index/IndexBuildController.java, modules/index/src/main/java/org/apache/ignite/internal/index/IndexBuildingManager.java, modules/index/src/test/java/org/apache/ignite/internal/index/ChangeIndexStatusTaskControllerTest.java, modules/index/src/test/java/org/apache/ignite/internal/index/IndexBuildControllerTest.java, modules/index/src/test/java/org/apache/ignite/internal/index/TestIndexManagementUtils.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/ZonePartitionReplicaListener.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexUtils.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
https://issues.apache.org/jira/browse/IGNITE-24779
* ChangeIndexStatusTaskController now supports primacy tracking for per-zone partitions
* Do not try to start building an index created with its table
* Improved error handling in IndexBuildController (do not swallow exceptions, instead pass them to failure handler)
* Tracking local partition set growth in TableManager for per-zone partitions
* Supported per-zone partitions in the module tests
=> IGNITE-24779 Support index lifecycle for per-zone partitions

modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/inlineschema/TupleWithSchemaMarshalling.java, modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientBinaryTupleUtils.java, modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/StreamerReceiverSerializer.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/IgniteComputeImpl.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/streamer/ItAbstractDataStreamerTest.java
Allow Tuple as a data streamer payload, argument, and result.
* Reuse `TupleWithSchemaMarshalling` from Compute (allows nested Tuples as well)
* Move streamer-specific logic from `ClientBinaryTupleUtils` to `StreamerReceiverSerializer`
=> IGNITE-24469 Add tuple support to data streamer with receiver

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/sqllogic/Statement.java, modules/sql-engine/src/integrationTest/sql/group1/types/time/test_time.test, modules/sql-engine/src/integrationTest/sql/group1/types/time/time_parsing.test
Add tests that document current behaviour of TIME literals/ CAST to TIME.
- Casts with precision loss in precision supported precision range behave the same way as casts to decimals: ` SELECT '20.999'::DECIMAL(4,2) produces 20.99` and `SELECT '01:01:01.999'::TIME(2) ` produces  01:01:01.990 
- Documents the behaviour of casts with precision on with on time types with sub-millisecond precision - the behaviour is inconsistent between TIME literals and CASTs but that is OK for now since sub-millisecond precision is not fully supported yet.
https://issues.apache.org/jira/browse/IGNITE-24840
---
\- There is a …
=> IGNITE-24840: Sql. Extend SQL logic test coverage for TIME types

modules/network/src/main/java/org/apache/ignite/internal/network/configuration/MulticastNodeFinderConfigurationSchema.java
https://issues.apache.org/jira/browse/IGNITE-24972
TC agents sometimes have problems with network latency, so resultWaitTime in test should be increased (1000ms is used in similar AI2 test)
It also won't hurt to have increased default in config also
=> IGNITE-24972 Flaky ItMulticastNodeFinderTest

modules/client/src/main/java/org/apache/ignite/internal/client/PayloadOutputChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/sql/ClientSql.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlApiBaseTest.java
https://issues.apache.org/jira/browse/IGNITE-24968
The test fails due to a race between the token cancellation check and the cancellation request.
To fix this, `PayloadOutputChannel` now accepts a callback action that will be called when the payload is sent.
=> IGNITE-24968 Java thin: fix race on query cancellation

modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
Explicitly log node start exception (and possible exception from node stop caused by failed start) to make sure they remain in logs even if the code attempting to start the node doesn't log them
https://issues.apache.org/jira/browse/IGNITE-25161
=> IGNITE-25161 Improve exception logging during node start

modules/network/src/main/java/org/apache/ignite/internal/network/netty/NettySender.java
https://issues.apache.org/jira/browse/IGNITE-24876
The reordering was happening because messages waiting for a sender to be opened (in the sender awaiting queue) would be written directly to the channel (when the sender was finally opened), bypassing the event loop queue.
=> IGNITE-24876 Fix message reordering in network

modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/snapshot/SnapshotExecutorImpl.java
Reset state when a snapshot is cancelled
https://issues.apache.org/jira/browse/IGNITE-24820
=> IGNITE-24820 Properly handle snapshot cancellation

modules/platforms/dotnet/Apache.Ignite.Tests/Transactions/TransactionsTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Transactions/LazyTransaction.cs, modules/platforms/dotnet/Apache.Ignite/Transactions/ITransaction.cs
Follow the recommendation to implement `IDisposable` when implementing `IAsyncDisposable`:
https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync
=> IGNITE-25178 .NET: Add synchronous Dispose method to ITransaction

modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/UpsertKvBenchmark.java
https://issues.apache.org/jira/browse/IGNITE-25007
Benchmark output
```
Benchmark                 (batch)  (fieldLength)  (fieldValueGeneration)  (fsync)  (idxes)  (indexType)  (partitionCount)   Mode  Cnt      Score     Error  Units
UpsertKvBenchmark.upsert        1            100            uniquePrefix    false        0         HASH                 8  thrpt   20  10357.167 ± 113.030  ops/s
UpsertKvBenchmark.upsert        1            100            uniquePrefix    false        0       SORTED                 8  thrpt   20  10412.456 ±  78.296  ops/s
UpsertKvBenchmark.upsert        1            100            uniquePrefix    false       10         HASH                 8  thrpt   20   6626.293 ±  57.927  ops/s
UpsertKvBenchmark.upsert        1            100            uniquePrefix …
```
=> IGNITE-25007 Create JMH benchmark to test secondary indexes

modules/platforms/build.gradle, modules/platforms/dotnet/Apache.Extensions.Caching.Ignite.Tests/Apache.Extensions.Caching.Ignite.Tests.csproj, modules/platforms/dotnet/Apache.Ignite.Benchmarks/Apache.Ignite.Benchmarks.csproj, modules/platforms/dotnet/Apache.Ignite.Internal.Generators/Apache.Ignite.Internal.Generators.csproj, modules/platforms/dotnet/Apache.Ignite.Tests/Apache.Ignite.Tests.csproj
* Use `dotnet publish` instead of `dotnet build` to prepare the release binaries
* Exclude tests and benchmarks with `IsPublishable` property
=> IGNITE-25354 .NET: Exclude tests and benchmarks from release

modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcClientTimeZoneTest.java, modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc/JdbcResultSet.java, modules/jdbc/src/test/java/org/apache/ignite/internal/jdbc/JdbcResultSetTest.java
Updates JDBCResultSet:
- Updates `getString` to return string representation of JDBC data types. 
- Fixes `getTime`, `getDate` and `getTimestamp` from TIMESTAMP_LTZ to take connection's zoneId into account.
https://issues.apache.org/jira/browse/IGNITE-25190
---
\- The pull request title is treated as the final commit message. The following pattern must …
=> IGNITE-25190 Current timestamp / date adjusted to user time zone when cast to varchar

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlQueryProcessor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExchangeServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionContext.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/MailboxRegistryImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/Inbox.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/Outbox.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/message/MessageListener.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/message/MessageServiceImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImplTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/RuntimeSortedIndexTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/ExchangeExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestBuilders.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestNode.java
https://issues.apache.org/jira/browse/IGNITE-25363
This patch addresses an issue causing query to hang in case NODE_LEFT event is delayed. The solution is to consider node ID which changes after the restart instead of consistent name.
----------
\- The pull request title is treated as the final commit message. The following pattern must be used: …
=> IGNITE-25363 Sql. Delayed NODE_LEFT event processing may cause query to hang

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AbstractTableCommand.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AlterTableAddColumnCommand.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AlterTableAlterColumnCommand.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AlterTableDropColumnCommand.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateTableCommand.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateTableCommandBuilder.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/DropTableCommand.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/RenameTableCommand.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/CreateTableCommandValidationTest.java
This flag disables SYSTEM schema validation. For an internal
usage we want to be able to create table in SYSTEM schema.
https://issues.apache.org/jira/browse/IGNITE-25467
=> IGNITE-25467 Add flag to CreateTableCommand

modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/BinaryTupleParser.java, modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/BinaryTupleReader.java, modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/ByteBufferAccessor.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/BinaryTuple.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/BinaryTupleComparator.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/BinaryTupleComparatorUtils.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/PartialBinaryTupleMatcher.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/UnsafeByteBufferAccessor.java
https://issues.apache.org/jira/browse/IGNITE-25525
```
Benchmark                                         Mode  Cnt  Score    Error  Units
TupleComparatorBenchmark.testBytesFullCompare     avgt   10  0.054 ±  0.001  us/op
TupleComparatorBenchmark.testBytesPartialCompare  avgt   10  0.037 ±  0.001  us/op
TupleComparatorBenchmark.testStrFullCompare       avgt   10  0.782 ±  0.002  us/op
TupleComparatorBenchmark.testStrPartialCompare    avgt   10  0.404 ±  0.001  us/op
TupleComparatorBenchmark.testUuidFullCompare      avgt   10  0.013 ±  0.001  us/op
TupleComparatorBenchmark.testUuidPartialCompare   avgt   10  0.011 ±  0.001  us/op
TupleComparatorBenchmark.timestampFullCompare     avgt   10  0.012 ±  0.001  us/op
TupleComparatorBenchmark.timestampPartialCompare  avgt   10  0.010 ±  0.001 …
```
=> IGNITE-25525 ExceptionInInitializerError in BinaryTupleParser since JDK 17

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/format/DateTimeFormatElement.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/format/DateTimeFormatException.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/format/DateTimeTemplateField.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/format/Scanner.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/util/format/ScannerSelfTest.java
Implements a scanner that converts a string into a list of datetime format elements. An element can either be a field or a delimiter.
Tests:
- One field pattern for each field.
- One field pattern with delimiters before and after the field.
- Some Invalid patterns.
- Multiple fields with delimiters between them (fields are shuffled)
- Syntax rules: each field can appear only once, consecutive delimiters.
- Syntax rules: whether some field can be used with others, etc.
The code is based on this a scanner described in https://craftinginterpreters.com/scanning.html
https://issues.apache.org/jira/browse/IGNITE-25556:
---
we ask both an author and a reviewer to verify the …
=> IGNITE-25556: Sql. Date/Time. Datetime format scanner

modules/catalog-compaction/src/main/java/org/apache/ignite/internal/catalog/compaction/CatalogCompactionRunner.java, modules/index/build.gradle, modules/index/src/integrationTest/java/org/apache/ignite/internal/index/ItIndexRecoveryTest.java, modules/network/src/main/java/org/apache/ignite/internal/network/DefaultMessagingService.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexMeta.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexMetaStorage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaBuildIndexProcessor.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/ReplicatorUtils.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/index/IndexMetaStorageRecoveryTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replicator/ReplicatorUtilsTest.java
Also, another bug is fixed in ReplicatorUtils, where we could fail if Catalog still contains information about an index that is already removed from the index meta storage
https://issues.apache.org/jira/browse/IGNITE-25579
=> IGNITE-25579 Fix index meta storage recovery for dropped indices

modules/file-transfer/src/test/java/org/apache/ignite/internal/network/file/TestMessagingService.java, modules/network-api/src/main/java/org/apache/ignite/internal/network/MessagingService.java, modules/network-api/src/main/java/org/apache/ignite/internal/network/wrapper/JumpToExecutorByConsistentIdAfterSend.java, modules/network-api/src/test/java/org/apache/ignite/internal/network/wrapper/JumpToExecutorByConsistentIdAfterSendTest.java, modules/network/src/main/java/org/apache/ignite/internal/network/DefaultMessagingService.java, modules/network/src/main/java/org/apache/ignite/internal/network/scalecube/ScaleCubeClusterServiceFactory.java, modules/network/src/main/java/org/apache/ignite/internal/network/scalecube/ScaleCubeDirectMarshallerTransport.java, modules/network/src/test/java/org/apache/ignite/internal/network/DefaultMessagingServiceTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/scalecube/ScaleCubeDirectMarshallerTransportTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/ClusterServiceFactory.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
When sending by consistent ID or address, the check is redundant and can cause issues.
https://issues.apache.org/jira/browse/IGNITE-25805
=> IGNITE-25805 Only check actual target ID when sending by ClusterNode

modules/platforms/dotnet/Apache.Ignite.Tests/Sql/SqlTests.cs
*  Tweak the query for script to run longer so it does not complete before being cancelled
* Together with https://github.com/apache/ignite-3/commit/beb15d5c4c760b7baa30c21241dc13bcb8aae13f, flakiness should be fixed
=> IGNITE-25835 Fix TestCancelQueryExecute flakiness

modules/platforms/dotnet/Apache.Ignite.Tests/MetricsTests.cs
Add `RecordObservableInstruments` and `WaitForCondition` to `AssertTaggedMetric`.
=> IGNITE-25163 .NET: Fix MetricsTests flakiness

modules/api/src/main/java/org/apache/ignite/Ignite.java, modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/RecordViewBinaryTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Buffers/PooledArrayBuffer.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Compute/Compute.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/BinaryTuple/BinaryTupleBuilder.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/DataStreamer.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/BinaryTupleBuilderExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/IRecordSerializerHandler.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/ObjectSerializerHandler.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/RecordSerializer.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/TuplePairSerializerHandler.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Serialization/TupleSerializerHandler.cs
* Fix use-after-free with `PooledArrayBuffer.GetSpan` when underlying pooled array is reallocated - use the span immediately, or save position and use `GetSpanAt` later (for "reserved count" scenarios)
* Fix integer overflow in `CheckAndResizeBuffer`
* Fix `Compute.WriteEnumerable` - wrong type code and span handling in fallback branch
* Get rid of unsafe `MemoryMarshal.CreateSpan` in data streamer - use `scoped` lifetime for `noValueSet` instead
=> IGNITE-25941 .NET: Fix pooled buffer bugs

modules/runner/src/testFixtures/java/org/apache/ignite/internal/Cluster.java
… nodes history and timers on scale up timer trigger
https://issues.apache.org/jira/browse/IGNITE-25877
=> IGNITE-25877 Critical system error caused by failure in updating data nodes history and timers on scale up timer trigger

modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/IgniteTestUtils.java
https://issues.apache.org/jira/browse/IGNITE-26128
=> IGNITE-26128 Add to IgniteTestUtils#runRace suspended exceptions of operations if the race did not end by timeout

modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItCmgDisasterRecoveryTest.java
JIRA Ticket: [IGNITE-26136](https://issues.apache.org/jira/browse/IGNITE-26136)
Disable flaky test ItCmgDisasterRecoveryTest#repairWorksWhenCmgMajorityIsOnline due to https://issues.apache.org/jira/browse/IGNITE-26144
=> IGNITE-26136 Disable ItCmgDisasterRecoveryTest#repairWorksWhenCmgMajorityIsOnline

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PrepareServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/RelWithSources.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/partitionawareness/PartitionAwarenessMetadata.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/partitionawareness/PartitionAwarenessMetadataExtractor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/Cloner.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/mapping/MappingTestRunner.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/PartitionPruningMetadataTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/PartitionPruningTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/prepare/partitionawareness/PartitionAwarenessMetadataTest.java
Converts partition pruning metadata into partition awareness (PA) metadata to increase the number of queries that can benefit from PA optimisation.
https://issues.apache.org/jira/browse/IGNITE-25560
---
\- The pull request title is treated as the final commit message. The following pattern must be used: IGNITE-XXXX Change summary where XXXX - number of …
=> IGNITE-25560  Sql.  Partition awareness cover extension

modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientOp.java, modules/client-common/src/main/java/org/apache/ignite/internal/client/sql/QueryModifier.java, modules/client-common/src/test/java/org/apache/ignite/internal/client/proto/sql/QueryModifierTest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientResourceRegistry.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlCommon.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlCursorNextResultRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlExecuteRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlProperties.java, modules/client-handler/src/test/java/org/apache/ignite/client/handler/requests/sql/ClientSqlCommonTest.java, modules/client/src/main/java/org/apache/ignite/client/ClientOperationType.java, modules/client/src/main/java/org/apache/ignite/client/RetryReadPolicy.java, modules/client/src/main/java/org/apache/ignite/internal/client/ClientUtils.java, modules/client/src/main/java/org/apache/ignite/internal/client/sql/ClientAsyncResultSet.java, modules/client/src/main/java/org/apache/ignite/internal/client/sql/ClientSql.java, modules/client/src/test/java/org/apache/ignite/client/ClientSqlTest.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeCursor.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientMultistatementSqlTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientSqlTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/api/AsyncResultSetImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/SqlExceptionMapperProvider.java
https://issues.apache.org/jira/browse/IGNITE-26087
* `SQL_EXEC` operation extended, server response now contains the flag indicating whether the sql cursor has next result.
* Added new `SQL_CURSOR_NEXT_RESULT_SET` operation to able obtain next cursor result of the multi-statement query.
* Added new `ALLOW_MULTISTATEMENT` query modifier and the corresponding SQL property flag `allowMultiStatement`.
* Execution of a multi-statement query is now based on the `allowMultiStatement` flag (from `SqlProperties`) rather than the presence of the `TX_CONTROL` query type.
=> IGNITE-26087 Ability to obtain results of a multi-statement query execution using the internal thin client SQL API.

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/BaseSqlMultiStatementTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlMultiStatementTest.java
https://issues.apache.org/jira/browse/IGNITE-26218
Test fails because `fetchCursors` does not wait for all cursors to close.
General check has been relaxed (replaced with conditional wait) to prevent flaky failures like IGNITE-25930
=> IGNITE-26218 Sql. Fixed flaky test ItSqlMultiStatementTest.statementRestrictedByQueryType.

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PrepareServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/ddl/ClusterWideStorageProfileValidator.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/ddl/DdlSqlToCommandConverter.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/ddl/StorageProfileValidator.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImplTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestBuilders.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/prepare/ddl/AbstractDdlSqlToCommandConverterTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/prepare/ddl/DdlSqlToCommandConverterTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/prepare/ddl/DistributionZoneSqlToCommandConverterTest.java
JIRA Ticket: [IGNITE-26273](https://issues.apache.org/jira/browse/IGNITE-26273)
The main goal is to modify `DdlSqlToCommandConverter#convert` to return `CompletableFuture<CatalogCommand>` instead of just `CatalogCommand`.
Some validations may require distributed and thus asynchronous interactions.
The solution is straightforward: to replace return statements with `completeFuture(...)` wrapping.
=> IGNITE-26273 Make DDL converter API asynchronous

modules/core/src/main/java/org/apache/ignite/internal/util/StripedVersatileReadWriteLock.java, modules/core/src/main/java/org/apache/ignite/internal/util/VersatileReadWriteLock.java, modules/core/src/test/java/org/apache/ignite/internal/util/StripedVersatileReadWriteLockTest.java, modules/core/src/test/java/org/apache/ignite/internal/util/VersatileReadWriteLockBenchmark.java, modules/core/src/test/java/org/apache/ignite/internal/util/VersatileReadWriteLockTest.java, modules/runner/src/main/java/org/apache/ignite/internal/restart/IgniteAttachmentLock.java, modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofKeyValueView.java
https://issues.apache.org/jira/browse/IGNITE-23779
A striped lock over VersatileReadWriteLock is introduced so that contention is decreased
=> IGNITE-23779 Decrease contention on attachment lock

modules/client-common/src/main/java/org/apache/ignite/internal/jdbc/proto/event/JdbcColumnMeta.java, modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/ItClientHandlerTest.java, modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc/JdbcResultSetMetadata.java, modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc2/JdbcResultSetMetadata.java, modules/jdbc/src/test/java/org/apache/ignite/internal/jdbc/ColumnDefinition.java, modules/jdbc/src/test/java/org/apache/ignite/internal/jdbc/JdbcResultSetMetadataBaseSelfTest.java, modules/jdbc/src/test/java/org/apache/ignite/internal/jdbc/JdbcResultSetMetadataSelfTest.java, modules/jdbc/src/test/java/org/apache/ignite/internal/jdbc2/JdbcResultSetMetadata2SelfTest.java
Implements `jdbc ResultSetMetadata` over ignite client result set metadata.
https://issues.apache.org/jira/browse/IGNITE-26276
--- …
=> IGNITE-26276 Sql. Jdbc. Add new implementation for ResultSetMetadata

modules/compute/src/main/java/org/apache/ignite/internal/compute/executor/platform/dotnet/DotNetComputeExecutor.java, modules/compute/src/test/java/org/apache/ignite/internal/compute/executor/platform/dotnet/DotNetComputeExecutorTest.java
If there is no active executor process, there is nothing to undeploy.
=> IGNITE-26277 Fix DotNetComputeExecutor process start on undeploy

modules/api/src/main/java/org/apache/ignite/catalog/annotations/Zone.java, modules/api/src/main/java/org/apache/ignite/catalog/definitions/ZoneDefinition.java
JIRA Ticket: [IGNITE-26373](https://issues.apache.org/jira/browse/IGNITE-26373)
The main goal is to revert public API changes after #6476 especially `Zone` annotation and `ZoneDefinition`.
We have to maintain compatibility, especially user's code compilation compatibility.
1. `ZoneDefinition#dataNodesAutoAdjust` and it's getters and builder methods are reverted;
2. `Zone#dataNodesAutoAdjust` is reverted
3. All usages above are marked as `@Deprecated`
4. There no more non-test entities from not internal packages
=> IGNITE-26373 Return public API for auto adjust related entities

modules/compatibility-tests/src/testFixtures/java/org/apache/ignite/internal/PlatformCompatibilityTestNodeRunner.java, modules/platforms/dotnet/Apache.Ignite.Tests/Compatibility/CurrentClientWithOldServerCompatibilityTest.cs, modules/platforms/dotnet/Apache.Ignite.Tests/JavaServer.cs
Use random free ports to start Java server for compatibility tests.
=> IGNITE-26312 .NET: Fix port issues in compat tests

modules/jdbc/src/integrationTest/java/org/apache/ignite/internal/jdbc/ItJdbcMetadataSelfTest.java, modules/jdbc/src/integrationTest/java/org/apache/ignite/internal/jdbc/ItJdbcParameterMetadataSelfTest.java, modules/jdbc/src/integrationTest/java/org/apache/ignite/internal/jdbc/ItJdbcResultSetMetadataSelfTest.java, modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcAuthenticationTest.java, modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc/JdbcConnection.java, modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc/JdbcDatabaseMetadata.java, modules/jdbc/src/test/java/org/apache/ignite/internal/jdbc/JdbcDatabaseMetadataSelfTest.java
Updates JdbcDatabaseMetadata to use jdbc client handler directly add some test for metadata methods as well.
Adds tests for all methods that return ResultSet to ensure that their metadata is consistent with jdbc spec.
https://issues.apache.org/jira/browse/IGNITE-26417
---
\- The pull request title is treated as the final commit message. The following …
=> IGNITE-26417 Jdbc. DatabaseMetadata for thin client backed connection

modules/compatibility-tests/build.gradle, modules/compatibility-tests/src/testFixtures/java/org/apache/ignite/internal/CompatibilityTestBase.java, modules/replicator/src/main/java/org/apache/ignite/internal/raft/client/TopologyAwareRaftGroupService.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-26127
The main problem here is replica await timeout during active rebalance on cluster restart.
On a first iteration all three nodes on a current version start almost simultaneously, see that there's no data nodes history key, read the topology from the old version which contains all three nodes and continue to work normal.
On the second run (probably due to the classes already loaded and JVM is warmed up) first node reads logical topology from the metastorage and quickly adds itself to the topology. Now the second node reads the topology but sees only the first node there and this triggers a rebalance. Third node see first two nodes in the topology and triggers rebalance once again.
If at this moment the test tries to read data from a table, …
=> IGNITE-26127 Compatibility test fails consecutive run

modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcResultSetSelfTest.java, modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc/JdbcResultSet.java, modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc2/JdbcResultSet.java, modules/jdbc/src/test/java/org/apache/ignite/internal/jdbc/JdbcResultSetBaseSelfTest.java, modules/jdbc/src/test/java/org/apache/ignite/internal/jdbc/JdbcResultSetSelfTest.java, modules/jdbc/src/test/java/org/apache/ignite/internal/jdbc2/JdbcResultSet2SelfTest.java
Adds accessors for  the boolean and numeric types to ResultSet backed by thin client.
https://issues.apache.org/jira/browse/IGNITE-26369
--- …
=> IGNITE-26369 Jdbc. Add accessor methods to thin client-backed ResultSet (numeric types)

modules/platforms/dotnet/Apache.Ignite/Internal/Table/Table.cs
Fix unintended retry when schema task fails quickly. This fixes `TestFailedSchemaLoadTaskIsRetried` flakiness.
=> IGNITE-26393 .NET: Fix schema caching race condition

modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc2/JdbcResultSet.java, modules/jdbc/src/test/java/org/apache/ignite/internal/jdbc/JdbcResultSetBaseSelfTest.java, modules/jdbc/src/test/java/org/apache/ignite/internal/jdbc/JdbcResultSetSelfTest.java, modules/jdbc/src/test/java/org/apache/ignite/internal/jdbc2/JdbcResultSet2SelfTest.java
Adds remaining methods such as `getBytes`  and tests for  `getObject for java.util.UUID)`.
https://issues.apache.org/jira/browse/IGNITE-26140
--- …
=> IGNITE-26140 Sql. Jdbc. Add new implementation for java.sql.ResultSet (adapter for org.apache.ignite.sql.ResultSet).

migration-tools/modules/migration-tools-commons-tests/build.gradle, migration-tools/modules/migration-tools-commons-tests/src/main/java/org/apache/ignite/migrationtools/tests/models/InterceptingFieldsModel.java, migration-tools/modules/migration-tools-commons/src/main/java/org/apache/ignite/migrationtools/sql/FieldNameConflictException.java, migration-tools/modules/migration-tools-commons/src/main/java/org/apache/ignite/migrationtools/sql/SqlDdlGenerator.java, migration-tools/modules/migration-tools-commons/src/main/java/org/apache/ignite/migrationtools/tablemanagement/PersistentTableTypeRegistryImpl.java, migration-tools/modules/migration-tools-commons/src/main/java/org/apache/ignite/migrationtools/tablemanagement/RegisterOnlyTableTypeRegistry.java, migration-tools/modules/migration-tools-commons/src/main/java/org/apache/ignite/migrationtools/tablemanagement/TableTypeDescriptor.java, migration-tools/modules/migration-tools-commons/src/main/java/org/apache/ignite/migrationtools/tablemanagement/TableTypeRegistry.java, migration-tools/modules/migration-tools-commons/src/main/java/org/apache/ignite/migrationtools/tablemanagement/TableTypeRegistryMapImpl.java, migration-tools/modules/migration-tools-commons/src/main/java/org/apache/ignite/migrationtools/tablemanagement/TableTypeRegistryUtils.java, migration-tools/modules/migration-tools-commons/src/main/java/org/apache/ignite/migrationtools/types/InspectedField.java, migration-tools/modules/migration-tools-commons/src/main/java/org/apache/ignite/migrationtools/types/InspectedFieldType.java, migration-tools/modules/migration-tools-commons/src/main/java/org/apache/ignite/migrationtools/types/TypeInspector.java, migration-tools/modules/migration-tools-commons/src/test/java/org/apache/ignite/migrationtools/sql/sql/SqlDdlGeneratorTest.java, migration-tools/modules/migration-tools-commons/src/test/java/org/apache/ignite/migrationtools/types/TypeInspectorTest.java, migration-tools/modules/migration-tools-persistence/src/main/java/org/apache/ignite/migrationtools/persistence/Ignite2PersistentCacheTools.java
Changes:
* Extract InspectedField logic from SqlDdlGenerator
* Add information about the column to class mappings in the TableTypeRegistry
* Refactor SqlDdlGenerator to extract field inspection logic and add information about column to field mappings
https://issues.apache.org/jira/browse/IGNITE-26520
=> IGNITE-26520 Refactor SqlDdlGenerator

modules/platforms/dotnet/Apache.Ignite.Tests/FakeServer.cs, modules/platforms/dotnet/Apache.Ignite.Tests/MetricsTests.cs
* Disable reconnect
* Add lock
* Increase timeout
* Add logging
=> IGNITE-26474 .NET: Fix metrics test flakiness
