apache/ignite-3

docs/_docs/general-tips.adoc

IGNITE-20540 Added information of logging to docs

---

modules/cli/build.gradle

https://issues.apache.org/jira/browse/IGNITE-20791

IGNITE-20791 Fix version conflict in IDEA runner

---

modules/platforms/dotnet/Apache.Ignite.Tests/BasicAuthenticatorTests.cs
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/PlatformTestNodeRunner.java

Wait for the configuration change to be applied by the server when disabling authentication.

IGNITE-20785 .NET: Fix BasicAuthenticatorTests flakiness

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java

https://issues.apache.org/jira/browse/IGNITE-20796

IGNITE-20796 Refactor replica stop in TableManager

---

modules/raft/src/main/java/org/apache/ignite/internal/raft/RaftGroupServiceImpl.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/RaftMessageGroup.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/ActionRequest.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/ReadActionRequest.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/WriteActionRequest.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/ActionRequestProcessor.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/IgniteRpcServer.java
modules/raft/src/test/java/org/apache/ignite/internal/raft/RaftGroupServiceTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItBuildIndexTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/schema/CheckCatalogVersionOnActionRequest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/schema/CheckCatalogVersionOnActionRequestTest.java

https://issues.apache.org/jira/browse/IGNITE-20803

IGNITE-20803 Split ActionRequest into 2 interfaces

---

modules/cli/src/integrationTest/java/org/apache/ignite/internal/NodeConfig.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/connect/ItConnectCommandTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/questions/ItConnectToSslClusterTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/ssl/ItJdbcSslCustomCipherTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/ssl/ItSslCustomCipherTest.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/connect/ConnectCall.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/connect/ConnectionChecker.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/config/CliConfigKeys.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/core/JdbcUrlFactory.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/core/rest/ApiClientFactory.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/core/rest/ApiClientSettings.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/core/rest/ApiClientSettingsBuilder.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/core/JdbcUrlFactoryTest.java

https://issues.apache.org/jira/browse/IGNITE-20676

IGNITE-20676 Support cipher suites in CLI for REST and JDBC connections

---

modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesAbstractTest.java

https://issues.apache.org/jira/browse/IGNITE-20820

IGNITE-20820 Increase await timeout in ItMetaStorageMultipleNodesAbstractTest

---

modules/rest/src/main/java/org/apache/ignite/internal/rest/RestComponent.java

It happens bacause of the race condition inside
micronaut.
https://github.com/micronaut-projects/micronaut-core/issues/10091
https://issues.apache.org/jira/browse/IGNITE-20819

IGNITE-20819 Use shared lock on HTTP server startup

---

modules/rest-api/build.gradle
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/GeneralErrorsController.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/constants/HttpCode.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/exception/handler/IgniteExceptionHandler.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/exception/handler/IgniteInternalCheckedExceptionHandler.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/exception/handler/IgniteInternalExceptionHandler.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/exception/handler/JavaExceptionHandler.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/exception/handler/replacement/AuthenticationExceptionHandlerReplacement.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/exception/handler/replacement/ConstraintExceptionHandlerReplacement.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/exception/handler/replacement/ContentLengthExceededHandlerReplacement.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/exception/handler/replacement/ConversionErrorHandlerReplacement.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/exception/handler/replacement/DefaultAuthorizationExceptionHandlerReplacement.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/exception/handler/replacement/HttpStatusHandlerReplacement.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/exception/handler/replacement/JsonExceptionHandlerReplacement.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/exception/handler/replacement/UnsatisfiedArgumentHandlerReplacement.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/exception/handler/replacement/UnsatisfiedRouteHandlerReplacement.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/exception/handler/replacement/UriSyntaxHandlerReplacement.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/problem/HttpProblemResponse.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/problem/ProblemJsonMediaType.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/problem/ProblemJsonMediaTypeCodec.java
modules/rest-api/src/test/java/org/apache/ignite/internal/rest/exception/handler/EchoMessage.java
modules/rest-api/src/test/java/org/apache/ignite/internal/rest/exception/handler/ErrorHandlingTest.java
modules/rest-api/src/test/java/org/apache/ignite/internal/rest/exception/handler/TestController.java
modules/rest-api/src/test/java/org/apache/ignite/internal/rest/exception/handler/ThrowableProvider.java
modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/cluster/ItClusterManagementControllerTest.java

https://issues.apache.org/jira/browse/IGNITE-19723
- Introduced a controller for general errors
- Customized error handlers to replace default Micronaut implementations
- Sets application/problem+json content type where applicable
\- The pull request title is treated as the final commit message. The following pattern must be used: IGNITE-XXXX Change …

IGNITE-19723 Enhance REST error handling

---

modules/replicator/src/main/java/org/apache/ignite/internal/raft/client/TopologyAwareRaftGroupService.java

https://issues.apache.org/jira/browse/IGNITE-20828

IGNITE-20828 Do not retry attempts to unsubscribe in TopologyAwareRaftGroupService

---

modules/core/src/main/java/org/apache/ignite/internal/hlc/HybridTimestamp.java
modules/core/src/main/java/org/apache/ignite/internal/lang/JavaLoggerFormatter.java

https://issues.apache.org/jira/browse/IGNITE-20817

IGNITE-20817 Reimplement HybridTimestamp#toString to make it readable by humans

---

modules/file-io/src/main/java/org/apache/ignite/internal/fileio/AsyncFileIo.java
modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/tree/BplusTree.java
modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/store/AbstractFilePageStoreIoTest.java

https://issues.apache.org/jira/browse/IGNITE-20821

IGNITE-20821 Fix race between read and rename for delta-files

---

modules/raft/src/main/java/org/apache/ignite/internal/raft/RaftGroupServiceImpl.java

https://issues.apache.org/jira/browse/IGNITE-20753

GNITE-20753 Add additional information on the recoverable exception

---

modules/table/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java

https://issues.apache.org/jira/browse/IGNITE-20833

IGNITE-20833 Switch ItTableRaftSnapshotsTest to KV API

---

modules/platforms/cpp/ignite/odbc/CMakeLists.txt
modules/platforms/cpp/ignite/odbc/query/query.h
modules/platforms/cpp/ignite/odbc/query/special_columns_query.cpp
modules/platforms/cpp/ignite/odbc/query/special_columns_query.h
modules/platforms/cpp/ignite/odbc/sql_statement.cpp
modules/platforms/cpp/tests/odbc-test/api_robustness_test.cpp

- Ported code from AI2;
- Un-commented test.

IGNITE-19218 Implement special columns query in ODBC 

---

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/CliCommandTestNotInitializedIntegrationBase.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/ItNodeNameTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/connect/ItConnectWithBasicAuthenticationCommandTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/questions/ItConnectToBasicAuthClusterTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/questions/ItConnectToClusterTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/questions/ItConnectToSslAndAuthClusterTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/questions/ItConnectToSslClusterTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/sql/ItSqlConnectSslBasicTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/sql/ItSqlConnectSslTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/ssl/ItSslCustomCipherTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/ssl/ItSslTest.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/registry/impl/NodeNameRegistryImpl.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/RestComponent.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/component/ItRestAddressReportTest.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java

https://issues.apache.org/jira/browse/IGNITE-19240

IGNITE-19240 Use HTTPS port for dynamic completers when connected to SSL enabled node

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java
modules/core/src/main/java/org/apache/ignite/internal/Kludges.java
modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java

https://issues.apache.org/jira/browse/IGNITE-20856

IGNITE-20856 Replace IGNITE-20499 with IGNITE-20854 in To-Dos

---

modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerRecoveryTest.java
modules/catalog/src/testFixtures/java/org/apache/ignite/internal/catalog/BaseCatalogManagerTest.java

https://issues.apache.org/jira/browse/IGNITE-20860

IGNITE-20860 Сheck the correctness of the catalog version recovery

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java
modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/BaseIgniteAbstractTest.java
modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/TestIgnitionManager.java
modules/replicator/build.gradle
modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java
modules/replicator/src/main/java/org/apache/ignite/internal/replicator/configuration/ReplicationConfigurationModule.java
modules/replicator/src/main/java/org/apache/ignite/internal/replicator/configuration/ReplicationConfigurationSchema.java
modules/replicator/src/test/java/org/apache/ignite/internal/replicator/configuration/ReplicationConfigurationModuleTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/readonly/ItReadOnlyTxInPastTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/runner/src/main/java/org/apache/ignite/internal/app/SameValueLongSupplier.java
modules/runner/src/test/java/org/apache/ignite/internal/app/SameValueLongSupplierTest.java
modules/runner/src/testFixtures/java/org/apache/ignite/internal/ClusterPerTestIntegrationTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceRecoveryTest.java
modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerTest.java

https://issues.apache.org/jira/browse/IGNITE-20854

IGNITE-20854 Configure idleSafeTimePropagationPeriod with a distributed property

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItDurableFinishTest.java

https://issues.apache.org/jira/browse/IGNITE-20825

IGNITE-20825 Fix ItDurableFinishTest.testCoordinatorMissedResponse  flakiness

---

modules/index/src/main/java/org/apache/ignite/internal/index/IndexManager.java
modules/index/src/test/java/org/apache/ignite/internal/index/IndexManagerTest.java
modules/index/src/test/java/org/apache/ignite/internal/index/TestIndexManagementUtils.java

https://issues.apache.org/jira/browse/IGNITE-20886

IGNITE-20886 Don't unregister indexes on CatalogEvent#INDEX_DROP

---

modules/core/src/main/java/org/apache/ignite/internal/future/OrderingFuture.java
modules/core/src/test/java/org/apache/ignite/internal/future/OrderingFutureCallbackInterferenceTest.java
modules/core/src/test/java/org/apache/ignite/internal/future/OrderingFutureCallbackOrderingTest.java
modules/core/src/test/java/org/apache/ignite/internal/future/OrderingFutureConcurrencyTest.java
modules/core/src/test/java/org/apache/ignite/internal/future/OrderingFutureTest.java

https://issues.apache.org/jira/browse/IGNITE-20891

IGNITE-20891 Add thenCompose to OrderingFuture

---

modules/api/src/main/java/org/apache/ignite/lang/IgniteCheckedException.java
modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java
modules/client/src/main/java/org/apache/ignite/internal/client/ClientUtils.java
modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java
modules/client/src/main/java/org/apache/ignite/internal/client/compute/ClientCompute.java
modules/client/src/test/java/org/apache/ignite/client/ClientKeyValueBinaryViewTest.java
modules/client/src/test/java/org/apache/ignite/client/ClientKeyValueViewTest.java
modules/client/src/test/java/org/apache/ignite/client/ClientRecordViewTest.java
modules/client/src/test/java/org/apache/ignite/internal/client/ClientUtilsTest.java
modules/core/src/main/java/org/apache/ignite/internal/util/ExceptionUtils.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientComputeTest.java

- Fixed stack traces;
- Added checks to existing tests to ensure we're getting proper stack traces.

IGNITE-20871 Fix stack trace in client exceptions

---

modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java
modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java
modules/replicator/src/main/java/org/apache/ignite/internal/replicator/exception/PrimaryReplicaMissException.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItSingleNodeTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java

https://issues.apache.org/jira/browse/IGNITE-20910

IGNITE-20910 Add test for inserting data after a restart

---

modules/index/src/test/java/org/apache/ignite/internal/index/IndexManagerTest.java
modules/index/src/test/java/org/apache/ignite/internal/index/TestIndexManagementUtils.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageManagerImplTest.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesAbstractTest.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java
modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/MultiActorPlacementDriverTest.java

https://issues.apache.org/jira/browse/IGNITE-20935

IGNITE-20935 Remove MetaStorageManagerImpl#getService

---

modules/client-handler/src/test/java/org/apache/ignite/client/handler/requests/jdbc/JdbcQueryCursorSelfTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/AbstractMultiNodeBenchmark.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/InsertBenchmark.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/AsyncSqlCursorImpl.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/QueryTransactionWrapper.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlQueryProcessor.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/ModifyNode.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/TestDownstream.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/DataSourceScanNodeSelfTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/ModifyNodeExecutionTest.java

IGNITE-20887 Sql. Avoid using blocking api in sql threads

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/BitSetPartitionSet.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/PartitionSet.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/AbstractPartitionSetTest.java

https://issues.apache.org/jira/browse/IGNITE-20951

IGNITE-20951 Add PartitionSet#clear method

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java

https://issues.apache.org/jira/browse/IGNITE-19905

IGNITE-19905 Remove redundant TODOs

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java

https://issues.apache.org/jira/browse/IGNITE-20942

IGNITE-20942 Group equality check added for PartitionReplicaListener scoped PR events

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java

https://issues.apache.org/jira/browse/IGNITE-20953

IGNITE-20953 Move cleanup out of the TX locks

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java

https://issues.apache.org/jira/browse/IGNITE-20766

IGNITE-20766 Deal with the primary replica provider in integration tests

---

modules/platforms/dotnet/Apache.Ignite.Tests/LoggingTests.cs

* Use `TextWriter.Synchronized` to handle multithreaded writes
* Close the client and the writer before accessing the log

IGNITE-20967 .NET: Fix TestMicrosoftConsoleLogger flakiness

---

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/PartitionMetaManager.java
modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStoreManager.java
modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/store/GroupPageStoresMap.java
modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/PartitionMetaManagerTest.java
modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/PersistentPageMemoryNoLoadTest.java
modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStoreManagerTest.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryTableStorage.java

https://issues.apache.org/jira/browse/IGNITE-20958

IGNITE-20958 PersistentPageMemoryMvPartitionStorageTest#groupConfigShorteningWorksCorrectly threw an AssertionError

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTransactionConflictTest.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/LockManager.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/event/LockEvent.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/event/LockEventParameters.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/HeapLockManager.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/OrphanDetector.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java
modules/transactions/src/test/java/org/apache/ignite/internal/tx/AbstractLockManagerEventsTest.java
modules/transactions/src/test/java/org/apache/ignite/internal/tx/HeapLockManagerEventsTest.java

https://issues.apache.org/jira/browse/IGNITE-20773

IGNITE-20773 Adjust lock resolution procedure in order to have an ability to do tx coordinator liveness check

---

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/PersistentPageMemory.java
modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointManager.java
modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointManagerTest.java

https://issues.apache.org/jira/browse/IGNITE-20984

IGNITE-20984 Getting rid of double writing of partition meta to a DeltaFilePageStoreIo

---

modules/core/src/main/java/org/apache/ignite/internal/sql/AbstractSession.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlApiBaseTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlAsynchronousApiTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlClientAsynchronousApiTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlClientSynchronousApiTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlSynchronousApiTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/api/SessionImpl.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/api/SessionImplTest.java

IGNITE-16960: Support script execution using native public Java API.

---

modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientOp.java
modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java
modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlExecuteRequest.java
modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlExecuteScriptRequest.java
modules/client/src/main/java/org/apache/ignite/client/ClientOperationType.java
modules/client/src/main/java/org/apache/ignite/client/RetryReadPolicy.java
modules/client/src/main/java/org/apache/ignite/internal/client/ClientChannel.java
modules/client/src/main/java/org/apache/ignite/internal/client/ClientUtils.java
modules/client/src/main/java/org/apache/ignite/internal/client/ReliableChannel.java
modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java
modules/client/src/main/java/org/apache/ignite/internal/client/sql/ClientSession.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlClientAsynchronousApiTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlClientSynchronousApiTest.java

* Add `ClientSqlExecuteScriptRequest` on the server
* Implement `executeScriptAsync` on the client
* Enable existing tests

IGNITE-17060 Implement script SQL API for java thin client

---

modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientHandlerModule.java
modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientPrimaryReplicaTracker.java
modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientResourceRegistry.java

Update `ClientHandlerModule`, `ClientResourceRegistry`, `ClientPrimaryReplicaTracker`.

IGNITE-20921 Add stopGuard and busyLock to client connector classes

---

modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/matchers/CompletableFutureExceptionMatcher.java

https://issues.apache.org/jira/browse/IGNITE-21007

IGNITE-21007 Add exception message matcher to CompletableFutureExceptionMatcher

---

modules/jdbc/build.gradle
modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcAuthenticationTest.java

IGNITE-20937:  Extract JDBC tests from runner module to ignite-jdbc

---

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java

https://issues.apache.org/jira/browse/IGNITE-20310

IGNITE-20310 wait for meta storage invokes in DistributionZoneManager start

---

modules/index/src/main/java/org/apache/ignite/internal/index/IndexBuildController.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/WatchProcessor.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java

https://issues.apache.org/jira/browse/IGNITE-20971

IGNITE-20971 Fix deadlock when receiving obsolete lease

---

modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/DeployMessagingService.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/loader/JobContextManager.java
modules/core/src/main/java/org/apache/ignite/internal/util/CompletableFutures.java
modules/core/src/test/java/org/apache/ignite/internal/util/CompletableFuturesTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/AbstractSchemaChangeTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionDependencyResolverImpl.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java

https://issues.apache.org/jira/browse/IGNITE-21043

IGNITE-21043 Introduce a method to obtain a list from CompletableFuture#allOf

---

modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/VolatileTxStateMetaStorage.java

https://issues.apache.org/jira/browse/IGNITE-21024

IGNITE-21024 add busylocks

---

modules/raft/src/test/java/org/apache/ignite/disruptor/StripedDisruptorTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/NoOpTransaction.java
modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestThreeNodesThreeReplicasCollocated.java
modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxStateLocalMapTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotCopierTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/outgoing/OutgoingSnapshotTxDataStreamingTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerDurableUnlockTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java
modules/transactions/README.md
modules/transactions/src/main/java/org/apache/ignite/internal/tx/TxState.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadOnlyTransactionImpl.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/message/WriteIntentSwitchReplicaRequest.java
modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerTest.java
modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxStateTest.java
modules/transactions/src/test/java/org/apache/ignite/internal/tx/impl/ReadWriteTransactionImplTest.java
modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/AbstractTxStateStorageTest.java

https://issues.apache.org/jira/browse/IGNITE-21012

IGNITE-21012 Fix typo in the transaction state COMMITED

---

modules/api/src/main/java/org/apache/ignite/compute/JobExecution.java
modules/api/src/main/java/org/apache/ignite/compute/JobExecutionContext.java
modules/compute/build.gradle
modules/compute/src/main/java/org/apache/ignite/internal/compute/ComputeComponent.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/ComputeComponentImpl.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/ComputeUtils.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/executor/ComputeExecutor.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/executor/ComputeExecutorImpl.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/executor/JobExecutionImpl.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/executor/QueueExecutionImpl.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/queue/PriorityQueueExecutor.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/queue/QueueEntry.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/queue/QueueExecution.java
modules/compute/src/test/java/org/apache/ignite/internal/compute/JobExecutionContextImplTest.java
modules/compute/src/test/java/org/apache/ignite/internal/compute/executor/ComputeExecutorTest.java
modules/compute/src/test/java/org/apache/ignite/internal/compute/queue/PriorityQueueExecutorTest.java

https://issues.apache.org/jira/browse/IGNITE-20845

IGNITE-20845 Compute jobs cancellation

---

modules/configuration/src/main/java/org/apache/ignite/internal/configuration/NamedListConfiguration.java
modules/configuration/src/test/java/org/apache/ignite/internal/configuration/ConfigurationRegistryTest.java

https://issues.apache.org/jira/browse/IGNITE-21072

IGNITE-21072 Getting named list element by UUID should cast to polymorphic type

---

modules/platforms/cpp/ignite/odbc/config/connection_info.cpp
modules/platforms/cpp/ignite/odbc/config/connection_info.h
modules/platforms/cpp/ignite/odbc/config/connection_info_test.cpp
modules/platforms/cpp/ignite/odbc/sql_connection.cpp
modules/platforms/cpp/tests/odbc-test/connection_test.cpp

https://issues.apache.org/jira/browse/IGNITE-20992

IGNITE-20992 ODBC 3.0: Propagate username to connection_info

---

modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcTransactionTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlApiBaseTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlMultiStatementTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlMultiStatementTxTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/IgniteMath.java

I've taken message from Cockroach DB

IGNITE-20997: Improve the error message when attempting to divide by zero

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java
modules/core/src/main/java/org/apache/ignite/internal/hlc/HybridTimestamp.java
modules/core/src/test/java/org/apache/ignite/internal/hlc/HybridTimestampTest.java
modules/runner/src/testFixtures/java/org/apache/ignite/internal/ClusterPerClassIntegrationTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItMixedQueriesTest.java
modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/BaseSqlIntegrationTest.java

https://issues.apache.org/jira/browse/IGNITE-21084

IGNITE-21084 Round up timestamp-to-wait-after-DDL to the closest millisecond

---

modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/PlacementDriverManagerTest.java
modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java

https://issues.apache.org/jira/browse/IGNITE-21106

IGNITE-21106 Obsolete leases removal

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java

https://issues.apache.org/jira/browse/IGNITE-20916

IGNITE-20916 Remove API future related code from TableManager

---

modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/Leases.java
modules/replicator/src/main/java/org/apache/ignite/internal/replicator/Replica.java

https://issues.apache.org/jira/browse/IGNITE-21040

IGNITE-21040 Placement driver logging enhancement

---

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java

https://issues.apache.org/jira/browse/IGNITE-21108

IGNITE-21108 Fixed NPE in ReplicaManager

---

modules/cluster-management/build.gradle
modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/topology/ItLogicalTopologyTest.java

https://issues.apache.org/jira/browse/IGNITE-21121

IGNITE-21121 Move ItLogicalTopologyTest to the cluster-management module

---

modules/network-api/src/main/java/org/apache/ignite/network/AbstractMessagingService.java
modules/network-api/src/main/java/org/apache/ignite/network/TrackableNetworkMessageHandler.java

https://issues.apache.org/jira/browse/IGNITE-21124

IGNITE-21124 Add ability to log long message processing

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateTableCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogTableDescriptor.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/AlterColumnEntry.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/DropColumnsEntry.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/NewColumnsEntry.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/MakeIndexAvailableCommandValidationTest.java
modules/client-handler/src/testFixtures/java/org/apache/ignite/client/handler/FakeCatalogService.java
modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtilUpdateAssignmentsTest.java
modules/schema/src/test/java/org/apache/ignite/internal/schema/SchemaManagerTest.java
modules/schema/src/test/java/org/apache/ignite/internal/schema/catalog/CatalogToSchemaDescriptorConverterTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractIndexStorageTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/schema/CatalogValidationSchemasSourceTest.java

https://issues.apache.org/jira/browse/IGNITE-21014

IGNITE-21014 Add table creation revision for table descriptor

---

modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/jdbc/JdbcQueryCursor.java
modules/client-handler/src/test/java/org/apache/ignite/client/handler/requests/jdbc/JdbcQueryCursorSelfTest.java
modules/client/src/test/java/org/apache/ignite/client/fakes/FakeCursor.java
modules/core/src/main/java/org/apache/ignite/internal/util/AsyncWrapper.java
modules/core/src/test/java/org/apache/ignite/internal/util/AsyncWrapperSelfTest.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/Loza.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlApiBaseTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/BaseSqlMultiStatementTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlMultiStatementTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlMultiStatementTxTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/AsyncSqlCursor.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/AsyncSqlCursorImpl.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlQueryProcessor.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/AsyncRootNode.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/tx/QueryTransactionWrapper.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/tx/QueryTransactionWrapperImpl.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/tx/ScriptTransactionContext.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/tx/ScriptTransactionWrapperImpl.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/AsyncSqlCursorImplTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/AsyncRootNodeTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/util/QueryCheckerTest.java

This patch introduces parallelisation for sequence of SELECT statements.
===============
- [Apache Ignite Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Java+Code+Style …

IGNITE-20673 Sql. Independent multi statement queries need to be executed in parallel

---

modules/network/src/main/java/org/apache/ignite/internal/network/recovery/HandshakeManagerUtils.java
modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryClientHandshakeManager.java
modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryServerHandshakeManager.java
modules/network/src/test/java/org/apache/ignite/internal/network/recovery/RecoveryClientHandshakeManagerTest.java
modules/network/src/test/java/org/apache/ignite/internal/network/recovery/RecoveryServerHandshakeManagerTest.java

https://issues.apache.org/jira/browse/IGNITE-21138

IGNITE-21138 Complete client-side handshake future with NodeStoppingException if rejecting a handshake due to stopping

---

modules/api/src/main/java/org/apache/ignite/lang/ErrorGroups.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CatalogUtils.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AlterTableAlterColumnCommandValidationTest.java
modules/schema/src/main/java/org/apache/ignite/internal/schema/registry/UpgradingRowAdapter.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItAlterTableAlterColumnTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCreateTableDdlTest.java
modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/engine/util/SqlTestUtils.java

AlterTableAlterColumnCommandValidationTest and CatalogManagerSelfTest main validation test, seems no need to copy all checks into integration one.

IGNITE-20906 Sql. Fix possibility to change column type according to IEP-108

---

modules/network/src/main/java/org/apache/ignite/internal/network/message/ClassDescriptorMessage.java
modules/network/src/main/java/org/apache/ignite/internal/network/serialization/ClassDescriptor.java
modules/network/src/main/java/org/apache/ignite/internal/network/serialization/ClassDescriptorFactory.java
modules/network/src/main/java/org/apache/ignite/internal/network/serialization/ClassDescriptorRegistry.java
modules/network/src/main/java/org/apache/ignite/internal/network/serialization/Classes.java
modules/network/src/main/java/org/apache/ignite/internal/network/serialization/DeclaredType.java
modules/network/src/main/java/org/apache/ignite/internal/network/serialization/FieldDescriptor.java
modules/network/src/main/java/org/apache/ignite/internal/network/serialization/PerSessionSerializationService.java
modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/BuiltInContainerMarshallers.java
modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshaller.java
modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/NullsBitsetWriter.java
modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/CleanSlateUnmarshaller.java
modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerWithArbitraryObjectsTest.java
modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerWithBuiltinsTest.java
modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerWithExternalizableTest.java
modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerWithSchemaChangeTest.java
modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerWithSerializableOverrideStreamsTest.java
modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerWithSerializableTest.java
modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/TestUnmarshalUtils.java
modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/TestUnmarshaling.java
modules/network/src/test/java/org/apache/ignite/network/DefaultMessagingServiceTest.java
modules/network/src/testFixtures/java/org/apache/ignite/internal/network/messages/InstantContainer.java
modules/network/src/testFixtures/java/org/apache/ignite/internal/network/messages/MessageWithInstant.java

https://issues.apache.org/jira/browse/IGNITE-21159

IGNITE-21159 Deserialization of Instant field in a Marshallable fails

---

modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientOp.java
modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java
modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlExecuteRequest.java
modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlParameterMetadataRequest.java
modules/client/src/main/java/org/apache/ignite/internal/client/ClientUtils.java
modules/client/src/test/java/org/apache/ignite/client/RetryPolicyTest.java
modules/platforms/cpp/ignite/client/detail/cluster_connection.h
modules/platforms/cpp/ignite/client/detail/compute/compute_impl.cpp
modules/platforms/cpp/ignite/client/detail/node_connection.cpp
modules/platforms/cpp/ignite/client/detail/response_handler.h
modules/platforms/cpp/ignite/common/primitive.h
modules/platforms/cpp/ignite/odbc/app/parameter_set.cpp
modules/platforms/cpp/ignite/odbc/app/parameter_set.h
modules/platforms/cpp/ignite/odbc/config/configuration.h
modules/platforms/cpp/ignite/odbc/config/connection_info.h
modules/platforms/cpp/ignite/odbc/module.def
modules/platforms/cpp/ignite/odbc/query/data_query.cpp
modules/platforms/cpp/ignite/odbc/query/special_columns_query.cpp
modules/platforms/cpp/ignite/odbc/query/special_columns_query.h
modules/platforms/cpp/ignite/odbc/sql_connection.cpp
modules/platforms/cpp/ignite/odbc/sql_statement.cpp
modules/platforms/cpp/ignite/odbc/type_traits.cpp
modules/platforms/cpp/ignite/protocol/client_operation.h
modules/platforms/cpp/ignite/protocol/messages.h
modules/platforms/cpp/tests/odbc-test/api_robustness_test.cpp
modules/platforms/cpp/tests/odbc-test/connection_test.cpp
modules/platforms/cpp/tests/odbc-test/meta_queries_test.cpp
modules/platforms/cpp/tests/odbc-test/queries_test.cpp
modules/platforms/dotnet/Apache.Ignite/Internal/Proto/ClientOp.cs
modules/platforms/dotnet/Apache.Ignite/Internal/Proto/ClientOpExtensions.cs

- Added `ClientSqlParameterMetadataRequest` server side class;
- Implemented request sending on ODBC side;
- Un-muted old tests;
- Added a new test.

IGNITE-19854 Parameter metadata fetching for non-executed query

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java

https://issues.apache.org/jira/browse/IGNITE-21169

IGNITE-21107 Prevent double storage update in case of 1PC transaction

---

modules/table/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java

https://issues.apache.org/jira/browse/IGNITE-21180

IGNITE-21180 Enable tests in ItTableRaftSnapshotsTest

---

modules/runner/src/testFixtures/java/org/apache/ignite/internal/ClusterPerClassIntegrationTest.java

https://issues.apache.org/jira/browse/IGNITE-21178

IGNITE-21178 Add delay duration when waiting for indexes

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/schemasync/ItSchemaForwardCompatibilityTest.java

https://issues.apache.org/jira/browse/IGNITE-21187

IGNITE-21187 Enable type changing-related test in ItSchemaForwardCompatibilityTest

---

modules/core/src/main/java/org/apache/ignite/internal/event/AbstractEventProducer.java

https://issues.apache.org/jira/browse/IGNITE-21198

IGNITE-21198 Optimize memory usage in AbstractEventProducer#fireEvent

---

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/Replica.java
modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java
modules/replicator/src/main/java/org/apache/ignite/internal/replicator/listener/ReplicaListener.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerDurableUnlockTest.java

https://issues.apache.org/jira/browse/IGNITE-21196

IGNITE-21196 Optimize primary replica events processing

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbSharedStorage.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbStorage.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbTableStorage.java
modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/rocksdb/RocksDbTxStateStorageTest.java
modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/AbstractTxStateStorageTest.java

https://issues.apache.org/jira/browse/IGNITE-21204

IGNITE-21204 Implement shared rocksdb storage for transaction states

---

build.gradle
modules/runner/build.gradle

https://issues.apache.org/jira/browse/IGNITE-21128

IGNITE-21128 Add default jvm args to runnerPlatformTest

---

modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java
modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/negotiation/LeaseAgreement.java

https://issues.apache.org/jira/browse/IGNITE-21206

IGNITE-21206 Lease grant messages should be retried after the failure of the placement driver active actor

---

modules/platforms/cpp/ignite/client/detail/sql/result_set_impl.h
modules/platforms/cpp/ignite/client/detail/sql/sql_impl.cpp
modules/platforms/cpp/ignite/client/detail/sql/sql_impl.h
modules/platforms/cpp/ignite/client/sql/result_set.cpp
modules/platforms/cpp/ignite/client/sql/result_set.h
modules/platforms/cpp/ignite/client/sql/sql.cpp
modules/platforms/cpp/ignite/client/sql/sql.h
modules/platforms/cpp/ignite/protocol/client_operation.h
modules/platforms/cpp/tests/client-test/sql_test.cpp

- Implement script API in C++;
- Added tests;
- Introduced some minor fixes for `result_page` class.

IGNITE-20653 SQL script execution for C++ Client

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTransactionConflictTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTransactionRecoveryTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java

https://issues.apache.org/jira/browse/IGNITE-20995

IGNITE-20995 Add more integration tests for tx recovery on unstable topology

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogService.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java
modules/client-handler/src/testFixtures/java/org/apache/ignite/client/handler/FakeCatalogService.java

https://issues.apache.org/jira/browse/IGNITE-21214

IGNITE-21214 Add Catalog API to get a schema by ID

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateTableCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogTableDescriptor.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogTableSchemaVersions.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/AlterColumnEntry.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/DropColumnsEntry.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/NewColumnsEntry.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/MakeIndexAvailableCommandValidationTest.java
modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/jdbc/JdbcMetadataCatalog.java
modules/client-handler/src/testFixtures/java/org/apache/ignite/client/handler/FakeCatalogService.java
modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtilUpdateAssignmentsTest.java
modules/schema/src/main/java/org/apache/ignite/internal/schema/SchemaManager.java
modules/schema/src/main/java/org/apache/ignite/internal/schema/SchemaUtils.java
modules/schema/src/main/java/org/apache/ignite/internal/schema/catalog/CatalogToSchemaDescriptorConverter.java
modules/schema/src/test/java/org/apache/ignite/internal/schema/SchemaManagerTest.java
modules/schema/src/test/java/org/apache/ignite/internal/schema/catalog/CatalogToSchemaDescriptorConverterTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractIndexStorageTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/schema/CatalogValidationSchemasSourceTest.java

https://issues.apache.org/jira/browse/IGNITE-21205

IGNITE-21205 Get rid of metastorage in schema manager

---

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/mapping/QuerySplitter.java
modules/sql-engine/src/test/resources/mapping/correlated.test
modules/sql-engine/src/test/resources/mapping/table_functions.test

https://issues.apache.org/jira/browse/IGNITE-20795
---

IGNITE-20795: Sql. QuerySplitter does not visit IgniteTableFunctionScan nodes.

---

modules/platforms/cpp/ignite/common/error_codes.h
modules/platforms/cpp/ignite/odbc/common_types.cpp
modules/platforms/dotnet/Apache.Ignite/ErrorCodes.g.cs

https://issues.apache.org/jira/browse/IGNITE-21233

IGNITE-21233 Fix missing error codes

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/RenameTableCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/RenameTableCommandBuilder.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/CatalogEvent.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/RenameTableEventParameters.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/RenameTableEntry.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/RenameTableCommandValidationTest.java
modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTable.java
modules/client/src/test/java/org/apache/ignite/client/fakes/FakeInternalTable.java
modules/table/src/main/java/org/apache/ignite/internal/table/InternalTable.java
modules/table/src/main/java/org/apache/ignite/internal/table/TableImpl.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java

https://issues.apache.org/jira/browse/IGNITE-21215

IGNITE-21215 Add Catalog API for renaming a table

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDmlTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/DecimalLiteralTest.java

IGNITE-20381 Prevent modification operations call after CatalogManagerImpl is closed

---

modules/network-api/src/main/java/org/apache/ignite/network/NetworkMessageHandler.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/message/MessageServiceImpl.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestClusterTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestNode.java

…opped but incoming message still processed

IGNITE-21226 NPE throws from MessageServiceImpl if service already stopped but incoming message still processed

---

modules/compute/src/main/java/org/apache/ignite/internal/compute/queue/QueueEntry.java

https://issues.apache.org/jira/browse/IGNITE-21282

IGNITE-21282 Fix flaky ItComputeTestEmbedded#cancelsJobLocally

---

modules/client-common/src/main/java/org/apache/ignite/internal/jdbc/JdbcConverterUtils.java
modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcStatementSelfTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDynamicParameterTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItFunctionsTest.java

IGNITE-21134 Sql. Support NULL column type in jdbc

---

modules/network/README.md
modules/runner/README.md
modules/runner/threading.md

https://issues.apache.org/jira/browse/IGNITE-21273

IGNITE-21273 Document newly-added thread pools in README files

---

modules/network/src/main/java/org/apache/ignite/internal/network/direct/DirectMessageWriter.java
modules/network/src/main/java/org/apache/ignite/internal/network/direct/stream/DirectByteBufferStreamImplV1.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/util/OptimizedMarshaller.java

https://issues.apache.org/jira/browse/IGNITE-21309

IGNITE-21309 Avoid potential memory leaks in direct message writer

---

modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItTransactionRecoveryTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java
modules/table/src/testFixtures/java/org/apache/ignite/internal/table/TxAbstractTest.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/MismatchingTransactionOutcomeException.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadWriteTransactionImpl.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java
modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerTest.java

https://issues.apache.org/jira/browse/IGNITE-21173

IGNITE-21173 Repeated call to commit/abort should not emit exceptions

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItFunctionsTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/IgniteSqlFunctions.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/RexImpTable.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/fun/IgniteSqlOperatorTable.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/IgniteMethod.java

IGNITE-20809 Sql. SUBSTRING function need to handle different numeric types as a params

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/LowWatermark.java

IGNITE-21328 Fix logging in LowWatermark#start when there is no low watermark in vault

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CatalogUtils.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/AlterColumnEntry.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/DropColumnsEntry.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/NewColumnsEntry.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/RenameTableEntry.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/CatalogUtilsTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/CompatValidationResult.java

https://issues.apache.org/jira/browse/IGNITE-21339

IGNITE-21339 Introduce a utility method to replace a Catalog table descriptor in a schema

---

modules/cli/src/main/java/org/apache/ignite/internal/cli/core/JdbcUrlFactory.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/core/JdbcUrlFactoryTest.java
modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcAuthenticationTest.java
modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc/ConnectionProperties.java
modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc/ConnectionPropertiesImpl.java
modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc/JdbcConnection.java

Removes basic auth prefix from JDBC connection properties.
https://issues.apache.org/jira/browse/IGNITE-20829
--- …

IGNITE-20829: Remove "basicAuthentication" prefix from JDBC url connection properties

---

modules/workers/src/main/java/org/apache/ignite/internal/worker/CriticalWorkerWatchdog.java

https://issues.apache.org/jira/browse/IGNITE-21343

IGNITE-21343 Do not cut thread dump depth in warnings about critical worker blockage

---

modules/error-code-annotation-processor/src/main/java/org/apache/ignite/internal/error/code/generators/GenericGenerator.java

https://issues.apache.org/jira/browse/IGNITE-21347

IGNITE-21347 Fix license header extra whitespaces in ErrorCodeGroup annotation processor

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogService.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java
modules/client-handler/src/testFixtures/java/org/apache/ignite/client/handler/FakeCatalogService.java
modules/index/src/main/java/org/apache/ignite/internal/index/IndexManagementUtils.java
modules/index/src/test/java/org/apache/ignite/internal/index/IndexManagementUtilsTest.java

https://issues.apache.org/jira/browse/IGNITE-21357

IGNITE-21357 Getting the catalog version in which the index created

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java

https://issues.apache.org/jira/browse/IGNITE-21317

IGNITE-21317 Disable tests

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AbstractTableCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CatalogUtils.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogSystemViewTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AbstractCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AlterTableAddColumnCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AlterTableAlterColumnCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AlterTableDropColumnCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/CreateTableCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/DropTableCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/RenameTableCommandValidationTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCreateTableDdlTest.java

IGNITE-20574 Sql. Do not permit to create tables in reserved system schemas

---

modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/ItClusterStateHttpServerFilterNotInitializedTest.java
modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/ItNotInitializedClusterRestTest.java

https://issues.apache.org/jira/browse/IGNITE-21377

IGNITE-21377 Remove redundant tests

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replication/request/ReadWriteReplicaRequest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java

https://issues.apache.org/jira/browse/IGNITE-21017

IGNITE-21017 Tracking RW transaction update operations

---

modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/ActiveActorTest.java
modules/replicator/src/test/java/org/apache/ignite/internal/raft/client/TopologyAwareRaftGroupServiceTest.java

https://issues.apache.org/jira/browse/IGNITE-21381

IGNITE-21381 disable flaky testChangeLeaderForce tests

---

modules/core/src/main/java/org/apache/ignite/internal/util/CompletableFutures.java
modules/network/src/integrationTest/java/org/apache/ignite/internal/network/netty/ItConnectionManagerTest.java
modules/network/src/integrationTest/java/org/apache/ignite/network/scalecube/ItScaleCubeNetworkMessagingTest.java
modules/network/src/main/java/org/apache/ignite/internal/network/netty/ChannelKey.java
modules/network/src/main/java/org/apache/ignite/internal/network/netty/DefaultRecoveryDescriptorProvider.java
modules/network/src/main/java/org/apache/ignite/internal/network/netty/NettySender.java
modules/network/src/main/java/org/apache/ignite/internal/network/recovery/HandshakeManagerUtils.java
modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryClientHandshakeManager.java
modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryDescriptor.java
modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryServerHandshakeManager.java
modules/network/src/main/java/org/apache/ignite/network/DefaultMessagingService.java
modules/network/src/main/java/org/apache/ignite/network/OutNetworkObject.java
modules/network/src/test/java/org/apache/ignite/internal/network/netty/NettyClientTest.java
modules/network/src/test/java/org/apache/ignite/internal/network/recovery/RecoveryClientHandshakeManagerTest.java
modules/network/src/test/java/org/apache/ignite/internal/network/recovery/RecoveryServerHandshakeManagerTest.java
modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java

https://issues.apache.org/jira/browse/IGNITE-21336

IGNITE-21336 Handle ClosedChannelException gracefully

---

modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java

https://issues.apache.org/jira/browse/IGNITE-21391

IGNITE-21391 Disable ItNodeTest#testAppendEntriesWhenFollowerIsInErrorState

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogService.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AbstractCreateIndexCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateHashIndexCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateSortedIndexCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateTableCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogHashIndexDescriptor.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogIndexDescriptor.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogSortedIndexDescriptor.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/AbstractChangeIndexStatusEntry.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerRecoveryTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AbstractChangeIndexStatusCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AbstractCommandValidationTest.java
modules/catalog/src/testFixtures/java/org/apache/ignite/internal/catalog/BaseCatalogManagerTest.java
modules/client-handler/src/testFixtures/java/org/apache/ignite/client/handler/FakeCatalogService.java
modules/index/src/main/java/org/apache/ignite/internal/index/IndexManagementUtils.java
modules/index/src/test/java/org/apache/ignite/internal/index/IndexManagementUtilsTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractHashIndexStorageTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractSortedIndexStorageTest.java

https://issues.apache.org/jira/browse/IGNITE-21376

IGNITE-21376 Add the catalog version in which the index was created

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItDataSchemaSyncTest.java

https://issues.apache.org/jira/browse/IGNITE-21400

IGNITE-21400 Disable ItDataSchemaSyncTest.checkSchemasCorrectlyRestore test

---

modules/network/src/main/java/org/apache/ignite/internal/network/netty/ChannelEventLoopsSource.java
modules/network/src/main/java/org/apache/ignite/internal/network/netty/ConnectionManager.java
modules/network/src/main/java/org/apache/ignite/internal/network/recovery/HandshakeManagerUtils.java
modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryClientHandshakeManager.java
modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryServerHandshakeManager.java
modules/network/src/main/java/org/apache/ignite/network/NettyBootstrapFactory.java
modules/network/src/main/java/org/apache/ignite/network/NettyWorkersRegistrar.java
modules/network/src/test/java/org/apache/ignite/internal/network/netty/RecoveryHandshakeTest.java
modules/network/src/test/java/org/apache/ignite/internal/network/recovery/RecoveryClientHandshakeManagerTest.java
modules/network/src/test/java/org/apache/ignite/internal/network/recovery/RecoveryServerHandshakeManagerTest.java
modules/network/src/test/java/org/apache/ignite/network/DefaultMessagingServiceTest.java

https://issues.apache.org/jira/browse/IGNITE-21414

IGNITE-21414 Use the same event loop for channels of the same logical connection

---

modules/raft-api/src/main/java/org/apache/ignite/internal/raft/service/LeaderWithTerm.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/RaftGroupServiceImpl.java
modules/replicator/src/main/java/org/apache/ignite/internal/raft/client/TopologyAwareRaftGroupService.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerIndexLockingTest.java

https://issues.apache.org/jira/browse/IGNITE-21394

IGNITE-21394 TimeoutException in the listener of pending assignments change shouldn't fail the watch processor

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogHashIndexDescriptor.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogIndexDescriptor.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogObjectDescriptor.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogSchemaDescriptor.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogSortedIndexDescriptor.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogSystemViewDescriptor.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogTableDescriptor.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogZoneDescriptor.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/descriptors/CatalogDataStorageDescriptorTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/descriptors/CatalogHashIndexDescriptorTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/descriptors/CatalogSchemaDescriptorTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/descriptors/CatalogSortedIndexDescriptorTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/descriptors/CatalogSystemViewDescriptorTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/descriptors/CatalogTableDescriptorTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/descriptors/CatalogZoneDescriptorTest.java

https://issues.apache.org/jira/browse/IGNITE-21423

IGNITE-21423 Improve toString() implementations for classes representing Catalog objects

---

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZonesUtil.java
modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneFiltersTest.java

https://issues.apache.org/jira/browse/IGNITE-21313

IGNITE-21313 JsonPath configuration is updated at zone filtering.

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/IndexBuilderTxRwOperationTracker.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/ReplicatorUtils.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replicator/ReplicatorUtilsTest.java
modules/table/src/testFixtures/java/org/apache/ignite/internal/table/TableTestUtils.java

https://issues.apache.org/jira/browse/IGNITE-21398

IGNITE-21398 Correct IndexBuilderTxRwOperationTracker update in PartitionReplicaListener

---

modules/client/src/test/java/org/apache/ignite/client/fakes/FakeCompute.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/IgniteComputeImpl.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/IgniteComputeInternal.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/compute/ComputeController.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/compute/ComputeRestFactory.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java

https://issues.apache.org/jira/browse/IGNITE-21420

IGNITE-21420 Refactor ComputeController

---

modules/compute/src/main/java/org/apache/ignite/internal/compute/queue/QueueExecutionImpl.java
modules/compute/src/test/java/org/apache/ignite/internal/compute/queue/PriorityQueueExecutorTest.java

https://issues.apache.org/jira/browse/IGNITE-21422

IGNITE-21422 Cancelling queued job should cancel result

---

modules/core/build.gradle

https://issues.apache.org/jira/browse/IGNITE-21397

IGNITE-21397 Remove fastutil shading from ignite-core module

---

modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java

https://issues.apache.org/jira/browse/IGNITE-21448

IGNITE-21448 Fix build

---

build.gradle

https://issues.apache.org/jira/browse/IGNITE-21446

IGNITE-21446 Add IDEA JUnit run configuration setting to build.gradle

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTableScanTest.java

https://issues.apache.org/jira/browse/IGNITE-21455

IGNITE-21455 ItTableScanTest#testCompositeScanRequest is flaky

---

modules/platforms/cpp/ignite/client/detail/client_error_flags.h
modules/platforms/cpp/ignite/client/detail/table/table_impl.cpp
modules/platforms/cpp/ignite/client/detail/utils.cpp
modules/platforms/cpp/ignite/common/ignite_error.h
modules/platforms/cpp/tests/client-test/CMakeLists.txt
modules/platforms/cpp/tests/client-test/key_value_binary_view_test.cpp
modules/platforms/cpp/tests/client-test/record_binary_view_test.cpp
modules/platforms/cpp/tests/client-test/record_view_test.cpp
modules/platforms/cpp/tests/client-test/schema_synchronization_test.cpp

- Added test with `ALTER TABLE`;
- Implemented schema retry on unmapped columns;

IGNITE-20241 C++ Reload schema when unmapped columns are detected

---

modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java

https://issues.apache.org/jira/browse/IGNITE-21457

IGNITE-21457 disable flaky ItNodeTest.testSetPeer2 test

---

modules/network/src/integrationTest/java/org/apache/ignite/internal/network/netty/ItConnectionManagerTest.java
modules/network/src/integrationTest/java/org/apache/ignite/internal/network/netty/OutgoingAcknowledgementSilencer.java
modules/network/src/main/java/org/apache/ignite/internal/network/netty/NettySender.java

https://issues.apache.org/jira/browse/IGNITE-21470

IGNITE-21470 Wait for sender to appear before applying an ack silencer

---

modules/network/src/test/java/org/apache/ignite/internal/network/DefaultMessagingServiceTest.java

https://issues.apache.org/jira/browse/IGNITE-21471

IGNITE-21471 Change approach in sendMessagesTwoChannels in DefaultMessagingServiceTest

---

modules/core/src/main/java/org/apache/ignite/internal/tostring/IgniteToStringBuilder.java
modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java

https://issues.apache.org/jira/browse/IGNITE-21247

IGNITE-21247 Log enhancements for LeaseUpdater

---

build.gradle

https://issues.apache.org/jira/browse/IGNITE-21477

IGNITE-21477 Fix jvmArgs propagation in tests

---

modules/compute/src/main/java/org/apache/ignite/internal/compute/queue/QueueExecutionImpl.java
modules/compute/src/test/java/org/apache/ignite/internal/compute/queue/PriorityQueueExecutorTest.java

IGNITE-21479 Fix race with setting priority in PriorityQueueExecutorTest

---

modules/workers/src/main/java/org/apache/ignite/internal/worker/ThreadAssertions.java

https://issues.apache.org/jira/browse/IGNITE-21488

IGNITE-21488 Disable thread assertions by default

---

modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java

IGNITE-21317 Disable testClientsAreUpdatedAfterPendingRebalanceHandled

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/ClockWaiter.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java
modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/DeploymentManagerImpl.java
modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/FileDeployerService.java
modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/metastore/NodeStatusWatchListener.java
modules/code-deployment/src/test/java/org/apache/ignite/deployment/FileDeployerServiceTest.java
modules/compute/src/test/java/org/apache/ignite/internal/compute/loader/JobContextManagerTest.java
modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/distributionzones/ItIgniteDistributionZoneManagerNodeRestartTest.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/DefaultLogStorageFactory.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/VolatileLogStorageFactoryCreator.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/logit/LogitLogStorageFactory.java
modules/raft/src/test/java/org/apache/ignite/raft/jraft/storage/impl/LogStorageBenchmark.java
modules/raft/src/test/java/org/apache/ignite/raft/jraft/storage/logit/LogitLogStorageTest.java
modules/runner/src/defaultsGenerator/java/org/apache/ignite/internal/configuration/generator/DefaultsGenerator.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/ItDistributedConfigurationPropertiesTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/storage/ItDistributedConfigurationStorageTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/runner/src/main/java/org/apache/ignite/internal/configuration/storage/DistributedConfigurationStorage.java
modules/runner/src/main/java/org/apache/ignite/internal/configuration/storage/LocalFileConfigurationStorage.java
modules/runner/src/test/java/org/apache/ignite/internal/configuration/storage/DistributedConfigurationStorageTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PrepareServiceImpl.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/gc/MvGc.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/outgoing/OutgoingSnapshotsManager.java

https://issues.apache.org/jira/browse/IGNITE-21486

IGNITE-21486 Pass node name to NamedThreadFactory where possible

---

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/hints/ForceIndexHintPlannerTest.java

IGNITE-21453 Fix force index hint test.

---

modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java

https://issues.apache.org/jira/browse/IGNITE-21317
Table creation/Zone altering awaiting logic added.

IGNITE-21317 Fix ItRebalanceDistributedTest

---

modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadOnlyTransactionImpl.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java

https://issues.apache.org/jira/browse/IGNITE-21375

IGNITE-21375 RO transactions should not update txnState local map

---

modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
modules/table/src/testFixtures/java/org/apache/ignite/internal/table/TxAbstractTest.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java

https://issues.apache.org/jira/browse/IGNITE-21503

IGNITE-21503 Fix ItRebalanceDistributedTest#testRebalanceWithTheSameNodes

---

modules/network/src/integrationTest/java/org/apache/ignite/internal/network/netty/ItConnectionManagerTest.java
modules/network/src/integrationTest/java/org/apache/ignite/internal/network/scalecube/ItScaleCubeNetworkMessagingTest.java

https://issues.apache.org/jira/browse/IGNITE-21493

IGNITE-21493 Apply ack silencer when the channel is open

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/schemasync/ItSchemaSyncMultiNodeTest.java
modules/runner/src/testFixtures/java/org/apache/ignite/internal/ClusterPerTestIntegrationTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java

https://issues.apache.org/jira/browse/IGNITE-21316

IGNITE-21316 Add manual schema sync to ItRebalanceDistributedTest

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItReadOnlyTransactionTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTableScanTest.java
modules/schema/src/main/java/org/apache/ignite/internal/schema/SchemaDescriptor.java
modules/schema/src/main/java/org/apache/ignite/internal/schema/marshaller/reflection/ObjectStatistics.java
modules/schema/src/main/java/org/apache/ignite/internal/schema/row/RowAssembler.java
modules/schema/src/test/java/org/apache/ignite/internal/schema/RowTest.java
modules/schema/src/test/java/org/apache/ignite/internal/schema/registry/UpgradingRowAdapterTest.java
modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItAbstractInternalTableScanTest.java
modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItInternalTableReadOnlyOperationsTest.java
modules/table/src/integrationTest/java/org/apache/ignite/distributed/ReplicaUnavailableTest.java
modules/table/src/main/java/org/apache/ignite/internal/schema/marshaller/TupleMarshallerImpl.java
modules/table/src/test/java/org/apache/ignite/internal/table/ColocationHashCalculationTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/PartitionCommandListenerTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotCopierTest.java

This patch doesn't change format of marshalled table rows in any way, only rearranges the code.
------------------- …

IGNITE-21506 Refactoring of tuple marshaller

---

build.gradle

https://issues.apache.org/jira/browse/IGNITE-21515

IGNITE-21515 enable assertions for idea test runner

---

modules/schema/src/main/java/org/apache/ignite/internal/schema/SchemaManager.java
modules/schema/src/test/java/org/apache/ignite/internal/schema/SchemaManagerTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java

IGNITE-21532 Fix schema manager recovery

---

.asf.yaml

See https://github.com/apache/infrastructure-asfyaml?tab=readme-ov-file#autolinks-for-jira

Enable GitHub autolink for Jira tickets

---

modules/core/src/main/java/org/apache/ignite/internal/thread/ThreadOperation.java
modules/core/src/test/java/org/apache/ignite/internal/thread/IgniteThreadFactoryTest.java
modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/BaseIgniteAbstractTest.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/JRaftUtils.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/util/concurrent/DefaultFixedThreadsExecutorGroupFactory.java
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/ThreadAssertingMvPartitionStorage.java
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/ThreadAssertingPartitionTimestampCursor.java
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/ThreadAssertingIndexStorage.java
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/ThreadAssertingPeekCursor.java
modules/table/build.gradle
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
modules/transactions/build.gradle
modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/ThreadAssertingTxStateStorage.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/ThreadAssertingTxStateTableStorage.java
modules/workers/src/main/java/org/apache/ignite/internal/worker/ThreadAssertingCursor.java
modules/workers/src/main/java/org/apache/ignite/internal/worker/ThreadAssertions.java

https://issues.apache.org/jira/browse/IGNITE-21517

IGNITE-21517 Add thread assertions to TxStateStorage

---

modules/client/src/test/java/org/apache/ignite/client/fakes/FakeInternalTable.java
modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/ItPrimaryReplicaChoiceTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItInternalTableTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTableScanTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ScannableTableImpl.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/ScannableTableSelfTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/TableScanNodeExecutionTest.java
modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItAbstractInternalTableScanTest.java
modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItInternalTableReadOnlyScanTest.java
modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItInternalTableReadWriteScanTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItTransactionRecoveryTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/InternalTable.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java
modules/table/src/testFixtures/java/org/apache/ignite/internal/table/TxAbstractTest.java

https://issues.apache.org/jira/browse/IGNITE-21511

IGNITE-21511 Use read only transaction id in ReadOnlyScanRetrieveBatchReplicaRequest

---

packaging/common/setup-java.sh
packaging/zip/ignite3db

https://issues.apache.org/jira/browse/IGNITE-19608
The following changes are made:
* The output is redirected to the ignite3db-startup.log
* Useful error-handling flags are set
* Timeout is set to wait java application startup.

IGNITE-19608 Improve the UIX of ignite3db script

---

modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientMessagePacker.java
modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientMessageUnpacker.java
modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientOp.java
modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java
modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlExecuteBatchRequest.java
modules/client/src/main/java/org/apache/ignite/client/ClientOperationType.java
modules/client/src/main/java/org/apache/ignite/client/RetryReadPolicy.java
modules/client/src/main/java/org/apache/ignite/internal/client/ClientUtils.java
modules/platforms/cpp/ignite/common/ignite_error.h
modules/platforms/cpp/ignite/odbc/app/application_data_buffer.cpp
modules/platforms/cpp/ignite/odbc/query/data_query.cpp
modules/platforms/cpp/ignite/odbc/query/query.h
modules/platforms/cpp/ignite/odbc/sql_statement.cpp
modules/platforms/cpp/ignite/protocol/client_operation.h
modules/platforms/cpp/ignite/protocol/protocol_version.cpp
modules/platforms/cpp/ignite/protocol/protocol_version.h
modules/platforms/cpp/ignite/protocol/reader.h
modules/platforms/cpp/tests/odbc-test/odbc_connection.h
modules/platforms/cpp/tests/odbc-test/odbc_test_utils.h
modules/platforms/cpp/tests/odbc-test/queries_test.cpp
modules/platforms/cpp/tests/odbc-test/timeout_test.cpp

https://issues.apache.org/jira/browse/IGNITE-19215

IGNITE-19215 ODBC 3.0: Implement DML data batching

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/CatalogEvent.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/DestroyIndexEvent.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/DestroyIndexEventParameters.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/DestroyTableEvent.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/DestroyTableEventParameters.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/IndexEventParameters.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/MakeIndexAvailableEventParameters.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/StartBuildingIndexEventParameters.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/UpdateLog.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/UpdateLogImpl.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerRecoveryTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java
modules/catalog/src/testFixtures/java/org/apache/ignite/internal/catalog/BaseCatalogManagerTest.java
modules/catalog/src/testFixtures/java/org/apache/ignite/internal/catalog/CatalogTestUtils.java
modules/index/src/test/java/org/apache/ignite/internal/index/IndexManagerTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java

Rework EventParameters class hierarchy related to index events.
Add new Catalog events for indexes and tests. …

IGNITE-21535 Create catalog events for destroying table and index

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSecondaryIndexTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rule/TableScanToKeyValueGetRule.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/PrimaryKeyLookupPlannerTest.java

IGNITE-21524 Sql. Incorrect conversion to KeyValue plan

---

modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/BaseIgniteAbstractTest.java

https://issues.apache.org/jira/browse/IGNITE-21439

IGNITE-21439 Enable thread assertions in tests

---

modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/ActionRequestProcessor.java

https://issues.apache.org/jira/browse/IGNITE-21561

IGNITE-21561 Fix NullPointerException in ActionRequestProcessor

---

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/tree/BplusTree.java
modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/tree/io/BplusInnerIo.java
modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/tree/io/BplusIo.java

https://issues.apache.org/jira/browse/IGNITE-21573

IGNITE-21573 Fix IDEA warnings in BplusTree

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDmlTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/ddl/DdlSqlToCommandConverter.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/Commons.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/IgniteCustomAssignmentsRules.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/CastResolutionTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/prepare/ddl/DdlSqlToCommandConverterTest.java

IGNITE-20593 Sql. Fix all possible default expressions

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableUtils.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java

https://issues.apache.org/jira/browse/IGNITE-21549

IGNITE-21549 Add a wait for safeTtime(partition) before starting the index building process

---

modules/index/src/test/java/org/apache/ignite/internal/index/IndexManagerTest.java
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/MvTableStorage.java
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/HashIndexStorage.java
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/ThreadAssertingHashIndexStorage.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvTableStorage.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractHashIndexStorageTest.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/PageMemoryHashIndexStorage.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryMvTableStorageTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryMvTableStorageTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/AbstractPageMemoryHashIndexStorageTest.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/HashIndex.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbHashIndexStorage.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvTableStorageTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbHashIndexStorageTest.java

https://issues.apache.org/jira/browse/IGNITE-17626

IGNITE-17626 Cleanup API for destroying indexes

---

modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/MvTableStorage.java
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/ThreadAssertingMvTableStorage.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/engine/AbstractStorageEngineTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvTableStorage.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/AbstractPageMemoryTableStorage.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/PersistentPageMemoryHashIndexStorageTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/PersistentPageMemorySortedIndexStorageTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/VolatilePageMemoryHashIndexStorageTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/VolatilePageMemorySortedIndexStorageTest.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorage.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvTableStorageTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbHashIndexStorageTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbSortedIndexStorageTest.java

https://issues.apache.org/jira/browse/IGNITE-21590

IGNITE-21590 Remove MvTableStorage#stop method

---

modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractSortedIndexStorageTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/AbstractPageMemorySortedIndexStorageTest.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/HashIndex.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMetaStorage.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorage.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/SortedIndex.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/AbstractRocksDbIndexStorage.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbHashIndexStorage.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvTableStorageTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbHashIndexStorageTest.java

https://issues.apache.org/jira/browse/IGNITE-21574

IGNITE-21574 Implement index destruction for RocksDB engine

---

modules/table/src/main/java/org/apache/ignite/internal/table/TableImpl.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableIndexStoragesSupplier.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/command/BuildIndexCommand.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexUpdateHandler.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/index/IndexUpdateHandlerTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/PartitionCommandListenerTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java
modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java

https://issues.apache.org/jira/browse/IGNITE-21560

IGNITE-21560 Add schema sync before apply BuildIndexCommand

---

modules/index/src/integrationTest/java/org/apache/ignite/internal/index/ItBuildIndexOneNodeTest.java
modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNodeNoCleanupMessage.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerIndexLockingTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java
modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java
modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummySchemaManagerImpl.java

https://issues.apache.org/jira/browse/IGNITE-21606

IGNITE-21606 Add tuple upgrade during filtering index scans

---

modules/client/src/test/java/org/apache/ignite/client/ClientLoggingTest.java
modules/client/src/test/java/org/apache/ignite/client/TestLoggerFactory.java

https://issues.apache.org/jira/browse/IGNITE-21616

IGNITE-21616 Fix ClientLoggingTest.testBasicLogging

---

modules/api/src/main/java/org/apache/ignite/compute/JobStatus.java
modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItExecutionsCleanerTest.java
modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/utils/TestingJobExecution.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/ComputeComponentImpl.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/ExecutionManager.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/IgniteComputeImpl.java
modules/compute/src/test/java/org/apache/ignite/internal/compute/state/InMemoryComputeStateMachineTest.java

https://issues.apache.org/jira/browse/IGNITE-21219

IGNITE-21219 Write memory leak tests

---

modules/platforms/dotnet/Apache.Ignite.Tests/BasicAuthenticatorTests.cs
modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTestExtensions.cs
modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs
modules/platforms/dotnet/Apache.Ignite.Tests/FakeServer.cs
modules/platforms/dotnet/Apache.Ignite.Tests/PartitionAwarenessTests.cs
modules/platforms/dotnet/Apache.Ignite.Tests/Proto/ColocationHashTests.cs
modules/platforms/dotnet/Apache.Ignite/Compute/ICompute.cs
modules/platforms/dotnet/Apache.Ignite/Compute/JobExecutionOptions.cs
modules/platforms/dotnet/Apache.Ignite/Internal/Compute/Compute.cs

Add `JobExecutionOptions` parameter to all .NET Compute APIs.

IGNITE-21334 .NET: Add JobExecutionOptions

---

modules/network/src/integrationTest/java/org/apache/ignite/internal/network/netty/ItConnectionManagerTest.java
modules/network/src/main/java/org/apache/ignite/internal/network/NetworkMessageTypes.java
modules/network/src/main/java/org/apache/ignite/internal/network/message/ClusterNodeMessage.java
modules/network/src/main/java/org/apache/ignite/internal/network/message/InvokeResponse.java
modules/network/src/main/java/org/apache/ignite/internal/network/netty/ConnectionManager.java
modules/network/src/main/java/org/apache/ignite/internal/network/netty/NettyServer.java
modules/network/src/main/java/org/apache/ignite/internal/network/recovery/HandshakeManagerUtils.java
modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryClientHandshakeManager.java
modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryClientHandshakeManagerFactory.java
modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryServerHandshakeManager.java
modules/network/src/main/java/org/apache/ignite/internal/network/recovery/message/HandshakeStartMessage.java
modules/network/src/main/java/org/apache/ignite/internal/network/recovery/message/HandshakeStartResponseMessage.java
modules/network/src/main/java/org/apache/ignite/internal/network/scalecube/ScaleCubeClusterServiceFactory.java
modules/network/src/main/java/org/apache/ignite/internal/network/scalecube/ScaleCubeDirectMarshallerTransport.java
modules/network/src/test/java/org/apache/ignite/internal/network/DefaultMessagingServiceTest.java
modules/network/src/test/java/org/apache/ignite/internal/network/netty/RecoveryHandshakeTest.java
modules/network/src/test/java/org/apache/ignite/internal/network/recovery/RecoveryClientHandshakeManagerTest.java
modules/network/src/test/java/org/apache/ignite/internal/network/recovery/RecoveryServerHandshakeManagerTest.java

https://issues.apache.org/jira/browse/IGNITE-21640

IGNITE-21640 Exchange with ClusterNode instances on handshake

---

modules/network/src/test/java/org/apache/ignite/internal/network/netty/NettyServerTest.java

https://issues.apache.org/jira/browse/IGNITE-21647

IGNITE-21647 Fix NettyServerTest flapping NullPointerException

---

check-rules/pmd-rules.xml
modules/client-handler/src/test/java/org/apache/ignite/client/handler/ClientResourceRegistryTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/exp/IgniteSqlFunctionsTest.java

IGNITE-21653 Fix PMD warning that there is unknown rule

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/LowWatermark.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/LowWatermarkChangedListener.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/gc/MvGc.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/LowWatermarkTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/gc/MvGcTest.java

https://issues.apache.org/jira/browse/IGNITE-21658
Minor LowWatermark refactoring.
- [Apache Ignite Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Java+Code+Style+Guide …

IGNITE-21658 Make LowWatermark a top level component

---

.idea/inspectionProfiles/Project_Default.xml
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/MvTableStorage.java
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/ThreadAssertingMvTableStorage.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/engine/AbstractStorageEngineTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvTableStorage.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/AbstractPageMemoryTableStorage.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/PersistentPageMemoryHashIndexStorageTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/PersistentPageMemorySortedIndexStorageTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/VolatilePageMemoryHashIndexStorageTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/VolatilePageMemorySortedIndexStorageTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorageConcurrencyTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorageGcTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorageTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/VolatilePageMemoryMvPartitionStorageConcurrencyTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/VolatilePageMemoryMvPartitionStorageGcTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/VolatilePageMemoryMvPartitionStorageTest.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorage.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorageConcurrencyTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorageGcTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorageTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvTableStorageTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageEngineTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbHashIndexStorageTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbSortedIndexStorageTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/gc/PersistentPageMemoryGcUpdateHandlerTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/gc/RocksDbGcUpdateHandlerTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/gc/VolatilePageMemoryGcUpdateHandlerTest.java

https://issues.apache.org/jira/browse/IGNITE-21670

IGNITE-21670 Remove MvTableStorage#start method

---

modules/core/src/main/java/org/apache/ignite/internal/thread/AbstractStripedThreadPoolExecutor.java
modules/core/src/main/java/org/apache/ignite/internal/thread/StripedExecutor.java
modules/core/src/main/java/org/apache/ignite/internal/thread/StripedScheduledThreadPoolExecutor.java
modules/core/src/main/java/org/apache/ignite/internal/thread/StripedThreadPoolExecutor.java
modules/network/src/main/java/org/apache/ignite/internal/network/DefaultMessagingService.java
modules/network/src/main/java/org/apache/ignite/internal/network/LazyStripedExecutors.java
modules/network/src/main/java/org/apache/ignite/internal/network/recovery/HandshakeManagerUtils.java
modules/workers/src/main/java/org/apache/ignite/internal/worker/CriticalSingleThreadExecutor.java
modules/workers/src/main/java/org/apache/ignite/internal/worker/CriticalStripedThreadPoolExecutor.java

https://issues.apache.org/jira/browse/IGNITE-21626

IGNITE-21626 Make each component of the Inbound pool striped

---

modules/file-io/src/main/java/org/apache/ignite/internal/fileio/FileIo.java
modules/file-io/src/main/java/org/apache/ignite/internal/fileio/FileIoDecorator.java
modules/file-io/src/main/java/org/apache/ignite/internal/fileio/RandomAccessFileIo.java
modules/file-io/src/test/java/org/apache/ignite/internal/fileio/AbstractFileIoTest.java
modules/file-io/src/test/java/org/apache/ignite/internal/fileio/AsyncFileIoTest.java

https://issues.apache.org/jira/browse/IGNITE-21682

IGNITE-21682 Remove transferFrom and transferTo from FileIo

---

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/hint/IgniteHint.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PlannerHelper.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PlannerPhase.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rel/IgniteSort.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rel/agg/IgniteColocatedAggregateBase.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rule/MergeJoinConverterRule.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rule/SortAggregateConverterRule.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rule/SortExchangeTransposeRule.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/trait/TraitUtils.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/Commons.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/HintUtils.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/AggregatePlannerTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/ColocatedSortAggregatePlannerTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/IdentityDistributionPlannerTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/JoinColocationPlannerTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/MapReduceSortAggregatePlannerTest.java

IGNITE-21668 Sql. Disable order-preserving multi target exchange

---

gradle/libs.versions.toml
modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/registry/impl/NodeNameRegistryImpl.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/core/exception/handler/IgniteCliApiExceptionHandlerTest.java

https://issues.apache.org/jira/browse/IGNITE-21707

IGNITE-21707: Update openapi generator

---

modules/index/src/test/java/org/apache/ignite/internal/index/IndexManagerTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/TableImpl.java

https://issues.apache.org/jira/browse/IGNITE-21576

IGNITE-21576 Unmute tests in IndexManagerTest

---

buildscripts/java-integration-test.gradle
buildscripts/java-junit5.gradle
modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java
modules/core/src/main/java/org/apache/ignite/internal/lang/IgniteExceptionMapperUtil.java
modules/core/src/main/java/org/apache/ignite/internal/thread/PublicApiThreading.java
modules/core/src/main/java/org/apache/ignite/internal/util/CompletableFutures.java
modules/index/src/test/java/org/apache/ignite/internal/index/IndexManagerTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/runner/src/testFixtures/java/org/apache/ignite/internal/test/WatchListenerInhibitor.java
modules/table/build.gradle
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/threading/ItKvRecordApiThreadingTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/AbstractTableView.java
modules/table/src/main/java/org/apache/ignite/internal/table/KeyValueBinaryViewImpl.java
modules/table/src/main/java/org/apache/ignite/internal/table/KeyValueViewImpl.java
modules/table/src/main/java/org/apache/ignite/internal/table/RecordBinaryViewImpl.java
modules/table/src/main/java/org/apache/ignite/internal/table/RecordViewImpl.java
modules/table/src/main/java/org/apache/ignite/internal/table/TableImpl.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/test/java/org/apache/ignite/internal/table/KeyValueBinaryViewOperationsTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/KeyValueViewOperationsTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/RecordBinaryViewOperationsTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/RecordViewOperationsTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java

https://issues.apache.org/jira/browse/IGNITE-21714

IGNITE-21714 Prevent threads from being hijacked in KV/Record view APIs

---

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImplTest.java

https://issues.apache.org/jira/browse/IGNITE-21728

IGNITE-21728 Wait for the cursors to close in ExecutionServiceImplTest

---

modules/core/src/main/java/org/apache/ignite/internal/thread/PublicApiThreading.java
modules/core/src/test/java/org/apache/ignite/internal/thread/PublicApiThreadingTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/threading/ItKvRecordApiThreadingTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/AbstractTableView.java
modules/table/src/main/java/org/apache/ignite/internal/table/AntiHijackAsyncCursor.java

https://issues.apache.org/jira/browse/IGNITE-21729

IGNITE-21729 Prevent threads from being hijacked via async cursors in KV/Record view APIs

---

modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/HashIndexTree.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/SortedIndexTree.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/IndexStorageFactory.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/PageMemoryIndexes.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorage.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/RenewablePartitionStorageState.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/VolatilePageMemoryMvPartitionStorage.java

* Extract creation of different type of Index Trees into the IndexStorageFactory class;
* Extract index management into the PageMemoryIndexes class.
https://issues.apache.org/jira/browse/IGNITE-21742
\- The pull request title is treated as the final commit message. The following pattern must be used: IGNITE-XXXX Change summary where XXXX - number of …

IGNITE-21742 Refactor creation and management of Page Memory Indexes

---

modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/ItInitializedClusterRestTest.java

https://issues.apache.org/jira/browse/IGNITE-21724

IGNITE-21724 Support "-ea" version suffix in ItInitializedClusterRestTest

---

modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/AbstractPageMemoryIndexStorage.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/ScanVersionsCursor.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java

https://issues.apache.org/jira/browse/IGNITE-21749

IGNITE-21749 Add assertions for destroyed/closed storages behavior

---

check-rules/spotbugs-excludes.xml

IGNITE-21752 improved excludes for generated rest client

---

modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/ActiveActorTest.java
modules/replicator/src/testFixtures/java/org/apache/ignite/internal/raft/client/AbstractTopologyAwareGroupServiceTest.java

https://issues.apache.org/jira/browse/IGNITE-21381

IGNITE-21381 ActiveActorTest#testChangeLeaderForce is flaky

---

check-rules/spotbugs-excludes.xml
modules/network/src/main/java/org/apache/ignite/internal/network/LazyStripedExecutors.java
modules/network/src/main/java/org/apache/ignite/internal/network/netty/ConnectionManager.java

https://issues.apache.org/jira/browse/IGNITE-21696

IGNITE-21696 Don't synchronize on AtomicReferenceArray

---

modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/core/AppendEntriesRequestProcessor.java
modules/raft/src/test/java/org/apache/ignite/raft/jraft/rpc/impl/core/AppendEntriesRequestProcessorTest.java
modules/raft/src/test/java/org/apache/ignite/raft/jraft/rpc/impl/core/BaseNodeRequestProcessorTest.java

https://issues.apache.org/jira/browse/IGNITE-21766

IGNITE-21766 Avoid a race while handling messages in jraft

---

check-rules/pmd-rules.xml
modules/cli/src/main/java/org/apache/ignite/internal/cli/core/flow/Flow.java
modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientBinaryTupleUtils.java
modules/client-handler/src/main/java/org/apache/ignite/client/handler/JdbcQueryCursorHandlerImpl.java
modules/configuration/src/test/java/org/apache/ignite/internal/configuration/tree/TraversableTreeNodeTest.java
modules/core/src/test/java/org/apache/ignite/internal/util/CollectionUtilsTest.java
modules/core/src/test/java/org/apache/ignite/internal/util/io/IgniteUnsafeDataInputOutputByteOrderTest.java
modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java
modules/file-transfer/src/test/java/org/apache/ignite/internal/network/file/FileTransferServiceImplTest.java
modules/index/src/test/java/org/apache/ignite/internal/index/IndexAvailabilityControllerTest.java
modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc/JdbcDatabaseMetadata.java
modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/BuiltInMarshalling.java
modules/network/src/test/java/org/apache/ignite/internal/network/netty/InboundDecoderTest.java
modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerWithArbitraryObjectsTest.java
modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/PersistentPageMemory.java
modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/store/AbstractFilePageStoreIoTest.java
modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/PlacementDriverTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/RexImpTable.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteSqlValidator.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rel/IgniteMergeJoin.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/trait/DistributionTrait.java
modules/storage-api/src/test/java/org/apache/ignite/internal/storage/DataStorageModulesTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java
modules/table/src/test/java/org/apache/ignite/internal/table/MutableRowTupleAdapterTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/RecordBinaryViewOperationsTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/RecordViewOperationsTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java

https://issues.apache.org/jira/browse/IGNITE-21652

IGNITE-21652 Extend codestyle checks made by PMD

---

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgStorageException.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/RocksDbClusterStateStorage.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/StorageException.java
modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/AbstractClusterStateStorageManagerTest.java
modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/AbstractClusterStateStorageTest.java
modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/RocksDbClusterStateStorageManagerTest.java
modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/RocksDbClusterStateStorageTest.java
modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/TestClusterStateStorageTest.java
modules/cluster-management/src/testFixtures/java/org/apache/ignite/internal/cluster/management/MockNode.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java

https://issues.apache.org/jira/browse/IGNITE-21811

IGNITE-21811 Cleanup in RocksDbClusterStateStorage

---

modules/raft-api/src/main/java/org/apache/ignite/internal/raft/configuration/RaftConfigurationSchema.java
modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java
modules/raft/src/integrationTest/java/org/apache/ignite/raft/server/ItJraftCounterServerTest.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/Loza.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/JRaftUtils.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/NodeImpl.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/disruptor/StripedDisruptor.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/option/NodeOptions.java
modules/raft/src/test/java/org/apache/ignite/disruptor/StripedDisruptorTest.java
modules/raft/src/test/java/org/apache/ignite/raft/jraft/core/FSMCallerTest.java
modules/raft/src/test/java/org/apache/ignite/raft/jraft/core/ReadOnlyServiceTest.java
modules/raft/src/test/java/org/apache/ignite/raft/jraft/storage/impl/LogManagerTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItRaftCommandLeftInLogUntilRestartTest.java

https://issues.apache.org/jira/browse/IGNITE-21798

IGNITE-21798 Add properties to configure number of RAFT threads

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/PartitionCommandListenerTest.java

https://issues.apache.org/jira/browse/IGNITE-21795

IGNITE-21795 Unconditionally update storage with proper raft index within PartitionListener

---

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/tree/BplusTree.java
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/IndexStorage.java
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/util/StorageUtils.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/impl/AbstractTestIndexStorage.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/AbstractPageMemoryIndexStorage.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/PageMemoryHashIndexStorage.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/meta/UpdateLastRowIdUuidToBuildInvokeClosure.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/PageMemorySortedIndexStorage.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/IndexStorageFactory.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/PageMemoryIndexes.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMetaStorage.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/AbstractRocksDbIndexStorage.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbHashIndexStorage.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbSortedIndexStorage.java

https://issues.apache.org/jira/browse/IGNITE-21819

IGNITE-21819 Clear nextRowIdToBuild on rebalance

---

modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java

IGNITE-21708 Fix CatalogManagerSelfTest::testPkAvailableIndexEvent flaky test.

---

modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/IgniteTestUtils.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TransactionInflights.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java

https://issues.apache.org/jira/browse/IGNITE-18617

IGNITE-18617 Clear rw tx context and cleanup ready futures on tx finish

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/TableScanNodeExecutionTest.java
modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxAbstractDistributedTestSingleNode.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItColocationTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItOperationRetryTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItTransactionRecoveryTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerRecoveryTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImplTest.java
modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java
modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/configuration/TransactionConfigurationSchema.java

https://issues.apache.org/jira/browse/IGNITE-21540

IGNITE-21540 Handle lock exception for transaction operations

---

modules/platforms/cpp/ignite/network/detail/macos/macos_async_worker_thread.cpp

https://issues.apache.org/jira/browse/IGNITE-21804

IGNITE-21804 Fix macos build of Ignite CPP client

---

modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/executor/IgnitePicocliCommands.java

https://issues.apache.org/jira/browse/IGNITE-21674
Add a workaround for https://github.com/jline/jline3/issues/956

IGNITE-21674 Fix subcommand completion in CLI

---

modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryClientHandshakeManager.java
modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryServerHandshakeManager.java

https://issues.apache.org/jira/browse/IGNITE-21834

IGNITE-21834 Add more details to assertions in recovery handhake managers

---

modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorage.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryMvTableStorageTest.java

https://issues.apache.org/jira/browse/IGNITE-21821

IGNITE-21821 Fix Error: Partition file page store is either not initialized or deleted

---

modules/core/src/main/java/org/apache/ignite/internal/table/criteria/QueryCriteriaAsyncCursor.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItCriteriaQueryTest.java

IGNITE-21681 QueryCriteriaAsyncCursor doesn't satisfy AsyncCursor contract.

---

modules/index/src/main/java/org/apache/ignite/internal/index/IndexManager.java

https://issues.apache.org/jira/browse/IGNITE-21845

IGNITE-21845 Destroy index out of LWM updater thread

---

check-rules/spotbugs-excludes.xml
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/engine/AbstractStorageEngineTest.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/HashIndex.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/Index.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbDataRegion.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbIndexes.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMetaStorage.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageEngine.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorage.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/SortedIndex.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/AbstractRocksDbIndexStorage.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbHashIndexStorage.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbSortedIndexStorage.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/instance/IndexColumnFamily.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/instance/SharedRocksDbInstance.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/engine/RocksDbStorageEngineTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/instance/SharedRocksDbInstanceTest.java

https://issues.apache.org/jira/browse/IGNITE-21760

IGNITE-21760 Remove destroyed RocksDB tables on recovery

---

docs/_docs/config/data-region.adoc
docs/_docs/storage/rocksdb.adoc
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbDataRegion.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/configuration/schema/RocksDbDataRegionConfigurationSchema.java

https://issues.apache.org/jira/browse/IGNITE-21851

IGNITE-21851 Remove RocksDB cache type support

---

modules/index/src/integrationTest/java/org/apache/ignite/internal/index/ItIndexAndIndexStorageDestructionTest.java

https://issues.apache.org/jira/browse/IGNITE-21855

IGNITE-21855 Fix ItIndexAndIndexStorageDestructionTest

---

modules/table/src/integrationTest/java/org/apache/ignite/internal/threading/ItKvRecordApiThreadingTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/threading/ItTablesApiThreadingTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/threading/PublicApiThreadingTests.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/AntiHijackIgniteTables.java

https://issues.apache.org/jira/browse/IGNITE-21849

IGNITE-21849 Prevent thread hijacking via IgniteTables

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateTableCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/TablePrimaryKey.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/TableSortedPrimaryKey.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/CreateTableCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/TablePrimaryKeyTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlApiBaseTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCreateTableDdlTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/ddl/DdlSqlToCommandConverter.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/schema/SqlSchemaManagerImplTest.java

IGNITE-21673 Do not allow duplicate column names in unique column list of a primary key constraint.

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogVersionAwareValidationException.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlApiBaseTest.java

IGNITE-21776 Sql. Concurrent "create table" call with same name need to wait already processed result

---

modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItComputeBaseTest.java
modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItComputeTestEmbedded.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/executor/ComputeExecutorImpl.java

https://issues.apache.org/jira/browse/IGNITE-21878

IGNITE-21878 Allow compute threads to execute storage operations

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItOrToUnionRuleTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSecondaryIndexTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PlannerPhase.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rule/logical/LogicalOrToUnionRule.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/RexUtils.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/CorrelatedSubqueryPlannerTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/IndexSearchBoundsPlannerTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/PlannerTest.java

Benchmark                          (queryId)  Mode  Cnt   Score   Error  Units
TpchPrepareBenchmark.prepareQuery         19  avgt   10  29.258 ± 6.672  ms/op

IGNITE-21287 Sql. LogicalOrToUnionRule may hang

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CatalogUtils.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/RenameTableCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/RenameIndexEntry.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/serialization/CatalogEntrySerializerProvider.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/serialization/MarshallableEntryType.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/RenameTableCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/storage/CatalogEntrySerializationTest.java

https://issues.apache.org/jira/browse/IGNITE-21862

IGNITE-21862 Rename PK index when renaming a table

---

modules/api/src/main/java/org/apache/ignite/compute/IgniteCompute.java
modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItComputeTestEmbedded.java

https://issues.apache.org/jira/browse/IGNITE-21818

IGNITE-21818 Support broadcasting null-returning jobs

---

modules/storage-api/src/test/java/org/apache/ignite/internal/storage/index/TestHashIndexStorageTest.java
modules/storage-api/src/test/java/org/apache/ignite/internal/storage/index/TestSortedIndexStorageTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractIndexStorageTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractSortedIndexStorageTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/impl/TestIndexRow.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbSortedIndexStorage.java

* Fix incorrect offset in assertion
* Use non-zero partition ID in tests
https://issues.apache.org/jira/browse/IGNITE-21885 …

IGNITE-21885 Fix AssertionError in RocksDbSortedIndexStorage#scan

---

modules/platforms/cpp/ignite/client/compute/compute.cpp
modules/platforms/cpp/ignite/client/compute/compute.h
modules/platforms/cpp/ignite/client/compute/job_execution.h
modules/platforms/cpp/ignite/client/compute/job_execution_options.h
modules/platforms/cpp/ignite/client/detail/compute/compute_impl.cpp
modules/platforms/cpp/ignite/client/detail/compute/compute_impl.h
modules/platforms/cpp/ignite/client/detail/compute/job_execution_impl.h
modules/platforms/cpp/tests/client-test/compute_test.cpp
modules/platforms/cpp/tests/client-test/schema_synchronization_test.cpp
modules/platforms/cpp/tests/test-common/basic_auth_test_suite.h

https://issues.apache.org/jira/browse/IGNITE-21335

IGNITE-21335 C++ 3.0: Implement job_execution_options

---

modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItComputeTestEmbedded.java
modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItExecutionsCleanerTest.java
modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/threading/ItComputeApiThreadingTest.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/AntiHijackIgniteCompute.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/AntiHijackJobExecution.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/IgniteComputeImpl.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/AntiHijackIgniteTables.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/AntiHijackTable.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/AntiHijackIgniteTransactions.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/AntiHijackTransaction.java

https://issues.apache.org/jira/browse/IGNITE-21876

IGNITE-21876 Prevent thread hijacking via IgniteCompute

---

modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/threading/ItSqlApiThreadingTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/api/AntiHijackAsyncResultSet.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/api/AntiHijackIgniteSql.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/api/IgniteSqlImpl.java

https://issues.apache.org/jira/browse/IGNITE-21869

IGNITE-21869 Prevent thread hijacking via IgniteSql

---

modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/flush/RocksDbFlusher.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbSharedStorage.java

https://issues.apache.org/jira/browse/IGNITE-21896

IGNITE-21896 Close RocksDB flush listener on stop

---

modules/core/src/main/java/org/apache/ignite/internal/tostring/IgniteToStringExclude.java
modules/core/src/main/java/org/apache/ignite/internal/tostring/IgniteToStringInclude.java
modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/messages/MessageImplGenerator.java
modules/network/src/test/java/org/apache/ignite/internal/network/AllTypesMessageTest.java
modules/network/src/testFixtures/java/org/apache/ignite/internal/network/messages/AllTypesMessage.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replication/request/SingleRowReplicaRequest.java

https://issues.apache.org/jira/browse/IGNITE-17591

IGNITE-17591 Refactor toString generation for network messages

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlUsesKeyValueGetTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlUsesKeyValuePutTest.java

Renames:  
- ItKeyValueGetTest to ItSqlUsesKeyValueGetTest 
- ItKeyValuePutTest to ItSqlUsesKeyValuePutTest
https://issues.apache.org/jira/browse/IGNITE-21794
--- …

IGNITE-21794: Sql. Rename ItKeyValuePutTest and ItKeyValueGetTest

---

modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcErrorsSelfTest.java
modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcStatementSelfTest.java

IGNITE-21879 Sql. Jdbc IdbcStatementSelfTest.testOpenCursorsPureQuery  is flaky

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/InsertBenchmark.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlQueryProcessor.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/ParserServiceImpl.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/benchmarks/TpchPrepareBenchmark.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImplTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestBuilders.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/PlannerTimeoutTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/prepare/PrepareServiceImplTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/ParserServiceImplTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/metrics/PlanningCacheMetricsTest.java
modules/workers/src/main/java/org/apache/ignite/internal/worker/ThreadAssertions.java

https://issues.apache.org/jira/browse/IGNITE-21887
Before
|Benchmark|(clusterSize)|(fsync)|Mode|Cnt|Score|Error|Units|
|-----|-----|-----|-----|-----|-----|-----|-----|
|SelectBenchmark.sqlGet|1|false|avgt|20|55.288|± 3.919|us/op|
|InsertBenchmark.sqlInsert|1|false|avgt|20|0.437|± 0.018|ms/op|
After
|Benchmark|(clusterSize)|(fsync)|Mode|Cnt|Score|Error|Units|
|-----|-----|-----|-----|-----|-----|-----|-----|
|SelectBenchmark.sqlGet|1|false|avgt|20|10.265|± 0.137|us/op|
|InsertBenchmark.sqlInsert|1|false|avgt|20|0.367|± 0.017|ms/op|
The benchmarks were run on personal laptop(12th Gen Intel(R) Core(TM) i7-1280P, 32 GB RAM).
-----------------------------------
we ask both …

IGNITE-21887 Sql. Reuse caller thread if query already prepared

---

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rel/agg/IgniteSortAggregateBase.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/AbstractAggregatePlannerTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/AbstractPlannerTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/AggregatePlannerTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/ColocatedHashAggregatePlannerTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/ColocatedSortAggregatePlannerTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/MapReduceHashAggregatePlannerTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/MapReduceSortAggregatePlannerTest.java

https://issues.apache.org/jira/browse/IGNITE-21897

IGNITE-21897 Sql. Invalid collation passthrough for sorted aggregates

---

modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/UnitStatus.java
modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/metastore/ClusterEventCallbackImpl.java
modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/metastore/DeploymentUnitFailover.java
modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/metastore/DeploymentUnitStore.java
modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/metastore/DeploymentUnitStoreImpl.java
modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/metastore/status/SerializeUtils.java
modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/metastore/status/UnitClusterStatus.java
modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/metastore/status/UnitNodeStatus.java
modules/code-deployment/src/test/java/org/apache/ignite/deployment/UnitStatusesSerializerTest.java
modules/code-deployment/src/test/java/org/apache/ignite/deployment/metastore/DeploymentUnitStoreImplTest.java
modules/code-deployment/src/test/java/org/apache/ignite/internal/deployunit/DeploymentManagerImplTest.java

https://issues.apache.org/jira/browse/IGNITE-21757

IGNITE-21757 Fix redeploy

---

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractExecutionTest.java

IGNITE-21895 Assertion rarely raised on LimitExecutionTest.testLimit

---

modules/client/src/test/java/org/apache/ignite/client/TestServer.java
modules/eventlog/build.gradle
modules/eventlog/src/integrationTest/java/org/apache/ignite/internal/eventlog/ItEventLogConfigurationValidationTest.java
modules/eventlog/src/integrationTest/java/org/apache/ignite/internal/eventlog/impl/InMemoryCollectionSink.java
modules/eventlog/src/integrationTest/java/org/apache/ignite/internal/eventlog/impl/InMemoryCollectionSinkConfigurationSchema.java
modules/eventlog/src/integrationTest/java/org/apache/ignite/internal/eventlog/impl/ItEventLogConfigurationTest.java
modules/eventlog/src/integrationTest/java/org/apache/ignite/internal/eventlog/impl/TestEventTypes.java
modules/eventlog/src/integrationTest/java/org/apache/ignite/internal/eventlog/impl/TestSinkFactory.java
modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/api/IgniteEvents.java
modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/config/EventLogConfigurationModule.java
modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/config/schema/ChannelConfigurationSchema.java
modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/config/schema/EventTypeValidatorImpl.java
modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/config/schema/ValidEventType.java
modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/impl/ChannelFactory.java
modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/impl/ConfigurationBasedChannelRegistry.java
modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/impl/ConfigurationBasedSinkRegistry.java
modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/impl/EventChannelImpl.java
modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/impl/EventLogImpl.java
modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/impl/SinkFactory.java
modules/eventlog/src/test/java/org/apache/ignite/internal/eventlog/impl/ConfigurationBasedChannelRegistryTest.java
modules/eventlog/src/test/java/org/apache/ignite/internal/eventlog/impl/ConfigurationBasedSinkRegistryTest.java
modules/eventlog/src/test/java/org/apache/ignite/internal/eventlog/impl/LogSinkTest.java

https://issues.apache.org/jira/browse/IGNITE-21905

IGNITE-21905 Add integration test for EventLog

---

modules/code-deployment/build.gradle
modules/code-deployment/src/test/java/org/apache/ignite/deployment/metastore/DeploymentUnitStoreImplTest.java
modules/failure-handler/build.gradle
modules/failure-handler/src/testFixtures/java/org/apache/ignite/internal/failure/NoOpFailureProcessor.java
modules/failure-handler/src/testFixtures/java/org/apache/ignite/internal/failure/NoopFailureProcessor.java
modules/metastorage/build.gradle
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageManagerImplTest.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesRocksDbTest.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageSafeTimePropagationRocksDbTest.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageServicePersistenceTest.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageWatchTest.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/WatchProcessor.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/impl/MetaStorageRocksDbRangeTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/RocksDbCompactionKeyValueStorageTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/RocksDbKeyValueStorageTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/WatchProcessorTest.java
modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java
modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/TestRocksDbKeyValueStorage.java
modules/runner/build.gradle
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/table/build.gradle
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java

https://issues.apache.org/jira/browse/IGNITE-21307

IGNITE-21307 Add using a failure handler during watch processing

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItDataSchemaSyncTest.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbStorage.java
modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/AbstractTxStateStorageTest.java
modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/test/TestTxStateStorage.java

https://issues.apache.org/jira/browse/IGNITE-22002

IGNITE-22002 Substitute assertion with explicit check for PrimaryReplicaChangeCommand

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSetOpTest.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadWriteTransactionImpl.java

https://issues.apache.org/jira/browse/IGNITE-22008

IGNITE-22008 Fix double-checked locking in ReadWriteTransactionImpl

---

modules/sql-engine/src/integrationTest/sql/aggregate/group/test_group_by_not_in_select.test

IGNITE-21920 Cover SQL E051-04 (Basic query specification, GROUP BY can contain columns not in <select list>) feature by tests

---

modules/platforms/dotnet/Apache.Ignite.Tests/Table/SchemaSynchronizationTest.cs
modules/runner/src/integrationTest/java/org/apache/ignite/internal/schemasync/ItSchemaSyncAndImplicitTransactionsTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/schemasync/ItSchemaSyncSingleNodeTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/AbstractTableView.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/IncompatibleSchemaException.java

https://issues.apache.org/jira/browse/IGNITE-20416

IGNITE-20416 Retry when schema change is detected during implicit transaction

---

modules/runner/src/testFixtures/java/org/apache/ignite/internal/table/NodeUtils.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/TransactionStateResolver.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/VolatileTxStateMetaStorage.java

https://issues.apache.org/jira/browse/IGNITE-22027

IGNITE-22027 Fix ItPrimaryReplicaChoiceTest#testPrimaryChangeLongHandling

---

modules/network/src/main/java/org/apache/ignite/internal/network/NettyWorkersRegistrar.java
modules/replicator/build.gradle
modules/replicator/src/integrationTest/java/org/apache/ignite/internal/replicator/ItPlacementDriverReplicaSideTest.java
modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java
modules/replicator/src/test/java/org/apache/ignite/internal/replicator/ReplicaManagerTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/table/build.gradle
modules/table/src/integrationTest/java/org/apache/ignite/distributed/ReplicaUnavailableTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java
modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java
modules/workers/src/main/java/org/apache/ignite/internal/worker/CriticalWorkerWatchdog.java

https://issues.apache.org/jira/browse/IGNITE-22038

IGNITE-22038 Make idle safe time sending more robust

---

docs/_docs/sql-reference/ddl.adoc
modules/api/src/main/java/org/apache/ignite/catalog/IndexType.java
modules/catalog-dsl/src/test/java/org/apache/ignite/internal/catalog/sql/CreateFromAnnotationsTest.java
modules/catalog-dsl/src/test/java/org/apache/ignite/internal/catalog/sql/CreateFromDefinitionTest.java
modules/catalog-dsl/src/test/java/org/apache/ignite/internal/catalog/sql/CreateTableTest.java
modules/catalog-dsl/src/test/java/org/apache/ignite/internal/catalog/sql/QueryPartTest.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/help/IgniteSqlCommand.java
modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/ItPrimaryReplicaChoiceTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/SqlPartitionPruningBenchmark.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTableScanTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItIndexesSystemViewTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/datatypes/tests/BaseIndexDataTypeTest.java
modules/sql-engine/src/main/codegen/config.fmpp
modules/sql-engine/src/main/codegen/includes/parserImpls.ftl
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/ddl/DdlSqlToCommandConverter.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlCreateIndex.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlIndexType.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/SqlDdlParserTest.java

https://issues.apache.org/jira/browse/IGNITE-21976

IGNITE-21976 Sql. Amend TREE keyword to SORTED for CREATE INDEX syntax

---

modules/client-handler/src/testFixtures/java/org/apache/ignite/client/handler/FakePlacementDriver.java
modules/index/src/test/java/org/apache/ignite/internal/index/TestPlacementDriver.java
modules/placement-driver-api/src/main/java/org/apache/ignite/internal/placementdriver/PlacementDriver.java
modules/placement-driver-api/src/testFixtures/java/org/apache/ignite/internal/placementdriver/TestPlacementDriver.java
modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/LeaseTracker.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/TableScanNodeExecutionTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItColocationTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/wrappers/DelegatingPlacementDriver.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerRecoveryTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/wrappers/ExecutorInclinedPlacementDriverTest.java
modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java
modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TransactionInflights.java
modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerTest.java

https://issues.apache.org/jira/browse/IGNITE-22033

IGNITE-22033 Replace PlacementDriver#currentLease with #getPrimaryReplica in ReadWriteTxContext#waitReadyToFinish

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java

https://issues.apache.org/jira/browse/IGNITE-22042

IGNITE-22042 Do not enlist operations in a FINISHING transaction

---

modules/platforms/cpp/tests/client-test/basic_authenticator_test.cpp

https://issues.apache.org/jira/browse/IGNITE-22052

IGNITE-22052 Disable flaky basic_authenticator_test

---

modules/platforms/cpp/tests/client-test/transactions_test.cpp

https://issues.apache.org/jira/browse/IGNITE-22057

IGNITE-22027 Disable destruction_does_not_update_data

---

modules/sql-engine/src/integrationTest/sql/join/test_not_distinct_from.test

IGNITE-22053 Sql. Logic test without ordering compares with ordered results

---

modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/InlineUtils.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/io/HashIndexTreeIo.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/io/SortedIndexTreeIo.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/InlineUtilsTest.java

https://issues.apache.org/jira/browse/IGNITE-22041

IGNITE-22041 Correct inline size calculation for indexes

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItAlterTableAlterColumnTest.java

https://issues.apache.org/jira/browse/IGNITE-21996
The problem is not reproduced, we will simply add integration tests to cover the described case.

IGNITE-21996 Improve test coverage for ALTER COLUMN command.

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItMetadataTest.java
modules/sql-engine/src/integrationTest/sql/basic_queries/rename_columns_in _from.test
modules/sql-engine/src/integrationTest/sql/basic_queries/rename_columns_in_from.test
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/JoinCommutePlannerTest.java

https://issues.apache.org/jira/browse/IGNITE-21923 

IGNITE-21923: Cover SQL E051-09(Basic query specification, Rename columns in the FROM clause) feature by tests

---

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/mapping/MappingServiceImpl.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/mapping/MappingServiceImplTest.java

https://issues.apache.org/jira/browse/IGNITE-22083

IGNITE-22083 Invalidate fragment mapping cache when logical topology changes

---

modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/completer/DynamicCompleterRegistry.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/core/repl/completer/DynamicCompleterRegistryTest.java

Now you can define --option for multiple commands, and they won't be conflicting.
https://issues.apache.org/jira/browse/IGNITE-19949

IGNITE-19949 Fix dynamic completer for same options

---

modules/sql-engine/src/integrationTest/sql/set/test_except_all.test

https://issues.apache.org/jira/browse/IGNITE-21940

IGNITE-21940 Sql. Cover SQL F304(EXCEPT ALL table operator) feature by tests

---

modules/sql-engine/src/integrationTest/sql/set/test_intersect.test

https://issues.apache.org/jira/browse/IGNITE-21939

IGNITE-21939 Sql. Cover SQL F302-02(INTERSECT [ALL] table operator) feature by tests.

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java

https://issues.apache.org/jira/browse/IGNITE-22024

IGNITE-22024 Fixed ItSqlClientSynchronousApiTest#runtimeErrorInDmlCausesTransactionToFail

---

modules/sql-engine/src/integrationTest/sql/join/test_nested_outer_join.test

IGNITE-21937 Sql. Cover SQL F041-05 feature by tests

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/DefaultValue.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogTableColumnDescriptor.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/storage/CatalogEntrySerializationTest.java
modules/core/src/main/java/org/apache/ignite/internal/util/io/IgniteDataInput.java
modules/core/src/main/java/org/apache/ignite/internal/util/io/IgniteDataOutput.java
modules/core/src/main/java/org/apache/ignite/internal/util/io/IgniteUnsafeDataInput.java
modules/core/src/main/java/org/apache/ignite/internal/util/io/IgniteUnsafeDataOutput.java
modules/core/src/test/java/org/apache/ignite/internal/util/io/IgniteUnsafeDataInputOutputByteOrderTest.java

Removes serialization from `DefaultValue`.
https://issues.apache.org/jira/browse/IGNITE-21435
---
- [Apache Ignite Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Java+C …

IGNITE-21435: Sql. Catalog DefaultValue should not depend on Serializable.

---

modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientPrimaryReplicaTracker.java
modules/index/src/main/java/org/apache/ignite/internal/index/IndexManager.java
modules/low-watermark/src/main/java/org/apache/ignite/internal/lowwatermark/LowWatermark.java
modules/low-watermark/src/main/java/org/apache/ignite/internal/lowwatermark/LowWatermarkImpl.java
modules/low-watermark/src/main/java/org/apache/ignite/internal/lowwatermark/event/ChangeLowWatermarkEventParameters.java
modules/low-watermark/src/main/java/org/apache/ignite/internal/lowwatermark/event/LowWatermarkEvent.java
modules/low-watermark/src/main/java/org/apache/ignite/internal/lowwatermark/event/LowWatermarkEventParameters.java
modules/low-watermark/src/test/java/org/apache/ignite/internal/lowwatermark/LowWatermarkImplTest.java
modules/low-watermark/src/testFixtures/java/org/apache/ignite/internal/lowwatermark/TestLowWatermark.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/gc/MvGc.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/FullStateTransferIndexChooser.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/gc/MvGcTest.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java
modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerTest.java

https://issues.apache.org/jira/browse/IGNITE-22075

IGNITE-22075 GC doesn't wait for RO transactions

---

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PlannerHelper.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PlannerPhase.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/CorrelatedSubqueryPlannerTest.java

https://issues.apache.org/jira/browse/IGNITE-22093
---

IGNITE-22093: Sql. Rename PlannerPhase::HEP_DECORRELATE

---

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/ClusterStateStorage.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListener.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/RaftStorageManager.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/RocksDbClusterStateStorage.java
modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/AbstractClusterStateStorageTest.java
modules/cluster-management/src/testFixtures/java/org/apache/ignite/internal/cluster/management/raft/TestClusterStateStorage.java

https://issues.apache.org/jira/browse/IGNITE-22105

IGNITE-22105 Add busy lock to RocksDbClusterStateStorage

---

modules/network/src/main/java/org/apache/ignite/internal/network/netty/NettyServer.java

https://issues.apache.org/jira/browse/IGNITE-22116

IGNITE-22116 Include underlying exception when reporting occupied port issue

---

modules/sql-engine/src/integrationTest/sql/join/inner/test_table_from_outer_join_used_in_inner.test

IGNITE-21938 Sql. Cover SQL F041-07 feature by tests

---

modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageEngine.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageProfile.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/configuration/schema/RocksDbProfileConfigurationSchema.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/instance/SharedRocksDbInstanceCreator.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/instance/SharedRocksDbInstanceTest.java

https://issues.apache.org/jira/browse/IGNITE-19762

IGNITE-19762 Remove data region remnants from RocksDb storage

---

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java

https://issues.apache.org/jira/browse/IGNITE-18275

IGNITE-18275 Remove obsolete TODOs

---

modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItTxResourcesVacuumTest.java

https://issues.apache.org/jira/browse/IGNITE-22147

IGNITE-22147 Disabled ItTxResourcesVacuumTest.testRecoveryAfterPersistentStateVacuumized

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItTablesApiTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDmlTest.java
modules/sql-engine/src/integrationTest/sql/aggregate/aggregates/test_sum.test
modules/sql-engine/src/integrationTest/sql/contstraint/test_not_null_constraint.test
modules/sql-engine/src/integrationTest/sql/filter/test_zonemap.test_ignore
modules/sql-engine/src/integrationTest/sql/function/generic/test_large_in.test_ignore
modules/sql-engine/src/integrationTest/sql/join/natural/natural_join.test
modules/sql-engine/src/integrationTest/sql/join/test_cross_product_parallelism.test_ignore
modules/sql-engine/src/integrationTest/sql/order/test_order_same_value.test
modules/sql-engine/src/integrationTest/sql/types/decimal/decimal_arithmetic.test
modules/sql-engine/src/integrationTest/sql/types/decimal/decimal_decimal_overflow_cast.test
modules/sql-engine/src/integrationTest/sql/types/decimal/decimal_overflow.test
modules/sql-engine/src/integrationTest/sql/types/decimal/decimal_overflow_table.test
modules/sql-engine/src/integrationTest/sql/types/decimal/test_decimal.test
modules/sql-engine/src/integrationTest/sql/types/decimal/test_decimal_cast.test
modules/sql-engine/src/integrationTest/sql/types/string/test_scan_big_varchar.test

IGNITE-22159: unmute tests

---

modules/client-handler/src/test/java/org/apache/ignite/client/handler/requests/table/ClientHandlerTupleTests.java
modules/schema/src/main/java/org/apache/ignite/internal/schema/registry/UpgradingRowAdapter.java
modules/schema/src/main/java/org/apache/ignite/internal/schema/row/Row.java
modules/schema/src/main/java/org/apache/ignite/internal/schema/row/RowImpl.java
modules/schema/src/test/java/org/apache/ignite/internal/schema/registry/UpgradingRowAdapterTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/MutableRowTupleAdapter.java
modules/table/src/main/java/org/apache/ignite/internal/table/RecordViewImpl.java

https://issues.apache.org/jira/browse/IGNITE-22156

IGNITE-22156 Replace inheritance with delegation for UpgradingRowAdapter class.

---

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java

IGNITE-22175: Improve handling for RocksDb resources on RocksDbKeyValueStorage

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java

IGNITE-19091 Sql. Fix ItIgniteNodeRestartTest::testQueryCorrectnessAfterNodeRestart

---

modules/sql-engine/src/integrationTest/sql/order/test_nested_order_by.test

IGNITE-21945 Sql. Cover SQL F855(Nested <order by clause> in <query expression>)

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/sqllogic/ItSqlLogicTest.java
modules/sql-engine/src/integrationTest/sql/basic_queries/test_simple_table.test

IGNITE-21977 Sql. Extend test coverage for SQL feature F661(Simple tables)

---

modules/cluster-management/build.gradle
modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/ItClusterManagerTest.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/ValidationManager.java
modules/cluster-management/src/testFixtures/java/org/apache/ignite/internal/cluster/management/BaseItClusterManagementTest.java
modules/cluster-management/src/testFixtures/java/org/apache/ignite/internal/cluster/management/MockNode.java

https://issues.apache.org/jira/browse/IGNITE-22190

IGNITE-22190 Refactor ItClusterManagerTest test infrastructure

---

modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/snapshot/RocksSnapshotManager.java

IGNITE-22176: Started injecting the RocksDbEnv from the parent Db in the RocksSnapshotManager

---

modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/causalitydatanodes/DistributionZoneCausalityDataNodesTest.java
modules/raft/src/test/java/org/apache/ignite/disruptor/StripedDisruptorTest.java

https://issues.apache.org/jira/browse/IGNITE-22185

IGNITE-22185 Mute test from DistributionZoneCausalityDataNodesTest

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/PlatformBenchmarkNodeRunner.java

Removes `portRange` property that no longer exists.
https://issues.apache.org/jira/browse/IGNITE-22194
--- …

IGNITE-22194 Remove portRange from PlatformBenchmarkNodeRunner

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AlterTableAddColumnCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AlterTableAlterColumnCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CatalogUtils.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateTableCommand.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AlterTableAddColumnCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AlterTableAlterColumnCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/CreateTableCommandValidationTest.java
modules/schema/src/main/java/org/apache/ignite/internal/schema/DefaultValueGenerator.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItAlterTableAlterColumnTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCreateTableDdlTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/SqlDdlParserTest.java

https://issues.apache.org/jira/browse/IGNITE-22161

IGNITE-22161 Sql. Fix infinity loop after query validation failure

---

modules/sql-engine/src/integrationTest/sql/set/test_basic_union.test
modules/sql-engine/src/integrationTest/sql/set/test_set_distinct.test

https://issues.apache.org/jira/browse/IGNITE-21952
---

IGNITE-21952: Cover SQL T551(Optional key words for default syntax) feature by test

---

modules/index/src/main/java/org/apache/ignite/internal/index/IndexBuildController.java

https://issues.apache.org/jira/browse/IGNITE-22191

IGNITE-22191 Fixed case null MvPartitionStorage in IndexBuildController

---

modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItTxResourcesVacuumTest.java

https://issues.apache.org/jira/browse/IGNITE-22206

IGNITE-22206 Unmute disabled ItTxResourcesVacuumTest#testRecoveryAfterPersistentStateVacuumized

---

docs/_docs/general-tips.adoc
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbDataStorageModule.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/configuration/schema/RocksDbStorageEngineExtensionConfigurationSchema.java

https://issues.apache.org/jira/browse/IGNITE-22220

IGNITE-22220 Rename `RocksDbStorageEngineExtensionConfigurationSchema#rocksDb` field

---

modules/sql-engine/src/integrationTest/sql/subquery/exists/test_enhanced_exists_predicate.test

IGNITE-21951 Sql. Cover SQL T501(Enhanced EXISTS predicate)

---

modules/sql-engine/src/integrationTest/sql/types/string/test_unicode_escapes_in_literals.test_ignored

https://issues.apache.org/jira/browse/IGNITE-21942

IGNITE-21942 Cover SQL F393(Unicode escapes in literals) feature by tests

---

modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/FSMCallerImpl.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItTxResourcesVacuumTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxCleanupRequestSender.java

https://issues.apache.org/jira/browse/IGNITE-22245

IGNITE-22245 Force switch write intents

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItKvKeyColumnPositionTest.java

Removes a couple of redundant test cases.
https://issues.apache.org/jira/browse/IGNITE-22256
---
- [Apache Ignite Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Java+Co …

IGNITE-22256: ItKvKeyColumnPositionTest contains tests that are no longer needed.

---

modules/core/src/testFixtures/resources/log4j2-test.xml
modules/eventlog/build.gradle
modules/eventlog/src/integrationTest/java/org/apache/ignite/internal/eventlog/ItEventLogTest.java
modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/api/IgniteEventType.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgnitionImpl.java

https://issues.apache.org/jira/browse/IGNITE-22254

IGNITE-22254 Cluster initialization fails when event log is configured

---

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/datastructure/DataStructure.java
modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/freelist/PagesList.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/gc/GcStorageHandler.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/gc/MvGc.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/gc/AbstractGcUpdateHandlerTest.java

https://issues.apache.org/jira/browse/IGNITE-22050

IGNITE-22050 Fix incorrect partId in reused pages

---

modules/sql-engine/src/integrationTest/sql/aggregate/aggregates/test_covar.test_ignore
modules/sql-engine/src/integrationTest/sql/aggregate/aggregates/test_regression.test_ignore
modules/sql-engine/src/integrationTest/sql/aggregate/aggregates/test_stddev.test_ignore
modules/sql-engine/src/integrationTest/sql/function/numeric/test_pg_math.test

IGNITE-21984 Sql. Extend test coverage for SQL T621(Enhanced numeric functions)

---

modules/api/src/main/java/org/apache/ignite/lang/ErrorGroups.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/ItPartitionStatesCommandTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/ItResetPartitionsCommandTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/ItResetPartitionsReplCommandTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/ItResetPartitionsTest.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/PartitionStatesCallInput.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/reset/ResetPartitionsCall.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/reset/ResetPartitionsCallInput.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/Options.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/RecoveryCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/reset/ResetPartitionsCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/reset/ResetPartitionsMixin.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/reset/ResetPartitionsReplCommand.java
modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/exception/DistributionZoneNotFoundException.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/recovery/DisasterRecoveryApi.java
modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/recovery/ItDisasterRecoveryControllerTest.java

https://issues.apache.org/jira/browse/IGNITE-22166

IGNITE-22166 CLI for disaster recovery: reset-lost-partitions

---

modules/sql-engine/src/integrationTest/sql/order/test_offset.test

Extracts test for `OFFSET` clause into a separate file.
https://issues.apache.org/jira/browse/IGNITE-21980
--- …

IGNITE-21980: Extend test coverage for SQL F861(Top-level <result offset clause> in <query expression>)

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlApiBaseTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlAsynchronousApiTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlClientAsynchronousApiTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlClientSynchronousApiTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlSynchronousApiTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/threading/ItSqlApiThreadingTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/api/IgniteSqlImpl.java

https://issues.apache.org/jira/browse/IGNITE-21872

IGNITE-21872 Sql. Implement IgniteSql#executeBatchAsync() accepting Statement

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlOperatorsTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/prepare/TypeCoercionTest.java

IGNITE-18559 Sql. Investigate the least restrictive type between VARCHAR and DECIMAL

---

modules/eventlog/src/integrationTest/java/org/apache/ignite/internal/eventlog/ItEventLogConfigurationValidationTest.java
modules/eventlog/src/integrationTest/java/org/apache/ignite/internal/eventlog/ItEventLogTest.java
modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/api/IgniteEventType.java
modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/api/IgniteEvents.java
modules/eventlog/src/test/java/org/apache/ignite/internal/eventlog/event/IgniteEventsTest.java
modules/eventlog/src/test/java/org/apache/ignite/internal/eventlog/impl/ConfigurationBasedChannelRegistryTest.java
modules/eventlog/src/test/java/org/apache/ignite/internal/eventlog/impl/EventLogTest.java
modules/eventlog/src/test/java/org/apache/ignite/internal/eventlog/impl/LogSinkTest.java
modules/eventlog/src/test/java/org/apache/ignite/internal/eventlog/ser/JacksonBasedJsonSerializerTest.java
modules/security/src/main/java/org/apache/ignite/internal/security/authentication/AuthenticationManagerImpl.java

Now the names are more consistent and follows same pattern.
https://issues.apache.org/jira/browse/IGNITE-22300

IGNITE-22300 Adjust EventType

---

modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogTableTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCreateTableDdlTest.java

Adds few test cases for functional default mismatch error.
https://issues.apache.org/jira/browse/IGNITE-22148
--- …

IGNITE-22148: BinaryTupleFormatException for UUID

---

modules/sql-engine/src/integrationTest/sql/function/blob/test_position.test
modules/sql-engine/src/integrationTest/sql/types/blob/test_blob.test
modules/sql-engine/src/integrationTest/sql/types/blob/test_blob_cast.test

IGNITE-21982 Sql. Extend test coverage for SQL T021(BINARY and VARBINARY data types).

---

modules/rest-api/src/main/java/org/apache/ignite/internal/rest/ResourceHolder.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/ResourceCleaner.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/authentication/IgniteAuthenticationProvider.java

https://issues.apache.org/jira/browse/IGNITE-22333

IGNITE-22333 Fix memory leak

---

modules/sql-engine/src/integrationTest/sql/order/test_offset_in_subqueries.test

https://issues.apache.org/jira/browse/IGNITE-2198
---

IGNITE-21981: Extend test coverage for SQL F862(<result offset clause in subqueries)

---

modules/rest-api/src/main/java/org/apache/ignite/internal/rest/ResourceHolder.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/authentication/ClusterStateHttpServerFilter.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/authentication/IgniteSecurityFilter.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/cluster/ClusterManagementController.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/cluster/TopologyController.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/compute/ComputeController.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/configuration/AbstractConfigurationController.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/deployment/DeploymentManagementController.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/metrics/NodeMetricController.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/node/NodeManagementController.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/recovery/DisasterRecoveryController.java

https://issues.apache.org/jira/browse/IGNITE-22342

IGNITE-22342 Improve resource cleaning

---

modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/FSMCallerImpl.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/NodeImpl.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/ReadOnlyServiceImpl.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/disruptor/DisruptorBuilder.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/disruptor/DisruptorEventType.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/disruptor/NodeIdAware.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/disruptor/StripedDisruptor.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/impl/LogManagerImpl.java
modules/raft/src/test/java/org/apache/ignite/disruptor/StripedDisruptorTest.java

https://issues.apache.org/jira/browse/IGNITE-15568

IGNITE-15568 Striped Disruptor doesn't work with JRaft event handlers properly

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItFunctionsTest.java
modules/sql-engine/src/integrationTest/sql/function/timestamp/current_time.test

IGNITE-21970 Sql. Extend test coverage for SQL F051-06, F051-07, F051-08 (Basic date and time)

---

modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvPartitionStorage.java
modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java
modules/table/src/testFixtures/java/org/apache/ignite/internal/table/TxAbstractTest.java
modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/test/TestTxStateStorage.java

https://issues.apache.org/jira/browse/IGNITE-21418

IGNITE-21418 Add more logs to debug this issue

---

packaging/cli/build.gradle

https://issues.apache.org/jira/browse/IGNITE-22339

IGNITE-22339 Fix cli startup script for deb/rpm

---

modules/network/src/main/java/org/apache/ignite/internal/network/netty/OutboundEncoder.java

https://issues.apache.org/jira/browse/IGNITE-22371

IGNITE-22371 Increase Netty IO buffer size

---

modules/raft/src/test/java/org/apache/ignite/disruptor/StripedDisruptorTest.java

https://issues.apache.org/jira/browse/IGNITE-22359

IGNITE-22359 StripedDisruptorTest.testMultipleSubscriberBatching is flaky

---

modules/jdbc/src/integrationTest/java/org/apache/ignite/internal/jdbc/ItJdbcMetadataSelfTest.java

https://issues.apache.org/jira/browse/IGNITE-22368
Reuse the connection from field.

IGNITE-22368 Close JDBC connection in integration tests

---

modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/recovery/restart/RestartPartitionsTest.java

https://issues.apache.org/jira/browse/IGNITE-22387

IGNITE-22387 Fix restart-partitions CLI unit tests

---

modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxCleanupRequestSender.java

https://issues.apache.org/jira/browse/IGNITE-22335

IGNITE-22335 Add assertion in async TxCleanupMessageResponse handler

---

modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/BinaryTupleBuilder.java
modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/BinaryTupleCommon.java
modules/schema/src/main/java/org/apache/ignite/internal/schema/marshaller/reflection/ObjectStatistics.java
modules/schema/src/main/java/org/apache/ignite/internal/schema/row/RowAssembler.java
modules/table/src/main/java/org/apache/ignite/internal/schema/marshaller/TupleMarshallerImpl.java
modules/table/src/test/java/org/apache/ignite/internal/schema/marshaller/TupleMarshallerStatisticsTest.java

https://issues.apache.org/jira/browse/IGNITE-22061

IGNITE-22061 Use constant value when estimating decimal size.

---

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaService.java

https://issues.apache.org/jira/browse/IGNITE-22207

IGNITE-22207 Fix a deadlock in the ReplicaService

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlOperatorsTest.java
modules/sql-engine/src/integrationTest/sql/function/numeric/test_invalid_math.test
modules/sql-engine/src/integrationTest/sql/function/numeric/test_pg_math.test

IGNITE-21985 Sql. Extend test coverage for SQL T624(Common logarithm functions)

---

modules/sql-engine/src/integrationTest/sql/subquery/any_all/test_any_all.test
modules/sql-engine/src/integrationTest/sql/subquery/any_all/test_correlated_any_all.test

IGNITE-21960 Sql. Extend test coverage for SQL E061-07(Quantified comparison predicate)

---

modules/cli/src/main/java/org/apache/ignite/internal/cli/call/cluster/status/ClusterStatus.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/cluster/status/ClusterStatusCall.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/decorators/ClusterStatusDecorator.java

https://issues.apache.org/jira/browse/IGNITE-22414

IGNITE-22414 Fix cluster status command for not initialized cluster

---

modules/network/src/main/java/org/apache/ignite/internal/network/netty/PipelineUtils.java
modules/network/src/test/java/org/apache/ignite/internal/network/netty/RecoveryHandshakeTest.java

https://issues.apache.org/jira/browse/IGNITE-22399

IGNITE-22399 Improve handling of small network messages on send

---

modules/sql-engine/src/integrationTest/sql/types/char/test_char_comparison.test
modules/sql-engine/src/integrationTest/sql/types/string/test_string_comparison.test

Adds test cases for character comparison operator for CHAR/CHAR, and VARCHAR/VARCHAR.
https://issues.apache.org/jira/browse/IGNITE-21959
--- …

IGNITE-21959: Extend test coverage for SQL E021-12(Character comparison)

---

modules/platforms/cpp/ignite/odbc/config/connection_info.cpp
modules/platforms/cpp/ignite/odbc/config/connection_info.h
modules/platforms/cpp/tests/client-test/basic_authenticator_test.cpp
modules/platforms/cpp/tests/test-common/basic_auth_test_suite.h
modules/platforms/cpp/tests/test-common/ignite_runner.h
modules/platforms/cpp/tests/test-common/test_utils.cpp
modules/platforms/cpp/tests/test-common/test_utils.h

https://issues.apache.org/jira/browse/IGNITE-22052

IGNITE-22052: Fix authentication tests

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItAlterTableDdlTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCreateTableDdlTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDmlTest.java

Marks tests.
https://issues.apache.org/jira/browse/IGNITE-21968
---

IGNITE-21968: Extend test coverage for SQL E141-07(Basic integrity constraints. Column defaults)

---

modules/api/src/main/java/org/apache/ignite/lang/util/IgniteNameUtils.java
modules/core/src/test/java/org/apache/ignite/internal/util/IgniteNameUtilsTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCreateTableDdlTest.java
modules/sql-engine/src/integrationTest/sql/identifiers/test_delimited_identifiers.test

IGNITE-21964 Extend test coverage for SQL E031-01(Identifiers. Delimited identifiers)

---

modules/client/src/main/java/org/apache/ignite/internal/client/compute/ClientTaskExecution.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/ExecutionManager.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/loader/JobContextManager.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/messaging/ComputeMessaging.java
modules/compute/src/main/java/org/apache/ignite/internal/compute/task/TaskExecutionInternal.java
modules/core/src/main/java/org/apache/ignite/internal/util/CompletableFutures.java
modules/core/src/test/java/org/apache/ignite/internal/util/CompletableFuturesTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/AbstractSchemaChangeTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/PersistentTxStateVacuumizer.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TransactionInflights.java

https://issues.apache.org/jira/browse/IGNITE-22518

IGNITE-22518 Rename CompletableFutures#allOf to CompletableFutures#allOfToList

---

modules/platforms/cpp/CMakeLists.txt
modules/platforms/cpp/DEVNOTES.md
modules/platforms/cpp/cmake/dependencies.cmake
modules/platforms/cpp/ignite/client/detail/node_connection.h
modules/platforms/cpp/ignite/common/CMakeLists.txt
modules/platforms/cpp/ignite/common/big_decimal.cpp
modules/platforms/cpp/ignite/common/big_decimal.h
modules/platforms/cpp/ignite/common/big_integer.cpp
modules/platforms/cpp/ignite/common/big_integer.h
modules/platforms/cpp/ignite/common/bignum_test.cpp
modules/platforms/cpp/ignite/common/detail/factory.h
modules/platforms/cpp/ignite/common/detail/mpi.cpp
modules/platforms/cpp/ignite/common/detail/mpi.h
modules/platforms/cpp/ignite/common/detail/utils.h
modules/platforms/cpp/ignite/common/ignite_mbedtls_config.h
modules/platforms/cpp/ignite/common/mpi.cpp
modules/platforms/cpp/ignite/common/mpi.h
modules/platforms/cpp/ignite/network/codec.h
modules/platforms/cpp/ignite/network/codec_data_filter.cpp
modules/platforms/cpp/ignite/network/codec_data_filter.h
modules/platforms/cpp/ignite/network/length_prefix_codec.h
modules/platforms/cpp/ignite/odbc/app/application_data_buffer.cpp
modules/platforms/cpp/ignite/odbc/config/config_tools.cpp
modules/platforms/cpp/ignite/odbc/meta/column_meta.cpp
modules/platforms/cpp/ignite/odbc/query/table_metadata_query.cpp
modules/platforms/cpp/ignite/odbc/sql_statement.cpp
modules/platforms/cpp/ignite/odbc/sql_statement.h
modules/platforms/cpp/ignite/odbc/string_utils.h
modules/platforms/cpp/tests/odbc-test/connection_test.cpp
modules/platforms/cpp/tests/odbc-test/queries_test.cpp

https://issues.apache.org/jira/browse/IGNITE-22198

IGNITE-22198 Support multiple precision arithmetic operations in native code

---

modules/platforms/cpp/CMakeLists.txt

https://issues.apache.org/jira/browse/IGNITE-22529

IGNITE-22529 Make platforms CMake more usable as subproject

---

modules/platforms/cpp/ignite/common/big_decimal.cpp
modules/platforms/cpp/ignite/common/big_decimal.h
modules/platforms/cpp/ignite/common/big_integer.h
modules/platforms/cpp/ignite/common/bignum_test.cpp
modules/platforms/cpp/ignite/tuple/tuple_test.cpp
modules/platforms/cpp/tests/test-common/test_utils.cpp

https://issues.apache.org/jira/browse/IGNITE-22534

IGNITE-22534 Add double constructor and serialization/deserialization code to the decimal type

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/configuration/SchemaSynchronizationConfigurationSchema.java

https://issues.apache.org/jira/browse/IGNITE-22502

IGNITE-22502 Decrease default delay duration to 500 milliseconds

---

modules/api/src/main/java/org/apache/ignite/catalog/definitions/TableDefinition.java
modules/catalog-dsl/src/test/java/org/apache/ignite/internal/catalog/sql/InvalidDefinitionTest.java

Added validation to prevent TableDefinition from generating invalid SQL.
https://issues.apache.org/jira/browse/IGNITE-22276

IGNITE-22276 Add index columns validation for TableDefinition

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AlterTableAddColumnCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CatalogUtils.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateTableCommand.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogTableTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AlterTableAlterColumnCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/CreateTableCommandValidationTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCreateTableDdlTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/ddl/DdlSqlToCommandConverter.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/prepare/ddl/DdlSqlToCommandConverterTest.java

https://issues.apache.org/jira/browse/IGNITE-22421
----

IGNITE-22421: Sql. Interval type. DDL statements should return a proper error

---

docs/_docs/administrators-guide/config/storage/rocksdb.adoc
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageProfile.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/configuration/schema/RocksDbProfileConfigurationSchema.java

https://issues.apache.org/jira/browse/IGNITE-22550

IGNITE-22550 Get rid of RocksDbProfileConfigurationSchema#numShardBits

---

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/datatypes/BaseTypeCoercionTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/datatypes/SetOperatorCoercionTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/datatypes/utils/Types.java

https://issues.apache.org/jira/browse/IGNITE-22462

IGNITE-22462  Add planner test to verify type coercion for set operations like UNION, INTERSECT and EXCEPT

---

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/partitions/reset/ItResetPartitionsCommandTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/partitions/reset/ItResetPartitionsReplCommandTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/partitions/reset/ItResetPartitionsTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/partitions/restart/ItRestartPartitionsCommandTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/partitions/restart/ItRestartPartitionsReplCommandTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/partitions/restart/ItRestartPartitionsTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/partitions/states/ItPartitionStatesCommandTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/partitions/states/ItPartitionStatesReplCommandTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/partitions/states/ItPartitionStatesTest.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/PartitionStatesCallInput.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/reset/ResetPartitionsCallInput.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/restart/RestartPartitionsCallInput.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/RecoveryReplCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/PartitionsCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/PartitionsReplCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/reset/ResetPartitionsCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/reset/ResetPartitionsMixin.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/reset/ResetPartitionsReplCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/restart/RestartPartitionsCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/restart/RestartPartitionsMixin.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/restart/RestartPartitionsReplCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/states/PartitionStatesCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/states/PartitionStatesMixin.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/states/PartitionStatesReplCommand.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/recovery/restart/RestartPartitionsTest.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/recovery/DisasterRecoveryApi.java
modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/recovery/ItDisasterRecoveryControllerResetPartitionsTest.java
modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/recovery/ItDisasterRecoveryControllerRestartPartitionsTest.java
modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/recovery/ItDisasterRecoveryControllerTest.java

https://issues.apache.org/jira/browse/IGNITE-22385

IGNITE-22385 Change Disaster recovery CLI / REST to declarative style

---

modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/MessageClass.java
modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/messages/MessageImplGenerator.java
modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/serialization/MessageSerializerGenerator.java
modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/serialization/SerializationFactoryGenerator.java
modules/network-api/src/main/java/org/apache/ignite/internal/network/NetworkMessage.java
modules/network/src/main/java/org/apache/ignite/internal/network/direct/DirectMessageWriter.java
modules/network/src/main/java/org/apache/ignite/internal/network/direct/state/DirectMessageState.java
modules/network/src/main/java/org/apache/ignite/internal/network/direct/stream/DirectByteBufferStreamImplV1.java
modules/network/src/test/java/org/apache/ignite/internal/network/serialization/MessageSerializationRegistryImplTest.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/util/DefaultByteBuffersPool.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/util/OptimizedStream.java
modules/table/src/test/java/org/apache/ignite/internal/benchmarks/UpdateCommandsMarshalingMicroBenchmark.java

https://issues.apache.org/jira/browse/IGNITE-22544

IGNITE-22544 Benchmark and optimize raft commands serialization.

---

modules/api/src/main/java/org/apache/ignite/lang/ErrorGroups.java
modules/api/src/main/java/org/apache/ignite/lang/UnexpectedNullValueException.java
modules/platforms/cpp/ignite/common/error_codes.h
modules/platforms/cpp/ignite/odbc/common_types.cpp
modules/platforms/dotnet/Apache.Ignite/ErrorCodes.g.cs

https://issues.apache.org/jira/browse/IGNITE-22269

IGNITE-22269 Introduce new err code NULLABLE_VALUE_ERR

---

examples/src/integrationTest/java/org/apache/ignite/example/sql/ItSqlExamplesTest.java
examples/src/main/java/org/apache/ignite/example/sql/SqlApiExample.java

https://issues.apache.org/jira/browse/IGNITE-22262

IGNITE-22262 Sql. Fixed API usage example (SqlApiExample).

---

modules/api/src/main/java/org/apache/ignite/table/KeyValueView.java

IGNITE-22582 Clarify KeyValueView#getAll javadoc about non-existing keys

---

modules/platforms/cpp/ignite/common/big_integer.cpp
modules/platforms/cpp/ignite/common/big_integer.h
modules/platforms/cpp/ignite/common/detail/bits.h
modules/platforms/cpp/ignite/common/detail/bytes.h
modules/platforms/cpp/ignite/common/detail/mpi.cpp
modules/platforms/cpp/ignite/common/detail/mpi.h
modules/platforms/cpp/ignite/common/detail/server_version.h
modules/platforms/cpp/ignite/tuple/binary_tuple_builder.cpp
modules/platforms/cpp/ignite/tuple/tuple_test.cpp
modules/platforms/cpp/tests/client-test/compute_test.cpp
modules/platforms/cpp/tests/test-common/ignite_runner.h

https://issues.apache.org/jira/browse/IGNITE-22541

IGNITE-22541 Fix bool handling in C++ binary_tuple_builder

---

modules/failure-handler/src/main/java/org/apache/ignite/internal/failure/handlers/StopNodeOrHaltFailureHandler.java
modules/failure-handler/src/main/java/org/apache/ignite/internal/failure/handlers/configuration/StopNodeOrHaltFailureHandlerConfigurationSchema.java

https://issues.apache.org/jira/browse/IGNITE-22589

IGNITE-22589 Rename StopNodeOrHaltFailureHandlerConfigurationSchema.timeout to timeoutMillis

---

modules/failure-handler/build.gradle
modules/failure-handler/src/main/java/org/apache/ignite/internal/failure/FailureProcessor.java
modules/failure-handler/src/main/java/org/apache/ignite/internal/failure/handlers/NoOpFailureHandler.java
modules/failure-handler/src/main/java/org/apache/ignite/internal/failure/handlers/StopNodeFailureHandler.java
modules/failure-handler/src/main/java/org/apache/ignite/internal/failure/handlers/StopNodeOrHaltFailureHandler.java
modules/failure-handler/src/test/java/org/apache/ignite/internal/failure/FailureProcessorTest.java

https://issues.apache.org/jira/browse/IGNITE-22591

IGNITE-22589 Fix FailureProcessor initialization

---

docs/_docs/ignite-cli-tool.adoc
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/cluster/init/ItClusterInitTest.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/Options.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/cluster/init/ClusterInitOptions.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/cluster/ClusterInitTest.java
modules/cli/src/test/resources/cluster-configuration-with-default.conf

IGNITE-22574 Ignite CLI: Allow to pass multiple files with cluster configuration for init command.

---

modules/platforms/build.gradle
modules/platforms/cpp/ignite/client/CMakeLists.txt
modules/platforms/cpp/tests/client-test/CMakeLists.txt
modules/platforms/cpp/tests/odbc-test/CMakeLists.txt
packaging/README.md

https://issues.apache.org/jira/browse/IGNITE-22460
Title says it all.

IGNITE-22460 Rename libignite-client.so to libignite3-client.so

---

modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs
modules/platforms/dotnet/Apache.Ignite/Compute/IJobExecution.cs
modules/platforms/dotnet/Apache.Ignite/Compute/JobState.cs
modules/platforms/dotnet/Apache.Ignite/Compute/JobStatus.cs
modules/platforms/dotnet/Apache.Ignite/Internal/Compute/Compute.cs
modules/platforms/dotnet/Apache.Ignite/Internal/Compute/JobExecution.cs

https://issues.apache.org/jira/browse/IGNITE-22525

IGNITE-22525 .NET: Rename JobStatus to JobState and vice versa

---

modules/platforms/build.gradle
modules/platforms/cpp/Doxyfile

https://issues.apache.org/jira/browse/IGNITE-22566

IGNITE-22566 Add C++ docs generation to gradle

---

modules/platforms/cpp/ignite/client/compute/job_execution.cpp
modules/platforms/cpp/ignite/client/compute/job_execution.h
modules/platforms/cpp/ignite/client/compute/job_state.h
modules/platforms/cpp/ignite/client/compute/job_status.h
modules/platforms/cpp/ignite/client/detail/compute/compute_impl.cpp
modules/platforms/cpp/ignite/client/detail/compute/compute_impl.h
modules/platforms/cpp/ignite/client/detail/compute/job_execution_impl.cpp
modules/platforms/cpp/ignite/client/detail/compute/job_execution_impl.h
modules/platforms/cpp/tests/client-test/compute_test.cpp

https://issues.apache.org/jira/browse/IGNITE-22526

IGNITE-22526 Rename job_state to job_status and vice versa

---

modules/platforms/cpp/ignite/client/CMakeLists.txt
modules/platforms/cpp/ignite/client/compute/compute.cpp
modules/platforms/cpp/ignite/client/compute/compute.h
modules/platforms/cpp/ignite/client/compute/job_descriptor.h
modules/platforms/cpp/ignite/client/compute/job_execution_options.h
modules/platforms/cpp/ignite/client/detail/compute/compute_impl.cpp
modules/platforms/cpp/ignite/client/detail/compute/compute_impl.h
modules/platforms/cpp/tests/client-test/compute_test.cpp
modules/platforms/cpp/tests/client-test/schema_synchronization_test.cpp
modules/platforms/cpp/tests/test-common/basic_auth_test_suite.h

https://issues.apache.org/jira/browse/IGNITE-22527

IGNITE-22527 C++ Add parameter object to Compute API

---

examples/src/main/java/org/apache/ignite/example/sql/SqlApiExample.java
modules/api/src/main/java/org/apache/ignite/sql/Statement.java
modules/core/src/main/java/org/apache/ignite/internal/sql/StatementImpl.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/SelectBenchmark.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/api/StatementBuilderImplTest.java

IGNITE-22611 SQL. Statement should not extends AutoClosable 

---

modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/treesitter/parser/SqlTokenType.java

https://issues.apache.org/jira/browse/IGNITE-22612

IGNITE-22612 SQL highlighter sometimes fails

---

modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcComplexQuerySelfTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDataTypesTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItFunctionsTest.java
modules/sql-engine/src/integrationTest/sql/cast/test_cast_bigint.test
modules/sql-engine/src/integrationTest/sql/cast/test_cast_int.test
modules/sql-engine/src/integrationTest/sql/cast/test_cast_smallint.test
modules/sql-engine/src/integrationTest/sql/cast/test_cast_tinyint.test
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/ConverterUtils.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/IgniteExpressions.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteSqlValidator.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rex/IgniteRexBuilder.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/IgniteMath.java

IGNITE-22578 Sql. Extend test coverage for numeric to/from decimal cast with overflow

---

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/PartitionReplicationMessageGroup.java
modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/PartitionReplicationMessageUtils.java
modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/disaster/LocalPartitionStateEnum.java
modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/disaster/LocalPartitionStateMessage.java
modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/raft/SnapshotTxDataResponse.java
modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/raft/TxMetaMessage.java
modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/replication/MultipleRowPkReplicaRequest.java
modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/replication/MultipleRowReplicaRequest.java
modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/replication/RequestType.java
modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/replication/SingleRowPkReplicaRequest.java
modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/replication/SingleRowReplicaRequest.java
modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/replication/SwapRowReplicaRequest.java
modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/network/disaster/LocalPartitionStateEnumTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/UpdatableTableImpl.java
modules/table/src/integrationTest/java/org/apache/ignite/distributed/ReplicaUnavailableTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItColocationTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/DisasterRecoveryManager.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/ManualGroupUpdateRequest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotCopier.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/outgoing/OutgoingSnapshot.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/PartitionCommandListenerTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotCopierTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/outgoing/OutgoingSnapshotTxDataStreamingTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerIndexLockingTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replicator/action/RequestTypeTest.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/TxState.java
modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxStateTest.java

https://issues.apache.org/jira/browse/IGNITE-22614

IGNITE-22614 Get rid of @Marshallable in package org.apache.ignite.internal.partition.replicator.network

---

modules/index/src/integrationTest/java/org/apache/ignite/internal/index/ItIndexNodeFinishedRwTransactionsCheckerTest.java
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/MvPartitionStorage.java
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/ThreadAssertingMvPartitionStorage.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvPartitionStorage.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceRecoveryTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceTriggersRecoveryTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/IndexCleanupTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/StorageCleanupTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/StorageUpdateHandlerTest.java

https://issues.apache.org/jira/browse/IGNITE-22618

IGNITE-22618 Remove MvPartitionStorage#rowsCount

---

modules/cli/src/main/java/org/apache/ignite/internal/cli/core/flow/builder/Flows.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/CliCommandTestBase.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/cluster/ClusterInitReplTest.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/cluster/ClusterInitTest.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/flow/FlowTest.java

https://issues.apache.org/jira/browse/IGNITE-22632

IGNITE-22632 Handle cluster configuration file reading error

---

modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/ActionRequestProcessor.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/SMCompactedThrowable.java

https://issues.apache.org/jira/browse/IGNITE-22597

IGNITE-22597 Use SMFullThrowable when exception in user's state machine happens.

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItReplicaStateManagerTest.java

https://issues.apache.org/jira/browse/IGNITE-22649

IGNITE-22649 Disable ItReplicaStateManagerTest.testReplicaStatesManagement

---

modules/index/src/main/java/org/apache/ignite/internal/index/IndexBuildController.java

https://issues.apache.org/jira/browse/IGNITE-22556

IGNITE-22556 Fix exception in IndexBuildController.requireMvTableStorageNonNull

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/schemasync/ItSchemaSyncMultiNodeTest.java

https://issues.apache.org/jira/browse/IGNITE-21512
The test does not fail anymore

IGNITE-21512 Enable a test in ItSchemaSyncMultiNodeTest

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexMetaStorage.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/index/BaseIndexMetaStorageTest.java

https://issues.apache.org/jira/browse/IGNITE-22673

IGNITE-22673 Fix predicate in candition of IndexMetaStorage#saveToMetastore

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/UpdateLogImpl.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/storage/UpdateLogImplTest.java

https://issues.apache.org/jira/browse/IGNITE-22674

IGNITE-22674 Fix predicate in condition of UpdateLogImpl#saveSnapshot

---

modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/reset/ResetPartitionsCallInput.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/restart/RestartPartitionsCallInput.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/states/PartitionStatesCall.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/states/PartitionStatesCallInput.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/reset/ResetPartitionsCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/reset/ResetPartitionsMixin.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/reset/ResetPartitionsReplCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/restart/RestartPartitionsCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/restart/RestartPartitionsMixin.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/restart/RestartPartitionsReplCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/states/PartitionStatesCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/states/PartitionStatesMixin.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/states/PartitionStatesReplCommand.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/ProfileMixinTest.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/ProfileOptionTest.java

https://issues.apache.org/jira/browse/IGNITE-22675

IGNITE-22675 Recovery CLI commands don't accept profile option

---

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java
modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngine.java
modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngineV2.java
modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceRaftGroupEventsListener.java
modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtil.java
modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/ZoneRebalanceRaftGroupEventsListener.java
modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngineTest.java
modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtilUpdateAssignmentsTest.java
modules/index/src/main/java/org/apache/ignite/internal/index/IndexAvailabilityController.java
modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java

https://issues.apache.org/jira/browse/IGNITE-22415

IGNITE-22415 Search for table in older versions of catalog

---

packaging/odbc/build.gradle

https://issues.apache.org/jira/browse/IGNITE-22686

IGNITE-22686 Fix ODBC MSI package build

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java

https://issues.apache.org/jira/browse/IGNITE-22521

IGNITE-22521 ItIgniteNodeRestartTest.testSequentialAsyncTableCreationThenAlterZoneThenRestartOnMsSnapshot is flaky

---

modules/table/src/integrationTest/java/org/apache/ignite/internal/threading/ItKvRecordApiThreadingTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/threading/ItPartitionManagerApiThreadingTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/PublicApiThreadingTable.java
modules/table/src/main/java/org/apache/ignite/internal/table/partition/PublicApiThreadingPartitionManager.java

https://issues.apache.org/jira/browse/IGNITE-22693

IGNITE-22693 Add protection against internal thread hijacking to PartitionManager

---

modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientOp.java
modules/client/src/test/java/org/apache/ignite/client/RetryPolicyTest.java

https://issues.apache.org/jira/browse/IGNITE-22523

IGNITE-22523 Thin client: reserve op code range for extensions

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java

https://issues.apache.org/jira/browse/IGNITE-22714

IGNITE-22714 Use IndexMeta in PartitionReplicaListener

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AbstractCreateIndexCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateHashIndexCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateSortedIndexCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateTableCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogHashIndexDescriptor.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogIndexDescriptor.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogSortedIndexDescriptor.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/AbstractChangeIndexStatusEntry.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/RenameIndexEntry.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogIndexTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerRecoveryTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogTableTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AbstractChangeIndexStatusCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/CatalogUtilsTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/descriptors/CatalogHashIndexDescriptorTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/descriptors/CatalogSortedIndexDescriptorTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/storage/CatalogEntrySerializationTest.java
modules/storage-api/src/test/java/org/apache/ignite/internal/storage/index/StorageIndexDescriptorTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractHashIndexStorageTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractSortedIndexStorageTest.java

https://issues.apache.org/jira/browse/IGNITE-22720

IGNITE-22720 Get rid of CatalogIndexDescriptor#txWaitCatalogVersion

---

modules/network-api/src/main/java/org/apache/ignite/internal/network/TrackableNetworkMessageHandler.java

https://issues.apache.org/jira/browse/IGNITE-22310

IGNITE-22310 Do not log slow network processing in storage threads

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableUtils.java

https://issues.apache.org/jira/browse/IGNITE-21771

IGNITE-21771 Removed unnecessary TODO

---

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/marshaller/PartitionCommandsMarshallerImpl.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/schema/PartitionCommandsMarshallerImpl.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/schema/PartitionCommandsMarshallerImplTest.java

https://issues.apache.org/jira/browse/IGNITE-22736

IGNITE-22736 Fix log buffers position change by unmarshalling process

---

modules/platforms/cpp/ignite/common/big_decimal.cpp

https://issues.apache.org/jira/browse/IGNITE-22737

IGNITE-22737 Cleanup comments in the platforms native code

---

modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java

https://issues.apache.org/jira/browse/IGNITE-22750

IGNITE-22750 log node start errors in error logging level

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/InsertBenchmark.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteSqlToRelConvertor.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/ParserServiceImpl.java

https://issues.apache.org/jira/browse/IGNITE-22735
Results of e2e benchmark on my laptop as follow: 
```
Before:
Benchmark                          (clusterSize)  (fsync)  (partitionCount)  Mode  Cnt    Score   Error  Units
InsertBenchmark.sqlInlinedInsert               1    false                25  avgt   20  249.793 ± 6.699  us/op
InsertBenchmark.sqlPreparedInsert              1    false                25  avgt   20   74.698 ± 5.611  us/op
After:
Benchmark                          (clusterSize)  (fsync)  (partitionCount)  Mode  Cnt    Score   Error  Units
InsertBenchmark.sqlInlinedInsert               1    false                25  avgt   20  221.851 ± 6.699  us/op
InsertBenchmark.sqlPreparedInsert              1    false                25  avgt   20   74.618 ± 6.140  us/op
``` …

IGNITE-22735 Sql. Avoid double parsing of sql queries

---

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/KeyValueStorage.java

https://issues.apache.org/jira/browse/IGNITE-16444

IGNITE-16444 Get rid of unnecessary TODO

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItInternalTableTest.java
modules/schema/src/testFixtures/java/org/apache/ignite/internal/schema/BinaryRowMatcher.java
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/MvPartitionStorage.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageConcurrencyTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageGcTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvPartitionStorage.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorageTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorageTest.java

https://issues.apache.org/jira/browse/IGNITE-22764

IGNITE-22764 Increase readability in MvPartitionStorage tests

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java

https://issues.apache.org/jira/browse/IGNITE-20137

IGNITE-20137 Fixed ItIgniteNodeRestartTest#testOneNodeRestartWithGap

---

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java
modules/raft-api/src/main/java/org/apache/ignite/internal/raft/RaftManager.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/Loza.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/LogStorageFactory.java
modules/raft/src/testFixtures/java/org/apache/ignite/internal/raft/TestLozaFactory.java
modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerRecoveryTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java

https://issues.apache.org/jira/browse/IGNITE-22292

IGNITE-22292 Moved LogSyncer out of Loza and RaftServer.

---

modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/StoragePartitionMeta.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/StoragePartitionMetaFactory.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/StoragePartitionMetaIo.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AddWriteCommittedInvokeClosure.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/CommitWriteInvokeClosure.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorage.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/VolatilePageMemoryMvPartitionStorage.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryMvTableStorageTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/StoragePartitionMetaManagerTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/StoragePartitionMetaTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryMvTableStorageTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorageTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorageConcurrencyTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/VolatilePageMemoryMvPartitionStorageConcurrencyTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorageTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvTableStorageTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItEstimatedSizeTest.java

https://issues.apache.org/jira/browse/IGNITE-22616

IGNITE-22616 Implement AbstractPageMemoryMvPartitionStorage#estimatedSize

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCastToTsWithLocalTimeZoneTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/RexToLixTranslator.java

https://issues.apache.org/jira/browse/IGNITE-22780
-------------------------

IGNITE-22780 Sql. Fix cast from VARCHAR to TS WITH LOCAL TZ 

---

docs/_docs/developers-guide/java-to-tables.adoc
modules/api/src/main/java/org/apache/ignite/catalog/IgniteCatalog.java

https://issues.apache.org/jira/browse/IGNITE-22658
Examples that could not be compiled and executed are updated.

IGNITE-22658 Update IgniteCatalog javadoc

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCastToTsWithLocalTimeZoneTest.java

https://issues.apache.org/jira/browse/IGNITE-22793
--------------

IGNITE-22793 Sql. Make ItCastToTsWithLocalTimeZoneTest stable

---

modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageTest.java
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvPartitionStorage.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AddWriteCommittedInvokeClosure.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/CommitWriteInvokeClosure.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorageTest.java

https://issues.apache.org/jira/browse/IGNITE-22797

IGNITE-22797 Fix estimated size for insert-after-delete scenario

---

modules/page-memory/src/integrationTest/java/org/apache/ignite/internal/pagememory/tree/AbstractBplusTreeReusePageMemoryTest.java
modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/datastructure/DataStructure.java
modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/freelist/FreeListImpl.java
modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/freelist/PagesList.java
modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/tree/BplusTree.java
modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/freelist/FreeListImplTest.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryTableStorage.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryDataRegion.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/HashIndexRow.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/HashIndexRowKey.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/HashIndexTree.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/meta/IndexMetaKey.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/meta/IndexMetaTree.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/SortedIndexRow.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/SortedIndexTree.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/VersionChainTree.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/gc/GcQueue.java

https://issues.apache.org/jira/browse/IGNITE-22799

IGNITE-22799 Add partition ID to BplusTree names to make debugging easier

---

check-rules/spotbugs-excludes.xml
modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/GarbageCollector.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMetaStorage.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/ThreadLocalState.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/instance/SharedRocksDbInstance.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorageConcurrencyTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorageTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvTableStorageTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItEstimatedSizeTest.java

https://issues.apache.org/jira/browse/IGNITE-22617

IGNITE-22617 Implement RocksDbMvPartitionStorage#estimatedSize

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java

https://issues.apache.org/jira/browse/IGNITE-22820

IGNITE-22820 Unwrap exception cause on retry in InternalTableImpl

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/datatypes/ItCastToTsWithLocalTimeZoneTest.java

https://issues.apache.org/jira/browse/IGNITE-22831
--------------

IGNITE-22831 Sql. Make ItCastToTsWithLocalTimeZoneTest stable (attempt #2)

---

modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/causalitydatanodes/DistributionZoneCausalityDataNodesTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItEstimatedSizeTest.java

https://issues.apache.org/jira/browse/IGNITE-22834

IGNITE-22834 disable flaky testEstimatedSizeAfterScaleUp test

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDmlTest.java

…est correctness
https://issues.apache.org/jira/browse/IGNITE-22848

IGNITE-22848 ItDmlTest#scanExecutedWithinGivenTransaction make this test correctness

---

modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs
modules/platforms/dotnet/Apache.Ignite/ClientOperationType.cs
modules/platforms/dotnet/Apache.Ignite/Compute/ICompute.cs
modules/platforms/dotnet/Apache.Ignite/Compute/ITaskExecution.cs
modules/platforms/dotnet/Apache.Ignite/Compute/TaskDescriptor.cs
modules/platforms/dotnet/Apache.Ignite/Compute/TaskState.cs
modules/platforms/dotnet/Apache.Ignite/Compute/TaskStatus.cs
modules/platforms/dotnet/Apache.Ignite/Internal/Compute/Compute.cs
modules/platforms/dotnet/Apache.Ignite/Internal/Compute/JobExecution.cs
modules/platforms/dotnet/Apache.Ignite/Internal/Compute/TaskExecution.cs
modules/platforms/dotnet/Apache.Ignite/Internal/Proto/ClientOp.cs
modules/platforms/dotnet/Apache.Ignite/Internal/Proto/ClientOpExtensions.cs
modules/platforms/dotnet/Apache.Ignite/RetryReadPolicy.cs
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/PlatformTestNodeRunner.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientComputeTest.java

* Add `ICompute.SubmitMapReduceAsync`, `ITaskExecution`, `TaskDescriptor`, `TaskState`, `TaskStatus`
* Rename `IJobExecution.GetStatusAsync` to `GetStateAsync`

IGNITE-22125 .NET: Add MapReduce API

---

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java

IGNITE-22859 Mute ItReplicaLifecycleTest#testAlterFilterTrigger

---

modules/client-common/src/main/java/org/apache/ignite/internal/client/table/MutableTupleBinaryTupleAdapter.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTablePutGetEmbeddedTest.java

Remove unnecessary assertion, add test.

IGNITE-22013 Java thin: fix AssertionError on single-column table with KeyValueView

---

modules/network-api/src/main/java/org/apache/ignite/internal/network/NetworkMessage.java
modules/network-api/src/main/java/org/apache/ignite/internal/network/TrackableNetworkMessageHandler.java
modules/network/src/main/java/org/apache/ignite/internal/network/DefaultMessagingService.java
modules/network/src/main/java/org/apache/ignite/internal/network/message/InvokeRequest.java
modules/network/src/main/java/org/apache/ignite/internal/network/message/InvokeResponse.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/RaftGroupServiceImpl.java

https://issues.apache.org/jira/browse/IGNITE-22869

IGNITE-22869 Fix some NetworkMessage logging

---

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/datatypes/NumericCaseTypeCoercionTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/datatypes/NumericComparisonTypeCoercionTest.java

IGNITE-22580 Sql. Add planner test to verify numeric type coercion for CASE operator

---

modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/DefaultLogStorageFactory.java
modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/flush/RocksDbFlushListener.java

https://issues.apache.org/jira/browse/IGNITE-21993

IGNITE-21993 Move WAL sync before RocksDB flush under if statement

---

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/datatypes/NumericCaseTypeCoercionTest.java

IGNITE-22892 Sql. NumericCaseTypeCoercionTest duplicates test case fix

---

modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/TestServer.java
modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/raft/ItCmgRaftServiceTest.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterInitializer.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterTag.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/network/messages/CmgInitMessage.java
modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManagerTest.java
modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/ClusterTagTest.java
modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/network/CmgMessageHandlerTest.java
modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/AbstractClusterStateStorageManagerTest.java
modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListenerTest.java

https://issues.apache.org/jira/browse/IGNITE-22803

IGNITE-22803 Put cluster ID in CmgInitMessage

---

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java

https://issues.apache.org/jira/browse/IGNITE-22947

IGNITE-22947 Fix check style.

---

modules/platforms/build.gradle
modules/platforms/cpp/ignite/network/CMakeLists.txt

https://issues.apache.org/jira/browse/IGNITE-22961

IGNITE-22961 Fix platforms build on Mac

---

modules/api/src/main/java/org/apache/ignite/table/TupleImpl.java
modules/api/src/test/java/org/apache/ignite/table/TupleImplTest.java
modules/table/src/main/java/org/apache/ignite/internal/schema/marshaller/TupleMarshallerImpl.java
modules/table/src/main/java/org/apache/ignite/table/TupleHelper.java
modules/table/src/test/java/org/apache/ignite/table/TupleHelperTest.java

https://issues.apache.org/jira/browse/IGNITE-22958
```
Benchmark                                   (fieldsCount)  (nullable)  Mode  Cnt          Before          After  Units
TupleMarshallerFixlenOnlyBenchmark.measure              1       false  avgt   10   0.267 ± 0.001  0.207 ± 0.002  us/op
TupleMarshallerFixlenOnlyBenchmark.measure             10       false  avgt   10   1.168 ± 0.006  0.624 ± 0.001  us/op
TupleMarshallerFixlenOnlyBenchmark.measure            100       false  avgt   10  10.166 ± 0.055  5.415 ± 0.012  us/op
Benchmark                 (clusterSize)  (fsync)  (partitionCount)  Mode  Cnt          Before           After  Units
InsertBenchmark.kvInsert              1    false                25  avgt   20  65.570 ± 7.661  61.336 ± 4.492  us/op
```
-------------------
Thank you …

IGNITE-22958 Improve performance of TupleMarshaller part 2

---

modules/sql-engine/build.gradle
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestBuilders.java

IGNITE-22753 Sql. TestCluster, NPE eventually raised on mocked structure

---

modules/api/src/main/java/org/apache/ignite/lang/IgniteException.java
modules/failure-handler/src/main/java/org/apache/ignite/internal/failure/FailureProcessor.java
modules/workers/build.gradle
modules/workers/src/integrationTest/java/org/apache/ignite/internal/worker/ItCriticalWorkerMonitoringTest.java
modules/workers/src/main/java/org/apache/ignite/internal/worker/CriticalWorkerWatchdog.java

https://issues.apache.org/jira/browse/IGNITE-22976

IGNITE-22976 Remove CriticalWorkerWatchdog message duplication

---

modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java

https://issues.apache.org/jira/browse/IGNITE-22983

IGNITE-22983 Create public API components once

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientComputeMarshallingTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientComputeTypeCheckMarshallingTest.java

https://issues.apache.org/jira/browse/IGNITE-22982
There's no point in creating a specific client for these tests, we can use the common one.
Also the test should wait for the particular status.

IGNITE-22982 Use cached client in compute tests

---

modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryReconfigurationTest.java

https://issues.apache.org/jira/browse/IGNITE-22850

IGNITE-22850 The same set of leases writes to Meta storage

---

modules/catalog-compaction/src/main/java/org/apache/ignite/internal/catalog/compaction/CatalogCompactionRunner.java
modules/catalog-compaction/src/test/java/org/apache/ignite/internal/catalog/compaction/CatalogCompactionRunnerSelfTest.java
modules/client-handler/src/testFixtures/java/org/apache/ignite/client/handler/FakePlacementDriver.java
modules/index/src/test/java/org/apache/ignite/internal/index/TestPlacementDriver.java
modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/utils/TestPlacementDriver.java
modules/placement-driver-api/src/main/java/org/apache/ignite/internal/placementdriver/AssignmentsPlacementDriver.java
modules/placement-driver-api/src/testFixtures/java/org/apache/ignite/internal/placementdriver/TestPlacementDriver.java
modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/AssignmentsTracker.java
modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/PlacementDriverManager.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/ExecutionTargetProviderImpl.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/wrappers/DelegatingPlacementDriver.java

IGNITE-22722 Add the ability to get assignments for a list of replication groups at once

---

modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/DefaultLogStorageFactory.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/util/SharedLogStorageFactoryUtils.java
modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/LoggingRocksDbFlushListener.java
modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/flush/RocksDbFlushListener.java
modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/flush/RocksDbFlusher.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageProfile.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/instance/SharedRocksDbInstanceCreator.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorageTest.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbSharedStorage.java

https://issues.apache.org/jira/browse/IGNITE-22987

IGNITE-22987 Add logs for rocksdb flusher

---

modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItEstimatedSizeTest.java

https://issues.apache.org/jira/browse/IGNITE-23002

IGNITE-23002 Mute ItEmbeddedMarshallingTest.testEstimatedSizeAfterScaleUp

---

modules/low-watermark/src/main/java/org/apache/ignite/internal/lowwatermark/LowWatermarkImpl.java
modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java
modules/raft/build.gradle
modules/raft/src/main/java/org/apache/ignite/internal/raft/Loza.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java
modules/raft/src/test/java/org/apache/ignite/internal/raft/StateMachineFailureHandlerTest.java
modules/raft/src/testFixtures/java/org/apache/ignite/internal/raft/TestLozaFactory.java
modules/raft/src/testFixtures/java/org/apache/ignite/internal/raft/server/TestJraftServerFactory.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java

https://issues.apache.org/jira/browse/IGNITE-22599

IGNITE-22599 Invoke failure handler for users state machine errors.

---

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/mapping/MappingParameters.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/mapping/largecluster/AbstractTarget.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/mapping/largecluster/LargeClusterFactory.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/mapping/smallcluster/SmallClusterFactory.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/mapping/ExecutionTargetFactorySelfTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/mapping/MappingServiceImplTest.java

IGNITE-22861 Sql. Make mapping parameters respect mapOnBackups flag.

---

modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/completer/DynamicCompletionInsider.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/core/repl/completer/DynamicCompleterRegistryTest.java

https://issues.apache.org/jira/browse/IGNITE-23031

IGNITE-23031 Fix parameter completion when option is present

---

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/sql/ItSqlReplCommandNotInitialedClusterTest.java
modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/topology/ItLogicalTopologyTest.java
modules/failure-handler/src/integrationTest/java/org/apache/ignite/internal/failure/handlers/FailureHandlerTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/start/ItStartTest.java
modules/runner/src/testFixtures/java/org/apache/ignite/internal/Cluster.java
modules/security/src/integrationTest/java/org/apache/ignite/internal/ssl/ItSslTest.java

https://issues.apache.org/jira/browse/IGNITE-23029

IGNITE-23029 Cluster#startAndInit() should wait for node registration

---

modules/platforms/cpp/ignite/network/CMakeLists.txt
modules/platforms/cpp/ignite/odbc/sql_connection.cpp
modules/platforms/cpp/ignite/odbc/sql_statement.h
modules/platforms/python/cpp_module/CMakeLists.txt
modules/platforms/python/cpp_module/module.cpp
modules/platforms/python/cpp_module/py_connection.cpp
modules/platforms/python/cpp_module/py_cursor.cpp
modules/platforms/python/cpp_module/py_cursor.h
modules/platforms/python/pyignite3/__init__.py
modules/platforms/python/pyignite3/native_type_code.py
modules/platforms/python/tests/test_connect.py
modules/platforms/python/tests/test_execute.py
modules/platforms/python/tests/util.py

https://issues.apache.org/jira/browse/IGNITE-22469
- Implemented query execution;
- Added tests;
- Type support is currently limited [IGNITE-22745](https://issues.apache.org/jira/browse/IGNITE-22745);
- Parameters are not supported yet as this functionality is mostly covered by [IGNITE-22741](https://issues.apache.org/jira/browse/IGNITE-22741).

IGNITE-22469 DB API Driver: Implement simple query execution

---

modules/api/build.gradle
modules/api/src/main/java/org/apache/ignite/lang/ErrorGroup.java
modules/api/src/main/java/org/apache/ignite/lang/ErrorGroups.java

IGNITE-22963 Remove fastutils from dependencies of ignite-api

---

modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/instance/SharedRocksDbInstanceCreator.java

https://issues.apache.org/jira/browse/IGNITE-23045

IGNITE-23045 Fix parameters order in SharedRocksDbInstanceCreator

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogTableDescriptor.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogTableTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/IgniteIndex.java

IGNITE-22945 Remove duplicate method from CatalogTableDescriptor

---

modules/storage-api/src/test/java/org/apache/ignite/internal/storage/util/MvPartitionStoragesTest.java

https://issues.apache.org/jira/browse/IGNITE-23047

IGNITE-23047 Fix flaky MvPartitionStoragesTest#testWaitOperationOnGetAllForCloseOrDestroy

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogTableDescriptor.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogTableTest.java

https://issues.apache.org/jira/browse/IGNITE-23053

IGNITE-23053 Get rid of CatalogTableDescriptor#creationToken

---

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogParamsValidationUtils.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AbstractIndexCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AbstractTableCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CatalogUtils.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/RenameIndexCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/RenameIndexCommandBuilder.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogIndexTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AlterTableAddColumnCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AlterTableAlterColumnCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AlterTableDropColumnCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/CreateTableCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/DropTableCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/RenameIndexCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/RenameTableCommandValidationTest.java
modules/catalog/src/testFixtures/java/org/apache/ignite/internal/catalog/BaseCatalogManagerTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCreateTableDdlTest.java

IGNITE-18747 Sql. Provide commands and handlers for index rename operation

---

modules/core/src/main/java/org/apache/ignite/internal/hlc/HybridClockImpl.java
modules/core/src/test/java/org/apache/ignite/internal/hlc/HybridClockTest.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/server/raft/ItMetaStorageRaftGroupTest.java

https://issues.apache.org/jira/browse/IGNITE-23050

IGNITE-23050 Restore systemUTC().instant().toEpochMilli() in HybridClockImpl for better stability

---

packaging/db/linux/service/vars.env
packaging/db/zip/linux/vars.env
packaging/db/zip/windows/vars.bat

https://issues.apache.org/jira/browse/IGNITE-23048

IGNITE-23048 Set JVM_GC_LOG_SIZE with units

---

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java

https://issues.apache.org/jira/browse/IGNITE-23062

IGNITE-23062 Disable ItReplicaLifecycleTest.testStableAreWrittenAfterRestart

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/AsyncApiOperation.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/References.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/SyncApiOperation.java
modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofIgnite.java
modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofIgniteTables.java
modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofIgniteTransactions.java
modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofKeyValueView.java
modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofPartitionManager.java
modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofRecordView.java
modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofTable.java

https://issues.apache.org/jira/browse/IGNITE-23012

IGNITE-23012 Support IgniteTransactions transparency wrt node restart

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/ApiReferencesTestUtils.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/AsyncApiOperation.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/ItShutDownServerApiReferencesTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/References.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/SyncApiOperation.java
modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofIgnite.java
modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofIgniteSql.java

https://issues.apache.org/jira/browse/IGNITE-23013

IGNITE-23013 Support IgniteSql transparency with respect to node restart

---

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/pruning/ModifyNodeVisitor.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/pruning/PartitionPruningMetadataExtractor.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/PartitionPruningMetadataTest.java

https://issues.apache.org/jira/browse/IGNITE-22785
--------

IGNITE-22785 Sql. Fix ArrayIndexOutOfBoundsException when key column literal overflows

---

modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java
modules/client/src/test/java/org/apache/ignite/client/HeartbeatTest.java

Fix incorrect condition for enabling heartbeat timeout.

IGNITE-23067 Java thin: fix heartbeat timeout

---

modules/raft/src/main/java/org/apache/ignite/internal/raft/RaftGroupServiceImpl.java

https://issues.apache.org/jira/browse/IGNITE-23071

IGNITE-23071 Yet another raft log pollution reduction.

---

modules/index/build.gradle
modules/index/src/integrationTest/java/org/apache/ignite/internal/index/ItIndexNodeFinishedRwTransactionsCheckerTest.java

https://issues.apache.org/jira/browse/IGNITE-23077

IGNITE-23077 Fix flaky ItIndexNodeFinishedRwTransactionsCheckerTest#testOnePhaseCommitViaKeyValue

---

modules/sql-engine/src/test/resources/mapping/test_partition_pruning.test

https://issues.apache.org/jira/browse/IGNITE-22773
----------

IGNITE-22773 Sql. Add test on partition pruning for disjoint case

---

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceRaftGroupEventsListener.java
modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/ZoneRebalanceRaftGroupEventsListener.java
modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java

https://issues.apache.org/jira/browse/IGNITE-22680

IGNITE-22680 Use matching assignments timestamp in zone rebalance listener

---

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterState.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/ClusterStateStorageManager.java
modules/core/src/main/java/org/apache/ignite/internal/util/CompletableFutures.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java
modules/runner/build.gradle
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteServerImpl.java
modules/system-disaster-recovery/README.md
modules/system-disaster-recovery/build.gradle
modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/ClusterResetException.java
modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/ServerRestarter.java
modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManager.java
modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImpl.java
modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/message/ResetClusterMessage.java
modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/message/SystemDisasterRecoveryMessageGroup.java
modules/system-disaster-recovery/src/test/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImplTest.java
settings.gradle

https://issues.apache.org/jira/browse/IGNITE-22876

IGNITE-22876 Implement cluster reset initiation

---

modules/system-disaster-recovery/src/test/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImplTest.java

https://issues.apache.org/jira/browse/IGNITE-23095

IGNITE-23095 Fix crashes in SystemDisasterRecoveryManagerImplTest

---

modules/core/src/main/java/org/apache/ignite/internal/util/VersatileReadWriteLock.java

https://issues.apache.org/jira/browse/IGNITE-23099

IGNITE-23099 Fix writeUnlock() contract in VersatileReadWriteLock

---

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/configuration/ItConfigCommandTest.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/configuration/NodeConfigUpdateCall.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/node/config/NodeConfigTest.java

https://issues.apache.org/jira/browse/IGNITE-23089

IGNITE-23089 Node config update command show terminal control symbols

---

modules/security/src/main/java/org/apache/ignite/internal/security/authentication/AuthenticationManagerImpl.java
modules/security/src/main/java/org/apache/ignite/internal/security/authentication/basic/BasicAuthenticator.java
modules/security/src/test/java/org/apache/ignite/internal/security/authentication/AuthenticationManagerImplTest.java
modules/security/src/test/java/org/apache/ignite/internal/security/authentication/UserDetailsMatcher.java
modules/security/src/test/java/org/apache/ignite/internal/security/authentication/basic/BasicAuthenticatorTest.java

https://issues.apache.org/jira/browse/IGNITE-23100

IGNITE-23100 Improve semantic of authenticateAsync

---

modules/schema/src/main/java/org/apache/ignite/internal/schema/configuration/GcConfigurationSchema.java

https://issues.apache.org/jira/browse/IGNITE-23104

IGNITE-23104 Add validation of some fields in GcConfigurationSchema

---

modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestThreeNodesThreeReplicas.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java

https://issues.apache.org/jira/browse/IGNITE-23086

IGNITE-23086 Fix ItTxDistributedTestThreeNodesThreeReplicas.testDeleteUpsertAllRollback

---

modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageServicePersistenceTest.java

https://issues.apache.org/jira/browse/IGNITE-23098

IGNITE-23098 Make sure raft is closed before storage

---

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/PersistentPageMemory.java
modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointDirtyPages.java
modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointPagesWriter.java
modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointPagesWriterFactory.java
modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointWorkflow.java
modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/Checkpointer.java
modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/replacement/RandomLruPageReplacementPolicy.java
modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointPagesWriterTest.java

https://issues.apache.org/jira/browse/IGNITE-23084

IGNITE-23084 Implement checkpoint buffer draining in checkpoint threads if it's close to overflow

---

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/configuration/ItConfigCommandTest.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/treesitter/highlighter/JsonAnsiHighlighter.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/decorators/JsonDecorator.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/cluster/config/ClusterConfigTest.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/node/config/NodeConfigTest.java

https://issues.apache.org/jira/browse/IGNITE-23101

IGNITE-23101 CLI should show HOCON representation of the config

---

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/system-disaster-recovery-api/src/main/java/org/apache/ignite/internal/disaster/system/message/ResetClusterMessage.java
modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItCmgDisasterRecoveryTest.java
modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManager.java
modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImpl.java
modules/system-disaster-recovery/src/test/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImplTest.java

https://issues.apache.org/jira/browse/IGNITE-22808

IGNITE-22808 Migrate running node missed during CMG reparation to new cluster

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDataTypesTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/sqllogic/ItSqlLogicTest.java
modules/sql-engine/src/integrationTest/sql/cast/test_cast_bigint.test
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteSqlValidator.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteTypeCoercion.java

IGNITE-20889 Sql. Remove extra coercion code

---

modules/platforms/python/cpp_module/CMakeLists.txt
modules/platforms/python/cpp_module/module.cpp
modules/platforms/python/cpp_module/py_connection.cpp
modules/platforms/python/cpp_module/py_cursor.cpp
modules/platforms/python/pyignite3/__init__.py
modules/platforms/python/setup.py
modules/platforms/python/tox.ini

https://issues.apache.org/jira/browse/IGNITE-22747

IGNITE-22747 Python Client: add tox.ini for CI/CD

---

modules/cluster-management/src/testFixtures/java/org/apache/ignite/internal/cluster/management/BaseItClusterManagementTest.java
modules/network/src/main/java/org/apache/ignite/internal/network/StaticNodeFinder.java
modules/network/src/test/java/org/apache/ignite/internal/network/StaticNodeFinderMain.java
modules/network/src/test/java/org/apache/ignite/internal/network/StaticNodeFinderTest.java
modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java
modules/table/src/testFixtures/java/org/apache/ignite/internal/table/TxAbstractTest.java

https://issues.apache.org/jira/browse/IGNITE-22942

IGNITE-22942 Add ability to StaticNodeFinder to resolve multiple IP addresses under the same host name

---

modules/platforms/cpp/ignite/odbc/query/data_query.cpp
modules/platforms/cpp/ignite/odbc/query/data_query.h
modules/platforms/python/cpp_module/py_cursor.cpp
modules/platforms/python/pyignite3/__init__.py
modules/platforms/python/tests/test_execute.py
modules/platforms/python/tests/test_fetch_constants.py
modules/platforms/python/tests/test_fetch_table.py

https://issues.apache.org/jira/browse/IGNITE-22741
- Implemented data fetching row by row, using [fetchone()](https://peps.python.org/pep-0249/#fetchone);
- Implemented data fetching in bulk, using [fetchmany()](https://peps.python.org/pep-0249/#fetchmany);
- Implemented fetching of the all remaining data, using [fetchall()](https://peps.python.org/pep-0249/#fetchall);
- Added tests for supported data types constants;
- Added tests for table data;
- Created separate ticket [IGNITE-23126](https://issues.apache.org/jira/browse/IGNITE-23126) to support parameters.

IGNITE-22741 DB API Driver 3: Implement Data Fetching

---

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java
modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java

https://issues.apache.org/jira/browse/IGNITE-22679

IGNITE-22679 Explain the workflow at the start of catalog manager.

---

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/AsyncRootNode.java

https://issues.apache.org/jira/browse/IGNITE-23072
--------

IGNITE-23072 Sql. Fix error on concurrent cursor closing

---

modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/DefaultLogStorageFactory.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/RocksDbSharedLogStorage.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/util/SharedLogStorageFactoryUtils.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/table/src/integrationTest/java/org/apache/ignite/distributed/ReplicasSafeTimePropagationTest.java
modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java

https://issues.apache.org/jira/browse/IGNITE-22960

IGNITE-22960 Set useFsync in DBOptions for DefaultLogStorageFactory

---

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterState.java
modules/system-disaster-recovery-api/src/main/java/org/apache/ignite/internal/disaster/system/message/ResetClusterMessage.java
modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImpl.java
modules/system-disaster-recovery/src/test/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImplTest.java

https://issues.apache.org/jira/browse/IGNITE-23145

IGNITE-23145 Keep initial config after CMG repair

---

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/network/messages/CmgMessageGroup.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListener.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/commands/ChangeMetastorageNodesCommand.java
modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListenerTest.java
modules/system-disaster-recovery/README.md

https://issues.apache.org/jira/browse/IGNITE-22902

IGNITE-22902 Implement command for changing metastorageNodes in CMG

---

modules/catalog-compaction/src/integrationTest/java/org/apache/ignite/internal/catalog/compaction/ItCatalogCompactionTest.java

https://issues.apache.org/jira/browse/IGNITE-23052
-----

IGNITE-23052 Sql. Fix flaky testGlobalMinimumTxBeginTime

---

packaging/db/ignite.java.util.logging.properties

https://issues.apache.org/jira/browse/IGNITE-23143

IGNITE-23143 Node restart should rotate the logs

---

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java
modules/raft-api/src/main/java/org/apache/ignite/internal/raft/RaftManager.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/Loza.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/server/RaftServer.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java
modules/system-disaster-recovery-api/src/main/java/org/apache/ignite/internal/disaster/system/message/MetastorageIndexTermRequestMessage.java

https://issues.apache.org/jira/browse/IGNITE-22900

IGNITE-22900 Implement ability to get MG index+term from node

---

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListener.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/raft/MetaStorageListener.java
modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/ZonePartitionRaftListener.java
modules/raft-api/src/main/java/org/apache/ignite/internal/raft/service/RaftGroupListener.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/ActionRequestProcessor.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java

https://issues.apache.org/jira/browse/IGNITE-22609

IGNITE-22609 Add busy lock to raft group listeners

---

modules/core/src/main/java/org/apache/ignite/internal/hlc/HybridClockImpl.java
modules/core/src/main/java/org/apache/ignite/internal/util/FastTimestamps.java
modules/core/src/test/java/org/apache/ignite/internal/hlc/HybridClockTest.java

https://issues.apache.org/jira/browse/IGNITE-23117

IGNITE-23117 Substitute systemUTC with currentTimeMillis in HybridClockImpl

---

modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/threading/ItComputeApiThreadingTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/AsyncApiOperation.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/ItShutDownServerApiReferencesTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/NoOpJob.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/NoOpMapReduceTask.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/References.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/SyncApiOperation.java
modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofIgnite.java
modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofIgniteCompute.java

https://issues.apache.org/jira/browse/IGNITE-23014

IGNITE-23014 IgniteCompute transparency with respect to node restart

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/SortedIndexLocker.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerIndexLockingTest.java
modules/transactions/src/integrationTest/java/org/apache/ignite/internal/tx/ItTransactionsInsertLockTest.java

https://issues.apache.org/jira/browse/IGNITE-23034

IGNITE-23034 Make sorted index lock match the IEP

---

modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/cluster/status/ClusterStatusCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/cluster/status/ClusterStatusReplCommand.java

https://issues.apache.org/jira/browse/IGNITE-23174

IGNITE-23174 Fix alias for cluster show command

---

packaging/build.gradle
packaging/db/build.gradle

https://issues.apache.org/jira/browse/IGNITE-23173

IGNITE-23173 Distributions should log libraries too

---

modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorageConcurrencyTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorageGcTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorageTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvTableStorageTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbHashIndexStorageTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbSortedIndexStorageTest.java
modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/instance/SharedRocksDbInstanceTest.java

https://issues.apache.org/jira/browse/IGNITE-23189

IGNITE-23189 Increase rocksdb write buffer size in unit tests

---

modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItTransactionRecoveryTest.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/OrphanDetector.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java
modules/transactions/src/test/java/org/apache/ignite/internal/tx/AbstractLockManagerTest.java
modules/transactions/src/test/java/org/apache/ignite/internal/tx/impl/OrphanDetectorTest.java

https://issues.apache.org/jira/browse/IGNITE-22980

IGNITE-22980 Lock manager may fail and lock waiter simultaneously

---

modules/table/src/main/java/org/apache/ignite/internal/table/IndexWrapper.java
modules/table/src/main/java/org/apache/ignite/internal/table/TableImpl.java
modules/table/src/main/java/org/apache/ignite/internal/table/TableViewInternal.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/SortedIndexLocker.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexUtils.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/SortedIndexLockerTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerSortedIndexLockingTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java
modules/transactions/src/integrationTest/java/org/apache/ignite/internal/tx/ItTransactionsInsertLockTest.java

https://issues.apache.org/jira/browse/IGNITE-23191

IGNITE-23191 Pass unique flag into Sorted index

---

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/partitions/reset/ItResetPartitionsCommandTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/partitions/restart/ItRestartPartitionsReplCommandTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/partitions/states/ItPartitionStatesCommandTest.java

https://issues.apache.org/jira/browse/IGNITE-23194

IGNITE-23194 Add missing test for recovery restart repl command

---

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftService.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMaintenanceTest.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetastorageGroupMaintenance.java
modules/raft-api/src/main/java/org/apache/ignite/internal/raft/IndexWithTerm.java
modules/raft-api/src/main/java/org/apache/ignite/internal/raft/service/LeaderWithTerm.java
modules/raft-api/src/test/java/org/apache/ignite/internal/raft/IndexWithTermTest.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/NodeImpl.java
modules/system-disaster-recovery-api/src/main/java/org/apache/ignite/internal/disaster/system/message/BecomeMetastorageLeaderMessage.java
modules/system-disaster-recovery-api/src/main/java/org/apache/ignite/internal/disaster/system/repair/MetastorageRepair.java
modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/MetastorageRepairImpl.java
modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImpl.java
modules/system-disaster-recovery/src/test/java/org/apache/ignite/internal/disaster/system/MetastorageRepairImplTest.java
modules/system-disaster-recovery/src/test/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImplTest.java

https://issues.apache.org/jira/browse/IGNITE-23215

IGNITE-23215 Implement MetastorageRepair

---

modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/raft/ItCmgRaftServiceTest.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListener.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/topology/LogicalTopologyImpl.java
modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListenerTest.java
modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/topology/LogicalTopologyImplTest.java
modules/cluster-management/src/testFixtures/java/org/apache/ignite/internal/cluster/management/MockNode.java
modules/cluster-management/src/testFixtures/java/org/apache/ignite/internal/cluster/management/raft/TestClusterStateStorage.java
modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/distributionzones/ItIgniteDistributionZoneManagerNodeRestartTest.java
modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/BaseDistributionZoneManagerTest.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesAbstractTest.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageWatchTest.java
modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/ItDistributedConfigurationPropertiesTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/storage/ItDistributedConfigurationStorageTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/ClusterIdService.java
modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryStorage.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java

https://issues.apache.org/jira/browse/IGNITE-23223

IGNITE-23223 Obtain clusterId from cluster state in LogicalTopology

---

modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/DefaultLogStorageFactory.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/IgniteJraftServiceFactory.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/RaftGroupService.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/table/build.gradle
modules/table/src/integrationTest/java/org/apache/ignite/internal/ItRaftFsyncOptionTest.java

https://issues.apache.org/jira/browse/IGNITE-23154

IGNITE-23154 Always sync Raft log per append for CMG and Metastorage

---

modules/core/src/main/java/org/apache/ignite/internal/hlc/HybridTimestamp.java
modules/placement-driver-api/src/main/java/org/apache/ignite/internal/placementdriver/message/StopLeaseProlongationMessageResponse.java
modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java
modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java

https://issues.apache.org/jira/browse/IGNITE-23229

IGNITE-23229 Fixed StopLeaseProlongationMessageResponse#deniedLeaseExpirationTime may unbox a null value and cause NPE

---

modules/cli/src/main/java/org/apache/ignite/internal/cli/Main.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/executor/ReplExecutorImpl.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/core/style/component/ErrorUiComponent.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/core/style/component/ErrorUiComponentTest.java

https://issues.apache.org/jira/browse/IGNITE-23091
We need to initialize question factory before executing any command.

IGNITE-23224 Non-REPL connect command fails

---

modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteServerImpl.java
modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItCmgDisasterRecoveryTest.java

https://issues.apache.org/jira/browse/IGNITE-23096

IGNITE-23096 Trigger node stop even when it's restarting

---

modules/replicator/src/testFixtures/java/org/apache/ignite/internal/raft/client/AbstractTopologyAwareGroupServiceTest.java

https://issues.apache.org/jira/browse/IGNITE-23250

IGNITE-23250 Fix ActiveActorTest.testChangeLeaderWhenActualLeft

---

modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/NodeImpl.java

https://issues.apache.org/jira/browse/IGNITE-23238

IGNITE-23238 Prevent closure state reinitialization

---

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java

https://issues.apache.org/jira/browse/IGNITE-23253

IGNITE-23253 Disable ItReplicaLifecycleTest

---

modules/rest-api/build.gradle
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/recovery/system/ResetClusterRequest.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/recovery/system/SystemDisasterRecoveryApi.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/exception/handler/ClusterResetExceptionHandler.java
modules/rest/build.gradle
modules/rest/src/main/java/org/apache/ignite/internal/rest/RestManager.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/recovery/system/SystemDisasterRecoveryController.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/recovery/system/SystemDisasterRecoveryFactory.java
modules/rest/src/test/java/org/apache/ignite/internal/rest/recovery/system/SystemDisasterRecoveryControllerTest.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/system-disaster-recovery-api/src/main/java/org/apache/ignite/internal/disaster/system/exception/ClusterResetException.java
modules/system-disaster-recovery-api/src/main/java/org/apache/ignite/internal/disaster/system/exception/MigrateException.java
modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManager.java
modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImpl.java
modules/system-disaster-recovery/src/test/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImplTest.java

https://issues.apache.org/jira/browse/IGNITE-22805

IGNITE-22805 Implement REST API for initiating CMG repair

---

modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/recovery/system/MigrateRequest.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/recovery/system/SystemDisasterRecoveryApi.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/exception/handler/MigrateExceptionHandler.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/recovery/system/SystemDisasterRecoveryController.java
modules/rest/src/test/java/org/apache/ignite/internal/rest/recovery/system/SystemDisasterRecoveryControllerTest.java

https://issues.apache.org/jira/browse/IGNITE-23107

IGNITE-23107 Add REST API for migrating running nodes missed during CMG repair

---

modules/rest/src/main/java/org/apache/ignite/internal/rest/RestComponent.java

https://issues.apache.org/jira/browse/IGNITE-23273
By default, Micronaut uses a shared ConversionService, so, if we start a few Ignite nodes in the same JVM (like we do in our tests) and then we stop a node, the shared ConversionService gets reset and loses converters still needed for remaining nodes. This commit switches to using one ConversionService instance per Ignite node to avoid this interference.

IGNITE-23273 Use a ConversionService per Ignite node

---

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/cluster/ItResetClusterCommandTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/cluster/ItResetClusterReplCommandTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/cluster/ItResetClusterTest.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/cluster/ResetClusterCall.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/cluster/ResetClusterCallInput.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/reset/ResetPartitionsCallInput.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/Options.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/RecoveryReplCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/cluster/RecoveryClusterCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/cluster/RecoveryClusterReplCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/cluster/reset/ResetClusterCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/cluster/reset/ResetClusterMixin.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/cluster/reset/ResetClusterReplCommand.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/recovery/system/ResetClusterRequest.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/recovery/system/SystemDisasterRecoveryApi.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/recovery/system/SystemDisasterRecoveryController.java
modules/system-disaster-recovery/build.gradle
modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItCmgDisasterRecoveryTest.java
modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItSystemGroupDisasterRecoveryTest.java
modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryClient.java

https://issues.apache.org/jira/browse/IGNITE-22812

IGNITE-22812 Add CLI for initiating CMG repair

---

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/cluster/ItMigrateToClusterCommandTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/cluster/ItResetClusterTest.java
modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/cluster/ItSystemDisasterRecoveryCliTest.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/cluster/MigrateToClusterCall.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/cluster/MigrateToClusterCallInput.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/Options.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/cluster/RecoveryClusterCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/cluster/migrate/MigrateToClusterCommand.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/cluster/migrate/MigrateToClusterMixin.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/cluster/reset/ResetClusterMixin.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/cluster/reset/ResetClusterReplCommand.java
modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/cluster/ClusterState.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/RestManager.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/cluster/ClusterManagementController.java
modules/rest/src/main/java/org/apache/ignite/internal/rest/recovery/system/SystemDisasterRecoveryController.java
modules/rest/src/test/java/org/apache/ignite/internal/rest/RestManagerTest.java
modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItCmgDisasterRecoveryTest.java
modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItSystemGroupDisasterRecoveryTest.java
modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryClient.java

https://issues.apache.org/jira/browse/IGNITE-22879

IGNITE-22879 Add CLI for migrating running nodes to new CMG

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/PartitionScanPublisher.java

IGNITE-23299 Sql. Fix invalid inflight transaction tracking.

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/ApiReferencesTestUtils.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/AsyncApiOperation.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/Pojo.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/PojoKey.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/PojoValue.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/References.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/SyncApiOperation.java
modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofIgnite.java
modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofIgniteCatalog.java
modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofIgniteTables.java

https://issues.apache.org/jira/browse/IGNITE-23015

IGNITE-23015 Support IgniteCatalog transparency with respect to node restart

---

modules/core/src/main/java/org/apache/ignite/internal/lang/IgniteStringBuilder.java
modules/core/src/main/java/org/apache/ignite/internal/util/ByteUtils.java
modules/core/src/test/java/org/apache/ignite/internal/util/ByteUtilsTest.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/StoragePartitionMeta.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/StoragePartitionMetaFactory.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/StoragePartitionMetaIo.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/BlobStorage.java
modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorage.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/StoragePartitionMetaManagerTest.java
modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/StoragePartitionMetaTest.java
modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java

https://issues.apache.org/jira/browse/IGNITE-23197

IGNITE-23197 Store lease holder node ID as 2 longs in MvPartitionStorage implementations

---

modules/metastorage-api/src/main/java/org/apache/ignite/internal/metastorage/MetaStorageCompactionManager.java
modules/metastorage-api/src/main/java/org/apache/ignite/internal/metastorage/MetaStorageManager.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java

https://issues.apache.org/jira/browse/IGNITE-23309

IGNITE-23309 Add interface MetaStorageCompactionManager

---

modules/platforms/cpp/ignite/odbc/diagnostic/diagnostic_record.h
modules/platforms/python/cpp_module/module.cpp
modules/platforms/python/cpp_module/py_cursor.cpp
modules/platforms/python/cpp_module/type_conversion.h
modules/platforms/python/cpp_module/utils.cpp
modules/platforms/python/cpp_module/utils.h
modules/platforms/python/pyignite3/__init__.py
modules/platforms/python/tests/test_connect.py
modules/platforms/python/tests/test_errors.py
modules/platforms/python/tests/util.py

https://issues.apache.org/jira/browse/IGNITE-23218
- Made sure fitting errors are raised in all places in C++ code;
- Added mapping of ODBC errors to DB API errors;
- Added tests.

IGNITE-23218 Better error types

---

modules/platforms/cpp/ignite/odbc/sql_connection.cpp
modules/platforms/python/cpp_module/module.cpp
modules/platforms/python/cpp_module/py_connection.cpp
modules/platforms/python/cpp_module/py_connection.h
modules/platforms/python/cpp_module/py_cursor.cpp
modules/platforms/python/cpp_module/type_conversion.h
modules/platforms/python/pyignite3/__init__.py
modules/platforms/python/tests/conftest.py
modules/platforms/python/tests/test_connect.py
modules/platforms/python/tests/test_fetch_table.py
modules/platforms/python/tests/test_transactions.py

https://issues.apache.org/jira/browse/IGNITE-22740
- Improved documentation;
- Implemented some optional features;
- Implemented transactions;
- Added tests.

IGNITE-22740 DB API Driver 3: Implement Transactions

---

modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/cluster/init/ClusterInitOptions.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/cluster/init/ConfigFileParseException.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/cluster/init/ConfigParseExceptionHandler.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/core/exception/handler/DefaultExceptionHandlers.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/cluster/ClusterInitTest.java

https://issues.apache.org/jira/browse/IGNITE-23209

IGNITE-23209 Improve error message when config file couldn't be parsed

---

packaging/docker/Dockerfile

https://issues.apache.org/jira/browse/IGNITE-23272

IGNITE-23272 Fix docker warnings

---

modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteServerImpl.java
modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryClient.java

https://issues.apache.org/jira/browse/IGNITE-23337
Also, more information is included in thrown exceptions

IGNITE-23337 Increase CLI timeout in ItCmgDisasterRecoveryTest

---

modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofIgniteCatalog.java

https://issues.apache.org/jira/browse/IGNITE-23343

IGNITE-23343 Fix main branch after merge

---

modules/sql-engine/src/integrationTest/sql/function/generic/test_coalesce.test
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/TypeUtils.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/util/TypeUtilsTest.java

https://issues.apache.org/jira/browse/IGNITE-23351
-------

IGNITE-23351 COALESCE detects type wrong if first argument is null

---

modules/api/src/main/java/org/apache/ignite/lang/ErrorGroups.java
modules/index/src/integrationTest/java/org/apache/ignite/internal/index/ItIndexAndIndexStorageDestructionTest.java
modules/platforms/cpp/ignite/client/detail/cluster_connection.cpp
modules/platforms/cpp/ignite/common/error_codes.h
modules/platforms/cpp/ignite/common/ignite_error.h
modules/platforms/cpp/ignite/common/ignite_result.h
modules/platforms/cpp/ignite/network/error_handling_filter.cpp
modules/platforms/cpp/ignite/network/ssl/secure_utils.cpp
modules/platforms/cpp/ignite/odbc/common_types.cpp
modules/platforms/dotnet/Apache.Ignite/ErrorCodes.g.cs
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/StorageClosedException.java
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/StorageDestroyedException.java
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/StorageException.java
modules/storage-api/src/main/java/org/apache/ignite/internal/storage/StorageRebalanceException.java

https://issues.apache.org/jira/browse/IGNITE-22825

IGNITE-22825 Remove non-public storage error codes

---

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/KeyValueStorage.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AbstractCompactionKeyValueStorageTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/BasicOperationsKeyValueStorageTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/RocksDbCompactionKeyValueStorageTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/RocksDbKeyValueStorageTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryCompactionKeyValueStorageTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorageTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/TestRocksDbKeyValueStorageTest.java
modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/AbstractKeyValueStorageTest.java
modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java
modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorageSnapshot.java
modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/ValueSnapshot.java

https://issues.apache.org/jira/browse/IGNITE-23363

IGNITE-23363 Add support for working with snapshots in SimpleInMemoryKeyValueStorage

---

modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngineTest.java
modules/metastorage-api/src/main/java/org/apache/ignite/internal/metastorage/Entry.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/TestMetasStorageUtils.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesVsStorageTest.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageServicePersistenceTest.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageServiceTest.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/server/raft/ItMetaStorageRaftGroupTest.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/EntryImpl.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/KeyValueStorage.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/Value.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksStorageUtils.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/impl/EntryImplTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AndConditionTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/BasicOperationsKeyValueStorageTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/ExistenceConditionTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/OrConditionTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/RevisionConditionTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/TombstoneConditionTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/ValueConditionTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/WatchProcessorTest.java
modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java
modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorageSnapshot.java
modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/ValueSnapshot.java
modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/LeaseTrackerTest.java
modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/LeaseUpdaterTest.java

https://issues.apache.org/jira/browse/IGNITE-23357

IGNITE-23357 Get rid of metastorage Entry#updateCounter

---

modules/rest/src/test/java/org/apache/ignite/internal/rest/configuration/ClusterConfigurationControllerTest.java
modules/rest/src/test/java/org/apache/ignite/internal/rest/configuration/NodeConfigurationControllerTest.java
modules/rest/src/test/java/org/apache/ignite/internal/rest/recovery/system/SystemDisasterRecoveryControllerTest.java

https://issues.apache.org/jira/browse/IGNITE-23371

IGNITE-23371 Disable route filters in tests

---

modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java
modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java

https://issues.apache.org/jira/browse/IGNITE-23339

IGNITE-23339 Fixed StackOverflowError in stop lease prolongation

---

modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItEstimatedSizeTest.java

https://issues.apache.org/jira/browse/IGNITE-23001

IGNITE-23001 Reduce flakiness of ItEstimatedSizeTest

---

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/BasicOperationsKeyValueStorageTest.java
modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java

https://issues.apache.org/jira/browse/IGNITE-23386

IGNITE-23386 Create revision in Metastorage even if removal has no effect

---

modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/LeaseTracker.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java

https://issues.apache.org/jira/browse/IGNITE-23255

IGNITE-23255 Fastest way to use Placement driver for RO transaction

---

modules/metastorage-api/src/main/java/org/apache/ignite/internal/metastorage/MetaStorageManager.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageServiceTest.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/KeyValueStorage.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/raft/MetaStorageListener.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AbstractCompactionKeyValueStorageTest.java
modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java

https://issues.apache.org/jira/browse/IGNITE-23287

IGNITE-23287 Throw CompactedException for getAll metastorage methods

---

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/schema/SchemaSyncServiceImpl.java

https://issues.apache.org/jira/browse/IGNITE-23411

IGNITE-23411 Recover Metastorage SafeTime on Metastorage recovery

---

modules/metastorage-api/src/main/java/org/apache/ignite/internal/metastorage/MetaStorageManager.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/KeyValueStorage.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/KeyValueStorageUtils.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AbstractCompactionKeyValueStorageTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/KeyValueStorageUtilsTest.java
modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java

https://issues.apache.org/jira/browse/IGNITE-23286

IGNITE-23286 Throw CompactedException for get list metastorage methods

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDynamicParameterTest.java

IGNITE-23418 Sql. Fix tests after forbid implicit casts between different type families

---

modules/runner/src/testFixtures/java/org/apache/ignite/internal/testframework/TestIgnitionManager.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/sqllogic/ItSqlLogicTest.java

https://issues.apache.org/jira/browse/IGNITE-23399

IGNITE-23399 Decrease frequency of Metastorage idle SafeTime propagation in tests

---

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/KeyValueStorage.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AbstractCompactionKeyValueStorageTest.java
modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java

https://issues.apache.org/jira/browse/IGNITE-23417

IGNITE-23417 Fix race between compaction and KeyValueStorage#range

---

modules/platforms/cpp/ignite/odbc/sql_connection.cpp
modules/platforms/python/pyignite3/__init__.py
modules/platforms/python/requirements/tests.txt
modules/platforms/python/tests/test_dbapi_compliance.py
modules/platforms/python/tests/test_fetch_table.py

https://issues.apache.org/jira/browse/IGNITE-22744
- Added `dbapi-compliance` test package;
- Implemented `test_dbapi_compliance.py` with `TestPyignite3` test suite;
- Fixed all the encountered issues.

IGNITE-22744 Python Driver add DB API 2 compliance test

---

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/coercion/BaseTypeCheckExecutionTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/coercion/NumericBinaryOperationsExecutionTest.java

IGNITE-23415 NumericBinaryOperationsExecutionTest fails with division by zero

---

modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java

https://issues.apache.org/jira/browse/IGNITE-23453

IGNITE-23453 Enforce proper raft and rocks stop order in ItNodeTest.

---

modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/MetastorageRepairImpl.java
modules/system-disaster-recovery/src/test/java/org/apache/ignite/internal/disaster/system/MetastorageRepairImplTest.java

https://issues.apache.org/jira/browse/IGNITE-23462

IGNITE-23462 Also listen for node join when waiting for nodes doing MG repair

---

modules/metastorage-api/src/main/java/org/apache/ignite/internal/metastorage/MetaStorageCompactionManager.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageSafeTimePropagationRocksDbTest.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageSafeTimePropagationSimpleStorageTest.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/KeyValueStorage.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AbstractCompactionKeyValueStorageTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/RocksDbCompactionKeyValueStorageTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/RocksDbKeyValueStorageTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryCompactionKeyValueStorageTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorageTest.java
modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/AbstractKeyValueStorageTest.java
modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java
modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorageSnapshot.java

https://issues.apache.org/jira/browse/IGNITE-23419

IGNITE-23419 Advance Safe Time in KeyValueStorage#saveCompactionRevision

---

modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationManager.java
modules/network-api/src/main/java/org/apache/ignite/internal/network/ClusterService.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItNoThreadsLeftTest.java
modules/vault/src/main/java/org/apache/ignite/internal/vault/VaultManager.java

https://issues.apache.org/jira/browse/IGNITE-23471

IGNITE-23471 Remove outdated todos

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/DisasterRecoveryManager.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/DisasterRecoveryRequest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/DisasterRecoveryRequestSerializer.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/DisasterRecoveryRequestsSerialization.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/ManualGroupRestartRequest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/ManualGroupRestartRequestSerializer.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/ManualGroupUpdateRequest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/ManualGroupUpdateRequestSerializer.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/disaster/DisasterRecoveryRequestSerializerTest.java

https://issues.apache.org/jira/browse/IGNITE-23470

IGNITE-23470 Do not use ByteUtils#toBytes to persist disaster recovery requests

---

modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationConverter.java
modules/configuration/src/main/java/org/apache/ignite/internal/configuration/hocon/HoconConverter.java
modules/configuration/src/main/java/org/apache/ignite/internal/configuration/util/ConfigurationUtil.java

https://issues.apache.org/jira/browse/IGNITE-23482

IGNITE-23482 Widen types in Configuration API

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexMeta.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexMetaSerializer.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexMetaStorage.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/MetaIndexStatus.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/MetaIndexStatusChange.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/index/BaseIndexMetaStorageTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/index/IndexMetaSerializerTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/index/MetaIndexStatusTest.java

https://issues.apache.org/jira/browse/IGNITE-23473

IGNITE-23473 Do not use ByteUtils#toBytes to persist IndexMeta

---

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/CliCommandTestNotInitializedIntegrationBase.java
modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/ItPrimaryReplicaChoiceTest.java
modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/authentication/ItAuthenticationTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/ItClusterTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteStopLogMessagesTest.java
modules/runner/src/testFixtures/java/org/apache/ignite/internal/Cluster.java
modules/runner/src/testFixtures/java/org/apache/ignite/internal/ClusterPerClassIntegrationTest.java
modules/runner/src/testFixtures/java/org/apache/ignite/internal/ClusterPerTestIntegrationTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItIndexesSystemViewTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSystemViewsTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItZonesSystemViewTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoverySystemViewTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItCriteriaQueryTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItOperationRetryTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItTransactionPrimaryChangeTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItTransactionRecoveryTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItTxResourcesVacuumTest.java

* Nullify the list of nodes after calling `Cluster#shutdown`
* Use threadsafe collections where necessary
* Cleanup usages of starting and stoppng a cluster
https://issues.apache.org/jira/browse/IGNITE-23491
\- The pull request title is treated as the final commit message. The following pattern must be used: IGNITE-XXXX Change summary where XXXX - …

IGNITE-23491 Fix various issues with the Cluster class

---

modules/platforms/build.gradle

https://issues.apache.org/jira/browse/IGNITE-23500

IGNITE-23500 Fix odbc driver file version

---

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/BaseSqlMultiStatementTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/AsyncRootNode.java

https://issues.apache.org/jira/browse/IGNITE-23480
---------

IGNITE-23480 Sql. Add debug output to investigate flakiness of basicMultiStatementQuery test

---

modules/configuration-api/src/main/java/org/apache/ignite/configuration/validation/CamelCaseKeys.java
modules/configuration/src/main/java/org/apache/ignite/internal/configuration/validation/CamelCaseKeysValidator.java
modules/configuration/src/main/java/org/apache/ignite/internal/configuration/validation/ConfigurationValidatorImpl.java
modules/configuration/src/test/java/org/apache/ignite/internal/configuration/validation/CamelCaseKeysValidatorTest.java
modules/configuration/src/testFixtures/java/org/apache/ignite/internal/configuration/validation/TestValidationUtil.java
modules/runner/src/main/java/org/apache/ignite/internal/configuration/SystemDistributedConfigurationSchema.java
modules/runner/src/main/java/org/apache/ignite/internal/configuration/SystemDistributedExtensionConfigurationSchema.java
modules/runner/src/main/java/org/apache/ignite/internal/configuration/SystemLocalConfigurationSchema.java
modules/runner/src/main/java/org/apache/ignite/internal/configuration/SystemPropertyConfigurationSchema.java

https://issues.apache.org/jira/browse/IGNITE-23504

IGNITE-23504 Add configuration of local and distributed system properties

---

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/TableScanNodeExecutionTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItColocationTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerRecoveryTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/storage/InternalTableEstimatedSizeTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImplTest.java
modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java
modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java

https://issues.apache.org/jira/browse/IGNITE-23524

IGNITE-23524 Remove clock in favour of clockService in TableManager

---

modules/platforms/python/tests/test_fetch_parameters.py
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlApiBaseTest.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDynamicParameterTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/TypeUtils.java
modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/engine/util/SqlTestUtils.java

https://issues.apache.org/jira/browse/IGNITE-23214

IGNITE-23214 Valid error for unsupported types for dynamic parameters

---

docs/_docs/developers-guide/java-to-tables.adoc
docs/_docs/sql-reference/distribution-zones.adoc
docs/_docs/sql-reference/grammar-reference.adoc
modules/storage-api/README.md

IGNITE-21563 Replace ENGINE based approach by STORAGE_PROFILES in docs

---

modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/recovery/system/ResetClusterRequest.java
modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManager.java

https://issues.apache.org/jira/browse/IGNITE-23531

IGNITE-23531 Proofread REST API for disaster recovery

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTableScanTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/PartitionScanPublisher.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/storage/PartitionScanPublisherTest.java

* Linearize Subscriber requests
* Linearize Subscriber callback invocations
* Fix minor Flow contact violations
https://issues.apache.org/jira/browse/IGNITE-23536 …

IGNITE-23536 Fix PartitionScanPublisher

---

modules/raft/src/integrationTest/java/org/apache/ignite/internal/raft/ItLozaTest.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/DefaultLogStorageFactory.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/RocksDbSharedLogStorage.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/RocksDbSharedLogStorageUtils.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/RocksDbSpillout.java
modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/VolatileLogStorageFactory.java

https://issues.apache.org/jira/browse/IGNITE-23530

IGNITE-23530 Do not include node name in Raft group identifier in storages

---

modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/cluster/ResetClusterCall.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/cluster/ResetClusterCallInput.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/Options.java
modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/cluster/reset/ResetClusterMixin.java
modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/recovery/cluster/reset/ResetClusterCommandTest.java
modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItCmgDisasterRecoveryTest.java
modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItMetastorageGroupDisasterRecoveryTest.java
modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryClient.java

https://issues.apache.org/jira/browse/IGNITE-22897

IGNITE-22897 CLI for initiating MG repair

---

modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItIdempotentCommandCacheTest.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/raft/CommandResultAndTimestamp.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/raft/MetaStorageListener.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/raft/MetaStorageWriteHandler.java
modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java

https://issues.apache.org/jira/browse/IGNITE-23546

IGNITE-23546 Fix long handling of EvictIdempotentCommandsCacheCommand

---

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java

JIRA Ticket: [IGNITE-23538](https://issues.apache.org/jira/browse/IGNITE-23538)
The main goal is to fix and enable the corresponding `ItRebalanceDistributedTest` test class.
`ItRebalanceDistributedTest` contains critical tests that cover all rebalance logic inside so it must be enabled ASAP.
The main issue was that we didn't wait untill we join the cluster. So, the corresponding compose stage on `cmgManager#joinFuture` is added in this PR. 
Also I made a small refactoring on `startComponentsAsync` (now it works with array of components argument) and propagate the same changes to `ItReplicaLifecycleTest`. The last is disabled, but there is the identical node starting process and when we'll return to [IGNITE-23252](https://issues.apache.org/jira/browse/IGNITE-23252) it's important do not …

IGNITE-23538 Fix ItRebalanceDistributedTest after Metastorage started requiring cluster state on start

---

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/WatchProcessor.java

https://issues.apache.org/jira/browse/IGNITE-23553

IGNITE-23553 Only notify FailureHandler about first watch notification failure

---

modules/platforms/build.gradle
packaging/build.gradle
packaging/cli/build.gradle
packaging/client/cpp/build.gradle
packaging/client/dotnet/build.gradle
packaging/client/java/build.gradle
packaging/db/build.gradle

https://issues.apache.org/jira/browse/IGNITE-23570

IGNITE-23570 Improve tasks dependencies

---

modules/api/src/main/java/org/apache/ignite/catalog/ColumnType.java
modules/catalog-dsl/src/integrationTest/java/org/apache/ignite/internal/catalog/AllColumnTypesPojo.java
modules/catalog-dsl/src/integrationTest/java/org/apache/ignite/internal/catalog/ItCatalogDslTest.java
modules/catalog-dsl/src/test/java/org/apache/ignite/internal/catalog/sql/CreateFromAnnotationsTest.java

* Fix SQL to Java type mapping in Catalog API
* Add tests for all supported column types

IGNITE-23268 Fix Catalog API temporal type mapping

---

modules/platforms/build.gradle

https://issues.apache.org/jira/browse/IGNITE-23576

IGNITE-23576 Fix :packaging-odbc:distZip

---

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java
modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTableScanTest.java
modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItPartitionStoragesTest.java
modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItTxResourcesVacuumTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/PartitionSet.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerRecoveryTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java

https://issues.apache.org/jira/browse/IGNITE-19713

IGNITE-19713 Start partition storages only for locally assigned partitions

---

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java
modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/ColumnFamily.java

https://issues.apache.org/jira/browse/IGNITE-23567

IGNITE-23567 Store Metastorage checksums durably

---

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/cluster/ItSystemDisasterRecoveryCliTest.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteServerImpl.java
modules/runner/src/testFixtures/java/org/apache/ignite/internal/Cluster.java
modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItCmgDisasterRecoveryTest.java
modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItMetastorageGroupDisasterRecoveryTest.java
modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItSystemGroupDisasterRecoveryTest.java

https://issues.apache.org/jira/browse/IGNITE-23579

IGNITE-23579 Improve diagnostics of CMG/MG disaster recovery

---

modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/matchers/CompletableFutureExceptionMatcher.java
modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItMetastorageGroupDisasterRecoveryTest.java

https://issues.apache.org/jira/browse/IGNITE-23581
* Make sure Metastorage does not diverge in this test (it's an unrelated matter)
* Include stack trace info in a failed assertion description

IGNITE-23581 Fix ItMetastorageGroupDisasterRecoveryTest#oldMgLeaderDoesNotHijackLeadership()

---

DEVNOTES.md

https://issues.apache.org/jira/browse/IGNITE-23586

IGNITE-23586 Update DEVNOTES.md according to current CLI implementation

---

modules/core/src/main/java/org/apache/ignite/internal/hlc/HybridTimestamp.java
modules/core/src/main/java/org/apache/ignite/internal/util/GridUnsafe.java
modules/core/src/test/java/org/apache/ignite/internal/hlc/HybridTimestampTest.java
modules/partition-distribution/src/main/java/org/apache/ignite/internal/partitiondistribution/AssignmentsSerializer.java
modules/partition-distribution/src/test/java/org/apache/ignite/internal/partitiondistribution/AssignmentsSerializerTest.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/ManualGroupRestartRequestSerializer.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexMetaSerializer.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/disaster/DisasterRecoveryRequestSerializerTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/index/IndexMetaSerializerTest.java
modules/transactions/src/main/java/org/apache/ignite/internal/tx/TxMetaSerializer.java
modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxMetaSerializerTest.java

https://issues.apache.org/jira/browse/IGNITE-23583

IGNITE-23583 Optimize HybridTimestamp serialization

---

modules/core/src/main/java/org/apache/ignite/internal/hlc/HybridTimestamp.java
modules/core/src/main/java/org/apache/ignite/internal/util/ByteUtils.java
modules/core/src/main/java/org/apache/ignite/internal/util/VarIntUtils.java
modules/core/src/test/java/org/apache/ignite/internal/hlc/HybridTimestampTest.java

https://issues.apache.org/jira/browse/IGNITE-23592

IGNITE-23592 Align serialization methods of HybridTimestamp

---

modules/catalog-compaction/src/test/java/org/apache/ignite/internal/catalog/compaction/AbstractCatalogCompactionTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerRecoveryTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/storage/UpdateLogImplTest.java
modules/catalog/src/testFixtures/java/org/apache/ignite/internal/catalog/BaseCatalogManagerTest.java
modules/catalog/src/testFixtures/java/org/apache/ignite/internal/catalog/CatalogTestUtils.java
modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java
modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/BaseDistributionZoneManagerTest.java
modules/index/src/test/java/org/apache/ignite/internal/index/ChangeIndexStatusTaskTest.java
modules/index/src/test/java/org/apache/ignite/internal/index/IndexAvailabilityControllerRestorerTest.java
modules/index/src/test/java/org/apache/ignite/internal/index/IndexAvailabilityControllerTest.java
modules/index/src/test/java/org/apache/ignite/internal/index/IndexManagerTest.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageManagerImplTest.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/RecoveryRevisionsListenerImpl.java
modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/index/BaseIndexMetaStorageTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/index/IndexMetaStorageRecoveryTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/FullStateTransferIndexChooserTest.java

https://issues.apache.org/jira/browse/IGNITE-23596

IGNITE-23596 Start of Metastorage Raft node blocks a network thread

---

modules/network-api/src/main/java/org/apache/ignite/internal/network/NetworkMessage.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/WriteActionRequest.java
modules/raft/src/test/java/org/apache/ignite/raft/jraft/rpc/WriteActionRequestTest.java

https://issues.apache.org/jira/browse/IGNITE-23610

IGNITE-23610 Log WriteCommand class when logging about long WriteActionRequest processing

---

packaging/docker/Dockerfile

https://issues.apache.org/jira/browse/IGNITE-23614

IGNITE-23614 Declare IGNITE3_EXTRA_JVM_ARGS as an ENV variable in Dockerfile

---

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/RecoveryRevisionsListenerImpl.java

https://issues.apache.org/jira/browse/IGNITE-23618

IGNITE-23618 Fix dead lock when restoring metastorage

---

modules/api/src/main/java/org/apache/ignite/catalog/annotations/Zone.java
modules/api/src/main/java/org/apache/ignite/catalog/definitions/ZoneDefinition.java
modules/catalog-dsl/src/integrationTest/java/org/apache/ignite/internal/catalog/ItCatalogDslTest.java
modules/catalog-dsl/src/integrationTest/java/org/apache/ignite/internal/matcher/ZoneDefinitionMatcher.java
modules/catalog-dsl/src/main/java/org/apache/ignite/internal/catalog/sql/CreateFromAnnotationsImpl.java
modules/catalog-dsl/src/main/java/org/apache/ignite/internal/catalog/sql/CreateFromDefinitionImpl.java
modules/catalog-dsl/src/main/java/org/apache/ignite/internal/catalog/sql/CreateZoneImpl.java
modules/catalog-dsl/src/main/java/org/apache/ignite/internal/catalog/sql/IgniteCatalogSqlImpl.java
modules/catalog-dsl/src/main/java/org/apache/ignite/internal/catalog/sql/Option.java
modules/catalog-dsl/src/test/java/org/apache/ignite/internal/catalog/sql/CreateFromAnnotationsTest.java
modules/catalog-dsl/src/test/java/org/apache/ignite/internal/catalog/sql/CreateFromDefinitionTest.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogParamsValidationUtils.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AlterZoneCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CatalogUtils.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateZoneCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateZoneCommandBuilder.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/RenameZoneCommand.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogZoneDescriptor.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/ConsistencyMode.java
modules/catalog/src/main/java/org/apache/ignite/internal/catalog/systemviews/ZonesSystemViewProvider.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AbstractCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/CreateZoneCommandValidationTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/descriptors/CatalogZoneDescriptorTest.java
modules/catalog/src/test/java/org/apache/ignite/internal/catalog/storage/CatalogEntrySerializationTest.java
modules/client-handler/src/testFixtures/java/org/apache/ignite/client/handler/FakeCatalogService.java
modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItZonesSystemViewTest.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/ddl/DdlSqlToCommandConverter.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/ddl/ZoneOptionEnum.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/prepare/ddl/DistributionZoneSqlToCommandConverterTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/DistributionZoneSqlDdlParserTest.java

https://issues.apache.org/jira/browse/IGNITE-23449

IGNITE-23449 Add support of the new flag HA in zone description

---

modules/network/src/main/java/org/apache/ignite/internal/network/netty/OutboundEncoder.java

https://issues.apache.org/jira/browse/IGNITE-23631

IGNITE-23631 Optimize NetworkMessageChunkedInput constructor

---

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItSchemaChangeKvViewTest.java

https://issues.apache.org/jira/browse/IGNITE-23644

IGNITE-23644 Unmute testDropColumn and testMergeChangesAddDropAdd in ItSchemaChangeKvViewTest

---

modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java

https://issues.apache.org/jira/browse/IGNITE-23616

IGNITE-23616 Found a performance drop in Ignite benchmarks

---

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java

https://issues.apache.org/jira/browse/IGNITE-23643

IGNITE-23643 Improve logging on ClusterManagementGroupManager startup

---

modules/runner/src/main/java/org/apache/ignite/internal/app/LifecycleManager.java
modules/runner/src/test/java/org/apache/ignite/internal/app/LifecycleManagerTest.java

https://issues.apache.org/jira/browse/IGNITE-23652

IGNITE-23652 Don't swallow component stop exception

---

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionContext.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestClusterTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestNode.java

https://issues.apache.org/jira/browse/IGNITE-23317

IGNITE-23317 Sql. Added additional dynamic parameters validation for internal testing

---

modules/replicator/src/main/java/org/apache/ignite/internal/raft/client/TopologyAwareRaftGroupService.java

https://issues.apache.org/jira/browse/IGNITE-23649

IGNITE-23649 Check whether leader host is null within refreshAndGetLeaderWithTerm.

---

modules/platforms/cpp/ignite/common/big_integer.cpp
modules/platforms/cpp/ignite/common/bignum_test.cpp
modules/platforms/cpp/ignite/common/detail/mpi.cpp
modules/platforms/cpp/ignite/common/detail/mpi.h

https://issues.apache.org/jira/browse/IGNITE-23638

IGNITE-23638 Remove unnecessary shrink calls in the big_number C++ implementation

---

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java

https://issues.apache.org/jira/browse/IGNITE-23659

IGNITE-23659 Remove dubious sneakyThrow usages

---

modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/distributionzones/ItIgniteDistributionZoneManagerNodeRestartTest.java

https://issues.apache.org/jira/browse/IGNITE-23662

IGNITE-23662 Mute several flaky tests in ItIgniteDistributionZoneManagerNodeRestartTest

---

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java

https://issues.apache.org/jira/browse/IGNITE-23664

IGNITE-23664 Simplify working with locks in PartitionReplicaLifecycleManager

---

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/fsm/Query.java
modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/tx/ScriptTransactionContext.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/benchmarks/SqlBenchmark.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/TransactionEnlistTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/coercion/BaseTypeCheckExecutionTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/ClusterServiceFactory.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/NoOpTransaction.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/NoOpTransactionTracker.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestBuilders.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestCluster.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestClusterTest.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestNode.java
modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/util/QueryCheckerTest.java

https://issues.apache.org/jira/browse/IGNITE-23663
----------

IGNITE-23663 Sql. Make TestNode to use QueryExecutor

---

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java

https://issues.apache.org/jira/browse/IGNITE-23668

IGNITE-23668 Fix ItReplicaLifecycleTest class cast exception

---

modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngineTest.java
modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtilUpdateAssignmentsTest.java
modules/metastorage-api/src/main/java/org/apache/ignite/internal/metastorage/server/time/ClusterTime.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesAbstractTest.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesVsStorageTest.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageServicePersistenceTest.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageServiceTest.java
modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/server/raft/ItMetaStorageRaftGroupTest.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageServiceImpl.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/raft/MetaStorageListener.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/raft/MetaStorageWriteHandler.java
modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/time/ClusterTimeImpl.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/impl/IdempotentCommandCacheTest.java
modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/time/ClusterTimeTest.java
modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/impl/StandaloneMetaStorageManager.java
modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/PlacementDriverTest.java

https://issues.apache.org/jira/browse/IGNITE-23672

IGNITE-23672 Remove ClusterTime#now()

---

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/PartitionReplicationMessageGroup.java
modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/raft/PartitionSnapshotMeta.java
modules/raft/src/main/java/org/apache/ignite/raft/jraft/entity/RaftOutter.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotCopier.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotReader.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/outgoing/OutgoingSnapshot.java
modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/outgoing/SnapshotMetaUtils.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotReaderTest.java
modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/outgoing/SnapshotMetaUtilsTest.java
modules/workers/src/integrationTest/java/org/apache/ignite/internal/worker/ItCriticalWorkerMonitoringTest.java

https://issues.apache.org/jira/browse/IGNITE-23385

IGNITE-23385 Move fields added to SnapshotMeta from JRaft to our own message
