apache/ignite-3

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java
https://issues.apache.org/jira/browse/IGNITE-23669
=> IGNITE-23669 Add missing busy locks to ClusterManagementGroupManager

modules/table/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java
https://issues.apache.org/jira/browse/IGNITE-23691
=> IGNITE-23691 Disable ItTableRaftSnapshotsTest.txSemanticsIsMaintained

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/Checkpointer.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/compaction/Compactor.java
https://issues.apache.org/jira/browse/IGNITE-23697
=> IGNITE-23697 Fix negative pin avgWriteSpeed in message Checkpoint finished

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/disaster/LocalPartitionStateMessage.java, modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/recovery/LocalPartitionStateResponse.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/recovery/ItDisasterRecoveryControllerTest.java, modules/rest/src/main/java/org/apache/ignite/internal/rest/recovery/DisasterRecoveryController.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoverySystemViewTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/DisasterRecoveryManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/DisasterRecoverySystemViews.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/LocalPartitionState.java
https://issues.apache.org/jira/browse/IGNITE-22940
=> IGNITE-22940 Expose partition size to public API

modules/replicator/src/testFixtures/java/org/apache/ignite/internal/raft/client/AbstractTopologyAwareGroupServiceTest.java
https://issues.apache.org/jira/browse/IGNITE-23700
=> IGNITE-23700 Fix NPE in AbstractTopologyAwareGroupServiceTest

.idea/codeStyles/Project.xml, modules/network-api/src/main/java/org/apache/ignite/internal/network/NetworkMessage.java, modules/network/src/main/java/org/apache/ignite/internal/network/message/ScaleCubeMessage.java
https://issues.apache.org/jira/browse/IGNITE-23718
=> IGNITE-23718 Improve logging for ScaleCubeMessage

modules/network/src/main/java/org/apache/ignite/internal/network/netty/NettyServer.java
https://issues.apache.org/jira/browse/IGNITE-23711
=> IGNITE-23711 Add missing synchronization in NettyServer

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImplTest.java
=> IGNITE-23706 Sql. Fix flaky testCursorIsClosedAfterAllDataReadWithNodeFailure

modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/ReplicatorGroupImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/AbstractClientService.java
https://issues.apache.org/jira/browse/IGNITE-23395
=> IGNITE-23395 Fixed Raft subsystem spams to log with network exceptions

.gitignore, modules/platforms/cpp/.gitignore, modules/platforms/cpp/ignite/odbc/CMakeLists.txt, modules/platforms/cpp/ignite/odbc/version.rc.in
Added metainfo to the resulting ODBC dll library.
=> IGNITE-22660 Add meta info to ODBC dll

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogHashIndexDescriptor.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogSchemaDescriptor.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogSortedIndexDescriptor.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogSystemViewDescriptor.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogTableColumnDescriptor.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogTableDescriptor.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogTableSchemaVersions.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogZoneDescriptor.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/AlterColumnEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/DropColumnsEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/DropIndexEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/DropTableEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/DropZoneEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/MakeIndexAvailableEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/NewColumnsEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/ObjectIdGenUpdateEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/RemoveIndexEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/RenameIndexEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/RenameTableEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/SetDefaultZoneEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/SnapshotEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/StartBuildingIndexEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/VersionedUpdate.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/serialization/CatalogSerializationUtils.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/storage/UpdateLogImplTest.java
https://issues.apache.org/jira/browse/IGNITE-23630
=> IGNITE-23630 Store catalog object IDs as varints

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerRecoveryTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbSharedStorage.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/rocksdb/RocksDbTxStateStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-23767
=> IGNITE-23767 Use shared threadpools in RocksDbFlusher for TxStateRocksDbSharedStorage

modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImpl.java, modules/system-disaster-recovery/src/test/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImplTest.java
https://issues.apache.org/jira/browse/IGNITE-23768
=> IGNITE-23768 Prohibit migration from repaired cluster to old one

modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/PlacementDriverNodesOperabilityTest.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/PlacementDriverManager.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/LeaseNegotiationTest.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/LeaseUpdaterTest.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/Cluster.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/ClusterPerClassIntegrationTest.java
https://issues.apache.org/jira/browse/IGNITE-23245
=> IGNITE-23245 Fixed Placement driver returns assignments only in MS nodes

check-rules/spotbugs-excludes.xml, modules/core/src/main/java/org/apache/ignite/internal/replicator/TablePartitionId.java, modules/core/src/main/java/org/apache/ignite/internal/replicator/ZonePartitionId.java, modules/core/src/main/java/org/apache/ignite/internal/util/StringUtils.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZonesUtil.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngine.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtil.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/ZoneRebalanceUtil.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/causalitydatanodes/DistributionZoneCausalityDataNodesTest.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/AssignmentsTracker.java, modules/runner/src/main/java/org/apache/ignite/internal/configuration/storage/DistributedConfigurationStorage.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-23770
=> IGNITE-23770 Introduce a method to extract ReplicationGroupId from Meta Storage keys

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/DataStorageModule.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/DataStorageModules.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/DataStorageModulesTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestDataStorageModule.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryDataStorageModule.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryDataStorageModule.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbDataStorageModule.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageEngine.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorageConcurrencyTest.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorageGcTest.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorageTest.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvTableStorageTest.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/benchmarks/CommitManyWritesBenchmark.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/engine/RocksDbStorageEngineTest.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbHashIndexStorageTest.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbSortedIndexStorageTest.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/instance/SharedRocksDbInstanceTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerRecoveryTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/gc/RocksDbGcUpdateHandlerTest.java
https://issues.apache.org/jira/browse/IGNITE-23774
=> IGNITE-23774 Use shared threadpools in RocksDbFlusher for SharedRocksDbInstance

modules/sql-engine/build.gradle, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/sqllogic/ItSqlLogic2Test.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/sqllogic/ItSqlLogic3Test.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/sqllogic/ItSqlLogicTest.java
=> IGNITE-23800 Fix SqlLogicTest gradle configuration

modules/placement-driver/build.gradle, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/AssignmentsTracker.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/ActiveActorTest.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/LeaseUpdaterTest.java
https://issues.apache.org/jira/browse/IGNITE-23771
=> IGNITE-23771 Remove intermediate conversion to string in AssignmentsTracker

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItReadOnlyTransactionTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-23787
=> IGNITE-23787 Implicit get for embedded mode starts RW transaction

modules/core/src/main/java/org/apache/ignite/internal/hlc/ClockWaiter.java
https://issues.apache.org/jira/browse/IGNITE-23811
=> IGNITE-23811 Get rid of ClockWaiter#busyLock

modules/catalog-compaction/src/test/java/org/apache/ignite/internal/catalog/compaction/AbstractCatalogCompactionTest.java, modules/catalog/src/testFixtures/java/org/apache/ignite/internal/catalog/BaseCatalogManagerTest.java, modules/catalog/src/testFixtures/java/org/apache/ignite/internal/catalog/CatalogTestUtils.java, modules/core/src/main/java/org/apache/ignite/internal/hlc/ClockWaiter.java, modules/core/src/test/java/org/apache/ignite/internal/hlc/ClockWaiterTest.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/distributionzones/ItIgniteDistributionZoneManagerNodeRestartTest.java, modules/index/src/test/java/org/apache/ignite/internal/index/ChangeIndexStatusTaskTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItIdempotentCommandCacheTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ddl/DdlCommandHandlerExceptionHandlingTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestBuilders.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestCluster.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/storage/InternalTableEstimatedSizeTest.java, modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java
https://issues.apache.org/jira/browse/IGNITE-23814
=> IGNITE-23814 Replace with ThreadPoolsManager#commonScheduler in ClockWaiter#scheduler

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointMetricsTracker.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointWorkflow.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/Checkpointer.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/Duration.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointMetricsTrackerTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointWorkflowTest.java
https://issues.apache.org/jira/browse/IGNITE-23819
=> IGNITE-23819 Fix the time output in "Checkpoint finished"

modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/cluster/init/ClusterInitOptions.java
https://issues.apache.org/jira/browse/IGNITE-23829
=> IGNITE-23829 Fix --config={} in cluster init

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/KeyValueGetPlan.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/KeyValueModifyPlan.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/SelectCountPlan.java
https://issues.apache.org/jira/browse/IGNITE-23682
Results on MBP M3 as follow:
```
Before
Benchmark               (clusterSize)  (fsync)  Mode  Cnt  Score   Error  Units
SelectBenchmark.kvGet               1    false  avgt   20  3.025 ± 0.126  us/op
SelectBenchmark.sqlGet              1    false  avgt   20  8.652 ± 0.142  us/op
After
Benchmark               (clusterSize)  (fsync)  Mode  Cnt  Score   Error  Units
SelectBenchmark.sqlGet              1    false  avgt   20  5.872 ± 0.098  us/op
Before
Benchmark                          (clusterSize)  (fsync)  (partitionCount)  (replicaCount)  Mode  Cnt   Score   Error  Units
InsertBenchmark.kvInsert                       1    false                24               1  avgt   20  38.814 ± 9.475  us/op
InsertBenchmark.sqlPreparedInsert …
```
=> IGNITE-23682 Sql. Avoid unnecessary task scheduling for simple plan

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/mapping/ExecutionDistributionProviderImpl.java
https://issues.apache.org/jira/browse/IGNITE-23795
-----------------
=> IGNITE-23795 Sql. Remove work around code from ExecutionDistributionProviderImpl

modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientBinaryTupleUtils.java, modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ClientComputeJobUnpacker.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/ComputeUtils.java, modules/platforms/cpp/ignite/client/detail/compute/compute_impl.cpp
https://issues.apache.org/jira/browse/IGNITE-23878
=> IGNITE-23878 Prevent intermediate serialization when passing native type

modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTable.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/client/ItClientGetTableSchemaTest.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/test/WatchListenerInhibitor.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/SchemaManager.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/catalog/CatalogToSchemaDescriptorConverter.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/SchemaManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-23871
=> IGNITE-23871 Do not fail in SchemaRegistry#schemaAsync(int) when requested version is not yet known

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/WatchProcessor.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-23675
=> IGNITE-23675 Add logging to WatchProcessor#notifyWatches:notificationFuture

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/MetastorageChecksum.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/MetastorageChecksumTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/RocksDbKeyValueStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-23907
=> IGNITE-23907 Make revision checksum calculation for idempotent command cache eviction command deterministic

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java
https://issues.apache.org/jira/browse/IGNITE-23908
=> IGNITE-23908 Do not fsync Metastorage revision checksum writes

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/WatchProcessor.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/raft/MetaStorageWriteHandler.java
* updateCompactionRevision and updateOnlyRevision used to always trigger the Failure Handler;
* remove inefficient byte array manipulations
https://issues.apache.org/jira/browse/IGNITE-23906 …
=> IGNITE-23906 Minor fixes in WatchProcessor

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/Member.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/Replica.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaImpl.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ZonePartitionReplicaImpl.java
https://issues.apache.org/jira/browse/IGNITE-23900
=> IGNITE-23900 Add createSnapshot and transferLeadership methods to Replica

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItDataSchemaSyncTest.java
https://issues.apache.org/jira/browse/IGNITE-23928
=> IGNITE-23928 Disable ItDataSchemaSyncTest.checkSchemasCorrectlyRestore

modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/instance/SharedRocksDbInstanceCreator.java
https://issues.apache.org/jira/browse/IGNITE-23933
=> IGNITE-23933 Disable flushing to disk on stop for RocksDB-based partition storage

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtil.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/ZoneRebalanceUtil.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtilUpdateAssignmentsTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/GroupUpdateRequest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/disaster/DisasterRecoveryMsInvokeTest.java
https://issues.apache.org/jira/browse/IGNITE-23776
=> IGNITE-23776 pendingChangeTriggerKey is updated even if rebalance is skipped

modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItComputeBaseTest.java, modules/compute/src/jobs/java/org/apache/ignite/internal/compute/FailingJobOnFirstExecution.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/ComputeComponent.java, modules/compute/src/test/java/org/apache/ignite/internal/compute/ComputeComponentImplTest.java
https://issues.apache.org/jira/browse/IGNITE-23917
=> IGNITE-23917 Remote execution doesn't use options

modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbSharedStorage.java
https://issues.apache.org/jira/browse/IGNITE-23943
=> IGNITE-23943 Disable flushing to disk on stop for tx state storage

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/WatchProcessor.java
https://issues.apache.org/jira/browse/IGNITE-23955
=> IGNITE-23955 Improve logging in WatchProcessor

modules/client/src/test/java/org/apache/ignite/client/fakes/FakeInternalTable.java, modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItWorkerShutdownTest.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/IgniteComputeImpl.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/NextColocatedWorkerSelector.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryReconfigurationTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItColocationTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/InternalTable.java, modules/table/src/main/java/org/apache/ignite/internal/table/TableImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/TableViewInternal.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/partition/HashPartitionManagerImpl.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/TxAbstractTest.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-23950
=> IGNITE-23950 Remove InternalTable#partition()

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/UpdateLogImpl.java, modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/metastore/ClusterStatusWatchListener.java, modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/metastore/NodeStatusWatchListener.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngine.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngineV2.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/causalitydatanodes/DistributionZoneCausalityDataNodesTest.java, modules/index/src/main/java/org/apache/ignite/internal/index/IndexAvailabilityController.java, modules/metastorage-api/src/main/java/org/apache/ignite/internal/metastorage/WatchListener.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageCompactionTriggerTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageManagerImplTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesVsStorageTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageSafeTimePropagationAbstractTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageWatchTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/Watch.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/WatchProcessor.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AbstractCompactionKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/BasicOperationsKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/WatchProcessorTest.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/AssignmentsTracker.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/LeaseTracker.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/configuration/storage/DistributedConfigurationStorage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/DisasterRecoveryManager.java
https://issues.apache.org/jira/browse/IGNITE-23962
=> IGNITE-23962 Remove WatchListener#onError method

modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java
https://issues.apache.org/jira/browse/IGNITE-23964
=> IGNITE-23964 Fix race on snapshot init

modules/api/src/main/java/org/apache/ignite/table/Tuple.java, modules/api/src/main/java/org/apache/ignite/table/TupleImpl.java, modules/client-common/src/main/java/org/apache/ignite/internal/client/table/MutableTupleBinaryTupleAdapter.java, modules/client/src/test/java/org/apache/ignite/client/AbstractClientTableTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientKeyValueViewTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientRecordViewTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientSqlTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientTupleTest.java, modules/client/src/test/java/org/apache/ignite/client/CustomTuple.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeIgniteTables.java, modules/core/src/main/java/org/apache/ignite/internal/table/criteria/SqlRowProjection.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientSqlTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/api/AsyncResultSetImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/TestRow.java, modules/table/src/main/java/org/apache/ignite/internal/table/AbstractRowTupleAdapter.java, modules/table/src/main/java/org/apache/ignite/internal/table/MutableRowTupleAdapter.java, modules/table/src/test/java/org/apache/ignite/internal/table/InteropOperationsTest.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/TestTupleBuilder.java
=> IGNITE-23420 Tuple API does not provide a method to read decimal values

modules/core/src/main/java/org/apache/ignite/internal/tostring/ClassDescriptor.java, modules/core/src/main/java/org/apache/ignite/internal/tostring/FieldDescriptor.java, modules/core/src/main/java/org/apache/ignite/internal/tostring/IgniteStringifier.java, modules/core/src/main/java/org/apache/ignite/internal/tostring/IgniteToStringBuilder.java, modules/core/src/main/java/org/apache/ignite/internal/tostring/SizeOnlyStringifier.java, modules/core/src/main/java/org/apache/ignite/internal/tostring/Stringifier.java, modules/core/src/main/java/org/apache/ignite/internal/tostring/ToStringUtils.java, modules/core/src/test/java/org/apache/ignite/internal/tostring/IgniteStringifierTest.java, modules/core/src/test/java/org/apache/ignite/internal/tostring/SizeOnlyStringifierTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/command/GetAllCommand.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/messages/MessageImplGenerator.java, modules/network-annotation-processor/src/test/java/org/apache/ignite/internal/network/processor/tests/OtherMessages.java, modules/network-annotation-processor/src/test/java/org/apache/ignite/internal/network/processor/tests/OtherMessagesTest.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/replication/MultipleRowPkReplicaRequest.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/replication/MultipleRowReplicaRequest.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/RpcRequests.java
https://issues.apache.org/jira/browse/IGNITE-23948
=> IGNITE-23948 Add print size only for MultipleRowReplicaRequest#binaryTuples in IgniteToStringBuilder#toString

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/LogicalRelImplementor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/RowHandler.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/SqlRowHandler.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/CorrelatedNestedLoopJoinNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/HashJoinNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/MergeJoinNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/ModifyNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/NestedLoopJoinNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/row/RowSchema.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/ExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/HashJoinExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/ModifyNodeExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/row/RowSchemaTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/row/SqlRowHandlerTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/ArrayRowHandler.java
=> IGNITE-23898 Sql. Calculate schema for concat two rows just once

modules/client/src/test/java/org/apache/ignite/client/fakes/FakeIgniteTables.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/TableScanNodeExecutionTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItLockTableTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/HeapLockManager.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-23837
=> IGNITE-23837 Add log when lock manager run out of slots

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java
JIRA Ticket: [IGNITE-23982](https://issues.apache.org/jira/browse/IGNITE-23982)
The goal of the PR is to comment out the corresponding assertions.
Several TC failures for a small time window.
The corresponding assertions are commented out.
=> IGNITE-23982 Comment out asserts on primary elected/expired in ReplicaStateManager

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/HashJoinNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/ExtendedFieldDeserializingProjectedTuple.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/FieldDeserializingProjectedTuple.java
https://issues.apache.org/jira/browse/IGNITE-23957
----------
=> IGNITE-23957 Sql. Fix excessive memory consumption during query processing

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/QueryTaskExecutorImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/AsyncRootNodeTest.java
https://issues.apache.org/jira/browse/IGNITE-23605
=> IGNITE-23605 Fixes AsyncRootNodeTest

modules/configuration-api/src/main/java/org/apache/ignite/configuration/annotation/PublicName.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/asm/ConfigurationAsmGenerator.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/asm/ConfigurationImplAsmGenerator.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/asm/InnerNodeAsmGenerator.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/hocon/HoconConverterTest.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/tree/ConstructableTreeNodeTest.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/tree/TraversableTreeNodeTest.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/tree/extension/ExtendedConstructableTreeNodeTest.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/tree/extension/ExtendedTraversableTreeNodeTest.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/tree/polymorphic/PolymorphicConstructableTreeNodeTest.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/tree/polymorphic/PolymorphicTraversableTreeNodeTest.java
https://issues.apache.org/jira/browse/IGNITE-23872
=> IGNITE-23872 Allow arbitrary names for configuration properties

modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItComputeTestStandalone.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/ComputeComponentImpl.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/loader/JobContextManager.java
https://issues.apache.org/jira/browse/IGNITE-23731
=> IGNITE-23731 IgniteCompute test with deployed jar is failed

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItJoinTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/LogicalRelImplementor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/HashJoinNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rule/HashJoinConverterRule.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/Commons.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractJoinExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/HashJoinExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/HashJoinPlannerTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/PlannerTest.java, modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/BaseSqlIntegrationTest.java
https://issues.apache.org/jira/browse/IGNITE-23970
---------
=> IGNITE-23970 Sql. Extend usage of HashJoin

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/CliIntegrationTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/CliCommandTestNotInitializedIntegrationBase.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/cluster/init/ItClusterInitTest.java, modules/code-deployment/src/integrationTest/java/org/apache/ignite/internal/deployment/Unit.java, modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcAuthenticationTest.java, modules/metrics/src/integrationTest/java/org/apache/ignite/internal/metrics/exporters/ItMetricsTest.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/ItClusterStateHttpServerFilterInitializedTest.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/ItClusterStateHttpServerFilterNotInitializedTest.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/deployment/DeploymentManagementControllerTest.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/recovery/ItDisasterRecoveryControllerResetPartitionsTest.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/recovery/ItDisasterRecoveryControllerRestartPartitionsTest.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/recovery/ItDisasterRecoveryControllerTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/ItClusterTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/inmemory/ItRaftStorageVolatilityTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/start/ItStartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/Cluster.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/ClusterConfiguration.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/ClusterPerClassIntegrationTest.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/ClusterPerTestIntegrationTest.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/NodeNamingStrategy.java, modules/security/src/integrationTest/java/org/apache/ignite/internal/ssl/ItSslTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryReconfigurationTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceRecoveryTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceTest.java
https://issues.apache.org/jira/browse/IGNITE-24009
=> IGNITE-24009 Add an ability to run multiple test clusters

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlQueryProcessor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutableTableRegistry.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutableTableRegistryImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionDependencyResolver.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionDependencyResolverImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/KeyValueGetPlan.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/KeyValueModifyPlan.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/SelectCountPlan.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutableTableRegistrySelfTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionDependencyResolverSelfTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImplTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/NoOpExecutableTableRegistry.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestBuilders.java
https://issues.apache.org/jira/browse/IGNITE-21584
----------
=> IGNITE-21584 Make ExecutableTableRegistry method synchronous

modules/configuration/src/main/java/org/apache/ignite/internal/configuration/asm/ConfigurationAsmGenerator.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/validation/ConfigurationValidatorImpl.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/validation/ConfigurationValidatorImplTest.java
https://issues.apache.org/jira/browse/IGNITE-24046
=> IGNITE-24046 Fix findSchemaField in ConfigurationValidarorImpl

modules/table/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryReconfigurationTest.java
https://issues.apache.org/jira/browse/IGNITE-24051
=> IGNITE-24051 Disable ItDisasterRecoveryReconfigurationTest.testIncompleteRebalanceAfterResetPartitions

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDataTypesTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteTypeCoercion.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/ImplicitCastsTest.java
=> IGNITE-23276 Sql. Clean up IgniteTypeCoercion

modules/metastorage-api/src/main/java/org/apache/ignite/internal/metastorage/MetaStorageManager.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageServiceTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/command/MetastorageCommandsMessageGroup.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/command/RemoveByPrefixCommand.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageService.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageServiceImpl.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/KeyValueStorage.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/MetastorageChecksum.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/raft/MetaStorageWriteHandler.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/BasicOperationsKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/RocksDbKeyValueStorageTest.java, modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/AbstractKeyValueStorageTest.java, modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java
https://issues.apache.org/jira/browse/IGNITE-23959
=> IGNITE-23959 Introduce removeByPrefix command to metastorage

modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ResourceVacuumManager.java
https://issues.apache.org/jira/browse/IGNITE-24065
=> IGNITE-24065 Cancel futures returned by `scheduleAtFixedRate` in ResourceVacuumManager

modules/catalog-compaction/src/integrationTest/java/org/apache/ignite/internal/catalog/compaction/ItCatalogCompactionTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/NodeConfig.java, modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/topology/ItLogicalTopologyTest.java, modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItExecutionsCleanerTest.java, modules/core/src/main/java/org/apache/ignite/internal/failure/FailureProcessor.java, modules/core/src/main/java/org/apache/ignite/internal/thread/ThreadUtils.java, modules/core/src/main/java/org/apache/ignite/internal/util/ExceptionUtils.java, modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/distributionzones/ItDistributionZonesFiltersTest.java, modules/failure-handler/src/main/java/org/apache/ignite/internal/failure/FailureManager.java, modules/failure-handler/src/main/java/org/apache/ignite/internal/failure/configuration/FailureProcessorConfigurationSchema.java, modules/failure-handler/src/main/java/org/apache/ignite/internal/failure/handlers/StopNodeFailureHandler.java, modules/failure-handler/src/main/java/org/apache/ignite/internal/failure/handlers/StopNodeOrHaltFailureHandler.java, modules/failure-handler/src/test/java/org/apache/ignite/internal/failure/FailureProcessorLoggingTest.java, modules/failure-handler/src/test/java/org/apache/ignite/internal/failure/FailureProcessorTest.java, modules/failure-handler/src/test/java/org/apache/ignite/internal/failure/FailureProcessorThreadDumpThrottlingTest.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/AbstractClientService.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/util/internal/ThrowUtil.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/RestNode.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteServerTest.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/ClusterPerClassIntegrationTest.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/ClusterPerTestIntegrationTest.java, modules/security/src/integrationTest/java/org/apache/ignite/internal/ssl/ItSslTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItUnstableTopologyTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceTriggersRecoveryTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItTransactionPrimaryChangeTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItTxResourcesVacuumTest.java
https://issues.apache.org/jira/browse/IGNITE-20449
=> IGNITE-20449 Add support generating thread dump on failure

modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/OrphanDetector.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/impl/OrphanDetectorTest.java
https://issues.apache.org/jira/browse/IGNITE-24052
=> IGNITE-24052 Stop listening to configuration changes on OrphanDetector stop

modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/RaftGroupServiceImpl.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaImpl.java
https://issues.apache.org/jira/browse/IGNITE-24058
=> IGNITE-24058 Improve logging of NodeStoppedException

modules/table/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryReconfigurationTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/distributed/disaster/ItHighAvailablePartitionSequentialRecoveriesTest.java
https://issues.apache.org/jira/browse/IGNITE-24073
=> IGNITE-24073 Disable ItHighAvailablePartitionSequentialRecoveriesTest.testTwoSequentialResets

modules/table/src/integrationTest/java/org/apache/ignite/internal/table/distributed/disaster/ItHighAvailablePartitionSequentialRecoveriesTest.java
https://issues.apache.org/jira/browse/IGNITE-24066
=> IGNITE-24066 Mute flaky testTwoSequentialResets

modules/table/src/integrationTest/java/org/apache/ignite/internal/table/distributed/disaster/ItHighAvailablePartitionSequentialRecoveriesTest.java
https://issues.apache.org/jira/browse/IGNITE-24077
=> IGNITE-24077 Fix compilation issue.

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlQueryProcessor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/fsm/QueryExecutor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/fsm/QueryIdGenerator.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestNode.java
https://issues.apache.org/jira/browse/IGNITE-24045
Result of the benchmark on my laptop (MBP M3) as follow:
```
Before
Benchmark                         (clusterSize)  (fsync)  Mode  Cnt   Score   Error  Units
SelectBenchmark.sqlGet_1_thread               1    false  avgt   20   6.061 ± 0.137  us/op
SelectBenchmark.sqlGet_4_threads              1    false  avgt   20   8.773 ± 0.848  us/op
SelectBenchmark.sqlGet_8_threads              1    false  avgt   20  16.954 ± 1.540  us/op
After
Benchmark                         (clusterSize)  (fsync)  Mode  Cnt   Score   Error  Units
SelectBenchmark.sqlGet_1_thread               1    false  avgt   20   5.758 ± 0.099  us/op
SelectBenchmark.sqlGet_4_threads              1    false  avgt   20   8.473 ± 0.958  us/op
SelectBenchmark.sqlGet_8_threads …
```
=> IGNITE-24045 Sql. Replace UUID.randomUUID() with custom generator for query id

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/HashJoinNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rule/HashJoinConverterRule.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/HashJoinExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/HashJoinPlannerTest.java
https://issues.apache.org/jira/browse/IGNITE-24050
--------
=> IGNITE-24050 Sql. Fix usage of HashJoins with non-equi predicate

modules/core/src/main/java/org/apache/ignite/internal/replicator/TablePartitionId.java
https://issues.apache.org/jira/browse/IGNITE-24048
=> IGNITE-24048 TablePartitionId's hash might lead to collisions in HeapLockManager

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListener.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/raft/MetaStorageListener.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/ZonePartitionRaftListener.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/MockStateMachine.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/TestCluster.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/FSMCallerImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/IteratorImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/IteratorWrapper.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/core/IteratorImplTest.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/core/IteratorTest.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java
https://issues.apache.org/jira/browse/IGNITE-24056
=> IGNITE-24056 Interrupt write command batch application on Raft node stop

modules/arch-test/build.gradle, modules/spring/spring-boot-ignite-client-autoconfigure/src/main/java/org/apache/ignite/IgniteClientAutoConfiguration.java, modules/spring/spring-boot-ignite-client-autoconfigure/src/main/java/org/apache/ignite/IgniteClientProperties.java, modules/spring/spring-boot-ignite-client-autoconfigure/src/main/java/org/apache/ignite/SslConfigurationProperties.java, modules/spring/spring-boot-ignite-client-autoconfigure/src/test/java/org/apache/ignite/IgniteClientAutoConfigurationTest.java, modules/spring/spring-boot-starter-ignite-client-example/src/test/java/org/apache/ignite/ExampleApplicationTest.java, settings.gradle
https://issues.apache.org/jira/browse/IGNITE-24079
Updated code according to changes made by https://issues.apache.org/jira/browse/IGNITE-23892, https://issues.apache.org/jira/browse/IGNITE-23890, https://issues.apache.org/jira/browse/IGNITE-24009
=> IGNITE-24079 Fix including spring boot modules

modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItTransactionRecoveryTest.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/event/LockEventParameters.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/HeapLockManager.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/OrphanDetector.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/AbstractLockManagerEventsTest.java
https://issues.apache.org/jira/browse/IGNITE-23467
=> IGNITE-23467 Resolve all abandoned locks for the key at a time

modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/PersistentLogStorageFactories.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/TestCluster.java
https://issues.apache.org/jira/browse/IGNITE-24113
=> IGNITE-24113 Use separate persistent log storages per Raft node in ItNodeTest

modules/runner/src/integrationTest/java/org/apache/ignite/internal/storageprofile/ItDefaultStorageProfileTest.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/ThreadAssertingMvTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/configuration/PageMemoryStorageEngineLocalConfigurationModule.java
https://issues.apache.org/jira/browse/IGNITE-24114
=> IGNITE-24114 Only create default profile if it doesn't exist

modules/sql-engine/src/main/codegen/config.fmpp, modules/sql-engine/src/main/codegen/includes/parserImpls.ftl, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlCreateSchema.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlDropSchema.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlDropSchemaBehavior.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlDropSchemaPolicy.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/SqlSchemaDdlParserTest.java
https://issues.apache.org/jira/browse/IGNITE-24019
=> IGNITE-24019 Extend SQL parser grammar with CREATE/DROP SCHEMA statements.

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-24124
=> IGNITE-24124 Fix pool starvation in TableManager#beforeNodeStop()

modules/client/src/main/java/org/apache/ignite/internal/client/TcpIgniteClient.java, modules/client/src/test/java/org/apache/ignite/client/ClientMetricsTest.java, modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/PlatformTestNodeRunner.java
* Change `JMX_MBEAN_PACKAGE` to `org.apache.ignite`
* Fix client metrics initialization, add JMX integration test
=> IGNITE-24108 Fix client JMX export, fix MBean package

modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcBatchSelfTest.java, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/PlacementDriverNodesOperabilityTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoverySystemViewTest.java
https://issues.apache.org/jira/browse/IGNITE-24128
=> IGNITE-24128 Remove casts to RestartProofIgnite

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
https://issues.apache.org/jira/browse/IGNITE-24147
=> IGNITE-24147 Assert that operation timestamp is not lower than transaction timestamp

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceRaftGroupEventsListener.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/ZoneRebalanceRaftGroupEventsListener.java, modules/raft-api/src/main/java/org/apache/ignite/internal/raft/RaftGroupEventsListener.java, modules/raft/src/integrationTest/java/org/apache/ignite/internal/raft/ItRaftGroupServiceTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/TestCluster.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/JraftGroupEventsListener.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/RaftGroupEventsListenerAdapter.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/NodeImpl.java
https://issues.apache.org/jira/browse/IGNITE-24106
=> IGNITE-24106 Propagate raft term and index to onNewPeersConfigurationApplied

modules/core/src/main/java/org/apache/ignite/internal/util/ExceptionUtils.java, modules/failure-handler/src/main/java/org/apache/ignite/internal/failure/FailureManager.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/Replicator.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/AbstractClientService.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java
https://issues.apache.org/jira/browse/IGNITE-24148
=> IGNITE-24148 Do not log exceptions caused by node stop

modules/transactions/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryReconfigurationTest.java
https://issues.apache.org/jira/browse/IGNITE-24161
=> IGNITE-24161 Mute flaky testAssignmentsChainUpdatedOnAutomaticReset

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
https://issues.apache.org/jira/browse/IGNITE-24164
=> IGNITE-24164 Remove catalog usage from debug logging

modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngineTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtilUpdateAssignmentsTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItIdempotentCommandCacheTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageServicePersistenceTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageServiceTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/server/raft/ItMetaStorageRaftGroupTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/CommandIdGenerator.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageServiceImpl.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/impl/IdempotentCommandCacheTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/impl/MetaStorageDeployWatchesCorrectnessTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerRecoveryTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AbstractCompactionKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/BasicOperationsKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/RocksDbKeyValueStorageTest.java, modules/runner/src/test/java/org/apache/ignite/internal/configuration/storage/DistributedConfigurationStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-24155
=> IGNITE-24155 Remove node id supplier from CommandIdGenerator

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexMetaStorage.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/index/IndexMetaStorageRecoveryTest.java
https://issues.apache.org/jira/browse/IGNITE-24172
=> IGNITE-24172 Fix flaky IndexMetaStorageRecoveryTest#testMissingDropTableWithUpdateLwmBeforeRestart

modules/api/src/main/java/org/apache/ignite/catalog/IgniteCatalog.java, modules/catalog-dsl/src/integrationTest/java/org/apache/ignite/internal/catalog/ItCatalogDslTest.java, modules/catalog-dsl/src/main/java/org/apache/ignite/internal/catalog/sql/IgniteCatalogSqlImpl.java, modules/catalog-dsl/src/main/java/org/apache/ignite/internal/catalog/sql/SelectFromView.java, modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofIgniteCatalog.java, modules/runner/src/main/java/org/apache/ignite/internal/threading/PublicApiThreadingIgniteCatalog.java
=> IGNITE-24031 Sql schema. Extend IgniteCatalog API with supporting qualified names

modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageServiceTest.java
https://issues.apache.org/jira/browse/IGNITE-24205
=> IGNITE-24205 Fix flaky ItMetaStorageServiceTest#testRemoveByPrefix

modules/client-handler/src/main/java/org/apache/ignite/client/handler/JdbcHandlerBase.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/JdbcQueryEventHandlerImpl.java, modules/client-handler/src/test/java/org/apache/ignite/client/handler/SqlQueryTypeInJdbcTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlApiBaseTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlMultiStatementTxTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/api/AsyncResultSetImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlQueryProcessor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlQueryType.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/fsm/OptimizingPhaseHandler.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/fsm/ParsingPhaseHandler.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/fsm/ValidationHelper.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/tx/ScriptTransactionContext.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/SqlQueryTypeSelfTest.java
https://issues.apache.org/jira/browse/ignite-21122
---
=> IGNITE-21122: Sql. Introduce attributes for SqlQueryType and use them instead of direct checks.

modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java
https://issues.apache.org/jira/browse/IGNITE-24202
=> IGNITE-24202 Fix ItNodeTest#longBatchInStateMachineAndShutdown() flakiness

modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/ClassWrapper.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/ConfigurationProcessor.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/ConfigurationProcessorUtils.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/ConfigurationValidationException.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/validation/InjectedValueValidator.java
https://issues.apache.org/jira/browse/IGNITE-24208
=> IGNITE-24208 Refactor configuration annotation processor (Part 1)

modules/api/src/main/java/org/apache/ignite/lang/TableNotFoundException.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/Catalog.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/partitions/reset/ItResetPartitionsTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/partitions/restart/ItRestartPartitionsTest.java, modules/core/src/main/java/org/apache/ignite/internal/util/StringUtils.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceMinimumRequiredTimeProviderImplTest.java, modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/recovery/ResetPartitionsRequest.java, modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/recovery/RestartPartitionsRequest.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/recovery/ItDisasterRecoveryControllerResetPartitionsTest.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/recovery/ItDisasterRecoveryControllerRestartPartitionsTest.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/recovery/ItDisasterRecoveryControllerTest.java, modules/rest/src/main/java/org/apache/ignite/internal/rest/recovery/DisasterRecoveryController.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/DisasterRecoveryManager.java, modules/transactions/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryManagerTest.java, modules/transactions/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryReconfigurationTest.java
=> IGNITE-24211 Sql. Fix invalid qualified name usage in Catalog object

modules/configuration-annotation-processor/src/integrationTest/java/org/apache/ignite/internal/configuration/processor/ItConfigurationProcessorTest.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/ClassWrapper.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/ConfigurationProcessor.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/validation/AbstractConfigurationValidator.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/validation/ConfigValidator.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/validation/ConfigValueValidator.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/validation/ConfigurationExtentionValidator.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/validation/ConfigurationRootValidator.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/validation/InjectedNameValidator.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/validation/MiscellaneousIssuesValidator.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/validation/NamedConfigValueValidator.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/validation/PolymorphicConfigInstanceValidator.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/validation/PolymorphicConfigValidator.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/validation/Validator.java
https://issues.apache.org/jira/browse/IGNITE-17166
=> IGNITE-17166 Refactor configuration annotation processor (Part 2)

modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/LockManagerBenchmark.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItLockTableTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNodeNoCleanupMessage.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItColocationTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/SortedIndexLockerTest.java, modules/transactions/build.gradle, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/HeapLockManager.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/AbstractLockManagerTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/AbstractLockingTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/CoarseGrainedLockManagerTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/HeapLockManagerTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-20694
=> IGNITE-20694 Add system properties for configuring HeapLockManager

modules/api/src/main/java/org/apache/ignite/lang/ErrorGroups.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/network/messages/InitErrorMessage.java, modules/platforms/cpp/ignite/common/error_codes.h, modules/platforms/cpp/ignite/odbc/common_types.cpp, modules/platforms/dotnet/Apache.Ignite/ErrorCodes.g.cs, modules/rest/src/main/java/org/apache/ignite/internal/rest/cluster/ClusterManagementController.java
https://issues.apache.org/jira/browse/IGNITE-24203
=> IGNITE-24203 Fix NullPointerException in ClusterManagementController#mapClusterState

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/StorageScanNode.java
=> IGNITE-24017 Sql. StorageScanNode SubscriberImpl onNext can be called after subscription is cancelled

modules/catalog-dsl/src/integrationTest/java/org/apache/ignite/internal/catalog/ItCatalogApiThreadingTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteServerTest.java, modules/runner/src/main/java/org/apache/ignite/IgniteServer.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteServerImpl.java
https://issues.apache.org/jira/browse/IGNITE-22688
=> IGNITE-22688 Make async continuation executor configurable in IgniteServer

modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/ItClientHandlerBindTest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientHandlerModule.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/configuration/ClientConnectorConfigurationSchema.java, modules/network/src/main/java/org/apache/ignite/internal/network/configuration/NetworkConfigurationSchema.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/NettyServer.java, modules/network/src/test/java/org/apache/ignite/internal/network/netty/NettyServerTest.java
https://issues.apache.org/jira/browse/IGNITE-24248
=> IGNITE-24248 Support configuration syntax for multiple binding addresses

modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/HeapLockManager.java
https://issues.apache.org/jira/browse/IGNITE-24223
=> IGNITE-24223 Remove invalid assert

modules/raft-api/src/main/java/org/apache/ignite/internal/raft/configuration/RaftConfigurationSchema.java
https://issues.apache.org/jira/browse/IGNITE-24249
=> IGNITE-24249 Switch fsync setting for tables to false by default

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/topology/api/LogicalNode.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/Node.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/NodeWithAttributes.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngine.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngineV2.java, modules/network-api/src/main/java/org/apache/ignite/internal/network/ClusterNodeImpl.java
https://issues.apache.org/jira/browse/IGNITE-24236
=> IGNITE-24236 Reduce log pollution by LogicalNode

modules/platforms/cpp/ignite/odbc/app/parameter_set.h, modules/platforms/cpp/ignite/odbc/query/cursor.h, modules/platforms/cpp/ignite/odbc/query/data_query.cpp, modules/platforms/cpp/ignite/odbc/query/result_page.h, modules/platforms/python/cpp_module/module.cpp, modules/platforms/python/cpp_module/py_cursor.cpp, modules/platforms/python/cpp_module/utils.cpp, modules/platforms/python/cpp_module/utils.h, modules/platforms/python/tests/conftest.py, modules/platforms/python/tests/test_fetch_table.py
https://issues.apache.org/jira/browse/IGNITE-23967
- Added tests;
- Fixed a bug that prevented the exception during fetch to be reported;
- Fixed argument ordering (`timeout` and `page_size` were mixed up);
- Fixed last page indicator reading.
=> IGNITE-23967 Python DB API Fix fetching long result sets

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteServerImpl.java, modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItSystemGroupDisasterRecoveryTest.java
https://issues.apache.org/jira/browse/IGNITE-24259
=> IGNITE-24259 Improve NodeStoppingException handling

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/WatchProcessor.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/WatchProcessorTest.java
https://issues.apache.org/jira/browse/IGNITE-24271
=> IGNITE-24271 Do not pass NodeStoppingException to FailureHandler in WatchProcessor

modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/distributionzones/ItIgniteDistributionZoneManagerNodeRestartTest.java
https://issues.apache.org/jira/browse/IGNITE-24238
=> IGNITE-24238 Fix flaky testCreationZoneWhenDataNodesAreDeletedIsNotSuccessful

modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java
https://issues.apache.org/jira/browse/IGNITE-24273
=> IGNITE-24273 Fix flaky ItNodeTest#testInstallSnapshot

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/statistic/SqlStatisticManagerImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/statistic/SqlStatisticManagerImplTest.java
https://issues.apache.org/jira/browse/IGNITE-24269
-----------------
=> IGNITE-24269 Fix race during updating tableSize map

modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTableGetRequest.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTables.java, modules/client/src/test/java/org/apache/ignite/client/AbstractClientTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientComputeTest.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeIgniteTables.java, modules/platforms/cpp/ignite/client/detail/table/tables_impl.cpp, modules/platforms/cpp/tests/client-test/tables_test.cpp, modules/platforms/dotnet/Apache.Ignite.Tests/FakeServer.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Table/TablesTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Tables.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientConnectionTest.java
Return the original name of the resolved table from the server.
=> IGNITE-24276 Thin client: return actual table name from TABLE_GET

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-24268
=> IGNITE-24268 Minor refactoring in PartitionReplicaLifecycleManager

modules/network/src/main/java/org/apache/ignite/internal/network/netty/ConnectionManager.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/NettyClient.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/NettyServer.java, modules/network/src/test/java/org/apache/ignite/internal/network/netty/NettyClientTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/netty/NettyServerTest.java
https://issues.apache.org/jira/browse/IGNITE-24207
=> IGNITE-24207 Speed ​​up Netty channel creation when using SSL

modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java
https://issues.apache.org/jira/browse/IGNITE-24292
=> IGNITE-24292 Fix IndexOutOfBoundsException from jraft IteratorImpl#done

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestNode.java
https://issues.apache.org/jira/browse/IGNITE-24295
---------
=> IGNITE-24295 Sql. TpcdsQueryPlannerTest query 64 timeouts

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteServerImpl.java
https://issues.apache.org/jira/browse/IGNITE-24308
=> IGNITE-24308 Log max heap and available processors on start

modules/core/src/main/java/org/apache/ignite/internal/future/timeout/TimeoutObject.java, modules/core/src/main/java/org/apache/ignite/internal/future/timeout/TimeoutWorker.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/asserts/CompletableFutureAssert.java, modules/network/src/main/java/org/apache/ignite/internal/network/DefaultMessagingService.java, modules/network/src/test/java/org/apache/ignite/internal/network/DefaultMessagingServiceTest.java
https://issues.apache.org/jira/browse/IGNITE-24313
=> IGNITE-24313 Improve invocation timeout exception message

modules/platforms/python/cpp_module/type_conversion.h, modules/platforms/python/cpp_module/utils.cpp, modules/platforms/python/tests/test_fetch_table.py
https://issues.apache.org/jira/browse/IGNITE-24298
- Added a test with 10000 rows;
- Fixed multiple freeing of the object that should not have been freed in the first place.
=> IGNITE-24298 DB API: Fix invalid freeing of an object

modules/core/src/main/java/org/apache/ignite/internal/replicator/TablePartitionId.java
https://issues.apache.org/jira/browse/IGNITE-24118
=> IGNITE-24118 Investigate performance drop on master.

modules/platforms/dotnet/Apache.Ignite.Tests/PartitionAwarenessTests.cs, modules/platforms/dotnet/Apache.Ignite.Tests/Transactions/TransactionsTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/IgniteClientInternal.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Transactions/LazyTransaction.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Transactions/Transactions.cs
Record observable timestamp when the user starts the transaction.
=> IGNITE-24329 .NET: Fix LazyTransaction observable timestamp

modules/partition-replicator/build.gradle, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/TestPlacementDriver.java
https://issues.apache.org/jira/browse/IGNITE-24333
=> IGNITE-24333 Extract Node class from ItReplicaLifecycleTest

modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStoreManager.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java
https://issues.apache.org/jira/browse/IGNITE-24337
=> IGNITE-24337 Don't throw NoSuchFileException in IgniteUtils.deleteIfExistsThrowable

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/agg/Accumulators.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/agg/AccumulatorsFactory.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/PlanUtils.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/exp/agg/LiteralValAccumulatorTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/util/PlanUtilsTest.java
=> IGNITE-23813 Sql. Provide correct implementation of LITERAL_AGG aggregate function

packaging/odbc/build.gradle
https://issues.apache.org/jira/browse/IGNITE-24352
- Fixed rpm package version;
- Fixed scripts ownership (OS user).
=> IGNITE-24352 Fix ODBC RPM build

modules/client/src/test/java/org/apache/ignite/client/fakes/FakeInternalTable.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/TableScanNodeExecutionTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItColocationTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/InternalTable.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/PartitionAccessImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerRecoveryTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/PartitionAccessImplTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotCopierTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/storage/InternalTableEstimatedSizeTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImplTest.java, modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/ThreadAssertingTxStateStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/TxStateStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbPartitionStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbSharedStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbStorage.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/rocksdb/RocksDbTxStatePartitionStorageTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/test/TestTxStatePartitionStorageTest.java, modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/AbstractTxStatePartitionStorageTest.java, modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/test/TestTxStateStorage.java
https://issues.apache.org/jira/browse/IGNITE-24344
=> IGNITE-24344 Rename TxStateTableStorage to TxStateStorage

modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/DataStorageManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerRecoveryTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbSharedStorage.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/rocksdb/RocksDbTxStatePartitionStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-24370
=> IGNITE-24370 Move TxStateRocksDbSharedStorage creation from TableManager

modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/AssignmentsTracker.java
https://issues.apache.org/jira/browse/IGNITE-23365
=> IGNITE-23365 Improve assignments tracker logging

modules/catalog-compaction/src/main/java/org/apache/ignite/internal/catalog/compaction/CatalogManagerCompactionFacade.java, modules/catalog-compaction/src/test/java/org/apache/ignite/internal/catalog/compaction/CatalogManagerCompactionFacadeTest.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogNotFoundException.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogService.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerRecoveryTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java
=> IGNITE-24321 Avoid returning null from CatalogService methods

modules/core/src/main/java/org/apache/ignite/internal/replicator/ZonePartitionId.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/message/ReplicaMessageUtils.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/message/ZonePartitionIdMessage.java
https://issues.apache.org/jira/browse/IGNITE-24389
=> IGNITE-24389 Remove outdated tableId field from ZonePartitionId

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItZoneDataReplicationTest.java
https://issues.apache.org/jira/browse/IGNITE-24393
=> IGNITE-24393 Disable flaky test

modules/vault/src/main/java/org/apache/ignite/internal/vault/persistence/PersistentVaultService.java
https://issues.apache.org/jira/browse/IGNITE-24392
=> IGNITE-24392 Use fsync in PersistentVaultService

packaging/docker/Dockerfile
https://issues.apache.org/jira/browse/IGNITE-24396
=> IGNITE-24396 Running CLI from docker prints question marks

modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/logit/option/StoreOptions.java
https://issues.apache.org/jira/browse/IGNITE-24395
=> IGNITE-24395 Add some system properties to Logit options

modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcTransactionTest.java
https://issues.apache.org/jira/browse/IGNITE-21539
=> IGNITE-21539 Jdbc. Added some missed non-autocommit test cases.

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java, modules/index/src/main/java/org/apache/ignite/internal/index/IndexManager.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ddl/DdlCommandHandlerExceptionHandlingTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexMetaStorage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexUtils.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/FullStateTransferIndexChooser.java
=> IGNITE-24339 Fix flaky test DdlCommandHandlerExceptionHandlingTest#testZoneNotFoundOnDrop2

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlOperatorsTest.java, modules/sql-engine/src/integrationTest/sql/group1/function/numeric/test_pg_math.test, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/IgniteSqlFunctions.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/RexImpTable.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/IgniteMethod.java
https://issues.apache.org/jira/browse/IGNITE-22405
---
=> IGNITE-22405: Sql. Implement log10 function based on java Math.log10 implementation

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-24423
=> IGNITE-24423 Fix potential NullPointerException in InternalTableImpl

modules/schema/src/main/java/org/apache/ignite/internal/schema/SchemaManager.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlMultiStatementTest.java
https://issues.apache.org/jira/browse/IGNITE-24418
------
=> IGNITE-24418 Fix schema registration in SchemaManager for batched commands

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ddl/DdlCommandHandlerExceptionHandlingTest.java
=> IGNITE-24426 Fix broken test

modules/catalog-dsl/src/integrationTest/java/org/apache/ignite/internal/catalog/ItCatalogDslTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSchemaTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/ddl/DdlSqlToCommandConverter.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/DdlBatchingTest.java
https://issues.apache.org/jira/browse/IGNITE-24434
-----------
=> IGNITE-24434 Sql. Unable to create SCHEMA and TABLE in the same script

modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlExecuteBatchRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlExecuteRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlExecuteScriptRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTableCommon.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/client/ItClientObservableTimeTest.java
https://issues.apache.org/jira/browse/IGNITE-24275
----------
=> IGNITE-24275 Sql. Rework or replace HybridTimestampTracker.clientTracker

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AlterTableAddColumnCommand.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AlterTableAlterColumnCommand.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AlterTableDropColumnCommand.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CatalogUtils.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/DropIndexCommand.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/DropTableCommand.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/RenameIndexCommand.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/RenameTableCommand.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AbstractCommandValidationTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AlterTableAddColumnCommandValidationTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AlterTableAlterColumnCommandValidationTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AlterTableDropColumnCommandValidationTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/CreateAbstractIndexCommandValidationTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/DropIndexCommandValidationTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/DropTableCommandValidationTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/RenameIndexCommandValidationTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/RenameTableCommandValidationTest.java
=> IGNITE-24328 Sql. DDL commands should respect IF EXISTS flag if schema not exists.

modules/catalog-dsl/src/integrationTest/java/org/apache/ignite/internal/catalog/ItCatalogDslTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCancelScriptTest.java
=> IGNITE-24448 Fix ItCatalogDslTest#tableCreateAndDropWithQualifiedName

modules/jdbc/src/main/java/org/apache/ignite/jdbc/package-info.java
=> IGNITE-24403 add package level javadoc for org.apache.ignite.jdbc

modules/core/src/main/java/org/apache/ignite/internal/replicator/ZonePartitionId.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/LeaseBatchSerializer.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/leases/LeaseBatchSerializerTest.java
https://issues.apache.org/jira/browse/IGNITE-24450
=> IGNITE-24450 Implement serialization and deserialization for zone leases

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/RaftTableProcessor.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/ZonePartitionRaftListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java
https://issues.apache.org/jira/browse/IGNITE-24478
=> IGNITE-24478 Introduce RaftTableProcessor interface

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/connect/ItConnectWithBasicAuthenticationCommandTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/core/repl/executor/ItIgnitePicocliCommandsTest.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/call/connect/ConnectionChecker.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/JdbcUrlFactory.java
https://issues.apache.org/jira/browse/IGNITE-24489
=> IGNITE-24489 Can't run sql after asking for credentials

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/ZoneResourcesManager.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManagerTest.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/ZoneResourcesManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-24521
=> IGNITE-24521 Move listeners map into ZoneResourcesManager

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItAggregatesTest.java
=> IGNITE-24158 Sql. Cleanup ItAggregatesTest

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java
https://issues.apache.org/jira/browse/IGNITE-24558
=> IGNITE-24558 Fix ItReplicaLifecycleTest.testCatalogCompaction

modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
https://issues.apache.org/jira/browse/IGNITE-24503
=> IGNITE-24503 Remove the list of configuration modules from log

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/ZoneResourcesManager.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/ZoneResourcesManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-24583
=> IGNITE-24583 Use thread-safe map for zone partition resources

docs/_docs/administrators-guide/config/node-config.adoc, docs/_docs/installation/migration-from-ai2/overview.adoc, docs/_docs/sql-reference/ddl.adoc
Eviction and expiration are not yet implemented in Ignite 3 - remove related documentation.
=> IGNITE-24543 Remove eviction and expiration from docs

modules/table/src/integrationTest/java/org/apache/ignite/internal/table/distributed/disaster/ItHighAvailablePartitionsRecoveryTest.java
https://issues.apache.org/jira/browse/IGNITE-24599
=> IGNITE-24599 Disable ItHighAvailablePartitionsRecoveryTest.testManualRecovery

modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
https://issues.apache.org/jira/browse/IGNITE-23864
=> IGNITE-23864 Log node configuration on start

modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/views/TransactionsViewProvider.java
https://issues.apache.org/jira/browse/IGNITE-24520
---
=> IGNITE-24520 Sql. TransactionViewProvider should only return local transactions

modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
https://issues.apache.org/jira/browse/IGNITE-24504
=> IGNITE-24504 Log cluster configuration

modules/network/src/integrationTest/java/org/apache/ignite/internal/network/netty/ItConnectionManagerTest.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/ConnectionManager.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/ItIgniteStartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/Cluster.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/NodeBootstrapConfigUpdater.java
https://issues.apache.org/jira/browse/IGNITE-22863
=> IGNITE-22863 'Port already in use' error code gets lost

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageCompactionTrigger.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageCompactionTriggerConfiguration.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/impl/MetaStorageCompactionTriggerConfigurationTest.java
https://issues.apache.org/jira/browse/IGNITE-23280
=> IGNITE-23280 Turn on metastorage compaction trigger

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/metadata/IgniteMdSelectivity.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/SelectRowCountEstimationTest.java
=> IGNITE-24590 Sql. Fix selectivity after IGNITE-23969

docs/_docs/developers-guide/clients/java.adoc
https://issues.apache.org/jira/browse/IGNITE-24582
change wrong group id org.ignite to org.apache.ignite
- [Apache Ignite Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE …
=> IGNITE-24582 Fix the wrong group id of the Java client artifact in the Developers Guide

docs/_docs/developers-guide/clients/overview.adoc
https://issues.apache.org/jira/browse/IGNITE-24605
=> IGNITE-24605 Fix Ignite version in documentation

modules/page-memory/src/integrationTest/java/org/apache/ignite/internal/pagememory/tree/persistence/ItBplusTreePersistentPageMemoryTest.java, modules/page-memory/src/integrationTest/java/org/apache/ignite/internal/pagememory/tree/persistence/ItBplusTreeReuseListPersistentPageMemoryTest.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/PersistentPageMemory.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointDirtyPages.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointManager.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointProgress.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointProgressImpl.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/Checkpointer.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/throttling/CheckpointBufferOverflowWatchdog.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/throttling/CheckpointLockStateChecker.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/throttling/ExponentialBackoff.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/throttling/ExponentialBackoffThrottlingStrategy.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/throttling/PagesWriteThrottle.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/throttling/PagesWriteThrottlePolicy.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/replacement/AbstractPageReplacementTest.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryDataRegion.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryNoLoadTest.java
https://issues.apache.org/jira/browse/IGNITE-24546
=> IGNITE-24546 Port target ratio based throttling from Apache Ignite 2

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/sqllogic/Statement.java
https://issues.apache.org/jira/browse/IGNITE-24616
--------------
=> IGNITE-24616 Sql. Improve error reporting in SqlLogic test runner

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/ZonePartitionRaftListener.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/handlers/AbstractCommandHandler.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/handlers/CommandHandlers.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/handlers/FinishTxCommandHandler.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/handlers/VacuumTxStatesCommandHandler.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/handlers/WriteIntentSwitchCommandHandler.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/handlers/MinimumActiveTxTimeCommandHandler.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/PartitionCommandListenerTest.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/message/TxMessageGroup.java
https://issues.apache.org/jira/browse/IGNITE-24573
=> IGNITE-24573  Add common interface to process raft commands

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CatalogUtils.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/CatalogUtilsTest.java, modules/core/src/main/java/org/apache/ignite/internal/type/NativeTypes.java, modules/core/src/test/java/org/apache/ignite/internal/type/NativeTypeTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/LargeBinaryBenchmark.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/LargeStringBenchmark.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItAlterTableDdlTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCreateTableDdlTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDataTypesTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/datatypes/ItVarlenTypesTest.java, modules/sql-engine/src/integrationTest/sql/group1/function/string/test_char_length.test, modules/sql-engine/src/integrationTest/sql/group1/types/blob/test_blob.test, modules/sql-engine/src/integrationTest/sql/group1/types/char/test_char_length.test, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/type/IgniteTypeSystem.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/SqlExceptionMapperProvider.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ddl/VarlenValuesSizeTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/datatypes/NumericFunctionsTypeCoercionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/prepare/ddl/DdlSqlToCommandConverterTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/type/IgniteTypeSystemTest.java, modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/engine/util/QueryCheckerImpl.java
https://issues.apache.org/jira/browse/IGNITE-24154
---
=> IGNITE-24154: Increase maximum precision for VARBINARY and VARCHAR types up to integer.MAX_VALUE

modules/transactions/src/integrationTest/java/org/apache/ignite/tx/distributed/ItTxResourcesVacuumTest.java
https://issues.apache.org/jira/browse/IGNITE-24639
=> IGNITE-24639 Muting ItTxResourcesVacuumTest#testVacuum

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/command/TableAwareCommand.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNodeNoCleanupMessage.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItColocationTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/test/java/org/apache/ignite/internal/benchmarks/UpdateCommandsMarshallingMicroBenchmark.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/command/PartitionRaftCommandsSerializationTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/PartitionCommandListenerTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerIndexLockingTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerSortedIndexLockingTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/schema/CheckCatalogVersionOnActionRequestTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/storage/InternalTableEstimatedSizeTest.java, modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-24635
=> IGNITE-24635 Substitute TablePartitionId with hybrid in PartitionReplicaListener

modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/ZoneResourcesManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-24644
=> IGNITE-24644 Fix ZoneResourcesManagerTest#supportsParallelAllocation

modules/storage-api/src/main/java/org/apache/ignite/internal/storage/util/StorageUtils.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/AbstractPageMemoryIndexStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/AbstractRocksDbIndexStorage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbPartitionStorage.java, modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/AbstractTxStatePartitionStorageTest.java, modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/test/TestTxStatePartitionStorage.java
https://issues.apache.org/jira/browse/IGNITE-24626
=> IGNITE-24626 Improve error handling on storage stop

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/storage/BlackholeSubscriber.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImplTest.java
https://issues.apache.org/jira/browse/IGNITE-24580
=> IGNITE-24580 Make sure tableId is added to enlistment in InternalTableImpl

modules/core/src/main/java/org/apache/ignite/internal/util/ExceptionUtils.java, modules/core/src/test/java/org/apache/ignite/internal/lang/ExceptionUtilsTest.java
https://issues.apache.org/jira/browse/IGNITE-24648
=> IGNITE-24648 Fix potential infinite loop in ExceptionUtils#hasCauseOrSuppressed

modules/page-memory/src/integrationTest/java/org/apache/ignite/internal/pagememory/tree/persistence/ItBplusTreePersistentPageMemoryTest.java, modules/page-memory/src/integrationTest/java/org/apache/ignite/internal/pagememory/tree/persistence/ItBplusTreeReuseListPersistentPageMemoryTest.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/PersistentPageMemory.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/replacement/AbstractPageReplacementTest.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryDataRegion.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryNoLoadTest.java
https://issues.apache.org/jira/browse/IGNITE-24653
=> IGNITE-24653 Remove unused PageChangeTracker interface

modules/core/src/main/java/org/apache/ignite/internal/sql/SyncResultSetAdapter.java, modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/api/IgniteSqlImpl.java
https://issues.apache.org/jira/browse/IGNITE-24641
=> IGNITE-24641 Make waits in sql module interruptible

modules/client/src/main/java/org/apache/ignite/internal/client/ReliableChannel.java, modules/core/src/main/java/org/apache/ignite/internal/util/ExceptionUtils.java
https://issues.apache.org/jira/browse/IGNITE-24645
=> IGNITE-24645 Improve connection error logging for thin client

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogSystemViewRegistry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/systemviews/IndexColumnsSystemViewProvider.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/systemviews/ItIndexColumnsSystemViewTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/systemviews/ItIndexesSystemViewTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/systemviews/ItSchemasSystemViewTest.java
https://issues.apache.org/jira/browse/IGNITE-24304
---
=> IGNITE-24304 Sql. System views. Introduce a system view for index columns

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/MergeJoinNode.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/MergeJoinExecutionTest.java
https://issues.apache.org/jira/browse/IGNITE-24636
----------
=> IGNITE-24636 Sql. Fix freezes in MergeJoin[type=RIGHT]

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/fsm/MultiStatementHandler.java
=> IGNITE-24483 Sql. ItJdbcMultiStatementSelfTest.testAutoCommitFalseTxControlStatementsNotSupported is flaky

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlParser.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/Commons.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/IgniteResource.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlParserSelfTest.java
https://issues.apache.org/jira/browse/ignite-24452
---
=> IGNITE-24452 Sql. Assertion for unsupported Calcite statements

modules/runner/src/testFixtures/java/org/apache/ignite/internal/ClusterPerClassIntegrationTest.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/ClusterPerTestIntegrationTest.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/MicronautCleanup.java
https://issues.apache.org/jira/browse/IGNITE-24670
=> IGNITE-24670 Fix Micronaut shutdown hook leak in integration tests

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaImpl.java
https://issues.apache.org/jira/browse/IGNITE-24673
=> IGNITE-24673 Fix removing placement driver listeners

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/PageReadWriteManager.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/PartitionMetaManager.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointManager.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/compaction/Compactor.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/store/AbstractFilePageStoreIo.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStore.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStoreManager.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/store/PageStore.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointManagerTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/compaction/CompactorTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/replacement/AbstractPageReplacementTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/store/AbstractFilePageStoreIoTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/store/DeltaFilePageStoreIoTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStoreTest.java, modules/page-memory/src/testFixtures/java/org/apache/ignite/internal/pagememory/persistence/TestPageReadWriteManager.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryDataRegion.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/StoragePartitionMetaManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-24681
=> IGNITE-24681 Remove constant `calculateCrc` flag from persistence code

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/ReliableCatalogVersions.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/handlers/WriteIntentSwitchRequestHandler.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java
https://issues.apache.org/jira/browse/IGNITE-24574
=> IGNITE-24574 Implement required catalog version selection for WriteIntentSwitch requests handling

modules/system-disaster-recovery-api/src/main/java/org/apache/ignite/internal/disaster/system/message/ResetClusterMessage.java, modules/system-disaster-recovery-api/src/test/java/org/apache/ignite/internal/disaster/system/message/ResetClusterMessageTest.java
https://issues.apache.org/jira/browse/IGNITE-24672
=> IGNITE-24672 Do not log initial config with ResetClusterMessage

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-24696
=> IGNITE-24696 Make waits in TableManager interruptible

modules/cli/src/main/java/org/apache/ignite/internal/cli/core/rest/ApiClientFactory.java
https://issues.apache.org/jira/browse/IGNITE-24671
=> IGNITE-24671 Disable potential HTTP request retry in CLI

modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/NodeImpl.java
https://issues.apache.org/jira/browse/IGNITE-24697
=> IGNITE-24697 Log groupId with unsuccessful election message

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AlterZoneCommand.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/RenameZoneCommand.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/AlterZoneEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/AlterZoneEntry.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/storage/CatalogEntrySerializationTest.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DataNodesManager.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DataNodesManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-24657
=> IGNITE-24657 Remove previousDescriptor from AlterZoneEntry

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionContext.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/HashJoinNode.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/RuntimeSortedIndexTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractJoinExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/HashJoinExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestBuilders.java
=> IGNITE-24675 Sql. Hash join operation may hands for right and outer join.

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/metadata/IgniteMdSelectivity.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/SelectRowCountEstimationTest.java
=> IGNITE-24692 Sql. Fix correct mappings for primary keys

modules/runner/src/testFixtures/java/org/apache/ignite/internal/MicronautCleanup.java
https://issues.apache.org/jira/browse/IGNITE-24700
=> IGNITE-24700 Fix micronaut shutdown hooks cleaner on Java 21

.idea/codeStyles/Project.xml, modules/catalog-compaction/src/test/java/org/apache/ignite/internal/catalog/compaction/AbstractCatalogCompactionTest.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java, modules/catalog/src/testFixtures/java/org/apache/ignite/internal/catalog/BaseCatalogManagerTest.java, modules/catalog/src/testFixtures/java/org/apache/ignite/internal/catalog/CatalogTestUtils.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/distributionzones/ItIgniteDistributionZoneManagerNodeRestartTest.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/BaseDistributionZoneManagerTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerLogicalTopologyEventsTest.java, modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/impl/StandaloneMetaStorageManager.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-24705
=> IGNITE-24705 Use correct catalog version in DistributionZoneManager

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java, modules/core/src/main/java/org/apache/ignite/internal/hlc/ClockWaiter.java, modules/core/src/main/java/org/apache/ignite/internal/util/PendingComparableValuesTracker.java, modules/core/src/main/java/org/apache/ignite/internal/util/PendingIndependentComparableValuesTracker.java, modules/core/src/test/java/org/apache/ignite/internal/hlc/ClockWaiterTest.java, modules/core/src/test/java/org/apache/ignite/internal/util/PendingComparableValuesTrackerTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/time/ClusterTimeImpl.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/time/ClusterTimeTest.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java
https://issues.apache.org/jira/browse/IGNITE-24614
=> IGNITE-24614 Prevent throwing safe time advance exception on stop

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItBuildIndexTest.java
https://issues.apache.org/jira/browse/IGNITE-24710
=> IGNITE-24710 Remove outdated code

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItZoneDataReplicationTest.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/ZonePartitionReplicaListener.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/ZonePartitionRaftListener.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/raft/ZonePartitionRaftListenerTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java
https://issues.apache.org/jira/browse/IGNITE-24690
=> IGNITE-24690 Add synchronization to ZonePartitionRaftListener

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/CommandResult.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/RaftTableProcessor.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/ZonePartitionRaftListener.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/handlers/AbstractCommandHandler.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/handlers/FinishTxCommandHandler.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/handlers/VacuumTxStatesCommandHandler.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/handlers/WriteIntentSwitchCommandHandler.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/raft/ZonePartitionRaftListenerTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/handlers/BuildIndexCommandHandler.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/handlers/MinimumActiveTxTimeCommandHandler.java
https://issues.apache.org/jira/browse/IGNITE-24713
=> IGNITE-24713 Use custom class as Raft command result

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteTypeCoercion.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/datatypes/BaseTypeCoercionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/datatypes/NumericQuantifyOperatorTypeCoercionTest.java
https://issues.apache.org/jira/browse/IGNITE-24707
----------
=> IGNITE-24707 Sql. Fix type coercion for quantify operators

modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/TestServer.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientHandlerModule.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlExecuteScriptRequest.java, modules/client/src/test/java/org/apache/ignite/client/TestClientHandlerModule.java, modules/client/src/test/java/org/apache/ignite/client/TestServer.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/api/IgniteSqlImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/api/IgniteSqlImplTest.java
https://issues.apache.org/jira/browse/IGNITE-24477
=> IGNITE-24477 Use common executor instead of ForkJoinPool in public sql script handler.

modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageManagerImplTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/time/ClusterTimeImpl.java, modules/network/src/main/java/org/apache/ignite/internal/network/NettyWorkersRegistrar.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
https://issues.apache.org/jira/browse/IGNITE-24717
=> IGNITE-24717 Improve handling of Metastorage safe time sync problems

modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItInternalTableReadWriteScanColocationTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItInternalTableReadWriteScanTest.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/TxManager.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadWriteTransactionImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerColocationTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/impl/ReadWriteTransactionImplColocationTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/impl/ReadWriteTransactionImplTest.java
https://issues.apache.org/jira/browse/IGNITE-24695
=> IGNITE-24695 Assert replication group type on enlistment

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItAbstractColocationTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItColocationTxRecoveryTest.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/TxRecoveryEngine.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/ZonePartitionReplicaListener.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/handlers/ReplicaSafeTimeSyncRequestHandler.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/handlers/TxRecoveryMessageHandler.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/handlers/VacuumTxStateReplicaRequestHandler.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
https://issues.apache.org/jira/browse/IGNITE-24361
=> IGNITE-24361 Implement TxRecoveryMessage processing for zone replica

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/LogicalRelImplementor.java
https://issues.apache.org/jira/browse/IGNITE-24732
Result of several queries from TPC-H suite on a single node cluster with scale factor 0.1:
```
Before
Benchmark          (fsync)  (queryId)  Mode  Cnt     Score    Error  Units
TpchBenchmark.run    false          1  avgt   20  1924.575 ±  3.575  ms/op
TpchBenchmark.run    false          2  avgt   20   256.358 ± 13.635  ms/op
TpchBenchmark.run    false          5  avgt   20   366.379 ±  0.677  ms/op
TpchBenchmark.run    false          7  avgt   20   548.897 ±  2.109  ms/op
TpchBenchmark.run    false          8  avgt   20   387.975 ±  3.322  ms/op
TpchBenchmark.run    false         22  avgt   20   417.330 ±  4.561  ms/op
After
Benchmark          (fsync)  (queryId)  Mode  Cnt     Score    Error  Units
TpchBenchmark.run    false          1 …
```
=> IGNITE-24732 Sql. Avoid expression lookup on every expression invocation

modules/sql-engine/src/integrationTest/sql/group1/join/natural/test_natural_join.test
=> IGNITE-24743 Sql. Disable flaky test_natural_join

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractRightMaterializedJoinNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/FilterNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/HashJoinNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/Inbox.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/MergeJoinNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/NestedLoopJoinNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/SortAggregateNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/SortNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/StorageScanNode.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractJoinExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/BaseAggregateTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/DataSourceScanNodeExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/FilterExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/HashJoinExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/IndexScanNodeExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/MergeJoinExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/TableScanNodeExecutionTest.java
=> IGNITE-23960 Sql. Execution node should not hold thread for too long

modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/BasePlacementDriverTest.java, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/ItPrimaryReplicaChoiceTest.java, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/MultiActorPlacementDriverTest.java, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/PlacementDriverManagerTest.java, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/PlacementDriverNodesOperabilityTest.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/LeaseNegotiationTest.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/LeaseUpdaterTest.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/PlacementDriverTest.java, modules/replicator/src/testFixtures/java/org/apache/ignite/internal/replicator/ReplicaTestUtils.java
https://issues.apache.org/jira/browse/IGNITE-24748
=> IGNITE-24748 Support zone partitions in placement-driver tests

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItColocationDurableFinishTest.java
https://issues.apache.org/jira/browse/IGNITE-24774
=> IGNITE-24775 Disable ItColocationDurableFinishTest.testChangePrimaryOnCleanup

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/AbstractCompoundCondition.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/AndCondition.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/OrCondition.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AndConditionTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/OrConditionTest.java
https://issues.apache.org/jira/browse/IGNITE-24771
=> IGNITE-24771 Optimize AbstractCompoundCondition

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/GroupUpdateRequest.java, modules/transactions/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryResetPartitionsTest.java
https://issues.apache.org/jira/browse/IGNITE-24755
=> IGNITE-24755 Fix NPE because "localPartitionStateByNode" is null

modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AndConditionTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/OrConditionTest.java
https://issues.apache.org/jira/browse/IGNITE-24776
=> IGNITE-24776 Fix broken OrConditionTest

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItIndexAvailabilityTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/statistic/SqlStatisticManagerImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/statistic/SqlStatisticManagerImplTest.java
=> IGNITE-24760 Sql. Flaky testComplexIndexConditionInitialTableCreate test

modules/core/src/main/java/org/apache/ignite/internal/thread/IgniteThread.java, modules/network-api/src/main/java/org/apache/ignite/internal/network/IgniteMessageServiceThread.java, modules/network-api/src/main/java/org/apache/ignite/internal/network/IgniteMessageServiceThreadFactory.java, modules/network-api/src/main/java/org/apache/ignite/internal/network/TrackableNetworkMessageHandler.java, modules/network/src/main/java/org/apache/ignite/internal/network/CriticalStripedThreadPoolExecutorFactory.java, modules/network/src/main/java/org/apache/ignite/internal/network/DefaultMessagingService.java
https://issues.apache.org/jira/browse/IGNITE-24562
=> IGNITE-24562 Avoid "Message handling has been too long" message in custom pools

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/DisasterRecoveryManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/DisasterRecoverySystemViews.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/LocalPartitionState.java, modules/transactions/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoverySystemViewTest.java
=> IGNITE-24763 Sql. Unification of column names in disaster recovery system views

modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java
https://issues.apache.org/jira/browse/IGNITE-24787
=> IGNITE-24787 Fix "Lease update" message frequency

modules/metastorage-cache/src/main/java/org/apache/ignite/internal/metastorage/cache/IdempotentCacheVacuumizer.java, modules/metastorage-cache/src/test/java/org/apache/ignite/internal/metastorage/cache/IdempotentCacheVacuumizerTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItIdempotentCommandCacheTest.java
https://issues.apache.org/jira/browse/IGNITE-24784
=> IGNITE-24784 Fix eviction timestamp calculation in idempotent cache vacuumizer

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AbstractCompactionKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/BasicOperationsKeyValueStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-24790
=> IGNITE-24790 Fix race in meta-storage compaction

modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientPrimaryReplicaTracker.java, modules/client-handler/src/test/java/org/apache/ignite/client/handler/ClientPrimaryReplicaTrackerTest.java, modules/client-handler/src/testFixtures/java/org/apache/ignite/client/handler/FakeCatalogService.java, modules/client-handler/src/testFixtures/java/org/apache/ignite/client/handler/FakePlacementDriver.java, modules/client/src/test/java/org/apache/ignite/client/AbstractClientTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientPartitionManagerTest.java, modules/client/src/test/java/org/apache/ignite/client/PartitionAwarenessTest.java, modules/client/src/test/java/org/apache/ignite/client/TestServer.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeIgniteTables.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItInternalTableReadWriteScanTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/partition/HashPartitionManagerImpl.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/impl/ReadWriteTransactionImplTest.java
https://issues.apache.org/jira/browse/IGNITE-24768
=> IGNITE-24768 Support per-zone partitions in client handler

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaBuildIndexProcessor.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
https://issues.apache.org/jira/browse/IGNITE-24665
=> IGNITE-24665 Extract BuildIndexEventListener from PartitionReplicaListener

modules/core/src/main/java/org/apache/ignite/internal/tostring/IgniteToStringBuilder.java, modules/core/src/test/java/org/apache/ignite/internal/tostring/IgniteToStringBuilderSelfTest.java, modules/core/src/test/java/org/apache/ignite/internal/tostring/IgniteToStringBuilderTest.java
https://issues.apache.org/jira/browse/IGNITE-24803
=> IGNITE-24803 Do not skip non-private fields in IgniteToStringBuilder

modules/transactions/src/integrationTest/java/org/apache/ignite/tx/distributed/ItTxResourcesVacuumTest.java
https://issues.apache.org/jira/browse/IGNITE-24633
=> IGNITE-24633 Fix ItTxResourcesVacuumTest.testVacuum

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractRightMaterializedJoinNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractSetOpNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/AsyncRootNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/CorrelatedNestedLoopJoinNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/FilterNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/HashAggregateNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/HashJoinNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/Inbox.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/IndexSpoolNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/LimitNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/MergeJoinNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/ModifyNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/NestedLoopJoinNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/Outbox.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/ProjectNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/RootNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/ScanNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/SortAggregateNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/SortNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/StorageScanNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/TableSpoolNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/UnionAllNode.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractJoinExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/CorrelatedNestedLoopJoinExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/ExecutionTest.java
=> IGNITE-24765 Sql. Reduce number of state checks in executions nodes

docs/_layouts/default.html
This is one of a number of PR's I'm submitting to remove  **_Google_** & **_Yandex_** analytics from the Ignite website as part of [IGNITE-24264](https://issues.apache.org/jira/browse/IGNITE-24264). I have also included replacing those analytics which are not permitted at the ASF with _**Matomo**_ (see [analytics.apache.org](https://analytics.apache.org/)).
From what I see, it looks like you sometimes re-generate your docs from the branches, so I've cherry picked the change across branches - hence the number of PRs
I didn't have much idea how the docs/website were built when I submitted [PR #189](https://github.com/apache/ignite-website/pull/189) - so thanks for applying that, but it seems it had no effect. Hopefully this effort will yield better results.
Thank you for submitting the pull …
=> IGNITE-24264 Replace Google Analytics with Matomo (Ignite-3 main)

docs/_layouts/default.html
This is one of a number of PR's I'm submitting to remove  **_Google_** & **_Yandex_** analytics from the Ignite website as part of [IGNITE-24264](https://issues.apache.org/jira/browse/IGNITE-24264). I have also included replacing those analytics which are not permitted at the ASF with _**Matomo**_ (see [analytics.apache.org](https://analytics.apache.org/)).
From what I see, it looks like you sometimes re-generate your docs from the branches, so I've cherry picked the change across branches - hence the number of PRs
I didn't have much idea how the docs/website were built when I submitted [PR #189](https://github.com/apache/ignite-website/pull/189) - so thanks for applying that, but it seems it had no effect. Hopefully this effort will yield better results.
Thank you for submitting the pull …
=> IGNITE-24264 Replace Google Analytics with Matomo (Ignite3 3.0)

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/mapping/MappingServiceImpl.java
https://issues.apache.org/jira/browse/IGNITE-24806
=> IGNITE-24806 Fix MappingServiceImpl.buildTargetForTable

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/AbstractChangeIndexStatusEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/DropIndexEntry.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/storage/DropIndexEntryTest.java, modules/index/build.gradle, modules/index/src/main/java/org/apache/ignite/internal/index/ChangeIndexStatusTask.java, modules/index/src/main/java/org/apache/ignite/internal/index/ChangeIndexStatusTaskScheduler.java, modules/index/src/main/java/org/apache/ignite/internal/index/IndexBuildingManager.java, modules/index/src/test/java/org/apache/ignite/internal/index/ChangeIndexStatusTaskTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
https://issues.apache.org/jira/browse/IGNITE-24804
=> IGNITE-24804 Ignore 'index not found' exception when switching index state

docs/_docs/developers-guide/cache.adoc, docs/_docs/developers-guide/sql/jdbc-driver.adoc, docs/_docs/quick-start/embedded-mode.adoc
=> IGNITE-24711 Fix ignite group id in docs

.asf.yaml
* Remove `allow_force_pushes` (outdated flag - force pushes are disabled for all protected branches)
* Add `required_conversation_resolution`
* Add `squash_commit_message: PR_TITLE_AND_DESC`
(see https://github.com/apache/infrastructure-asfyaml for more details)
=> IGNITE-24807 Fix outdated flags in .asf.yaml

modules/table/src/integrationTest/java/org/apache/ignite/internal/table/distributed/disaster/AbstractHighAvailablePartitionsRecoveryTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/distributed/disaster/ItHighAvailablePartitionsRecoveryByFilterUpdateTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/distributed/disaster/ItHighAvailablePartitionsRecoveryTest.java
https://issues.apache.org/jira/browse/IGNITE-24509
=> IGNITE-24509 Fix HA tests where we check that partition storages are empty

modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/NodeImpl.java
https://issues.apache.org/jira/browse/IGNITE-24523
=> IGNITE-24523 Logs configuration change using debug level

modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java
https://issues.apache.org/jira/browse/IGNITE-24819
=> IGNITE-24819 Mute ItNodeTest#testNodeWillNeverGetOutOfSnapshot

modules/core/src/main/java/org/apache/ignite/internal/hlc/HybridTimestamp.java
https://issues.apache.org/jira/browse/IGNITE-24841
=> IGNITE-24841 Optimize HybridTimestamp#toString

modules/failure-handler/src/main/java/org/apache/ignite/internal/failure/FailureManager.java, modules/failure-handler/src/main/java/org/apache/ignite/internal/failure/configuration/FailureProcessorConfigurationSchema.java, modules/failure-handler/src/test/java/org/apache/ignite/internal/failure/FailureProcessorLoggingTest.java, modules/failure-handler/src/test/java/org/apache/ignite/internal/failure/FailureProcessorTest.java, modules/failure-handler/src/test/java/org/apache/ignite/internal/failure/FailureProcessorThreadDumpThrottlingTest.java
https://issues.apache.org/jira/browse/IGNITE-24801
=> IGNITE-24801 Fix typo in FailureProcessorConfigurationSchema

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/PartitionTxStateAccessImpl.java, modules/raft/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/PartitionMvStorageAccessImpl.java
https://issues.apache.org/jira/browse/IGNITE-24849
=> IGNITE-24849 Flush storages after rebalance

modules/catalog-compaction/src/test/java/org/apache/ignite/internal/catalog/compaction/CatalogCompactionRunnerSelfTest.java, modules/client-handler/src/test/java/org/apache/ignite/client/handler/ClientPrimaryReplicaTrackerTest.java, modules/client-handler/src/testFixtures/java/org/apache/ignite/client/handler/FakeCatalogService.java
https://issues.apache.org/jira/browse/IGNITE-24855
=> IGNITE-24855 Adopt CatalogCompactionRunnerSelfTest for colocation track

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManagerTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/partition/ItPartitionDestructionTest.java
https://issues.apache.org/jira/browse/IGNITE-24873
=> IGNITE-24873 Destroy zone partition storages on partition eviction

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/ZonePartitionRaftListener.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/PartitionDataStorage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/SnapshotAwarePartitionDataStorage.java, modules/table/src/testFixtures/java/org/apache/ignite/distributed/TestPartitionDataStorage.java
https://issues.apache.org/jira/browse/IGNITE-24872
=> IGNITE-24872 Fix minor issues related to RaftTableProcessor

modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/snapshot/SnapshotExecutorImpl.java
https://issues.apache.org/jira/browse/IGNITE-24888
=> IGNITE-24888 Add more logging when saving a snapshot

modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxObservableTimePropagationTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/ItRaftFsyncOptionTest.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/TxInfrastructureTest.java
https://issues.apache.org/jira/browse/IGNITE-24880
=> IGNITE-24880 Support per-zone partitions in integration tests of table module

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/ZoneResourcesManager.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/OnSnapshotSaveHandler.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/PartitionSnapshotInfo.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/ZonePartitionRaftListener.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/raft/ZonePartitionRaftListenerTest.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/lease/LeaseInfo.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ReplicasSafeTimePropagationTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/PartitionCommandListenerTest.java, modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-24822
=> IGNITE-24822 Persist last created Raft snapshot information

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointProgressImpl.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/throttling/PagesWriteSpeedBasedThrottle.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/throttling/SpeedBasedMemoryConsumptionThrottlingStrategy.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/throttling/PageMemoryThrottlingTest.java
https://issues.apache.org/jira/browse/IGNITE-24839
=> IGNITE-24839 Avoid unwarranted long parking periods in speed based throttling

modules/catalog-compaction/src/integrationTest/java/org/apache/ignite/internal/catalog/compaction/ItCatalogCompactionTest.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/sql/ItSqlQueryControllerTest.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/transaction/ItTransactionControllerTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/systemviews/AbstractSystemViewTest.java, modules/transactions/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoverySystemViewTest.java
=> IGNITE-24703 Wait for system views registration on node start

modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItIdempotentCommandCacheTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/raft/service/ItAbstractListenerSnapshotTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItZoneDataReplicationTest.java, modules/raft-api/src/main/java/org/apache/ignite/internal/raft/service/RaftGroupService.java, modules/raft/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItCliServiceTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/server/ItJraftCounterServerTest.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/RaftGroupServiceImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/CliService.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/Node.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/CliServiceImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/NodeImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/CliRequests.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/cli/SnapshotRequestProcessor.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/LogManager.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/SnapshotExecutor.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/impl/LogManagerImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/snapshot/SnapshotExecutorImpl.java, modules/raft/src/test/java/org/apache/ignite/internal/raft/RaftGroupServiceTest.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/rpc/impl/cli/SnapshotRequestProcessorTest.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/storage/impl/LogManagerTest.java, modules/replicator/src/main/java/org/apache/ignite/internal/raft/client/TopologyAwareRaftGroupService.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/Replica.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaImpl.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ZonePartitionReplicaImpl.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItRaftCommandLeftInLogUntilRestartTest.java, modules/transactions/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryReconfigurationTest.java
https://issues.apache.org/jira/browse/IGNITE-24907
=> IGNITE-24907 Add method for a forced raft snapshot

modules/api/src/main/java/org/apache/ignite/lang/ErrorGroups.java, modules/network-api/src/main/java/org/apache/ignite/internal/network/DuplicateConsistentIdException.java, modules/platforms/cpp/ignite/common/error_codes.h, modules/platforms/cpp/ignite/odbc/common_types.cpp, modules/platforms/dotnet/Apache.Ignite/ErrorCodes.g.cs
https://issues.apache.org/jira/browse/IGNITE-24882
=> IGNITE-24882 Remove unneeded public error code

modules/catalog-compaction/src/integrationTest/java/org/apache/ignite/internal/catalog/compaction/ItCatalogCompactionTest.java, modules/catalog-compaction/src/main/java/org/apache/ignite/internal/catalog/compaction/CatalogCompactionRunner.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/mapping/MappingServiceImplTest.java
https://issues.apache.org/jira/browse/IGNITE-24901
=> IGNITE-24901 Fix detecting removed tables in CatalogCompactionRunner when colocation feature enabled

examples/README.md, examples/src/main/java/org/apache/ignite/example/compute/ComputeAsyncExample.java, examples/src/main/java/org/apache/ignite/example/compute/ComputeBroadcastExample.java, examples/src/main/java/org/apache/ignite/example/compute/ComputeCancellationExample.java, examples/src/main/java/org/apache/ignite/example/compute/ComputeColocatedExample.java, examples/src/main/java/org/apache/ignite/example/compute/ComputeExample.java, examples/src/main/java/org/apache/ignite/example/compute/ComputeJobPriorityExample.java, examples/src/main/java/org/apache/ignite/example/compute/ComputeMapReduceExample.java, examples/src/main/java/org/apache/ignite/example/compute/ComputeWithCustomResultMarshallerExample.java, examples/src/main/java/org/apache/ignite/example/compute/ComputeWithResultExample.java
=> IGNITE-24875 Add Compute examples

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/sqllogic/ItSqlLogicTest.java
=> IGNITE-24914: Fix flaky SqlLogic test_order_same_value.test

modules/catalog-dsl/src/integrationTest/java/org/apache/ignite/internal/catalog/ItCatalogDslTest.java, modules/catalog-dsl/src/main/java/org/apache/ignite/internal/catalog/sql/TableDefinitionCollector.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/systemviews/TablesSystemViewProvider.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/systemviews/ItTablesSystemViewTest.java
https://issues.apache.org/jira/browse/IGNITE-24761
---
=> IGNITE-24761 Sql. System views. Update table column system view to include information on key, collation columns

modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/IgniteTestUtils.java
=> IGNITE-24736 Improve IgniteTestUtils.randomString function javadocs

modules/core/src/main/java/org/apache/ignite/internal/util/IgniteSpinBusyLock.java, modules/core/src/main/java/org/apache/ignite/internal/util/IgniteStripedBusyLock.java, modules/core/src/main/java/org/apache/ignite/internal/util/PendingComparableValuesTracker.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java
https://issues.apache.org/jira/browse/IGNITE-24917
=> IGNITE-24917 Introduce IgniteStripedBusyLock and use it

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaStateManager.java
https://issues.apache.org/jira/browse/IGNITE-24921
=> IGNITE-24921 Make ReplicaStateManager a top-level class

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-24927
=> IGNITE-24927 Fix table storages destruction for per-zone partitions

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointMetricsTracker.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/Checkpointer.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointMetricsTrackerTest.java
https://issues.apache.org/jira/browse/IGNITE-23266
=> IGNITE-23266 Add metrics of waiting to complete page replacement on checkpoint

modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItExecutionsCleanerTest.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/ComputeComponentImpl.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/ExecutionManager.java, modules/compute/src/test/java/org/apache/ignite/internal/compute/ComputeComponentImplTest.java
https://issues.apache.org/jira/browse/IGNITE-24910
=> IGNITE-24910 Fix flaky killComputeJobFromRemote test

modules/index/src/integrationTest/java/org/apache/ignite/internal/index/ItIndexRegistrationAndRebalanceConcurrencyTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlApiBaseTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/AbstractPageMemoryTableStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-24938
=> IGNITE-24938 Ignore attempts to create index storage in destroyed partition

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/compaction/Compactor.java
https://issues.apache.org/jira/browse/IGNITE-24952
=> IGNITE-24952 Improve assertion in Compactor#mergeDeltaFileToMainFile

modules/index/src/main/java/org/apache/ignite/internal/index/IndexBuildTask.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaStateManager.java
https://issues.apache.org/jira/browse/IGNITE-24944
=> IGNITE-24944 Improve TrackerClosedException handling

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/UpdateLogImpl.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerDescriptorCausalityTokenTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerRecoveryTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/storage/UpdateLogImplTest.java
=> IGNITE-24930 Catalog. Write protocol version into metastore on startup

modules/api/src/main/java/org/apache/ignite/lang/util/IgniteNameUtils.java, modules/api/src/test/java/org/apache/ignite/table/QualifiedNameTest.java, modules/core/src/test/java/org/apache/ignite/internal/util/IgniteNameUtilsTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlParser.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlParserSelfTest.java
=> IGNITE-24584: Sql. IgniteNameUtils.parseIdentifier must be compatible with Calcite's sql identifier

modules/network/src/main/java/org/apache/ignite/internal/network/DefaultMessagingService.java, modules/network/src/main/java/org/apache/ignite/internal/network/RecipientInetAddress.java, modules/network/src/test/java/org/apache/ignite/internal/network/DefaultMessagingServiceTest.java
https://issues.apache.org/jira/browse/IGNITE-24955
=> IGNITE-24955 Fix current node address resolving in DefaultMessagingService#resolveRecipientAddress

modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/ItClusterVersionUpgradeTest.java, modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/raft/ItCmgRaftServiceTest.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/ValidationManager.java, modules/core/src/main/java/org/apache/ignite/internal/properties/IgniteProductVersion.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
https://issues.apache.org/jira/browse/IGNITE-24951
=> IGNITE-24951 Remove validation for Ignite version match on join

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/raft/ItZonePartitionRaftListenerRecoveryTest.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/ZonePartitionRaftListener.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/raft/ZonePartitionRaftListenerTest.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java
=> IGNITE-24811 Fix restoration of empty tables storages for zone-based colocation

modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerRecoveryTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/storage/UpdateLogImplTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/cluster/init/ItClusterInitDefaultMsCmgTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/cluster/init/ItClusterInitTest.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZonesSchedulersTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/causalitydatanodes/DistributionZoneCausalityDataNodesTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageWatchTest.java, modules/network/src/integrationTest/java/org/apache/ignite/internal/network/netty/ItConnectionManagerTest.java, modules/network/src/integrationTest/java/org/apache/ignite/internal/network/scalecube/ItScaleCubeNetworkMessagingTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/server/ItJraftCounterServerTest.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/util/ThreadIdTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/FutureTimeoutBenchmark.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/client/ItClientGetTableSchemaTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteInMemoryNodeRestartTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/streamer/ItAbstractDataStreamerTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlMultiStatementTxTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/util/CompositeSubscriptionTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/distributed/disaster/ItHighAvailablePartitionsRecoveryNoStaleRecoveriesTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/distributed/disaster/ItHighAvailablePartitionsRecoveryTest.java
https://issues.apache.org/jira/browse/IGNITE-24969
=> IGNITE-24969 Add assertions to "waitForCondition" calls in tests

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/raft/ItZonePartitionRaftListenerRecoveryTest.java
https://issues.apache.org/jira/browse/IGNITE-24971
=> IGNITE-24971 Fix flaky test

modules/transactions/src/main/java/org/apache/ignite/internal/tx/InternalTxOptions.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-24967
=> IGNITE-24967 Add ability to explicitly specify read timestamp for RO transactions

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableAssignmentsManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableAssignmentsService.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-24949
=> IGNITE-24949 Refactor createTableLocally

modules/platforms/cpp/ignite/client/CMakeLists.txt, modules/platforms/cpp/ignite/client/detail/type_mapping_utils.h, modules/platforms/cpp/ignite/common/CMakeLists.txt
https://issues.apache.org/jira/browse/IGNITE-24982
Added missing headers to public list.
Filed a ticket to prevent problems like this one in the future: https://issues.apache.org/jira/browse/IGNITE-24983
=> IGNITE-24982 C++: Add missing headers to public

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItTemporalIndexTest.java
=> IGNITE-24843 Sql. Add tests to verify indexes of temporal types

modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryDataRegion.java
https://issues.apache.org/jira/browse/IGNITE-24986
=> IGNITE-24986 Fixed throttling properties parsing and error message

modules/catalog-compaction/src/integrationTest/java/org/apache/ignite/internal/catalog/compaction/ItCatalogCompactionTest.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeTxManager.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlQueryProcessor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/fsm/QueryExecutor.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/ExplicitTxContext.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/NoOpTransaction.java, modules/table/src/main/java/org/apache/ignite/internal/table/AbstractTableView.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java, modules/transactions/src/jmh/java/org/apache/ignite/internal/tx/impl/TransactionExpirationRegistryBenchmark.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/InternalTransaction.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/PublicApiThreadingTransaction.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadOnlyTransactionImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadWriteTransactionImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/RemoteReadWriteTransaction.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/impl/ReadOnlyTransactionImplTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/impl/ReadWriteTransactionImplTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/impl/TransactionExpirationRegistryConcurrentTest.java
https://issues.apache.org/jira/browse/IGNITE-24980
=> IGNITE-24980 Rename InternalTransaction#startTimestamp() to schemaTimestamp()

docs/_docs/sql-reference/distribution-zones.adoc
=> IGNITE-25003 Remove ALTER ZONE SET STORAGE PROFILES

modules/metrics/src/main/java/org/apache/ignite/internal/metrics/exporters/jmx/MetricSetMbean.java, modules/metrics/src/test/java/org/apache/ignite/internal/metrics/exporters/jmx/JmxExporterTest.java
https://issues.apache.org/jira/browse/IGNITE-24905
=> IGNITE-24905 Fixed MetricSetMbean doesn't support custom composite metrics

modules/catalog-compaction/build.gradle, modules/catalog-compaction/src/test/java/org/apache/ignite/internal/catalog/compaction/AbstractCatalogCompactionTest.java, modules/catalog/build.gradle, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java, modules/catalog/src/testFixtures/java/org/apache/ignite/internal/catalog/BaseCatalogManagerTest.java, modules/catalog/src/testFixtures/java/org/apache/ignite/internal/catalog/CatalogTestUtils.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/distributionzones/ItIgniteDistributionZoneManagerNodeRestartTest.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManagerTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
https://issues.apache.org/jira/browse/IGNITE-25004
=> IGNITE-25004 Notify failure handler in CatalogManagerImpl

modules/distribution-zones/src/testFixtures/java/org/apache/ignite/internal/distributionzones/DistributionZonesTestUtil.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/inmemory/ItRaftStorageVolatilityTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteInMemoryNodeRestartTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItReplicaStateManagerTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTableScanTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItOperationRetryTest.java
https://issues.apache.org/jira/browse/IGNITE-24997
=> IGNITE-24997 Adapt runner test for the colocation track

modules/raft/src/integrationTest/java/org/apache/ignite/internal/raft/ItLearnersTest.java
https://issues.apache.org/jira/browse/IGNITE-25018
=> IGNITE-25018 Fix flaky ItLearnersTest

modules/client/src/test/java/org/apache/ignite/client/fakes/FakeInternalTable.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/partition/ItAbstractPartitionManagerTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/InternalTable.java, modules/table/src/main/java/org/apache/ignite/internal/table/KeyValueBinaryViewImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/KeyValueViewImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/RecordBinaryViewImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/RecordViewImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/partition/HashPartitionManagerImpl.java
https://issues.apache.org/jira/browse/IGNITE-25015
=> IGNITE-25015 Fix ItAbstractDataStreamerTest test when the colocation feature is enabled

modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-25020
=> IGNITE-25020 Fix NPE in TableManagerTest when colocation is enabled

modules/core/src/main/java/org/apache/ignite/internal/util/subscription/OrderedMergePublisher.java
=> IGNITE-24966 Sql. Improve OrderedMergePublisher performance

modules/schema/src/main/java/org/apache/ignite/internal/schema/SchemaManager.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/SchemaManagerTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-25024
=> IGNITE-25024 Remove async from SchemaManager#dropRegistryAsync

modules/api/src/main/java/org/apache/ignite/lang/util/IgniteNameUtils.java, modules/core/src/test/java/org/apache/ignite/internal/util/IgniteNameUtilsTest.java
=> IGNITE-25011 Make IgniteNameUtils.quoteIfNeeded consistent with parse methods.

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/AbstractKeyValueStorage.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java
https://issues.apache.org/jira/browse/IGNITE-25031
=> IGNITE-25031 Remove unnecessary locks from some meta-storage operations

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItAbstractColocationTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/ZonePartitionReplicaListener.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/ZonePartitionRaftListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/InternalTable.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-24397
=> IGNITE-24397 Add tests for table removal for colocation

modules/raft/src/integrationTest/java/org/apache/ignite/internal/raft/ItLearnersTest.java
https://issues.apache.org/jira/browse/IGNITE-25047
=> IGNITE-25047 Fix ItLearnersTest after merge

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-25046
=> IGNITE-25046 Delete tables asynchronously

modules/index/src/integrationTest/java/org/apache/ignite/internal/index/ItIndexNodeFinishedRwTransactionsCheckerTest.java
Wait for partition storage to be created before accessing it
https://issues.apache.org/jira/browse/IGNITE-25050
=> IGNITE-25050 Fix ItIndexNodeFinishedRwTransactionsCheckerTest

modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/TestRebalanceUtil.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/distributionzones/ItDistributionZoneMetaStorageCompactionTest.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/distributionzones/ItDistributionZonesFiltersTest.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceTest.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceTriggersRecoveryTest.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/table/ItEstimatedSizeTest.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtil.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/ZoneRebalanceUtil.java, modules/partition-distribution/src/main/java/org/apache/ignite/internal/partitiondistribution/AssignmentsQueue.java
https://issues.apache.org/jira/browse/IGNITE-25040
=> IGNITE-25040 Adapt distribution zones test to colocation feature

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaStateManager.java
https://issues.apache.org/jira/browse/IGNITE-24999
=> IGNITE-24999 Fix a race in weakStopReplica

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/PartitionSnapshotStorage.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/incoming/IncomingSnapshotCopier.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/incoming/IncomingSnapshotCopierTest.java
https://issues.apache.org/jira/browse/IGNITE-25062
=> IGNITE-25062 Simplify code in IncomingSnapshotCopier

modules/core/src/main/java/org/apache/ignite/internal/thread/ThreadUtils.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImpl.java
https://issues.apache.org/jira/browse/IGNITE-25076
=> IGNITE-25076 Fix possible NullPointerException when FailureProcessor dumping a thread dump

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/raft/ItZonePartitionRaftListenerRecoveryTest.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/ZoneResourcesManager.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/PartitionSnapshotStorage.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/PartitionSnapshotStorageFactory.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/PartitionSnapshotWriter.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/incoming/IncomingSnapshotCopier.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/startup/StartupPartitionSnapshotReader.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManagerTest.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/ZoneResourcesManagerTest.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/PartitionSnapshotStorageFactoryTest.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/PartitionSnapshotStorageTest.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/incoming/IncomingSnapshotCopierTest.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/outgoing/OutgoingSnapshotReaderTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-25068
=> IGNITE-25068 Decouple PartitionSnapshotStorage from its factory

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDeleteWithSubQueryTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/MergeJoinNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/ScanNode.java
https://issues.apache.org/jira/browse/IGNITE-24918
--------------
=> IGNITE-24918 Sql. Prevent MergeJoin from scheduling more tasks when it's going to finish

modules/client/src/main/java/org/apache/ignite/internal/client/compute/ClientCompute.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientKeyValueView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientRecordSerializer.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientRecordView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientSchema.java, modules/client/src/test/java/org/apache/ignite/client/AbstractClientTableTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientKeyValueViewTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientRecordViewTest.java, modules/marshaller-common/src/main/java/org/apache/ignite/internal/marshaller/Marshaller.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientMarshallingTest.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/marshaller/reflection/KvMarshallerImpl.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/marshaller/KvMarshallerTest.java
=> IGNITE-25016 Relax Mapper requirements and allow unmapped columns.

modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/AbstractClientService.java
https://issues.apache.org/jira/browse/IGNITE-25088
=> IGNITE-25088 Do not throw in connectAsync() when stopped

modules/transactions/src/integrationTest/java/org/apache/ignite/tx/distributed/ItTxResourcesVacuumTest.java, modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/test/ItTransactionTestUtils.java
https://issues.apache.org/jira/browse/IGNITE-25095
=> Ignite-25095 Fix some tech issues of ItTxResourcesVacuumTest.

modules/api/src/main/java/org/apache/ignite/sql/ColumnType.java, modules/platforms/dotnet/Apache.Ignite/BigDecimal.cs, modules/platforms/dotnet/Apache.Ignite/Sql/ColumnType.cs
Describe how column types correspond to SQL, Java, and .NET types.
=> IGNITE-25089 Improve javadoc and xmldoc for ColumnType

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/AbstractZoneReplicationTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItAbstractColocationTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItBuildIndexTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItColocationSqlTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItColocationTxRecoveryTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItZoneDataReplicationTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItZoneTxFinishTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java
https://issues.apache.org/jira/browse/IGNITE-25098
=> IGNITE-25098 Refactor fake node startup for colocation tests

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/AbstractZoneReplicationTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItAbstractColocationTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItBuildIndexTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItColocationSqlTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItColocationTxRecoveryTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItZoneDataReplicationTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItZoneTxFinishTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java
https://issues.apache.org/jira/browse/IGNITE-25106
This reverts commit 514bdc6ae42c60fc98f3c471d84c703e2fa950df. …
=> IGNITE-25106 Revert "IGNITE-25098 Refactor fake node startup for colocation tests"

modules/core/src/main/java/org/apache/ignite/internal/lang/IgniteSystemProperties.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/table/ItEstimatedSizeTest.java, modules/index/src/main/java/org/apache/ignite/internal/index/IndexBuildController.java, modules/index/src/test/java/org/apache/ignite/internal/index/IndexManagementUtilsTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/ItTruncateRaftLogAndRestartNodesTest.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/Cluster.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/ReplicationGroupsUtils.java, modules/transactions/src/integrationTest/java/org/apache/ignite/tx/distributed/ItTransactionPrimaryChangeTest.java
https://issues.apache.org/jira/browse/IGNITE-25108
=> IGNITE-25108 Fix several different tests in case of enabled colocation.

modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/AbstractMultiNodeBenchmark.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/TxBalanceRetryOperationBenchmark.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/TxUpsertRetryOperationBenchmark.java
https://issues.apache.org/jira/browse/IGNITE-25051
=> IGNITE-25051 Fix benchmarks configuration

modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/AbstractPageMemoryTableStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorage.java
https://issues.apache.org/jira/browse/IGNITE-25102
=> IGNITE-25102 Throw more specific exceptions on table storage destroy

modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/inmemory/VolatilePageMemoryNoLoadSelfTest.java, modules/page-memory/src/testFixtures/java/org/apache/ignite/internal/pagememory/AbstractPageMemoryNoLoadSelfTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryNoLoadTest.java
https://issues.apache.org/jira/browse/IGNITE-25111
=> IGNITE-25111 Specialize testLoadedPagesCount() tests

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-24981
=> IGNITE-24981 Partition storage is missing on index build with colocation

modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/compaction/CompactorTest.java
https://issues.apache.org/jira/browse/IGNITE-25127
=> IGNITE-25127 Fix race in CompactorTest#testStartAndStop

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogService.java, modules/client-handler/src/testFixtures/java/org/apache/ignite/client/handler/FakeCatalogService.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/ReliableCatalogVersions.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java
https://issues.apache.org/jira/browse/IGNITE-24057
=> IGNITE-24057 Handle catalog compaction while resolving assignments timestamp

modules/replicator/src/main/java/org/apache/ignite/internal/raft/client/TopologyAwareRaftGroupService.java
https://issues.apache.org/jira/browse/IGNITE-25134
=> IGNITE-25134 Fix exception handling in TopologyAwareRaftGroupService#sendWithRetry

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java
https://issues.apache.org/jira/browse/IGNITE-25139
=> IGNITE-25139 Fix compilation

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlQueryEventLogTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/systemviews/ItSqlQueriesSystemViewTest.java, modules/sql-engine/src/main/codegen/config.fmpp, modules/sql-engine/src/main/codegen/includes/parserImpls.ftl, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/ParserServiceImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/ParserServiceImplTest.java
https://issues.apache.org/jira/browse/IGNITE-25092
----------
=> IGNITE-25092 Sql. Running queries view should return query string in valid format

modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMaintenanceTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetastorageGroupMaintenance.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItZoneDataReplicationTest.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/RaftGroupServiceImpl.java, modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/MetastorageRepairImpl.java, modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImpl.java, modules/system-disaster-recovery/src/test/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImplTest.java
https://issues.apache.org/jira/browse/IGNITE-25126
=> IGNITE-25126 Do not wait for leader election when repairing MG

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/throttling/PagesWriteSpeedBasedThrottle.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/throttling/SpeedBasedMemoryConsumptionThrottlingStrategy.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/throttling/PageMemoryThrottlingTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/throttling/ThrottlingTest.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryDataRegion.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryStorageEngine.java
https://issues.apache.org/jira/browse/IGNITE-25144
=> IGNITE-25144 Make throttling dirty pages bounds configurable

modules/raft/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/ItTruncateRaftLogAndRestartNodesTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/schemasync/ItSchemaSyncAndReplicationTest.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/Cluster.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/ReplicationGroupsUtils.java
=> IGNITE-25061 Adapt ItTableRaftSnapshotsTest for the colocation track

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointProgress.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointProgressImpl.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/Checkpointer.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/throttling/PagesWriteSpeedBasedThrottle.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/throttling/SpeedBasedMemoryConsumptionThrottlingStrategy.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/throttling/ThrottlingTest.java
https://issues.apache.org/jira/browse/IGNITE-16879
=> IGNITE-16879 Add dynamic estimation of write vs fsync duration in throttling

modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/TestServer.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientHandlerModule.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlExecuteBatchRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlExecuteRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlExecuteScriptRequest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlQueryMetadataRequest.java, modules/client/src/test/java/org/apache/ignite/client/TestClientHandlerModule.java, modules/client/src/test/java/org/apache/ignite/client/TestServer.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
https://issues.apache.org/jira/browse/IGNITE-25086
---------------
=> IGNITE-25086 Thin Client. Sql. Switch sql request processing to another thread pool

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/PagePool.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/PersistentPageMemory.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointReadWriteLock.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/Checkpointer.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/throttling/IntervalBasedMeasurement.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/throttling/PagesWriteSpeedBasedThrottle.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/throttling/ProgressSpeedCalculation.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/throttling/SpeedBasedMemoryConsumptionThrottlingStrategy.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/throttling/ProgressSpeedCalculationTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/throttling/ThrottlingTest.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryDataRegion.java
https://issues.apache.org/jira/browse/IGNITE-25155
=> IGNITE-25155 Optimize aipersist and throttling code

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/AbstractKeyValueStorage.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/AdvanceSafeTimeEvent.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/UpdateEntriesEvent.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/UpdateOnlyRevisionEvent.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/WatchProcessor.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AbstractCompactionKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/WatchProcessorTest.java, modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/throttling/ThrottlingTest.java
https://issues.apache.org/jira/browse/IGNITE-25175
=> IGNITE-25175 New tests & refactoring in metastorage

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/mapping/FragmentMappingTest.java
The test passes.
https://issues.apache.org/jira/browse/IGNITE-25093
---
=> IGNITE-25093 Sql. FragmentMappingTest testCorrelated uses random distribution instead of affinity

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/ZoneResourcesManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerRecoveryTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-25177
=> IGNITE-25177 Fix NullPointerException in TableManagerTest when colocation is enabled

modules/table/src/main/java/org/apache/ignite/internal/table/IndexWrapper.java, modules/table/src/main/java/org/apache/ignite/internal/table/TableImpl.java
https://issues.apache.org/jira/browse/IGNITE-25180
=> IGNITE-25180 Fix race between drop index and partition garbage collection

modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/causalitydatanodes/DistributionZoneCausalityDataNodesTest.java
https://issues.apache.org/jira/browse/IGNITE-25176
=> IGNITE-25176 Mute flaky checkDataNodesRepeatedOnNodeAdded test

modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageManagerImplTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/ReadOperationForCompactionTracker.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AbstractCompactionKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/BasicOperationsKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/ReadOperationForCompactionTrackerTest.java, modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java
https://issues.apache.org/jira/browse/IGNITE-25183
=> IGNITE-25183 Revisit ReadOperationForCompactionTracker usages

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/WatchProcessor.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-25189
=> IGNITE-25189 Implement graceful WatchProcessor stop

modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/failure/FailureManagerExtension.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/failure/MuteFailureManagerLogging.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/log4j2/Log4jUtils.java, modules/core/src/testFixtures/resources/log4j2-test.xml, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/sqllogic/ItSqlLogicTest.java
https://issues.apache.org/jira/browse/IGNITE-25192
=> IGNITE-25192 Mute FailureManager logging in SQL Logic 1 suite

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlApiBaseTest.java
=> IGNITE-25049 Sql. Improve itSqlClientSynchronousApiTest.testTimeZoneId

modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/impl/StandaloneMetaStorageManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/disaster/DisasterRecoveryMsInvokeTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/gc/MvGcTest.java
https://issues.apache.org/jira/browse/IGNITE-25210
=> IGNITE-25210 Fix FH invocations in table module unit tests

modules/marshaller-common/src/main/java/org/apache/ignite/internal/marshaller/FieldAccessor.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/marshaller/KvMarshallerTest.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/marshaller/RecordMarshallerTest.java
=> IGNITE-24898 Fixed broken serialization in table views when a column is mapped to a primitive field using TypeConverter

modules/index/src/main/java/org/apache/ignite/internal/index/IndexBuildController.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/impl/MetaStorageLeaderElectionListenerTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/time/ClusterTimeTest.java
https://issues.apache.org/jira/browse/IGNITE-25224
=> IGNITE-25224 Close ClusterTime in MetaStorageLeaderElectionListenerTest

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/PartitionScanPublisher.java
=> IGNITE-24988 Sql. Improve error handling in PartitionScanPublisher

modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageCompactionTriggerOneNodeTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/KeyValueStorage.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/KeyValueStorageUtils.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AbstractCompactionKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/KeyValueStorageUtilsTest.java
https://issues.apache.org/jira/browse/IGNITE-25227
=> IGNITE-25227 Fix meta-storage compaction algorithm

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItBigZoneOperationTest.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/ZonePartitionReplicaListener.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/ZonePartitionRaftListener.java
https://issues.apache.org/jira/browse/IGNITE-24991
=> IGNITE-24991 Enable ItBigZoneOperationTest

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java
https://issues.apache.org/jira/browse/IGNITE-25237
=> IGNITE-25237 Fix failed ItMetaStorageWatchTest.testReplayUpdates

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaStateManager.java
https://issues.apache.org/jira/browse/IGNITE-25242
=> IGNITE-25242 Handle NodeStoppingException in ReplicaStateManager

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-25245
=> IGNITE-25245 Ignore NodeStoppingException in startPartitionAndStartClient

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageCompactionTrigger.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/CompactionStatisticsHolder.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java
https://issues.apache.org/jira/browse/IGNITE-25034
=> IGNITE-25034 Enrich meta-storage compaction logs

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItBigZoneOperationTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/LocalPartitionReplicaEvent.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-24943
=> IGNITE-24943 Fix table stop on zone replica stop

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/PartitionReplicatorNodeRecovery.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-25248
=> IGNITE-25248 Fix race between storage creation and node stop

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java
https://issues.apache.org/jira/browse/IGNITE-25254
=> IGNITE-25254 Ignore NodeStoppingException in PartitionReplicaLifecycleManager

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DataNodesHistory.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DataNodesHistoryEntry.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DataNodesManager.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneTimer.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngineV2.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DataNodesManagerTest.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaStateManager.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItDataSchemaSyncTest.java
https://issues.apache.org/jira/browse/IGNITE-25234
=> IGNITE-25234 Fix ItDataSchemaSyncTest.queryWaitAppropriateSchema

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCorrelatesTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PlannerPhase.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rule/logical/IgniteSubQueryRemoveRule.java
=> IGNITE-25253 Sql. Correlated query failed with: Required columns {3} not subset of left columns {0, 1, 2}

modules/index/src/main/java/org/apache/ignite/internal/index/IndexBuildController.java
https://issues.apache.org/jira/browse/IGNITE-25267
=> IGNITE-25267 Handle closed storages in IndexBuildController

modules/sql-engine/src/integrationTest/sql/group1/aggregate/group/test_group_by.test, modules/sql-engine/src/integrationTest/sql/group1/aggregate/group/test_group_by_alias.test
=> IGNITE-25077 expects error on using expressions with aliases in group by clause.

modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationDynamicDefaultsPatcherImpl.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/hocon/HoconConverter.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/tree/ConverterToMapVisitor.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/tree/ConverterToMapVisitorBuilder.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/util/ConfigurationFlattener.java, modules/runner/src/main/java/org/apache/ignite/internal/configuration/storage/LocalFileConfigurationStorage.java, modules/runner/src/test/java/org/apache/ignite/internal/configuration/storage/LocalFileConfigurationModule.java, modules/runner/src/test/java/org/apache/ignite/internal/configuration/storage/LocalFileConfigurationStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-25271
=> IGNITE-25271 Do not render deprecated configuration values

modules/core/src/main/java/org/apache/ignite/internal/lang/IgniteSystemProperties.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/ZoneRebalanceUtil.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/transactions/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryManagerTest.java, modules/transactions/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryReconfigurationTest.java
https://issues.apache.org/jira/browse/IGNITE-24232
=> IGNITE-24232 Implement correct node restart behavior when forced pending

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCorrelatesTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rule/logical/IgniteSubQueryRemoveRule.java
https://issues.apache.org/jira/browse/IGNITE-25275
----------
=> IGNITE-25275 Sql. Correlated sub-query in ON classes of join cannot be rewritten

modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItCmgDisasterRecoveryTest.java
https://issues.apache.org/jira/browse/IGNITE-25259
=> IGNITE-25259 Fix ItCmgDisasterRecoveryTest in colocation mode

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/datatypes/ItCastToTsWithLocalTimeZoneTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionContext.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/RexImpTable.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/RexToLixTranslator.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/IgniteMethod.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/IgniteSqlDateTimeUtils.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/RuntimeSortedIndexTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestBuilders.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/util/IgniteSqlDateTimeUtilsTest.java
https://issues.apache.org/jira/browse/IGNITE-25174
=> IGNITE-25174 Fix CURRENT_DATE.

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/raft/ItZonePartitionRaftListenerRecoveryTest.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/raft/ZonePartitionRaftListenerTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ReplicasSafeTimePropagationTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/PartitionCommandListenerTest.java, modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-25262
=> IGNITE-25262 Restore double-write protection with colocation

modules/core/src/main/java/org/apache/ignite/internal/lang/IgniteSystemProperties.java, modules/sql-engine/build.gradle, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItLimitOffsetTest.java
https://issues.apache.org/jira/browse/IGNITE-25261
=> IGNITE-25261 ItLimitOffsetTest#testInvalidLimitOffset fixed.

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java
https://issues.apache.org/jira/browse/IGNITE-25291
=> IGNITE-25291 Improve node stop handling in PartitionReplicaLifecycleManager

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ddl/DdlCommandHandlerExceptionHandlingTest.java
https://issues.apache.org/jira/browse/IGNITE-25222
Protect version tracker update with busy lock to avoid TrackerClosedException on update application
=> IGNITE-25222 Improve node stop handling in CatalogManagerImpl

modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/PersistentTxStateVacuumizer.java
https://issues.apache.org/jira/browse/IGNITE-25292
=> IGNITE-25292 Improve node stop handling in PersistentTxStateVacuumizer

modules/metrics/src/main/java/org/apache/ignite/internal/metrics/exporters/PushMetricExporter.java, modules/metrics/src/test/java/org/apache/ignite/internal/metrics/MetricConfigurationTest.java, modules/metrics/src/test/java/org/apache/ignite/internal/metrics/exporters/PushExporterTest.java, modules/metrics/src/test/java/org/apache/ignite/internal/metrics/exporters/TestExporter.java, modules/metrics/src/test/java/org/apache/ignite/internal/metrics/exporters/configuration/TestExporterConfigurationSchema.java, modules/metrics/src/test/java/org/apache/ignite/internal/metrics/exporters/configuration/TestPushExporterConfigurationSchema.java
https://issues.apache.org/jira/browse/IGNITE-25280
=> IGNITE-25280 Fix PushMetricExporter reconfiguration

build.gradle
https://issues.apache.org/jira/browse/IGNITE-25299
=> IGNITE-25299 Add application run configuration options to build.gradle

modules/runner/src/testFixtures/java/org/apache/ignite/internal/ClusterPerClassIntegrationTest.java
=> IGNITE-24399 Sql. Use DDL batching to perform dropAllTables, dropAllSchemas etc in tests

modules/index/src/main/java/org/apache/ignite/internal/index/IndexBuildTask.java
https://issues.apache.org/jira/browse/IGNITE-25304
=> IGNITE-25304 Improve ignorable exceptions detection in IndexBuildTask

modules/network/src/main/java/org/apache/ignite/internal/network/scalecube/ScaleCubeTopologyService.java, modules/network/src/test/java/org/apache/ignite/internal/network/scalecube/ScaleCubeTopologyServiceTest.java
https://issues.apache.org/jira/browse/IGNITE-25300
=> IGNITE-25300 Fix NoSuchElementException in ScaleCubeTopologyService

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/AbstractZoneReplicationTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItAbstractColocationTest.java
https://issues.apache.org/jira/browse/IGNITE-25307
=> IGNITE-25307 Fix ItReplicaLifecycleTest.testAlterReplicaTriggerDefaultZone

modules/catalog-compaction/src/main/java/org/apache/ignite/internal/catalog/compaction/CatalogCompactionRunner.java, modules/catalog-compaction/src/test/java/org/apache/ignite/internal/catalog/compaction/CatalogCompactionRunnerSelfTest.java
https://issues.apache.org/jira/browse/IGNITE-25167
-----------
=> IGNITE-25167 Catalog compaction should ignore NodeStoppingException

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rel/IgniteIndexScan.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rel/IgniteTableScan.java
=> IGNITE-25321 Sql. Fix compilation after IGNITE-25001

modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/NodeImpl.java
https://issues.apache.org/jira/browse/IGNITE-25325
=> IGNITE-25325 Fix prevote logging in NodeImpl

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/ZonePartitionReplicaListener.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/ZonePartitionReplicaListenerTest.java
https://issues.apache.org/jira/browse/IGNITE-25326
=> IGNITE-25326 Throw exception when handling replica request for destroyed table

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/PlacementDriverMessageProcessor.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java, modules/replicator/src/test/java/org/apache/ignite/internal/replicator/PlacementDriverReplicaSideTest.java
https://issues.apache.org/jira/browse/IGNITE-25272
=> IGNITE-25272 Move the replica-side lease negotiation flow to dedicated thread pool

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/PartitionScanPublisher.java
https://issues.apache.org/jira/browse/IGNITE-25334
=> IGNITE-25334 Improve assertion message in PartitionScanPublisher

modules/raft-api/src/main/java/org/apache/ignite/internal/raft/configuration/RaftConfigurationSchema.java
https://issues.apache.org/jira/browse/IGNITE-18480
=> IGNITE-18480 Set default for raft.installSnapshotTimeoutMillis to MAX_VALUE

modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/PlacementDriverManager.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/negotiation/LeaseNegotiator.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/LeaseNegotiationTest.java
https://issues.apache.org/jira/browse/IGNITE-23246
=> IGNITE-23246 Fixed leaking LeaseAgreements

modules/schema/src/main/java/org/apache/ignite/internal/schema/BinaryTupleComparatorUtils.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/PartialBinaryTupleMatcher.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/BinaryTupleComparatorTest.java
https://issues.apache.org/jira/browse/IGNITE-25340
=> IGNITE-25340 Incorrect tuple comparison in B-tree prefix

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-25345
=> IGNITE-25345 Improve handling of closed storages on node stop

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImplTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractExecutionTest.java
=> IGNITE-25221 Fix incorrect component stopping after test completed.

modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/config/schema/WebhookSinkConfigurationSchema.java, modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/impl/WebhookSink.java
=> IGNITE-25333 Bogus javadoc in WebhookSink.

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/LocalPartitionReplicaEventParameters.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerRecoveryTest.java
https://issues.apache.org/jira/browse/IGNITE-25355
=> IGNITE-25355 Fix zone replica recovery flow

modules/raft/src/main/java/org/apache/ignite/internal/raft/RaftGroupServiceImpl.java
https://issues.apache.org/jira/browse/IGNITE-25374
=> IGNITE-25374 Retry on ESTOP in RaftGroupServiceImpl

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/PartitionStatesMetricSource.java, modules/transactions/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryMetricTest.java
https://issues.apache.org/jira/browse/IGNITE-25123
=> IGNITE-25123 Support metrics for the colocation track

modules/sql-engine/src/integrationTest/sql/group1/types/timestamp/test_incorrect_timestamp_ltz.test
=> IGNITE-25232 Sql. Fix flaky test_incorrect_timestamp_ltz.test

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/outgoing/OutgoingSnapshotsManager.java
https://issues.apache.org/jira/browse/IGNITE-25384
=> IGNITE-25384 Ignore StorageClosedException in Raft snapshot streaming

modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TransactionExpirationRegistry.java
https://issues.apache.org/jira/browse/IGNITE-25385
* sets of transactions in txsByExpirationTime can be accessed concurrently (due to ConcurrentSkipListMap properties), so a concurrent set is used now to represent them
* we now handle NoSuchElementException from setIterator.next() that can happen due to concurrency
`TransactionExpirationRegistryBenchmark` results before the change
```
Benchmark                                                Mode  Cnt   Score    Error  Units
TransactionExpirationRegistryBenchmark2.register        thrpt   25  34,333 ±  3,354  ops/s
TransactionExpirationRegistryBenchmark2.register10      thrpt   25  74,290 ± 24,262  ops/s
TransactionExpirationRegistryBenchmark2.registerExpire  thrpt   25  16,293 ±  1,875  ops/s
```
Results after the change
```
Benchmark …
```
=> IGNITE-25385 Make TransactionExpirationRegistry thread-safe

modules/transactions/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryReconfigurationTest.java
https://issues.apache.org/jira/browse/IGNITE-25381
=> IGNITE-25381 Fix several ItDisasterRecoveryReconfigurationTest tests.

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/NullMvTableStorage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/NullStorageEngine.java
https://issues.apache.org/jira/browse/IGNITE-25356
=> IGNITE-25356 Switch to NaiveAsyncReadWriteLock

modules/replicator/src/main/java/org/apache/ignite/internal/raft/client/TopologyAwareRaftGroupService.java
https://issues.apache.org/jira/browse/IGNITE-25398
=> IGNITE-25398 Handle RecipientLeftException in topology-aware raft client

docs/_docs/administrators-guide/config/storage/volatile.adoc
=> IGNITE-24661 Fix volatile storage docs

modules/api/src/main/java/org/apache/ignite/catalog/definitions/TableDefinition.java, modules/catalog-dsl/src/main/java/org/apache/ignite/internal/catalog/sql/CreateTableImpl.java, modules/catalog-dsl/src/test/java/org/apache/ignite/internal/catalog/sql/CreateTableTest.java, modules/catalog-dsl/src/test/java/org/apache/ignite/internal/catalog/sql/InvalidDefinitionTest.java
=> IGNITE-24576 Catalog API - Add validation for sort order definition in Hash indexes

packaging/docker/docker-compose.yml
=> IGNITE-24496 Fix variable interpolation in packaging docker-compose

modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/Replicator.java
https://issues.apache.org/jira/browse/IGNITE-25399
=> IGNITE-25399 Fixed unclear and ugly log message "[Replicator] Replicator Replicator"

modules/network-api/src/main/java/org/apache/ignite/internal/network/RecipientLeftException.java, modules/network/src/integrationTest/java/org/apache/ignite/internal/network/netty/ItConnectionManagerTest.java, modules/network/src/main/java/org/apache/ignite/internal/network/DefaultMessagingService.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/ConnectionManager.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryClientHandshakeManager.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/message/HandshakeRejectionReason.java, modules/network/src/test/java/org/apache/ignite/internal/network/recovery/message/HandshakeRejectionReasonTest.java
https://issues.apache.org/jira/browse/IGNITE-25400
=> IGNITE-25400 Explicitly reject network connections to self

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSecondaryIndexTest.java, modules/sql-engine/src/main/codegen/includes/parserImpls.ftl, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/ddl/DdlSqlToCommandConverter.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/AbstractParserTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/SqlDdlParserTest.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/StorageSortedIndexDescriptor.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/util/StorageUtils.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/engine/AbstractStorageEngineTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractSortedIndexStorageTest.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/ColumnFamilyUtils.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/ColumnFamilyUtilsTest.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/instance/SharedRocksDbInstanceTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/IndexBaseTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/SortedIndexLockerTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/StorageCleanupTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/StorageUpdateHandlerTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerIndexLockingTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerSortedIndexLockingTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/ZonePartitionReplicaListenerTest.java
https://issues.apache.org/jira/browse/IGNITE-25352
-----------
=> IGNITE-25352 Sql. Support NULL ORDERING for indexes

modules/api/src/main/java/org/apache/ignite/table/KeyValueView.java, modules/api/src/main/java/org/apache/ignite/table/RecordView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientKeyValueBinaryView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientKeyValueView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientRecordBinaryView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientRecordView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/api/PublicApiClientKeyValueView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/api/PublicApiClientRecordView.java, modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofKeyValueView.java, modules/runner/src/main/java/org/apache/ignite/internal/restart/RestartProofRecordView.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/ClusterPerClassIntegrationTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/AsyncApiKeyValueViewAdapter.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/AsyncApiRecordViewAdapter.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/RemoveAllApiTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/KeyValueBinaryViewImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/KeyValueViewImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/PublicApiThreadingKeyValueView.java, modules/table/src/main/java/org/apache/ignite/internal/table/PublicApiThreadingRecordView.java, modules/table/src/main/java/org/apache/ignite/internal/table/RecordBinaryViewImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/RecordViewImpl.java
https://issues.apache.org/jira/browse/IGNITE-25392
=> IGNITE-25392 Implement removeAll()/deleteAll() in KV and Record views

modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/log4j2/LogInspector.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/server/ItConnectionErrorTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/server/JraftAbstractTest.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/RaftGroupServiceImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/Replicator.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/core/ReplicatorTest.java
https://issues.apache.org/jira/browse/IGNITE-25394
=> IGNITE-25394 Fixed log flooding on remaining nodes when a node is stopped

modules/failure-handler/src/main/java/org/apache/ignite/internal/failure/FailureManager.java, modules/failure-handler/src/test/java/org/apache/ignite/internal/failure/FailureProcessorTest.java
https://issues.apache.org/jira/browse/IGNITE-21461
=> IGNITE-21461 Add an ability to dynamically change failure handler configuration

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/configuration/schema/PersistentPageMemoryProfileConfigurationSchema.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/configuration/schema/VolatilePageMemoryProfileConfigurationSchema.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/configurations/StorageProfileConfigurationSchema.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/StorageEngine.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/engine/AbstractStorageEngineTest.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryStorageEngine.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryStorageEngine.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryDataRegionTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/engine/PersistentPageMemoryStorageEngineTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/engine/VolatilePageMemoryStorageEngineTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/BlobStorageTest.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageEngine.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/configuration/schema/RocksDbProfileConfigurationSchema.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/engine/RocksDbStorageEngineTest.java
https://issues.apache.org/jira/browse/IGNITE-24495
=> IGNITE-24495 Dynamically compute data region sizes

migration-tools/modules/ignite2-repack/build.gradle, migration-tools/modules/ignite3-repack/build.gradle, migration-tools/modules/ignite3-slim-repack/build.gradle
=> IGNITE-25364 Fix migration-tools repack modules publishing settings

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/QueryTimeoutTest.java
=> IGNITE-25416: test QueryTimeoutTest#testTimeoutDistributedRead mute

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItColocatedDataTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSetOpTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/externalize/RelJson.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/SqlSchemaManagerImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/trait/DistributionFunction.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/trait/IgniteDistributions.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/PartitionProvidersTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/DmlPlannerTest.java, modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/BaseSqlIntegrationTest.java
=> IGNITE-18426 Sql. Fix distribution function to use the distribution zone ID instead of the table ID

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-25426
=> IGNITE-25426 Ignore NodeStoppingException when destroying table

modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/flush/RocksDbFlusher.java, modules/rocksdb-common/src/test/java/org/apache/ignite/internal/rocksdb/flush/RocksDbFlusherTest.java
https://issues.apache.org/jira/browse/IGNITE-25378
=> IGNITE-25378 Retry flush requests on RocksDb write throttling

modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
https://issues.apache.org/jira/browse/IGNITE-25433
=> IGNITE-25433 Indicate zone based replication on node start

modules/sql-engine/src/main/codegen/config.fmpp, modules/sql-engine/src/main/codegen/includes/parserImpls.ftl, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/externalize/RelJson.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteSqlValidator.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PrepareServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlExplain.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/ExplainPlanForParserTest.java
https://issues.apache.org/jira/browse/IGNITE-25368
=> IGNITE-25368 Sql. Make PLAN FOR optional in EXPLAIN PLAN FOR

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/partitions/reset/ItResetPartitionsTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/partitions/restart/ItRestartPartitionsTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/recovery/partitions/states/ItPartitionStatesTest.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/reset/ResetPartitionsCall.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/restart/RestartPartitionsCall.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/call/recovery/states/PartitionStatesCall.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/recovery/partitions/reset/ResetPartitionsMixin.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/recovery/partitions/restart/RestartPartitionsTest.java, modules/core/src/main/java/org/apache/ignite/internal/lang/IgniteSystemProperties.java
https://issues.apache.org/jira/browse/IGNITE-25104
=> IGNITE-25104 Support DisasterRecoveryManager methods in CLI for the Colocation track

modules/jdbc/src/test/java/org/apache/ignite/internal/jdbc/JdbcResultSetTest.java
Fixes java 11 compatibility.
https://issues.apache.org/jira/browse/IGNITE-25439
---
- [Apache Ignite Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Java+Code+Style+Guid …
=> IGNITE-25439 Jdbc. Fix java 11 compatibility in tests

modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/NodeImpl.java
https://issues.apache.org/jira/browse/IGNITE-24314
=> IGNITE-24314 Fix flaky ItNodeTest.testInstallSnapshotWithThrottle

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItPublicApiColocationTest.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/ClusterPerClassIntegrationTest.java
https://issues.apache.org/jira/browse/IGNITE-17557
=> IGNITE-17557 enable ItPublicApiColocationTest tests

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceRaftGroupEventsListener.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/ZoneRebalanceRaftGroupEventsListener.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java
https://issues.apache.org/jira/browse/IGNITE-17592
=> IGNITE-17592 Fix synchronous await on futures in raft group events rebalance listener

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/TpcdsQueryPlannerTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/schema/SqlSchemaManagerImplTest.java, modules/sql-engine/src/test/resources/tpcds/plan/q64_colocated.plan
https://issues.apache.org/jira/browse/IGNITE-25432
=> IGNITE-25432 Fix SqlSchemaManagerImplTest and TpcdsQueryPlannerTest when the colocation enabled

modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationChanger.java
https://issues.apache.org/jira/browse/IGNITE-25459
=> IGNITE-25459 Improve Configuration framework error handling

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-25468
=> IGNITE-25468 Fix TableManager.tablesPerZoneLocks releasing

modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/flush/RocksDbFlusher.java, modules/rocksdb-common/src/test/java/org/apache/ignite/internal/rocksdb/flush/RocksDbFlusherTest.java
https://issues.apache.org/jira/browse/IGNITE-25463
=> IGNITE-25463 Fix flaky RocksDbFlusherTest

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceRaftGroupEventsListener.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtil.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/ZoneRebalanceRaftGroupEventsListener.java
https://issues.apache.org/jira/browse/IGNITE-25445
=> IGNITE-25445 Do not block on PartitionMover future

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/PlacementDriverMessageProcessor.java
https://issues.apache.org/jira/browse/IGNITE-25206
=> IGNITE-25206 Fixed Lease granted message not handled due to timeout

modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxCleanupRequestHandler.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java
https://issues.apache.org/jira/browse/IGNITE-25469
=> IGNITE-25469 Perform cleanup in a separate thread pool

modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationRegistry.java, modules/distribution-zones/build.gradle, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/configuration/schema/PersistentPageMemoryProfileConfigurationSchema.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/configuration/schema/VolatilePageMemoryProfileConfigurationSchema.java, modules/partition-replicator/build.gradle, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/storageprofile/ItStorageProfilesTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/testframework/TestIgnitionManager.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/configurations/StorageProfileConfigurationSchema.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/StorageEngine.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/engine/AbstractStorageEngineTest.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryStorageEngine.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryStorageEngine.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryDataRegionTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/engine/VolatilePageMemoryStorageEngineTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/BlobStorageTest.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageEngine.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/configuration/schema/RocksDbProfileConfigurationSchema.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/engine/RocksDbStorageEngineTest.java
https://issues.apache.org/jira/browse/IGNITE-25425
=> IGNITE-25425 Dynamically compute data region sizes

modules/transactions/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryReconfigurationTest.java
https://issues.apache.org/jira/browse/IGNITE-25481
=> IGNITE-25481 Fix NPE in ItDisasterRecoveryReconfigurationTest#testIncompleteRebalanceBeforeAutomaticResetPartitions

modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/recovery/ItDisasterRecoveryControllerRestartPartitionsTest.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/recovery/ItDisasterRecoveryControllerTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/mapping/MappingServiceImplTest.java
https://issues.apache.org/jira/browse/IGNITE-25447
=> IGNITE-25447 Use annotation to conditionally disable mismatching colocation tests

modules/core/src/main/java/org/apache/ignite/internal/util/FastTimestamps.java
https://issues.apache.org/jira/browse/IGNITE-25494
=> IGNITE-25494 Improve FastTimestamps

modules/runner/src/integrationTest/java/org/apache/ignite/internal/ItTruncateRaftLogAndRestartNodesTest.java
https://issues.apache.org/jira/browse/IGNITE-24802
=> IGNITE-24802 Investigate test "enter a node with an index greater than the current majority"

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/TpcdsColocatedQueryPlannerTest.java, modules/sql-engine/src/test/resources/tpcds/plan/q64_colocated.plan
https://issues.apache.org/jira/browse/IGNITE-25500
=> IGNITE-25500 Add TpcdsColocatedQueryPlannerTest for the colocation track

docs/_docs/developers-guide/clients/java.adoc, modules/client/src/main/java/org/apache/ignite/internal/client/ClientMetricSource.java, modules/core/src/main/java/org/apache/ignite/internal/streamer/StreamerSubscriber.java, modules/core/src/test/java/org/apache/ignite/internal/streamer/StreamerSubscriberTest.java
Fix `requestMore` and `close`:
* Minimize contention 
* Do not call user code under lock
* Handle exceptions in user code
=> IGNITE-25361 Fix StreamerSubscriber user code invoke under lock

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/StorageUpdateHandler.java
https://issues.apache.org/jira/browse/IGNITE-25506
=> IGNITE-25506 Investigate flaky ItTxDistributedTestThreeNodesThreeReplicasCollocated#testBalance

modules/network/src/integrationTest/java/org/apache/ignite/internal/network/scalecube/ItScaleCubeNetworkMessagingTest.java, modules/network/src/main/java/org/apache/ignite/internal/network/NettyBootstrapFactory.java, modules/network/src/main/java/org/apache/ignite/internal/network/configuration/AbstractSslConfigurationSchema.java, modules/network/src/main/java/org/apache/ignite/internal/network/configuration/InboundConfigurationSchema.java, modules/network/src/main/java/org/apache/ignite/internal/network/configuration/NetworkConfigurationSchema.java, modules/network/src/main/java/org/apache/ignite/internal/network/configuration/OutboundConfigurationSchema.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/ConnectionManager.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/NettyClient.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/NettySender.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/NettyServer.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/HandshakeManagerUtils.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/HandshakeTieBreaker.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryAcceptorHandshakeManager.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryInitiatorHandshakeManager.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryInitiatorHandshakeManagerFactory.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/message/HandshakeFinishMessage.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/message/HandshakeRejectedMessage.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/message/HandshakeStartMessage.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/message/HandshakeStartResponseMessage.java, modules/network/src/test/java/org/apache/ignite/internal/network/DefaultMessagingServiceTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/netty/NettyClientTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/netty/RecoveryHandshakeTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/recovery/RecoveryAcceptorHandshakeManagerTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/recovery/RecoveryInitiatorHandshakeManagerTest.java, modules/workers/src/integrationTest/java/org/apache/ignite/internal/worker/ItCriticalWorkerMonitoringTest.java
https://issues.apache.org/jira/browse/IGNITE-25006
=> IGNITE-25006 Rename client/server roles in server-to-server protocol

modules/network/src/main/java/org/apache/ignite/internal/network/configuration/ClusterMembershipConfigurationSchema.java
https://issues.apache.org/jira/browse/IGNITE-25324
=> IGNITE-25324 Increase scalecube suspicion timeout

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointManager.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointReadWriteLock.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointManagerTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointReadWriteLockTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointTimeoutLockTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointWorkflowTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/replacement/AbstractPageReplacementTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/throttling/PageMemoryThrottlingTest.java, modules/page-memory/src/testFixtures/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointTestUtils.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryDataStorageModule.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryStorageEngine.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryMvTableStorageTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryNoLoadTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/engine/PersistentPageMemoryStorageEngineTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/PersistentPageMemoryHashIndexStorageTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/PersistentPageMemorySortedIndexStorageTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorageConcurrencyTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorageGcTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorageTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvTableStorageConcurrencyTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/gc/PersistentPageMemoryGcUpdateHandlerTest.java
https://issues.apache.org/jira/browse/IGNITE-20068
=> IGNITE-20068 Print warning if checkpoint read lock took substantial time

modules/runner/src/testFixtures/java/org/apache/ignite/internal/ClusterPerClassIntegrationTest.java
https://issues.apache.org/jira/browse/IGNITE-25566
=> IGNITE-25566 Make some ClusterPerClassIntegrationTest.sql methods public

modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItAbstractColocationTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
* Fix invoke mocking in Node class
* Remove unnecessary busy lock usage in TableManager
https://issues.apache.org/jira/browse/IGNITE-25562 …
=> IGNITE-25562 Minor refactoring

modules/network/src/integrationTest/java/org/apache/ignite/internal/network/netty/ItConnectionManagerTest.java, modules/network/src/main/java/org/apache/ignite/internal/network/DefaultMessagingService.java, modules/network/src/main/java/org/apache/ignite/internal/network/LocalIpAddresses.java, modules/network/src/main/java/org/apache/ignite/internal/network/NodeFinderFactory.java, modules/network/src/main/java/org/apache/ignite/internal/network/RecipientInetAddress.java, modules/network/src/main/java/org/apache/ignite/internal/network/handshake/CriticalHandshakeException.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/ConnectionManager.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryInitiatorHandshakeManager.java, modules/network/src/main/java/org/apache/ignite/internal/network/scalecube/ScaleCubeClusterServiceFactory.java, modules/network/src/test/java/org/apache/ignite/internal/network/DefaultMessagingServiceTest.java
https://issues.apache.org/jira/browse/IGNITE-25480
=> IGNITE-25480 Consider local addresses in 'not my IP address' detection

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-25591
=> IGNITE-25591 Fix races on listeners registration and replica starts

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/PlacementDriverMessageProcessor.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaReservationFailedException.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaStateManager.java, modules/replicator/src/test/java/org/apache/ignite/internal/replicator/PlacementDriverReplicaSideTest.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/recovery/ItDisasterRecoveryControllerRestartPartitionsTest.java
https://issues.apache.org/jira/browse/IGNITE-25434
=> IGNITE-25434 Fixed critical system error on processPlacementDriverMessage

modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/distributionzones/ItDistributionZoneMetaStorageCompactionTest.java
https://issues.apache.org/jira/browse/IGNITE-25601
=> IGNITE-25601 Fix ItDistributionZoneMetaStorageCompactionTest.testCompaction

modules/transactions/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryReconfigurationTest.java
https://issues.apache.org/jira/browse/IGNITE-24818
=> IGNITE-24818 Add tests to check lease time is present

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/snapshot/outgoing/OutgoingSnapshot.java
https://issues.apache.org/jira/browse/IGNITE-25674
=> IGNITE-25674 Fix race between closing OutgoingSnapshot and iterating tx states

modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/NodeImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/Replicator.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/impl/LogManagerImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/snapshot/local/LocalSnapshotStorage.java
https://issues.apache.org/jira/browse/IGNITE-25679
=> IGNITE-25679 Do not log harmless events on WARN in JRaft

modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationChanger.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/util/ConfigurationFlattener.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/util/ConfigurationUtil.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/util/KeysTrackingConfigurationVisitor.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/RenamedConfigurationTest.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/util/ConfigurationUtilTest.java, modules/runner/src/main/java/org/apache/ignite/internal/configuration/storage/LocalFileConfigurationStorage.java
https://issues.apache.org/jira/browse/IGNITE-25458
=> IGNITE-25458 Fix deletion of renamed configuration from the storage

modules/raft/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/schemasync/ItSchemaSyncAndReplicationTest.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/Cluster.java
https://issues.apache.org/jira/browse/IGNITE-25678
=> IGNITE-25678 Fix laggingSchemasPreventPartitionDataReplication

modules/metrics/src/main/java/org/apache/ignite/internal/metrics/AtomicDoubleMetric.java, modules/metrics/src/main/java/org/apache/ignite/internal/metrics/sources/JvmMetricSource.java, modules/metrics/src/main/java/org/apache/ignite/internal/metrics/sources/OsMetricSource.java, modules/metrics/src/test/java/org/apache/ignite/internal/metrics/sources/JvmMetricSourceTest.java, modules/metrics/src/test/java/org/apache/ignite/internal/metrics/sources/OsMetricSourceTest.java
https://issues.apache.org/jira/browse/IGNITE-25639
=> IGNITE-25639 Enrich JVM and Os metrics

modules/sql-engine/src/integrationTest/sql/group1/explain/mapping.test, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/mapping/FragmentPrinter.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/mapping/MappingUtils.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PlannerHelper.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rel/IgniteReceiver.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rel/IgniteSender.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rel/explain/ExplainUtils.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rel/explain/IgniteRelWriter.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rel/explain/RelTreeToTextWriter.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/SqlSchemaManagerImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/trait/TraitUtils.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/mapping/FragmentMappingTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/mapping/MappingTestRunner.java, modules/sql-engine/src/test/resources/mapping/correlated.test, modules/sql-engine/src/test/resources/mapping/dml.test, modules/sql-engine/src/test/resources/mapping/hash_join.test, modules/sql-engine/src/test/resources/mapping/merge_join.test, modules/sql-engine/src/test/resources/mapping/set_ops.test, modules/sql-engine/src/test/resources/mapping/table_affinity.test, modules/sql-engine/src/test/resources/mapping/table_functions.test, modules/sql-engine/src/test/resources/mapping/table_identity.test, modules/sql-engine/src/test/resources/mapping/table_identity_single.test, modules/sql-engine/src/test/resources/mapping/table_single.test, modules/sql-engine/src/test/resources/mapping/test_backup_mapping.test, modules/sql-engine/src/test/resources/mapping/test_partition_pruning.test, modules/sql-engine/src/test/resources/mapping/union.test, modules/sql-engine/src/test/resources/mapping/values.test
https://issues.apache.org/jira/browse/IGNITE-25413
----
=> IGNITE-25413 Sql. Make FragmentPrinter configurable

modules/core/src/main/java/org/apache/ignite/internal/lang/IgniteSystemProperties.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/placement-driver-api/src/testFixtures/java/org/apache/ignite/internal/placementdriver/TestPlacementDriver.java
https://issues.apache.org/jira/browse/IGNITE-25074
=> IGNITE-25074 ItRebalanceDistributedTest adaptation to the colocaiton track.

modules/network/src/main/java/org/apache/ignite/internal/network/MulticastNodeFinder.java
https://issues.apache.org/jira/browse/IGNITE-25629
=> IGNITE-25629 Fix registering listeners for multicast request

modules/metrics/build.gradle, modules/metrics/src/testFixtures/java/org/apache/ignite/internal/metrics/TestMetricManager.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/PersistentPageMemory.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/BaseMvTableStorageTest.java, modules/storage-page-memory/build.gradle, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/AbstractPageMemoryTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryDataRegion.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryStorageEngine.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryMvTableStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-25630
=> IGNITE-25630 Add some data region metrics for aipersist

modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteServerImpl.java
https://issues.apache.org/jira/browse/IGNITE-25694
=> IGNITE-25694 Add JMX configuration for remote monitoring to logs

modules/runner/src/testFixtures/java/org/apache/ignite/internal/table/NodeUtils.java
* Consider all candidates when checking for success
* Rotate candidates on fail
https://issues.apache.org/jira/browse/IGNITE-25705
=> IGNITE-25705 Improve transferPrimary performance

modules/sql-engine/src/integrationTest/sql/group1/explain/mapping.test
Adds mapping tests for Sender/Receiver.
https://issues.apache.org/jira/browse/IGNITE-25551
---
- [Apache Ignite Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Java+Code …
=> IGNITE-25551 Sql. Explain. Improve test coverage of sender and receiver

modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationChanger.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationRegistry.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/notifications/ConfigurationListenerTest.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/BaseIgniteRestartTest.java, modules/security/src/main/java/org/apache/ignite/internal/security/authentication/AuthenticationManagerImpl.java
https://issues.apache.org/jira/browse/IGNITE-25536
=> IGNITE-25536 Do not notify configuration listeners on start

modules/client-common/src/main/java/org/apache/ignite/internal/client/proto/ProtocolBitmaskFeature.java, modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/ItClientHandlerMetricsTest.java, modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/ItClientHandlerTest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientHandlerModule.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/jdbc/JdbcQueryCursor.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlExecuteRequest.java, modules/client/build.gradle, modules/client/src/main/java/org/apache/ignite/client/IgniteClient.java, modules/client/src/main/java/org/apache/ignite/client/IgniteClientConfiguration.java, modules/client/src/main/java/org/apache/ignite/internal/client/IgniteClientConfigurationImpl.java, modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java, modules/client/src/main/java/org/apache/ignite/internal/client/TcpIgniteClient.java, modules/client/src/main/java/org/apache/ignite/internal/client/sql/ClientAsyncResultSet.java, modules/client/src/main/java/org/apache/ignite/internal/client/sql/ClientPartitionAwarenessMetadata.java, modules/client/src/main/java/org/apache/ignite/internal/client/sql/ClientResultSetMetadata.java, modules/client/src/main/java/org/apache/ignite/internal/client/sql/ClientSql.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTable.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTables.java, modules/client/src/test/java/org/apache/ignite/client/ClientMetricsTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientSqlTest.java, modules/client/src/test/java/org/apache/ignite/client/RetryPolicyTest.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeCursor.java, modules/jdbc/src/main/java/org/apache/ignite/internal/jdbc/JdbcConnection.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/api/AsyncResultSetImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/AsyncSqlCursor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/AsyncSqlCursorImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/fsm/QueryExecutor.java
https://issues.apache.org/jira/browse/IGNITE-25561
-----
=> IGNITE-25561 Sql. Transfer partition awareness meta to the client

modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/CompareIndexColumnsValue.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/PageMemoryHashIndexStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/io/HashIndexTreeIo.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/hash/AbstractPageMemoryHashIndexStorageTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/hash/PersistentPageMemoryHashIndexStorageTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/hash/VolatilePageMemoryHashIndexStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-25740
=> IGNITE-25740 Fix hash index comparator in aipersist/aimem

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/CliIntegrationTest.java, modules/core/src/main/java/org/apache/ignite/internal/thread/AbstractStripedThreadPoolExecutor.java, modules/metrics/src/main/java/org/apache/ignite/internal/metrics/DistributionMetric.java, modules/metrics/src/main/java/org/apache/ignite/internal/metrics/sources/StripedThreadPoolMetricSource.java, modules/metrics/src/main/java/org/apache/ignite/internal/metrics/sources/ThreadPoolMetricSource.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/metrics/ItMetricControllerTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/ThreadPoolsManager.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlQueryProcessor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/QueryTaskExecutorImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PrepareServiceImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImplTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/ExchangeExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestNode.java
=> IGNITE-25638 Add sql striped thread pool executor metrics

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/handlers/WriteIntentSwitchRequestHandler.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/PartitionReplicationMessageGroup.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/command/WriteIntentSwitchCommand.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/network/command/WriteIntentSwitchCommandV2.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/ZonePartitionRaftListener.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/handlers/WriteIntentSwitchCommandHandler.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/command/PartitionRaftCommandsSerializationTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/PartitionCommandListenerTest.java
https://issues.apache.org/jira/browse/IGNITE-25734
=> IGNITE-25734 Fix WriteIntentSwitchCommand compatibility

modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/serialization/BaseMethodNameResolver.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/serialization/MessageDeserializerGenerator.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/serialization/MessageReaderMethodResolver.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/serialization/MessageSerializerGenerator.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/serialization/MessageWriterMethodResolver.java, modules/network-api/src/main/java/org/apache/ignite/internal/network/annotations/PropertyName.java
https://issues.apache.org/jira/browse/IGNITE-25764
=> IGNITE-25764 Add @PropertyName for @Transferable interfaces

modules/raft-api/src/main/java/org/apache/ignite/internal/raft/configuration/DisruptorConfigurationSchema.java, modules/raft-api/src/main/java/org/apache/ignite/internal/raft/configuration/RaftConfigurationSchema.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/Loza.java
https://issues.apache.org/jira/browse/IGNITE-24428
=> IGNITE-24428 Make disruptor queue configurable

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/DataRegion.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/configuration/CheckpointConfiguration.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointManager.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/Checkpointer.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/compaction/Compactor.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointManagerTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointerTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/compaction/CompactorTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/replacement/AbstractPageReplacementTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/throttling/PageMemoryThrottlingTest.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryStorageEngine.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/configuration/schema/PageMemoryCheckpointConfigurationSchema.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/configuration/schema/PersistentPageMemoryStorageEngineConfigurationSchema.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryNoLoadTest.java
https://issues.apache.org/jira/browse/IGNITE-25770
=> IGNITE-25770 Remove checkpoint configuration schema from page-memory

modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/BasePlacementDriverTest.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/LeaseBatch.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/LeaseTracker.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/LeaseNegotiationTest.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/LeaseUpdaterTest.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/leases/LeaseSerializationTest.java
https://issues.apache.org/jira/browse/IGNITE-25785
=> IGNITE-25785 Remove intermediate byte buffer from LeaseBatch.fromBytes

modules/compatibility-tests/src/integrationTest/java/org/apache/ignite/internal/ItCompatibilityTest.java
https://issues.apache.org/jira/browse/IGNITE-25647
=> IGNITE-25647 Fix RAFT messages incompatibility

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/metrics/SqlQueryMetricSource.java
=> IGNITE-25791 Sql. Remove unused metric

modules/core/src/main/java/org/apache/ignite/internal/util/GridUnsafe.java
https://issues.apache.org/jira/browse/IGNITE-25796
=> IGNITE-25796 Fix ItCompatibilityTest#testCompatibility for MAC

modules/platforms/dotnet/Apache.Ignite/Internal/ClientFailoverSocket.cs
Simplify `ConnectAllSockets` to establish connections sequentially - `ConnectAsync` uses `_socketLock` anyway.
The `TestClientDropsConnectionOnClusterIdMismatch` test failure from the ticket was caused by `if (connectTask.IsCompleted) { continue; }` part which skips the task if it completes quickly and swallows the error.
=> IGNITE-25713 .NET: Fix ConnectAllSockets error handling race condition

modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/ItPrimaryReplicaChoiceTest.java
https://issues.apache.org/jira/browse/IGNITE-25799
=> IGNITE-25799 Fix flaky ItPrimaryReplicaChoiceTest#testPrimaryChangeLongHandling

modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteServerImpl.java
https://issues.apache.org/jira/browse/IGNITE-21874
=> IGNITE-21874 Log OS info to the server log at startup

modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteServerImpl.java
https://issues.apache.org/jira/browse/IGNITE-25817
=> IGNITE-25817 Log jvm info to the server log at startup

modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/recovery/GlobalPartitionStateResponse.java, modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/recovery/LocalPartitionStateResponse.java, modules/rest/src/main/java/org/apache/ignite/internal/rest/recovery/DisasterRecoveryController.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/DisasterRecoveryManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/TableState.java
https://issues.apache.org/jira/browse/IGNITE-25833
=> IGNITE-25833 Restore RecoveryApi compatibility

buildscripts/jmh.gradle, check-rules/spotbugs-excludes.xml, modules/transactions/src/jmh/java/org/apache/ignite/internal/tx/impl/TransactionExpirationRegistryBenchmark.java
https://issues.apache.org/jira/browse/IGNITE-25812
=> IGNITE-25812 Add necessary JMH dependencies to jmh.gradle

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlApiBaseTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/NestedLoopJoinNode.java, modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/BaseSqlIntegrationTest.java
=> IGNITE-25658 Sql. Cannot cancel a query fragment with a sequence of NestedLoopJoin operators

modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/RocksDbSharedLogStorage.java
https://issues.apache.org/jira/browse/IGNITE-25837
=> IGNITE-25837 Fix "end key comes before start key" error in RocksDbSharedLogStorage#truncateSuffix

modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/LeaseTracker.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/LeaseTrackerTest.java
https://issues.apache.org/jira/browse/IGNITE-25842
=> IGNITE-25842 Propagate exceptions in LeaseTracker.awaitPrimaryReplica

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/WatchProcessor.java
https://issues.apache.org/jira/browse/IGNITE-25865
=> IGNITE-25865 Reduce metastorage watch notification executor to 1 thread

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java
https://issues.apache.org/jira/browse/IGNITE-25866
=> IGNITE-25866 Fix critical system error on node stopping

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/AbstractTpcQueryPlannerTest.java
=> IGNITE-25820 Fix failed test TpcdsQueryPlannerTest.test([59] 59) on JDK 21

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/disaster/DisasterRecoveryManager.java
https://issues.apache.org/jira/browse/IGNITE-25860
=> IGNITE-25860 fix NoSuchElementException when get partition states.

README.md
https://issues.apache.org/jira/browse/IGNITE-25879
=> IGNITE-25879 Fix Link to documentation in README

modules/catalog-compaction/src/integrationTest/java/org/apache/ignite/internal/catalog/compaction/ItCatalogCompactionTest.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceMinimumRequiredTimeProviderImpl.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceMinimumRequiredTimeProviderImplTest.java
=> IGNITE-25867 Catalog compaction never happens after zone was dropped with all its tables.

modules/core/src/main/java/org/apache/ignite/internal/lang/IgniteSystemProperties.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/runner/src/main/java/org/apache/ignite/internal/schema/SchemaSafeTimeTrackerImpl.java, modules/runner/src/test/java/org/apache/ignite/internal/schema/SchemaSafeTimeTrackerImplTest.java
https://issues.apache.org/jira/browse/IGNITE-25885
=> IGNITE-25885 Recover schema safe time on node start

modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/ItReplicaLifecycleTest.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/ZoneResourcesManager.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/StorageEngine.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryStorageEngine.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/instance/SharedRocksDbInstance.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/BrokenTxStateStorage.java, modules/transactions/build.gradle, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/ThreadAssertingTxStateStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/TxStatePartitionStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/TxStateStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateMetaRocksDbPartitionStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbPartitionStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbSharedStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbStorage.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/rocksdb/RocksDbTxStateStorageTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbSharedStorageTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/test/TestTxStateStorageTest.java, modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/AbstractTxStatePartitionStorageTest.java, modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/AbstractTxStateStorageTest.java, modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/test/TestTxStateStorage.java
https://issues.apache.org/jira/browse/IGNITE-25886
=> IGNITE-25886 Implement method to get on-disk tables/zones IDs in tx state storage

modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/raft/ItZonePartitionRaftListenerRecoveryTest.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/ZoneResourcesManagerTest.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/DefaultLogStorageFactory.java, modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/LoggingRocksDbFlushListener.java, modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/flush/RocksDbFlushListener.java, modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/flush/RocksDbFlusher.java, modules/rocksdb-common/src/test/java/org/apache/ignite/internal/rocksdb/flush/RocksDbFlusherTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageEngine.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/instance/SharedRocksDbInstanceCreator.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/instance/SharedRocksDbInstanceTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerRecoveryTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbSharedStorage.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/rocksdb/RocksDbTxStatePartitionStorageTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateMetaRocksDbPartitionStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-25904
=> IGNITE-25904 Add node info to LoggingRocksDbFlushListener for log

modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/rocksdb/RocksDbTxStateStorageTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbSharedStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-25907
=> IGNITE-25907 Add logging of some node info on startup

modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceByPendingAssignmentsQueueTest.java
https://issues.apache.org/jira/browse/IGNITE-25917
=> IGNITE-25917 Disable flaky test

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java
https://issues.apache.org/jira/browse/IGNITE-25925
=> IGNITE-25925 Improve logging in PartitionReplicaLifecycleManager#changePeersOnRebalance

modules/compatibility-tests/src/testFixtures/java/org/apache/ignite/internal/OpenApiMatcher.java, modules/compatibility-tests/src/testFixtures/java/org/apache/ignite/internal/OpenApiMatcherTest.java
https://issues.apache.org/jira/browse/IGNITE-25831
=> IGNITE-25831 Add enums support to OpenAPI test

modules/compatibility-tests/build.gradle, modules/compatibility-tests/src/integrationTest/java/org/apache/ignite/internal/ItCompatibilityTest.java, modules/compatibility-tests/src/testFixtures/java/org/apache/ignite/internal/IgniteCluster.java, modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/config/schema/WebhookSinkConfigurationSchema.java, modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/config/schema/WebhookSinkRetryPolicyConfigurationSchema.java
https://issues.apache.org/jira/browse/IGNITE-25862
=> IGNITE-25862 Fix event log configuration compatibility

modules/metrics/src/main/java/org/apache/ignite/internal/metrics/DistributionMetric.java, modules/metrics/src/main/java/org/apache/ignite/internal/metrics/MetricRegistry.java, modules/metrics/src/main/java/org/apache/ignite/internal/metrics/exporters/PushMetricExporter.java, modules/metrics/src/main/java/org/apache/ignite/internal/metrics/exporters/configuration/LogPushExporterConfigurationSchema.java, modules/metrics/src/main/java/org/apache/ignite/internal/metrics/exporters/log/LogPushExporter.java, modules/metrics/src/test/java/org/apache/ignite/internal/metrics/DistributionMetricTest.java, modules/metrics/src/test/java/org/apache/ignite/internal/metrics/exporters/log/LogPushExporterTest.java
https://issues.apache.org/jira/browse/IGNITE-25937
=> IGNITE-25937 Extend the configuration of metric log exporter with optional white list of enabled metric sources

modules/network/src/main/java/org/apache/ignite/internal/network/netty/OutboundEncoder.java
https://issues.apache.org/jira/browse/IGNITE-26024
=> IGNITE-26024 Reuse allocated DirectMessageWriter instances

modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItCmgDisasterRecoveryTest.java, modules/system-disaster-recovery/src/integrationTest/java/org/apache/ignite/internal/disaster/system/ItMetastorageGroupDisasterRecoveryTest.java, modules/system-disaster-recovery/src/main/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImpl.java, modules/system-disaster-recovery/src/test/java/org/apache/ignite/internal/disaster/system/SystemDisasterRecoveryManagerImplTest.java
https://issues.apache.org/jira/browse/IGNITE-25894
=> IGNITE-25894 Do not allow MG repair to be run when MG has majority

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItCommonApiTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PlannerHelper.java
=> IGNITE-25896 Sql. Make root node support project with duplicate names.

modules/compatibility-tests/build.gradle, modules/compatibility-tests/src/testFixtures/java/org/apache/ignite/internal/CompatibilityTestBase.java
https://issues.apache.org/jira/browse/IGNITE-26042
=> IGNITE-26042 Use boolean property in the compatibility tests

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/metric/ItClusterMetricCommandTest.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/decorators/ClusterMetricSourceListDecorator.java
https://issues.apache.org/jira/browse/IGNITE-26011
=> IGNITE-26011 Rename the "Description" column to "Availability" in the cli metrics list

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/CliIntegrationTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/metric/ItClusterMetricCommandTest.java, modules/rest/src/main/java/org/apache/ignite/internal/rest/metrics/ClusterMetricController.java, modules/rest/src/main/java/org/apache/ignite/internal/rest/metrics/NodeMetricController.java
https://issues.apache.org/jira/browse/IGNITE-26036
=> IGNITE-26036 Add sorting in the list of metrics for cli by name

modules/catalog-compaction/src/test/java/org/apache/ignite/internal/catalog/compaction/CatalogCompactionRunnerSelfTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java, modules/client-handler/src/testFixtures/java/org/apache/ignite/client/handler/FakeCatalogService.java, modules/client/src/main/java/org/apache/ignite/internal/client/tx/ClientLazyTransaction.java, modules/client/src/test/java/org/apache/ignite/client/PartitionAwarenessTest.java, modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/threading/ItComputeApiThreadingTest.java, modules/compute/src/jobs/java/org/apache/ignite/internal/compute/InfiniteMapReduceTask.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/streamer/StreamerReceiverJob.java, modules/core/src/test/java/org/apache/ignite/lang/CancelHandleHelperSelfTest.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngine.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngineV2.java, modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/impl/ConfigurationBasedChannelRegistry.java, modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/impl/ConfigurationBasedSinkRegistry.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/schema/ExecutorInclinedSchemaSyncServiceTest.java, modules/placement-driver-api/src/test/java/org/apache/ignite/internal/placementdriver/wrappers/ExecutorInclinedPlacementDriverTest.java, modules/replicator/src/test/java/org/apache/ignite/internal/replicator/PlacementDriverReplicaSideTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/app/NoOpMapReduceTask.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/PlatformTestNodeRunner.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientComputeTest.java, modules/runner/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/ConditionalWatchInhibitor.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/systemviews/ItComputeSystemViewTest.java, modules/system-disaster-recovery/src/test/java/org/apache/ignite/internal/disaster/system/MetastorageRepairImplTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImplTest.java, modules/transactions/src/jmh/java/org/apache/ignite/internal/tx/impl/TransactionExpirationRegistryBenchmark.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/impl/TransactionExpirationRegistryConcurrentTest.java
https://issues.apache.org/jira/browse/IGNITE-26058
=> IGNITE-26058 Replace uses of СompletableFuture.completedFuture(null) with CompletableFutures#nullCompletedFuture in code base

modules/core/src/test/java/org/apache/ignite/internal/replicator/TablePartitionIdTest.java, modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManager.java, modules/partition-replicator/src/test/java/org/apache/ignite/internal/partition/replicator/PartitionReplicaLifecycleManagerTest.java, modules/raft-api/src/main/java/org/apache/ignite/internal/raft/StoredRaftNodeId.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/server/ItJraftServerTest.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/Loza.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/server/RaftServer.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/DataStorageManager.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/partition/ItPartitionDestructionTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableUtils.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableUtilsTest.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbSharedStorage.java
https://issues.apache.org/jira/browse/IGNITE-25621
=> IGNITE-25621 Implement reliable table destruction on node recovery

modules/low-watermark/src/main/java/org/apache/ignite/internal/lowwatermark/LowWatermarkImpl.java, modules/raft/build.gradle, modules/raft/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItParallelRaftSnapshotsTest.java
https://issues.apache.org/jira/browse/IGNITE-26035
=> IGNITE-26035 Add rebalancing test via raft snapshot and low watermark change

modules/raft/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItParallelRaftSnapshotsTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/gc/GcStorageHandler.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/gc/MvGc.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/gc/StorageRemovedException.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/gc/MvGcTest.java
https://issues.apache.org/jira/browse/IGNITE-26034
=> IGNITE-26034 Rebalancing via raft snapshot does not work after low watermark update

migration-tools/modules/migration-tools-commons/src/main/java/org/apache/ignite/migrationtools/sql/SqlDdlGenerator.java
=> IGNITE-26076 Update TODO reference for IGNITE-23268 to IGNITE-25351

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDmlTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteSqlToRelConvertor.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/DmlPlannerTest.java
=> IGNITE-26014 Sql. ArrayIndexOutOfBoundsException when converting MERGE with join

modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/raft/handlers/WriteIntentSwitchCommandHandler.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/partition/ItPartitionDestructionTest.java
https://issues.apache.org/jira/browse/IGNITE-26051
=> IGNITE-26051 Ignore destroyed tables in write intent switch command

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestClusterTest.java
https://issues.apache.org/jira/browse/IGNITE-26033
It was the test itself to blame. Test table has 25 partitions, each partition returns 3_333 rows. In the test, 10_000 rows were request, and it was assumed that both nodes contribute to the result. In fact, on rare occasions the first node (aka initiator) managed to fulfill the request, so propagation of timestamp from other node to initiator didn't happen by the time of the verification.
----
\- The JIRA ticket has the Patch …
=> IGNITE-26033 Sql. Fix TestClusterTest.testHybridTimestampPropagationToInitiator

modules/schema/src/main/java/org/apache/ignite/internal/schema/BinaryRowConverter.java
https://issues.apache.org/jira/browse/IGNITE-26195
=> IGNITE-26195 Reduce the number of lambda allocations in BinaryRowConverter

modules/raft/src/integrationTest/java/org/apache/ignite/raft/server/ItConnectionErrorTest.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/RaftGroupServiceImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/ReplicatorGroupImpl.java
https://issues.apache.org/jira/browse/IGNITE-26031
=> IGNITE-26031 Fix ItConnectionErrorTest.testStopLeader/Follower

docs/_docs/administrators-guide/config/node-config.adoc, modules/runner/src/testFixtures/java/org/apache/ignite/internal/testframework/TestIgnitionManager.java, modules/workers/src/main/java/org/apache/ignite/internal/worker/configuration/CriticalWorkersConfigurationSchema.java
https://issues.apache.org/jira/browse/IGNITE-26205
=> IGNITE-26205 Raise maxAllowedLagMillis default to 5 seconds

modules/client-handler/src/main/java/org/apache/ignite/client/handler/JdbcQueryEventHandlerImpl.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlExecuteRequest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/SelectBenchmark.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/benchmark/SqlMultiStatementBenchmark.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/BaseSqlMultiStatementTest.java, modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlMultiStatementTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/api/IgniteSqlImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlProperties.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/fsm/MultiStatementHandler.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/fsm/ValidationHelper.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/Commons.java, modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/engine/util/QueryCheckerImpl.java
https://issues.apache.org/jira/browse/IGNITE-26198
=> IGNITE-26198 Added SQL property to optionally restrict query execution with multiple statements

modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageWatchTest.java
=> IGNITE-26207 Fix flaky ItMetaStorageWatchTest

modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/PersistentTxStateVacuumizer.java
https://issues.apache.org/jira/browse/IGNITE-26030
=> IGNITE-26030 Fix critical system error on raft client stop

.idea/checkstyle-idea.xml, gradle/libs.versions.toml
https://issues.apache.org/jira/browse/IGNITE-26236
=> IGNITE-26236 Downgrade checkstyle plugin to 10.26.1

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/CliIntegrationTest.java, modules/core/src/main/java/org/apache/ignite/internal/hlc/ClockServiceImpl.java, modules/core/src/test/java/org/apache/ignite/internal/hlc/ClockServiceTest.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItIdempotentCommandCacheTest.java, modules/metrics/src/main/java/org/apache/ignite/internal/metrics/sources/ClockServiceMetricSource.java, modules/metrics/src/test/java/org/apache/ignite/internal/metrics/sources/ClockServiceMetricSourceTest.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/metrics/ItMetricControllerTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/storage/InternalTableEstimatedSizeTest.java
https://issues.apache.org/jira/browse/IGNITE-26122
=> IGNITE-26122 Add metric for clock drift

modules/core/src/main/java/org/apache/ignite/internal/thread/IgniteThreadFactory.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointReadWriteLock.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointWorkflow.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/Checkpointer.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/IgniteCheckpointThread.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/IgniteCheckpointThreadFactory.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointReadWriteLockTest.java
https://issues.apache.org/jira/browse/IGNITE-25590
=> IGNITE-25590 Add node name to checkpointer thread names

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/PersistentPageMemory.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/replacement/ClockPageReplacementPolicy.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/replacement/RandomLruPageReplacementPolicy.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/replacement/SegmentedLruPageReplacementPolicy.java
https://issues.apache.org/jira/browse/IGNITE-26252
=> IGNITE-26252 Minor code refactoring related to partition generation in PersistentPageMemory

modules/eventlog/src/main/java/org/apache/ignite/internal/eventlog/impl/ConfigurationBasedSinkRegistry.java
https://issues.apache.org/jira/browse/IGNITE-26251
=> IGNITE-26251 Fix event sink leak

modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryMvTableStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-26255
=> IGNITE-26255 Testing checkpoint after partition destruction in PersistentPageMemory

modules/transactions/src/integrationTest/java/org/apache/ignite/internal/disaster/DisasterRecoveryTestUtil.java, modules/transactions/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryManagerTest.java, modules/transactions/src/integrationTest/java/org/apache/ignite/internal/disaster/ItDisasterRecoveryReconfigurationTest.java
https://issues.apache.org/jira/browse/IGNITE-26265
=> IGNITE-26265 fix flaky testTwoPhaseResetEqualLogIndex

check-rules/spotbugs-excludes.xml, gradle/libs.versions.toml, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java, modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/snapshot/RocksSnapshotManager.java
https://issues.apache.org/jira/browse/IGNITE-26287
=> IGNITE-26287 Upgrade Spotbugs to 4.9.4

modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItMapReduceTest.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/task/TaskExecutionInternal.java, modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientComputeTest.java
https://issues.apache.org/jira/browse/IGNITE-25640
=> IGNITE-25640 Fix cancelled compute task status

modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/serialization/MessageWriterMethodResolver.java, modules/network-annotation-processor/src/test/java/org/apache/ignite/internal/network/processor/tests/SerializatersAndDeserializersFieldNamesTest.java
https://issues.apache.org/jira/browse/IGNITE-26319
=> IGNITE-26319 Use correct field name for writing marshallable field

modules/core/src/main/java/org/apache/ignite/internal/failure/FailureContext.java, modules/core/src/main/java/org/apache/ignite/internal/thread/ThreadUtils.java, modules/failure-handler/src/main/java/org/apache/ignite/internal/failure/FailureManager.java
https://issues.apache.org/jira/browse/IGNITE-26275
=> IGNITE-26275 Add failure context id

modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryMvTableStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-25861
=> IGNITE-25861 Add more tests for partition generation change

modules/client/src/test/java/org/apache/ignite/client/ClientComputeTest.java, modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/ItMapReduceTest.java, modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/events/ItComputeEventsEmbeddedTest.java, modules/compute/src/integrationTest/java/org/apache/ignite/internal/compute/utils/InteractiveTasks.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/ComputeComponentImpl.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/IgniteComputeImpl.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/executor/ComputeExecutor.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/executor/ComputeExecutorImpl.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/executor/platform/PlatformComputeConnection.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/executor/platform/dotnet/DotNetComputeExecutor.java, modules/compute/src/main/java/org/apache/ignite/internal/compute/task/TaskExecutionInternal.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientComputeTest.java
https://issues.apache.org/jira/browse/IGNITE-26317
=> IGNITE-26317 Cleanup compute module

modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DataNodesManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-26310
=> IGNITE-26310 Fix flaky DataNodesManagerTest#removeNodesWithScheduledScaleDown

modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/replacement/AbstractPageReplacementTest.java
https://issues.apache.org/jira/browse/IGNITE-26244
=> IGNITE-26244 Fix AbstractPageReplacementTest.testFsyncDeltaFilesWillNotStartOnCheckpointUntilPageReplacementIsComplete

modules/platforms/python/tests/test_fetch_table.py
https://issues.apache.org/jira/browse/IGNITE-26308
Muted the test until heartbeats are implemented.
=> IGNITE-26308 Mute the test until heartbeats are implemented

modules/transactions/src/integrationTest/java/org/apache/ignite/internal/tx/ItTxTimeoutOneNodeTest.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadWriteTransactionImpl.java
https://issues.apache.org/jira/browse/IGNITE-25918
=> IGNITE-25918 Fix datarace in ReadWriteTransactionImpl

docs/_docs/developers-guide/clients/overview.adoc
=> IGNITE-25616 Document jdbc\thin partition awareness usage

modules/client/src/test/java/org/apache/ignite/client/ClientMetricsTest.java
Ticket: https://issues.apache.org/jira/browse/IGNITE-26221
=> IGNITE-26221 Relax assertions in org.apache.ignite.client.ClientMetricsTest.testHandshakesFailedTimeout

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientConnectionTest.java
https://issues.apache.org/jira/browse/IGNITE-26444
=> IGNITE-26444 Use global client in testExceptionHasHint

modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java, modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ZonePartitionReplicaImpl.java
https://issues.apache.org/jira/browse/IGNITE-26327
=> IGNITE-26327 Fix testDestroyPartitionStoragesOnEvictNode and timeouts

check-rules/spotbugs-excludes.xml, modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/segstore/IndexMemTable.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/segstore/SegmentFileManager.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/segstore/SegmentPayload.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/segstore/SegstoreLogStorage.java, modules/raft/src/test/java/org/apache/ignite/internal/raft/storage/segstore/DeserializedSegmentPayload.java, modules/raft/src/test/java/org/apache/ignite/internal/raft/storage/segstore/IndexMemTableTest.java, modules/raft/src/test/java/org/apache/ignite/internal/raft/storage/segstore/SegmentFileManagerTest.java, modules/raft/src/test/java/org/apache/ignite/internal/raft/storage/segstore/SegstoreLogStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-26272
=> IGNITE-26272 Implement index memtable for the new log storage

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSecondaryIndexTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/RexUtils.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/IndexSearchBoundsPlannerTest.java
https://issues.apache.org/jira/browse/IGNITE-26471
=> IGNITE-26471 Fix NPE when building multibounds for hash index

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/io/DataPageIo.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-26518
=> IGNITE-26518 Fix free list corruption caused by specific binary rows

modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxAbstractDistributedTestSingleNode.java
https://issues.apache.org/jira/browse/IGNITE-26522
=> IGNITE-26522 Fix timeouts in ItTxDistributedTestSingleNode.testImplicitTransactionTimeout

modules/distribution-zones/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtil.java, modules/partition-replicator/src/integrationTest/java/org/apache/ignite/internal/partition/replicator/fixtures/Node.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/runner/src/main/java/org/apache/ignite/internal/app/ThreadPoolsManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-26545
=> IGNITE-26545 Fix shutdown TableManager#rebalanceScheduler

modules/core/src/test/java/org/apache/ignite/internal/testframework/ExecutorServiceExtensionTest.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/ExecutorServiceExtension.java
https://issues.apache.org/jira/browse/IGNITE-26551
=> IGNITE-26551 Expand the information in RejectedExecutionException for pools from ExecutorServiceExtension

modules/compute/src/main/java/org/apache/ignite/internal/compute/loader/JobClassLoader.java, modules/compute/src/test/java/org/apache/ignite/internal/compute/loader/JobClassLoaderFactoryTest.java
https://issues.apache.org/jira/browse/IGNITE-26533
Use proper double-checked locking for initializing the class loader to prevent leaks.
=> IGNITE-26533 Job class loader is leaking

modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryInitiatorHandshakeManager.java
https://issues.apache.org/jira/browse/IGNITE-26572
=> IGNITE-26572 Improve error message for handshake failure due to wrong cluster ID

modules/sql-engine/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItUnstableTopologyTest.java
https://issues.apache.org/jira/browse/IGNITE-26590
=> IGNITE-26590 ItUnstableTopologyTest.ensureLostOfNodeDoesntCausesQueryToFail test mute

modules/index/src/integrationTest/java/org/apache/ignite/internal/index/ItIndexAndRestartTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-26588
=> IGNITE-26588 Interpret missing partition set info as empty set

modules/network/src/main/java/org/apache/ignite/internal/network/recovery/HandshakeManagerUtils.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryAcceptorHandshakeManager.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryInitiatorHandshakeManager.java, modules/network/src/test/java/org/apache/ignite/internal/network/recovery/HandshakeManagerTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/recovery/RecoveryAcceptorHandshakeManagerTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/recovery/RecoveryInitiatorHandshakeManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-26601
=> IGNITE-26601 Throw RecipientLeftException if other side rejects handshake due to stopping

modules/page-memory/build.gradle, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/PersistentPageMemory.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/PersistentPageMemoryMetricSource.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/PersistentPageMemoryMetrics.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/PersistentPageMemoryMetricsTest.java
https://issues.apache.org/jira/browse/IGNITE-26594
=> IGNITE-26594 Add aipersist data region metrics

modules/platforms/dotnet/Apache.Extensions.Caching.Ignite.Tests/IgniteDistributedCacheTests.cs
https://issues.apache.org/jira/browse/IGNITE-26529
=> IGNITE-26529 .NET: Fix IgniteDistributedCacheTests.TestCustomTableAndColumnNames flakiness

modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/segstore/CheckpointQueue.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/segstore/RaftLogCheckpointer.java, modules/raft/src/test/java/org/apache/ignite/internal/raft/storage/segstore/CheckpointQueueTest.java, modules/raft/src/test/java/org/apache/ignite/internal/raft/storage/segstore/RaftLogCheckpointerTest.java
https://issues.apache.org/jira/browse/IGNITE-26618
=> IGNITE-26618 Unblock threads waiting on Raft storage checkpoint on stop

migration-tools/modules/e2e-ai3-tests/src/integrationTest/java/org/apache/ignite/migrationtools/tests/e2e/DataMigrationWithIgnite3ClientTest.java, migration-tools/modules/migration-tools-commons/src/main/java/org/apache/ignite/migrationtools/sql/SqlDdlGenerator.java, migration-tools/modules/migration-tools-commons/src/test/java/org/apache/ignite/migrationtools/sql/sql/SqlDdlGeneratorTest.java, migration-tools/modules/migration-tools-persistence/src/integrationTest/java/org/apache/ignite/migrationtools/persistence/CacheDdlCreationFromWorkDirTest.java, migration-tools/modules/migration-tools-persistence/src/main/java/org/apache/ignite/migrationtools/persistence/Ignite2PersistentCacheTools.java, migration-tools/tools/e2e-tests-framework/framework-core/src/main/java/org/apache/ignite/migrationtools/tests/e2e/framework/core/ExampleBasedCacheTest.java, migration-tools/tools/e2e-tests-framework/framework-core/src/main/java/org/apache/ignite/migrationtools/tests/e2e/framework/core/NameUtils.java, migration-tools/tools/e2e-tests-framework/implementations/src/main/java/org/apache/ignite/migrationtools/tests/e2e/impl/MySimpleMapCacheTest.java, migration-tools/tools/e2e-tests-framework/implementations/src/main/java/org/apache/ignite/migrationtools/tests/e2e/impl/VeryBasicAbstractCacheTest.java
Ticket: https://issues.apache.org/jira/browse/IGNITE-26539
Commits:
* Update integration tests to account for schemas
* Add support for Schemas
This PR must be merged after https://issues.apache.org/jira/browse/IGNITE-26520.
=> IGNITE-26539 Add support for SQL Schemas

modules/core/src/main/java/org/apache/ignite/internal/util/ExceptionUtils.java, modules/core/src/test/java/org/apache/ignite/internal/util/ExceptionUtilsTest.java
https://issues.apache.org/jira/browse/IGNITE-26648
=> IGNITE-26648 Fix missing stacktraces for ExceptionInInitializerErrors
