apache/ignite-3

modules/configuration-annotation-processor/src/test/java/org/apache/ignite/configuration/sample/storage/ConfigurationChangerTest.java, modules/configuration-annotation-processor/src/test/java/org/apache/ignite/configuration/sample/storage/TestConfigurationStorage.java, modules/configuration/src/main/java/org/apache/ignite/configuration/ConfigurationChanger.java, modules/configuration/src/main/java/org/apache/ignite/configuration/storage/ConfigurationStorage.java
=> IGNITE-14178 Configuration storage interface made asynchronous.

modules/configuration/src/main/java/org/apache/ignite/configuration/ConfigurationChanger.java, modules/configuration/src/main/java/org/apache/ignite/configuration/ConfigurationRegistry.java, modules/rest/src/main/java/org/apache/ignite/rest/RestModule.java, modules/rest/src/main/java/org/apache/ignite/rest/configuration/InMemoryConfigurationStorage.java, modules/rest/src/main/java/org/apache/ignite/rest/configuration/RestConfigurationSchema.java, modules/rest/src/main/java/org/apache/ignite/rest/presentation/json/JsonConverter.java, modules/runner/src/main/java/org/apache/ignite/app/IgniteRunner.java, modules/runner/src/main/java/org/apache/ignite/configuration/ConfigurationModule.java, modules/runner/src/main/java/org/apache/ignite/configuration/extended/LocalConfigurationSchema.java
=> IGNITE-14442 Fixed NPE in IgniteRunner caused by broken REST module.

modules/configuration-annotation-processor/src/integrationTest/java/org/apache/ignite/configuration/processor/internal/AbstractProcessorTest.java, modules/configuration-annotation-processor/src/integrationTest/java/org/apache/ignite/configuration/processor/internal/ConfigSet.java, modules/configuration-annotation-processor/src/integrationTest/java/org/apache/ignite/configuration/processor/internal/ITProcessorTest.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/configuration/processor/internal/ConfigurationDescription.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/configuration/processor/internal/ConfigurationElement.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/configuration/processor/internal/Processor.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/configuration/processor/internal/Utils.java, modules/configuration-annotation-processor/src/test/java/org/apache/ignite/configuration/ConfigurationChangerTest.java, modules/configuration-annotation-processor/src/test/java/org/apache/ignite/configuration/internal/util/ConfigurationUtilTest.java, modules/configuration-annotation-processor/src/test/java/org/apache/ignite/configuration/sample/ConfigurationArrayTest.java, modules/configuration-annotation-processor/src/test/java/org/apache/ignite/configuration/sample/ConstructableTreeNodeTest.java, modules/configuration-annotation-processor/src/test/java/org/apache/ignite/configuration/sample/NodeConfigurationSchema.java, modules/configuration-annotation-processor/src/test/java/org/apache/ignite/configuration/sample/TraversableTreeNodeTest.java, modules/configuration-annotation-processor/src/test/java/org/apache/ignite/configuration/sample/UsageTest.java, modules/configuration/src/main/java/org/apache/ignite/configuration/ConfigurationRegistry.java, modules/configuration/src/main/java/org/apache/ignite/configuration/NamedConfigurationTree.java, modules/configuration/src/main/java/org/apache/ignite/configuration/annotation/Config.java, modules/configuration/src/main/java/org/apache/ignite/configuration/annotation/Value.java, modules/configuration/src/main/java/org/apache/ignite/configuration/internal/DynamicConfiguration.java, modules/configuration/src/main/java/org/apache/ignite/configuration/internal/NamedListConfiguration.java, modules/configuration/src/main/java/org/apache/ignite/configuration/internal/util/ConfigurationNotificationsUtil.java, modules/configuration/src/main/java/org/apache/ignite/configuration/internal/validation/ImmutableValidator.java, modules/configuration/src/main/java/org/apache/ignite/configuration/internal/validation/ValidationContextImpl.java, modules/configuration/src/main/java/org/apache/ignite/configuration/tree/NamedListChange.java, modules/configuration/src/main/java/org/apache/ignite/configuration/tree/NamedListNode.java, modules/configuration/src/main/java/org/apache/ignite/configuration/validation/Immutable.java
=> IGNITE-13840 INIT classes removed from configuration framework.

modules/network/src/integrationTest/java/org/apache/ignite/network/TestMessage.java, modules/network/src/integrationTest/java/org/apache/ignite/network/scalecube/ITScaleCubeNetworkMessagingTest.java, modules/network/src/main/java/org/apache/ignite/network/scalecube/DelegatingTransportFactory.java, modules/network/src/main/java/org/apache/ignite/network/scalecube/ScaleCubeClusterServiceFactory.java, modules/network/src/main/java/org/apache/ignite/network/scalecube/ScaleCubeTopologyService.java
https://issues.apache.org/jira/browse/IGNITE-14682
=> IGNITE-14682 Fix sending messages from a node to itself

modules/metastorage-client/pom.xml, modules/metastorage-client/src/integrationTest/java/org/apache/ignite/internal/metastorage/client/ITMetaStorageServiceTest.java, modules/network/pom.xml, modules/network/src/integrationTest/java/org/apache/ignite/network/scalecube/TestScaleCubeClusterServiceFactory.java, modules/raft/pom.xml, modules/raft/src/integrationTest/java/org/apache/ignite/raft/server/ITRaftCounterServerTest.java, modules/table/pom.xml, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ITDistributedTableTest.java, parent/pom.xml
=> IGNITE-14717 Wide use of TestScaleCubeClusterServiceFactory.

modules/network/src/main/java/org/apache/ignite/network/scalecube/ScaleCubeClusterServiceFactory.java
=> IGNITE-14770 Added unregistration of scalecube mx bean.

modules/api/src/main/java/org/apache/ignite/configuration/schemas/runner/ClusterConfigurationSchema.java, modules/api/src/main/java/org/apache/ignite/configuration/schemas/runner/NodeConfigurationSchema.java, modules/api/src/main/java/org/apache/ignite/configuration/schemas/table/ColumnConfigurationSchema.java, modules/api/src/main/java/org/apache/ignite/configuration/schemas/table/ColumnTypeConfigurationSchema.java, modules/api/src/main/java/org/apache/ignite/configuration/schemas/table/IndexColumnConfigurationSchema.java, modules/api/src/main/java/org/apache/ignite/configuration/schemas/table/TableConfigurationSchema.java, modules/api/src/main/java/org/apache/ignite/configuration/schemas/table/TableIndexConfigurationSchema.java, modules/api/src/main/java/org/apache/ignite/configuration/schemas/table/TablesConfigurationSchema.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/configuration/processor/internal/Processor.java, modules/configuration-annotation-processor/src/test/java/org/apache/ignite/configuration/ConfigurationChangerTest.java, modules/configuration-annotation-processor/src/test/java/org/apache/ignite/configuration/internal/util/ConfigurationUtilTest.java, modules/configuration-annotation-processor/src/test/java/org/apache/ignite/configuration/notifications/ConfigurationListenerTest.java, modules/configuration-annotation-processor/src/test/java/org/apache/ignite/configuration/sample/BaselineConfigurationSchema.java, modules/configuration-annotation-processor/src/test/java/org/apache/ignite/configuration/sample/ClusterWideConfigurationSchema.java, modules/configuration-annotation-processor/src/test/java/org/apache/ignite/configuration/sample/LocalConfigurationSchema.java, modules/configuration-annotation-processor/src/test/java/org/apache/ignite/configuration/sample/NetworkConfigurationSchema.java, modules/configuration-annotation-processor/src/test/java/org/apache/ignite/configuration/sample/TraversableTreeNodeTest.java, modules/configuration/src/main/java/org/apache/ignite/configuration/annotation/Config.java
=> IGNITE-14788 Configuration schemas fields forced to be public.

modules/network-annotation-processor/src/main/java/org/apache/ignite/network/processor/internal/MessageClass.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/network/processor/internal/MessageGroupWrapper.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/network/processor/internal/ProcessingException.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/network/processor/internal/TypeUtils.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/network/processor/internal/messages/MessageBuilderGenerator.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/network/processor/internal/messages/MessageFactoryGenerator.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/network/processor/internal/messages/MessageImplGenerator.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/network/processor/internal/serialization/BaseMethodNameResolver.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/network/processor/internal/serialization/MessageCollectionItemTypeConverter.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/network/processor/internal/serialization/MessageDeserializerGenerator.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/network/processor/internal/serialization/MessageReaderMethodResolver.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/network/processor/internal/serialization/MessageSerializerGenerator.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/network/processor/internal/serialization/MessageWriterMethodResolver.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/network/processor/internal/serialization/RegistryInitializerGenerator.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/network/processor/internal/serialization/SerializationFactoryGenerator.java, modules/network-api/src/main/java/org/apache/ignite/network/ClusterNode.java, modules/network-api/src/main/java/org/apache/ignite/network/annotations/Transferable.java, modules/network/src/main/java/org/apache/ignite/network/internal/recovery/RecoveryClientHandshakeManager.java, modules/network/src/main/java/org/apache/ignite/network/internal/recovery/RecoveryServerHandshakeManager.java, modules/network/src/main/java/org/apache/ignite/network/internal/recovery/message/HandshakeStartMessage.java, modules/network/src/main/java/org/apache/ignite/network/internal/recovery/message/HandshakeStartResponseMessage.java, modules/network/src/main/java/org/apache/ignite/network/scalecube/ScaleCubeDirectMarshallerTransport.java
https://issues.apache.org/jira/browse/IGNITE-14562
=> IGNITE-14562 Fix javadoc warnings in network modules

modules/core/src/main/java/org/apache/ignite/internal/util/GridUnsafe.java
https://issues.apache.org/jira/browse/IGNITE-14895
=> IGNITE-14895 Reflection replaced with method handles in GridUnsafe.

modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/RpcClient.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/IgniteRpcClient.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/rpc/AbstractRpcTest.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/rpc/IgniteRpcTest.java
https://issues.apache.org/jira/browse/IGNITE-14909
=> IGNITE-14909 Use local address instead of external in AbstractRpcTest

modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ITCliServiceTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ITNodeTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/server/ITJRaftCounterServerTest.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/rpc/AbstractRpcTest.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/test/TestUtils.java
https://issues.apache.org/jira/browse/IGNITE-14910
1. Renamed `TestUtils#getMyIp` to `TestUtils#getLocalAddress`.
2. Removed Junit 4 in affected tests.
3. Applied automatic IDEA fixes in affected tests.
=> IGNITE-14910 Use local address in JRaft tests

modules/api/pom.xml
https://issues.apache.org/jira/browse/IGNITE-15014
=> IGNITE-15014 Explicit annotation processor dependency in api module.

modules/network-annotation-processor/src/integrationTest/java/org/apache/ignite/internal/network/processor/ITTransferableObjectProcessorTest.java, modules/network-annotation-processor/src/integrationTest/resources/org/apache/ignite/internal/network/processor/InheritedMessageClash.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/MessageClass.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/TransferableObjectProcessor.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/TypeUtils.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/messages/MessageBuilderGenerator.java, modules/network-annotation-processor/src/test/java/org/apache/ignite/internal/network/processor/InheritedMessage.java, modules/network-annotation-processor/src/test/java/org/apache/ignite/internal/network/processor/InheritedMessageTest.java, modules/network-annotation-processor/src/test/java/org/apache/ignite/internal/network/processor/SerializationOrderTest.java
https://issues.apache.org/jira/browse/IGNITE-15018
=> IGNITE-15018 Add support for message inheritance for @Transferable

modules/core/src/test/java/org/apache/ignite/internal/testframework/matchers/CompletableFutureMatcher.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/MetaStorageManager.java, modules/network-api/src/main/java/org/apache/ignite/network/AbstractMessagingService.java, modules/network-api/src/main/java/org/apache/ignite/network/MessagingService.java, modules/network/pom.xml, modules/network/src/integrationTest/java/org/apache/ignite/network/scalecube/ITScaleCubeNetworkMessagingTest.java, modules/network/src/main/java/org/apache/ignite/network/scalecube/ScaleCubeMessagingService.java, modules/network/src/test/java/org/apache/ignite/network/MessageSerializationRegistryImplTest.java, modules/network/src/test/java/org/apache/ignite/network/TestMessageTypes.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/RaftServerImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/RpcServer.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/IgniteRpcServer.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/rpc/TestIgniteRpcServer.java, modules/vault/src/integrationTest/java/org/apache/ignite/internal/vault/persistence/PersistencePropertiesVaultServiceTest.java, modules/vault/src/test/java/org/apache/ignite/internal/vault/VaultManagerTest.java, modules/vault/src/test/java/org/apache/ignite/internal/vault/VaultServiceTest.java
https://issues.apache.org/jira/browse/IGNITE-14983
=> IGNITE-14983 Enable registering message listeners for message groups

modules/core/pom.xml, modules/network/pom.xml, modules/storage-api/pom.xml, parent/pom.xml
https://issues.apache.org/jira/browse/IGNITE-15165
=> IGNITE-15165 Fix maven build when maven.test.skip is set

modules/metastorage-client/src/integrationTest/java/org/apache/ignite/internal/metastorage/client/ITMetaStorageServiceTest.java, modules/network-api/src/main/java/org/apache/ignite/network/ClusterLocalConfiguration.java, modules/network-api/src/main/java/org/apache/ignite/network/NodeFinder.java, modules/network/pom.xml, modules/network/src/integrationTest/java/org/apache/ignite/network/scalecube/ITNodeRestartsTest.java, modules/network/src/integrationTest/java/org/apache/ignite/network/scalecube/ITScaleCubeNetworkMessagingTest.java, modules/network/src/main/java/org/apache/ignite/network/StaticNodeFinder.java, modules/network/src/main/java/org/apache/ignite/network/scalecube/ScaleCubeClusterServiceFactory.java, modules/network/src/test/java/org/apache/ignite/network/LocalPortRangeNodeFinder.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ITCliServiceTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ITNodeTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/server/RaftServerAbstractTest.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/core/TestCluster.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/rpc/IgniteRpcTest.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/rpc/TestIgniteRpcServer.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgnitionImpl.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ITDistributedTableTest.java
https://issues.apache.org/jira/browse/IGNITE-14092
=> IGNITE-14092 Introduce the Node Finder API

modules/network-api/src/main/java/org/apache/ignite/network/AbstractMessagingService.java, modules/network-api/src/main/java/org/apache/ignite/network/MessagingService.java, modules/network/src/test/java/org/apache/ignite/network/AbstractMessagingServiceTest.java
https://issues.apache.org/jira/browse/IGNITE-15178
=> IGNITE-15178 Check for clashing message group IDs

modules/metastorage-client/src/integrationTest/java/org/apache/ignite/internal/metastorage/client/ITMetaStorageServicePersistenceTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/server/ITJRaftCounterServerTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/server/ITSimpleCounterServerTest.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/Loza.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JRaftServerImpl.java, modules/runner/pom.xml, modules/runner/src/integrationTest/java/org/apache/ignite/internal/storage/ITDistributedConfigurationStorageTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgnitionImpl.java, modules/runner/src/main/java/org/apache/ignite/internal/storage/DistributedConfigurationStorage.java, modules/runner/src/main/java/org/apache/ignite/internal/storage/LocalConfigurationStorage.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ITDistributedTableTest.java
https://issues.apache.org/jira/browse/IGNITE-15213
=> IGNITE-15213 Fix distributed configuration restart

modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationChanger.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/storage/ConfigurationStorage.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/storage/ConfigurationStorageListener.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/storage/TestConfigurationStorage.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/MetaStorageManager.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/storage/ITDistributedConfigurationStorageTest.java, modules/runner/src/main/java/org/apache/ignite/internal/storage/DistributedConfigurationStorage.java, modules/runner/src/main/java/org/apache/ignite/internal/storage/LocalConfigurationStorage.java
https://issues.apache.org/jira/browse/IGNITE-15264
=> IGNITE-15264 Fixed wrong applied revision handling in DistributedConfigurationStorage

parent/pom.xml
https://issues.apache.org/jira/browse/IGNITE-15182
=> IGNITE-15182 Fix PMD plugin configuration

check-rules/maven-check-scripts/CheckDuplicateDependencies.sh, modules/raft/pom.xml
https://issues.apache.org/jira/browse/IGNITE-15304
=> IGNITE-15304 Validate POM files for duplicate dependencies

modules/configuration-annotation-processor/src/test/java/org/apache/ignite/internal/configuration/tree/TraversableTreeNodeTest.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/asm/ConfigurationAsmGenerator.java
https://issues.apache.org/jira/browse/IGNITE-15296
=> IGNITE-15296 Generated node classes throw NPE now if null passed.

modules/core/src/main/java/org/apache/ignite/lang/JavaLoggerFormatter.java
https://issues.apache.org/jira/browse/IGNITE-15310
=> IGNITE-15310 fix bug in JavaLoggerFormatter

modules/runner/src/integrationTest/java/org/apache/ignite/internal/storage/ITDistributedConfigurationStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-15305
=> IGNITE-15305 Fixed flaky ITDistributedConfigurationStorageTest#testRestartWithPds.

modules/api/src/main/java/org/apache/ignite/configuration/schemas/clientconnector/ClientConnectorConfigurationSchema.java, modules/cli/src/integrationTest/java/org/apache/ignite/cli/ConfigCommandTest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientHandlerModule.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/table/ClientTablesGetRequest.java, modules/client-handler/src/test/java/org/apache/ignite/client/handler/ClientHandlerIntegrationTest.java, modules/client/src/test/java/org/apache/ignite/client/AbstractClientTest.java, modules/runner/pom.xml, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ITThinClientConnectionTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgnitionImpl.java, parent/pom.xml
* Start client-handler module when the node starts.
* Add integration test.
=> IGNITE-15236 Thin 3.0: Start client-handler module

modules/client-handler/pom.xml, parent/pom.xml
https://issues.apache.org/jira/browse/IGNITE-15331
=> IGNITE-15331 Remove slf4j-simple

CONTRIBUTING.md
https://issues.apache.org/jira/browse/IGNITE-15366
=> IGNITE-15366 Create CONTRIBUTING.md

modules/network-annotation-processor/src/integrationTest/java/org/apache/ignite/internal/network/processor/ITTransferableObjectProcessorTest.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/TransferableObjectProcessor.java
https://issues.apache.org/jira/browse/IGNITE-15433
=> IGNITE-15433 Improve network annotation processor error messages

modules/raft-client/src/main/java/org/apache/ignite/raft/client/service/CommandClosure.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/DataRow.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/InvokeClosure.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/Storage.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/basic/ConcurrentHashMapStorage.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/basic/DeleteExactInvokeClosure.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/basic/GetAndRemoveInvokeClosure.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/basic/GetAndReplaceInvokeClosure.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/basic/InsertInvokeClosure.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/basic/ReplaceExactInvokeClosure.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/basic/SimpleDataRow.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/basic/SimpleReadInvokeClosure.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/basic/SimpleRemoveInvokeClosure.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/basic/SimpleWriteInvokeClosure.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/AbstractStorageTest.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/command/CommandUtils.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/command/ReplaceIfExistCommand.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/command/response/SingleRowResponse.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java
https://issues.apache.org/jira/browse/IGNITE-15338
=> IGNITE-15338 Return null if a DataRow is not found

modules/api/pom.xml, modules/calcite/pom.xml, modules/cli/pom.xml, modules/configuration/pom.xml, modules/network/pom.xml, modules/raft-client/pom.xml, modules/raft/pom.xml, modules/rest/pom.xml, parent/pom.xml
=> Revert "IGNITE-15393 Add errorprone plugin (#304)"

modules/configuration/pom.xml, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationChanger.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationNode.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/DynamicConfiguration.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/DynamicConfigurationChanger.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/DynamicProperty.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/NamedListConfiguration.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/asm/ConfigurationAsmGenerator.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/util/ConfigurationUtil.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/testframework/ConfigurationExtension.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/testframework/ConfigurationExtensionTest.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/testframework/InjectConfiguration.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/util/ConfigurationUtilTest.java
https://issues.apache.org/jira/browse/IGNITE-15486
=> IGNITE-15486 JUnit configuration extension implemented

modules/platforms/dotnet/Apache.Ignite.Tests/ProjectFilesTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Schema.cs
* Suppress warnings CS1572, CS1573 on records for older SDKs
* Fix TestPublicTypesAreSealed
=> IGNITE-15432 .NET: Fix tests for TeamCity project

modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationRegistry.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/testframework/BasicConfigurationSchema.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/testframework/ConfigurationExtension.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/testframework/ConfigurationExtensionTest.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/testframework/ExtendedConfigurationSchema.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/testframework/InjectConfiguration.java
https://issues.apache.org/jira/browse/IGNITE-15501
=> IGNITE-15501 Improvements in ConfigurationExtension - support for listeners and internal schema extensions

modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/Processor.java, modules/configuration-api/src/main/java/org/apache/ignite/configuration/NamedConfigurationTree.java, modules/configuration-api/src/main/java/org/apache/ignite/configuration/NamedListChange.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/NamedListConfiguration.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/tree/NamedListNode.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/tree/TraversableTreeNodeTest.java
https://issues.apache.org/jira/browse/IGNITE-15520
=> IGNITE-15520 Fixed NamedListChange class type parameters.

modules/schema/src/main/java/org/apache/ignite/internal/schema/registry/UpgradingRowAdapter.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/TestUtils.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/registry/UpgradingRowAdapterTest.java
https://issues.apache.org/jira/browse/IGNITE-15339
=> IGNITE-15339 Fix broken access methods for column of temporal types after row upgrade

modules/core/src/main/java/org/apache/ignite/internal/util/IgniteSpinBusyLock.java, modules/core/src/main/java/org/apache/ignite/internal/util/IgniteSpinReadWriteLock.java, modules/metastorage-client/src/main/java/org/apache/ignite/internal/metastorage/client/CursorImpl.java, modules/metastorage-client/src/main/java/org/apache/ignite/internal/metastorage/client/MetaStorageServiceImpl.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/MetaStorageManager.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/Loza.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/RaftGroupServiceImpl.java, modules/table/src/test/java/org/apache/ignite/internal/table/TableManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-15444
=> IGNITE-15444 stop MetaStorageManager

modules/api/src/main/java/org/apache/ignite/table/Tuple.java, modules/api/src/main/java/org/apache/ignite/table/TupleImpl.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTuple.java, modules/client/src/test/java/org/apache/ignite/client/ClientKeyValueBinaryViewTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientTableTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientTupleTest.java, modules/client/src/test/java/org/apache/ignite/client/CustomTuple.java, modules/platforms/dotnet/Apache.Ignite.Tests/Table/TableTests.cs, modules/schema/src/main/java/org/apache/ignite/internal/schema/InvalidTypeException.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/SchemaMismatchException.java, modules/table/src/main/java/org/apache/ignite/internal/table/AbstractRowTupleAdapter.java, modules/table/src/main/java/org/apache/ignite/internal/table/TableRow.java, modules/table/src/main/java/org/apache/ignite/internal/table/TupleMarshallerImpl.java, modules/table/src/test/java/org/apache/ignite/internal/table/MutableRowTupleAdapterTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/StrictSchemaOperationsTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/TableBinaryViewOperationsTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/impl/TestTupleBuilder.java, modules/table/src/test/java/org/apache/ignite/table/TupleImplTest.java
https://issues.apache.org/jira/browse/IGNITE-15532
=> IGNITE-15532 Tuple equality comparison

modules/core/src/test/java/org/apache/ignite/internal/testframework/WorkDirectoryExtension.java, modules/metastorage-client/src/integrationTest/java/org/apache/ignite/internal/metastorage/client/ITMetaStorageServicePersistenceTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/client/service/ITAbstractListenerSnapshotTest.java, modules/storage-api/pom.xml, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/AbstractStorageTest.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/basic/ConcurrentHashMapStorage.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageTest.java, modules/table/pom.xml, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ITDistributedTableTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ITTablePersistenceTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/PartitionCommandListenerTest.java
https://issues.apache.org/jira/browse/IGNITE-15646
=> IGNITE-15646 ConcurrentHashMapStorage moved to test package.

modules/core/src/test/java/org/apache/ignite/internal/testframework/SystemPropertiesExtension.java, modules/core/src/test/java/org/apache/ignite/internal/testframework/WorkDirectoryExtension.java
https://issues.apache.org/jira/browse/IGNITE-15661
=> IGNITE-15661 Fix SystemPropertiesExtension state usage

modules/api/src/main/java/org/apache/ignite/schema/definition/builder/TableDefinitionBuilder.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/configuration/TableValidatorImpl.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/definition/builder/TableDefinitionBuilderImpl.java, modules/schema/src/main/java/org/apache/ignite/schema/SchemaBuilders.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/SchemaConfigurationTest.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/builder/TableDefinitionBuilderTest.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/configuration/SchemaConfigurationConverterTest.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/configuration/SchemaDescriptorConverterTest.java
https://issues.apache.org/jira/browse/IGNITE-15699
=> IGNITE-15699: Rename class with incorrect name: TableSchemaBuilder

idea/intellij-java-google-style.xml
https://issues.apache.org/jira/browse/IGNITE-15878
=> IGNITE-15878 Fix IDEA codestyle settings.

modules/core/pom.xml
https://issues.apache.org/jira/browse/IGNITE-15920
=> IGNITE-15920 Fix Maven warnings

pom.xml
https://issues.apache.org/jira/browse/IGNITE-15923
=> IGNITE-15923 Remove redundant property in maven-checkstyle-plugin configuration

modules/api/src/main/java/org/apache/ignite/configuration/schemas/table/HashIndexConfigurationSchema.java, modules/api/src/main/java/org/apache/ignite/configuration/schemas/table/PartialIndexConfigurationSchema.java, modules/api/src/main/java/org/apache/ignite/configuration/schemas/table/SortedIndexConfigurationSchema.java, modules/api/src/main/java/org/apache/ignite/configuration/schemas/table/TableIndexConfigurationSchema.java, modules/configuration-annotation-processor/src/integrationTest/java/org/apache/ignite/internal/configuration/processor/AbstractProcessorTest.java, modules/configuration-annotation-processor/src/integrationTest/java/org/apache/ignite/internal/configuration/processor/ItProcessorTest.java, modules/configuration-annotation-processor/src/integrationTest/resources/org/apache/ignite/internal/configuration/processor/internal/StaticConstantsConfigurationSchema.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/Processor.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/asm/ConfigurationAsmGenerator.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/util/ConfigurationNotificationsUtil.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/asm/ConfigurationAsmGeneratorTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/configuration/SchemaConfigurationConverter.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/configuration/SchemaConfigurationConverterTest.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/configuration/TableValidatorImplTest.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/TableManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-15884
=> IGNITE-15884 Make TableIndexConfigurationSchema polymorphic

modules/network/pom.xml, modules/network/src/main/java/org/apache/ignite/network/scalecube/ScaleCubeClusterServiceFactory.java, modules/network/src/main/java/org/apache/ignite/network/scalecube/ScaleCubeMessagingService.java, modules/network/src/main/java/org/apache/ignite/network/scalecube/ScaleCubeTopologyService.java, parent/pom.xml
https://issues.apache.org/jira/browse/IGNITE-15965
=> IGNITE-15965 Fix a race between cluster start and setting the local member

modules/network-annotation-processor/src/integrationTest/java/org/apache/ignite/internal/network/processor/ItTransferableObjectProcessorTest.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/TransferableObjectProcessor.java
https://issues.apache.org/jira/browse/IGNITE-15972
=> IGNITE-15972 Improve network processor error message

modules/configuration-annotation-processor/src/integrationTest/java/org/apache/ignite/internal/configuration/processor/ItProcessorTest.java, modules/configuration-annotation-processor/src/integrationTest/resources/org/apache/ignite/internal/configuration/processor/ConfigurationSchemaWithWrongPostfix.java, modules/configuration-annotation-processor/src/integrationTest/resources/org/apache/ignite/internal/configuration/processor/ConfigurationSchemaWithWrongSuffix.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/Processor.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationChanger.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationManager.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationRegistry.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/asm/ConfigurationAsmGenerator.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/tree/InnerNode.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/util/ConfigurationFlattener.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/util/ConfigurationUtil.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/ConfigurationRegistryTest.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/notifications/ConfigurationAnyListenerTest.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/notifications/ConfigurationListenerTest.java
See https://issues.apache.org/jira/browse/IGNITE-15971
=> IGNITE-15971 Fix problems with dynamic configuration

check-rules/checkstyle-rules.xml
[IGNITE-16035](https://issues.apache.org/jira/browse/IGNITE-16035)
=> IGNITE-16035 Add rule against empty line with whitespace only.

modules/configuration/src/main/java/org/apache/ignite/internal/configuration/tree/NamedListNode.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/tree/NamedListNodeTest.java
https://issues.apache.org/jira/browse/IGNITE-16042
=> IGNITE-16042 Fail NamedListChange#createAfter if called on a deleted key

modules/raft/pom.xml
https://issues.apache.org/jira/browse/IGNITE-16067
=> IGNITE-16067 Fix JMH benchmarks in the raft module

modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/externalize/RelJson.java, modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/metadata/IgniteMdCollation.java, modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/prepare/PlannerHelper.java, modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/rel/IgniteCorrelatedNestedLoopJoin.java, modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/rel/IgniteProject.java, modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/rel/agg/IgniteSortAggregateBase.java, modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/rule/FilterSpoolMergeToSortedIndexSpoolRule.java, modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/trait/IgniteDistributions.java, modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/trait/TraitUtils.java, modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/util/Commons.java, modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/util/IndexConditions.java, modules/calcite/src/main/java/org/apache/ignite/internal/processors/query/calcite/util/RexUtils.java, modules/calcite/src/test/java/org/apache/ignite/internal/processors/query/calcite/exec/rel/BaseAggregateTest.java, modules/core/src/main/java/org/apache/ignite/internal/util/CollectionUtils.java, modules/core/src/test/java/org/apache/ignite/internal/util/CollectionUtilsTest.java
[IGNITE-15870](https://issues.apache.org/jira/browse/IGNITE-15870)
Replace List<Integer>/Set<Integer> with IntArrayList/IntOpenHashSet, replace Set.copyOf with IntOpenHashSet based implementation.
=> IGNITE-15870 Calcite. Replace usages of Lists and Sets of int to IntList\IntSet

modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/Replicator.java
https://issues.apache.org/jira/browse/IGNITE-16309
=> IGNITE-16309 Fix replicator can recycle bytebuffer before it was sent

modules/network-api/src/main/java/org/apache/ignite/network/MessagingService.java, modules/network/src/integrationTest/java/org/apache/ignite/network/scalecube/ItClusterServiceTest.java, modules/network/src/main/java/org/apache/ignite/network/scalecube/ScaleCubeClusterServiceFactory.java, modules/network/src/main/java/org/apache/ignite/network/scalecube/ScaleCubeMessagingService.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/RaftGroupServiceImpl.java
https://issues.apache.org/jira/browse/IGNITE-16338
=> IGNITE-16338 Remove usages of Cluster#isShutdown method

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItNoThreadsLeftTest.java
https://issues.apache.org/jira/browse/IGNITE-16381
=> IGNITE-16381 Fix ItNoThreadsLeftTest

modules/api/src/main/java/org/apache/ignite/configuration/schemas/network/NetworkConfigurationSchema.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/ConnectionManager.java, modules/network/src/main/java/org/apache/ignite/network/NettyBootstrapFactory.java
https://issues.apache.org/jira/browse/IGNITE-16388
=> IGNITE-16388 Remove stale TODOs in network module

modules/client/src/test/java/org/apache/ignite/client/ConnectionTest.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/ExpandableByteBufTest.java
https://issues.apache.org/jira/browse/IGNITE-16408
=> IGNITE-16408 Tests fail when building under specific locales

modules/cli/src/main/java/org/apache/ignite/cli/builtins/node/NodeManager.java, parent/pom.xml
https://issues.apache.org/jira/browse/IGNITE-16404
=> IGNITE-16404 Enable Unsafe for netty

modules/cli/src/main/java/org/apache/ignite/cli/builtins/node/NodeManager.java
https://issues.apache.org/jira/browse/IGNITE-16419
=> IGNITE-16419 Split startup parameters

modules/runner/src/main/java/org/apache/ignite/internal/configuration/storage/DistributedConfigurationStorage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-16425
=> IGNITE-16425 Improved check of table existence.

modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientKeyValueBinaryView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientRecordBinaryView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientSchema.java, modules/client/src/main/java/org/apache/ignite/internal/marshaller/ClientMarshallerWriter.java, modules/client/src/test/java/org/apache/ignite/client/AbstractClientTableTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientKeyValueViewTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientRecordViewTest.java, modules/client/src/test/java/org/apache/ignite/client/ClientTableTest.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeIgniteTables.java
* Enable `testGetReturningTupleWithUnknownSchemaRequestsNewSchema`.
* Fix default column value handling in `ClientMarshallerWriter`, add tests.
=> IGNITE-16461 Thin client: Remove TODOs for completed tickets, enable/add tests

modules/configuration/src/main/java/org/apache/ignite/internal/configuration/DynamicConfiguration.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-16476
=> IGNITE-16476 Deal with all "TODO" on resolved tickets (IGNITE-14645, IGNITE-15409)

modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbSortedIndexStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-16515
=> IGNITE-16515 Fix flaky RocksDbSortedIndexStorageTest

check-rules/modernizer-rules.xml, examples/src/test/java/org/apache/ignite/example/ExampleTestUtils.java, modules/cli/pom.xml, modules/cli/src/integrationTest/java/org/apache/ignite/cli/ItConfigCommandTest.java, modules/cli/src/main/java/org/apache/ignite/cli/builtins/cluster/ClusterApiClient.java, modules/cli/src/main/java/org/apache/ignite/cli/builtins/cluster/InitClusterRequest.java, modules/cli/src/main/java/org/apache/ignite/cli/builtins/config/ConfigurationClient.java, modules/cli/src/main/java/org/apache/ignite/cli/spec/ClusterCommandSpec.java, modules/cli/src/main/java/org/apache/ignite/cli/spec/ConfigCommandSpec.java, modules/cli/src/main/java/org/apache/ignite/cli/spec/IgniteCliSpec.java, modules/cli/src/main/java/org/apache/ignite/cli/spec/NodeEndpointOptions.java, modules/cli/src/test/java/org/apache/ignite/cli/IgniteCliInterfaceTest.java, modules/cli/src/test/java/org/apache/ignite/cli/ui/ProgressBarTest.java, modules/cli/src/test/java/org/apache/ignite/cli/ui/SpinnerTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/MetaStorageManager.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgnitionTest.java
https://issues.apache.org/jira/browse/IGNITE-14871
=> IGNITE-14871 Add cluster initialization commands to the Ignite CLI

modules/metastorage-server/src/main/java/org/apache/ignite/internal/metastorage/server/raft/MetaStorageListener.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java
https://issues.apache.org/jira/browse/IGNITE-16522
=> IGNITE-16522 Fix usage of the JDK Marshaller in raft group listeners

parent/pom.xml
https://issues.apache.org/jira/browse/IGNITE-16566
=> IGNITE-16566 Use Mockito BOM in pom.xml

modules/metastorage-server/src/main/java/org/apache/ignite/internal/metastorage/server/KeyValueStorage.java, modules/metastorage-server/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java, modules/metastorage-server/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksStorageUtils.java, modules/metastorage-server/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/WatchCursor.java, modules/metastorage-server/src/test/java/org/apache/ignite/internal/metastorage/server/AbstractKeyValueStorageTest.java, modules/metastorage-server/src/test/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java
https://issues.apache.org/jira/browse/IGNITE-16584
=> IGNITE-16584 Fix metastorage cursor wrong order

modules/core/src/main/java/org/apache/ignite/internal/util/ArrayUtils.java
https://issues.apache.org/jira/browse/IGNITE-16451
=> IGNITE-16451 Try to optimize ArrayUtils#remove

modules/page-memory/src/integrationTest/java/org/apache/ignite/internal/pagememory/tree/ItBplusTreeReplaceRemoveRaceTest.java, modules/page-memory/src/integrationTest/java/org/apache/ignite/internal/pagememory/tree/ItBplusTreeSelfTest.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/PageMemoryIoModule.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/tree/BplusTree.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/tree/io/BplusMetaIo.java
https://issues.apache.org/jira/browse/IGNITE-16534
=> IGNITE-16534 Make BplusMetaIo abstract 

modules/raft/src/integrationTest/java/org/apache/ignite/internal/raft/ItRaftGroupServiceTest.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/RaftGroupServiceImpl.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/core/RaftGroupServiceTest.java
=> IGNITE-16678 RaftGroupService#transferLeadership fixed.

modules/network/src/main/java/org/apache/ignite/internal/network/netty/ConnectionManager.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/NettySender.java, modules/network/src/main/java/org/apache/ignite/network/DefaultMessagingService.java
https://issues.apache.org/jira/browse/IGNITE-16699
=> IGNITE-16699 Properly stop executors in the network module

modules/schema/src/main/java/org/apache/ignite/internal/schema/BinaryRow.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/ByteBufferRow.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/row/ExpandableByteBuf.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/row/Row.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/row/VarTableFormat.java
https://issues.apache.org/jira/browse/IGNITE-16704
=> IGNITE-16704 Removed excessive methods from BinaryRow interface.

modules/metastorage-server/src/main/java/org/apache/ignite/internal/metastorage/server/KeyValueStorage.java, modules/metastorage-server/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java, modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/ColumnFamily.java, modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/RocksUtils.java, modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/snapshot/ColumnFamilyRange.java, modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/snapshot/RocksSnapshotManager.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/PartitionStorage.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/AbstractPartitionStorageTest.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/basic/ConcurrentHashMapPartitionStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMetaStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbPartitionStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbSortedIndexStorage.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-16688
=> IGNITE-16688 Extract RocksDB snapshots into a separate class

modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/IncrementalCompilationConfig.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/MessageClass.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/TransferableObjectProcessor.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/messages/MessageFactoryGenerator.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/serialization/RegistryInitializerGenerator.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/serialization/SerializationFactoryGenerator.java, modules/network/src/integrationTest/java/org/apache/ignite/internal/network/processor/InMemoryJavaFileManager.java, modules/network/src/integrationTest/java/org/apache/ignite/internal/network/processor/ItTransferableObjectProcessorIncrementalTest.java
https://issues.apache.org/jira/browse/IGNITE-16674
=> IGNITE-16674 Fix incremental compilation for network messages

modules/core/src/test/java/org/apache/ignite/internal/testframework/WorkDirectoryExtension.java
https://issues.apache.org/jira/browse/IGNITE-16729
=> IGNITE-16729 Fix flaky test

modules/page-memory/src/integrationTest/java/org/apache/ignite/internal/pagememory/tree/ItBplusTreeSelfTest.java
https://issues.apache.org/jira/browse/IGNITE-16653
=> IGNITE-16653 Fix flaky ItBplusTreeFakeReuseSelfTest#testPutSizeLivelock

modules/api/src/main/java/org/apache/ignite/configuration/schemas/table/ColumnConfigurationSchema.java, modules/api/src/main/java/org/apache/ignite/configuration/schemas/table/IndexColumnConfigurationSchema.java, modules/api/src/main/java/org/apache/ignite/configuration/schemas/table/TableConfigurationSchema.java, modules/api/src/main/java/org/apache/ignite/configuration/schemas/table/TableIndexConfigurationSchema.java, modules/client/src/test/java/org/apache/ignite/client/ReconnectTest.java, modules/client/src/test/java/org/apache/ignite/client/RetryPolicyTest.java, modules/configuration-api/src/main/java/org/apache/ignite/configuration/notifications/ConfigurationNotificationEvent.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/notifications/ConfigurationNotificationEventImpl.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/tree/NamedListNode.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/util/ConfigurationSerializationUtil.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/notifications/ConfigurationListenerTest.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/testframework/ConfigurationExtension.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/testframework/InjectConfiguration.java, modules/core/src/test/java/org/apache/ignite/internal/util/io/IgniteUnsafeDataOutputArraySizingTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/AbstractSchemaChangeTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItDynamicTableCreationTest.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/configuration/SchemaConfigurationConverter.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/configuration/TableValidatorImpl.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/configuration/TableValidatorImplTest.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/AbstractSortedIndexMvStorageTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/PageMemoryPartitionStorageTest.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbPartitionStorageTest.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorageTest.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbSortedIndexStorageTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-16796
=> IGNITE-16796 NamedList related fixes in configuration, and more

modules/network/src/integrationTest/java/org/apache/ignite/internal/network/processor/ItTransferableObjectProcessorTest.java, modules/network/src/integrationTest/resources/org/apache/ignite/internal/network/processor/ItTestMessageGroup.java
https://issues.apache.org/jira/browse/IGNITE-16833
=> IGNITE-16833 Rename ITTestMessageGroup to ItTestMessageGroup

DEVNOTES.md, modules/raft/pom.xml, parent/pom.xml
https://issues.apache.org/jira/browse/IGNITE-16868
=> IGNITE-16868 Fix build in IDEA

DEVNOTES.md, modules/api/src/main/java/org/apache/ignite/configuration/schemas/table/TableConfigurationSchema.java, modules/metastorage-client/src/integrationTest/java/org/apache/ignite/internal/metastorage/client/ItMetaStorageRaftGroupTest.java, modules/network/src/main/java/org/apache/ignite/network/scalecube/ScaleCubeClusterServiceFactory.java, modules/platforms/dotnet/Apache.Ignite.Tests/RawSocketConnectionTests.cs, modules/raft/src/integrationTest/java/org/apache/ignite/internal/raft/ItRaftGroupServiceTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/client/service/ItAbstractListenerSnapshotTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/server/ItJraftCounterServerTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/server/ItSimpleCounterServerTest.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/JRaftServiceFactory.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/DefaultJRaftServiceFactory.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/NodeImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/option/BootstrapOptions.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/option/NodeOptions.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/LogStorageFactory.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/impl/DefaultLogStorageFactory.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/impl/RocksDbSharedLogStorage.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/core/TestCluster.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/storage/SnapshotExecutorTest.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/storage/impl/RocksDbSharedLogStorageAdvancedTest.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/storage/impl/RocksDbSharedLogStorageTest.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/storage/impl/SharedVsNonSharedLogStorageBenchmark.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNode.java
https://issues.apache.org/jira/browse/IGNITE-16802
=> IGNITE-16802 Shared RocksDB instance for the Raft Log Storage

modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/impl/DefaultLogStorageFactory.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/impl/RocksDbSharedLogStorage.java
https://issues.apache.org/jira/browse/IGNITE-16890
=> IGNITE-16890 Fix JVM crash

modules/network/src/main/java/org/apache/ignite/internal/network/serialization/BuiltInType.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/ClassDescriptor.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/ClassDescriptorFactory.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/PerSessionSerializationService.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshaller.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/ExternalizableMarshaller.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/ReadResolver.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/SchemaMismatchHandler.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/SchemaMismatchHandlers.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/StructuredObjectMarshaller.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/WriteReplacer.java, modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultSchemaMismatchHandlerTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerConcreteTypesKnownUpfrontOptimizationTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerWithSchemaChangeTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerWithSerializableOverrideStreamsTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerWithSerializableTest.java
https://issues.apache.org/jira/browse/IGNITE-16574
=> IGNITE-16574 Support schema changes concerning serializability status

modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/ItClusterManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-16915
=> IGNITE-16915 Fix flaky test

modules/api/src/main/java/org/apache/ignite/Ignition.java, modules/api/src/main/java/org/apache/ignite/IgnitionManager.java, modules/cli/src/integrationTest/java/org/apache/ignite/cli/AbstractCliIntegrationTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/cli/HandlerAdapter.java, modules/cli/src/integrationTest/java/org/apache/ignite/cli/ItClusterCommandTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/cli/ItConfigCommandTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/cli/NoOpHandler.java, modules/cli/src/integrationTest/resources/hardcoded-ports-config.json, modules/cli/src/test/java/org/apache/ignite/cli/AbstractCliTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/compute/ItComputeTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
https://issues.apache.org/jira/browse/IGNITE-16513
=> IGNITE-16513 Add an integration test for 'cluster init' CLI command

modules/network/src/main/java/org/apache/ignite/internal/network/serialization/ClassDescriptor.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/UosObjectInputStream.java, modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerWithSchemaChangeTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerWithSerializableOverrideStreamsTest.java
https://issues.apache.org/jira/browse/IGNITE-16571
=> IGNITE-16571 Implement defaultness semantics for GetField when schema changes

examples/pom.xml, modules/cli/src/main/java/org/apache/ignite/cli/builtins/node/NodeManager.java, modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerWithSchemaChangeTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerWithSerializableOverrideStreamsTest.java, parent/pom.xml
https://issues.apache.org/jira/browse/IGNITE-16940
=> IGNITE-16940 Make the project build on Java 18

modules/network/src/main/java/org/apache/ignite/internal/network/serialization/BrokenFieldAccessor.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/BrokenSerializationMethods.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/ClassDescriptor.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/ClassDescriptorMerger.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/ClassNameMapBackedClassIndexedDescriptors.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/FieldAccessor.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/FieldDescriptor.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/MergedLayer.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/PerSessionSerializationService.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/SerializationException.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshaller.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/SchemaMismatchEventSource.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/SchemaMismatchHandlers.java, modules/network/src/main/java/org/apache/ignite/internal/network/serialization/marshal/StructuredObjectMarshaller.java, modules/network/src/test/java/org/apache/ignite/internal/network/serialization/ClassDescriptorMergerTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/serialization/ClassNameMapBackedClassIndexedDescriptorsTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/serialization/marshal/DefaultUserObjectMarshallerWithSchemaChangeTest.java
https://issues.apache.org/jira/browse/IGNITE-16921
=> IGNITE-16921 Support schema changes concerning inheritance hierarchy

modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java, modules/core/src/test/java/org/apache/ignite/internal/util/IgniteUtilsTest.java, modules/page-memory/pom.xml, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/io/PageIo.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/FastCrc.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/IgniteInternalDataIntegrityViolationException.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStore.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStoreFactory.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/store/PageStore.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/FastCrcTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStoreFactoryTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStoreTest.java, parent/pom.xml
https://issues.apache.org/jira/browse/IGNITE-17014
=> IGNITE-17014 [Native Persistence 3.0] Porting FilePageStoreFactory and FilePageStore from 2.0

modules/network/src/test/java/org/apache/ignite/internal/network/netty/InboundDecoderTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/netty/NettyClientTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/netty/NettyServerTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/netty/RecoveryHandshakeTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/serialization/MarshallableTest.java
https://issues.apache.org/jira/browse/IGNITE-17040
=> IGNITE-17040 Fix Netty buffer leak detected

modules/network/src/test/java/org/apache/ignite/internal/network/netty/RecoveryHandshakeTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/serialization/MarshallableTest.java
https://issues.apache.org/jira/browse/IGNITE-17071
=> IGNITE-17071 Fix netty buffer leak in MarshallableTest

modules/network/src/test/java/org/apache/ignite/internal/network/netty/InboundDecoderTest.java
https://issues.apache.org/jira/browse/IGNITE-17080
=> IGNITE-17080 Fix netty buffer leak in InboundDecoderTest

modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/ItClusterManagerTest.java, modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/MockNode.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java
https://issues.apache.org/jira/browse/IGNITE-17067
=> IGNITE-17067 Send init response after CMG leader was elected

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/datapage/ReadPageMemoryRowValue.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageTest.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryDataRegion.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/PageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/PartitionlessLinks.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/Timestamps.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/io/RowVersionDataIo.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/PageMemoryMvPartitionStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-17009
=> IGNITE-17009 Support fragmented RowVersions

modules/cli/pom.xml
https://issues.apache.org/jira/browse/IGNITE-17097
There is a bug introduced in micronaut 3.4.0.
The workaround described here https://github.com/micronaut-projects/micronaut-core/issues/7144
=> IGNITE-17097: Add ServicesResourceTransformer to shade-plugin 

assembly/README.md, examples/src/main/java/org/apache/ignite/example/storage/PersistentPageMemoryStorageExample.java, examples/src/main/java/org/apache/ignite/example/storage/VolatilePageMemoryStorageExample.java
- Update examples with new commands
=> IGNITE-17126: Update README.md with Alpha 5 features

assembly/README.md, examples/src/main/java/org/apache/ignite/example/storage/PersistentPageMemoryStorageExample.java, examples/src/main/java/org/apache/ignite/example/storage/VolatilePageMemoryStorageExample.java
=> Revert "IGNITE-17126: Update README.md with Alpha 5 features"

modules/core/src/main/java/org/apache/ignite/internal/properties/IgniteProductVersion.java, modules/core/src/test/java/org/apache/ignite/internal/properties/IgniteProductVersionTest.java
https://issues.apache.org/jira/browse/IGNITE-17144
=> IGNITE-17144 Fix parsing of alpha versions of Ignite

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointMarkersStorage.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointMarkersStorageTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStoreManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-17273
=> IGNITE-17273 Close streams returned by Files.list

modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/raft/ItCmgRaftServiceTest.java
https://issues.apache.org/jira/browse/IGNITE-17283
=> IGNITE-17283 Start nodes in parallel in ItCmgRaftServiceTest

modules/network/src/test/java/org/apache/ignite/internal/network/serialization/MarshallableTest.java
https://issues.apache.org/jira/browse/IGNITE-17293
=> IGNITE-17293 Fix Netty buffer leak in MarshallableTest

modules/core/src/test/java/org/apache/ignite/internal/util/worker/IgniteWorkerTest.java
https://issues.apache.org/jira/browse/IGNITE-17289
=> IGNITE-17289 IgniteWorkerTest#testUpdateHeartbeat is flaky

modules/schema/src/main/java/org/apache/ignite/internal/schema/registry/SchemaRegistryImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/KeyValueBinaryViewImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/KeyValueViewImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/RecordBinaryViewImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/RecordViewImpl.java
https://issues.apache.org/jira/browse/IGNITE-14487
=> IGNITE-14487: Table view bulk methods refactoring.

modules/cli/src/main/java/org/apache/ignite/cli/commands/decorators/JsonDecorator.java, modules/cli/src/main/java/org/apache/ignite/cli/core/repl/completer/CompleterFilter.java, modules/cli/src/main/java/org/apache/ignite/cli/core/repl/completer/DynamicCompleter.java, modules/cli/src/main/java/org/apache/ignite/cli/core/repl/completer/DynamicCompleterActivationPoint.java, modules/cli/src/main/java/org/apache/ignite/cli/core/repl/completer/DynamicCompleterFactory.java, modules/cli/src/main/java/org/apache/ignite/cli/core/repl/completer/DynamicCompleterFilter.java, modules/cli/src/main/java/org/apache/ignite/cli/core/repl/completer/DynamicCompleterRegistry.java, modules/cli/src/main/java/org/apache/ignite/cli/core/repl/completer/HoconDynamicCompleter.java, modules/cli/src/main/java/org/apache/ignite/cli/core/repl/completer/LazyDynamicCompleter.java, modules/cli/src/main/java/org/apache/ignite/cli/core/repl/completer/NodeUrlProvider.java, modules/cli/src/main/java/org/apache/ignite/cli/core/repl/executor/IgnitePicocliCommands.java, modules/cli/src/main/java/org/apache/ignite/cli/core/repl/executor/ReplExecutor.java, modules/cli/src/test/java/org/apache/ignite/cli/core/repl/completer/DynamicCompleterFilterTest.java, modules/cli/src/test/java/org/apache/ignite/cli/core/repl/completer/DynamicCompleterRegistryTest.java, modules/cli/src/test/java/org/apache/ignite/cli/core/repl/completer/HoconDynamicCompleterTest.java
`cluster/node config show/update` are dynamically suggested with configuration keys taken from REST.
https://issues.apache.org/jira/browse/IGNITE-17125
=> IGNITE-17125: Add dynamic completers

modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbFlushListener.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageEngine.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorage.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-17532
=> IGNITE-17532 Removed explicit flush after partition deletion in RockDB based partition storage.

modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/MvTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/AbstractPageMemoryTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/IndexPageIoModule.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/meta/IndexMeta.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/meta/IndexMetaTree.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/meta/io/IndexMetaInnerIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/meta/io/IndexMetaIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/meta/io/IndexMetaLeafIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/meta/io/IndexMetaTreeMetaIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/MvPageIoModule.java, modules/storage-page-memory/src/main/resources/META-INF/services/org.apache.ignite.internal.pagememory.io.PageIoModule
https://issues.apache.org/jira/browse/IGNITE-17533
=> IGNITE-17533 Implement a meta B+Tree of indexes

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/Checkpointer.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointerTest.java
https://issues.apache.org/jira/browse/IGNITE-17547
=> IGNITE-17547 AssertionError in page memory checkpointer

modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationChanger.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/notifications/ConfigurationNotifier.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/storage/ConfigurationStorage.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/ConfigurationChangerTest.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/storage/TestConfigurationStorage.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/tree/NamedListNodeTest.java, modules/core/src/main/java/org/apache/ignite/internal/util/ByteUtils.java, modules/metastorage-client/src/main/java/org/apache/ignite/internal/metastorage/client/EntryImpl.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/storage/ItDistributedConfigurationStorageTest.java, modules/runner/src/main/java/org/apache/ignite/internal/configuration/storage/DistributedConfigurationStorage.java, modules/runner/src/main/java/org/apache/ignite/internal/configuration/storage/LocalConfigurationStorage.java, modules/runner/src/test/java/org/apache/ignite/internal/configuration/storage/DistributedConfigurationCatchUpTest.java, modules/runner/src/test/java/org/apache/ignite/internal/configuration/storage/DistributedConfigurationStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-17555
=> IGNITE-17555 Fix AssertionError and NPE in configuration

modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/LocalLogStorageFactory.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/LogStorageFactoryCreator.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/VolatileLogStorageFactory.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/impl/VolatileLogStorageFactoryCreator.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/impl/LogStorageException.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/impl/Logs.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/impl/OnHeapLogs.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/impl/RocksDbSpillout.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/impl/VolatileLogStorage.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/storage/impl/VolatileLogStorageBudgetingTest.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/storage/impl/VolatileLogStorageSpecificsTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/storage/ItRebalanceDistributedTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/inmemory/ItRaftStorageVolatilityTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/MockedStructuresTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-17336
=> IGNITE-17336 Spill-out to disk support for volatile RAFT log storage

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/freelist/AbstractFreeList.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/freelist/FreeList.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/io/AbstractDataPageIo.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/PartitionMeta.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/io/PartitionMetaIo.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/PartitionMetaManagerTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/PartitionMetaTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointerTest.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/HashIndexStorage.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/chm/TestConcurrentHashMapMvTableStorage.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/index/AbstractHashIndexStorageTest.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/AbstractPageMemoryTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryDataRegion.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/freelist/IndexColumnsFreeList.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/freelist/io/IndexColumnsDataIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/InsertHashIndexRowInvokeClosure.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/PageMemoryHashIndexStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/RemoveHashIndexRowInvokeClosure.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/meta/IndexMeta.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/meta/io/IndexMetaIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/VolatilePageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/util/TreeCursorAdapter.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/PersistentPageMemoryHashIndexStorageTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/VolatilePageMemoryHashIndexStorageTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorageTest.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorage.java
https://issues.apache.org/jira/browse/IGNITE-17339
=> IGNITE-17339 Hash index storage for page-memory based engines.

modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/IndexPageIoModule.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/IndexPageTypes.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/freelist/IndexColumns.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/freelist/IndexColumnsFreeList.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/freelist/ReadIndexColumnsValue.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/freelist/io/IndexColumnsDataIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/io/HashIndexTreeIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/meta/IndexMeta.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/meta/io/IndexMetaInnerIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/meta/io/IndexMetaLeafIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/SortedIndexRow.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/SortedIndexRowKey.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/SortedIndexTree.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/io/SortedIndexTreeInnerIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/io/SortedIndexTreeIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/io/SortedIndexTreeLeafIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/io/SortedIndexTreeMetaIo.java
https://issues.apache.org/jira/browse/IGNITE-17670
=> IGNITE-17670 Implementing a sorted index B+Tree

modules/page-memory/src/integrationTest/java/org/apache/ignite/internal/pagememory/tree/AbstractBplusTreePageMemoryTest.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/AwaitTasksCompletionExecutor.java
https://issues.apache.org/jira/browse/IGNITE-17676
=> IGNITE-17676 Fixed race in AwaitTasksCompletionExecutor that causes tests to be flaky

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/tree/BplusTree.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/tree/io/BplusIo.java
https://issues.apache.org/jira/browse/IGNITE-17652
=> IGNITE-17652 Improve B+Tree implementation documentation in Ignite 3

modules/configuration-annotation-processor/src/integrationTest/resources/org/apache/ignite/internal/configuration/processor/TestConfigurationSchema.java, modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/ConfigurationProcessor.java, modules/configuration-api/src/main/java/org/apache/ignite/configuration/annotation/Value.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/asm/ConfigurationAsmGeneratorTest.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/tree/ConfigurationArrayTest.java
https://issues.apache.org/jira/browse/IGNITE-17689
=> IGNITE-17689 Add UUID support for org.apache.ignite.configuration.annotation.Value

modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageEngine.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbStorage.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/TxStateStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-17697
=> IGNITE-17697 Stop thread-pools when RocksDB components are stopped

modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationChanger.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/util/ConfigurationFlattener.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/util/ConfigurationSerializationUtil.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/tree/NamedListNodeTest.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/util/ConfigurationSerializationUtilTest.java
https://issues.apache.org/jira/browse/IGNITE-17698
=> IGNITE-17698 Fix UUID serialization in configuration

modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/SortedIndexStorage.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/index/AbstractSortedIndexStorageTest.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/index/TestSortedIndexStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/impl/TestSortedIndexStorage.java
https://issues.apache.org/jira/browse/IGNITE-17706
=> IGNITE-17706 Remove directions in SortedIndexStorage

modules/configuration/src/main/java/org/apache/ignite/internal/configuration/hocon/HoconPrimitiveConfigurationSource.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/tree/ConverterToMapVisitor.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/hocon/HoconConverterTest.java
https://issues.apache.org/jira/browse/IGNITE-17712
=> IGNITE-17712 Fix UUID serialization for hocon in configuration

check-rules/checkstyle-rules.xml
https://issues.apache.org/jira/browse/IGNITE-17715
=> IGNITE-17715 Specify default path to the checkstyle header

modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/SortedIndexTree.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/io/SortedIndexTreeIo.java
https://issues.apache.org/jira/browse/IGNITE-17672
=> IGNITE-17672 Support BinaryTuple comparator for sorted index B+Tree

modules/configuration-api/src/main/java/org/apache/ignite/configuration/NamedListView.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/util/ConfigurationUtil.java, modules/index/src/main/java/org/apache/ignite/internal/index/IndexManager.java, modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/flush/RocksDbFlusher.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/HashIndexDescriptor.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/SortedIndexDescriptor.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/ConcurrentHashMapMvTableStorageTest.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/index/AbstractSortedIndexStorageTest.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/index/TestHashIndexStorageTest.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/index/TestSortedIndexStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/chm/TestConcurrentHashMapMvTableStorage.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/chm/TestConcurrentHashMapStorageEngine.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractHashIndexStorageTest.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryStorageEngine.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryStorageEngine.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/PersistentPageMemoryHashIndexStorageTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/index/VolatilePageMemoryHashIndexStorageTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorageTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorageTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/VolatilePageMemoryMvPartitionStorageTest.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageEngine.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/SortedIndex.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorageTest.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvTableStorageTest.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageEngineTest.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbHashIndexStorageTest.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbSortedIndexStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-17727
=> IGNITE-17727 Improve storage code after Tables Configuration changes

modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/BinaryTupleComparator.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/index/AbstractSortedIndexStorageTest.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbBinaryTupleComparator.java
https://issues.apache.org/jira/browse/IGNITE-17740
=> IGNITE-17740 Fix prefix comparison in RocksDB Sorted Index

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/LocalStateStorage.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/rest/ClusterManagementController.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/rest/TopologyController.java, modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/cluster/TopologyApi.java
https://issues.apache.org/jira/browse/IGNITE-17745
=> IGNITE-17745 Fix race condition in CMG Manager

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftService.java
https://issues.apache.org/jira/browse/IGNITE-17493
=> IGNITE-17493 Add 'isLeader' check to CMG topology listener

modules/core/src/main/java/org/apache/ignite/internal/util/Cursor.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/MvPartitionStorage.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/BaseMvStoragesTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/chm/TestConcurrentHashMapMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java
https://issues.apache.org/jira/browse/IGNITE-17673
=> IGNITE-17673 Extended MV partition storage API with methods to help cleaning SQL indices

modules/rest/openapi/openapi.yaml
https://issues.apache.org/jira/browse/IGNITE-17769
=> IGNITE-17769 Fix modules/rest/openapi/openapi.yaml after change IgniteProductVersion

modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/BinaryTupleBuilder.java, modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/BinaryTuplePrefixBuilder.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/BinaryTuplePrefix.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/BinaryTuplePrefixTest.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbSortedIndexStorage.java
https://issues.apache.org/jira/browse/IGNITE-17711
=> IGNITE-17711 Append element count to the end of BinaryTuplePrefix

modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/BinaryTupleParser.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/BinaryTuple.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/BinaryTuplePrefix.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/MvTableStorage.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/HashIndexStorage.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/IndexStorage.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/SortedIndexStorage.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/chm/TestConcurrentHashMapMvTableStorage.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractSortedIndexStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/impl/TestIndexRow.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/impl/TestSortedIndexStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/AbstractPageMemoryTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/PageMemoryHashIndexStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/PageMemorySortedIndexStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/util/TreeCursorAdapter.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryMvTableStorageTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryMvTableStorageTest.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbSortedIndexStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbStorage.java
https://issues.apache.org/jira/browse/IGNITE-17755
=> IGNITE-17755 Add a common interface for all index storages

modules/api/src/main/java/org/apache/ignite/sql/async/AsyncResultSet.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/jdbc/JdbcQueryCursor.java, modules/client/src/main/java/org/apache/ignite/internal/client/sql/ClientAsyncResultSet.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeAsyncResultSet.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeCursor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/api/AsyncResultSetImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/AsyncCursor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/AsyncSqlCursorImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlQueryProcessor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/AsyncWrapper.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/AsyncRootNode.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/IgniteSqlApiTest.java
Make async public APIs consistent.
=> IGNITE-17118 Replace CompletionStage with CompletableFuture in public APIs

modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryStorageEngine.java
https://issues.apache.org/jira/browse/IGNITE-17795
=> IGNITE-17795 Need to stop the checkpoint manager before the data regions stop

modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/BinaryTupleBuilder.java, modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/BinaryTupleCommon.java, modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/BinaryTupleParser.java, modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/BinaryTupleReader.java, modules/binary-tuple/src/test/java/org/apache/ignite/internal/binarytuple/BinaryTupleTest.java, modules/platforms/dotnet/Apache.Ignite.Tests/Proto/BinaryTuple/BinaryTupleTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/BinaryTuple/BinaryTupleBuilder.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Proto/BinaryTuple/BinaryTupleReader.cs
IEP updated: https://cwiki.apache.org/confluence/display/IGNITE/IEP-92%3A+Binary+Tuple+Format
=> IGNITE-17801 Add support for Duration and Period types in BinaryTuple

modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractSortedIndexStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-17823
=> IGNITE-17823 Use static test sorted index name

modules/metrics/build.gradle, modules/metrics/pom.xml, modules/metrics/src/test/java/org/apache/ignite/internal/metrics/ThreadPoolMetricTest.java
https://issues.apache.org/jira/browse/IGNITE-17825
=> IGNITE-17825 ThreadPoolMetricTest.test is flaky

modules/schema/src/main/java/org/apache/ignite/internal/schema/BitmaskNativeType.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/NativeTypeTest.java
https://issues.apache.org/jira/browse/IGNITE-17844
=> IGNITE-17844 Fixed corner case in BitmaskNativeType constructor.

modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/BinaryTupleCommon.java, modules/core/src/main/java/org/apache/ignite/internal/util/CursorUtils.java, modules/core/src/test/java/org/apache/ignite/internal/util/CursorUtilsTest.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/tree/BplusTree.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/BinaryTuplePrefixTest.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/BinaryTupleComparator.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/index/BinaryTupleComparatorTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/impl/TestSortedIndexStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/PageMemorySortedIndexStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/io/SortedIndexTreeIo.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbBinaryTupleComparator.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbSortedIndexStorage.java
https://issues.apache.org/jira/browse/IGNITE-17818
=> IGNITE-17818 Optimize RocksDB-based sorted index scan

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/tree/BplusTree.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/tree/io/BplusInnerIo.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/tree/io/BplusIo.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/tree/io/BplusLeafIo.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/util/PageIdUtils.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/util/PartitionlessLinks.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/util/PartitionlessLinksTest.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/io/HashIndexTreeIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/io/SortedIndexTreeIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/ReadRowVersion.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/io/RowVersionDataIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/io/VersionChainIo.java
https://issues.apache.org/jira/browse/IGNITE-17843
=> IGNITE-17843 Use partitionless pageId in BplusInnerIo

modules/cli/src/main/java/org/apache/ignite/internal/cli/call/connect/ConnectCall.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/questions/ConnectToClusterQuestion.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/flow/Flow.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/flow/Flowable.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/flow/builder/FlowBuilder.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/flow/builder/FlowBuilderImpl.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/flow/builder/Flows.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/flow/FlowTest.java
https://issues.apache.org/jira/browse/IGNITE-17553
=> IGNITE-17553: Add flatMap function to Flow framework

modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/SqlCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/SqlReplCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/topology/LogicalTopologyCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/topology/LogicalTopologyReplCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/topology/PhysicalTopologyCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/topology/PhysicalTopologyReplCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/decorators/DefaultDecoratorRegistry.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/decorators/PlainTableDecorator.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/decorators/PlainTopologyDecorator.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/decorators/TableDecorator.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/decorators/TopologyDecorator.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/util/PlainTableRenderer.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/util/PlainTableRendererTest.java
https://issues.apache.org/jira/browse/IGNITE-17569
=> IGNITE-17569: Add option to display plain tables

modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractSortedIndexStorageTest.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbBinaryTupleComparator.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbSortedIndexStorage.java
https://issues.apache.org/jira/browse/IGNITE-17878
=> IGNITE-17878 Added bounds to the sorted index scan

modules/storage-api/src/main/java/org/apache/ignite/internal/storage/MvPartitionStorage.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/ReadResult.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/BaseMvStoragesTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/RowVersion.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/VersionChain.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorageTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItInternalTableScanTest.java
https://issues.apache.org/jira/browse/IGNITE-17254
=> IGNITE-17254 Storage API for RAFT snapshot streaming

modules/storage-api/src/main/java/org/apache/ignite/internal/storage/MvPartitionStorage.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorageTest.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItInternalTableScanTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
https://issues.apache.org/jira/browse/IGNITE-17849
=> IGNITE-17849 Remove filter from partition fullscan

modules/platforms/dotnet/Apache.Ignite.Tests/JavaServer.cs
Disable gradle daemon
https://issues.apache.org/jira/browse/IGNITE-17901
=> IGNITE-17901 .NET: Fix tests - disable Gradle daemon

modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractSortedIndexStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-17903
=> IGNITE-17903 Remove random index names from AbstractSortedIndexTest

modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/raft/ItCmgRaftServiceTest.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterState.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterTag.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/network/messages/ClusterStateMessage.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/network/messages/CmgMessageGroup.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListener.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftService.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/commands/ClusterNodeMessage.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/commands/InitCmgStateCommand.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/commands/JoinReadyCommand.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/commands/JoinRequestCommand.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/commands/ReadLogicalTopologyCommand.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/commands/ReadStateCommand.java, modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/AbstractClusterStateStorageManagerTest.java, modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListenerTest.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/MessageClass.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/serialization/BaseMethodNameResolver.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/serialization/MessageReaderMethodResolver.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/serialization/MessageWriterMethodResolver.java, modules/network-api/src/main/java/org/apache/ignite/network/serialization/MessageReader.java, modules/network-api/src/main/java/org/apache/ignite/network/serialization/MessageWriter.java, modules/network/src/main/java/org/apache/ignite/internal/network/direct/DirectMessageReader.java, modules/network/src/main/java/org/apache/ignite/internal/network/direct/DirectMessageWriter.java, modules/network/src/main/java/org/apache/ignite/internal/network/direct/stream/DirectByteBufferStream.java, modules/network/src/main/java/org/apache/ignite/internal/network/direct/stream/DirectByteBufferStreamImplV1.java, modules/network/src/test/java/org/apache/ignite/internal/network/AllTypesMessageGenerator.java, modules/network/src/test/java/org/apache/ignite/internal/network/messages/AllTypesMessage.java
https://issues.apache.org/jira/browse/IGNITE-17887
=> IGNITE-17887 CMG RAFT commands converted to Transferable classes

docs/_docs/config/data-region.adoc
https://issues.apache.org/jira/browse/IGNITE-17210
=> IGNITE-17210 Changed data region documentation to remove config

modules/table/src/test/java/org/apache/ignite/internal/table/TxAbstractTest.java
https://issues.apache.org/jira/browse/IGNITE-18013
=> IGNITE-18013 Unmute tests after IGNITE-17968

modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/questions/ConnectToClusterQuestion.java
https://issues.apache.org/jira/browse/IGNITE-17752
This is a clarification of the message shown on REPL start.
=> IGNITE-17752 Clarify message shown when CLI was not started before

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-18074
=> IGNITE-18074 Fix tx state storage not destroyed on table drop.

modules/platforms/cpp/ignite/schema/CMakeLists.txt, modules/platforms/cpp/ignite/schema/binary_tuple_builder.cpp, modules/platforms/cpp/ignite/schema/binary_tuple_builder.h, modules/platforms/cpp/ignite/schema/binary_tuple_parser.cpp, modules/platforms/cpp/ignite/schema/binary_tuple_parser.h, modules/platforms/cpp/ignite/schema/tuple_assembler.h, modules/platforms/cpp/ignite/schema/tuple_test.cpp
https://issues.apache.org/jira/browse/IGNITE-18017
=> IGNITE-18017 Add C++ tests for binary tuple

modules/index/build.gradle, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/LogicalRelImplementor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/IndexScanNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/TableScanNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rel/IgniteIndexScan.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/IgniteTableImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/InternalIgniteTable.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/IndexScanNodeExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/TableScanNodeExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/AbstractPlannerTest.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/HashIndexDescriptor.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNode.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerIndexLockingTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-18090
Shutdown executor on node stop.
Fixed thread/pool names.
Fixed minor styles issues.
=> IGNITE-18090 Sql. Shutdown scan query executor on node stop

modules/index/src/test/java/org/apache/ignite/internal/index/IndexManagerTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/TableImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/test/java/org/apache/ignite/internal/table/Example.java
https://issues.apache.org/jira/browse/IGNITE-17846
=> IGNITE-17846 Indirect waiting of getting direct configuration value

modules/api/src/main/java/org/apache/ignite/tx/TransactionException.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-18125
=> IGNITE-18125 Fix NullPointerException in InternalTableImpl#enlist()

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/RebalanceRaftGroupEventsListener.java
https://issues.apache.org/jira/browse/IGNITE-18126
=> IGNITE-18126 Fix NPE in RebalanceRaftGroupEventsListener#onLeaderElected()

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/SortedIndexLocker.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/LockManager.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/HeapLockManager.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/AbstractLockManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-18052
=> IGNITE-18052 Introduce short term locks for sorted indexes operations

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-18181
=> IGNITE-18181 Race during table creation

modules/storage-api/build.gradle, modules/storage-api/pom.xml, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/RowId.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageTest.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java
https://issues.apache.org/jira/browse/IGNITE-18193
=> IGNITE-18193 Removed transactions dependency from storage-api

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-18204
=> IGNITE-18204 Start RAFT groups of table partitions in parallel

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTableScanTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/HashIndexLocker.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/IndexLocker.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/SortedIndexLocker.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
https://issues.apache.org/jira/browse/IGNITE-18165
=> IGNITE-18165 Applied short term locks to sorted indexes

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/LeaderOrTxState.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PlacementDriver.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java
https://issues.apache.org/jira/browse/IGNITE-18248
=> IGNITE-18248 Introduce LeaderOrTxState class instead of IgniteBiTuple

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/RaftStorageManager.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/commands/NodesLeaveCommand.java, modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/AbstractClusterStateStorageManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-18240
=> IGNITE-18240 Store logical topology as a single KV entry instead of a number of entries

modules/rest/src/main/java/org/apache/ignite/internal/rest/RestComponent.java
https://issues.apache.org/jira/browse/IGNITE-18263
=> IGNITE-18263 Fix REST API version in the generated openapi.yaml

examples/build.gradle, modules/bytecode/build.gradle, modules/raft-client/build.gradle, modules/runner/build.gradle, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
* Enable checkstyle in ignite-runner, ignite-bytecode, ignite-examples modules.
* Removed unused imports
https://issues.apache.org/jira/browse/IGNITE-18270
=> IGNITE-18270: Fix checkstyle in ignite-runner module

modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/ItClusterManagerTest.java, modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/MockNode.java, modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/raft/ItCmgRaftServiceTest.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftService.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/responses/LogicalTopologyResponse.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/rest/TopologyController.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/topology/LogicalTopology.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/topology/LogicalTopologyImpl.java, modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/topology/LogicalTopologyImplTest.java
https://issues.apache.org/jira/browse/IGNITE-18276
=> IGNITE-18276 Return topology version in CMGManager.logicalTopology()

modules/runner/build.gradle
https://issues.apache.org/jira/browse/IGNITE-18298
=> IGNITE-18298 .NET: Enable Java assertions in tests

.gitignore
https://issues.apache.org/jira/browse/IGNITE-18344
=> IGNITE-18344 Missing .gitignore items

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTableScanTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/TxAbstractTest.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/LockMode.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/Waiter.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/HeapLockManager.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/AbstractLockManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-18294
=> IGNITE-18294 Multiple lock intentions support

modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/ExitCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/TopLevelCliReplCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/SqlCompleter.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/SqlReplCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/SqlReplTopLevelCliCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/help/IgniteSqlCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/help/IgniteSqlCommandCompleter.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/help/IgniteSqlCommandConverter.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/help/SqlHelpCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/exception/handler/PicocliExecutionExceptionHandler.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/executor/IgnitePicocliCommands.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/executor/RegistryCommandExecutor.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/executor/ReplExecutor.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/sql/help/SqlHelpCommandTest.java
https://issues.apache.org/jira/browse/IGNITE-18101
=> IGNITE-18101: Add help for SQL commands

modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerConfigurationChangesTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
https://issues.apache.org/jira/browse/IGNITE-18359
=> IGNITE-18359 fix build after merging IGNITE-18117

modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/WorkDirectoryExtension.java
https://issues.apache.org/jira/browse/IGNITE-18399
=> IGNITE-18399 Adapt WorkDirectoryExtension to Gradle

modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/raft/ItCmgRaftServiceTest.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java, modules/metastorage-client/src/integrationTest/java/org/apache/ignite/internal/metastorage/client/ItMetaStorageServiceTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/MetaStorageManager.java, modules/raft-api/src/main/java/org/apache/ignite/internal/raft/RaftManager.java, modules/raft/src/integrationTest/java/org/apache/ignite/internal/raft/ItLearnersTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/internal/raft/ItLozaTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/internal/raft/ItRaftGroupServiceTest.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/Loza.java, modules/raft/src/test/java/org/apache/ignite/internal/raft/LozaTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/MockedStructuresTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNode.java
https://issues.apache.org/jira/browse/IGNITE-18374
=> IGNITE-18374 Remove RaftManager#prepareRaftGroup method

modules/runner/src/integrationTest/java/org/apache/ignite/internal/AbstractClusterIntegrationTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/compute/ItLogicalTopologyTest.java
https://issues.apache.org/jira/browse/IGNITE-18402
=> IGNITE-18402 ItLogicalTopologyTest.receivesLogicalTopologyEventsCausedByNodeRestart fails locally

modules/client-common/build.gradle, modules/marshaller-common/build.gradle, modules/network/build.gradle, modules/raft/build.gradle, modules/schema/build.gradle, modules/table/build.gradle
https://issues.apache.org/jira/browse/IGNITE-18420
=> IGNITE-18420 JMH dependencies improved.

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotCopier.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotCopierTest.java
https://issues.apache.org/jira/browse/IGNITE-18421
=> IGNITE-18421 Fix IncomingSnapshotCopier#cancel for the case of network problems

modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/completer/CompleterConf.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/completer/DynamicCompleterActivationPoint.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/completer/filter/CompleterFilter.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/completer/filter/DynamicCompleterFilter.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/completer/filter/ExclusionsCompleterFilter.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/completer/filter/NonRepeatableOptionsFilter.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/completer/filter/ShortOptionsFilter.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/executor/IgnitePicocliCommands.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/executor/ReplExecutor.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/core/repl/completer/filter/DynamicCompleterFilterTest.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/core/repl/completer/filter/ExclusionsCompleterFilterTest.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/core/repl/completer/filter/NonRepeatableOptionsFilterTest.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/core/repl/completer/filter/ShortOptionsFilterTest.java
https://issues.apache.org/jira/browse/IGNITE-18221
=> IGNITE-18221: Filter non-repitable options in interactive suggestions

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/topology/LogicalTopologyImpl.java, modules/distribution-zones/build.gradle, modules/distribution-zones/pom.xml, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZonesUtil.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerConfigurationChangesTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerLogicalTopologyEventsTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/storage/ItDistributedConfigurationStorageTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItTablesApiTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/runner/src/main/java/org/apache/ignite/internal/configuration/storage/DistributedConfigurationStorage.java
https://issues.apache.org/jira/browse/IGNITE-18087
=> IGNITE-18087 Populate DistributionZoneManager with CMG listeners to logical topology events

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/ValidationManager.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/storage/ItDistributedConfigurationStorageTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItTablesApiTest.java
https://issues.apache.org/jira/browse/IGNITE-18410
=> IGNITE-18410 Disabled ItDistributedConfigurationStorageTest#testRestartWithPds fixed.

packaging/build.gradle
https://issues.apache.org/jira/browse/IGNITE-18151
=> IGNITE-18151 Fix paths inside source zip

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItTablesApiTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTableScanTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/SortedIndexLocker.java
https://issues.apache.org/jira/browse/IGNITE-18050
=> IGNITE-18050 Possible phantom reads during sorted index scan

modules/raft/src/main/java/org/apache/ignite/raft/jraft/util/SafeTimeCandidateManager.java
https://issues.apache.org/jira/browse/IGNITE-18432
=> IGNITE-18432

modules/core/src/main/java/org/apache/ignite/lang/ErrorGroups.java, modules/transactions/build.gradle, modules/transactions/pom.xml, modules/transactions/src/main/java/org/apache/ignite/internal/tx/TxMeta.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/TxStateStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/TxStateTableStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbStorage.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbTableStorage.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/rocksdb/RocksDbTxStateStorageTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/test/TestTxStateStorageTest.java, modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/AbstractTxStateStorageTest.java, modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/test/TestTxStateStorage.java, modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/test/TestTxStateTableStorage.java
https://issues.apache.org/jira/browse/IGNITE-18022
=> IGNITE-18022 Creating an API for full rebalance of TxStateStorage on receiver

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTableScanTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
https://issues.apache.org/jira/browse/IGNITE-18057
=> IGNITE-18057 Fixed index scan transactional consistency.

modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/IgniteTestUtils.java, modules/storage-api/build.gradle, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/BinaryRowAndRowId.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/BinaryRowWithRowId.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/MvPartitionStorage.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/StorageEngine.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/TestMvPartitionStorageConcurrencyTest.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/TestMvPartitionStorageGcTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageConcurrencyTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageGcTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/BaseMvPartitionStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/BaseMvStoragesTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvPartitionStorage.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestStorageEngine.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryStorageEngine.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryStorageEngine.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorageTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorageConcurrencyTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorageTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/VolatilePageMemoryMvPartitionStorageConcurrencyTest.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageEngine.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorageConcurrencyTest.java
https://issues.apache.org/jira/browse/IGNITE-18019
=> IGNITE-18019 GC methods in MvPartitionStorage & new tests & old tests reorganization.

modules/storage-api/src/main/java/org/apache/ignite/internal/storage/ReadResult.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/ReadResultTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/BaseMvPartitionStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/BaseMvStoragesTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItAbstractInternalTableScanTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/outgoing/OutgoingSnapshotMvDataStreamingTest.java
https://issues.apache.org/jira/browse/IGNITE-17467
=> IGNITE-17467 Return RowIds in MvPartitionStorage#scan() results

modules/page-memory/src/integrationTest/java/org/apache/ignite/internal/pagememory/tree/AbstractBplusTreePageMemoryTest.java
https://issues.apache.org/jira/browse/IGNITE-17235
=> IGNITE-17235 Fix flaky ItBplusTreePageMemoryImplTest#testPutSizeLivelock

modules/core/src/main/java/org/apache/ignite/lang/ErrorGroups.java, modules/table/src/main/java/org/apache/ignite/internal/table/TableImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-18451
=> IGNITE-18451 Node stop may hang if an index is not created yet

modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/snapshot/SnapshotExecutorImpl.java, modules/raft/src/test/java/org/apache/ignite/raft/jraft/storage/SnapshotExecutorTest.java
https://issues.apache.org/jira/browse/IGNITE-18495
=> IGNITE-18495 Fix RAFT snapshot installation hang due to response swap on retry

modules/core/src/main/java/org/apache/ignite/internal/hlc/HybridTimestamp.java, modules/core/src/test/java/org/apache/ignite/internal/hlc/HybridTimestampTest.java
https://issues.apache.org/jira/browse/IGNITE-18500
=> IGNITE-18500 HybridTimestamp defines equals(), but not hashCode()

modules/raft/src/main/java/org/apache/ignite/internal/raft/server/RaftServer.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/FSMCallerImpl.java, modules/runner/build.gradle, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItRaftCommandLeftInLogUntilRestartTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItTableApiContractTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/AbstractBasicIntegrationTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java
https://issues.apache.org/jira/browse/IGNITE-18044
=> IGNITE-18044 Recovery collection of pending transaction on node start.

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItDataSchemaSyncTest.java
https://issues.apache.org/jira/browse/IGNITE-18514
=> IGNITE-18514 Disable ItDataSchemaSyncTest.checkSchemasCorrectlyRestore()

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/util/QueryChecker.java
https://issues.apache.org/jira/browse/IGNITE-18530
=> IGNITE-18530 Fix integration test failures on Windows

modules/metastorage-api/build.gradle, modules/metastorage/build.gradle
Add publishing specifications into metastorage modules gradle configuration.
=> IGNITE-18508 Fix metastorage gradle publishing

modules/page-memory/src/integrationTest/java/org/apache/ignite/internal/pagememory/tree/AbstractBplusTreePageMemoryTest.java
https://issues.apache.org/jira/browse/IGNITE-18541
=> IGNITE-18541 AbstractBplusTreePageMemoryTest "optimized".

modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/messages/MessageBuilderGenerator.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/messages/MessageImplGenerator.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/serialization/MessageDeserializerGenerator.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/serialization/MessageSerializerGenerator.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/serialization/SerializationFactoryGenerator.java
https://issues.apache.org/jira/browse/IGNITE-18547
=> IGNITE-18547 Fixed issue when IDEA would show NOTE messages as errors

modules/metastorage/build.gradle, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageManagerImplTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/command/MetastorageCommandsMessageGroup.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/command/PrefixCommand.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageService.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageServiceImpl.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/KeyValueStorage.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/raft/MetaStorageListener.java, modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java
https://issues.apache.org/jira/browse/IGNITE-18558
=> IGNITE-18558 Fix Meta Storage prefix overflow

modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbHashIndexStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbSortedIndexStorage.java
https://issues.apache.org/jira/browse/IGNITE-18566
=> IGNITE-18566 Fix busyLock usage in RocksDbTableStorage and related

modules/transactions/README.md
https://issues.apache.org/jira/browse/IGNITE-18522
=> IGNITE-18522

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/CliCommandTestNotInitializedIntegrationBase.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/core/repl/executor/ItIgnitePicocliCommandsTest.java
JdbcUrlDynamicCompleterFactory, ClusterUrlDynamicCompleterFactory, FilePathCompleter
https://issues.apache.org/jira/browse/IGNITE-18491
=> IGNITE-18491 Add tests for CLI completers

modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/AbstractPageMemoryTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryStorageEngine.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/PageMemoryHashIndexStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/PageMemorySortedIndexStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/VolatilePageMemoryMvPartitionStorage.java
https://issues.apache.org/jira/browse/IGNITE-18571
=> IGNITE-18571 Fix busyLock usage in AbstractPageMemoryTableStorage and related

modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/VolatilePageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryMvTableStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-18028
=> IGNITE-18028 Implementation of a full rebalance for VolatilePageMemoryMvPartitionStorage on receiver

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java, modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java
https://issues.apache.org/jira/browse/IGNITE-18598
=> IGNITE-18598 Fix compilation after merge

modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/MvTableStorage.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvPartitionStorage.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/AbstractPageMemoryTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/VolatilePageMemoryMvPartitionStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorage.java
https://issues.apache.org/jira/browse/IGNITE-18596
=> IGNITE-18596 Add RaftGroupConfiguration to MvTableStorage#finishRebalancePartition

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/metastorage/build.gradle, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageManagerImplTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageWatchTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/KeyValueStorage.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/OnRevisionAppliedCallback.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/WatchProcessor.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AbstractKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/RocksDbKeyValueStorageTest.java, modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/test/WatchListenerInhibitor.java, modules/runner/src/main/java/org/apache/ignite/internal/configuration/storage/DistributedConfigurationStorage.java
https://issues.apache.org/jira/browse/IGNITE-18600
=> IGNITE-18600 Save Meta Storage watch data to the Vault

modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvTableStorage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/PartitionAccess.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/PartitionAccessImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotCopier.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/PartitionAccessImplTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotCopierTest.java
https://issues.apache.org/jira/browse/IGNITE-18086
=> IGNITE-18086 Add index building in IncomingSnapshotCopier

modules/platforms/cpp/DEVNOTES.md, modules/platforms/cpp/ignite/client/detail/cluster_connection.cpp, modules/platforms/cpp/ignite/client/detail/logger_wrapper.h, modules/platforms/cpp/ignite/client/detail/node_connection.h, modules/platforms/cpp/ignite/client/ignite_logger.h, modules/platforms/cpp/tests/client-test/gtest_logger.h, modules/platforms/cpp/tests/client-test/ignite_client_test.cpp, modules/platforms/cpp/tests/client-test/ignite_runner_suite.h, modules/platforms/cpp/tests/client-test/main.cpp, modules/platforms/cpp/tests/client-test/record_binary_view_test.cpp, modules/platforms/cpp/tests/client-test/sql_test.cpp, modules/platforms/cpp/tests/client-test/tables_test.cpp, modules/platforms/cpp/tests/client-test/transactions_test.cpp, modules/platforms/cpp/tests/test-common/ignite_runner.cpp, modules/platforms/cpp/tests/test-common/ignite_runner.h, modules/platforms/cpp/tests/test-common/test_utils.cpp, modules/platforms/cpp/tests/test-common/test_utils.h
- Improved DEVNOTES.md;
- Fixed compilation errors and warnings;
- Introduce single-node mode to lower number of TC fails until causing issue is fixed;
=> IGNITE-18583 Fix C++ build

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/PartitionAccess.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/PartitionAccessImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotCopier.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/incoming/IncomingSnapshotCopierTest.java, modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/test/TestTxStateTableStorage.java
https://issues.apache.org/jira/browse/IGNITE-18030
=> IGNITE-18030 Integration of the new full rebalance API with IncomingSnapshotCopier

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/PartitionAccessImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/storage/state/rocksdb/TxStateRocksDbStorage.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/rocksdb/RocksDbTxStateStorageTest.java, modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/AbstractTxStateStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-18629
=> IGNITE-18629 Slightly improve busyLock usage in TxStateRocksDbStorage

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlAsynchronousApiTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/AbstractBasicIntegrationTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItIndexSpoolTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSecondaryIndexTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTableScanTest.java
https://issues.apache.org/jira/browse/IGNITE-18631
=> IGNITE-18631 Fix flaky ItSqlAsynchronousApiTest#checkMixedTransactionsForIndex test

modules/runner/src/integrationTest/java/org/apache/ignite/internal/AbstractClusterIntegrationTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/Cluster.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/compute/ItLogicalTopologyTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/inmemory/ItRaftStorageVolatilityTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java
https://issues.apache.org/jira/browse/IGNITE-18465
=> IGNITE-18465 Use Cluster in AbstractClusterIntegrationTest

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftService.java, modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/matchers/CompletableFutureMatcher.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageManagerImplTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageService.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageServiceImpl.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/WatchProcessor.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AbstractKeyValueStorageTest.java, modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/RaftGroupServiceImpl.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteInMemoryNodeRestartTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-18446
=> IGNITE-18446 Add busy lock to raft service

buildscripts/java-integration-test.gradle, buildscripts/java-junit5.gradle, modules/core/build.gradle, modules/core/src/test/java/org/apache/ignite/internal/util/IgniteStripedLockSelfTest.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/junit/DumpThreadsOnTimeout.java, modules/core/src/testFixtures/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
https://issues.apache.org/jira/browse/IGNITE-18638
=> IGNITE-18638 Make tests print thread dump when timing out

buildscripts/java-integration-test.gradle, buildscripts/java-junit5.gradle
https://issues.apache.org/jira/browse/IGNITE-18646
=> IGNITE-18646 Raise default JUnit test timeouts

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/IntegrationTestBase.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/core/repl/executor/ItIgnitePicocliCommandsTest.java, modules/network/src/main/java/org/apache/ignite/internal/network/configuration/ClusterMembershipConfigurationSchema.java, modules/network/src/main/java/org/apache/ignite/internal/network/configuration/ScaleCubeConfigurationSchema.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/AbstractClusterIntegrationTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/compute/ItLogicalTopologyTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
https://issues.apache.org/jira/browse/IGNITE-18611
=> IGNITE-18611 Change Scalecube-related timeouts to Scalecube defaults

modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcBatchSelfTest.java, modules/platforms/dotnet/Apache.Ignite.Tests/Sql/SqlTests.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlAsynchronousApiTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlSynchronousApiTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDynamicParameterTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItLimitOffsetTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSecondaryIndexTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/util/QueryChecker.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteSqlValidator.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PrepareServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/IgniteResource.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/PlannerTest.java
=> IGNITE-18422: Sql. Match number of dynamic parameters with given parameters

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/core/repl/executor/ItIgnitePicocliCommandsTest.java, modules/cluster-management/build.gradle, modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/MockNode.java, modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/raft/ItCmgRaftServiceTest.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/configuration/ClusterManagementConfigurationModule.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/configuration/ClusterManagementConfigurationSchema.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListener.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/ValidationManager.java, modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListenerTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/ItDistributedConfigurationPropertiesTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/storage/ItDistributedConfigurationStorageTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/storage/ItRebalanceDistributedTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
https://issues.apache.org/jira/browse/IGNITE-16785
=> IGNITE-16785 Add configuration for the timeout for removing nodes from logical topology

modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/HashIndex.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/SortedIndex.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvTableStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-18523
=> IGNITE-18523 Destroy RocksDbTableStorage on destroy()

modules/client/src/test/java/org/apache/ignite/client/ClientArchTest.java
https://issues.apache.org/jira/browse/IGNITE-18680
* Use source code instead of jar file
=> IGNITE-18680: Fix ClientArchTest source location provider

modules/index/src/main/java/org/apache/ignite/internal/index/IndexManager.java
https://issues.apache.org/jira/browse/IGNITE-18684
=> IGNITE-18684 Fix busyLock.leaveBusy() in IndexManager#onIndexDrop

modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/util/GradualTaskExecutorTest.java
https://issues.apache.org/jira/browse/IGNITE-18686
=> IGNITE-18686 GradualTaskExecutorTest.nonFinishedTasksAreCancelledWhenExecutorIsClosed is flaky

modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/BaseItClusterManagementTest.java, modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/ItClusterManagerTest.java, modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/MockNode.java, modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/rest/ItClusterManagementControllerTest.java, modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/rest/RestTestBase.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/server/raft/ItMetaStorageRaftGroupTest.java, modules/raft-api/src/main/java/org/apache/ignite/internal/raft/configuration/RaftConfigurationSchema.java, modules/raft-api/src/main/java/org/apache/ignite/internal/raft/service/RaftGroupService.java, modules/raft/build.gradle, modules/raft/src/integrationTest/java/org/apache/ignite/internal/raft/ItLearnersTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/server/ItJraftCounterServerTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/server/ItSimpleCounterServerTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/server/JraftAbstractTest.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/Loza.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/RaftGroupServiceImpl.java, modules/raft/src/test/java/org/apache/ignite/internal/raft/RaftGroupServiceTest.java, modules/raft/src/testFixtures/java/org/apache/ignite/internal/raft/service/ItAbstractListenerSnapshotTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNode.java
https://issues.apache.org/jira/browse/IGNITE-18682
=> IGNITE-18682 Extract RaftService timeouts to configuration

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java
https://issues.apache.org/jira/browse/IGNITE-17958
=> IGNITE-17958 PartitionListener should not close partition storage

modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/tx/ClientTransactionBeginRequest.java, modules/client/src/main/java/org/apache/ignite/internal/client/TcpIgniteClient.java, modules/client/src/main/java/org/apache/ignite/internal/client/tx/ClientTransactions.java, modules/platforms/cpp/ignite/client/detail/transaction/transaction_impl.h, modules/platforms/cpp/ignite/client/detail/transaction/transactions_impl.h, modules/platforms/cpp/ignite/protocol/writer.h, modules/platforms/dotnet/Apache.Ignite/Internal/Transactions/Transactions.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientTransactionsTest.java
* Add readOnly flag to the client protocol.
* Add support to Java thin API.
=> IGNITE-17929 Add read-only support to ClientTransactions

modules/table/src/test/java/org/apache/ignite/internal/table/KeyValueBinaryViewOperationsTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/KeyValueViewOperationsSimpleSchemaTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/KeyValueViewOperationsTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/RecordViewOperationsTest.java
https://issues.apache.org/jira/browse/IGNITE-18709
=> IGNITE-18709 Remove mention of already resolved issues

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
https://issues.apache.org/jira/browse/IGNITE-18737
=> IGNITE-18737 disable ItIgniteNodeRestartTest

modules/raft/src/integrationTest/java/org/apache/ignite/internal/raft/ItLearnersTest.java
[IGNITE-18740](https://issues.apache.org/jira/browse/IGNITE-18740)
=> IGNITE-18740 Use default timeout in ItLearnersTest

modules/index/src/main/java/org/apache/ignite/internal/index/IndexManager.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/BinaryConverter.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/BinaryTupleSchema.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/BinaryTupleSchemaTest.java
https://issues.apache.org/jira/browse/IGNITE-18701
=> IGNITE-18701 Incorrect binary tuple column mapping

modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/ItClusterManagerTest.java, modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/MockNode.java, modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/raft/ItCmgRaftServiceTest.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/configuration/ClusterManagementConfigurationSchema.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/network/messages/CmgMessageGroup.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListener.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftService.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/RaftStorageManager.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/ValidationManager.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/commands/ReadValidatedNodesCommand.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/topology/LogicalTopology.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/topology/LogicalTopologyImpl.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/topology/LogicalTopologyServiceImpl.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/topology/api/LogicalTopologyEventListener.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/topology/api/LogicalTopologyService.java, modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/AbstractClusterStateStorageManagerTest.java, modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListenerTest.java, modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/topology/LogicalTopologyImplTest.java, modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/topology/LogicalTopologyServiceImplTest.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/Cluster.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/compute/ItLogicalTopologyTest.java
https://issues.apache.org/jira/browse/IGNITE-18734
=> IGNITE-18734 Add validation-related events to Logical Topology

modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/raft/client/TopologyAwareRaftGroupServiceTest.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/raft/client/TopologyAwareRaftGroupService.java
https://issues.apache.org/jira/browse/IGNITE-18771
=> IGNITE-18771 Compilation fixed

modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/impl/TestHashIndexStorage.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/impl/TestSortedIndexStorage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/StorageUpdateHandler.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableSchemaAwareIndexStorage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionDataStorage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/outgoing/SnapshotAwarePartitionDataStorage.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/IndexCleanupTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java, modules/table/src/testFixtures/java/org/apache/ignite/distributed/TestPartitionDataStorage.java
https://issues.apache.org/jira/browse/IGNITE-18738
=> IGNITE-18738 Cleanup indexes on transaction abort

modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java
https://issues.apache.org/jira/browse/IGNITE-18774
=> IGNITE-18774 PartitionReplicaListenerTest#testReadOnlyGetAllAfterRowRewrite hangs forever

modules/core/src/main/java/org/apache/ignite/internal/util/CollectionUtils.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/TxAbstractTest.java
https://issues.apache.org/jira/browse/IGNITE-18632
=> IGNITE-18632 Barrier for locks after cleanup started

modules/client-handler/build.gradle, modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/ItClientHandlerTest.java, modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/ItSslClientHandlerTest.java, modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/TestServer.java, modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/TestSslConfig.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientHandlerModule.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/configuration/ClientConnectorConfigurationSchema.java, modules/client/build.gradle, modules/client/src/main/java/org/apache/ignite/client/ClientAuthenticationMode.java, modules/client/src/main/java/org/apache/ignite/client/IgniteClient.java, modules/client/src/main/java/org/apache/ignite/client/IgniteClientConfiguration.java, modules/client/src/main/java/org/apache/ignite/client/SslConfiguration.java, modules/client/src/main/java/org/apache/ignite/internal/client/IgniteClientConfigurationImpl.java, modules/client/src/main/java/org/apache/ignite/internal/client/SslConfigurationBuilder.java, modules/client/src/main/java/org/apache/ignite/internal/client/SslConfigurationImpl.java, modules/client/src/main/java/org/apache/ignite/internal/client/io/netty/NettyClientConnectionMultiplexer.java, modules/client/src/test/java/org/apache/ignite/client/RetryPolicyTest.java, modules/core/src/main/java/org/apache/ignite/lang/ErrorGroups.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/ssl/ItSslTest.java
* Client side: add `IgniteClientConfiguration.ssl`
* Server side: add `ClientConnectorConfigurationSchema.ssl`
https://issues.apache.org/jira/browse/IGNITE-18578
=> IGNITE-18578 Add SSL for Java client

modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestThreeNodesThreeReplicas.java
https://issues.apache.org/jira/browse/IGNITE-18813
=> IGNITE-18813 Useless waits commented with TODO in ItTxDistributedTestThreeNodesThreeReplicas.

modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/ItClusterManagerTest.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesTest.java
https://issues.apache.org/jira/browse/IGNITE-18795
=> IGNITE-18795 Reduce the number of Logical Topology updates

modules/platforms/cpp/CMakeLists.txt, modules/platforms/cpp/ignite/client/CMakeLists.txt, modules/platforms/cpp/ignite/common/CMakeLists.txt, modules/platforms/cpp/ignite/schema/CMakeLists.txt
CMake option to disable install ignite files added.
=> IGNITE-18802 CMake: option for the install target added.

modules/rest/build.gradle, modules/rest/src/main/java/org/apache/ignite/internal/rest/RestComponent.java, modules/rest/src/main/java/org/apache/ignite/internal/rest/configuration/RestSslConfigurationSchema.java, modules/rest/src/test/java/org/apache/ignite/internal/rest/RestComponentTest.java, modules/rest/src/test/java/org/apache/ignite/internal/rest/TestController.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/rest/ItPortRangeTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/rest/ssl/ItRestSslTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/rest/ssl/RestNode.java
https://issues.apache.org/jira/browse/IGNITE-18791
TCP Client and JDBC support this feature, now REST does it too.
=> IGNITE-18791 Add SSL Client authentication to REST

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-18768
=> IGNITE-18768 fix incorrect safe time initialization in TableManager

modules/platforms/cpp/ignite/client/CMakeLists.txt, modules/platforms/cpp/ignite/client/detail/client_operation.h, modules/platforms/cpp/ignite/client/detail/table/table_impl.cpp, modules/platforms/cpp/ignite/client/detail/table/table_impl.h, modules/platforms/cpp/ignite/client/detail/utils.cpp, modules/platforms/cpp/ignite/client/detail/utils.h, modules/platforms/cpp/ignite/client/table/ignite_tuple.h, modules/platforms/cpp/ignite/client/table/key_value_view.cpp, modules/platforms/cpp/ignite/client/table/key_value_view.h, modules/platforms/cpp/ignite/client/table/record_view.h, modules/platforms/cpp/ignite/client/table/table.cpp, modules/platforms/cpp/ignite/client/table/table.h, modules/platforms/cpp/tests/client-test/CMakeLists.txt, modules/platforms/cpp/tests/client-test/ignite_runner_suite.h, modules/platforms/cpp/tests/client-test/key_value_binary_view_test.cpp
Implemented:
- `key_value_view<ignite_tuple, ignite_tuple>`;
- Tests;
- Tuple conversation is not optimal, ticket created to optimize it when other record and kv views are ready.
=> IGNITE-17589 C++ Implement binary key_value_view

modules/platforms/cpp/ignite/client/CMakeLists.txt, modules/platforms/cpp/ignite/schema/CMakeLists.txt
=> IGNITE-18802 fix

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/CliCommandTestNotInitializedIntegrationBase.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/ItNodeNameTest.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/registry/impl/JdbcUrlRegistryImpl.java
https://issues.apache.org/jira/browse/IGNITE-18866
=> IGNITE-18866 JdbcUrlRegistryImpl should stop fetching URLs after disconnect

modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/junit/DumpThreadsOnTimeout.java
https://issues.apache.org/jira/browse/IGNITE-18861
=> IGNITE-18861 NPE in DumpThreadsOnTimeout extension

modules/cli/src/main/java/org/apache/ignite/internal/cli/core/flow/builder/FlowBuilderImpl.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/executor/ReplExecutor.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/row/RowAssembler.java
https://issues.apache.org/jira/browse/IGNITE-18894
=> IGNITE-18894 Cleanup resolved TODOs

modules/metastorage/README.md, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItTablesApiTest.java
https://issues.apache.org/jira/browse/IGNITE-18903
=> IGNITE-18903 Remove TODOs mentioning closed issues

modules/schema/src/main/java/org/apache/ignite/internal/schema/configuration/storage/DataStorageConfigurationSchema.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTablePersistenceTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNode.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/StorageUpdateHandler.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/IndexBaseTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/PartitionGcOnWriteConcurrentTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/PartitionGcOnWriteTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/PartitionCommandListenerTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerIndexLockingTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-18033
=> IGNITE-18033 Implement cooperative GC of MV data during RAFT commands execution

modules/runner/src/main/java/org/apache/ignite/internal/configuration/storage/LocalFileConfigurationStorage.java, modules/runner/src/test/java/org/apache/ignite/internal/configuration/storage/ConfigurationStorageTest.java, modules/runner/src/test/java/org/apache/ignite/internal/configuration/storage/LocalFileConfigurationStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-18833
=> IGNITE-18833 Fix node configuration file render method and write tests

modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageGcTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AddWriteCommittedInvokeClosure.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/CommitWriteInvokeClosure.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/GarbageCollector.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbMvPartitionStorage.java
https://issues.apache.org/jira/browse/IGNITE-18882
=> IGNITE-18882 Don't store tombstones if there is no other version of row

modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcResultSetSelfTest.java
https://issues.apache.org/jira/browse/IGNITE-18754
=> IGNITE-18754 Use local timezone in ItJdbcResultSetSelfTest#testTimestamp

modules/runner/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java
https://issues.apache.org/jira/browse/IGNITE-18864
=> IGNITE-18864 Add a test for a leader change during full rebalance to a leader with enough log

modules/cli/src/test/java/org/apache/ignite/internal/cli/sql/SqlSchemaProviderTest.java
https://issues.apache.org/jira/browse/IGNITE-18957
=> IGNITE-18957 Disable SqlSchemaProviderTest

modules/runner/src/integrationTest/java/org/apache/ignite/internal/rest/RestNode.java
https://issues.apache.org/jira/browse/IGNITE-18938
=> IGNITE-18938 SSL integration tests fail on Windows

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/gc/MvGc.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/gc/MvGcTest.java
https://issues.apache.org/jira/browse/IGNITE-18968
=> IGNITE-18968 Possible race between updating a low watermark and processing the last batch for storage in a background GC

modules/core/src/test/java/org/apache/ignite/internal/testframework/WorkDirectoryExtensionTest.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/WorkDirectoryExtension.java
https://issues.apache.org/jira/browse/IGNITE-18970
=> IGNITE-18970 Allow WorkDirectoryExtension to preserve work directories of specific tests

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItRaftCommandLeftInLogUntilRestartTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItReadOnlyTransactionTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItRoReadsTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-18835
=> IGNITE-18835 Get rid of skipping safe time waiting on a primary node.

modules/cli/build.gradle, modules/cli/src/test/java/org/apache/ignite/internal/cli/sql/SqlSchemaProviderTest.java
https://issues.apache.org/jira/browse/IGNITE-18956
=> IGNITE-18956 Use awaitility in flaky test

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/Replica.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/listener/ReplicaListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/test/java/org/apache/ignite/internal/table/TxLocalTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
* Also fix some IDEA style warnings
https://issues.apache.org/jira/browse/IGNITE-18997
=> IGNITE-18997 Remove redundant future transformations from PartitionReplicaListener

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/ItClusterCommandTest.java
https://issues.apache.org/jira/browse/IGNITE-19023
=> IGNITE-19023 Fix stale TODO comment

modules/network/src/main/java/org/apache/ignite/internal/network/configuration/SslConfigurationValidatorImpl.java, modules/network/src/test/java/org/apache/ignite/internal/network/configuration/SslConfigurationValidatorImplTest.java
https://issues.apache.org/jira/browse/IGNITE-19037
=> IGNITE-19037 Improve SSL ciphers validation

modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/BaseIgniteAbstractTest.java, modules/core/src/testFixtures/resources/java.util.logging.properties
https://issues.apache.org/jira/browse/IGNITE-18553
Apply java logging properties for IDEA runner
=> IGNITE-18553: Apply logging properties for integration tests

gradle/libs.versions.toml
https://issues.apache.org/jira/browse/IGNITE-18648
=> IGNITE-18648 Update jacoco

modules/raft/src/main/java/org/apache/ignite/internal/raft/Loza.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
=> IGNITE-19079

modules/rest-api/openapi/openapi.yaml, modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/cluster/authentication/AuthenticationProviderConfigDto.java
https://issues.apache.org/jira/browse/IGNITE-19084
=> IGNITE-19084: Fix openapi schema of AuthenticationProviderConfigDto

modules/cli/src/main/java/org/apache/ignite/internal/cli/core/ApiClientFactory.java
https://issues.apache.org/jira/browse/IGNITE-19074
=> IGNITE-19074: Don't cache API clients in the CLI

modules/cli/src/main/java/org/apache/ignite/internal/cli/call/cluster/status/ClusterStatusCall.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/call/unit/DeployUnitCall.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/call/unit/ListUnitCall.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/call/unit/UndeployUnitCall.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/call/unit/UnitStatusCall.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/node/metric/NodeMetricDisableCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/node/metric/NodeMetricDisableReplCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/node/metric/NodeMetricEnableCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/node/metric/NodeMetricEnableReplCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/node/metric/NodeMetricListCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/node/metric/NodeMetricListReplCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/unit/UnitDeployCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/unit/UnitListCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/unit/UnitStatusCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/unit/UnitUndeployCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/exception/handler/ClusterNotInitializedExceptionHandler.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/ItNodeOnlyEndpointsFilterInitializedTest.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/ItNodeOnlyEndpointsFilterNotInitializedTest.java, modules/rest/src/main/java/org/apache/ignite/internal/rest/RestComponent.java, modules/rest/src/main/java/org/apache/ignite/internal/rest/authentication/NodeOnlyEndpointsFilter.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/rest/ItNotInitializedClusterRestTest.java
https://issues.apache.org/jira/browse/IGNITE-18943
=> IGNITE-18943 Disable the set of endpoints for non-initialized cluster

modules/core/src/test/java/org/apache/ignite/internal/util/worker/IgniteWorkerTest.java
https://issues.apache.org/jira/browse/IGNITE-19094
=> IGNITE-19094 Fix flaky IgniteWorkerTest#testUpdateHeartbeat

modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogServiceSelfTest.java
https://issues.apache.org/jira/browse/IGNITE-19118
=> IGNITE-19118 Fix build problems after merge

modules/network/src/main/java/org/apache/ignite/network/DefaultMessagingService.java
https://issues.apache.org/jira/browse/IGNITE-19121
=> IGNITE-19121 Future returned by a dropped message send is never completed

.asf.yaml
* Disallow force pushes.
* Require linear history (no merge commits).
* Require review approval.
More info: https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features
=> IGNITE-19122 Enable main branch protection

modules/table/src/integrationTest/java/org/apache/ignite/distributed/ReplicaUnavailableTest.java
https://issues.apache.org/jira/browse/IGNITE-18868
=> IGNITE-18868 Recursive update of pendingInvokes in ReplicaService

modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-18865
=> IGNITE-18865 Test storage recovery on rebalance abortion

.asf.yaml
https://issues.apache.org/jira/browse/IGNITE-19159
=> IGNITE-19159 Remove required_pull_request_reviews from git - .asf.yaml

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogServiceImpl.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/IgniteTestUtils.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerLogicalTopologyEventsTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerScaleUpTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerWatchListenerTest.java, modules/metastorage-api/src/main/java/org/apache/ignite/internal/metastorage/MetaStorageManager.java, modules/metastorage-api/src/main/java/org/apache/ignite/internal/metastorage/WatchEvent.java, modules/metastorage-api/src/main/java/org/apache/ignite/internal/metastorage/WatchListener.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageManagerImplTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageWatchTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/OnRevisionAppliedCallback.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/Watch.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/WatchProcessor.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AbstractKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/RocksDbKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/WatchProcessorTest.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/AssignmentsTracker.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseTracker.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/storage/ItDistributedConfigurationStorageTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/test/WatchListenerInhibitor.java, modules/runner/src/main/java/org/apache/ignite/internal/configuration/storage/DistributedConfigurationStorage.java, modules/runner/src/test/java/org/apache/ignite/internal/configuration/storage/DistributedConfigurationCatchUpTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-19129
=> IGNITE-19129 Remove parallel Watch processing

modules/configuration-api/src/main/java/org/apache/ignite/configuration/NamedListView.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/tree/NamedListNode.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/index/src/main/java/org/apache/ignite/internal/index/IndexManager.java, modules/metrics/src/main/java/org/apache/ignite/internal/metrics/MetricManager.java, modules/metrics/src/main/java/org/apache/ignite/internal/metrics/exporters/configuration/ExporterConfigurationSchema.java, modules/rest/src/main/java/org/apache/ignite/internal/rest/authentication/DelegatingAuthenticationProvider.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/configuration/ConfigurationToSchemaDescriptorConverter.java, modules/security/src/main/java/org/apache/ignite/internal/configuration/AuthenticationProvidersValidatorImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ddl/DdlCommandHandler.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/index/SortedIndexDescriptor.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-19180
=> IGNITE-19180 NamedListView made iterable

modules/table/src/test/java/org/apache/ignite/internal/table/distributed/AbstractMvStorageUpdateHandlerTest.java
https://issues.apache.org/jira/browse/IGNITE-19188
=> IGNITE-19188 Fix broken compilation in AbstractMvStorageUpdateHandlerTest

modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/DeployMessagingService.java, modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/DeploymentManagerImpl.java, modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/FileDeployerService.java, modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/IgniteDeployment.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/deployment/ItDeploymentUnitTest.java
https://issues.apache.org/jira/browse/IGNITE-19024
=> IGNITE-19024 Atomic redeploy

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImplTest.java
https://issues.apache.org/jira/browse/IGNITE-19200
=> IGNITE-19200 DistributedQueryManager#close() fails to complete cancellation future

modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/cluster/status/ClusterStatusCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/sql/SqlSchemaLoader.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/UrlOptionsNegativeTest.java
https://issues.apache.org/jira/browse/IGNITE-19012
=> IGNITE-19012 Close TODOs

modules/distribution-zones/build.gradle, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneConfigurationParameters.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZonesUtil.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/configuration/DistributionZoneConfigurationSchema.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/configuration/FilterValidator.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/configuration/ValidFilter.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneConfigurationParametersTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-18952
=> IGNITE-18952 Add the filter as a configuration parameter of a Distribution zone

modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/ItClusterManagerTest.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/raft/CmgRaftGroupListener.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/topology/LogicalTopologyImpl.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/topology/api/LogicalNode.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/ActionRequest.java
https://issues.apache.org/jira/browse/IGNITE-19179
=> IGNITE-19179 Make logical topology rejoins idempotent

modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/messages/MessageImplGenerator.java, modules/network/src/test/java/org/apache/ignite/internal/network/processor/TransferableObjectProcessorTest.java, modules/network/src/test/resources/org/apache/ignite/internal/network/processor/MessageWithMarshallableNetworkMessageField.java
https://issues.apache.org/jira/browse/IGNITE-19220
=> IGNITE-19220 Prohibit marking NetworkMessage with Marshallable

docs/_docs/installation/installing-using-docker.adoc, modules/runner/src/main/java/org/apache/ignite/app/IgniteRunner.java, packaging/docker/cluster.conf, packaging/docker/docker-compose.yml
https://issues.apache.org/jira/browse/IGNITE-19153
=> IGNITE-19153 Fix docker compose

modules/core/src/main/java/org/apache/ignite/lang/ErrorGroups.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/cluster/ItClusterManagementControllerTest.java, modules/rest/src/main/java/org/apache/ignite/internal/rest/authentication/AuthenticationProviderFactory.java, modules/rest/src/main/java/org/apache/ignite/internal/rest/authentication/DelegatingAuthenticationProvider.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/security/src/main/java/org/apache/ignite/internal/security/authentication/AuthenticationManager.java, modules/security/src/main/java/org/apache/ignite/internal/security/authentication/AuthenticationManagerImpl.java, modules/security/src/main/java/org/apache/ignite/internal/security/authentication/AuthenticationRequest.java, modules/security/src/main/java/org/apache/ignite/internal/security/authentication/Authenticator.java, modules/security/src/main/java/org/apache/ignite/internal/security/authentication/AuthenticatorFactory.java, modules/security/src/main/java/org/apache/ignite/internal/security/authentication/BasicAuthenticator.java, modules/security/src/main/java/org/apache/ignite/internal/security/authentication/UserDetails.java, modules/security/src/main/java/org/apache/ignite/internal/security/authentication/UsernamePasswordRequest.java, modules/security/src/main/java/org/apache/ignite/internal/security/exception/AuthenticationException.java, modules/security/src/test/java/org/apache/ignite/internal/security/authentication/AuthenticationManagerImplTest.java, modules/security/src/test/java/org/apache/ignite/internal/security/authentication/StubAuthenticationViewEvent.java
https://issues.apache.org/jira/browse/IGNITE-19197
=> IGNITE-19197 Refactor authentication

buildscripts/java-core.gradle, buildscripts/java-integration-test.gradle
https://issues.apache.org/jira/browse/IGNITE-18253
=> IGNITE-18253 Jacoco report for integration tests

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/Checkpointer.java
https://issues.apache.org/jira/browse/IGNITE-19263
=> IGNITE-19263 Complete future at Checkpointer#syncUpdatedPageStores when Checkpointer shuts down

modules/cli/src/integrationTest/java/org/apache/ignite/internal/rest/ItGeneratedRestClientTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/ssl/ItSslTest.java
ItSslTest and ItGeneratedRestClientTest are optimized by sharing the cluster instance across common tests.
https://issues.apache.org/jira/browse/IGNITE-19191
=> IGNITE-19191 Optimize integration tests

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/README.md
https://issues.apache.org/jira/browse/IGNITE-18454
=> IGNITE-18454 Explain treading model in corresponding README.md file for TableManager

modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/Options.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/SqlCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/SqlReplCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/config/ConfigConstants.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/config/ConfigDefaultValueProvider.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/SessionDefaultValueProvider.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/SessionInfo.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/core/repl/SessionDefaultValueProviderTest.java
https://issues.apache.org/jira/browse/IGNITE-19283
=> IGNITE-19283 JDBC URL is not taken from the session

modules/platforms/cpp/ignite/client/CMakeLists.txt, modules/platforms/cpp/ignite/client/detail/type_mapping_utils.h, modules/platforms/cpp/ignite/client/table/key_value_view.h, modules/platforms/cpp/ignite/client/table/record_view.h, modules/platforms/cpp/ignite/client/table/table.h, modules/platforms/cpp/tests/client-test/CMakeLists.txt, modules/platforms/cpp/tests/client-test/all_fields_type.h, modules/platforms/cpp/tests/client-test/key_value_binary_view_test.cpp, modules/platforms/cpp/tests/client-test/key_value_view_test.cpp, modules/platforms/cpp/tests/client-test/record_view_test.cpp
- Implemented key_value_view for user objects;
- Added tests.
=> IGNITE-18255 Add key_value_view in C++

modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/IgniteTestUtils.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCorrelatesTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExchangeServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/AsyncRootNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/Inbox.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/Outbox.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/ScanNode.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/ExchangeExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/DmlPlannerTest.java
https://issues.apache.org/jira/browse/IGNITE-19018
=> IGNITE-19018: Sql. Investigate AssertionError in ScanNode.

modules/cli/src/integrationTest/java/org/apache/ignite/internal/rest/ItGeneratedRestClientTest.java
https://issues.apache.org/jira/browse/IGNITE-19235
=> IGNITE-19235 Enable ItGeneratedRestClientTest.initCluster()

modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerScaleUpTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/LowWatermark.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/LowWatermarkTest.java
https://issues.apache.org/jira/browse/IGNITE-19327
=> IGNITE-19327 Fix a bug on scheduling a new low watermark update

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItBuildIndexTest.java
https://issues.apache.org/jira/browse/IGNITE-19086
=> IGNITE-19086 Fix NullPointerException on building indexes if the number of replicas is more than one

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDmlTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItHashSpoolTest.java
https://issues.apache.org/jira/browse/IGNITE-16679
=> IGNITE-16679 Redesing local events in order to them contain a synchronous and asynchronous parts (unmuted tests)

modules/cli/src/main/java/org/apache/ignite/internal/cli/core/flow/question/JlineQuestionWriterReader.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/executor/ReplExecutor.java
https://issues.apache.org/jira/browse/IGNITE-19334
=> IGNITE-19334 Disable autocomplete for questions in REPL again

modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/cliconfig/ConfigManagerTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/storage/ItRebalanceDistributedTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/TableScanNodeExecutionTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTablePersistenceTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNode.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItColocationTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/TxLocalTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/command/PartitionRaftCommandsSerializationTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/PartitionCommandListenerTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerIndexLockingTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/TransactionIds.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/NodeIdSupplier.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TransactionIdGenerator.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/AbstractLockManagerTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/AbstractLockingTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/TransactionIdsTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerTest.java, modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/test/TestTransactionIds.java
https://issues.apache.org/jira/browse/IGNITE-19225
=> IGNITE-19225 Generate beginTs on a coordinator and send it to all tx participants

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageServiceImpl.java, modules/network/src/testFixtures/java/org/apache/ignite/utils/ClusterServiceTestUtils.java, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/MultiActorPlacementDriverTest.java, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/PlacementDriverManagerTest.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/PlacementDriverManager.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/TopologyTracker.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
https://issues.apache.org/jira/browse/IGNITE-18961
=> IGNITE-18961 Implement lease prolongation on placement driver side

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/cluster/init/ItClusterInitTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/unit/ItDeploymentUnitTest.java
https://issues.apache.org/jira/browse/IGNITE-19357
=> IGNITE-19357 Disable flaky tests

modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/snapshot/SnapshotExecutorImpl.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
https://issues.apache.org/jira/browse/IGNITE-19362
=> IGNITE-19362 Fix deadlock while restarting with existing raft snapshot and scheduled index rebuild

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTableScanTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/SortedIndexLocker.java
https://issues.apache.org/jira/browse/IGNITE-19302
=> IGNITE-19302 Phantom reads fixed

modules/runner/src/integrationTest/java/org/apache/ignite/internal/compute/ItLogicalTopologyTest.java
https://issues.apache.org/jira/browse/IGNITE-18711
=> IGNITE-18711 Leave logical topology gracefully when stopping Ignite node

modules/platforms/cpp/tests/client-test/ignite_runner_suite.h, modules/platforms/cpp/tests/client-test/sql_test.cpp
Added tests with UUIDs for C++ SQL API.
=> IGNITE-18917 SQL tests with UUID

modules/placement-driver-api/src/main/java/org/apache/ignite/internal/placementdriver/message/PlacementDriverActorMessage.java, modules/placement-driver-api/src/main/java/org/apache/ignite/internal/placementdriver/message/PlacementDriverMessage.java, modules/placement-driver-api/src/main/java/org/apache/ignite/internal/placementdriver/message/StopLeaseProlongationMessage.java, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/MultiActorPlacementDriverTest.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/Lease.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java
https://issues.apache.org/jira/browse/IGNITE-19390
=> IGNITE-19390 Handling lease deny message in placement driver side

modules/client-handler/src/main/java/org/apache/ignite/client/handler/JdbcQueryEventHandlerImpl.java, modules/core/src/main/java/org/apache/ignite/lang/RemoteException.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlAsynchronousApiTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDmlTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/AsyncSqlCursorImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExchangeServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/message/ErrorMessage.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/metadata/RemoteFragmentExecutionException.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImplTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/MockedStructuresTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-19272
=> IGNITE-19272 Sql. Log query exception on remote node and pass traceId back.

examples/src/integrationTest/java/org/apache/ignite/example/storage/ItPageMemoryStorageExampleTest.java
https://issues.apache.org/jira/browse/IGNITE-19427
=> IGNITE-19427 ItPageMemoryStorageExampleTest.testPersistentExample() is muted.

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java, modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/impl/StandaloneMetaStorageManager.java, modules/raft-api/src/main/java/org/apache/ignite/internal/raft/RaftManager.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/Loza.java
https://issues.apache.org/jira/browse/IGNITE-19429
=> IGNITE-19429 Forgot to wait for the RaftServer#raftNodeReadyFuture when start the raft node metastorage

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/CliIntegrationTestBase.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/call/CallInitializedIntegrationTestBase.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/configuration/ClusterManagementConfigurationSchema.java, modules/cluster-management/src/testFixtures/java/org/apache/ignite/internal/cluster/management/BaseItClusterManagementTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesTest.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/cluster/RestTestBase.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/ClusterPerTestIntegrationTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/compute/ItLogicalTopologyTest.java
https://issues.apache.org/jira/browse/IGNITE-19420
=> IGNITE-19420 Remove a node from Logical Topology  as soon as it leaves Physical Topology

packaging/build.gradle, packaging/cli/build.gradle, packaging/db/build.gradle
https://issues.apache.org/jira/browse/IGNITE-19418
=> IGNITE-19418 Fix gradle build with JDK 17

modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerConfigurationChangesTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerLogicalTopologyEventsTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerScaleUpTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerWatchListenerTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageServiceTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/KeyValueStorage.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksStorageUtils.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/StorageColumnFamilyType.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/raft/MetaStorageWriteHandler.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/impl/MetaStorageRangeTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AbstractCompactionKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AbstractKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/BaseKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/BasicOperationsKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/CompactionKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/RocksDbCompactionKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/RocksDbKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryCompactionKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorageTest.java, modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java, modules/runner/src/test/java/org/apache/ignite/internal/configuration/storage/DistributedConfigurationStorageTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerDistributionZonesTest.java, modules/table/src/test/java/org/apache/ignite/internal/utils/RebalanceUtilUpdateAssignmentsTest.java
https://issues.apache.org/jira/browse/IGNITE-14734
=> IGNITE-14734 Implement time-based compaction for meta storage

modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/io/HashIndexTreeIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/meta/io/IndexMetaInnerIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/meta/io/IndexMetaIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/meta/io/IndexMetaLeafIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/io/SortedIndexTreeIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/VersionChain.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/gc/io/GcIo.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/io/VersionChainIo.java
https://issues.apache.org/jira/browse/IGNITE-19439
=> IGNITE-19439 Fixed bug in VersionChainIo that lead to tree corruption

modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerConfigurationChangesTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerScaleUpTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerWatchListenerTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/util/DistributionZonesTestUtil.java
https://issues.apache.org/jira/browse/IGNITE-19342
=> IGNITE-19342 Some tests from DistributionZoneManagerScaleUpTest were fixed and enabled.

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerScaleUpTest.java
https://issues.apache.org/jira/browse/IGNITE-19255
=> IGNITE-19255 Some tests from DistributionZoneManagerScaleUpTest were fixed and enabled.

modules/index/src/main/java/org/apache/ignite/internal/index/IndexBuilder.java, modules/index/src/main/java/org/apache/ignite/internal/index/IndexManager.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ClusterPerClassIntegrationTest.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/MvTableStorage.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestMvTableStorage.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractHashIndexStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractSortedIndexStorageTest.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/AbstractPageMemoryTableStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryMvTableStorageTest.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbTableStorage.java, modules/table/src/main/java/org/apache/ignite/internal/table/TableImpl.java
https://issues.apache.org/jira/browse/IGNITE-19509
=> IGNITE-19509 Get rid of reading configuration when calling methods MvTableStorage#getOrCreate*Index

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/StorageUpdateHandler.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/PartitionAccessImpl.java
https://issues.apache.org/jira/browse/IGNITE-18619
=> IGNITE-18619 Need to properly wait for indexes to be created before rebalancing

modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/deployment/DeploymentManagementControllerTest.java
https://issues.apache.org/jira/browse/IGNITE-19525
=> IGNITE-19525 Disable flaky test

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/topology/api/LogicalNode.java, modules/core/src/main/java/org/apache/ignite/internal/hlc/HybridTimestamp.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/Lease.java
https://issues.apache.org/jira/browse/IGNITE-19183
=> IGNITE-19183 Fixed LogicalNode.toString method

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngine.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngineTest.java, modules/metastorage-api/src/main/java/org/apache/ignite/internal/metastorage/MetaStorageManager.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/distribution/zones/ItDistributionZonesFilterTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ddl/DdlCommandHandler.java
https://issues.apache.org/jira/browse/IGNITE-19443
=> IGNITE-19443 Empty data nodes are not propagated to pending assignments after filtering

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/message/TimestampAware.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ReplicaUnavailableTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/SortedIndexLocker.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java
https://issues.apache.org/jira/browse/IGNITE-19381
=> IGNITE-19381 TimestampAware messages sometimes lacks timestamps

modules/raft-api/src/main/java/org/apache/ignite/internal/raft/configuration/RaftConfigurationSchema.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/Loza.java
https://issues.apache.org/jira/browse/IGNITE-19472
=> IGNITE-19472 Make fsync flag configurable in RAFT

modules/table/src/testFixtures/java/org/apache/ignite/internal/table/TxAbstractTest.java
https://issues.apache.org/jira/browse/IGNITE-19523
=> IGNITE-19523 Unmuted TxAbstractTest.testRollbackUpgradedLock

modules/core/src/main/java/org/apache/ignite/internal/hlc/HybridTimestamp.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesAbstractTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesRocksDbTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageMultipleNodesSimpleStorageTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageSafeTimePropagationAbstractTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageSafeTimePropagationRocksDbTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageSafeTimePropagationSimpleStorageTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/impl/MetaStorageManagerImpl.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/OnRevisionAppliedCallback.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/WatchProcessor.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/StorageColumnFamilyType.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/raft/MetaStorageWriteHandler.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/BasicOperationsKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/RocksDbCompactionKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/RocksDbKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryCompactionKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/WatchProcessorTest.java, modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/AbstractKeyValueStorageTest.java, modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/SimpleInMemoryKeyValueStorage.java
https://issues.apache.org/jira/browse/IGNITE-19532
=> IGNITE-19532 Happens-before for safe time propagation

modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/Options.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/node/NodeUrlMixin.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/node/NodeUrlProfileMixin.java
https://issues.apache.org/jira/browse/IGNITE-19572
=> IGNITE-19572 Non-REPL node commands show node name option

modules/raft/src/main/java/org/apache/ignite/internal/raft/RaftGroupServiceImpl.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
https://issues.apache.org/jira/browse/IGNITE-19398
=> IGNITE-19398 ItIgniteNodeRestartTest optimized.

gradle/libs.versions.toml
https://issues.apache.org/jira/browse/IGNITE-19386
=> IGNITE-19386 Switch to standard scalecube-cluster

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/StorageUpdateHandler.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexUpdateHandler.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-19563
=> IGNITE-19563 Fixed deadlock in partition commands handler

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogServiceImpl.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AlterTableAddColumnParams.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AlterTableDropColumnParams.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CatalogUtils.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/ColumnParams.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/HashIndexDescriptor.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/IndexDescriptor.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/SortedIndexDescriptor.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/TableDescriptor.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/AddColumnEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/CatalogEvent.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/DropColumnEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/DropColumnsEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/NewColumnsEntry.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogServiceSelfTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItSchemaChangeTableViewTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlAsynchronousApiTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlSynchronousApiTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItMixedQueriesTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/internal/InternalSchemaTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ddl/DdlCommandHandlerWrapper.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ddl/DdlToCatalogCommandConverter.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/schema/FullTableSchemaTest.java
https://issues.apache.org/jira/browse/IGNITE-19592
=> IGNITE-19592 Implement ADD/DROP COLUMN DDL commands with using Catalog

modules/api/src/main/java/org/apache/ignite/lang/IgniteCheckedException.java, modules/api/src/main/java/org/apache/ignite/lang/IgniteException.java, modules/api/src/test/java/org/apache/ignite/lang/IgniteExceptionTest.java, modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/ItClientHandlerMetricsTest.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/core/src/main/java/org/apache/ignite/lang/ErrorGroup.java, modules/core/src/main/java/org/apache/ignite/lang/IgniteInternalCheckedException.java, modules/core/src/main/java/org/apache/ignite/lang/IgniteInternalException.java, modules/core/src/test/java/org/apache/ignite/lang/ErrorGroupTest.java, modules/platforms/cpp/tests/client-test/compute_test.cpp, modules/platforms/dotnet/Apache.Ignite.Tests/Sql/SqlTests.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Tables.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sqllogic/Statement.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/message/ErrorMessage.java
https://issues.apache.org/jira/browse/IGNITE-19534
=> IGNITE-19534 Fix error code duplication in the error message

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItReadOnlyTransactionTest.java
https://issues.apache.org/jira/browse/IGNITE-19627
=> IGNITE-19627 fix ItReadOnlyTransactionTest

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
https://issues.apache.org/jira/browse/IGNITE-19408
=> IGNITE-19408 Removed unnecessary TODO

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/schema/NonHistoricSchemas.java
https://issues.apache.org/jira/browse/IGNITE-19630
=> IGNITE-19630 Convert default value from Column to TableColumnDescriptor

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStoreManager.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStoreManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-19596
=> IGNITE-19596 Partition creation fails with NSFE

.idea/inspectionProfiles/Project_Default.xml, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/messages/MarshallableTypesBlackList.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/messages/MessageImplGenerator.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/serialization/BaseMethodNameResolver.java, modules/network-api/src/main/java/org/apache/ignite/network/serialization/MessageReader.java, modules/network-api/src/main/java/org/apache/ignite/network/serialization/MessageWriter.java, modules/network/src/main/java/org/apache/ignite/internal/network/direct/DirectMessageReader.java, modules/network/src/main/java/org/apache/ignite/internal/network/direct/DirectMessageWriter.java, modules/network/src/main/java/org/apache/ignite/internal/network/direct/stream/DirectByteBufferStream.java, modules/network/src/main/java/org/apache/ignite/internal/network/direct/stream/DirectByteBufferStreamImplV1.java, modules/network/src/test/java/org/apache/ignite/internal/network/AllTypesMessageGenerator.java, modules/network/src/test/java/org/apache/ignite/internal/network/processor/MarshallableBlacklistTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/processor/TransferableObjectProcessorTest.java, modules/network/src/testFixtures/java/org/apache/ignite/internal/network/messages/AllTypesMessage.java, modules/network/src/testFixtures/java/org/apache/ignite/internal/network/serialization/SimpleSerializableObject.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/entity/LocalStorageOutter.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replication/request/ReadWriteReplicaRequest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replication/request/ScanRetrieveBatchReplicaRequest.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/message/TxCleanupReplicaRequest.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/message/TxFinishReplicaRequest.java
https://issues.apache.org/jira/browse/IGNITE-19452
=> IGNITE-19452 Forbid placing Marshallable on some standard types

buildscripts/java-core.gradle, gradle/libs.versions.toml
https://issues.apache.org/jira/browse/IGNITE-19634
=> IGNITE-19634 Bump PMD version

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AbstractTableCommandParams.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogServiceSelfTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ddl/DdlToCatalogCommandConverter.java
https://issues.apache.org/jira/browse/IGNITE-19611
=> IGNITE-19611 Drop unused ifExists flag from Catalog action params

modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageServiceTest.java
https://issues.apache.org/jira/browse/IGNITE-19658
=> IGNITE-19658 Fix NPE in ItMetaStorageServiceTest

modules/storage-api/src/main/java/org/apache/ignite/internal/storage/StorageException.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/StorageRebalanceException.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/util/MvPartitionStorages.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/util/StorageOperation.java, modules/storage-api/src/test/java/org/apache/ignite/internal/storage/util/MvPartitionStoragesTest.java
https://issues.apache.org/jira/browse/IGNITE-19648
=> IGNITE-19648 Failed to cancel rebalance

modules/placement-driver-api/src/main/java/org/apache/ignite/internal/placementdriver/message/LeaseGrantedMessageResponse.java, modules/placement-driver-api/src/main/java/org/apache/ignite/internal/placementdriver/message/PlacementDriverActorMessage.java, modules/placement-driver-api/src/main/java/org/apache/ignite/internal/placementdriver/message/PlacementDriverGroupMessage.java, modules/placement-driver-api/src/main/java/org/apache/ignite/internal/placementdriver/message/PlacementDriverMessage.java, modules/placement-driver-api/src/main/java/org/apache/ignite/internal/placementdriver/message/PlacementDriverReplicaMessage.java, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/MultiActorPlacementDriverTest.java, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/PlacementDriverManagerTest.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/message/ReplicaRequest.java, modules/replicator/src/test/java/org/apache/ignite/internal/replicator/PlacementDriverReplicaSideTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ReplicaUnavailableTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/snapshot/message/SnapshotRequestMessage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replication/request/ReadWriteMultiRowReplicaRequest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replication/request/ReadWriteReplicaRequest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replication/request/ReadWriteSingleRowReplicaRequest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/outgoing/OutgoingSnapshotMvDataStreamingTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/snapshot/outgoing/OutgoingSnapshotTxDataStreamingTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java
https://issues.apache.org/jira/browse/IGNITE-19457
=> IGNITE-19457 Review nullability of network messages' fields

modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageServiceTest.java
https://issues.apache.org/jira/browse/IGNITE-19678
=> IGNITE-19678 Fix remaining NPEs in ItMetaStorageServiceTest

modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/BasicOperationsKeyValueStorageTest.java, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/TestRocksDbKeyValueStorageTest.java, modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/server/TestRocksDbKeyValueStorage.java
https://issues.apache.org/jira/browse/IGNITE-19674
=> IGNITE-19674 introduce TestRocksDbKeyValueStorage

modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/index/AbstractIndexStorageTest.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/AbstractPageMemoryIndexStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/common/IndexRowKey.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/HashIndexRowKey.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/hash/PageMemoryHashIndexStorage.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/index/sorted/PageMemorySortedIndexStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/AbstractRocksDbIndexStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbHashIndexStorage.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/index/RocksDbSortedIndexStorage.java
https://issues.apache.org/jira/browse/IGNITE-19422
=> IGNITE-19422 Fixed "get" method in index storages.

modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/TypeUtils.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/messages/MarshallableTypesBlackList.java, modules/network-annotation-processor/src/main/java/org/apache/ignite/internal/network/processor/messages/MessageImplGenerator.java, modules/network-annotation-processor/src/main/resources/marshallable.blacklist, modules/network/src/test/java/org/apache/ignite/internal/network/processor/MarshallableBlacklistTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/processor/TransferableObjectProcessorTest.java, modules/network/src/test/resources/marshallable.blacklist, modules/placement-driver-api/src/main/java/org/apache/ignite/internal/placementdriver/message/LeaseGrantedMessage.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/negotiation/LeaseNegotiator.java, modules/replicator/src/test/java/org/apache/ignite/internal/replicator/PlacementDriverReplicaSideTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/IgniteTableImpl.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ReplicaUnavailableTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableMessageGroup.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replication/request/BinaryTupleMessage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replication/request/MultipleRowReplicaRequest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replication/request/ReadOnlyReplicaRequest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replication/request/ScanRetrieveBatchReplicaRequest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replication/request/SingleRowReplicaRequest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replication/request/SwapRowReplicaRequest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerIndexLockingTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java
https://issues.apache.org/jira/browse/IGNITE-19451
=> IGNITE-19451 Prohibit some types from being Marshallable

modules/network/src/main/java/org/apache/ignite/network/scalecube/ScaleCubeTopologyService.java, modules/network/src/test/java/org/apache/ignite/network/scalecube/ScaleCubeTopologyServiceTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/Cluster.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/ClusterPerTestIntegrationTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/compute/ItLogicalTopologyTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/ssl/ItSslTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/start/ItStartTest.java
https://issues.apache.org/jira/browse/IGNITE-19685
=> IGNITE-19685 Treat Scalecube's LEAVING event as 'node left' in the physical topology

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaService.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ReplicaUnavailableTest.java
https://issues.apache.org/jira/browse/IGNITE-19136
=> IGNITE-19136 Handling timeout on waiting for replica readiness

modules/network/src/main/java/org/apache/ignite/network/DefaultMessagingService.java, modules/network/src/main/java/org/apache/ignite/network/scalecube/ScaleCubeClusterServiceFactory.java, modules/network/src/test/java/org/apache/ignite/network/DefaultMessagingServiceTest.java
https://issues.apache.org/jira/browse/IGNITE-19698
=> IGNITE-19698 Add node name to threads in DefaultMessagingService

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/call/unit/DeployUndeployTestSupport.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/call/AsyncCallExecutionPipeline.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/call/ProgressBarTracker.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/call/ProgressTracker.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/commands/UrlOptionsNegativeTest.java
https://issues.apache.org/jira/browse/IGNITE-19090
Do not create progress bar until first progress message is received.
=> IGNITE-19090 Don't show progress bar in case of an error

modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerScaleUpTest.java
https://issues.apache.org/jira/browse/IGNITE-19707
=> IGNITE-19707 Fix AssertionError in DistributionZoneManagerScaleUpTest

modules/jdbc/build.gradle
https://issues.apache.org/jira/browse/IGNITE-19552
=> IGNITE-19552 Build JDBC module jar

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
https://issues.apache.org/jira/browse/IGNITE-19079
=> IGNITE-19079 Enabled tests in ItIgniteNodeRestartTest: testTwoNodesRestartDirect and testTwoNodesRestartReverse

modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerWatchListenerTest.java
https://issues.apache.org/jira/browse/IGNITE-19714
=> IGNITE-19714 Fix AssertionError in DistributionZoneManagerWatchListenerTest

modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/configuration/NodeAttributeConfigurationSchema.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/topology/api/LogicalNode.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/configuration/DistributionZoneConfigurationSchema.java, modules/distribution-zones/tech-notes/filters.md
https://issues.apache.org/jira/browse/IGNITE-19184
=> IGNITE-19184 Added javadocs and md file to describe node attributes and distribution zone filters

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/core/repl/executor/ItIgnitePicocliCommandsTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/storage/ItRebalanceDistributedTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/configuration/GcConfigurationSchema.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/configuration/SchemaDistributedConfigurationModule.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/configuration/storage/DataStorageConfigurationSchema.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/MockedStructuresTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTablePersistenceTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNode.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/StorageUpdateHandler.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/gc/MvGc.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/AbstractMvStorageUpdateHandlerTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/IndexBaseTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/StorageUpdateHandlerTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/gc/MvGcTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/PartitionCommandListenerTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerIndexLockingTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-19718
=> IGNITE-19718 Move DataStorageConfigurationSchema#gcOnUpdateBatchSize to another place

build.gradle
https://issues.apache.org/jira/browse/IGNITE-19761
=> IGNITE-19761 Remove a stale TODO

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/compaction/Compactor.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/store/AbstractFilePageStoreIo.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/store/AbstractFilePageStoreIoTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/store/DeltaFilePageStoreIoTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStoreIoTest.java
https://issues.apache.org/jira/browse/IGNITE-19749
=> IGNITE-19749 AccessDeniedException on Windows

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-19747
=> IGNITE-19747 Fixed flaky ItRebalanceDistributedTest.testOnLeaderElectedRebalanceRestart

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItTableScanTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/SortedIndexLocker.java
https://issues.apache.org/jira/browse/IGNITE-19731
=> IGNITE-19731 Fixed ItTableScanTest different test failed

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-19805
=> IGNITE-19805 Fixed intermittent AssertionError in logs, by providing a correct causality bethween versioned values in TableManager.

modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/DeploymentManagerImpl.java, modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/FileDeployerService.java
https://issues.apache.org/jira/browse/IGNITE-19764
=> IGNITE-19764 FileDeployerService does not stop underlying thread pool

modules/api/src/main/java/org/apache/ignite/sql/SqlException.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogService.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogServiceImpl.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AbstractIndexCommandParams.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CatalogUtils.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateHashIndexParams.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateSortedIndexParams.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/AlterColumnEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/DropColumnsEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/DropIndexEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/DropTableEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/NewColumnsEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/NewIndexEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/NewTableEntry.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogServiceSelfTest.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/matchers/CompletableFutureMatcher.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/CatalogSqlSchemaManager.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/schema/CatalogSqlSchemaManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-19799
=> IGNITE-19799 Refactoring classes associated with the catalog

modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/raft/ItCmgRaftServiceTest.java, modules/cluster-management/src/main/java/org/apache/ignite/internal/cluster/management/ClusterManagementGroupManager.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageServiceTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/OnRevisionAppliedCallback.java, modules/metastorage/src/testFixtures/java/org/apache/ignite/internal/metastorage/impl/StandaloneMetaStorageManager.java, modules/raft-api/src/main/java/org/apache/ignite/internal/raft/RaftManager.java, modules/raft/src/integrationTest/java/org/apache/ignite/internal/raft/ItLearnersTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/internal/raft/ItLozaTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/internal/raft/ItRaftGroupServiceTest.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/Loza.java, modules/raft/src/test/java/org/apache/ignite/internal/raft/LozaTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/MockedStructuresTest.java
https://issues.apache.org/jira/browse/IGNITE-19831
=> IGNITE-19831 Rename RaftManager methods to better reflect their behavior

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogService.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogServiceImpl.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CatalogUtils.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/AddColumnEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/AlterColumnEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/AlterZoneEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/CatalogEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/CreateIndexEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/CreateTableEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/CreateZoneEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/DropColumnEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/DropIndexEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/DropTableEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/DropZoneEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/AlterColumnEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/AlterZoneEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/DropColumnsEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/DropIndexEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/DropTableEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/DropZoneEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/Fireable.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/NewColumnsEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/NewIndexEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/NewTableEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/NewZoneEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/UpdateLog.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/UpdateLogImpl.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogServiceSelfTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/storage/UpdateLogImplTest.java
https://issues.apache.org/jira/browse/IGNITE-19798
=> IGNITE-19798 Add functionality to the catalog to switch the IndexManager to catalog events

modules/platforms/cpp/ignite/client/CMakeLists.txt, modules/platforms/cpp/ignite/client/compute/compute.cpp, modules/platforms/cpp/ignite/client/compute/compute.h, modules/platforms/cpp/ignite/client/compute/deployment_unit.h, modules/platforms/cpp/ignite/client/detail/compute/compute_impl.cpp, modules/platforms/cpp/ignite/client/detail/compute/compute_impl.h, modules/platforms/cpp/ignite/protocol/writer.h, modules/platforms/cpp/tests/client-test/basic_authenticator_test.cpp, modules/platforms/cpp/tests/client-test/compute_test.cpp
- Changed Compute API in C++ client;
- Fixed existing tests;
- Added new tests.
=> IGNITE-19625 C++ Compute API supports deployment units 

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ReplicaUnavailableTest.java
https://issues.apache.org/jira/browse/IGNITE-19724
=> IGNITE-19724 Removed redundant joins

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngine.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtil.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtilUpdateAssignmentsTest.java
https://issues.apache.org/jira/browse/IGNITE-19843
=> IGNITE-19843 Unify code that triggers rebalance

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-19885
=> IGNITE-19885 Simplify handleChangeStableAssignmentEvent in TableManager

modules/rest/build.gradle
https://issues.apache.org/jira/browse/IGNITE-19891
=> IGNITE-19891 Fix Swagger-related compilation warnings

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-19906
=> IGNITE-19906 Check that table exists when going to destroy partition storage

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientTransactionsTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItCommonApiTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlAsynchronousApiTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlSynchronousApiTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java, modules/table/src/test/java/org/apache/ignite/internal/table/RepeatedFinishReadWriteTransactionTest.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/TxAbstractTest.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/TxManager.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/TxState.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadOnlyTransactionImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadWriteTransactionImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-19663
1. TestOnly IgniteImpl#txManager method added.
2. Assertion added in TxManagerImpl#changeState in order to check that changeState was successfully computed.
3. TestOnly TxManager#pending added.
4. New TxState#PENDING added
=> IGNITE-19663 Add possibility to check transaction state

modules/api/src/main/java/org/apache/ignite/lang/IgniteCheckedException.java, modules/api/src/main/java/org/apache/ignite/lang/IgniteException.java, modules/api/src/main/java/org/apache/ignite/lang/IgniteExceptionUtils.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/core/src/main/java/org/apache/ignite/lang/IgniteInternalCheckedException.java, modules/core/src/main/java/org/apache/ignite/lang/IgniteInternalException.java, modules/core/src/main/java/org/apache/ignite/lang/TraceableException.java
https://issues.apache.org/jira/browse/IGNITE-19864
=> IGNITE-19864 Introduce TraceableException

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZonesUtil.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngine.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerAlterFilterTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerFilterTest.java, modules/distribution-zones/src/testFixtures/java/org/apache/ignite/internal/distributionzones/DistributionZonesTestUtil.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/distribution/zones/ItIgniteDistributionZoneManagerNodeRestartTest.java
https://issues.apache.org/jira/browse/IGNITE-19581
=> IGNITE-19581 add restoring of zones state after restart taking into account zone's filter updates

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-19932
=> IGNITE-19932 Simplify handleChangePendingAssignmentEvent in TableManager

modules/platforms/cpp/ignite/client/detail/utils.cpp, modules/platforms/cpp/ignite/common/big_decimal.cpp, modules/platforms/cpp/ignite/common/big_decimal.h, modules/platforms/cpp/ignite/common/big_integer.h, modules/platforms/cpp/ignite/odbc/CMakeLists.txt, modules/platforms/cpp/ignite/odbc/app/application_data_buffer.cpp, modules/platforms/cpp/ignite/odbc/app/application_data_buffer.h, modules/platforms/cpp/ignite/odbc/app/application_data_buffer_test.cpp, modules/platforms/cpp/ignite/odbc/app/parameter.cpp, modules/platforms/cpp/ignite/odbc/app/parameter.h, modules/platforms/cpp/ignite/odbc/app/parameter_set.cpp, modules/platforms/cpp/ignite/odbc/app/parameter_set.h, modules/platforms/cpp/ignite/odbc/query/data_query.cpp, modules/platforms/cpp/ignite/protocol/utils.h, modules/platforms/cpp/ignite/tuple/tuple_test.cpp, modules/platforms/cpp/tests/odbc-test/CMakeLists.txt, modules/platforms/cpp/tests/odbc-test/api_robustness_test.cpp, modules/platforms/cpp/tests/odbc-test/error_test.cpp, modules/platforms/cpp/tests/odbc-test/odbc_connection.h, modules/platforms/cpp/tests/odbc-test/odbc_test_utils.h
- Implemented data buffers;
- Added tests;
- Unmuted related old tests.
=> IGNITE-19205 ODBC data buffers

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogServiceImpl.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogServiceSelfTest.java
https://issues.apache.org/jira/browse/IGNITE-19924
=> IGNITE-19924 Test shouldn't guess id of newly created catalog object

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogServiceImpl.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogServiceSelfTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItCreateTableDdlTest.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/configuration/TableValidatorImpl.java
https://issues.apache.org/jira/browse/IGNITE-19927
=> IGNITE-19927 Improve test coverage for CREATE TABLE

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/ClockWaiter.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/ClockWaiterTest.java, modules/core/src/main/java/org/apache/ignite/internal/hlc/ClockUpdateListener.java, modules/core/src/main/java/org/apache/ignite/internal/hlc/HybridClockImpl.java, modules/core/src/test/java/org/apache/ignite/internal/HybridClockTest.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/TestHybridClock.java
https://issues.apache.org/jira/browse/IGNITE-19963
=> IGNITE-19963 Move completion of ClockWaiter futures to a special thread pool

modules/core/src/main/java/org/apache/ignite/internal/future/OrderingFuture.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/IgniteTestUtils.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/matchers/CompletableFutureCompletedMatcher.java, modules/network/src/integrationTest/java/org/apache/ignite/internal/network/netty/ItConnectionManagerTest.java, modules/network/src/integrationTest/java/org/apache/ignite/network/scalecube/ItScaleCubeNetworkMessagingTest.java, modules/network/src/main/java/org/apache/ignite/internal/network/handshake/ChannelAlreadyExistsException.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/ChannelCreationListener.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/ConnectionManager.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/DefaultRecoveryDescriptorProvider.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/InboundRecoveryHandler.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/NettySender.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/NettyServer.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/HandshakeTieBreaker.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryClientHandshakeManager.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryDescriptor.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryDescriptorProvider.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryServerHandshakeManager.java, modules/network/src/main/java/org/apache/ignite/network/DefaultMessagingService.java, modules/network/src/test/java/org/apache/ignite/internal/network/netty/NettyServerTest.java, modules/network/src/test/java/org/apache/ignite/internal/network/netty/RecoveryHandshakeTest.java, modules/network/src/test/java/org/apache/ignite/network/DefaultMessagingServiceTest.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/LeaseTracker.java
https://issues.apache.org/jira/browse/IGNITE-19903
=> IGNITE-19903 Fix recovery descriptor race condition

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-19979
=> IGNITE-19979 Table start might fail due to an outdated causality token

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sqllogic/Query.java
https://issues.apache.org/jira/browse/IGNITE-19985
=> IGNITE-19985 Allow single empty line at the end of the SQL test script

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteInMemoryNodeRestartTest.java
https://issues.apache.org/jira/browse/IGNITE-19986
=> IGNITE-19986 Increase stability of inMemoryNodeRestartNotLeader in ItIgniteInMemoryNodeRestartTest

modules/platforms/cpp/ignite/odbc/query/data_query.cpp, modules/platforms/cpp/ignite/odbc/sql_connection.cpp, modules/platforms/cpp/ignite/odbc/sql_connection.h, modules/platforms/cpp/tests/odbc-test/CMakeLists.txt, modules/platforms/cpp/tests/odbc-test/odbc_connection.h, modules/platforms/cpp/tests/odbc-test/odbc_test_utils.h, modules/platforms/cpp/tests/odbc-test/timeout_test.cpp, modules/platforms/cpp/tests/odbc-test/transaction_test.cpp
- Implemented transactions;
- Ported tests from Ignite 2;
- Adjusted some tests
=> IGNITE-19399 Support ODBC transactions

modules/platforms/cpp/ignite/odbc/config/connection_info.cpp, modules/platforms/cpp/ignite/odbc/sql_environment.cpp, modules/platforms/cpp/tests/odbc-test/connection_test.cpp
- Added support of SQL_OV_ODBC3;
- Added test.
=> IGNITE-20003 Add support of ODBC version 3.0

modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/PlacementDriverManager.java
https://issues.apache.org/jira/browse/IGNITE-19989
=> IGNITE-19989 Fixed the name of updater thread and made it finish on node stop

modules/network/src/main/java/org/apache/ignite/internal/network/netty/ConnectionManager.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java
https://issues.apache.org/jira/browse/IGNITE-19996
=> Fix ItNodeTest#testNewPeersConfigurationAppliedListener flaky

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItRaftCommandLeftInLogUntilRestartTest.java
https://issues.apache.org/jira/browse/IGNITE-20021
=> IGNITE-20021 Too many Raft-FSMCaller-Disruptor threads

buildscripts/java-integration-test.gradle
https://issues.apache.org/jira/browse/IGNITE-20029
=> IGNITE-20029 Reduce heap size for integration tests

modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java
https://issues.apache.org/jira/browse/IGNITE-20031
=> IGNITE-20031 NPE on the lease updater

buildscripts/java-integration-test.gradle, gradle/libs.versions.toml, modules/client-handler/src/test/java/org/apache/ignite/client/handler/JdbcQueryEventHandlerImplTest.java, modules/client/build.gradle, modules/client/src/test/java/org/apache/ignite/internal/client/RepeatedFinishClientTransactionTest.java, modules/core/build.gradle, modules/index/build.gradle, modules/metastorage/src/test/java/org/apache/ignite/internal/metastorage/server/AndConditionTest.java, modules/sql-engine/build.gradle, modules/table/build.gradle, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/LowWatermarkTest.java
https://issues.apache.org/jira/browse/IGNITE-19952
=> IGNITE-19952 Bump Mockito version to support Java 17

modules/network/src/integrationTest/java/org/apache/ignite/internal/network/netty/ItConnectionManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-20040
=> IGNITE-20040 Fix flaky "testOneChannelLeftIfConnectToEachOther"

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/Catalog.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogService.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogSchemaDescriptor.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/UpdateLogImpl.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/storage/UpdateLogImplTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/storage/ItRebalanceDistributedTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
https://issues.apache.org/jira/browse/IGNITE-20039
=> IGNITE-20039 Add functionality to switch the IndexManager to catalog events #2

modules/distribution-zones/build.gradle, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngine.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtil.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/ZoneCatalogDescriptorUtils.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngineTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtilUpdateAssignmentsTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-20045
=> IGNITE-20045 Use classes from Catalog domain in assignments recalculation code

modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/BaseIgniteAbstractTest.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/IgniteAbstractTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/deployment/ItDeploymentUnitFailoverTest.java
https://issues.apache.org/jira/browse/IGNITE-20043
=> IGNITE-20043 Prevent certain Mockito-related memory leaks in tests.

modules/replicator/src/integrationTest/java/org/apache/ignite/internal/replicator/ItPlacementDriverReplicaSideTest.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/Replica.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java, modules/replicator/src/test/java/org/apache/ignite/internal/replicator/PlacementDriverReplicaSideTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/storage/ItRebalanceDistributedTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNode.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ReplicaUnavailableTest.java
https://issues.apache.org/jira/browse/IGNITE-20062
=> IGNITE-20062 Temporary fix for StackOverflowError in Replica#waitForActualState when a peer leaves

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/Replica.java, modules/replicator/src/test/java/org/apache/ignite/internal/raft/client/TopologyAwareRaftGroupServiceTest.java, modules/replicator/src/test/java/org/apache/ignite/internal/replicator/PlacementDriverReplicaSideTest.java
https://issues.apache.org/jira/browse/IGNITE-20064
=> IGNITE-20064 Fix hang in TopologyAwareRaftGroupServiceTest

modules/client/src/test/java/org/apache/ignite/client/fakes/FakeSchemaRegistry.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/SchemaManager.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/SchemaRegistry.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/registry/SchemaRegistryImpl.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/registry/SchemaRegistryImplTest.java, modules/table/src/test/java/org/apache/ignite/internal/benchmarks/TupleMarshallerFixlenOnlyBenchmark.java, modules/table/src/test/java/org/apache/ignite/internal/benchmarks/TupleMarshallerVarlenOnlyBenchmark.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummySchemaManagerImpl.java
https://issues.apache.org/jira/browse/IGNITE-20071
=> IGNITE-20071 Simplify SchemaManager and SchemaRegistryImpl interaction

modules/transactions/src/test/java/org/apache/ignite/internal/tx/storage/state/rocksdb/RocksDbTxStateStorageTest.java, modules/transactions/src/testFixtures/java/org/apache/ignite/internal/tx/storage/state/AbstractTxStateStorageTest.java
https://issues.apache.org/jira/browse/IGNITE-20075
=> IGNITE-20075 Get rid of potential thread leak in RocksDbTxStateStorageTest

modules/cluster-management/src/integrationTest/java/org/apache/ignite/internal/cluster/management/ItClusterManagerTest.java, modules/network/src/main/java/org/apache/ignite/internal/network/netty/ConnectionManager.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryClientHandshakeManager.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryServerHandshakeManager.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/message/HandshakeRejectedMessage.java, modules/network/src/main/java/org/apache/ignite/network/scalecube/ScaleCubeClusterServiceFactory.java, modules/network/src/test/java/org/apache/ignite/internal/network/netty/RecoveryHandshakeTest.java, modules/network/src/test/java/org/apache/ignite/network/DefaultMessagingServiceTest.java
https://issues.apache.org/jira/browse/IGNITE-20076
=> IGNITE-20076 Improve networking shutdown implementation

modules/configuration/src/test/java/org/apache/ignite/internal/configuration/testframework/ConfigurationExtensionTest.java, modules/configuration/src/testFixtures/java/org/apache/ignite/internal/configuration/testframework/ConfigurationExtension.java
https://issues.apache.org/jira/browse/IGNITE-20089
=> IGNITE-20089 Fix ConfigurationExtension static parameters injection

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/TxManager.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadWriteTransactionImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java
=> IGNITE-20033 

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/PlatformTestNodeRunner.java
https://issues.apache.org/jira/browse/IGNITE-20102
=> IGNITE-20102 Fix hanging C#/C++ tests due to IndexManager switch to catalog

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CatalogUtils.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogTableDescriptor.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/AddColumnEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/AlterColumnEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/CreateTableEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/DropTableEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/events/TableEventParameters.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/AlterColumnEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/DropColumnsEntry.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/NewColumnsEntry.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngineTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtilUpdateAssignmentsTest.java, modules/schema/build.gradle, modules/schema/src/main/java/org/apache/ignite/internal/schema/CatalogDescriptorUtils.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/CatalogSchemaManager.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/SchemaManager.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/SchemaUtils.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/catalog/CatalogToSchemaDescriptorConverter.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/AbstractSchemaConverterTest.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/CatalogSchemaManagerTest.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/catalog/CatalogToSchemaDescriptorConverterTest.java, modules/schema/src/test/java/org/apache/ignite/internal/schema/configuration/ConfigurationToSchemaDescriptorConverterTest.java, modules/schema/src/testFixtures/java/org/apache/ignite/internal/schema/testutils/SchemaConfigurationConverter.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/schema/CatalogSqlSchemaManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-19501
=> IGNITE-19501 SchemaManager should use CatalogService for building BinaryRow descriptors

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/call/metric/ItEnabledMetricCallsTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/call/metric/ItMetricCallsTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/metric/ItEnabledNodeMetricCommandTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/metric/ItNodeMetricCommandTest.java, modules/cli/src/integrationTest/java/org/apache/ignite/internal/rest/ItGeneratedRestClientTest.java
https://issues.apache.org/jira/browse/IGNITE-20101
=> IGNITE-20101 Relax CLI metric tests

modules/raft/src/main/java/org/apache/ignite/internal/raft/RaftGroupServiceImpl.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNode.java
https://issues.apache.org/jira/browse/IGNITE-20023
=> IGNITE-20023 Eliminate NPEs in ItTxDistributedTestSingleNode

build.gradle, buildscripts/java-integration-test.gradle
https://issues.apache.org/jira/browse/IGNITE-20080
=> IGNITE-20080 Reduce the number of threads used by Raft in tests

modules/catalog/build.gradle, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManager.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogParamsValidationUtils.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogValidationException.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AlterZoneParams.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CatalogUtils.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateZoneParams.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/DataStorageParams.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/DropZoneParams.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/descriptors/CatalogDataStorageDescriptor.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/BaseCatalogManagerTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerValidationTest.java, modules/core/src/main/java/org/apache/ignite/lang/IgniteInternalException.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ddl/DdlCommandHandlerWrapper.java
https://issues.apache.org/jira/browse/IGNITE-20146
=> IGNITE-20146 Add improvements to the catalog associated with the DistributionZone

.github/PULL_REQUEST_TEMPLATE.md, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogService.java, modules/core/src/main/java/org/apache/ignite/internal/hlc/HybridTimestamp.java, modules/core/src/test/java/org/apache/ignite/internal/hlc/HybridTimestampTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/schema/SchemaSyncService.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/schema/SchemaSyncServiceImpl.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/schema/SchemaSyncServiceImplTest.java
https://issues.apache.org/jira/browse/IGNITE-19770
=> IGNITE-19770 Add a mechanism to wait till a schema is available via Schema Sync at a ts

modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/JRaftUtils.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/NodeImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/core/AppendEntriesRequestProcessor.java
https://issues.apache.org/jira/browse/IGNITE-20161
=> IGNITE-20161 Fix NPE in AppendEntriesRequestProcessor

modules/cli/src/main/java/org/apache/ignite/internal/cli/logger/HttpLogging.java, modules/cli/src/test/java/org/apache/ignite/internal/cli/logger/HttpLoggingTest.java
https://issues.apache.org/jira/browse/IGNITE-19953
=> IGNITE-19953 Fix --verbose/-v option in CLI interactive mode

modules/raft/src/testFixtures/java/org/apache/ignite/internal/raft/service/ItAbstractListenerSnapshotTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTablePersistenceTest.java
https://issues.apache.org/jira/browse/IGNITE-20180
=> IGNITE-20180 Fix flaky ItTablePersistenceTest#testSnapshot

modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/storage/ItRebalanceDistributedTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-20053
=> IGNITE-20053 ItRebalanceDistributedTest fixed

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDmlTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/UpdatableTableImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/rule/TableModifyConverterRule.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/PlanUtils.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestBuilders.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/DmlPlannerTest.java
https://issues.apache.org/jira/browse/IGNITE-20030
=> IGNITE-20030 Delete operation fails if PK is set on arbitrary columns.

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CatalogUtils.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/PlatformTestNodeRunner.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientSqlTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlAsynchronousApiTest.java, modules/schema/build.gradle, modules/schema/src/testFixtures/java/org/apache/ignite/internal/schema/testutils/SchemaConfigurationConverter.java, modules/schema/src/testFixtures/java/org/apache/ignite/internal/schema/testutils/definition/ColumnType.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/CatalogColumnDescriptor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/CatalogSqlSchemaManager.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/type/IgniteTypeFactory.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/TypeUtils.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/schema/CatalogSqlSchemaManagerTest.java
=> IGNITE-20192 Fix default length for variable-length columns

modules/raft/src/integrationTest/java/org/apache/ignite/raft/server/ItSimpleCounterServerTest.java
https://issues.apache.org/jira/browse/IGNITE-20214
=> IGNITE-20214 Fix flaky ItSimpleCounterServerTest#testRefreshLeader test

modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/BaseDistributionZoneManagerTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneFiltersTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerAlterFilterTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerConfigurationChangesTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerFilterTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerScaleUpTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerWatchListenerTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/causalitydatanodes/DistributionZoneCausalityDataNodesTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/rebalance/DistributionZoneRebalanceEngineTest.java, modules/distribution-zones/src/testFixtures/java/org/apache/ignite/internal/distributionzones/DistributionZonesTestUtil.java, modules/placement-driver/build.gradle, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/MultiActorPlacementDriverTest.java, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/PlacementDriverManagerTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/distribution/zones/ItIgniteDistributionZoneManagerNodeRestartTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/MockedStructuresTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-20189
=> IGNITE-20189 Prepare existing tests for the distributed zone to switch to the catalog #2

modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java, modules/placement-driver/build.gradle, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/ActiveActorTest.java, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/BasePlacementDriverTest.java, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/MultiActorPlacementDriverTest.java, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/PlacementDriverManagerTest.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/PlacementDriverManager.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/TopologyTracker.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/LeaseTracker.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/Leases.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java
https://issues.apache.org/jira/browse/IGNITE-20229
=> IGNITE-20229 Get rid of configurations in PlacementDriverManager

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItRoReadsTest.java, modules/schema/build.gradle, modules/schema/src/testFixtures/java/org/apache/ignite/internal/schema/BinaryRowMatcher.java, modules/schema/src/testFixtures/java/org/apache/ignite/internal/schema/SchemaTestUtils.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageConcurrencyTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageGcTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvPartitionStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/BaseMvStoragesTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/AbstractPageMemoryMvPartitionStorageTest.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorageTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/IndexBaseTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java
https://issues.apache.org/jira/browse/IGNITE-20243
=> IGNITE-20243 Introduce a Matcher for BinaryRows

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDmlTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/UpdatableTableImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/ExpressionFactoryImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/RexImpTable.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/ModifyNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteSqlToRelConvertor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/HashFunctionFactoryImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/ImplicitCastsTest.java
=> IGNITE-19096 Sql. Replace placeholder values from ModifyNode

modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNode.java
https://issues.apache.org/jira/browse/IGNITE-20251
=> IGNITE-20251 NPE in ItTxDistributedTestThreeNodesThreeReplicas

README.md
https://issues.apache.org/jira/browse/IGNITE-20159
=> IGNITE-20159 Add README for the project

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/rebalance/RebalanceUtil.java, modules/distribution-zones/src/testFixtures/java/org/apache/ignite/internal/distributionzones/DistributionZonesTestUtil.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/storage/ItRebalanceDistributedTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/distribution/zones/ItIgniteDistributionZoneManagerNodeRestartTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-20249
=> IGNITE-20249 Refactoring some tests to make it easier to switch to catalog

buildscripts/java-junit5.gradle
https://issues.apache.org/jira/browse/IGNITE-20261
=> IGNITE-20261 Configure maximum heap size for unit tests

modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItCliServiceTest.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java, modules/raft/src/testFixtures/java/org/apache/ignite/raft/jraft/core/MockStateMachine.java
https://issues.apache.org/jira/browse/IGNITE-20257
=> IGNITE-20257 fix flaky ItCliServiceTest#testSnapshot test  @alievmirza

modules/platforms/cpp/ignite/client/detail/utils.cpp, modules/platforms/cpp/ignite/protocol/utils.cpp, modules/platforms/cpp/tests/client-test/all_fields_type.h, modules/platforms/cpp/tests/client-test/key_value_binary_view_test.cpp, modules/platforms/cpp/tests/client-test/key_value_view_test.cpp, modules/platforms/cpp/tests/client-test/record_binary_view_test.cpp, modules/platforms/cpp/tests/client-test/record_view_test.cpp, modules/platforms/cpp/tests/client-test/sql_test.cpp, modules/platforms/dotnet/Apache.Ignite.Tests/Sql/IgniteDbDataReaderTests.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/PlatformTestNodeRunner.java
- Added bool support;
- Edited tests.
=> IGNITE-19983 C++: Support BOOLEAN datatype

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItCommonApiTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sqllogic/ItSqlLogicTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/DestinationFactory.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutableTable.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutableTableRegistryImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionDependencyResolver.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionDependencyResolverImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/LogicalRelImplementor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ResolvedDependencies.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/externalize/RelJson.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/CatalogSqlSchemaManager.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/IgniteSchema.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/SqlSchemaManager.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/SqlSchemaManagerImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/trait/DistributionFunction.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/trait/DistributionTrait.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/trait/IgniteDistribution.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/HashFunctionFactory.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/HashFunctionFactoryImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionDependencyResolverSelfTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImplTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/TestExecutableTableRegistry.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/PredefinedSchemaManager.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestBuilders.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestNode.java
=> IGNITE-20246 Sql. Decouple distribution trait and function

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItRaftCommandLeftInLogUntilRestartTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
https://issues.apache.org/jira/browse/IGNITE-19570
=> IGNITE-19570 Write intent resolution for RW transactions

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/sql/ItSqlReplCommandTest.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/SqlReplCommand.java
https://issues.apache.org/jira/browse/IGNITE-20271 
=> IGNITE-20271 Error in CLI on SQL repl command

.run/PMD [pmdMain].run.xml, modules/rocksdb-common/src/main/java/org/apache/ignite/internal/rocksdb/ColumnFamily.java
=> IGNITE-20276: Include tests into run PMD configuration

modules/platforms/cpp/ignite/tuple/binary_tuple_builder.h
https://issues.apache.org/jira/browse/IGNITE-20278
=> IGNITE-20278 Make binary_tuple_builder more friendly for inheritance.

.run/All checks [PMD, modernizer, checkstyle].run.xml, .run/Fast build only java [clean build -x assembleDist -x distTar -x distZip -x check -x :platforms:build -x :platforms:cmakeConfigureOdbc -x :platforms:cmakeConfigure -x :platforms:cmakeBuildOdbc].run.xml
=> IGNITE-20283: IDEA gradle run configurations improvements

modules/runner/src/integrationTest/sql/sqlite/join/join1.test, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ArrayRowHandler.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExchangeService.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExchangeServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/LogicalRelImplementor.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/RowHandler.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/ExpressionFactoryImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/agg/AccumulatorsFactory.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/agg/GroupKey.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/Inbox.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/Outbox.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/externalize/RelJson.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/message/QueryBatchMessage.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/ExchangeExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/ExecutionTest.java
=> IGNITE-19788 Sql. Change QueryBatchMessage serialization

modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientDataStreamer.java, modules/core/src/main/java/org/apache/ignite/internal/streamer/StreamerBuffer.java, modules/core/src/main/java/org/apache/ignite/internal/streamer/StreamerOptions.java, modules/core/src/main/java/org/apache/ignite/internal/streamer/StreamerSubscriber.java, modules/core/src/test/java/org/apache/ignite/internal/streamer/StreamerSubscriberTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/DataStreamer.java
* Fix an error when computing the number of in-flight batches
* Remove StreamerOptions#retryLimit
* Remove obsolete timer checks in StreamerBuffer
https://issues.apache.org/jira/browse/IGNITE-20291
\- The pull request title is treated as the final commit message. The following pattern must be used: IGNITE-XXXX Change summary where XXXX - number of JIRA …
=> IGNITE-20291 Fix DataStreamer in-flight counts for backpressure

modules/table/src/test/java/org/apache/ignite/internal/table/TxLocalTest.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-20205
=> IGNITE-20205 Fixed flaky test TxLocalTest#testBalance

modules/platforms/dotnet/Apache.Ignite.Tests/MetricsTests.cs
Add `AssertMetric` for reliable and succinct checks.
=> IGNITE-20266 .NET: Fix MetricsTests flakiness

modules/distribution-zones/src/testFixtures/java/org/apache/ignite/internal/distributionzones/DistributionZonesTestUtil.java
https://issues.apache.org/jira/browse/IGNITE-20279
=> IGNITE-20279 Fixed asynchronous zone altering in DistributionZonesTestUtil.

modules/api/src/main/java/org/apache/ignite/lang/ErrorGroup.java, modules/api/src/main/java/org/apache/ignite/lang/ErrorGroups.java, modules/api/src/main/java/org/apache/ignite/lang/IgniteCheckedException.java, modules/api/src/main/java/org/apache/ignite/lang/IgniteException.java, modules/client/src/main/java/org/apache/ignite/internal/client/TcpIgniteClient.java, modules/core/src/main/java/org/apache/ignite/lang/IgniteInternalCheckedException.java, modules/core/src/main/java/org/apache/ignite/lang/IgniteInternalException.java, modules/core/src/test/java/org/apache/ignite/lang/ErrorGroupTest.java, modules/platforms/dotnet/Apache.Ignite.Internal.Generators/ErrorGroupsGenerator.cs, modules/platforms/dotnet/Apache.Ignite.Tests/ErrorGroupTests.cs, modules/runner/src/main/java/org/apache/ignite/internal/app/IgnitionImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/TransactionInternalCheckedException.java
https://issues.apache.org/jira/browse/IGNITE-17539
=> IGNITE-17539 Fix error groups initialization on start-up

modules/runner/src/integrationTest/java/org/apache/ignite/internal/test/WatchListenerInhibitor.java
https://issues.apache.org/jira/browse/IGNITE-20316
=> IGNITE-20316 WatchListenerInhibitor might cause lost updates

modules/raft/src/main/java/org/apache/ignite/raft/jraft/storage/impl/LogManagerImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/util/Utils.java
https://issues.apache.org/jira/browse/IGNITE-20318
=> IGNITE-20318 Fix logging for raft log truncation

modules/api/src/main/java/org/apache/ignite/lang/ErrorGroups.java
=> IGNITE-20321: Fix compilation error in ErrorGroups.

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/MapReduceAggregatesTest.java
=> IGNITE-20334 Sql. Fix compilation after IGNITE-20077

modules/platforms/cpp/cmake/find_odbc.cmake, modules/platforms/cpp/ignite/odbc/CMakeLists.txt
=> IGNITE-20329 Fix ODBC build for MacOS

modules/raft/src/main/java/org/apache/ignite/internal/raft/Loza.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/ActionRequestInterceptor.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/IgniteRpcServer.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/InterceptingActionRequestProcessor.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/NullActionRequestInterceptor.java, modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/core/AppendEntriesRequestInterceptor.java, modules/raft/src/testFixtures/java/org/apache/ignite/raft/jraft/rpc/TestIgniteRpcServer.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/schema/CatalogVersionSufficiency.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/schema/CheckCatalogVersionOnActionRequest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/schema/CheckCatalogVersionOnAppendEntries.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/schema/CatalogVersionSufficiencyTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/schema/CheckCatalogVersionOnActionRequestTest.java
https://issues.apache.org/jira/browse/IGNITE-20262
=> IGNITE-20262 Refuse accepting partition Raft commands when not enough schemas are available

modules/table/src/test/java/org/apache/ignite/internal/table/distributed/schema/CheckCatalogVersionOnActionRequestTest.java
https://issues.apache.org/jira/browse/IGNITE-20338
=> IGNITE-20338 CheckCatalogVersionOnActionRequestTest fails with NPEs

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManager.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/MockedStructuresTest.java
=> IGNITE-20016 Introduce bulk operation to catalog

modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/MultiActorPlacementDriverTest.java, modules/placement-driver/src/integrationTest/java/org/apache/ignite/internal/placementdriver/PlacementDriverManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-20319
=> IGNITE-20319 MultiActorPlacementDriverTest and PlacementDriverManagerTest incorrectly share hybridClock

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/ExchangeExecutionTest.java
=> IGNITE-20182 Sql. Flaky test ExchangeExecutionTest#racesBetweenRewindAndBatchesFromPreviousRequest

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogCommand.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManager.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogParamsValidationUtils.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/TableNotFoundValidationException.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AbstractTableCommand.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/AbstractTableCommandBuilder.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CatalogUtils.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateTableCommand.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/CreateTableCommandBuilder.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/DropTableCommand.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/commands/DropTableCommandBuilder.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerSelfTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/CatalogManagerValidationTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/AbstractCommandValidationTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/CreateTableCommandValidationTest.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/commands/DropTableCommandValidationTest.java, modules/catalog/src/testFixtures/java/org/apache/ignite/internal/catalog/BaseCatalogManagerTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ddl/DdlCommandHandlerWrapper.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ddl/DdlToCatalogCommandConverter.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/MockedStructuresTest.java
=> IGNITE-20307 Move handler of DropTable command from CatalogManager to command itself

modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/AbstractClusterStateStorageManagerTest.java, modules/cluster-management/src/test/java/org/apache/ignite/internal/cluster/management/raft/RocksDbClusterStateStorageManagerTest.java, modules/compute/src/test/java/org/apache/ignite/internal/compute/loader/JobClassLoaderFactoryTest.java, modules/compute/src/test/java/org/apache/ignite/internal/compute/loader/JobContextManagerTest.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/IgniteTestUtils.java, modules/raft/src/integrationTest/java/org/apache/ignite/raft/jraft/core/ItNodeTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/configuration/ItNodeBootstrapConfigurationTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/QueryTaskExecutorImpl.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/AbstractExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/ExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/planner/PlannerTest.java
https://issues.apache.org/jira/browse/IGNITE-18784
=> IGNITE-18784 Fix tests for Windows

modules/client-common/src/main/java/org/apache/ignite/internal/jdbc/proto/event/JdbcMetaTablesResult.java, modules/platforms/cpp/ignite/client/detail/node_connection.cpp, modules/platforms/cpp/ignite/client/detail/node_connection.h, modules/platforms/cpp/ignite/odbc/CMakeLists.txt, modules/platforms/cpp/ignite/odbc/meta/column_meta.h, modules/platforms/cpp/ignite/odbc/meta/table_meta.cpp, modules/platforms/cpp/ignite/odbc/meta/table_meta.h, modules/platforms/cpp/ignite/odbc/query/data_query.cpp, modules/platforms/cpp/ignite/odbc/query/query.h, modules/platforms/cpp/ignite/odbc/query/table_metadata_query.cpp, modules/platforms/cpp/ignite/odbc/query/table_metadata_query.h, modules/platforms/cpp/ignite/odbc/sql_statement.cpp, modules/platforms/cpp/ignite/odbc/string_utils.h, modules/platforms/cpp/ignite/protocol/client_operation.h, modules/platforms/cpp/ignite/protocol/messages.cpp, modules/platforms/cpp/ignite/protocol/messages.h, modules/platforms/cpp/tests/client-test/sql_test.cpp, modules/platforms/cpp/tests/odbc-test/api_robustness_test.cpp, modules/platforms/cpp/tests/odbc-test/meta_queries_test.cpp, modules/platforms/cpp/tests/odbc-test/odbc_connection.h, modules/platforms/cpp/tests/odbc-test/odbc_test_utils.h, modules/platforms/cpp/tests/odbc-test/queries_test.cpp
- Implemented table meta fetching, re-used `JDBC_TABLE_META` message. Need to refactor in future: [IGNITE-20349](https://issues.apache.org/jira/browse/IGNITE-20349);
- Implemented fetching on ODBC side;
- Un-commented related tests.
=> IGNITE-19214 Table metadata fetching for ODBC

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/StorageUpdateHandler.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PendingRows.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/IndexBaseTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/IndexCleanupTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/StorageUpdateHandlerTest.java
https://issues.apache.org/jira/browse/IGNITE-20354
=> IGNITE-20354 Reduce code duplication in commit cleanup

modules/runner/src/integrationTest/java/org/apache/ignite/internal/distribution/zones/ItIgniteDistributionZoneManagerNodeRestartTest.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerTest.java
=> CATALOG-FEATURE-FIX-TESTS-2023-09-07 Fix from Orlov

modules/runner/src/integrationTest/java/org/apache/ignite/internal/compute/ItComputeTestBaseEmbedded.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/rest/authentication/ItAuthenticationTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/rest/ssl/ItRestSslTest.java
* Also, get rid of parallel start/stop nodes
https://issues.apache.org/jira/browse/IGNITE-20351
=> IGNITE-20351 Log response body in REST test if it fails

modules/raft/src/main/java/org/apache/ignite/raft/jraft/rpc/impl/RaftGroupEventsClientListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/StorageUpdateHandler.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PendingRows.java
https://issues.apache.org/jira/browse/IGNITE-20379
=> IGNITE-20379 Concurrency issues with write intent tracking

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ClusterPerClassIntegrationTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItDmlTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItMetadataTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/datatypes/tests/BaseDataTypeTest.java, modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/engine/util/ColumnMatcher.java, modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/engine/util/InjectQueryCheckerFactory.java, modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/engine/util/MetadataMatcher.java, modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/engine/util/QueryChecker.java, modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/engine/util/QueryCheckerExtension.java, modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/engine/util/QueryCheckerFactory.java, modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/engine/util/QueryCheckerFactoryImpl.java, modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/engine/util/QueryCheckerImpl.java
=> IGNITE-20337 Ensure QueryChecker is properly used in tests

buildscripts/java-core.gradle
=> Revert "IGNITE-20200 Fix Gradle non-zero exit code on test failure"

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/UpdateLog.java, modules/catalog/src/main/java/org/apache/ignite/internal/catalog/storage/UpdateLogImpl.java, modules/catalog/src/test/java/org/apache/ignite/internal/catalog/storage/UpdateLogImplTest.java
https://issues.apache.org/jira/browse/IGNITE-20391
=> IGNITE-20391 Return future metastore event processing from UpdateListener#onUpdate

modules/file-transfer/src/integrationTest/java/org/apache/ignite/internal/network/file/ItFileTransferTest.java
https://issues.apache.org/jira/browse/IGNITE-20374
=> IGNITE-20374 Disable tests related to POSIX file permissions on Windows

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/distribution/zones/ItIgniteDistributionZoneManagerNodeRestartTest.java
https://issues.apache.org/jira/browse/IGNITE-20332
=> IGNITE-20332 Fixed DistributionZoneManager.onUpdateFilter handling.

modules/jdbc/src/integrationTest/java/org/apache/ignite/jdbc/ItJdbcStatementSelfTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutableTable.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutableTableRegistry.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutableTableRegistryImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionDependencyResolverImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ResolvedDependencies.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/schema/IgniteSchema.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/ExecutionDependencyResolverSelfTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/TestExecutableTableRegistry.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/util/StatementChecker.java
https://issues.apache.org/jira/browse/IGNITE-20331
=> IGNITE-20331 Cleanup the code after switching TableManager to the catalog

modules/platforms/cpp/tests/client-test/sql_test.cpp, modules/platforms/dotnet/Apache.Ignite.Tests/Sql/SqlTests.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/client/ItThinClientSqlTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItMetadataTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgnitePlanner.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/IgniteSqlValidator.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/PrepareServiceImpl.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/prepare/ValidationResult.java
=> IGNITE-19106 Sql. Fix partially broken column namings

modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/PlacementDriverManager.java
https://issues.apache.org/jira/browse/IGNITE-20280
=> IGNITE-20280 Lease updater exception is not logged on initialization

modules/configuration-annotation-processor/src/main/java/org/apache/ignite/internal/configuration/processor/ConfigurationProcessor.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationTreeGenerator.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/notifications/ConfigurationNotificationUtils.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/notifications/ConfigurationNotifier.java, modules/configuration/src/main/java/org/apache/ignite/internal/configuration/util/ConfigurationUtil.java, modules/configuration/src/test/java/org/apache/ignite/internal/configuration/util/ConfigurationUtilTest.java, modules/core/src/main/java/org/apache/ignite/internal/util/CollectionUtils.java, modules/core/src/test/java/org/apache/ignite/internal/util/CollectionUtilsTest.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/compaction/Compactor.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStoreManager.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/store/GroupPageStoresMap.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStoreManagerTest.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/store/GroupPageStoresMapTest.java
https://issues.apache.org/jira/browse/IGNITE-20398
=> IGNITE-20398 Filter null values for any cfg

modules/table/src/test/java/org/apache/ignite/internal/table/TxLocalTest.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-20355
=> IGNITE-20355 Fix failing RO tests in TxLocalTest

modules/runner/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/schemasync/ItSchemaSyncAndReplicationTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java
https://issues.apache.org/jira/browse/IGNITE-20394
=> IGNITE-20394 ItSchemaSyncAndReplicationTest#laggingSchemasPreventPartitionDataReplication sometims fails with TimeoutException

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/datatypes/tests/BaseDmlDataTypeTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/datatypes/tests/BaseExpressionDataTypeTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/datatypes/tests/BaseQueryDataTypeTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/datatypes/uuid/ItUuidDmlTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/datatypes/uuid/ItUuidExpressionTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/datatypes/uuid/ItUuidQueryTest.java
=> IGNITE-20226 Sql. Fix muted tests after disallowed char -> varbinary casting

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/PersistentPageMemory.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointManager.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointPagesWriter.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointWorkflow.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/Checkpointer.java, modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/util/PageIdUtils.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/checkpoint/CheckpointWorkflowTest.java, modules/storage-api/src/main/java/org/apache/ignite/internal/storage/engine/StorageEngine.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/AbstractMvTableStorageTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/engine/AbstractStorageEngineTest.java, modules/storage-api/src/testFixtures/java/org/apache/ignite/internal/storage/impl/TestStorageEngine.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/PersistentPageMemoryStorageEngine.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/VolatilePageMemoryStorageEngine.java, modules/storage-page-memory/src/main/java/org/apache/ignite/internal/storage/pagememory/mv/PersistentPageMemoryMvPartitionStorage.java, modules/storage-page-memory/src/test/java/org/apache/ignite/internal/storage/pagememory/engine/PersistentPageMemoryStorageEngineTest.java, modules/storage-rocksdb/src/main/java/org/apache/ignite/internal/storage/rocksdb/RocksDbStorageEngine.java, modules/storage-rocksdb/src/test/java/org/apache/ignite/internal/storage/rocksdb/engine/RocksDbStorageEngineTest.java
https://issues.apache.org/jira/browse/IGNITE-20419
=> IGNITE-20419 Fix partition meta loss after idle cluster restart.

modules/cli/src/main/java/org/apache/ignite/internal/cli/config/ini/IniConfigManager.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/config/ini/IniFile.java
https://issues.apache.org/jira/browse/IGNITE-20343
=> IGNITE-20343 Flaky ItIgnitePicocliCommandsTest

modules/client/src/main/java/org/apache/ignite/internal/client/ClientUtils.java, modules/client/src/main/java/org/apache/ignite/internal/client/TcpClientChannel.java, modules/platforms/cpp/ignite/client/detail/table/schema.h, modules/platforms/cpp/ignite/odbc/CMakeLists.txt, modules/platforms/cpp/ignite/odbc/app/application_data_buffer.h, modules/platforms/cpp/ignite/odbc/query/query.h, modules/platforms/cpp/ignite/odbc/query/table_metadata_query.h, modules/platforms/cpp/ignite/odbc/query/type_info_query.cpp, modules/platforms/cpp/ignite/odbc/query/type_info_query.h, modules/platforms/cpp/ignite/odbc/sql_statement.cpp, modules/platforms/cpp/ignite/odbc/type_traits.cpp, modules/platforms/cpp/ignite/odbc/type_traits.h, modules/platforms/cpp/ignite/protocol/utils.cpp, modules/platforms/cpp/tests/client-test/key_value_binary_view_test.cpp, modules/platforms/cpp/tests/client-test/key_value_view_test.cpp, modules/platforms/cpp/tests/client-test/record_binary_view_test.cpp, modules/platforms/cpp/tests/client-test/record_view_test.cpp, modules/platforms/cpp/tests/odbc-test/meta_queries_test.cpp
- Ported code from Ignite 2;
- Adjusted it to match new SQL engine;
- Un-muted related tests.
=> IGNITE-19216 ODBC type info fetching

modules/platforms/cpp/ignite/odbc/app/application_data_buffer.cpp, modules/platforms/cpp/ignite/odbc/app/application_data_buffer_test.cpp
=> IGNITE-20147 Fix ODBC timestamp-related tests

modules/runner/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceRecoveryTest.java
https://issues.apache.org/jira/browse/IGNITE-20441
=> IGNITE-20441 Mute ItRebalanceRecoveryTest

modules/client/src/main/java/org/apache/ignite/internal/client/ClientMetricSource.java, modules/client/src/test/java/org/apache/ignite/client/ClientMetricsTest.java
* Add a test to ensure all metrics are registered
* Fix missing metrics
=> IGNITE-20420 Fix missing metrics in ClientMetricSource

modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItColocationTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/StorageUpdateHandler.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/TxState.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java
https://issues.apache.org/jira/browse/IGNITE-20482
=> IGNITE-20482 Simplify write intent resolution in PartitionReplicaListener

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/agg/AccumulatorsFactory.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/TypeUtils.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/RuntimeSortedIndexTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/BaseAggregateTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/ExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/HashAggregateSingleGroupExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/HashIndexSpoolExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/MergeJoinExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/NestedLoopJoinExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/SortedIndexSpoolExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/TableScanNodeExecutionTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/TableSpoolExecutionTest.java
=> IGNITE-20336 Sql. Remove conversion from java types to TypeSpec

modules/raft/src/main/java/org/apache/ignite/raft/jraft/core/NodeImpl.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/raftsnapshot/ItTableRaftSnapshotsTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/schemasync/ItSchemaSyncAndReplicationTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/schema/CheckCatalogVersionOnActionRequest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/schema/CheckCatalogVersionOnAppendEntries.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/schema/CheckCatalogVersionOnActionRequestTest.java
https://issues.apache.org/jira/browse/IGNITE-20410
=> IGNITE-20410 CheckCatalogVersionOnActionRequest breaks RAFT client leaderId refresh protocol

examples/config/java.util.logging.properties, packaging/db/ignite.java.util.logging.properties, packaging/docker/ignite.java.util.logging.properties
https://issues.apache.org/jira/browse/IGNITE-20497
=> IGNITE-20497 Fix logger formatter

modules/api/src/main/java/org/apache/ignite/table/Tuple.java, modules/client/src/main/java/org/apache/ignite/internal/client/sql/ClientResultSetMetadata.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeAsyncResultSet.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/api/ItSqlAsynchronousApiTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItMetadataTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/api/ResultSetMetadataImpl.java
=> IGNITE-19894 Sql. Correct processing for case sensitivity column names

modules/platforms/dotnet/Apache.Ignite.Tests/Compute/ComputeTests.cs, modules/platforms/dotnet/Apache.Ignite/IgniteClient.cs, modules/platforms/dotnet/Apache.Ignite/IgniteClientConfiguration.cs, modules/platforms/dotnet/Apache.Ignite/IgniteException.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Common/IgniteArgumentCheck.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Common/IgniteToStringBuilder.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Compute/Compute.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Sql/ResultSet.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Sql/Sql.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/DataStreamer.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/KeyValueView.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/RecordView.cs, modules/platforms/dotnet/Apache.Ignite/Internal/Table/Tables.cs, modules/platforms/dotnet/Apache.Ignite/Log/CategoryLogger.cs, modules/platforms/dotnet/Apache.Ignite/Log/LoggerExtensions.cs, modules/platforms/dotnet/Apache.Ignite/RetryLimitPolicy.cs, modules/platforms/dotnet/Apache.Ignite/RetryReadPolicy.cs, modules/platforms/dotnet/Apache.Ignite/Sql/IgniteDbDataReader.cs, modules/platforms/dotnet/Apache.Ignite/Sql/IgniteQueryableExtensions.Average.cs, modules/platforms/dotnet/Apache.Ignite/Sql/IgniteQueryableExtensions.Dml.cs, modules/platforms/dotnet/Apache.Ignite/Sql/IgniteQueryableExtensions.Sum.cs, modules/platforms/dotnet/Apache.Ignite/Sql/IgniteQueryableExtensions.cs, modules/platforms/dotnet/Apache.Ignite/Sql/SqlStatement.cs, modules/platforms/dotnet/Apache.Ignite/SslStreamFactory.cs, modules/platforms/dotnet/Apache.Ignite/Table/IIgniteTuple.cs
=> IGNITE-20479 .NET: Replace IgniteArgumentCheck.NotNull with ThrowIfNull

modules/client/src/test/java/org/apache/ignite/client/fakes/FakeTxManager.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/exec/rel/TableScanNodeExecutionTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTablePersistenceTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNode.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNodeNoCleanupMessage.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItColocationTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/StorageUpdateHandler.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionDataStorage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/test/java/org/apache/ignite/internal/table/RepeatedFinishReadWriteTransactionTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/TxLocalTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/StorageCleanupTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java, modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/TxManager.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java
https://issues.apache.org/jira/browse/IGNITE-20041
=> IGNITE-20041 Asynchronous writeIntent cleanup on write intent resolution

modules/table/src/test/java/org/apache/ignite/internal/table/distributed/StorageCleanupTest.java
https://issues.apache.org/jira/browse/IGNITE-20509
=> IGNITE-20509 StorageCleanupTest compilation error

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItSchemaChangeKvViewTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
https://issues.apache.org/jira/browse/IGNITE-20486
=> IGNITE-20486 Protect write intent resolution with busy locks

modules/client-handler/build.gradle, modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/TestServer.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientHandlerModule.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/jdbc/JdbcMetadataCatalog.java, modules/client/build.gradle, modules/client/src/test/java/org/apache/ignite/client/TestClientHandlerModule.java, modules/client/src/test/java/org/apache/ignite/client/TestServer.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/schema/src/main/java/org/apache/ignite/internal/schema/CatalogSchemaManager.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerIndexLockingTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java, modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/distributed/schema/AlwaysSyncedSchemaSyncService.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-20518
=> IGNITE-20518 Use CatalogService in JdbcMetadataCatalog

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java
https://issues.apache.org/jira/browse/IGNITE-20527
=> IGNITE-20527 Compilation fixed.

modules/cli/src/integrationTest/java/org/apache/ignite/internal/cli/commands/sql/ItSqlReplCommandTest.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/Main.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/ReplManager.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/commands/sql/SqlReplCommand.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/executor/ReplExecutor.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/executor/ReplExecutorImpl.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/executor/ReplExecutorProvider.java, modules/cli/src/main/java/org/apache/ignite/internal/cli/core/repl/executor/ReplExecutorProviderImpl.java
https://issues.apache.org/jira/browse/IGNITE-20494
Github doesn't understand the renaming here done in two commits, so it's easier to see commits separately. …
=> IGNITE-20494 sql command does not enter repl

buildscripts/java-core.gradle
https://[issues.apache.org/jira/browse/IGNITE-19633](https://issues.apache.org/jira/browse/IGNITE-19633)
- [Apache Ignite Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE …
=> IGNITE-19633 Exclude volcano package from javadocs

modules/client/src/test/java/org/apache/ignite/client/fakes/FakeTxManager.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/SqlQueryProcessor.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/NoOpTransaction.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java, modules/table/src/test/java/org/apache/ignite/internal/table/RepeatedFinishReadWriteTransactionTest.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/InternalTransaction.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/TxManager.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadOnlyTransactionImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadWriteTransactionImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-20537
=> IGNITE-20537 Add ability to create implicit transactions

modules/client/src/test/java/org/apache/ignite/client/fakes/FakeTxManager.java, modules/platforms/dotnet/Apache.Ignite.Tests/Table/DataStreamerTests.cs, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/message/ReadOnlyDirectReplicaRequest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTablePersistenceTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableMessageGroup.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replication/request/ReadOnlyDirectMultiRowReplicaRequest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replication/request/ReadOnlyDirectReplicaRequest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replication/request/ReadOnlyDirectSingleRowReplicaRequest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java, modules/table/src/test/java/org/apache/ignite/internal/table/RepeatedFinishReadWriteTransactionTest.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/TxAbstractTest.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/InternalTransaction.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/TxManager.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/IgniteAbstractTransactionImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadOnlyTransactionImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadWriteTransactionImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/impl/ReadOnlyTransactionImplTest.java
https://issues.apache.org/jira/browse/IGNITE-19824
=> IGNITE-19824 Implicit RO should be used in implicit single gets

modules/client/src/test/java/org/apache/ignite/client/fakes/FakeTxManager.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/NoOpTransaction.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/InternalTransaction.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/TxManager.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/IgniteAbstractTransactionImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadOnlyTransactionImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/ReadWriteTransactionImpl.java, modules/transactions/src/main/java/org/apache/ignite/internal/tx/impl/TxManagerImpl.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/TxManagerTest.java, modules/transactions/src/test/java/org/apache/ignite/internal/tx/impl/ReadOnlyTransactionImplTest.java
https://issues.apache.org/jira/browse/IGNITE-20590
=> IGNITE-20590 Remove TxManager.beginImplicit()

modules/sql-engine/src/main/codegen/config.fmpp, modules/sql-engine/src/main/codegen/includes/parserImpls.ftl, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlCommitTransaction.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlStartTransaction.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/IgniteSqlStartTransactionMode.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/SqlOtherStatementsTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/sql/SqlTransactionControlParserTest.java
Updates SQL grammar to include `START TRANSACTION` and `COMMIT` statements.
https://issues.apache.org/jira/browse/IGNITE-20442
---- …
=> IGNITE-20442 Sql. Extend grammar with transaction related statements.

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexBuildCompletionListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexBuildTask.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/index/IndexBuilder.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/index/IndexBuilderTest.java
https://issues.apache.org/jira/browse/IGNITE-20621
=> IGNITE-20621 Add a replication group index build completion listener to IndexBuilder

modules/platforms/cpp/ignite/odbc/query/data_query.cpp, modules/platforms/cpp/tests/odbc-test/queries_test.cpp
- Added a test showing an issue;
- Fixed an issue.
=> IGNITE-20625 Fix ODBC metadata reading error

modules/platforms/dotnet/Apache.Ignite.Tests/Table/SchemaSynchronizationTest.cs, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ClusterPerClassIntegrationTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItBuildIndexTest.java
https://issues.apache.org/jira/browse/IGNITE-20635
=> IGNITE-20635 Cleanup code wrt IGNITE-18733 mentions

modules/cli/src/integrationTest/java/org/apache/ignite/internal/rest/ItGeneratedRestClientTest.java, modules/cli/src/testFixtures/resources/cluster-configuration-with-enabled-auth.conf, modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/ItClientHandlerTest.java, modules/client-handler/src/integrationTest/java/org/apache/ignite/client/handler/TestServer.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientHandlerModule.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/ClientInboundMessageHandler.java, modules/client/src/test/java/org/apache/ignite/client/ClientAuthenticationTest.java, modules/client/src/test/java/org/apache/ignite/client/TestClientHandlerModule.java, modules/client/src/test/java/org/apache/ignite/client/TestServer.java, modules/rest/src/integrationTest/java/org/apache/ignite/internal/rest/cluster/ItClusterManagementControllerTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/jdbc/ItJdbcTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/rest/ItInitializedClusterRestTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/rest/ItNotInitializedClusterRestTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/rest/authentication/ItAuthenticationTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/PlatformTestNodeRunner.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/runner/src/test/java/org/apache/ignite/internal/configuration/DistributedConfigurationUpdaterTest.java, modules/security-api/src/main/java/org/apache/ignite/internal/security/authentication/AuthenticationManager.java, modules/security-api/src/main/java/org/apache/ignite/internal/security/authentication/configuration/AuthenticationConfigurationSchema.java, modules/security-api/src/main/java/org/apache/ignite/internal/security/authentication/configuration/validator/AuthenticationProvidersValidatorImpl.java, modules/security-api/src/main/java/org/apache/ignite/internal/security/configuration/SecurityConfigurationSchema.java, modules/security/src/main/java/org/apache/ignite/internal/security/authentication/AuthenticationManagerImpl.java, modules/security/src/test/java/org/apache/ignite/internal/security/authentication/AuthenticationManagerImplTest.java, modules/security/src/test/java/org/apache/ignite/internal/security/authentication/AuthenticationProvidersValidatorImplTest.java, modules/security/src/test/java/org/apache/ignite/internal/security/authentication/StubSecurityViewEvent.java
https://issues.apache.org/jira/browse/IGNITE-20567
=> IGNITE-20567 Move the 'enabled' flag from the authentication configuration to security

modules/page-memory/src/main/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStore.java, modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/persistence/store/FilePageStoreTest.java
https://issues.apache.org/jira/browse/IGNITE-20657
=> IGNITE-20657 At the checkpoint ArrayIndexOutOfBoundsException

modules/platforms/cpp/ignite/odbc/CMakeLists.txt, modules/platforms/cpp/ignite/odbc/query/column_metadata_query.cpp, modules/platforms/cpp/ignite/odbc/query/primary_keys_query.cpp, modules/platforms/cpp/ignite/odbc/query/primary_keys_query.h, modules/platforms/cpp/ignite/odbc/query/query.h, modules/platforms/cpp/ignite/odbc/query/table_metadata_query.cpp, modules/platforms/cpp/ignite/odbc/sql_statement.cpp, modules/platforms/cpp/ignite/odbc/sql_statement.h, modules/platforms/cpp/ignite/protocol/client_operation.h, modules/platforms/cpp/tests/odbc-test/api_robustness_test.cpp, modules/platforms/cpp/tests/odbc-test/meta_queries_test.cpp
- Ported code from Ignite 2;
- Re-used JDBC protocol messages to implement the functionality;
- Un-commented related tests;
- Added new tests to check new functionality.
=> IGNITE-19219  Implement primary keys query in ODBC

modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNode.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/TxAbstractTest.java
https://issues.apache.org/jira/browse/IGNITE-20366
=> IGNITE-20366 testBatchReadPutConcurrently failed

modules/api/src/main/java/org/apache/ignite/table/RecordView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientRecordBinaryView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientRecordView.java, modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientTupleSerializer.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeInternalTable.java, modules/platforms/cpp/tests/client-test/key_value_binary_view_test.cpp, modules/platforms/cpp/tests/client-test/key_value_view_test.cpp, modules/platforms/cpp/tests/client-test/record_binary_view_test.cpp, modules/platforms/cpp/tests/client-test/record_view_test.cpp, modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItInternalTableTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItRoReadsTest.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/UpdatableTableImpl.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItColocationTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/InternalTable.java, modules/table/src/main/java/org/apache/ignite/internal/table/RecordBinaryViewImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/RecordViewImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/storage/RowBatch.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/storage/InternalTableImplTest.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/impl/DummyInternalTableImpl.java
https://issues.apache.org/jira/browse/IGNITE-20435
=> IGNITE-20435 Preserve key order in batch opperations (deleteAll, deleteAllExact, insertAll)

modules/runner/src/integrationTest/java/org/apache/ignite/internal/table/ItInternalTableTest.java
https://issues.apache.org/jira/browse/IGNITE-20672
=> IGNITE-20672 Fix compilation

modules/placement-driver/build.gradle, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java, modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/leases/Leases.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/LeaseUpdaterTest.java
https://issues.apache.org/jira/browse/IGNITE-20659
=> IGNITE-20659 Placement driver do not create a lease

modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/DeployMessagingService.java, modules/code-deployment/src/main/java/org/apache/ignite/internal/deployunit/exception/DeploymentUnitReadException.java
https://issues.apache.org/jira/browse/IGNITE-20630
=> IGNITE-20630 Select only available nodes for deployment unit download

modules/placement-driver/src/main/java/org/apache/ignite/internal/placementdriver/LeaseUpdater.java
https://issues.apache.org/jira/browse/IGNITE-20693
=> IGNITE-20693 Fixed NPE in placement driver actor on deactivation

modules/rest/src/main/java/org/apache/ignite/internal/rest/cluster/ClusterManagementRestFactory.java
https://issues.apache.org/jira/browse/IGNITE-20695
=> IGNITE-20695 Cleanup resource

modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/BaseIgniteAbstractTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
https://issues.apache.org/jira/browse/IGNITE-20699
=> IGNITE-20699 Decrease idle safe time propagation period in tests

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java
https://issues.apache.org/jira/browse/IGNITE-20702
=> IGNITE-20702 NPE in ReplicaManager.onReplicaMessageReceived fixed

modules/cli/src/main/java/org/apache/ignite/internal/cli/config/ini/IniConfigManager.java, modules/cli/src/testFixtures/java/org/apache/ignite/internal/cli/commands/cliconfig/TestConfigManagerHelper.java, modules/code-deployment/src/test/java/org/apache/ignite/deployment/FileDeployerServiceTest.java, modules/core/src/main/java/org/apache/ignite/internal/util/IgniteUtils.java, modules/core/src/main/java/org/apache/ignite/internal/util/OperatingSystem.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/IgniteTestUtils.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/WorkDirectoryExtension.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/deployment/DeployFile.java
https://issues.apache.org/jira/browse/IGNITE-20704
=> IGNITE-20704 Add methods to fsync files and directories

modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/BaseIgniteAbstractTest.java, modules/placement-driver/src/test/java/org/apache/ignite/internal/placementdriver/LeaseUpdaterTest.java
https://issues.apache.org/jira/browse/IGNITE-20703
=> IGNITE-20703 LeaseUpdaterTest causes a NullPointerException

modules/client/src/main/java/org/apache/ignite/internal/client/table/ClientKeyValueBinaryView.java
https://issues.apache.org/jira/browse/IGNITE-20684
=> IGNITE-20684 Use proper sync method

modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedCleanupRecoveryTest.java, modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTxDistributedTestSingleNodeNoCleanupMessage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/TransactionStateResolver.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerIndexLockingTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java, modules/table/src/testFixtures/java/org/apache/ignite/internal/table/TxAbstractTest.java
https://issues.apache.org/jira/browse/IGNITE-20560
**This is just a draft that is used to highlight the described issue. Feel free to cancel it if no longer needed.** …
=> IGNITE-20560 remove the field out of sync with the map

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlOperatorsTest.java
=> IGNITE-20726: Fix incorrect link that mentions a closed ticket.

modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java, modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZonesUtil.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerConfigurationChangesTest.java, modules/distribution-zones/src/test/java/org/apache/ignite/internal/distributionzones/DistributionZoneManagerLogicalTopologyEventsTest.java, modules/distribution-zones/src/testFixtures/java/org/apache/ignite/internal/distributionzones/DistributionZonesTestUtil.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/distribution/zones/ItIgniteDistributionZoneManagerNodeRestartTest.java
https://issues.apache.org/jira/browse/IGNITE-20561
=> IGNITE-20561 Change condition for DistributionZonesUtil#triggerKeyConditionForZonesChanges to solve inconsistency issues

examples/README.md
=> IGNITE-20734 Fixed a link to cli doc

modules/runner/src/integrationTest/java/org/apache/ignite/internal/distribution/zones/ItIgniteDistributionZoneManagerNodeRestartTest.java
https://issues.apache.org/jira/browse/IGNITE-20739
=> IGNITE-20739 fix compilation after merge of IGNITE-20561

modules/catalog/src/main/java/org/apache/ignite/internal/catalog/CatalogManagerImpl.java, modules/core/src/testFixtures/java/org/apache/ignite/internal/testframework/BaseIgniteAbstractTest.java, modules/metastorage/src/integrationTest/java/org/apache/ignite/internal/metastorage/impl/ItMetaStorageWatchTest.java, modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/server/persistence/RocksDbKeyValueStorage.java
https://issues.apache.org/jira/browse/IGNITE-20741
=> IGNITE-20741 Use correct timestamps on MetaStorage recovery

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/QueryTransactionWrapper.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/util/QueryCheckerTest.java, modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/engine/util/QueryChecker.java, modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/engine/util/QueryCheckerFactory.java, modules/sql-engine/src/testFixtures/java/org/apache/ignite/internal/sql/engine/util/QueryCheckerImpl.java
=> IGNITE-20743 Sql. QueryChecker doesn't check results

modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestBuilders.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestClusterTest.java, modules/sql-engine/src/test/java/org/apache/ignite/internal/sql/engine/framework/TestNode.java
Enables registration of system views on a test cluster (see TestBuilders).
https://issues.apache.org/jira/browse/IGNITE-20455
--- …
=> IGNITE-20455: Sql. Test Framework. Add System View support

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/ExecutionServiceImpl.java
https://issues.apache.org/jira/browse/IGNITE-20755
=> IGNITE-20755 Do not use join() in ExecutionServiceImpl#stop()

modules/replicator/src/main/java/org/apache/ignite/internal/replicator/ReplicaManager.java, modules/replicator/src/main/java/org/apache/ignite/internal/replicator/exception/ExpectedReplicationException.java, modules/table/src/main/java/org/apache/ignite/internal/table/AbstractTableView.java, modules/table/src/main/java/org/apache/ignite/internal/table/RecordBinaryViewImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/InternalSchemaVersionMismatchException.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/SchemaCompatValidator.java, modules/table/src/test/java/org/apache/ignite/internal/table/KeyValueBinaryViewOperationsTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/KeyValueViewOperationsTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/RecordBinaryViewOperationsTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/RecordViewOperationsTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerIndexLockingTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/replication/PartitionReplicaListenerTest.java, modules/table/src/testFixtures/java/org/apache/ignite/distributed/ItTxTestCluster.java
https://issues.apache.org/jira/browse/IGNITE-20715
=> IGNITE-20715 Check that versions of tuples sent to PartitionReplicaListener match tx-bound schema version

modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java
https://issues.apache.org/jira/browse/IGNITE-20709
=> IGNITE-20709 Disable ItIgniteNodeRestartTest#nodeWithDataTest

modules/api/src/main/java/org/apache/ignite/sql/Session.java, modules/client-handler/src/main/java/org/apache/ignite/client/handler/requests/sql/ClientSqlExecuteRequest.java, modules/client/src/main/java/org/apache/ignite/internal/client/sql/ClientSessionBuilder.java, modules/client/src/test/java/org/apache/ignite/client/fakes/FakeSessionBuilder.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/api/SessionBuilderImpl.java
https://issues.apache.org/jira/browse/IGNITE-20687
=> IGNITE-20687 Exclude IgniteTransactions from SQL session creation API

modules/table/src/integrationTest/java/org/apache/ignite/distributed/ItTablePersistenceTest.java, modules/table/src/integrationTest/java/org/apache/ignite/internal/table/ItColocationTest.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/StorageUpdateHandler.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableMessageGroup.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/command/TimedBinaryRowMessage.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/command/UpdateAllCommand.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/command/UpdateCommand.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/raft/PartitionListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/PartitionReplicaListener.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/replicator/TimedBinaryRow.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/IndexBaseTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/StorageUpdateHandlerTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/command/PartitionRaftCommandsSerializationTest.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/raft/PartitionCommandListenerTest.java
https://issues.apache.org/jira/browse/IGNITE-20609
=> IGNITE-20609 Move last commit timestamp into BinaryRowMessage

modules/table/src/main/java/org/apache/ignite/internal/table/distributed/PartitionReplicatorNodeRecovery.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java
https://issues.apache.org/jira/browse/IGNITE-20767
=> IGNITE-20767 Move code related to recovering volatile RAFT groups out of TableManager

modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/rel/HashAggregateNode.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/Commons.java
=> IGNITE-18702 Sql. Update nativeTypePrecision and nativeTypeScale to use constants from ColumnMetadata

modules/runner/src/testFixtures/java/org/apache/ignite/internal/Cluster.java
https://issues.apache.org/jira/browse/IGNITE-20776
=> IGNITE-20776 Stop nodes in parallel on Cluster shutdown

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItFunctionsTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItSqlOperatorsTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/datatypes/varbinary/ItVarBinaryExpressionTest.java, modules/runner/src/integrationTest/sql/types/string/test_unicode.test_ignored, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/IgniteSqlFunctions.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/exec/exp/RexImpTable.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/sql/fun/IgniteSqlOperatorTable.java, modules/sql-engine/src/main/java/org/apache/ignite/internal/sql/engine/util/IgniteMethod.java
=> IGNITE-20660 SQL: broken behaviour of OCTET_LENGTH function

build.gradle, modules/core/src/main/java/org/apache/ignite/internal/util/FeatureChecker.java, modules/raft/src/main/java/org/apache/ignite/internal/raft/storage/logit/LogitLogStorageFactory.java, packaging/common/bootstrap-functions.sh, packaging/db/build.gradle
https://issues.apache.org/jira/browse/IGNITE-20777
=> IGNITE-20777 Fix IllegalAccessException on Java 17 (at least)

modules/runner/src/integrationTest/java/org/apache/ignite/internal/rebalance/ItRebalanceDistributedTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteInMemoryNodeRestartTest.java, modules/runner/src/integrationTest/java/org/apache/ignite/internal/runner/app/ItIgniteNodeRestartTest.java, modules/runner/src/main/java/org/apache/ignite/internal/app/IgniteImpl.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/PartitionReplicatorNodeRecovery.java, modules/table/src/main/java/org/apache/ignite/internal/table/distributed/TableManager.java, modules/table/src/test/java/org/apache/ignite/internal/table/distributed/TableManagerTest.java
https://issues.apache.org/jira/browse/IGNITE-20301
=> IGNITE-20301 Fix flaky tests in ItIgniteInMemoryNodeRestartTest

modules/raft/src/main/java/org/apache/ignite/internal/raft/server/impl/JraftServerImpl.java
https://issues.apache.org/jira/browse/IGNITE-20786
=> IGNITE-20786 Disable Logit log storage by default

modules/runner/src/integrationTest/java/org/apache/ignite/internal/sql/engine/ItBuildIndexOneNodeTest.java
https://issues.apache.org/jira/browse/IGNITE-20794
=> IGNITE-20794 Fix build

DEVNOTES.md, modules/rest-api/openapi/docker-compose.yml, modules/rest-api/openapi/openapi.yaml, modules/rest-api/src/main/java/org/apache/ignite/internal/rest/api/Definition.java, modules/rest/src/main/java/org/apache/ignite/internal/rest/RestComponent.java
https://issues.apache.org/jira/browse/IGNITE-20783
* docker-compose file added
* security schema defined in openapi.yaml
* CORS enabled for Authorization header …
=> IGNITE-20783 Add Swagger UI docker-compose

modules/network/src/integrationTest/java/org/apache/ignite/internal/network/netty/ItConnectionManagerTest.java, modules/network/src/main/java/org/apache/ignite/internal/network/recovery/RecoveryClientHandshakeManager.java
https://issues.apache.org/jira/browse/IGNITE-20793
=> IGNITE-20793 Fix flaky ItConnectionManagerTest#testShutdown
